### PR TITLE
Added cleels

### PR DESCRIPTION
**Pull request by misterghast**
## About The Pull Request
added clown heels. they do not have a proper sprite yet because everything is terrible.

## Why It's Good For The Game
please i need this

## Changelog

:cl: Ghasterino
add: added clown heels. they squeak and waddle
/:cl:

### CODE REVIEW

**Comment by misterghast** [comment]
i forgor to test it...

**Comment by misterghast** [comment]
commit has been pushed. has actually been tested now

**Comment by ReturnToZender** [comment]
They need to have a sprite to be merged Ghast

**Comment by StrangeWeirdKitten** [comment]
yeah, I need a sprite.

**Comment by StrangeWeirdKitten** [comment]
Stale, feel free to reopen with the requested changes

**Pull request closed without merging**
