### PR TITLE
better interdyne (this time its good)

### PR DESCRIPTION
**Pull request by kaylexis**
## About The Pull Request

alright so this time i didnt make it huge and scrunched it as much as i could
NO PIPE ERRORS!! i hope. i tested it and it should work 
## Changelog
:cl:
fix: interdyne no longer relies off of a debug smes
add: syndicate fax machine
add: more specialized roles/sleepers
add: turbine and atmos
fix: squished the entire place a good bit
removed: shaft miner sleepers
removed: (in icebox) extra like 10 sleepers because for some reason that was a thing
/:cl:

### CODE REVIEW

**Comment by kaylexis** [comment]
someone please run checks because if theres another obscure error regarding pipes or doors im going to go mad

**Comment by projectkepler-ru** [comment]
fucking defcon 1 on this shit I need all hands on deck
@mcmeiler  @ReturnToZender  @Cyprex  @NullDagaf 
need all of you to give opinion

**Comment by mcmeiler** [comment]
As long as this doesn't add more sleepers in total, sure.

**Comment by kaylexis** [comment]
> As long as this doesn't add more sleepers in total, sure.

doesnt add more, removes a ton in icebox but mostly replaces existing ones with some DS-2 sleepers

**Comment by ReturnToZender** [comment]
> fucking defcon 1 on this shit I need all hands on deck @mcmeiler @ReturnToZender @Cyprex @NullDagaf need all of you to give opinion

Smaller Interdyne is better. It fits more neatly into the map, while having the same things. Interdyne has 7 players max, so I feel it should be compact, so it doesn't feel empty. Current Interdyne can really feel that way.

As long as it has the same number of sleepers, I don't mind, yes-- but I also like how small the TG/SPLURT Syndicate base _feels._ You really feel like a small group of Syndicate agents hiding out on lavaland.
That's pretty nebulous, but I hope that whatever version of the Syndicate base comes next, it matches that feeling.

**Review by KathrinBailey — CHANGES_REQUESTED** [review]
Use no diagonal walls around the bomb vault to prevent this weirdness with the firelocks.
image

**Comment by KathrinBailey** [comment]
Also just wanna make it clear that this is only a temporary fix, Interdyne needs to be remade from scratch.
I'm willing to accept it, still, but like I said. Temporary fix.

**Comment by kaylexis** [comment]
> Also just wanna make it clear that this is only a temporary fix, Interdyne needs to be remade from scratch. I'm willing to accept it, still, but like I said. Temporary fix.

yeah, i'll be doing that later, but this is just to satisfy the interdyne people for now
as currently the layout forces it to have a lot of useless space that could make it smaller

**Comment by projectkepler-ru** [comment]
test merge didn't work x-x

**Comment by K4rlox** [comment]
unmerge
1. apcs dont work and are not wired correctly
2. there are no shaft miner cryopods and THERES SCIENTIST PODS AT THE FUCKING MINER DORMS
3. theres a WALL behind the bolted vault door
4. theres no mining gear, theres a single pickaxe on a rack and thats it
5. theres no mining satchels anywhere
6. SMES dont work because its not wired correctly
7. Turbine is broken and unable to set up

overall, unmerge this shit, its very fucking badly made and does not work

**Comment by kaylexis** [comment]
> unmerge
> 
> 1. apcs dont work and are not wired correctly
> 2. there are no shaft miner cryopods and THERES SCIENTIST PODS AT THE FUCKING MINER DORMS
> 3. theres a WALL behind the bolted vault door
> 4. theres no mining gear, theres a single pickaxe on a rack and thats it
> 5. theres no mining satchels anywhere
> 6. SMES dont work because its not wired correctly
> 7. Turbine is broken and unable to set up
> 
> overall, unmerge this shit, its very fucking badly made and does not work

its called a testmerge for a reason im fixing all the issues
please use constructive critizism and don't yell at me because you can't handle that something has issues

**Comment by kaylexis** [comment]
hey guys i fixed it

**Comment by NullDagaf** [comment]
> its called a testmerge for a reason im fixing all the issues please use constructive critizism and don't yell at me because you can't handle that something has issues

It is constructive though.

**Comment by projectkepler-ru** [comment]
map screenshot please?

**Comment by nevimer** [comment]
poke me and ill reopen if you are working on it again

**Pull request closed without merging**
