### PR TITLE
Even more plant gene editor fixes (WIP)

### PR DESCRIPTION
**Pull request by shellspeed1**
## About The Pull Request

While working with the plant gene editor I noticed that were were having issues with it not actually improving for new parts. I also noticed that stat genes were not editable for whatever reason. So far I have the first issue fixed but I need to still figure out the second. Once finished this will fix both.

## Why It's Good For The Game

I like it when stuff works.

## Proof Of Testing

Can currently copy genes to disks at right values, cannot put them back in for stats.

## Changelog

:cl:
fix: Plant gene editor works again.
/:cl:

### CODE REVIEW

**Comment by Majkl-J** [comment]
Bonus points if you manage to look into https://github.com/Bubberstation/Bubberstation/issues/1290, if it even still is valid

**Comment by shellspeed1** [comment]
I probably won't be finishing this for another week or two as I have a CPA exam on monday than a trip. The suffering is REAL.

**Comment by Majkl-J** [comment]
> I probably won't be finishing this for another week or two as I have a CPA exam on monday than a trip. The suffering is REAL.

take your time

**Comment by shellspeed1** [comment]
Closing this as it looks like we just want to axe it for now.

**Pull request closed without merging**
