### PR TITLE
EVA suit resprite

### PR DESCRIPTION
**Pull request by Bamhalazam**
## About The Pull Request

It's an EVA suit resprite. Simple as.

## Why It's Good For The Game

I'm not a great spriter, HOWEVER the ancient suits irk me. New sprites:

image
image
image

## Changelog

:cl:

image: added/modified/removed some icons or images

/:cl:

### CODE REVIEW

**Comment by Bamhalazam** [comment]
now compatible with digitigrades too

**Comment by nevimer** [comment]
Screenshot of the digi?

**Comment by Bamhalazam** [comment]
image
image

digi gang shit

**Comment by nevimer** [comment]
the file edits are nonmodular and need to be in our modular folders, and you can override the base object there aswell

**Comment by ReturnToZender** [comment]
This looks sexy as fuck, you've got my 👍, just make it modular

**Comment by zeroisthebiggay** [comment]
not too fond of the medbay color scheme
maybe an orange stripe would be more industrial

**Pull request closed without merging**
