### PR TITLE
Replaces the Wizard's High Frequency Blade because I saw Merek get gibbed by it once.

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Replaces the High Frequency Blade the wizard gets with a REAL banhammer, and reduces the spell cost from 3 to 2.
Adds REAL banhammers send people to the void temporarily (similar to immortality talisman or void genetic power) on hit. Hitting someone on combat mode with it sends them to permabrig instead, if they're not already in the permabrig.

## Why It's Good For The Game

Lets look at what the High Frequency blade does:
- 100% block chance against projectiles if wielded.
- 50% block chance against melee attacks if wielded.
- 25% block chance otherwise.
- Average case 17 damage per hit, best case 36 damage per hit.
- +20 wound bonus.
- +25 bare wound bonus.
- Attack cooldown of 0.1 seconds (!!!)
- Gibs dead people on hit (very high chance to).
- Deconstructs walls on hit.
- https://www.youtube.com/watch?v=SYUHaf0BxFo

Very insane funny weapon that is way too powerful. This PR replaces that weapon with a funny banhammer that sends people to perma brig or the void instead.

## Proof Of Testing

image

image

## Changelog

:cl: BurgerBB
add: Adds REAL banhammers send people to the void temporarily (similar to immortality talisman or void genetic power) on hit. Hitting someone on combat mode with it sends them to permabrig instead, if they're not already in the permabrig.
del: Replaces the High Frequency Blade the wizard gets with a REAL banhammer, and reduces the spell cost from 3 to 2.
/:cl:

### CODE REVIEW

**Comment by theselfish** [comment]
Make it a mono-colour blue stunstick for maximum gmod rp.

**Review by Majkl-J — CHANGES_REQUESTED** [review]
Just remove the gib from it, and remove the long range block chance

**Comment by BurgerLUA** [comment]
> Just remove the gib from it, and remove the long range block chance

Out of the scope of the PR at this point considering the replacement has already been made, and it is my personal opinion that the weapon itself isn't salvageable for wizard.

**Comment by nevimer** [comment]
I think it's a pretty funny re-think

**Comment by BurgerLUA** [comment]
I mean if another PR was open to rework the blade I can modify this PR to just be another spellblade.

**Comment by Majkl-J** [comment]
> I mean if another PR was open to rework the blade I can modify this PR to just be another spellblade.

That's also fine tbh

**Review by Majkl-J — APPROVED** [review]
Eh if anyone wants to put the spellblade back they can it's not like wizard is enabled for us to know

**Pull request merged**
