### PR TITLE
improves the corporate AI lawset because I think it's bad

### PR DESCRIPTION
**Pull request by Swiftfeather**
## About The Pull Request

Changes corporate AI law 2 from "The station and its equipment is expensive to replace." to "The station, its equipment, and its resources are expensive to replace."

## Why It's Good For The Game

I spend so much time dealing with regs and laws at work trust me this is a better and clearer implementation in the spirit of the corporate lawset.

## Proof Of Testing

I tested it in my brain and I think it'll work

## Changelog

:cl:Swiftfeather
balance: Tweaked corporate AI law #2.
/:cl:

### CODE REVIEW

**Comment by StrangeWeirdKitten** [comment]
I'm not going to entirely be the arbiter of shutting law changes down, that'll be for the staff like K3 to decide, but I geniually have the opinion it doesn't make much of a signifigant diffrence. Why?

Laws, outside of fundimental restructures (like adding exceptions, removing exceptions, or changing concepts), does not really show any diffrence. Most silicons will just treat the law the same, because it's already practically the same thing. Just with an added word. Now the issue stems from the occasional poor silicon player? Well, laws don't fix shitty borg players. But that's my input regarding this. But hey, if the higher staff like it, then it'll get merged.

**Comment by projectkepler-ru** [comment]
> I'm not going to entirely be the arbiter of shutting law changes down, that'll be for the staff like K3 to decide, but I geniually have the opinion it doesn't make much of a signifigant diffrence. Why?
> 
> Laws, outside of fundimental restructures (like adding exceptions, removing exceptions, or changing concepts), does not really show any diffrence. Most silicons will just treat the law the same, because it's already practically the same thing. Just with an added word. Now the issue stems from the occasional poor silicon player? Well, laws don't fix shitty borg players. But that's my input regarding this. But hey, if the higher staff like it, then it'll get merged.

do note that specific wording do matter. There's a reason why silicon laws are not just flawed, but kept that way.

**Comment by Majkl-J** [comment]
You named your commit, "rawr"

**Review by Majkl-J — CHANGES_REQUESTED** [review]
Anyhow, show me those bubber edit comments

**Comment by YakumoChen** [comment]
Should take it to tg but
Laws should be kept simple on purpose, interpretation is the secret sauce of good AI rounds

**Comment by StrangeWeirdKitten** [comment]
oh this is the corporate lawset, I should probally actually look at the code before i make comments.

**Comment by Swiftfeather** [comment]
> You named your commit, "rawr"

Sometimes dragons just gotta rawr



> Anyhow, show me those bubber edit comments

It is there?? 
`		"The station, its equipment, and its resources are expensive to replace.",//BUBBER edit original "The station and its equipment is expensive to replace."`

**Comment by StrangeWeirdKitten** [comment]
I asked the staff and they basically already discussed and said what I said before I even said it. It's not really a change that will do anything, on a non-standard lawset (that's already kind of designed @projectkepler-ru and @YakumoChen said).

**Comment by projectkepler-ru** [comment]
> I asked the staff and they basically already discussed and said what I said before I even said it. It's not really a change that will do anything, on a non-standard lawset (that's already kind of designed @projectkepler-ru and @YakumoChen said).

whichi s fne :P

**Pull request closed without merging**
