### PR TITLE
Makes surgery slightly less free

### PR DESCRIPTION
**Pull request by Superhats**
## About The Pull Request
This reverts one of the two skyrat buffs to surgery speed, specifically the one from having no patient near you. 
This conserves the buff for doing surgery with numbing to encourage not doing floor surgery.
image

## Why It's Good For The Game
In the current medical ecosystem, wound tending has become the de-facto go-to for most injuries, due to being extremely quick, and requiring zero resources. A lot of doctors completely ignore chems as a result.

This buff that skyrat made is in large part to blame, as people have become so reliant on it that most people think having someone near you is a _debuff_ to your surgery speed. 

This PR makes surgery significantly slower to encourage the use of alternative methods such as chems. or even the use of things like miner's salve/sterilizine, which provide a flat buff to surgery speed. I ran a poll in #Suggestions and people seem to be mostly on-board with it.

## Proof Of Testing
image

## Changelog

:cl:VrazzleDazzle
balance: Surgery no longer receives a significant speed buff for being alone.
/:cl:

### CODE REVIEW

**Comment by sneksnek** [comment]
7w4700

**Comment by AllCorruptingWyrm** [comment]
medical is the last department that needs a nerf, why??

**Comment by Superhats** [comment]
> medical is the last department that needs a nerf, why??

This isn't to nerf medical, it's to force medical to use other tools like chemistry to treat injuries. Currently surgery is just the all around best option for everything.

**Comment by nevimer** [comment]
I'd argue chemistry is too strong - nothing stops you from super-soldiering everything if you just constantly consume reagents.

**Comment by Superhats** [comment]
Chemistry is extremely strong, yes. But so is being able to fix 200 brute damage in a couple dozen seconds with zero resources, in my opinion.

**Comment by Majkl-J** [comment]
I don't know how to feel about this, on one way it will make chemistry more prevalent (Something they can just achieve by putting the chems out front on a table and let the crew self-serve), on the other it will seriously penalize our playerbase which already possesses a lower skill ceiling and are really easily overwhelmed. 

Especially since this trades a 2x multiplier to the speed, saying to use either a 1.1 or 1.2 one instead, which is abysmal and really doesn't make the chems any more worth it. I'll leave that to other maintainers to decide, we could give it a shot as a TM in the meanwhile.

**Comment by Superhats** [comment]
> I don't know how to feel about this, on one way it will make chemistry more prevalent (Something they can just achieve by putting the chems out front on a table and let the crew self-serve), on the other it will seriously penalize our playerbase which already possesses a lower skill ceiling and are really easily overwhelmed.
> 
> Especially since this trades a 2x multiplier to the speed, saying to use either a 1.1 or 1.2 one instead, which is abysmal and really doesn't make the chems any more worth it. I'll leave that to other maintainers to decide, we could give it a shot as a TM in the meanwhile.

The modifier is now 1.5x instead of 2x. Currently surgery has two separate buffs, for doing surgery with numbing (0.5x) and for doing surgrey alone (another 0.5x)

**Comment by sneksnek** [comment]
> medical is the last department that needs a nerf, why??

medical has been subject to egregious powercreep by skyrat/nova. medical is the one department that DOES need adjusted to eliminate poor mechanics

> I'd argue chemistry is too strong - nothing stops you from super-soldiering everything if you just constantly consume reagents.

with the damage output of guns and melee, chemistry doesn't allow one to simply eat tons of damage. libital + salicylic is 4 brute/second. save for a couple chems (and the skyrat chems that should be removed since they're unabashedly op), you'll still need to play well to win combat

> I don't know how to feel about this, on one way it will make chemistry more prevalent (Something they can just achieve by putting the chems out front on a table and let the crew self-serve), on the other it will seriously penalize our playerbase which already possesses a lower skill ceiling and are really easily overwhelmed.
> 
> Especially since this trades a 2x multiplier to the speed, saying to use either a 1.1 or 1.2 one instead, which is abysmal and really doesn't make the chems any more worth it. I'll leave that to other maintainers to decide, we could give it a shot as a TM in the meanwhile.

we already have issues with new doctors refusing to learn or understand chemistry. buffing surgery to make some chemicals obsolete so they're less incentivized to learn chemistry is counterproductive to encouraging doctors to get better. one can argue that medical is already forgiving enough anyways

**Comment by destrucktoid** [comment]
Snek makes a valid point. People don't bother to learn things that aren't either fun or useful and for most people, chems just aren't useful when they can just use funny surgery to take people from 269 brute to full HP in about 5 seconds flat. Don't get me wrong, Nevimer is right that chems are extremely good _If you know how and when to use them_, the problem is that as Majkl pointed out, Bubbers playerbase has a lower skill ceiling; i would counter this by saying that by removing this handhold mechanic in the form of super buffed surgery and rewarding people for actually learning chems you will raise the skill ceiling. Ironically, handholding people who aren't very skilled and helping them out with nice and easy mechanics doesn't make them get better at the game, it just makes them stay static and refuse to learn better and more advanced mechanics since what they have is already good enough. Right now medical is in a state where surgery is just your one stop fix everything button and as a result nobody bothers to learn how to properly make and use chemicals.

**Comment by projectkepler-ru** [comment]
I don't know, what do you think? @MrMelbert

**Comment by Majkl-J** [comment]
> I don't know, what do you think? @MrMelbert

Can we not ping melbert about nontechnical stuff

**Comment by Majkl-J** [comment]
> > I don't know how to feel about this, on one way it will make chemistry more prevalent (Something they can just achieve by putting the chems out front on a table and let the crew self-serve), on the other it will seriously penalize our playerbase which already possesses a lower skill ceiling and are really easily overwhelmed.
> > Especially since this trades a 2x multiplier to the speed, saying to use either a 1.1 or 1.2 one instead, which is abysmal and really doesn't make the chems any more worth it. I'll leave that to other maintainers to decide, we could give it a shot as a TM in the meanwhile.
> 
> The modifier is now 1.5x instead of 2x. Currently surgery has two separate buffs, for doing surgery with numbing (0.5x) and for doing surgrey alone (another 0.5x). This only removes the latter.

From what I can see in surgery code, incorrect. The modifier from environment is multiplicative, 0.5 directly doubles the speed. Thus we are turning a 4x buff into a 2x buff (Since surgery and stasis beds both apply numbing the other buff doesnt make any difference for people who are dead/alive, thus I disregarded the numbing buff entirely) The bonus from the chems you mentioned is additive, 1.1 for salve, and 1.2 for sterilizine, and also doesn't stack, not mentioning the fact that these need to be applied on already open surgeries to work, which is not mentioned anywhere for players.

My point is that this only helps make chems prevalent for the cases where the person is alive, and completely gimps any actual revival by slowing it down a fair bit, which isn't really compensated by the chems available.

I also believe the reason people dont use/learn chemistry is because the tg wiki yells at them about pH and whatnot and it makes it seem much more difficult and complicated than it actually is. (You don't need to even consider purity with basic healing chems half the time)

**Comment by YakumoChen** [comment]
I think surgery should be encouraged, it requires another player to do it, something that chemistry wholly can ignore. I think the last thing we should be discouraging is having the doctors do their job.

**Comment by sneksnek** [comment]
> I think surgery should be encouraged, it requires another player to do it, something that chemistry wholly can ignore. I think the last thing we should be discouraging is having the doctors do their job.

understanding and using chemicals to heal people is their job. this argument is flawed anyways and could also be used the other way: the last thing we should be discouraging is chemists doing their job because making healing chemicals is obsolete

**Comment by Cyprex** [comment]
> In the current medical ecosystem, wound tending has become the de-facto go-to for most injuries, due to being extremely quick, and requiring zero resources. A lot of doctors completely ignore chems as a result.

This is specifically intended by upstream tg- anyone can just grab meds from the fridge and swallow them. The only challenge here is stocking up the fridge, which requires very little interaction between players.

On the other hand surgery generally involves a second player(usually medbay staff), and it's advantageous for the patient to strip. 

As such I do think the surgery design is much better. I am still okay with this PR, however, as it reverts a Skyrat buff.

**Comment by YakumoChen** [comment]
> chemistry requires someone to make the chemicals

Yeah, the chemist, who can stock the fridge so that everyone able to walk can largely ignore going inside medbay for the rest of the round

> understanding and using chemicals to heal people is their job.

No it doesn't, the chemfridge is public (and you're encouraged to stock it)

Fast surgery actually makes being a doctor competitive with self-service chemistry

**Comment by Superhats** [comment]
Speaking from experience, even with self-service chemistry, a lot of people default to asking a doctor. And a lot of things _can't_ be self-served, like dead organs and such.

**Comment by Superhats** [comment]
> > Speaking from experience, even with self-service chemistry, a lot of people default to asking a doctor. And a lot of things _can't_ be self-served, like dead organs and such.
> 
> Which is more interactive? Medscanning a patient, injecting them with your hypo, and telling them they're done, or doing surgery?
> 
> Dead organs obviously require surgery irregardless so I don't see how that's relevant

Tend wounds is a whole two surgery steps, it's hardly more interactive.

**Comment by YakumoChen** [comment]
It requires them going further into medbay and having the doctor be more than just a chem dispenser. Chems are just inject and wait

**Comment by Superhats** [comment]
I wouldn't call "Having to walk into the medbay" interactive.

**Comment by YakumoChen** [comment]
This nerfs more than just tend wounds as well besides, and there's still the options like anesthetic

**Comment by YakumoChen** [comment]
The pr body seems pretty disingenuous with a screenshot that literally has a character complain its slow

**Comment by YakumoChen** [comment]
Not to mention the thing you removed encouraged people to actually use the surgery rooms instead of just making triage a bunch of surgery tables

**Comment by Superhats** [comment]
> Not to mention the thing you removed encouraged people to actually use the surgery rooms instead of just making triage a bunch of surgery tables

Except guess what. People **still** didn't use the surgery rooms? They just yell at people to move out of the way?

**Comment by Superhats** [comment]
I'm starting to think you don't actually do medical. The buff very much didn't stop sec from breathing down your neck.

**Comment by YakumoChen** [comment]
My second main is medical so I do have several hundred hours in the role, thanks

The point I'm getting at is the buff encourages roleplay, the only buff you're leaving just encourages patients to... use the table? That they use anyway?

**Comment by YakumoChen** [comment]
Last I checked literally nobody does floor surgery ever, not because it's slow, but because being on a table actually gives you a decent success rate

**Review by Majkl-J — CHANGES_REQUESTED** [review]
I am still concerned about a point I am waiting to actually be addressed: You are removing a **x0.5 multiplier** saying it will incentivize using chems, completely disregarding the fact that sterilizine, the chem it is meant to mainly incentivize, has an abysmal **x0.833 multiplier**, which doesn't really compensate for it, especially for when you have a dead body, or several.

See this fancy desmos graph for information on how each of these affect it:
https://www.desmos.com/calculator/q8voaxkcnz

image

Red line is what effect multiplying by `1-(x*0.1)` does (Analgesia, quiet environment buffs, etc.)
Blue line is what the effect of chems like sterilizine does (using a value of `x*0.1`)

In another words:
image
you are sacrificing the whole area inbetween the green and purple line here, which is a fair bit of a timeloss that still doesn't justify using these chems. Ironically the only reagent with a noticeable effect worth applying is honey, which still only gives a 0,625x multiplier. Doesn't exactly give an incentive when botany can easily do better than a chemist.

Until you either justify how this is actually beneficial with the current changes, or make these chems have an actual effect on surgery capable of replacing the current one, we will be blocking the merge, as the maintainer team currently does not believe this is currently solving the supposed problem.

**Comment by Superhats** [comment]
So. Sterilizine will not return surgery to pre-nerf speed, you're correct. The point of this PR _is_ to slow surgery down, because doctors were defaulting to it even when someone had sub 100 brute and could walk just fine. 

I've personally done surgery on several dead miners with 500-750 damage while the testmerge was running, and thanks to experimental wound tending, it was still extremely quick to get them to a point where you can defib them, taking about 20-30 seconds if I had to give a rough estimate. However, thanks to tend wounds' diminishing returns at lower damage value, once you reach the 100-50 damage ballpark, it becomes more worthwhile to just slap some libital on them.

**Comment by StrangeWeirdKitten** [comment]
> So. Sterilizine will not return surgery to pre-nerf speed, you're correct. The point of this PR _is_ to slow surgery down, because doctors were defaulting to it even when someone had sub 100 brute and could walk just fine.
> 
> I've personally done surgery on several dead miners with 500-750 damage while the testmerge was running, and thanks to experimental wound tending, it was still extremely quick to get them to a point where you can defib them, taking about 20-30 seconds if I had to give a rough estimate. However, thanks to tend wounds' diminishing returns at lower damage value, once you reach the 100-50 damage ballpark, it becomes more worthwhile to just slap some libital on them.

This is really just a nerf for the sake of a nerf when honestly, there won't be some massive incentive just by removing the alone bonus. It takes player agency to set up things like treatment surgical tables. Most chemists who make chemicals are still highly useful. Blood factories. Synthflesh factories. Patches for the overall crew to use. Is there not much of a need? Sure, but you're going to have to actually look into the reagents and see what needs adjustment. A simple code block comment PR is not going to cut it. You can look for ways to loop in chemistry into the surgical process.

In this current state, the PR is denied. But I've went ahead and moved it to a draft if you wish to expand on the scope.

**Comment by Superhats** [comment]
Fair enough. Anything else is outside the scope of my abiltiies as a coder so I'm gonna go ahead and close this.

**Comment by Majkl-J** [comment]
> So. Sterilizine will not return surgery to pre-nerf speed, you're correct. The point of this PR is to slow surgery down, because doctors were defaulting to it even when someone had sub 100 brute and could walk just fine.

Doctors aren't really required to know anything beyond what which chem does, and surgery is the main interaction they get. If you want people to use chems you don't need to interact. You either spray a single arrow toward the stocked chemfridge, or stock pills upfront on tables in front of medbay, and let people self serve. 

In my experience with using the above it isn't that people don't want to use them, but that they are blind and don't want to bother checking if there even is a chemist, let alone try to ask for chems. This fact won't change unless you sit up at the front desk, actively making chems. If you want chems to be used more by MDs, you make them beneficial for the stuff they are mainly meant to be doing (Surgery), not nerf surgery in order to push using chems more, as that empowers another job without improving the interaction between the two.

> I've personally done surgery on several dead miners with 500-750 damage while the testmerge was running, and thanks to experimental wound tending, it was still extremely quick to get them to a point where you can defib them, taking about 20-30 seconds if I had to give a rough estimate. However, thanks to tend wounds' diminishing returns at lower damage value, once you reach the 100-50 damage ballpark, it becomes more worthwhile to just slap some libital on them.

This is a healthy interaction where a doctor depends on another department (Science) to improve their work. Surgery is the main interaction point for MDs, and making chems is a main (interaction, rarely) point of chemists. Giving the two interaction by incentivizing chems for surgery is preferable for player interaction, compared to just diminishing the one for the benefit of the other.

I personally feel like the nerf to surgery speeds CAN be there, but making the effect of surgery speedup chems stronger, and maybe instead of removing one buff making SURGERY_SPEEDUP_AREA equal to 0.7, keeping both analgesia and silent surgery as mechanics, albeit weaker, is probably a better way to go about making chemistry more prevalent

**Comment by sneksnek** [comment]
> > chemistry requires someone to make the chemicals
> 
> Yeah, the chemist, who can stock the fridge so that everyone able to walk can largely ignore going inside medbay for the rest of the round

your argument was that surgery required another person to perform. the same can be said for chemistry. human input is needed to make chemicals

> > understanding and using chemicals to heal people is their job.
> 
> No it doesn't, the chemfridge is public (and you're encouraged to stock it)

you're supposed to use chemicals as a doctor. you're surrounded by chemicals roundstart. the kits have a variety of chemicals with labels explaining their use. doctors are absolutely supposed to understand how chemicals function and make use of them. chemicals are also not arbitrarily limited to only being dispensed through the fridge. many do not understand what a chemical will do and will go to a doctor for help

> Fast surgery actually makes being a doctor competitive with self-service chemistry

surgery already has its place and was fast enough with upgrades to be 'competitive' with chemistry

> This is really just a nerf for the sake of a nerf when honestly, there won't be some massive incentive just by removing the alone bonus. It takes player agency to set up things like treatment surgical tables. Most chemists who make chemicals are still highly useful. Blood factories. Synthflesh factories. Patches for the overall crew to use. Is there not much of a need? Sure, but you're going to have to actually look into the reagents and see what needs adjustment. A simple code block comment PR is not going to cut it. You can look for ways to loop in chemistry into the surgical process.

The buff is poorly designed. The original practice of overcrowding a surgery area wasn't actually nerfed, the speeds were kept the same. Players are instead given a significant benefit for fulfilling a trivial condition. It was the wrong solution to a problem. Due to this, it's a buff to surgery when it wasn't necessary. We shouldn't be adjusting other elements around something that was poorly designed. This can lead to blatant powercreep, since one thing was buffed superfluously, other things may become buffed to compensate. We already see this because of deforest, but that's another can of worms for another PR.

For the latter part: chemistry still has its place but its usefulness is further being made obsolete. There is a notorious issue of doctors refusing to understand chemistry and this will further disincentive them. As already addressed, this is somewhat due to the tg wiki poorly explaining how chemistry works with an obtuse amount of verbosity, but I have also seen doctors outright reject using chemicals due to refusing to understand how they work rather than how they're made. If surgery is inherently as fast/faster than chemicals, then they have no reason to learn how chemicals work.

Overall I view it as a needless buff that can lead to potentially worse design in the future. I have some qualms with buffing surgery-boosting chemicals since I thought they were beneficial enough already. I also think it would be bad to be viewed as a 'compensation' for the removal of a buff that shouldn't have been implemented in the first place.

**Pull request closed without merging**
