### PR TITLE
Better airlock sounds QOL

### PR DESCRIPTION
**Pull request by pixelkitty286**
## About The Pull Request
Ports Citrp's airlock sounds and makes all airlocks have better sounds than they used to.

## Why It's Good For The Game

Every door sound is the same boring door sound and all sound the exactly same even though each door is different. In other words the door sounds I've got sound more aesthetically pleasing compared to "*SHHH*" "*SHHH CLUNK*".

## Proof Of Testing

https://github.com/Bubberstation/Bubberstation/assets/78038207/246abdf4-35c3-43de-a3a6-074a67865a44

https://github.com/Bubberstation/Bubberstation/assets/78038207/5a40e67c-cada-44f2-882f-474a4d60de0f

https://github.com/Bubberstation/Bubberstation/assets/78038207/a1d9e0df-f29c-48de-bbff-89c9896b7a66

https://github.com/Bubberstation/Bubberstation/assets/78038207/d8d13c8d-14c3-432f-b33c-a07b98c747e0

## Changelog

:cl:
add: Door sounds from Citrp
qol: Better door sounds
sound: added door sound files in modular sounds folder
code: Disabled skyrat's door sound over rides in airlock.dm
/:cl:

### CODE REVIEW

**Review by Majkl-J — COMMENTED** [review]
Some of these sound a bit over the top, but most are fine (Also love the shuttle ones holy shit)

**Review by Majkl-J — CHANGES_REQUESTED** [review]
First testmerge results: Sounds can be too disruptive or long. Suggesting using audacity to lower the peak of these. Also cut out the beeps at the end of some of the longer ones.

**Comment by pixelkitty286** [comment]
> First testmerge results: Sounds can be too disruptive or long. Suggesting using audacity to lower the peak of these. Also cut out the beeps at the end of some of the longer ones.

need specific sounds that have the issues to know what needs changed.

**Comment by nevimer** [comment]
These sounds were great on citadel.

**Comment by coffeecoffeecoffee** [comment]
These are fucking horrendous, and they activate a sound hypersensitivity of mine. If you port these, I legit won't be able to play anymore. I suppose that makes me biased, but please don't - they're fucking horrible and sound like rusty pitchforks on glass.

**Comment by Edgar-Allan-ShitPoest** [comment]
This is also not a good addition having these door sounds isn't more high or less high rp than just having our normal door sounds. They don't sound good at all and add nothing to the game, and to top it off they're just taken directly from Citadel rather than being something actually unique or original. This adds nothing and it's just change for the sake of change

**Comment by Swiftfeather** [comment]
These sound horrendous, they're almost all the sound version of coder sprites.

**Pull request merged**
