### PR TITLE
Adjustments to Nanotrasen Consultant Offices [Mostly Non-Modular]

### PR DESCRIPTION
**Pull request by ChromeFoxxity**
## About The Pull Request

Changes the offices to have more luxury items, such as statues, booze-o-mat's, and a few more apparel items in their lockers, as well as sorted equipment, with nicely placed gear, preserved maneuverability in their offices, and also adds Lisa into some of the offices, the technical pet of the NTC, considering the Nanotrasen Consultant has a dog collar in their locker, which might be leftover code, but this still works. As well as adds requests consoles, and otherwise more useful additions.

And yes, this is just because I play Nanotrasen Consultant. Don't judge me.

## Why It's Good For The Game

It's better for the game, to indicate the luxury of the Consultant's, smoking expensive cigars, with luxury champagne. Also makes it more to the fact that CentCom doesn't make every office unique per-say. Same assets here and there.

## Proof Of Testing

https://gyazo.com/f4dc2c9f5c328efacb12f63a440e42d2

## Changelog

:cl:
add: Adds booze-o-mats to the offices, along with more equipment such as Requests Consoles, and more managed, luxury items to said offices.
del: Removed a few assets.
spellcheck: Re-named doors.
/:cl:

image
image
image
image
image
image

### CODE REVIEW

**Comment by ChromeFoxxity** [comment]
And yes, I know I can make it modular pretty easily, but like- I haven't gotten to doing that. If asked, I can do it.

**Comment by nikothedude** [comment]
just do it before the maintainers mandate you do it

**Comment by theselfish** [comment]
> a few more apparel items in their lockers

You should do this by adding it to a garment bag, which I think the NT Rep has.
Locker bloat is bad.

**Comment by ChromeFoxxity** [comment]
> > a few more apparel items in their lockers
> 
> You should do this by adding it to a garment bag, which I think the NT Rep has. Locker bloat is bad.

This is a fair suggestion.

**Review by projectkepler-ru — CHANGES_REQUESTED** [review]
Why aren't these moved to their garment bag instead of to the locker

**Comment by ChromeFoxxity** [comment]
> Why aren't these moved to their garment bag instead of to the locker

I'll be fair, I didn't really consider that. I was originally intending to add some more gear into their lockers, but uh.. I haven't gotten to that part yet.

**Pull request closed without merging**
