### PR TITLE
Improves lobotomies by hugboxing them

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request
- Lobotomies are now repeatable (you can keep performing the "lobotomize" surgery step).
- Lobotomies deal 20 brain damage per successful attempt.
- Lobotomies have a 50% chance to not cure lobotomy tier traumas, but just regular surgery-tier traumas.
- Traumas that were not cured by a lobotomy have their resilience lowered by 1 (unless it's an ACTUALLY permanent trauma, or caused by an active fracture).
- The medical scanner and kiosk now differentiate from magic and permanent traumas,

## Why this is good for the game
It sucks that there are a lot of sources of permanent, near-crippling traumas caused by antag fuckery, such as heretics and inverse neurine. This makes it so that someone's round isn't completely ruined because they were affected by these things, as long as lobotomies are researched and there are active doctors.

## TODO
Add some code or something to prevent people from "farming" special rare+powerful traumas.
Test the code.

## Changelog

:cl:
balance: Rebalances lobotomies so they can be repeatable and cure magic traumas. Lobotomies can lower the resilience of traumas that were not removed, and they now have a chance not to cure lobotomy-tier traumas.
/:cl:

### CODE REVIEW

**Comment by Oscari-pog** [comment]
Good joke PR

**Comment by BurgerLUA** [comment]
> Good joke PR

This is not a joke PR.

**Comment by Detective-Google** [comment]
I feel like this probably hugboxes them *too* hard, but I do agree that being able to do multiple lobotomies on someone to just make their game unplayable with no recourse outside a few very niche techniques should go.

havent seen it much lately but a couple weeks ago I saw it multiple times where someone'd just spam lobotomies on others to effectively force them out of the round.

**Comment by BurgerLUA** [comment]
> I feel like this probably hugboxes them _too_ hard, but I do agree that being able to do multiple lobotomies on someone to just make their game unplayable with no recourse outside a few very niche techniques should go.
> 
> havent seen it much lately but a couple weeks ago I saw it multiple times where someone'd just spam lobotomies on others to effectively force them out of the round.

I never considered this. The reason why this PR exists is so that people can remove the permanent phobia caused by heretics. I'd say the ability not to abuse game-crippling lobotomies is a good thing too.

**Comment by zeroisthebiggay** [comment]
> I never considered this. The reason why this PR exists is so that people can remove the permanent phobia caused by heretics. I'd say the ability not to abuse game-crippling lobotomies is a good thing too.

i think that it'd be better to just make heretic induced traumas lobotomy tier instead

**Comment by chemistrymain2** [comment]
> > I feel like this probably hugboxes them _too_ hard, but I do agree that being able to do multiple lobotomies on someone to just make their game unplayable with no recourse outside a few very niche techniques should go.
> > havent seen it much lately but a couple weeks ago I saw it multiple times where someone'd just spam lobotomies on others to effectively force them out of the round.
> 
> I never considered this. The reason why this PR exists is so that people can remove the permanent phobia caused by heretics. I'd say the ability not to abuse game-crippling lobotomies is a good thing too.

Being able to deliberately fail lobotomy steps multiple times is a good way to permanently RR someone

**Comment by BurgerLUA** [comment]
If people use lobotomies to round remove people, ahelp them like you would with literally any current method of round removal. Using lobotomies to round remove someone is such a convoluted way to round remove someone anyways.

**Comment by nevimer** [comment]
This was a good idea, it deserves a shot to be tested. It may need to be rebased however. Brain traumas suck for long rounds.

**Comment by BurgerLUA** [comment]
Remaking this PR.

**Pull request closed without merging**
