### PR TITLE
GAS 2 - Part 2 - The Sequel, the worm, what you have been waiting for

### PR DESCRIPTION
**Pull request by nevimer**
## About The Pull Request

The famous bug-shaped crewmembers are back! Pull directly from my April Fools PR. 

## Why It's Good For The Game

BUGS, BUGS OF ALL KIND

## Changelog

:cl:
add: Giant Armoured Serpentids
/:cl:

### CODE REVIEW

**Comment by IgiariValkyr** [comment]
Ozzo promoted to favorite maintainer. Friendship with Burger ended.

**Comment by xXPawnStarrXx** [comment]
I thought this said GaGs, got excited and realised it was just dumb bugs...

**Comment by projectkepler-ru** [comment]
hehe. bugs

**Review by Majkl-J — CHANGES_REQUESTED** [review]
Gonna need to move the edits in our files

**Comment by ChickyRooster** [comment]
This is missing a lot of what makes a bay GAS special. No threat display or stance switching.

**Comment by Majkl-J** [comment]
Stalling this out since nobody's working it

**Pull request closed without merging**
