### PR TITLE
Fixes a reversion that causes the bureaucratic error event to have a chance to close all job slots

### PR DESCRIPTION
**Pull request by Shadow-Quill**
## About The Pull Request

Reverts a reversion in #456 which re-enabled the bureaucratic error event having a 33% chance to choose a random overflow job and close all job slots for all other jobs.

## Why It's Good For The Game

A HoP can only open non-command job slots at a rate of one slot every thirty seconds.
This can leave people only able to latejoin as assistants.
The job slot randomization that skyrat added is annoying, but doesn't prevent new people from joining actual jobs.

## Proof Of Testing

N/A, just re-commented out something that was un-commented out.

## Changelog

:cl:
del: Fixes a reversion which re-enabled a chance to close all job slots except one when the bureaucratic error event triggers.
/:cl:

### CODE REVIEW

**Comment by shellspeed1** [comment]
Hot take, can we rework this so it OPENS a job slot for all jobs?

**Comment by Cyprex** [comment]
This event is bugged, fix the bug instead of disabling the event. I'll leave this open so that it can be testmerged until the event is fixed.

**Comment by Shadow-Quill** [comment]
> This event is bugged

How is it bugged?

**Comment by Cyprex** [comment]
Okay, I had a look at the code and it's not bugged. There's a 66% chance for it to randomize all job slots, and a 33% chance for it to make a random job unlimited and close all other slots. So let's just remove the 3 lines that close all other slots and we're good.

**Comment by StrangeWeirdKitten** [comment]
@Shadow-Quill status?

**Comment by Majkl-J** [comment]
staled out

**Pull request closed without merging**
