### PR TITLE
Revert "Reworks the Gifted quirk and just gives everyone 6 free quirk points."

### PR DESCRIPTION
**Pull request by Majkl-J**
Reverts Bubberstation/Bubberstation#1354

### CODE REVIEW

**Comment by projectkepler-ru** [comment]
we fucked up

**Comment by YakumoChen** [comment]
Maybe the coder should be expected to test their code like we have a field for

**Comment by Majkl-J** [comment]
> Maybe the coder should be expected to test their code like we have a field for

I already berated the person who spontaneously pressed the merge button

**Comment by StrangeWeirdKitten** [comment]
@BurgerLUA you're going to have to open another PR since I'm merging the revert

**Pull request merged**
