### PR TITLE
Removes emagged LMG crate from cargo

### PR DESCRIPTION
**Pull request by YakumoChen**
## About The Pull Request

Removes the machine gun that's buyable from cargo with an emagged console
## Why It's Good For The Game

It's stupidly powerful. You can spray and pray and mow down entire security teams, which happens every time I've seen a cargo antag get a hold of the thing. There's no real counterplay to it since you can point it at someone and vomit out ammo until they retreat or die. The only real answer to one is to buy one yourself, but security tends to be more worried about friendly fire than antags are, which this thing is likely to do.
## Changelog

:cl:
balance: Nanotrasen has cracked down on gunrunners supplying imported LMGs into the sector.
/:cl:

### CODE REVIEW

**Comment by IgiariValkyr** [comment]
>How this PR looks since this was just added back
cover3

**Comment by sippykot** [comment]
HONESTLY with the current state of sec gear and guncargo... Let syndies have their guns...

**Comment by ReturnToZender** [comment]
Already done in #2125 which is on track to be merged once we look at the prices in cargo

**Comment by YakumoChen** [comment]
I'll hope that merge comes soon then. A little spiteful the complaints are coming only when i put a spotlight on it, but alas.

**Pull request closed without merging**
