### PR TITLE
Nerfs Wounds significantly, opening doors for better balance.

### PR DESCRIPTION
**Pull request by BurgerLUA**
### Wound Exponent

**Decreases wound exponent from 1.4 to 1.3**, meaning wounding is slightly rarer with threshold meeting weapons.

### Wound minimum damage.

**Increases the wound minimum damage from 5 to 14.** This means that a weapon has to deal 14 or more damage to even deal a wound. 

Examples of 15 damage weapons are: ritual knives, lead pipes, lit welders, tactical toolbox, butcher cleavers.

Examples of 13 damage weapons are: A chainsaw that isn't on, A cyborg picket sign, a botanist's scythe, a plasma shiv, a thrown potted plant.

### Wound maximum damage calculations.

**Increases the maximum considered damage for wounding from 35 to 45.** This is to compensate for the changes, which result in 35 damage weapons (previously) having nearly the same wounding strength as 45 damage weapons (in this pr). This change basically means that anything over 45 damage has the same wounding power as a 45 damage weapon.

### Wound dismember minimum damage

**Increases the dismemberment minimum damage from 10 to 26.** This means that a weapon has to deal 26 or more damage in order to actually dismember.

Example of 30 damage weapons are: energy swords, energy katanas, deathnettle, pirate cutlass, eldritch longswords, chaplain chainsword (active), 9mm rounds, .45 rounds.

Examples of 25 damage weapons are: Brass spears, nightmare armblade, implanted armblades, ling armblade. .38 revolver rounds.

Examples of 22 damage weapons are: Chainsaw arms, T4 scythe, axe (thrown), spear (thrown), toolbox (thrown).

Examples of 20 damage weapons are: 4.6x30mm rounds.

### Baseball Bats

Because baseball bats have a kneecapping element that relies on it meeting the wound threshold, baseball bat base damage has to be buffed. To compensate for this buff from 12 damage to 14 damage, I changed the click cooldown from 8 deciseconds to 10 deciseconds.

## Why It's Good For The Game

The wound system is holding the game back significantly when it comes to features. Right now, brute wounds are absolutely insane compared to burn wounds, which is causing people to make PRs that remove security equipment, limiting the selection that officers get in terms of dealing with valids.

The numbers I chose were extremely specific. Generally, antag stuff and harder to obtain stuff meets the threshold for wounding while easy to obtain items don't. Solo antag equipment and "highly dangerous and visible" weapons meet the threshold for dismemberment, while roundstart stuff don't.

## Changelog

:cl: BurgerBB
balance: Nerf wounds significantly. Slightly tweaks baseball bats.
/:cl:

### CODE REVIEW

**Comment by Majkl-J** [comment]
This basically closes #613 and any discussion around it

**Comment by YakumoChen** [comment]
This kneecaps a lot of weapon options right now in favour of just selecting weapons with the highest force.

The dismemberment change alone completely guts many weapons explicitly designed for wounding and dismemberment, such as the captain's sabre.

**Comment by YakumoChen** [comment]
> brute wounds are absolutely insane compared to burn wounds, which is causing people to make PRs that remove security equipment, limiting the selection that officers get in terms of dealing with valids.

Most of the removal of security equipment is reverting the horrible skyrat balance we inherit, because ballistics as a whole have a heap of upsides and no real downsides. TG's energy only security actually plays ball with antags and makes EMPs as dangerous as they ought to be.

**Comment by Moostard** [comment]
I think it would be better to just slow down the bleeding from brute wounds instead of nerfing every wound there is. Especially that burn wounds are quite pathetic already.

Wounds add some flavour to the combat and makes chems less of a "solve all" solution.

**Comment by destrucktoid** [comment]
I agree with moostard here, this PR is rather over engineered, the crucial problem here is that bleeding right now is too strong, rather than completely kneecapping bleeding, instead i think we should try slowing it down first before looking into more drastic changes (this PR)

**Comment by KareRott** [comment]
> > brute wounds are absolutely insane compared to burn wounds, which is causing people to make PRs that remove security equipment, limiting the selection that officers get in terms of dealing with valids.
> 
> Most of the removal of security equipment is reverting the horrible skyrat balance we inherit, because ballistics as a whole have a heap of upsides and no real downsides. TG's energy only security actually plays ball with antags and makes EMPs as dangerous as they ought to be.

I just got it, I understand why burger does not want to get rid of ballistics in sec, it's because he's a synth and that would be against his best interests, making EMP use more common. x3 (teasing)

**Comment by projectkepler-ru** [comment]
> > > brute wounds are absolutely insane compared to burn wounds, which is causing people to make PRs that remove security equipment, limiting the selection that officers get in terms of dealing with valids.
> > 
> > 
> > Most of the removal of security equipment is reverting the horrible skyrat balance we inherit, because ballistics as a whole have a heap of upsides and no real downsides. TG's energy only security actually plays ball with antags and makes EMPs as dangerous as they ought to be.
> 
> I just got it, I understand why burger does not want to get rid of ballistics in sec, it's because he's a synth and that would be against his best interests, making EMP use more common. x3 (teasing)

Reasonable behaviour

**Comment by projectkepler-ru** [comment]
> I think it would be better to just slow down the bleeding from brute wounds instead of nerfing every wound there is. Especially that burn wounds are quite pathetic already.
> 
> Wounds add some flavour to the combat and makes chems less of a "solve all" solution.

I concur but I also think this is worth trying out

**Comment by YakumoChen** [comment]
This has a severe impact on chaplain in as many null rods use wounding as a balance lever, dismemberment in particular. 

I especially don't think baseball bats need a buff

**Comment by BurgerLUA** [comment]
The baseball bats are getting a buff because without the buff, the kneecap code doesn't work because it needs to wound in order for that to trigger.

**Comment by YakumoChen** [comment]
Didn't mean to post my comment but you must have gotten an email alert 

The fact you have to workaround by buffing an already powerful weapon (bats) already shows some big cracks in this idea

This PR is very overbroad and if you want to nerf wounds, I really suggest you start somewhere small and work you way up if you're still unhappy.

Someone else suggested nerfing bleeding in particular, which I think is a good start

There's no reason to go nuclear and ruin the balance of everything at once

**Comment by StrangeWeirdKitten** [comment]
> Didn't mean to post my comment but you must have gotten an email alert 
> 
> 
> 
> The fact you have to workaround by buffing an already powerful weapon (bats) already shows some big cracks in this idea
> 
> 
> 
> This PR is very overbroad and if you want to nerf wounds, I really suggest you start somewhere small and work you way up if you're still unhappy.
> 
> 
> 
> Someone else suggested nerfing bleeding in particular, which I think is a good start
> 
> 
> 
> There's no reason to go nuclear and ruin the balance of everything at once

Agreed. Start someplace smaller like bleeding. This PR has very massive sweeping changes and it'll buff synths even more as an example. If you need to start buffing weapons to compensate, then this is way too sweeping and not the way to go.

**Pull request closed without merging**
