### PR TITLE
Fix feline traits giving speech modifier

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request

Fixes feline traits speech modifier

## Why It's Good For The Game

PurrrrrrrrrRRRRRRRRrrrrrrr

## Changelog

:cl: LT3
fix: Feline traits will give purr speech modifier
/:cl:

### CODE REVIEW

**Review by Majkl-J — APPROVED** [review]
Catboy (Accusatory)

**Comment by NanoCats** [comment]
Hey, I don't consent to a speech impediment being added to my character without my informed consent. Make an override.

image

**Comment by lessthnthree** [comment]
> Hey, I don't consent to a speech impediment being added to my character without my informed consent. **Would you kindly** add a way to override this functionality.
> 
> image

Are you using the feline traits quirk?

**Comment by NanoCats** [comment]
> > Hey, I don't consent to a speech impediment being added to my character without my informed consent. **Would you kindly** add a way to override this functionality.
> > image
> 
> Are you using the feline traits quirk?

Yes, but I don't appreciate that now coming with a speech impediment. I liked that trait FINE before you came along and did this.

**Comment by lessthnthree** [comment]
> > > Hey, I don't consent to a speech impediment being added to my character without my informed consent. **Would you kindly** add a way to override this functionality.
> > > image
> > 
> > 
> > Are you using the feline traits quirk?
> 
> Yes, but I don't appreciate that now coming with a speech impediment. I liked that trait FINE before you came along and did this.

I'll improve the check, then.

**Comment by NanoCats** [comment]
What do you mean "improve the check" I just don't want to always have my character say 3 more rs than they should for no reason.

**Comment by lessthnthree** [comment]
> What do you mean "improve the check" I just don't want to always have my character say 3 more rs than they should for no reason.

The quirk has always said "This will replace most other tongue-based speech quirks."

It being broken and you using it doesn't change that.

**Comment by pixelkitty286** [comment]
If you are playing or using a tajara as your base species please know i coded it to where you never need the feline quirks they get them by default.

**Comment by lessthnthree** [comment]
> If you are playing or using a tajara as your base species please know i coded it to where you never need the feline quirks they get them by default.

Four months ago an upstream change added a felinid tongue. The better way to make the tajaran tongue optional is to put it in the augments tab, which is what I'm doing now.

**Comment by pixelkitty286** [comment]
> > If you are playing or using a tajara as your base species please know i coded it to where you never need the feline quirks they get them by default.
> 
> Four months ago an upstream change added a felinid tongue. The better way to make the tajaran tongue optional is to put it in the augments tab, which is what I'm doing now.

No it's not I made them this way so they are on par with Lizards base traits

**Comment by pixelkitty286** [comment]
The rrr is their accent not by choice, but by species I made tajara into what they are so people stopped using them as just anthromorphs. Tajara are specifically supposed to be a separated race with the same intentions how lizards are supposed to be with their sss.

**Comment by lessthnthree** [comment]
> The rrr is their accent not by choice, but by species I made tajara into what they are so people stopped using them as just anthromorphs. Tajara are specifically supposed to be a separated race with the same intentions how lizards are supposed to be with their sss.

Right, and the forked tongue is available in augments to non lizard species players.

**Pull request merged**
