### PR TITLE
[Semi-Definitely-Non-Modular] Service Borg Edits

### PR DESCRIPTION
**Pull request by IgiariValkyr**
## About The Pull Request

**_This pull was originally for Skyrat, thus was already tested on their codebase and is functional._**

This pull edits Service Borgs to fix those weird quirks that they have. This includes:
- Duplicate tools [3 droppers, ~~2 trays~~, 2 lighters]
- Redundant tools [Default Borg Shaker that was _already commented out close to the bottom of the list,_ free bottle of universal enzyme]
- Lack of proper condiments [This was resolved by creating a 5th shaker to replace the Condiment Synthesizer module that is researched and printed.]
- Alphabeticalizes the Shakers [As stated on tin, the shakers are now in alphabetical order. No longer will it be orange, tomato, lime, carrot, berry in the juice shaker; or any other shaker for that matter.]
- Adds Kortara to the alcohol shaker [Lizard's favorite!]

## Why It's Good For The Game

Service Borgs have been a weird beast for a long while on TG base, having duplicate tools and the menus being generally difficult to navigate. This cleans up their code to allow them to be much easier to use. The new shaker as well allows the borgs to make more drinks / help better in the kitchen / completely perform the job if there is neither a bartender or chef.

## Changelog

:cl:
add: A whole new shaker for service borgs all about condiments has been added!
add: Kortara is available in the Cyborg Alcohol Shaker! No more will you have to hunt down a Tizirian Delicacies machine!
del: Several duplicate tools have been removed from the service borg module.
qol: All reagents in the service borg shakers have been listed alphabetically.
/:cl:

### CODE REVIEW

**Comment by IgiariValkyr** [comment]
One second. Apparently the server doesn't have vegetable oil.

**Comment by IgiariValkyr** [comment]
Fixed 👍

**Comment by Serxule** [comment]
i mean the duplicate trays can be useful for carrying more items (i think itd make it a 16 food item limit instead of 8? if i remember how much food a tray holds)

**Comment by IgiariValkyr** [comment]
> i mean the duplicate trays can be useful for carrying more items (i think itd make it a 16 food item limit instead of 8? if i remember how much food a tray holds)

A fantastic argument. Uncommenting it

**Comment by nevimer** [comment]
you must make this more modular. maybe make a new file of defines and change it to use the new ones where its called?

**Comment by IgiariValkyr** [comment]
> you must make this more modular. maybe make a new file of defines and change it to use the new ones where its called?

I attempted before. Trying to overwrite a defines block with a modular one had no effect.

**Comment by nevimer** [comment]
ill sort out the modularity later

**Pull request merged**
