### PR TITLE
[Greer] Replaces NTC's captain pen with a fountain pen

### PR DESCRIPTION
**Pull request by ReturnToZender**
## About The Pull Request
Red pen writing looks the same as the Captain's, and not as good. This swaps the NTC's captain fountain with just a regular fountain. More snazzy!

## Why It's Good For The Game
I get to have more style in my PDA as the NTC
image

## Proof Of Testing

<details>
<summary>Screenshots/Videos</summary>

</details>

## Changelog

:cl: ReturnToZender
del: Replaces the NTC's captain fountain pen with a regular fountain pen
/:cl:

### CODE REVIEW

**Comment by IgiariValkyr** [comment]
Alternate solution, make theirs write in green cause NT

**Comment by ReturnToZender** [comment]
> Alternate solution, make theirs write in green cause NT

Not a terrible suggestion, and definitely possible. I'd need a good shade of green that looks good on paper, though.

**Comment by YakumoChen** [comment]
> > Alternate solution, make theirs write in green cause NT
> 
> Not a terrible suggestion, and definitely possible. I'd need a good shade of green that looks good on paper, though.

We have green ink in four-colour pens, just use that

**Comment by ChromeFoxxity** [comment]
As a fellow NTC player, I respect this. I always resort to default pens due to the whole cursive thing, and the red ink part.

**Review by Majkl-J — CHANGES_REQUESTED** [review]
Give us the greer pen

**Comment by IgiariValkyr** [comment]
> Give us the greer pen
Give me a second on that.

**Comment by IgiariValkyr** [comment]
image

/obj/item/pen/fountain/nt
	name = "nanotrasen fountain pen"
	desc = "It's an expensive green fountain pen. The case may be plastic, but that gold is real!"
	icon_state = "pen-fountain-nt"
	colour = "#18610D"
	custom_materials = list(/datum/material/gold = SMALL_MATERIAL_AMOUNT*7.5)

firefox_2024-11-23_16-13-33

**Comment by ReturnToZender** [comment]
greer
image
image

**Pull request merged**
