### PR TITLE
Removes Voidraptor from being votable because I died to it once

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Removes Voidraptor from being votable.

## Why It's Good For The Game

Unironically the worst map in rotation right now, in my honest opinion. I am by no means an expert on game design or map design, but here are my thoughts on it.

- Maintenance is filled with hostile and extremely deadly mobs that need to be cleared out every shift start. This is terrible game design because it assumes that security/everyone carries lethals round start and all it takes is one assistant to open a door for a flood of enemies to merk several people walking in the halls (this happens nearly every round). This also doesn't make any lick of sense realism wise unless we want to follow Skyrat's "everything is a mess" frontier fetish because someone played on a fallout erp server once.
- Restating the above two points, it's basically enforcing the grudge that people have against assistants who loot and build things in maint because it's """"lrp"""". This is extremely hostile design and bad for the players.
- Worse than Deltastation in terms of fighting something in maint (such as blob, or other threats). Corridors are winding, tight, and only leaves space for large maintenance areas that benefit a threat like blob significantly. Lack of power wires in most sections of maint really mess it up.
- The chapel is extremely easy to isolate from the station as the only way to access it without space suits is via transit tubes. It tried to copy what Pubbystation did, but didn't implement a shuttle that you can get to it. I recall that mappers implemented a walkway that you could use to access it as well, before it was remove from rotation.
- The most hugboxed supermatter cooling setup I've seen. Not only is the amount of heat exchanging pipes excessive, but it is completely isolated from outside sources.
- An absolutely terrible atmos setup that leaves minimal room for projects and other things that is somehow worse than Burgerstation's atmos setup.
- The vault is isolated from space, requiring you to break through via maint. This would normally be acceptable (icebox has this), however the vault is literally next to the HoS office.
- The armory is also isolated from space, requiring you to break through via maint.
- Minimal amount of evac ship space. Larger evac shuttles will either crash into the chapel asteroid horizontally, or crash into the bitrunning den vertically.
- Hugboxed command section that offers field generators already setup that can protect the command bridge section, with 2 generators to help.
- Absurdly long transit tube + catwalk walkway leading to the AI core.
- A medbay setup that consists of 2 tile wide hallways.

I could write more but it would be nitpicks at this point.

## Why Remove and not Improve?

Voidraptor is an upstream map. Any changes I make will either have to be done upstream, or via a terrible and unmaintainable method of map edits.

## Changelog

:cl: BurgerBB
del: Removes Void Raptor from being votable.
/:cl:

### CODE REVIEW

**Comment by IgiariValkyr** [comment]
L

**Comment by StrangeWeirdKitten** [comment]
This is config, and I'll bring this up later between the other maintainers.

**Comment by StrangeWeirdKitten** [comment]
> > This is config and would be what we use tondosable it, and I'll bring this up later between the other maintainers.
> 
> 
> 
> I did not see a config option for maps on the config branch of bubberstation so I assumed it was just done here.

Our config between repo and server is not kept up to date. As you probably already know, we have to manually add new config entries on this when there is a config change. (I just copy and paste it, lol)

But overall, void raptor is inside the mapping config. That's why it's votable

**Comment by Majkl-J** [comment]
On one side, I really like the map from a visual perspective. On the other, god is it kinda mid for gameplay.

**Comment by StrangeWeirdKitten** [comment]
While I agree voidraptor is incredibly mid, the two Russians with knives aren't really that big of a deal. There are maps (like birdshot) that have it significantly worse. Atmos is fine, there's plenty of space. The engine is whatever. Though in all honesty, if I were to disable every map people didn't like, we'd just be running on Meta. 

overall, I did take the liberty to bring this up to Ozzo and he said no as well.

**Comment by StrangeWeirdKitten** [comment]
also some of the minor stuff can be fixed with the automapper skyrat made.

**Pull request closed without merging**
