### PR TITLE
(Non-Modular) Comments out Skyrat Modsuit Overrides

### PR DESCRIPTION
**Pull request by StrangeWeirdKitten**
## About The Pull Request

This PR aims to comment out `modular_skyrat\modules\modsuit_armour\modsuit_armour.dm`. It reverts it back to TG armor. This is a massive balance change for armor

**This will need to be test merged**

## Why It's Good For The Game

Skyrat has severely buffed crew side armor values while reducing antag armor values. The most effected are the HoS and Captain modsuit armor values which have 40 percent armor reduction. You can face tank a lot of ammo with these values. The only better armor is the elite syndicate modsuit w/ armor boosting. Then again, if you're fighting the captain. You are also fighting all of security, the blueshield, and crew more often than not. 

Skyrat stacks heavily against their antags and this will hopefully reduce some of the pain in the long run. 

## Testing
**Skyrat Armor Values**

image

**TG Armor Values**

image

## Changelog

:cl: Danger Kitten
balance: Reduces modsuit armor values back to TG standard
/:cl:

### CODE REVIEW

**Comment by nevimer** [comment]
I disagree, this is one of a few things skyrat did for a reason. We can't go around changing raw values willy nilly. Personally I'd buff syndicate suits before nerfing non-antag modsuits. I think the seperation of the space/armor modes to be terrible design, remove that instead.

**Comment by StrangeWeirdKitten** [comment]
> I disagree, this is one of a few things skyrat did for a reason. We can't go around changing raw values willy nilly. Personally I'd buff syndicate suits before nerfing non-antag modsuits. I think the seperation of the space/armor modes to be terrible design, remove that instead.

This was made in a discussion with Moth and a lot of testing on the centcomm z-level. Armor values can always be adjusted and I'll make a seperate bubber armor override if specific suits need to be modified.

**Comment by StrangeWeirdKitten** [comment]
If required, I'd like to at least cut the Captain's armor by 10 percent or I can comment out the nerfs to syndi armor. 

>I think the seperation of the space/armor modes is a terrible design, remove that instead.

No, space combat trades off lower armor values with speed and mobility because you don't take slowdown when injured. The armor booster for the syndicate suits specifically trade space capabilities for mobility and added armor.

**Comment by zeroisthebiggay** [comment]
sometimes i wonder if when things are set to pending maintainer discussion are they actually discussed

**Comment by projectkepler-ru** [comment]
This is an affront to god

**Comment by ReturnToZender** [comment]
Should just be an un-tick if it comments out the whole file

**Comment by Eastwardrope** [comment]
Can you also revert or change the AI in modsuit? Intellicards no longer allow you to upload into suits instead its only pAIs they literally just changed that one thing if it could be made unrestricted that'd be awesome

**Pull request closed without merging**
