### PR TITLE
Removes Scuhf_ Sprites

### PR DESCRIPTION
**Pull request by NotMergot**
## About The Pull Request

Removes Schuf_'s sprites, this was made at their request.

## Why It's Good For The Game

Sprite Maker doesn't want their sprite work here.

## Changelog

:cl:
del: Scuhf_ Hierophant Weapon Sprites
del: Scuhf_ Hierophant Marker Sprites
del: Scuhf_ Homestuck Horn Sprites
del: Scuhf_ Kangaroo Alt Tail Sprites
del: Code pertaining to the above sprites.
/:cl:

### CODE REVIEW

**Comment by StrangeWeirdKitten** [comment]
No. The Repo is not going to be involved in these politics.

https://creativecommons.org/licenses/by-sa/3.0/

**Comment by StrangeWeirdKitten** [comment]
To clearify, @NotMergot Creative Commons goes both ways. Everyone is freely allowed to contribute to the repo and anyone is freely capable of pulling our code and using it on any project they desire. I'm not going to gut multiple sprites from the codebase because the spriter in question is no longer satisfied with it for whatever reason. If this is an association thing, I'd be happy to remove the comments linking their discord very publically. Keep in mind that once something is put into github, it's forever. So everything will still remain inside comment history.

**Comment by NotMergot** [comment]
I just pr'd this cuz I was asked to. Ain't tryna start anything so if that's how it is, that's how it is. Thanks for the explanation, didn't know alla dat

**Comment by Offwrldr** [comment]
### Well, this is wild.

This reads as spiteful. I know the context and have seen this issue from every angle and fully believe that y'all could just _remove the sprites_ and be done with the issue in entirety. I don't understand the refusal, it just seems mean-spirited.

image

A few days ago I get a DM from the ticket bot regarding the ticket I made about this, and the ticket was closed without me acknowledging the conclusion of that ticket. I dismissed the DM, thinking y'all would be removing that sprite, and reopened it tonight to review the content within, believing that I would see confirmation of this:

image

Instead, I see now that the ticket was closed as such:

image

You use the term "gut" to describe a few pixels going missing from the game. Why does this matter so much to you? Are you worried this will establish a bad precedent, or is this simply to get back at someone for being difficult? As it stands, it seems the latter, not the former, and I'm left feeling grossed out watching the whole exchange from the sidelines. You continue saying that it will forever remain in the Github, yet it **can be removed**, you merely choose not to.

**Comment by snaffle15** [comment]
> I just pr'd this cuz I was asked to. Ain't tryna start anything so if that's how it is, that's how it is. Thanks for the explanation, didn't know alla dat

no worries, thanks above all.

**Pull request closed without merging**
