### PR TITLE
Revert "Cyborg-Reverse-Nerf (#458)"

### PR DESCRIPTION
**Pull request by YakumoChen**
This reverts commit 471ddc298871cbea75630d20ddd825f19d7e0651.

## About The Pull Request

No attempt at modularisation, unpopular change, not balanced

## Why It's Good For The Game
Its bad for the codebase
Cyborgs should not have electric welders
Medborgs losing drapes for the processor only serves to confuse them
Powercreep

## Changelog

:cl:
balance: Reverts PR that added several new modules to borgs (such as an electric welder)
/:cl:

### CODE REVIEW

**Comment by lurzefromgermany** [comment]
your whole deletion of code, also brings back the bugs I patched.

**Comment by YakumoChen** [comment]
its a straight revert, the code isn't modular at all, it should never have been merged in that state.

**Comment by Majkl-J** [comment]
>Powercreep
The flash in my pocket:

**Comment by DeerJesus** [comment]
> > Powercreep
> > The flash in my pocket:

one flash does nothing against a borg now

i support this change

**Comment by DeerJesus** [comment]
@lurzefromgermany oh also you refused to use the changelog in even the remotest sense of correctness because you were 'gifting code to the server' (nevermind the fact that it was god-awful code)

the server owes you nothing

get off your high horse

**Comment by lurzefromgermany** [comment]
> @lurzefromgermany oh also you refused to use the changelog in even the remotest sense of correctness (until threatened to not merge several times) because you were 'gifting code to the server (nevermind the fact that it was god-awful code that i wouldnt gift to a starving man)
> 
> the server owes you nothing
> 
> get off your high horse

If that is the case, their change log also needs to note that it's removing patches as well. Your contributions also have just been code deletions. responding to the original poster now, none of the cyborg code is modularized.

**Comment by DeerJesus** [comment]
> > @lurzefromgermany oh also you refused to use the changelog in even the remotest sense of correctness (until threatened to not merge several times) because you were 'gifting code to the server (nevermind the fact that it was god-awful code that i wouldnt gift to a starving man)
> > the server owes you nothing
> > get off your high horse
> 
> If that is the case, their change log also needs to note that it's removing patches as well. Your contributions also have just been code deletions. responding to the original poster now, none of the cyborg code is modularized.

Most of my contributions are upstream.

**Comment by nevimer** [comment]
Not going to do this for a while.

**Pull request closed without merging**
