### PR TITLE
Legalizes nuking from space

### PR DESCRIPTION
**Pull request by NullDagaf**
## About The Pull Request

So apparently if you detonate the nuclear device from outside of Delta's bridge, it doesn't count as "blowing up the station".
This fixes that.

## Changelog

:cl:
fix: legalizes nuking from space
/:cl:

### CODE REVIEW

**Comment by Cyprex** [comment]
No, don't just remove the space check wholesale. I need to know more about what specifically the issues is(a screenshot would help) to advise you better.

**Comment by Nicolai904** [comment]
dumb pr fix map instead of making it blow up anywhere

**Comment by Serxule** [comment]
nukies will now plant on a single tile in the middle of space that nobody can reach or find

**Comment by KathrinBailey** [comment]
Draft until you can explain how this won't be a balance issue.
It sounds like it is a problem, but this isn't the correct fix for it.

**Comment by NullDagaf** [comment]
Nevermind, apparently this is svul. Closing.

> nukies will now plant on a single tile in the middle of space that nobody can reach or find

Also. Nuke pinpointers are a thing.

**Pull request closed without merging**
