### PR TITLE
Adds Cargo shelves from Shiptest, makes Skyrat modular shelves buildable

### PR DESCRIPTION
**Pull request by ReturnToZender**
## About The Pull Request

Source Inspiration: https://github.com/shiptest-ss13/Shiptest/pull/2374

This PR add
## Why It's Good For The Game

This makes it so that cargo techs can neatly stack crates on a shelf for convenience. How neat!

## Proof Of Testing

https://cdn.discordapp.com/attachments/1059199070855495753/1195241690450120734/2024-01-11_23-39-46.mp4?ex=65b34691&is=65a0d191&hm=9314c27ee40abaf5ef185408c7ebd3d8336a8fc091a2b94524ec23252d4fe67f&

## Changelog

:cl: ReturnToZender, GenericDM (Original Version)
add: Cargo shelves are now craftable using metal! They store up to 3 crates per shelf.
fix: Skyrat modular shelves (such as gun racks and tall shelves) are now buildable using metal.
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
is it possible to give the sprites a different icon depending on the rack type?

**Comment by ReturnToZender** [comment]
> is it possible to give the sprites a different icon depending on the rack type?

Is that GANDALF? And yeah, it is, I just need interesting sprites. I'm gonna make the cargo shelf have a unique sprite... don't have any sprites for gunracks or similar, though.

**Comment by GenericDM** [comment]
As much as I dislike where my code has ended up, I do believe that it is for the best to have everyone get the best possible version of it.
There are two patches I put out after the initial PR. https://github.com/shiptest-ss13/Shiptest/pull/2605 and https://github.com/shiptest-ss13/Shiptest/pull/2597
These improve the user experience by allowing the cursor to change to a clickdrag state when clickdragging a crate, and improving the visuals by making players render behind crates, instead of looking like they're standing on top of the shelf.
Take care.

**Comment by Gandalf2k15** [comment]
> > is it possible to give the sprites a different icon depending on the rack type?
> 
> Is that GANDALF? And yeah, it is, I just need interesting sprites. I'm gonna make the cargo shelf have a unique sprite... don't have any sprites for gunracks or similar, though.

YUH IT ME :D

**Review by Majkl-J — CHANGES_REQUESTED** [review]
The shelves should be like 2 metal + 2 rods and not as simple to craft

**Review by Majkl-J — CHANGES_REQUESTED** [review]
If you update the costs to like 2-4 metal sheets raw material (In any form, be it rods+metal, or just metal), I will gladly merge this

**Review by Majkl-J — APPROVED** [review]

**Pull request merged**
