### PR TITLE
Added simple policy text to the lavaland elite spawn message. 

### PR DESCRIPTION
**Pull request by Erol509**
## Why It's Good For The Game

What the title says. If it doesnt say clearly, people wont understand such a common sense. 

## Proof Of Testing

I couldnt test it, as I didnt manage to get ghost offer on the localhost after several tries. 

## Changelog

:cl:
add: Added one aditional line, more like a policy to lavaland elite spawn.
/:cl:

### CODE REVIEW

**Comment by Arturlang** [comment]
Cant antag policy messages be set in config by hosts? This isnt really neccesary

**Comment by ReturnToZender** [comment]
Oh shit, can it? I can see if I can add this then

**Comment by Arturlang** [comment]
image

**Comment by Majkl-J** [comment]
Well, since zender didn't edit the config yet, Ill do today once I come back from college

**Comment by Majkl-J** [comment]
This should be on the config repo

**Pull request closed without merging**
