### PR TITLE
nukes ballistics from guncargo again (skyrat stealthadded it) 

### PR DESCRIPTION
**Pull request by DeerJesus**
## About The Pull Request

we decided we do not want this already in the previous pr. they refactored guncargo. this re-removes the ballistics.

## Why It's Good For The Game

we decided we do not want this already in the previous pr. they refactored guncargo. this re-removes the ballistics. also these ballistics are more OP than the last

## Changelog

:cl:
del: new ballistic guncargo
/:cl:

### CODE REVIEW

**Comment by DeerJesus** [comment]
the new gun is more powerful than the fucking l6 saw for crying out loud

**Comment by Moostard** [comment]
Would be nice to have shotguns orderable though.
Otherwise station cant get any ballistics. No shotguns and detective .38 revolver.

**Comment by DeerJesus** [comment]
Done

**Comment by NargaInDisguise** [comment]
Please leave shotguns and pistols, only orderable on broad or something, low pop times with no sec is hell when crew can't defend themselves well at all

**Comment by DeerJesus** [comment]
> Please leave shotguns and pistols, only orderable on broad or something, low pop times with no sec is hell when crew can't defend themselves well at all

this is done already

**Comment by YakumoChen** [comment]
What 12g ammo do we have available? Most of the skyrat ammo is OP garbage and even regular buckshot is notoriously powerful

**Comment by DuffCreeper** [comment]
We love straight removals instead of re-balancing, very cool

**Comment by Majkl-J** [comment]
> We love straight removals instead of re-balancing, very cool

Genuinely why bother when the base tg weapons are balanced already. Fair, I do like all the srat weapons, and kinda will miss them, but still, easier to remove them

**Comment by nevimer** [comment]
> We love straight removals instead of re-balancing, very cool

Fair enough, we noticed some glaring balance issues with testing the new guns. Now, I don't want to outright remove them but in their current state they're like assop weapons for crew. That is to say, they down people super fast and are entirely unfair for anyone facing them.

**Comment by Majkl-J** [comment]
> > We love straight removals instead of re-balancing, very cool
> 
> Fair enough, we noticed some glaring balance issues with testing the new guns. Now, I don't want to outright remove them but in their current state they're like assop weapons for crew. That is to say, they down people super fast and are entirely unfair for anyone facing them.

Heck I got killed in 2 shots in syndie armor they are broken

**Comment by StrangeWeirdKitten** [comment]
You can still order them through normal cargo shipments

**Pull request merged**
