### PR TITLE
Adds some new (unbalanced) chemicals

### PR DESCRIPTION
**Pull request by BurgerLUA**
Draft because untested.

## About The Pull Request

Adds 3 new medical chems obtained by doing chemistry.

### Xlasyn
Xlasyn works like clonexadone except it heals minor amounts of organ damage while in the cryotube. Sure you can just eat food, but this is a little faster and a little more medical.

### Synuirite
A coagulant you can actually make with chemistry. Weaker than what other coagulants you can obtain.

### Plasmacillin
A unique subtype of spaceacillin that cures any low-resistance (less than 6) disease at stage 1. Using it outside of that may be able to still cure diseases, however there is a chance for the disease to gain a new symptom that gives it flat added resistance. May not actually give you resistance to the disease if too much is used.

## Why It's Good For The Game

Played medical a bit and I noticed there were a few gaps in treatment options. Plus I had some of these ideas for meds for years, so I'm adding them here.

## Changelog

:cl: BurgerBB
add: Adds some new (unbalanced) chemicals: Xlasyn, Synuirite, Plasmacillin
/:cl:

### CODE REVIEW

**Comment by destrucktoid** [comment]
I disagree with the addition of synurite in it's current state, it's only 33% worse than sanguirite in terms of clotting (per U) yet is mass producible with very little effort. It needs either removing or nerfing even more than it is currently.

**Comment by Majkl-J** [comment]
Honestly? Love these, I hate drinking ground up banana peels.

**Comment by BurgerLUA** [comment]
> I disagree with the addition of synurite in it's current state, it's only 33% worse than sanguirite in terms of clotting (per U) yet is mass producible with very little effort. It needs either removing or nerfing even more than it is currently.

It takes synthflesh to make, which is difficult to mass produce. It's still possible but, you know.

**Comment by destrucktoid** [comment]
> > I disagree with the addition of synurite in it's current state, it's only 33% worse than sanguirite in terms of clotting (per U) yet is mass producible with very little effort. It needs either removing or nerfing even more than it is currently.
> 
> It takes synthflesh to make, which is difficult to mass produce. It's still possible but, you know.

Synthflesh is NOT hard to make. It's literally libital, blood, carbon. It's that simple. Just make libital hook up to duped blood and add carbon from the dispenser.

**Comment by destrucktoid** [comment]
> Honestly? Love these, I hate drinking ground up banana peels.

The point is that Ground up banana peels AREN'T something that can just be made in chemistry, you actually need botany for it. This promotes working with other departments as well as making it just that little bit harder to make anti-bloodloss pills which is intentional.

**Comment by projectkepler-ru** [comment]
> > I disagree with the addition of synurite in it's current state, it's only 33% worse than sanguirite in terms of clotting (per U) yet is mass producible with very little effort. It needs either removing or nerfing even more than it is currently.
> 
> It takes synthflesh to make, which is difficult to mass produce. It's still possible but, you know.

synthflesh is incredibly easy to make tbh

**Comment by BurgerLUA** [comment]
> > > I disagree with the addition of synurite in it's current state, it's only 33% worse than sanguirite in terms of clotting (per U) yet is mass producible with very little effort. It needs either removing or nerfing even more than it is currently.
> > 
> > 
> > It takes synthflesh to make, which is difficult to mass produce. It's still possible but, you know.
> 
> synthflesh is incredibly easy to make tbh

Bananas are too.

**Comment by StrangeWeirdKitten** [comment]
@BurgerLUA what's the status on this PR?

**Comment by BurgerLUA** [comment]
> @BurgerLUA what's the status on this PR?

its a draft

**Pull request closed without merging**
