### PR TITLE
THE END OF BOULDER MINING (for offstation factions, also raw ore bluespace miners for them) (Test Merge Ready)

### PR DESCRIPTION
**Pull request by shellspeed1**
## About The Pull Request

For quite a bit now, there has been some issues between the station and offstation groups related to boulders. Specifically, the fact that they are a quite limited resource and are often stolen by the boulder retrieval matrix.  Rather than come up with a creative solution, I have decided the best thing to do was to engage in the same behavior by stealing Moffingtons method to prevent offstation factions from building the retrievers (with permission) while adding bluespace miners that produce their own raw materials. 

## Why It's Good For The Game

Prevents future conflict and bitching. 

## Proof Of Testing

https://youtu.be/lYqr_M79JF8?si=P_OvpDRjQF8zkpCO

## Changelog

:cl:
add: The raw ore bluespace miner has been added for offstation factions.
balance: Offstation factions can no longer produce boulder retrieval matrixes with their circuit imprinters.
/:cl:

### CODE REVIEW

**Comment by Erol509** [comment]
You can buy boulder beacon with mining points inside mining vendor.

**Comment by shellspeed1** [comment]
> You can buy boulder beacon with mining points inside mining vendor.

I'm not totally sure if that is something that should be touched, just to maintain modularity with TG in case there are further changes.  I could look at adding a separate list of stuff to pull for the offstation vendor specifically.

**Comment by shellspeed1** [comment]
> > You can buy boulder beacon with mining points inside mining vendor.
> 
> I'm not totally sure if that is something that should be touched, just to maintain modularity with TG in case there are further changes. I could look at adding a separate list of stuff to pull for the offstation vendor specifically.

I put something together, but its probably fucked. Golems are on their own for it as they have a valid balance reason to be using stuff and may actually need access to it that way (they can literally pulls boulders out of vents, I should experiment with this sometime)

**Comment by shellspeed1** [comment]
Go figure, CI hates that

**Comment by Arturlang** [comment]
Removing conflict isn't a good thing, it's much more interesting when factions in a hostile z-level have reasons to conflict with eachother, this is perfect for that, literally holding control points that you could fortify if need be.

**Comment by Frost155** [comment]
> Removing conflict isn't a good thing, it's much more interesting when factions in a hostile z-level have reasons to conflict with eachother, this is perfect for that, literally holding control points that you could fortify if need be.

if it was that easy to fight and figure out who is building the system, it would be amazing but so fare, i seen derelict space drone ghost role, "ghost role" a role that's not suppose to interact with the station eat more the half the amount of ore the station was putting out, because they choose to build several of them. Please note the pictures only have one in them but its been several time on tarkon or other ghost roles, where they have made more, even if they "get shit all"
Drone
Round 5584

**Review by StrangeWeirdKitten — APPROVED** [review]

**Comment by DoktorBarron** [comment]
So long as the raw ore bluespace miner can be made without a bluespace crystal, I'm for it.
but if it needs a crystal, drones are buggered since they have no ores, no crystals, and can't leave the z-level the ruined station is on without perishing. (also the drones should have a interdyne/tarkon order console so they can order in more gas tanks and possibly super matter shards seeing as KS13 unlike Babylon station doesn't have one, but that's for another PR to solve)

I also have a dumber suggestion to allow for the boulder smelter and refiner to be still be useful to ghost roles, if only to let them have the strange objects you get from them, a "small asteroid harvester", effectively the boulder retriever, but it just make boulders out of thin air on a semi-random timer. lore wise it'd be pulling in loose bits of space rocks that float past.

**Comment by Frost155** [comment]
> So long as the raw ore bluespace miner can be made without a bluespace crystal, I'm for it. but if it needs a crystal, drones are buggered since they have no ores, no crystals, and can't leave the z-level the ruined station is on without perishing. (also the drones should have a interdyne/tarkon order console so they can order in more gas tanks and possibly super matter shards seeing as KS13 unlike Babylon station doesn't have one, but that's for another PR to solve)
> 
> I also have a dumber suggestion to allow for the boulder smelter and refiner to be still be useful to ghost roles, if only to let them have the strange objects you get from them, a "small asteroid harvester", effectively the boulder retriever, but it just make boulders out of thin air on a semi-random timer. lore wise it'd be pulling in loose bits of space rocks that float past.


Fair, maybe putting down a small stack of blue space crystals at start like 10? could be the fix for that. since it would solve the problem of needing blue space ore, at least for the drones,  if its not already in the vault, as tarkon has its own source of bluespace crystals, if you do the treasure hunt, thats on the noteboard and well later if you do it right with research you can make blue space "ore like copies" from diamonds i think and plasma? with any lathe but that's for later and wont be useable until you get the blue space miner up and running

And to the retrieval thing
Wouldn't it just be use full to add to the blue space miner? or would that fill up the output they make already?

**Comment by shellspeed1** [comment]
> So long as the raw ore bluespace miner can be made without a bluespace crystal, I'm for it. but if it needs a crystal, drones are buggered since they have no ores, no crystals, and can't leave the z-level the ruined station is on without perishing. (also the drones should have a interdyne/tarkon order console so they can order in more gas tanks and possibly super matter shards seeing as KS13 unlike Babylon station doesn't have one, but that's for another PR to solve)
> 
> I also have a dumber suggestion to allow for the boulder smelter and refiner to be still be useful to ghost roles, if only to let them have the strange objects you get from them, a "small asteroid harvester", effectively the boulder retriever, but it just make boulders out of thin air on a semi-random timer. lore wise it'd be pulling in loose bits of space rocks that float past.

Boulder smelter and refiner as are still usable, as for the drones I'm not sure they actually have access as its specifically part of the Tarkon and Interdyne technets. This means that the drones and charlie station are both back to where they were before boulder mining was a thing.

**Comment by shellspeed1** [comment]
> You can buy boulder beacon with mining points inside mining vendor.

Resolved issue.

**Comment by shellspeed1** [comment]
> So long as the raw ore bluespace miner can be made without a bluespace crystal, I'm for it. but if it needs a crystal, drones are buggered since they have no ores, no crystals, and can't leave the z-level the ruined station is on without perishing. (also the drones should have a interdyne/tarkon order console so they can order in more gas tanks and possibly super matter shards seeing as KS13 unlike Babylon station doesn't have one, but that's for another PR to solve)
> 
> I also have a dumber suggestion to allow for the boulder smelter and refiner to be still be useful to ghost roles, if only to let them have the strange objects you get from them, a "small asteroid harvester", effectively the boulder retriever, but it just make boulders out of thin air on a semi-random timer. lore wise it'd be pulling in loose bits of space rocks that float past.

Its not a horrible idea, but I also don't have the

**Comment by shellspeed1** [comment]
Woops, wrong button.

**Comment by KateAnbolho** [comment]
To note on the BSM issue, both factions have the ability to mine their own ore now, with tarkon having a massive, rich asteroid belt.

**Comment by Cyprex** [comment]
What if you did some linkage thing like ORMs use? Vents claimed by station miners should be linked to station boulder retrievers by default, but you could tap the vents to change that linkage- so that they now teleport to your receiver. This could be accompanied by an alert broadcasted by the boulder receiver it's currently linked to.
You could also have it so you can link retrieval devices with existing ones to split the received ores between them, and allow the station to construct more without having to go down and laboriously tap vents. You could steal access then- but you'd need to get close to a retrieval device, not just a miner(i. e. you'd have to actually enter cargo)

**Comment by YakumoChen** [comment]
> > You can buy boulder beacon with mining points inside mining vendor.
> 
> Resolved issue.

Removing it from the vendor just makes it inconvenient, remove it from off-station vendors only

**Comment by shellspeed1** [comment]
> > > You can buy boulder beacon with mining points inside mining vendor.
> > 
> > 
> > Resolved issue.
> 
> Removing it from the vendor just makes it inconvenient, remove it from off-station vendors only

It makes it so the only way for offstation factions to get the boulder miner is to ask NT directly for it. Additionally, I'm not sure its exactly inconvenient when you can still get the boulder processor and refinery board from an autolathe. All you have to do to get the rest of the setup is ask engineering or science for a single board. 

As a sidenote, to accomplish this as I did try it out, both the offstation and interdyne vendors would need to be completely redone codewise which would be a modularity issue at least for the former. This is a better solution in my opinion overall.

**Comment by shellspeed1** [comment]
> What if you did some linkage thing like ORMs use? Vents claimed by station miners should be linked to station boulder retrievers by default, but you could tap the vents to change that linkage- so that they now teleport to your receiver. This could be accompanied by an alert broadcasted by the boulder receiver it's currently linked to. You could also have it so you can link retrieval devices with existing ones to split the received ores between them, and allow the station to construct more without having to go down and laboriously tap vents. You could steal access then- but you'd need to get close to a retrieval device, not just a miner(i. e. you'd have to actually enter cargo)

Because that would just lead to people being dicks and mass sync'ing all of the boulder miners. It also does not fix the issue for offstation factions like Tarkon and drones who don't have access to boulders.

**Comment by YakumoChen** [comment]
> > > > You can buy boulder beacon with mining points inside mining vendor.
> > > 
> > > 
> > > Resolved issue.
> > 
> > 
> > Removing it from the vendor just makes it inconvenient, remove it from off-station vendors only
> 
> It makes it so the only way for offstation factions to get the boulder miner is to ask NT directly for it. Additionally, I'm not sure its exactly inconvenient when you can still get the boulder processor and refinery board from an autolathe. All you have to do to get the rest of the setup is ask engineering or science for a single board.
> 
> As a sidenote, to accomplish this as I did try it out, both the offstation and interdyne vendors would need to be completely redone codewise which would be a modularity issue at least for the former. This is a better solution in my opinion overall.

Miners shouldn't have to wait for science to do the critical part of their job where they get the minerals flowing

The convenience of the boulder beacon also is that you don't have to build the machines when they aren't mapped in by default, they just teleport in.

This is a very poor band-aid solution that would arguably be better served by just changing policy to ban off-station players building these. Or giving them a different mining vendor without the beacon.

**Comment by shellspeed1** [comment]
> > > > > You can buy boulder beacon with mining points inside mining vendor.
> > > > 
> > > > 
> > > > Resolved issue.
> > > 
> > > 
> > > Removing it from the vendor just makes it inconvenient, remove it from off-station vendors only
> > 
> > 
> > It makes it so the only way for offstation factions to get the boulder miner is to ask NT directly for it. Additionally, I'm not sure its exactly inconvenient when you can still get the boulder processor and refinery board from an autolathe. All you have to do to get the rest of the setup is ask engineering or science for a single board.
> > As a sidenote, to accomplish this as I did try it out, both the offstation and interdyne vendors would need to be completely redone codewise which would be a modularity issue at least for the former. This is a better solution in my opinion overall.
> 
> Miners shouldn't have to wait for science to do the critical part of their job where they get the minerals flowing
> 
> The convenience of the boulder beacon also is that you don't have to build the machines when they aren't mapped in by default, they just teleport in. Building machines is annoying and inconvenient.
> 
> This is a very poor band-aid solution that would arguably be better served by just changing policy to ban off-station players building these.
> 
> Or giving them a different mining vendor without the beacon.
> 
> It wouldn't be hard to do this upstream on the skyrat codebase if that's an issue.

I am once again going to have to disagree with you on it being a requirement to get materials flowing when many stations have round start boulder mining setups and the ORM for materials that are just mined by hand. Considering that I saw miners more often than not going to science and asking for the setup as is or just not bothering to make one, I'm once again unconvinced that it is as big of an issue as you make it out to be. 

As for upstreaming it, it would need to be done on TG, not skyrat which is the real headache to deal with.

**Comment by YakumoChen** [comment]
> On a different note, why have something serve as ban-bait? That just seems like kind of a dick thing to do, especially when people who don't play the roles might not know this is policy.

Better to keep a pretty simple to enforce policy (admins generally don't ban on first offense for things, they can just delete the offending teleporter or give IC concequences) than to code a blatant QOL reduction into the game

**Comment by YakumoChen** [comment]
Also I don't see how you should need to go upstream, the ghost roles that see actual consistent play are all mapped here or on skyrat.

**Comment by shellspeed1** [comment]
> Also I don't see how you should need to go upstream to TG, the ghost roles that see actual consistent play are all mapped here or on skyrat.

Map wise, the issue is the golems who would need their vendor replaced. I could automap it out to a new varient however 

> > On a different note, why have something serve as ban-bait? That just seems like kind of a dick thing to do, especially when people who don't play the roles might not know this is policy.
> 
> Better to keep a pretty simple to enforce policy (admins generally don't ban on first offense for things, they can just delete the offending teleporter or give IC concequences) than to code a blatant QOL reduction into the game.
> 
> I have never seen miners go to science for a teleporter, they just buy the beacon and set it up if they need to.
> 
> I've never seen mining not set up a boulder setup either, it's pretty critical when output from manual mining is so low.

I'll make it available for now and work on a better solution than if the need arises. Some of the offstation factions (Like drones) need bluespace anyway to kick start their stuff and this is a not horrible way for them to acquire it. I'm still not a fan of leaving it to ahelps if issues do arise though. At the very least, it does make the code modular so I'll just have to settle for that.

**Comment by YakumoChen** [comment]
> Map wise, the issue is the golems who would need their vendor replaced. I could automap it out to a new varient however

I feel like this is a valid thing to do anyway, I can try and push it upstream myself, golems shouldn't be causing petty conflicts with the station

**Comment by Arturlang** [comment]
Yea the optimal choice would be having to manually a mining scanner to a boulder matrix, which then links that one to it, and using it on a already active miner would link to it, bluespace miners are a not great solution, they're incredibly effective and you just set it up once and have unlimited resources, which kind of breaks the economy

**Comment by shellspeed1** [comment]
Closed because maintainer indicated they had no desire to pursue this.

**Pull request closed without merging**
