### PR TITLE
disables secborgs and enables peaceborgs by moving a single character around

### PR DESCRIPTION
**Pull request by DeerJesus**
## About The Pull Request
I didn't even think about disabling secborgs when I made that salt PR changing the laws but this seems like a good idea.

## Why It's Good For The Game
Does anyone even like secborgs? Can anyone give me one good reason why the security borg is good for the game?

Anything that I could say has already been said.

Anyway, for some reason peaceborgs were disabled? They're way better though, because they exist to prevent crew from killing each other in a much less 'I AM THE LAW' way. And they give out cookies and give hugs instead of screaming random sec stuff and 'trying to get the frags'.

## Changelog

:cl:
config: Goodbye secborgs, HELLO peaceborgs!
/:cl:

### CODE REVIEW

**Comment by chemistrymain2** [comment]
900+ hour borg main here

PLEASE

**Comment by Icarus-The-Sun** [comment]
You should make PRs that change config files to the config repo! [https://github.com/Bubberstation/config](url)

**Comment by DeerJesus** [comment]
> You should make PRs that change config files to the config repo! [https://github.com/Bubberstation/config](url)

It says that this isn't a real repo! 404!

**Comment by DeerJesus** [comment]
> > You should make PRs that change config files to the config repo! [https://github.com/Bubberstation/config](url)
> 
> It says that this isn't a real repo! 404!

Ah it kinda works now.

**Comment by lurzefromgermany** [comment]
> 900+ hour borg main here
> 
> PLEASE

4k+ hour borg main here
don't!

**Comment by DeerJesus** [comment]
> > 900+ hour borg main here
> > PLEASE
> 
> 4k+ hour borg main here don't!

8k+ hour borg main here

bias!

**Comment by neri-ventado** [comment]
ZASED. ZASED. GREAT PR. SPEEDMERGE. 

Secborgs have been a a constant plague upon anyone they're up against due to the fact that they have no slowdown. 

some people have also taken to using the unique non-human sprites to juggle people & baton spam then ;3

**Comment by YakumoChen** [comment]
This doesn't change the actual server configuration I think?

**Comment by Icarus-The-Sun** [comment]
This PR will not be merged here-It won't affect any files. All files affecting config files need to be made on the Config Repo, since that overwrites everything.

**Comment by DeerJesus** [comment]
im too lazy to close it

**Comment by nevimer** [comment]
it will not work in this repo

**Pull request closed without merging**
