### PR TITLE
Ports New Ghost Caffe update from Nova

### PR DESCRIPTION
**Pull request by Erol509**
## About The Pull Request
Cherry picked PR from Nova, it adds new areas to the ghost caffee. 

https://github.com/NovaSector/NovaSector/pull/117

## Why It's Good For The Game

More theme specific areas, cool 

## Proof Of Testing
image
image
image

## Changelog
:cl: Thlumyn
add: Added new areas to the ghost cafe, including a ashwalker and icewalker zones.
/:cl:

### CODE REVIEW

**Comment by Erol509** [comment]
Not yet done, It needs one small change in dme file

**Review by Majkl-J — APPROVED** [review]
One of the rooms at the bottom left is lacking walls but otherwise great and seems to work fine

**Comment by YakumoChen** [comment]
The map needs some fixes first, there's some other errors like the ashwalker den being completely inaccessible and the vending machines being the wrong type (with radios)

**Comment by Erol509** [comment]
> The map needs some fixes first, there's some other errors like the ashwalker den being completely inaccessible and the wardrobe vending machines being the wrong type (with radios). Should be the "ghost cafe" subtyping.

Are these vendors problem in this caffee or one we already have in game?

**Comment by YakumoChen** [comment]
seems like this might be a problem with the vending code, now that I've gotten a chance to look at the map file. Strange.

**Comment by StrangeWeirdKitten** [comment]
We are still pulling upstream from skyrat, this would be best taken there

**Pull request closed without merging**
