### PR TITLE
CentCom / NTC Changes

### PR DESCRIPTION
**Pull request by ChromeFoxxity**
## About The Pull Request

Resprites a few of the CentCom uniforms, recoloring most of them, as well as redesiging some, whilst also adding some custom ones. Other than the uniforms, also adds an old gun that NTC used to use, and a Sabre to NTC. While also adding some more clothes to NTC. And one uniform in loadouts.

## Why It's Good For The Game

As a Representative main myself, (CC-25), I'm always complaining about the clunky energy carbine that NTC's are always given, I was always told it was a placeholder until they were eventually given their to-be gun. I've gotten a little impatient, and decided to give them a gun that hasn't been used by anyone else, and it's been used by them before a long while ago. I thought it works, for self defense. The Sabre however, I must complain I always buy one from Cargo at shift-start. And this also adds it to CentCom Commanders, it's BARELY stronger than a cargo sabre, admittedly I should keep it as strong as a Cargo sabre, to make it fair, but I also gave it to Commanders. The uniforms however, looked a little stale, the shading was a little off, from a dusty, green to a almost pitch black green instantly. This gives it a more vibrant coloring, while also keeping that classic green as the primary color. The gold has also been given more vibrancy, to make it look more like gold instead of just yellow stripes, it may look odd, but it fits more with the Captain's uniform, which these are based off of, or look similar to. I have also slightly updated some of the sprites best I could, and also updated the turtlenecks to fit with the rest of the turtlenecks the server has. This is purely just to make it look good in-game, and also fit in with the rest of the clothing. The vibrancy might look off, I'm not that much of a spriter.

## Proof Of Testing

image

## Sprites
COMMANDER
image

OFFICIAL (And Turtleneck Official)
image

ERT OFFICERS
image

CENTCOM REPLICAS
image

MISCELLANEOUS SPRITES
image

## Changelog

:cl:
add: Adds the M4a5 pistol, and CentCom Sabre to the NTC's locker.
add: Adds the CentCom Sabre to the CentCom Commanders.
add: Adds different sprites to the CentCom uniforms, and clothing.
add: Adds a CentCom Carapace, and CentCom Gloves that aren't Naval.
add: Adds the Tactical Turtleneck in the loadout for the Blueshield. (Greenshield).
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
> TURTLENECK SPRITES AREN'T MINE

Credit the artist then???

**Comment by ChromeFoxxity** [comment]
> > TURTLENECK SPRITES AREN'T MINE
> 
> Credit the artist then???
> 
> I do still have a problem with NTCs having a bunch of stuff like ceremonial swords that only serve to inflate their egos beyond their actual position as a corpo lawyer. Its already annoying to play captain and have players with this job act like they're higher on the food chain then I am.
> 
> They also don't need a pistol upgrade, they are not CC reps.
> 
> https://github.com/Bubberstation/Bubberstation/blob/12f61ac2aed80f3288ecb96d766435655da9731e/modular_skyrat/modules/modular_weapons/code/company_and_or_faction_based/romulus_technology/ammo/pistol.dm#L13

While I do agree that they probably shouldn't act like that, they still technically are CC Reps. There's quite literally an alt title (was removed, but re-added again) that is literally CC Rep. It's either or at this point, and the pistol is self defense. I personally dislike using lasers anyway. And they used to have this pistol as well.

**Comment by YakumoChen** [comment]
NTCs are not full CC reps, this has been made very clear in the past.

They also do not need gun creep, their guns were explicitly removed before for the same reasons. If they want more guns, they can use cargo.

**Comment by ReturnToZender** [comment]
Please don't give the NTC a M4A5 or M5A5, or a sabre. I will have to remove both later.

**Comment by YakumoChen** [comment]
> Why wouldn't they just casually give a sword to their representatives,

Why would they give a sword meant for decorated, high-ranking officers to a CC intern?

**Comment by ChromeFoxxity** [comment]
> Please don't give the NTC a M4A5 or M5A5, or a sabre. I will have to remove both later.
> 
> Aren't you banned from Consultant for this sort of thing?

No. But this isn't about that, a sabre most of the time in my regards is just for emergency self defense. In most cases, it's never even used. Like most people who buy the cargo sabre, they never even use it at times. It's merely just for something to wear, even then. You can remove the pistol if you'd like, since that pistol hasn't been used by anything. But the sabre is a thing a lot of people have said was a neat idea for Rep.

**Comment by ChromeFoxxity** [comment]
> > Why wouldn't they just casually give a sword to their representatives,
> 
> Why would they give a sword meant for decorated, high-ranking officers to a CC intern?

Asking that would be asking why they get access to a formal coat, renamed officer's coat, and sometimes Commander clothing. Most admins know me for being a NTC that lives on being the definition of a CentCom official.

**Comment by YakumoChen** [comment]
> > > Why wouldn't they just casually give a sword to their representatives,
> > 
> > 
> > Why would they give a sword meant for decorated, high-ranking officers to a CC intern?
> 
> Asking that would be asking why they get access to a formal coat, renamed officer's coat, and sometimes Commander clothing. Most admins know me for being a NTC that lives on being the definition of a CentCom official.

You're free to roleplay whatever you want but per the wiki, you have zero authority outside your words and fax machine access

**Comment by ChromeFoxxity** [comment]
> > > > Why wouldn't they just casually give a sword to their representatives,
> > > 
> > > 
> > > Why would they give a sword meant for decorated, high-ranking officers to a CC intern?
> > 
> > 
> > Asking that would be asking why they get access to a formal coat, renamed officer's coat, and sometimes Commander clothing. Most admins know me for being a NTC that lives on being the definition of a CentCom official.
> 
> You're free to roleplay whatever you want but per the wiki, you have zero authority outside your words and fax machine access

You're considering this on the OOC side of things, however IC, NTC is a CentCom employee, and is higher in stature and position. HOWEVER, not on the station. They are merely just an inspector, but without the authority, for being a freely playable role, and all.

**Comment by YakumoChen** [comment]
> > > > > Why wouldn't they just casually give a sword to their representatives,
> > > > 
> > > > 
> > > > Why would they give a sword meant for decorated, high-ranking officers to a CC intern?
> > > 
> > > 
> > > Asking that would be asking why they get access to a formal coat, renamed officer's coat, and sometimes Commander clothing. Most admins know me for being a NTC that lives on being the definition of a CentCom official.
> > 
> > 
> > You're free to roleplay whatever you want but per the wiki, you have zero authority outside your words and fax machine access
> 
> You're considering this on the OOC side of things, however IC, NTC is a CentCom employee, and is higher in stature and position. HOWEVER, not on the station. They are merely just an inspector, but without the authority, for being a freely playable role, and all.

You shouldn't get an officers sword unless you're actually coming on the station as a CC officer of actual rank.

**Comment by ChromeFoxxity** [comment]
> > > > > > Why wouldn't they just casually give a sword to their representatives,
> > > > > 
> > > > > 
> > > > > Why would they give a sword meant for decorated, high-ranking officers to a CC intern?
> > > > 
> > > > 
> > > > Asking that would be asking why they get access to a formal coat, renamed officer's coat, and sometimes Commander clothing. Most admins know me for being a NTC that lives on being the definition of a CentCom official.
> > > 
> > > 
> > > You're free to roleplay whatever you want but per the wiki, you have zero authority outside your words and fax machine access
> > 
> > 
> > You're considering this on the OOC side of things, however IC, NTC is a CentCom employee, and is higher in stature and position. HOWEVER, not on the station. They are merely just an inspector, but without the authority, for being a freely playable role, and all.
> 
> You shouldn't get an officers sword unless you're actually coming on the station as a CC officer of actual rank.

You're forgetting everyone can literally buy a 300 credit sword from cargo. Basically anyone can have it shift-start, and Rep can get it too. This sword is barely stronger than the cargo sword, but it's shift-start, it barely changes anything except maybe 5 more damage to a limb, and saving you 300 credits.

**Comment by nikothedude** [comment]
youre not actually supposed to be getting swords roundstart dude, thats powergaming

**Comment by ChromeFoxxity** [comment]
> youre not actually supposed to be getting swords roundstart dude, thats powergaming

How. Rep isn't even combative, the sword is just for show, it's literally a costume piece if anything.

**Comment by nikothedude** [comment]
> > youre not actually supposed to be getting swords roundstart dude, thats powergaming
> 
> How. Rep isn't even combative, the sword is just for show, it's literally a costume piece if anything.

okay, tell that to the guy that just got chopped up by it after trying to jump the guy that bought a sword roundstart

**Comment by YakumoChen** [comment]
> It MIGHT BE expensive, but you're ALSO forgetting that they give all of their ERT's the highest tech.

The ERTs are _ranking CC Officers_ that come to the station to deal with emergencies, obviously they are equipped for that purpose

**Comment by ChromeFoxxity** [comment]
> > It MIGHT BE expensive, but you're ALSO forgetting that they give all of their ERT's the highest tech.
> 
> The ERTs are _ranking CC Officers_ that come to the station to deal with emergencies, obviously they are equipped for that purpose

Do you want me to just make a cheaper sword for specifically the Rep? Because to be honest, I can do that. A FULL Ceremonial sword, that is even worse than the cargo sword, I'll do it. Honest to god.

**Comment by ChromeFoxxity** [comment]
> > > youre not actually supposed to be getting swords roundstart dude, thats powergaming
> > 
> > 
> > How. Rep isn't even combative, the sword is just for show, it's literally a costume piece if anything.
> 
> okay, tell that to the guy that just got chopped up by it after trying to jump the guy that bought a sword roundstart

What are you even talking about? For as long as I remember, I've been buying a sabre from cargo round-start every shift I'm NTC. I enjoy having it.

**Comment by YakumoChen** [comment]
I take issue with the fact that its a ceremonial sword for an unranked CC staff on station

**Comment by nikothedude** [comment]
1. you really should NOT be buying a sword roundstart
2. also yes can we cut down on the gun and weapon creep its very much getting on my nerves

**Comment by YakumoChen** [comment]
> What are you even talking about? For as long as I remember, I've been buying a sabre from cargo round-start every shift I'm NTC. I enjoy having it.

Openly toeing the rules is not a free pass to break them, you can always be ahelped for problematic behaviour

**Comment by ChromeFoxxity** [comment]
> > What are you even talking about? For as long as I remember, I've been buying a sabre from cargo round-start every shift I'm NTC. I enjoy having it.
> 
> Openly toeing the rules is not a free pass to break them, you can always be ahelped for problematic behaviour

What rule is that even breaking.

**Comment by YakumoChen** [comment]
> > > What are you even talking about? For as long as I remember, I've been buying a sabre from cargo round-start every shift I'm NTC. I enjoy having it.
> > 
> > 
> > Openly toeing the rules is not a free pass to break them, you can always be ahelped for problematic behaviour
> 
> What rule is that even breaking.

Powergaming, and you keep flipping between "it's for show" and "it's for defense" as here

> No. But this isn't about that, a sabre most of the time in my regards is just for emergency self defense. 

Also you still have not given proper credit for sprites used, which is generally required for PRs.

**Comment by ChromeFoxxity** [comment]
> > > > What are you even talking about? For as long as I remember, I've been buying a sabre from cargo round-start every shift I'm NTC. I enjoy having it.
> > > 
> > > 
> > > Openly toeing the rules is not a free pass to break them, you can always be ahelped for problematic behaviour
> > 
> > 
> > What rule is that even breaking.
> 
> Powergaming, and you keep flipping between "it's for show" and "it's for defense" as here
> 
> > No. But this isn't about that, a sabre most of the time in my regards is just for emergency self defense.
> 
> Also you still have not given proper credit for sprites used, which is generally required for PRs.

I have given credit by default by not saying I'm the one who made it, I know I should say the specific name, but I don't know the first thing to even going and finding it. I'm not familiar with everything in Github.

And, about the whole "Defense, and Show" thing.. It's a sword. It's both, you're not gonna get any action out of it 9 times out of 10 shifts.

And the powergaming? No. My character is just so uptight he has the requirement of having a sword just to look good. I literally don't use it AT ALL. If I wanted to defend myself, I would use the gun I was given, or the baton. I have no use for it, but it is something that I wear. It's not powergaming, if it's a costume piece.

**Comment by YakumoChen** [comment]
If you cannot properly attribute the source of sprites used, you should not be using them.

**Comment by ChromeFoxxity** [comment]
> If you cannot properly attribute the source of sprites used, you should not be using them.

Why don't you help me to find it then.

**Comment by nikothedude** [comment]
im very glad youre virtuous and dont use the sword to powergame

unfortunately, you are not the only NTR player
unfortunately, this does not justify the feature creep of giving them a sword

you want to give NTR a sword? make a cheap plastic one that does like. replica katana damage. itd be a silly injoke about how centcom doesnt care much while still looking badass

**Comment by YakumoChen** [comment]
> > If you cannot properly attribute the source of sprites used, you should not be using them.
> 
> Why don't you help me to find it then.

It's your PR.

If you can't do the basics of attribution, remove the offending part.

**Comment by ChromeFoxxity** [comment]
> im very glad youre virtuous and dont use the sword to powergame
> 
> unfortunately, you are not the only NTR player unfortunately, this does not justify the feature creep of giving them a sword
> 
> you want to give NTR a sword? make a cheap plastic one that does like. replica katana damage. itd be a silly injoke about how centcom doesnt care much while still looking badass

As I said, I could make a weaker sword. I literally don't mind doing this. I just want something to wear on my belt slot.

**Comment by Majkl-J** [comment]
Guys holy shit who's gonna read all that I was asleep

**Comment by ChromeFoxxity** [comment]
> Guys holy shit who's gonna read all that I was asleep

You must suffer as I have.. Also, it's just an argument over a sword being ceremonial being given to the rep.

**Comment by YakumoChen** [comment]
I could point out you're still giving the rep a 15 force sword with a huge wound chance, and that the server host told you to remove it.

**Comment by ReturnToZender** [comment]
> I could point out you're still giving the rep a 15 force sword with a huge wound chance, and that the server host told you to remove it.

My roleplay role shan't become a loot bag. The fact that the NTC is soft power allows it to effectively negotiate with crew and people who aren't crew, giving them a sword and lethal gun would take from that. The SC-2 isn't a placeholder, it's the intended weapon-- it is very visually apparent when it is on you, and that it's a non-lethal weapon, as opposed to the M5A5. This is neglecting to mention the _inherent_ difficulties in giving any role a ballistic weapon.

If you need a sword to be listened to, your pen is bad.

**Comment by ChromeFoxxity** [comment]
> > I could point out you're still giving the rep a 15 force sword with a huge wound chance, and that the server host told you to remove it.
> 
> Seconded, but there is an important overall reason-- my roleplay role shan't become a loot bag. The fact that the NTC is soft power allows it to effectively negotiate with crew and people who aren't crew, giving them a sword and lethal gun would take from that. The SC-2 isn't a placeholder, it's the intended weapon-- it is very visually apparent when it is on you, and that it's a non-lethal weapon, as opposed to the M5A5. This is neglecting to mention the _inherent_ difficulties in giving any role a ballistic weapon.
> 
> If you need a sword to be listened to, your pen is bad.

I mean, come on. The Rep sword is even weaker than the cargo one. It may be lethal, but you can literally use lethal mode on an SC-2, so that completely negates the whole "non-lethal" look, I mean, yeah, Pistols are full lethal, but it still has a lethal mode. A sword is really only to just for ABSOLUTE emergency, like a Captain's. Captains never really get to use theirs, but it's a last resort in defense. Why would I use a shitty sabre if I had a gun? As I said before, it's just merely for the looks. I'm not trying to be any hostile, hell, even a damn combat or survival knife would do the same as this sabre, but they're hidden.

**Comment by YakumoChen** [comment]
Cap's sabre is the best roundstart weapon on the station and easily top tier for melee on melee combat.

**Comment by ChromeFoxxity** [comment]
> Cap's sabre is the best roundstart melee weapon on the station and easily top tier for melee on melee combat.

Yes, but Captains only defend themselves if they have to. Kinda like a NTC. But still.

**Comment by ChromeFoxxity** [comment]
Also, almost every other NTC I know usually plays with the cargo sabre on them, I'm just making it easier for them..

**Comment by YakumoChen** [comment]
I think what the top moff was trying to say is that the pen is mightier than the sword, and perhaps the Consultant should be open-carrying that instead

**Comment by YakumoChen** [comment]
The captain also gets a sabre because again, I cannot stress this enough,  they are a **_high ranking decorated officer_** on the station and also a walking loot bag and the show of force is a visible deterrent.

**Comment by Majkl-J** [comment]
I'm not reading all the constant back and forth, we'll be discussing what changes are required in the maint team then unlocking this again

**Comment by Cyprex** [comment]
This PR is a mess. In the future you _need_ to atomize changes- you can't just do a resprite and then change the loadouts at the same time in a way that affects balance so much.

> No. But this isn't about that, a sabre most of the time in my regards is just for emergency self defense. In most cases, it's never even used. Like most people who buy the cargo sabre, they never even use it at times. It's merely just for something to wear, even then. You can remove the pistol if you'd like, since that pistol hasn't been used by anything. But the sabre is a thing a lot of people have said was a neat idea for Rep.
> 
> Consider the Captain's. It's the strongest one, yet they never really use it unless they are up in their face. And the Rep is specifically to avoid any combat when they can't help it. So this is just a last fallback defense.

What? This argument is just crap.

Zenders arguments were frankly pretty good- soft power and not becoming a loot bag. Fights between CC & Crew are very messy, and sending a few powerful players to slaughter the server isn't usually fun- Deathsquads exist for hard power already. CC Reps should be listened to because of them being CC, not because of their equipment.

**Comment by Majkl-J** [comment]
I agree with @Cyprex, this needs to be atomized into smaller batches. As of current this is a large set of several big changes that is  terrible to review, and even worse to discuss/test. Do icons, loadouts, and item changes all independently, and feel free to reopen the atomized parts of the PR during the freeze, no need to ask us.

**Pull request closed without merging**
