### PR TITLE
Lavaland Dauntless tweaks

### PR DESCRIPTION
**Pull request by tmyqlfpir**
## About The Pull Request

This PR tweaks the layout for the lavaland Dauntless base. It does the following:
* Expand the hanger by 1 unit so blackmarket trader shuttle can dock without clipping onto distro pipes
* Redo dorms from scratch so two dorm rooms have lava windows (complete with privacy shutters)
* Tweak layout for kitchen and hydro so they are not as cramped
* Tweak layout for medical to have more gawking area (it is a common place to congregate)
* Readded Insurgent Care healthbot from DS-2 into medbay
* Wrench down R&D console in research
* Add syndie soap bar to showers

## Why It's Good For The Game

This is directly in response to feedback from players who regularly play on Dauntless.

## Proof Of Testing

preview

This is an older screenshot composite of the new layout.
**Please ignore the dense rock, jukebox, extra crematorium and holofan for the turbine** - those were tests and are not included in this PR.

This is the blackmarket shuttle fitting inside neatly.

## Changelog

:cl:
qol: Tweak layout of Dauntless kitchen, dorms and medbay
/:cl:

### CODE REVIEW

**Review by Majkl-J — COMMENTED** [review]
You will have to fix the pipe network CI.

**Review by Majkl-J — COMMENTED** [review]
I'll run some local testing on this to see it for myself, but looks good. Also, unrelated, but I do wonder if it would be possible to swap chemistry and surgery, because sometimes someone just explodes and subsequently cuts into the plasma tank

**Comment by StrangeWeirdKitten** [comment]
I approve people other than me working on my things. It looks good.

**Comment by shellspeed1** [comment]
Would it be possible to sneak in a colony fabricator for interdyne with all of these changes as well? Alot of the flatpack machines are perfect for them to mess with as they are already on lavaland.

**Comment by Majkl-J** [comment]
I'm not opposed to the above suggestion

**Comment by captainfrost20** [comment]
I cant remember if its been fixed as I havent been on dauntless in a moment but all of the multi layer adapters under the atmos tanks (oxygen, N2, plasma) are OMNI. 
dauntless

**Comment by captainfrost20** [comment]
> They're still OMNI. What color should they be instead?

Anything that isnt OMNI, really. You could do N2 as yellow, O2 as light blue, and plasma as pink. Or just copy whatever PT does for its color coating.

**Comment by captainfrost20** [comment]
You rock!

**Pull request merged**
