### PR TITLE
[Ready] Firelock (and air alarm) Overhaul

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Changes how firelocks automatically trigger. Firelocks are handled completely by the air alarm, and don't have their own atmos checks.

Reverts firelock crowbar behavior back to /tg/'s behavior.

Actually makes it so that crowbars stay open when forced open via right click.

Firelocks no longer automatically close when forced open via manual override (alt click). Reduces manual override time from 10 seconds to 5 seconds.

Changes firelock sprites to be less visible when not active.

Air alarms slowly heat the room if the temperature is too low.

## Why It's Good For The Game

Firelocks are some of the worst and most annoying things to deal with in the game. They're incredibly inconsistent in terms of how they actually function, and can be a downright nuisance to deal with. This PR makes it so that firelocks are controlled by the area's air alarm status, thus eliminating any confusion as to why the shutters keep fucking closing for no real reason.

I recommend a testmerge for this so feedback can be given about the new system given this functionally alters the power of breaches. As a consequence of this PR, average case scenario is that adjacent rooms will run into atmos issues as well, but they will be much easier to repair and diagnose.

## Changelog

:cl: BurgerBB
add: Firelocks are triggered only by air alarms (or manual input). Reverts firelocks back to /tg/'s behavior, and fixes a lot of bugs. The description for examining firelocks is now actually accurate!
add: Air alarms slowly heat the room if the temperature is too low.
/:cl:

### CODE REVIEW

**Comment by Serxule** [comment]
> Firelocks no longer automatically close when forced open.

they already do this if you open one and stay standing next to it (and close otherwise), this will just result in spacing/fires spreading much further than they should

**Comment by DeerJesus** [comment]
PR this upstream to tg. Please. Please for the love of god.

**Comment by BurgerLUA** [comment]
> PR this upstream to tg. Please. Please for the love of god.

If it works here, and /tg/ is okay with it, they can probably easily port it.

**Comment by Kapu1178** [comment]
you are going to find out very quickly why doing this requires more work.

**Comment by BurgerLUA** [comment]
testmerges are good

**Comment by BurgerLUA** [comment]
> This is going to create so many issues. Your problem is, in its root, "the firelock sound is annoying" - which this doesn't even fix.
> 
> It's going to be a nightmare in terms of the entire station getting vented - something that can _already_ be an issue

It's not the sound. It's just generally the inability for firelocks to properly reset because they detect their own atmos.

**Comment by Detective-Google** [comment]
might as well throw it on as a testmerge and give it a try

**Comment by TripleShades** [comment]
The new firelock sprites make it extremely hard to tell if an airlock has an existing firelock, making replacement after damages annoying.
image

**Comment by BurgerLUA** [comment]
> The new firelock sprites make it extremely hard to tell if an airlock has an existing firelock, making replacement after damages annoying. It's also much, much harder to properly crowbar down/borg click firelocks into the closed state. image

Emergency shutters have an invisible hitbox that you can click on. You don't have to be pixel perfect.
It actually has more clickable area than the current shutters.

**Comment by TripleShades** [comment]
> > The new firelock sprites make it extremely hard to tell if an airlock has an existing firelock, making replacement after damages annoying. It's also much, much harder to properly crowbar down/borg click firelocks into the closed state. image
> 
> Emergency shutters have an invisible hitbox that you can click on. You don't have to be pixel perfect. It actually has more clickable area than the current shutters.

This still does not address the visibility issue. It's not apparent when it's not a hallway firelock, so the majority of airlocks next to walls and other airlocks.

**Comment by Eastwardrope** [comment]
Something on this as well AIs can't hold open firelocks for any reason if the AI clicks one that's active it'll immediately drop back down IDK if that's in the purview of this PR though.

**Comment by BurgerLUA** [comment]
> Something on this as well AIs can't hold open firelocks for any reason if the AI clicks one that's active it'll immediately drop back down IDK if that's in the purview of this PR though.

Does it work when right clicking?

**Comment by Eastwardrope** [comment]
No there's not even an option for it. It's been an issue for awhile for
seemingly no reason. Like if it's to stop AIs from vacuuming out the
station or spreading fire around they can just disable the alarms

**Comment by nevimer** [comment]
This was difficult for me with my vision issues - I think it's a step backwords in accessibility for an already inaccessible game. It should keep the original colours and shapes if anything.

**Comment by BurgerLUA** [comment]
> This was difficult for me with my vision issues - I think it's a step backwords in accessibility for an already inaccessible game. It should keep the original colours and shapes if anything.

Do you mean the idle sprites? I agree, I could probably make them more visible.

**Comment by BurgerLUA** [comment]
image

sprites were updated

**Comment by StrangeWeirdKitten** [comment]
Marked as Stale for now since I'm trying to push decisions for old PRs, but it would need @nevimer's approval or disapproval since he's handling this.

**Comment by nevimer** [comment]
Testmerge worthy

**Comment by KareRott** [comment]
Please remove the part about air alarms producing heat. That is not adding fun to the game, it's just removing a task from atmos techs.

**Comment by KareRott** [comment]
Atmos techs are suppose to deal with fire alarms. It makes absolutely no sense to remove this task from engineers and atmos techs unless you are doing it purely because such atmos techs and engineers are not there due to low pop. Responding to alarms is half of what engineering is. Don't take that away with automated garbage like this.

**Comment by ChakatStormCloud** [comment]
Honestly this entire PR is throwing the baby out with the bathwater, 90% of the buggyness is caused by closed doors with a firelock holding onto problem air, all firelocks need is to check if their turf is either closed turf or blocked on all sides, and maybe a var to make specific ones just not check at all. (plus the crowbar and override issues, those need fixing.)

plus the heating power of the alarms is enough that it's going to remove cold air management entirely, even in breaches.

**I seriously suggest this PR be atomised** into 1 with the crowbar/over ride changes, 1 with the changes to how they're triggered, and 1 with the air alarm heating, let those features stand on their own merits instead of being crammed in at once

**Comment by BurgerLUA** [comment]
I disagree entirely

**Comment by StrangeWeirdKitten** [comment]
I want to run this for a week or two on a test merge then come to a decision.

**Comment by KareRott** [comment]
The firelocks are not that much of a problem as they currently are. When ever it seems like there is an issue with them, they won't stop closing, it's because they are sensing the heat or cold in the tile next to them. This can be a tile that is a wall, mind you. Which the only thing you can currently do to fix it is reset the firelock by taking it apart then wrenching it back down again. If a wall tile was an issue like that, it means that engineers had fixed a breach there and are still working on it. They could still fix the firelock while they are in the area.

**Comment by KareRott** [comment]
The fire alarm thing just needs to be  removed, it's not going to help at all. It's only removing atmos jobs. 

> I want to run this for a week or two on a test merge then come to a decision.

I won't be playing for that week if it is merged.

**Comment by Cyprex** [comment]
> Changes how firelocks automatically trigger. Firelocks are handled completely by the air alarm, and don't have their own atmos checks.

Uhhhh... I fail to see how this is desirable? I imagine you would want them to lock individually around a spaced portion, rather than lock down the entire central hallway? Kapu's comment also gives me pause here. That said I'd have to see how this plays out ingame.
> Reverts firelock crowbar behavior back to /tg/'s behavior.

Explanation: You can currently alt-click firelocks even without a crowbar to open them after 10 seconds. This lowers that down to 5 seconds, which is tg's value.
> Actually makes it so that crowbars stay open when forced open via right click.

Sure, whatever
> Firelocks no longer automatically close when forced open via manual override (alt click). Reduces manual override time from 10 seconds to 5 seconds.

Dunno? I guess this makes them a lot less annoying to deal with but also sorta defeats their purpose? Will they ever re-lock again of their own?
> Changes firelock sprites to be less visible when not active.

Why? it is sometimes important to know if a firelock exists. I think the way it currently is before this PR is fine.
> Air alarms slowly heat the room if the temperature is too low.

I dunno, seems to make atmos techs unnecessary as mentioned above? I can definitely see where you're coming from with this, making atmos issues less annoying- but I also think that it does indeed make atmos techs/heaters etc. less needed- I think mixing things up, making players react to issues leads to interesting gameplay! In particular that atmos tech fixing brig air could steal a few things... or things like that!

**Comment by StrangeWeirdKitten** [comment]
https://discordapp.com/channels/1059199070016655462/1071095123145924679 is the official feedback thread. I'm going to take a gander into the numbers and some local testing, with some discussion before giving this PR a trial run for a week.

I'm only interested in code-related comments on the repo and I'll be hiding all off-topic. I opened the discord channel to talk.

**Comment by mcmeiler** [comment]
> https://discordapp.com/channels/1059199070016655462/1071095123145924679 is the official feedback thread. I'm going to take a gander into the numbers and some local testing, with some discussion before giving this PR a trial run for a week.
> 
> I'm only interested in code-related comments on the repo and I'll be hiding all off-topic. I opened the discord channel to talk.

You linked #suggestions . Not the thread.
https://discord.com/channels/1059199070016655462/1168137211565309984

**Pull request merged**
