### PR TITLE
Un-Skyrats Demonic Frost Miner Arena: AKA - The Mining Site / Observation Pit

### PR DESCRIPTION
**Pull request by IgiariValkyr**
## About The Pull Request

Did you know that Skyrat made a version of the Demonic Frost Miner's arena that was a singular z-level in 2021?
Did you know it hasn't been maintained since?
Did you know we've still been running that same edit even though Demonic Frost Miner's arena has been updated visually by TG in 2023?

This PR fixes these Did You Knows by destroying the Skyrat variation entirely so that TG#78826 actually loads properly. This makes the ruin two z-levels again, a site above looking into the ice pit with entrances all around the edge (just jump, i dare you), and makes the pit far less of a solid flat ice plane and turns it into an actual mining site (the ruin is literally called Mining Site, I shit you not).

_**There is a known issue from both testing and [TG proper](https://github.com/tgstation/tgstation/issues/78870) where the top ruin can generate without the bottom. This is due to how Multi-Z Ruins place. The top is placed before the bottom, and if a ruin is already placed where the bottom will go, the arena will not generate, but the upper pit will generate. An example of this would be [if it generates over the Hearthkin Camp](https://files.catbox.moe/skyte4.png). I am currently looking into a fix at the moment, however it's not needed at the time given Ice Moon progression regularly is broken with Wendigo or the Clockwork Defender not spawning their ruins either. As well, this does not seem to ruin the aesthetic of the top ruin itself as it still serves as an observation point for the pit.**_
_**As such, I've decided to call the whole ruin Mining Site, but only Observation Pit if only the top generates.**_

## Why It's Good For The Game

Actually keeps us on par with TG and removes an unmaintained ruin from the code.
Changes the arena of Demonic Frost Miner so its not so stale (there's lore and a single wall to hide behind if you're scared and dead bodies wow)

## Proof Of Testing

<details>
<summary>Screenshots/Videos</summary>

### Successful Placement (Mining Site)
dreamseeker_2024-12-27_05-14-38

### Unsuccesful Placement (Observation Pit)
dreamseeker_2024-12-27_05-04-31

</details>

## Changelog

:cl:
fix: The updated arena for Demonic Frost Miner actually loads now
/:cl:

### CODE REVIEW

**Comment by Majkl-J** [comment]
The TG issue may have been fixed by me on tg recently with what I'm porting in https://github.com/Bubberstation/Bubberstation/pull/2628 but I'm not 100% sure

**Comment by IgiariValkyr** [comment]
> The TG issue may have been fixed by me on tg recently with what I'm porting in #2628 but I'm not 100% sure

I see you merged this, so I'm going to sync this branch to master then test it again. If it works, great. If not, well we're still in the same spot we are already so I don't really care lmao.

**Comment by IgiariValkyr** [comment]
5 consecutive reboots had it spawn with it properly together, so I want to say that you did fix it. That or I'm just exceedingly lucky with it spawning. I feel safer letting it be merged now.

**Comment by Majkl-J** [comment]
> 5 consecutive reboots had it spawn with it properly together, so I want to say that you did fix it. That or I'm just exceedingly lucky with it spawning. I feel safer letting it be merged now.

If it still happens here and there you know for sure I'll try and fix it

**Review by Majkl-J — APPROVED** [review]

**Comment by IgiariValkyr** [comment]
> > 5 consecutive reboots had it spawn with it properly together, so I want to say that you did fix it. That or I'm just exceedingly lucky with it spawning. I feel safer letting it be merged now.
> 
> If it still happens here and there you know for sure I'll try and fix it

As I mentioned, wendigo and clockwork both seem to also have the same (or related) spawning issue, so missing him every now and then is not that big of an issue. Just something that needs to be fixed occasionally. I’ll help if possible, even though I’m no coder.

**Pull request merged**
