### PR TITLE
Integrates Donator items into the vendors

### PR DESCRIPTION
**Pull request by theselfish**
## About The Pull Request
Title
If it was ACTUALLY locked, as in not commented out, it was left. Otherwise, they're in vendors around. As a bonus so is nearly every plushy.

## Why It's Good For The Game

I am on an endless crusade to purge loadout exclusive items from the game.

If you lose it, have it destroyed or straight up just want another one, it's not easy to get via a vendor. Yay! Wahoo! Yippie!

## Proof Of Testing

image
image
image
image
image
image
image
image
image
image
image
image
image

I'd take photos of the rest but trust me. It works.

## Changelog

:cl:
add: Non-locked Donator have been added to vendors. Collect them all!
/:cl:

### CODE REVIEW

**Review by projectkepler-ru — APPROVED** [review]
If any specific donator want it gone they can request it, otherwise this is fine

**Comment by xXPawnStarrXx** [comment]
I feel some should be put in more specific vendors, this can always be done later. (I.e. Hydrogen robes in atmos dispenser, command stuff in the command vendor, the ash drake skull in the ashwalker 'vendor'.)

**Comment by IgiariValkyr** [comment]
Hey wait a damn. You're outright removing this stuff from the loadouts too. Not cool!

**Comment by theselfish** [comment]
> I feel some should be put in more specific vendors, this can always be done later. (I.e. Hydrogen robes in atmos dispenser, command stuff in the command vendor, the ash drake skull in the ashwalker 'vendor'.)

Command stuff is in the command vendor.
The drake skull is in the costume vendor because it's a costume thing.
No idea what the robes are, I put them in the clothmate because it's just clothes.

**Pull request merged**
