### PR TITLE
M1911 as goodie

### PR DESCRIPTION
**Pull request by projectkepler-ru**
## About The Pull Request
You can now buy m1911 as goodie

Also updated the reshi revolvers icon
## Why It's Good For The Game
I calculated  the damage-to-credits ratio on how much are we spending to deal the same amount of damage and receive the benefit
alongside checking how long it'd take to get similar item, this is fairly reasonable cost. Considering the alternative of what I do to get the same damages

## Changelog

:cl:
add: Contract from Colt has been secured with NT and now we can buy m1911
image: icon updated for the reshi revolver
/:cl:

### CODE REVIEW

**Comment by IgiariValkyr** [comment]
Reminder that the tracker still uses 357 now instead of the 460 it initially did due to 460 being removed.

**Comment by projectkepler-ru** [comment]
> Reminder that the tracker still uses 357 now instead of the 460 it initially did due to 460 being removed.

im aware, the tracker will come back later, I don' have the energy to come up with all the things for it yet but I am just laying the groundwork for it now

**Comment by chemistrymain3** [comment]
is there any particular reason why the m1911 would be brought back

or, you know, exist

**Comment by coffeecoffeecoffee** [comment]
slightly different ballistics choices are good, actually
i think having ww2 era firearms as anything other than an ultra-rare 'budget cuts' station trait or a space loot spawn or something does kind of hurt the already-struggling atmosphere of the game though and i think it could use a reskin and rename. give is a spaceteen-eleven or something dawg

**Comment by projectkepler-ru** [comment]
> slightly different ballistics choices are good, actually i think having ww2 era firearms as anything other than an ultra-rare 'budget cuts' station trait or a space loot spawn or something does kind of hurt the already-struggling atmosphere of the game though and i think it could use a reskin and rename. give us a spaceteen-eleven or something

well its a gold trimmed m1911, i guess we can do something like that
regarding the theme

nothing i can do

**Comment by projectkepler-ru** [comment]
> is there any particular reason why the m1911 would be brought back
> 
> or, you know, exist

aren't you supposed to be banned

**Comment by Majkl-J** [comment]
> aren't you supposed to be banned

image

**Pull request merged**
