### PR TITLE
Stops misgendering Bubblegum

### PR DESCRIPTION
**Pull request by Superhats**
## About The Pull Request
Bubblegum has been a lady the whole time. 
image

## Why It's Good For The Game
Nuff said.

## Changelog

:cl:VrazzleDazzle
spellcheck: Did you know Bubblegum was female all along?
/:cl:

### CODE REVIEW

**Comment by StrangeWeirdKitten** [comment]
Evidence of such claims?

**Comment by Superhats** [comment]
> Evidence of such claims?

Refer to the message for getting your projectile deflected.

**Comment by StrangeWeirdKitten** [comment]
> > Evidence of such claims?
> 
> Refer to the message for getting your projectile deflected.

tbqh it's just TG inconsistancies. They're really ``gender = plural`` if you look down the mob tree a bit. No one ever bothered to check it. But I'm more leaning towards the multiple refrences of him being a king than a queen.

**Comment by Superhats** [comment]
Yeah, fair enough.

**Comment by StrangeWeirdKitten** [comment]
> Yeah, fair enough.

They have no gender, only rage and fury and they'll still beat your ass.

**Pull request closed without merging**
