### PR TITLE
[NOT MODULAR][TM] Nerfs Bluespace crystals

### PR DESCRIPTION
**Pull request by Swiftfeather**
## About The Pull Request

Adds a time to use bluespace crystals of a few seconds

Honestly this might be doable entirely without the uncalibrated delimb chance. We'll see how it tests out.

This one actually isn't a salt PR I'm just going off of how annoying it is as a ghostmain to watch people teleport away scott free when the odds aren't in their favor. Also this [suggestion's](https://discord.com/channels/1059199070016655462/1071095123145924679/1230587434773778462) results imply that players are kind of tired of it and I generally believe that if an overwhelming majority of respondents want something maybe that something isn't a bad idea.

## Why It's Good For The Game

Now that arcmining is creating infinite bluespace crystals we are seeing antags get literal stacks of them and be uncatchable the entire shift.

## Proof Of Testing

(Just pretend there's no delimbing and screaming because that's been removed)
image

## Changelog

:cl: Swiftfeather
balance: Makes bluespace crystal teleportation take time.
/:cl:

### CODE REVIEW

**Comment by SonicGotNuked** [comment]
Good

**Review by StrangeWeirdKitten — CHANGES_REQUESTED** [review]

**Comment by Swiftfeather** [comment]
I played with 1-4 seconds on local and 1 was way too short. Let's see how 3 does with a TM?

**Comment by projectkepler-ru** [comment]
Finally, I can throw BS crystal at people and delimb them

**Comment by Swiftfeather** [comment]
> Finally, I can throw BS crystal at people and delimb them

That's actually not how I set it up. I didn't make the delimb chance under the teleport proc, I put it under the using a crystal on yourself proc. But we're gonna try it with just a cooldown first and see how it turns out.

**Comment by BurgerLUA** [comment]
On Yogstation, teleporting from bluespace crystals makes you vomit. Maybe add that too while increasing the cooldown for delimbing.

**Comment by Swiftfeather** [comment]
> On Yogstation, teleporting from bluespace crystals makes you vomit. Maybe add that too while increasing the cooldown for delimbing.

I removed the delimbing. We're just gonna try with a cd for now.

**Comment by HissyNays** [comment]
While cooldown is good idea, delimbing seems too much, good that it's removed.

**Comment by The-Sun-In-Splendour** [comment]
Change "beings" to "begins".

**Pull request merged**
