### PR TITLE
Adds Nanotrasen Private Security as a ERT type

### PR DESCRIPTION
**Pull request by ChromeFoxxity**
## About The Pull Request

This adds NT Private Security as a possible ERT, EFFECTIVELY weaker than the average ERT, however stronger than the Interns. As a sort of small threat security force, armed with WT-550's, M1911's. The Commander of the squad is given a Advanced Taser (Originally a M5A4 pistol, but the mags weren't working). They're given boxes of cuffs, batons, and the Commander is also administered a telescopic shield, and reinforced bola.

## Why It's Good For The Game

They're mostly used for smaller threats that security is underequipped, or outmanned. It may just be Security. But they're armed, and given their possible numbers, this could be a easy way to handle small threats like a out of control Traitor, or changeling by chance These are terrible examples, but you get what I mean by small threats that the station cannot handle. Either way, they're what you need for when a whole ERT seems like too much. From small jobs to small threats, medium threats, or if you want to test the skill of the said ERT members and show the station you think little of them, throw them at a large threat. Can be also used for apprehension of individuals, and also be a strike team, or a defense team. Who cares! They're here at your disposal. Use them as you wish!

## Proof Of Testing

image
image
image
## Changelog

:cl:
add: Adds Private Security as an ERT.
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
> The Commander of the squad is given a NT-ARG 'Boarder'"

Have you tested this weapon? It's one of the strongest guns on base tg code lmao

**Comment by YakumoChen** [comment]
I also don't see how this is less strong than a code blue ERT, or even considered a good pick as a security force  

They're only armed with lethal weapons, which are also ballistics. This is the equivalent of calling in Shitcurity as an ERT. You intend this to bolster an understaffed security when this is functionally SWAT?

**Comment by ChromeFoxxity** [comment]
> > The Commander of the squad is given a NT-ARG 'Boarder'"
> 
> Have you tested this weapon? It's one of the strongest guns on base tg code lmao

Yeah, I've only figured that out recently, but. You know, that's one of the only other ballistic guns that NT uses.

**Comment by ChromeFoxxity** [comment]
> I also don't see how this is less strong than a code blue ERT, or even considered a good pick as a security force
> 
> They're only armed with lethal weapons, which are also ballistics. This is the equivalent of calling in Shitcurity as an ERT. You intend this to bolster an understaffed security when this is functionally SWAT?
> 
> It also doesn't mesh with the general expectation Nanotrasen uses energy weaponry.

Nanotrasen doesn't JUST use energy weapons. Private security namely use M1911's and WT550's. This is also accounting that fact.

**Comment by ReturnToZender** [comment]
The NT-ARG "Boarder" is the M90-Gl reskinned. Also, Nanotrasen ERTs use lasers.

**Review by Majkl-J — COMMENTED** [review]
Where are the sprites from?

**Comment by ChromeFoxxity** [comment]
> Where are the sprites from?

You're probably not gonna believe me. But I forgot we're apart of TG, they are non-Skyrat and Bubber security uniforms. Since they were replaced, I tried to go for the more classic approach of security on these guys.

**Comment by Cyprex** [comment]
I don't quite understand your response? Could you clarify?

**Comment by ChromeFoxxity** [comment]
> I don't quite understand your response, could you clarify?

They are in the generic code icons, however I added them modular-wise. Like they are already in the non-modular icons as uniforms but I forgot and added them on bubberstation modular files.

**Comment by Majkl-J** [comment]
> They are in the generic code icons, however I added them modular-wise. Like they are already in the non-modular icons as uniforms but I forgot and added them on bubberstation modular files.

Then simply reference the base files

**Review by Majkl-J — CHANGES_REQUESTED** [review]
Unresolved conflicts, and duplicate icons that should be relinked to the tg ones

**Comment by YakumoChen** [comment]
> The NT-ARG "Boarder" is the M90-Gl reskinned. Also, Nanotrasen ERTs use lasers.

This still needs resolved

**Comment by Majkl-J** [comment]
Closing this as stale due to reviews and conflicts being not adressed after a week, as well as uncertainty about the origins of the sprites amplified by not repathing them to the supposed tg variants

**Pull request closed without merging**
