### PR TITLE
Seedlings can no longer have the Perennial Growth (Repeatable Harvest) trait because I died to them once.

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Seedlings can no longer have the Perennial Growth (Repeatable Harvest) trait.
Decreased the TC cost from 8 to 3 to compensate.

## Why It's Good For The Game

This prevents botany traitors from having a near unlimited amount of powerful minions because of botany buffs PRs that made botany easier as well as rule changes that kind of prevent security from doing anything as it would be metagaming to assume the seedlings could be evil, as there is a common non-evil variant.

If you want to have more minions, work for them.

## Changelog

:cl: BurgerBB
balance: Seedlings can no longer have the Perennial Growth (Repeatable Harvest) trait. Decreased the TC cost from 8 to 3 to compensate.
/:cl:

### CODE REVIEW

**Review by Majkl-J — CHANGES_REQUESTED** [review]
Make it modular for the sake of Ozzo's mental health

**Comment by BurgerLUA** [comment]
It's not modular in case /tg/ changes or removes the feature.

**Comment by Majkl-J** [comment]
> It's not modular in case /tg/ changes or removes the feature.

If they change it it will add additional work on having to solve conflicts, if they remove it then there will be nothing for the traitor item to point to and the compiler will catch it, so it will be solved that way

**Comment by YakumoChen** [comment]
> It's not modular in case /tg/ changes or removes the feature.

upstream changing things in files is the entire point of modularisation, you're supposed to do it whenever possible to reduce code debt.

**Comment by BurgerLUA** [comment]
If /tg/station removes or changes how seedlings work in a similar PR, then that PR then a conflict warning will show up. If I made it modular, it would not show up in any sort of warning system or linters or runtime errors and will only ever be noticed in game.

**Comment by YakumoChen** [comment]
It'll throw an error on compile that something in the modular file is pointing to nothing, so it'll be easy to just disable or remove the file, instead of trawling through a code file and playing spot the difference.

**Comment by BurgerLUA** [comment]
No modular change would throw an error on compile because of how byond works.

**Comment by Majkl-J** [comment]
> No modular change would throw an error on compile because of how byond works.

image
So if tg removes seedlings this won't error is what you're saying?

**Comment by BurgerLUA** [comment]
> > No modular change would throw an error on compile because of how byond works.
> 
> image So if tg removes seedlings this won't error is what you're saying?

if /tg/ removes seedlings then an error will show up
If /tg/ removes seedling as an uplink item, an error won't show up

**Comment by DeerJesus** [comment]
Then how do you get more seeds?

**Comment by BurgerLUA** [comment]
> Then how do you get more seeds?

You buy more from the uplink.

**Review by projectkepler-ru — APPROVED** [review]

**Comment by projectkepler-ru** [comment]
having played as traitor botanist recently. even with just **5** of these things they're already rediculously strong, allowing them to be repeatedly replanted would make them just a more annoying version of fighting xenobiology slime except they can shoo projectiles at you.

**Pull request closed without merging**
