### PR TITLE
Revert "Adding Haydeez"

### PR DESCRIPTION
**Pull request by ReturnToZender**
## About The Pull Request
Reverts Bubberstation/Bubberstation#1826, aka the Haydeez borgs. They're overly sexualized human-adjacent sprites and most people don't like it, see comments on the original PR. All of the discourse around these borgs has not been positive, with the best reviews being a "meh" at best, and people don't like borgs that are so blatantly sexualized running around, making people uncomfortable. They should be converted to synth sprites at most.

Since this is a revert, I left the changelog section empty.

## Why It's Good For The Game
These borgs ruin my dogborg gameplay :( but they also too closely resemble synths and have no ability to cover up. They don't look particularly good, either

## Proof Of Testing
I did this with a web edit but if you need proof of testing I can still provide that

### CODE REVIEW

**Comment by theselfish** [comment]
Since we're removing overly sexualized borg sprites, I presume Raptor Borgs are next on the chopping block?

**Comment by ReturnToZender** [comment]
> Since we're removing overly sexualized borg sprites, I presume Raptor Borgs are next on the chopping block?
> 
> Edit: If we're removing stuff that makes players uncomfortable, I also presume that all the dogborgs are getting axed?

ok dogborg hater the freaks are talking

**Comment by theselfish** [comment]
> > Since we're removing overly sexualized borg sprites, I presume Raptor Borgs are next on the chopping block?
> > Edit: If we're removing stuff that makes players uncomfortable, I also presume that all the dogborgs are getting axed?
> 
> ok dogborg hater the freaks are talking

So no then. It's simply because you personally dislike the models, then?

**Comment by ReturnToZender** [comment]
> > > Since we're removing overly sexualized borg sprites, I presume Raptor Borgs are next on the chopping block?
> > > Edit: If we're removing stuff that makes players uncomfortable, I also presume that all the dogborgs are getting axed?
> > 
> > 
> > ok dogborg hater the freaks are talking
> 
> So no then. It's simply because you personally dislike the models, then?

Yeah I don't like 'em, I think they'd be massively improved as synth sprites, see the dollhouse set for what I'm getting at. Synths would also be able to cover up their massive chest.

**Comment by theselfish** [comment]
> > > > Since we're removing overly sexualized borg sprites, I presume Raptor Borgs are next on the chopping block?
> > > > Edit: If we're removing stuff that makes players uncomfortable, I also presume that all the dogborgs are getting axed?
> > > 
> > > 
> > > ok dogborg hater the freaks are talking
> > 
> > 
> > So no then. It's simply because you personally dislike the models, then?
> 
> Yeah I don't like 'em, I think they'd be massively improved as synth sprites, see the dollhouse set for what I'm getting at. Synths would also be able to cover up their massive chest.

You should edit your PR body to say that then, instead of trying to paint it as a modesty thing, then.

**Comment by Odairu** [comment]
> > > > > Since we're removing overly sexualized borg sprites, I presume Raptor Borgs are next on the chopping block?
> > > > > Edit: If we're removing stuff that makes players uncomfortable, I also presume that all the dogborgs are getting axed?
> > > > 
> > > > 
> > > > ok dogborg hater the freaks are talking
> > > 
> > > 
> > > So no then. It's simply because you personally dislike the models, then?
> > 
> > 
> > Yeah I don't like 'em, I think they'd be massively improved as synth sprites, see the dollhouse set for what I'm getting at. Synths would also be able to cover up their massive chest.
> 
> You should edit your PR body to say that then, instead of trying to paint it as a modesty thing.

Dog borgs are not overtly sexualized in their spriting, these are, so modesty is valid here. And frankly, dog/raptor borgs are obscenely popular, whereas these sprites, are not.

**Comment by theselfish** [comment]
> > > > > > Since we're removing overly sexualized borg sprites, I presume Raptor Borgs are next on the chopping block?
> > > > > > Edit: If we're removing stuff that makes players uncomfortable, I also presume that all the dogborgs are getting axed?
> > > > > 
> > > > > 
> > > > > ok dogborg hater the freaks are talking
> > > > 
> > > > 
> > > > So no then. It's simply because you personally dislike the models, then?
> > > 
> > > 
> > > Yeah I don't like 'em, I think they'd be massively improved as synth sprites, see the dollhouse set for what I'm getting at. Synths would also be able to cover up their massive chest.
> > 
> > 
> > You should edit your PR body to say that then, instead of trying to paint it as a modesty thing.
> 
> Dog borgs are not overtly sexualized in their spriting, these are, so modesty is valid here. And frankly, dog/raptor borgs are obscenely popular, whereas these sprites, are not.

So it's a popularity contest?
If so, there are a lot more sprites to remove.

Also, typically in the western world rear ends are considered a sexualized thing.
image
Having a defined, and large one would be considered obscene by most people.

**Comment by projectkepler-ru** [comment]
Cease your bickering on the sprite issues, if you, genuinely have concerns that are NOT already addressed
you should consider the following:

bring this up upon the #feedback or in relevant channel 
Thanks!
- Calvin

**Comment by StrangeWeirdKitten** [comment]
I'm going to flat out say that demanding it be worked into a synth shell is entirely out of scope of the original PR and especially with non-standard sprites. The original author of the PR has been entirely open with us and our feedback. I've already had multiple discussions with the other maintainers over the original PR. But unless Nevimer or Zirok decide to merge this PR, I'm pretty much going to close it in 48 hours.

**Comment by ReturnToZender** [comment]
> I'm going to flat out say that demanding it be worked into a synth shell is entirely out of scope of the original PR and especially with non-standard sprites. The original author of the PR has been entirely open with us and our feedback. I've already had multiple discussions with the other maintainers over the original PR. But unless Nevimer or Zirok decide to merge this PR, I'm pretty much going to close it in 48 hours.

Nevimer is explicitly on vacation and Zirok doesn't merge PRs, you deliberately chose not to mention any of the maintainers that dislike this change

**Comment by StrangeWeirdKitten** [comment]
Ozzo was a part of the initial discussions and pinged on discord and Swift is the only one that comes to mind. I said I'll test merge it for a bit, and I demanded an alt for the service model. My expectations were met. Especially Strange's expectations were met. and I had another brief discussion then hit merge.

If the original PR author is continuously working to improve their work, which they seem to be extremely willing to do, then I don't see the rush to revert these. If it's a bit down the line and they fall unmaintained, we can have another revert discussion. Regarding the sprite quality, ping Fluffy in a #feedback channel and give them some constructive feedback on the spriting. 

Obviously I am not going to waste my time working with someone, discussing with other maintainers, and helping them learn how to navigate our codebase and contribute to it if I have zero intentions to merge it. Especially turning around to revert it. If they want to work on it, and continue to work on it, then the borg model can stay and I belive that is only fair. I've said the same in regards to Raptor borgs with you and other contributors putting both time and money to improve them. It's not going to make or break the game, because it's not really that big of a change.

**Comment by ReturnToZender** [comment]
> Ozzo was a part of the initial discussions and pinged on discord and Swift is the only one that comes to mind. I said I'll test merge it for a bit, and I demanded an alt for the service model. My expectations were met. Especially Strange's expectations were met. and I had another brief discussion then hit merge later that day

image
image

**Comment by StrangeWeirdKitten** [comment]
image

I'm not omnipresent. But my point above still stands.

**Comment by ReturnToZender** [comment]
> I'm not omnipresent. But my point above basically sums up what I spoke about.

Sure, but neither of the maintainers you are referring to are going to give an opinion on this and you've given it a 48 hour deadline

**Comment by Swiftfeather** [comment]
Screenshot_20240803_010643_Discord

**Comment by theselfish** [comment]
> Screenshot_20240803_010643_Discord

image

**Comment by BurgerLUA** [comment]
The Haydee sprites could probably be merged if the size of the parts were reduced by half.

Here is an example of an edit done by me.

image

**Comment by GyrPhlymBaBumble** [comment]
> The Haydee sprites could probably be merged if the size of the parts were reduced by half.
> 
> Here is an example of an edit done by me.
> 
> image

This is legitimately uncomfortable for me to look at. It looks anorexic to me. anyways, I feel as if the sideview is the problem the users that ARE having a problem with are having issues with; but I'm not going to be reducing it. This feels like unnecessary hatred, to be honest. I'm currently working on engineering resprites to make them look more in-line with other engineering sprites but I haven't worked on it in a few days.



> Screenshot_20240803_010643_Discord

Swift I'm going to be honest I didn't even know this poll was a thing. I feel like if we're actually going to determine such a thing, for one we need more users to be aware of it, and for two, that's still showing my original borgs before I toned down the two service borgs that were offending the most amount of users



> Ozzo was a part of the initial discussions and pinged on discord and Swift is the only one that comes to mind. I said I'll test merge it for a bit, and I demanded an alt for the service model. My expectations were met. Especially Strange's expectations were met. and I had another brief discussion then hit merge later that day
> 
> If the original PR author is continuously working to improve their work, which they seem to be extremely willing to do, then I don't see the rush to revert these. If it's a bit down the line and they fall unmaintained, we can have another revert discussion. Regarding the sprite quality, ping Fluffy in a #feedback channel and give them some constructive feedback on the spriting.
> 
> Obviously I am not going to waste my time working with someone, discussing with other maintainers, and helping them learn how to navigate our codebase and contribute to it if I have zero intentions to merge it. Especially turning around to revert it. If they want to work on it, and continue to work on it, then the borg model can stay and I belive that is only fair. I've said the same in regards to Raptor borgs with you and other contributors putting both time and money to improve them. It's not going to make or break the game, because it's not really that big of a change.
> 
> I would like to add that they have been entirely open of trying to mess with ideas to add a little bit of a toggleable sprites. But our borg code quite litterally does not support that nor am I going to then turn around and demand they rework it to the point it can.

I haven't been open because I am entirely new to coding, but it does look like it would be possible to do rewriting the chameleon model's code but only having it pull from a list with those borgs in it, or something along those lines. If I did implement it I would be entirely happy with a "use this in private" order on it with punishment for noncompliance.

**Comment by SovietSpaghetti** [comment]
moffington being against these on account of being "oversexualized and bad sprites" while publicly admitting that he made the raptorborg's ass fatter is funny 
image

**Comment by Swiftfeather** [comment]
I was never offended by any of the sprites, they're more well made than some of our other borg sprites, you did a good job imo. I personally think they just look too human to be a cyborg.

**Comment by ReturnToZender** [comment]
> moffington being against these on account of being "oversexualized and bad sprites" while publicly admitting that he made the raptorborg's ass fatter is funny

The fatter asses was so they don't have an unfair advantage in combat, actually. They have an unusual sprite shape and I needed to make sure those features were exaggerated when I ported them to Bubberstation, because of our action RP environment. It was a balance feature, and a damn good one at that. I understand because most people weren't there at the time, Maintainerbus isn't exactly the most transparent, certainly wasn't then, but that's how it is.

**Comment by FoxxyRenamon** [comment]
> > The Haydee sprites could probably be merged if the size of the parts were reduced by half.
> > Here is an example of an edit done by me.
> > image
> 
> This is legitimately uncomfortable for me to look at. It looks anorexic to me. anyways, I feel as if the sideview is the problem the users that ARE having a problem with are having issues with; but I'm not going to be reducing it. This feels like unnecessary hatred, to be honest. I'm currently working on engineering resprites to make them look more in-line with other engineering sprites but I haven't worked on it in a few days.
> 
> > Screenshot_20240803_010643_Discord
> 
> Swift I'm going to be honest I didn't even know this poll was a thing. I feel like if we're actually going to determine such a thing, for one we need more users to be aware of it, and for two, that's still showing my original borgs before I toned down the two service borgs that were offending the most amount of users
> 
> image
> 
> > Ozzo was a part of the initial discussions and pinged on discord and Swift is the only one that comes to mind. I said I'll test merge it for a bit, and I demanded an alt for the service model. My expectations were met. Especially Strange's expectations were met. and I had another brief discussion then hit merge later that day
> > If the original PR author is continuously working to improve their work, which they seem to be extremely willing to do, then I don't see the rush to revert these. If it's a bit down the line and they fall unmaintained, we can have another revert discussion. Regarding the sprite quality, ping Fluffy in a #feedback channel and give them some constructive feedback on the spriting.
> > Obviously I am not going to waste my time working with someone, discussing with other maintainers, and helping them learn how to navigate our codebase and contribute to it if I have zero intentions to merge it. Especially turning around to revert it. If they want to work on it, and continue to work on it, then the borg model can stay and I belive that is only fair. I've said the same in regards to Raptor borgs with you and other contributors putting both time and money to improve them. It's not going to make or break the game, because it's not really that big of a change.
> > I would like to add that they have been entirely open of trying to mess with ideas to add a little bit of a toggleable sprites. But our borg code quite litterally does not support that nor am I going to then turn around and demand they rework it to the point it can.
> 
> I haven't been open because I am entirely new to coding, but it does look like it would be possible to do rewriting the chameleon model's code but only having it pull from a list with those borgs in it, or something along those lines. If I did implement it I would be entirely happy with a "use this in private" order on it with punishment for noncompliance.

I'm sorry but how exactly does that look anorexic to you? That's an extremely serious illness and im having a hard time seeing that at all on that sprite...

**Comment by theselfish** [comment]
@StrangeWeirdKitten It's been over 48 hours, as far as I can tell.

**Comment by Krypandenej** [comment]
could take the idea I was trying to pitch a while back and make haydee models mechanically restricted to cafe or dorms. Like, LustWish gets a special little borg projector that lets you disguise as Haydee. Only works in dorms, or in cafe/interlink. This way we can keep the model for the people who like it, and simultaneously prevent it from getting flaunted in public.

Failing that, may as well just push the commit already if people are getting this uncomfy over it. I have plenty of opinions on whenever or not this "fits" into bubber or not, but the bottom line is that we've been on this issue for weeks now with no end in sight. Just let splurt take the models for now, we can calm down, and then think about other ways of implementing it if people are interested

**Comment by StrangeWeirdKitten** [comment]
> @StrangeWeirdKitten It's been over 48 hours, as far as I can tell.

Yeah I've been in Virginia and away from home.

Anyway, I'm still not interested in continuously shifting the goal posts. My expectations for the merge were met and I've already previously outlined why I'm not reverting it. The contributor said they still wish to work on it and improve it, they've been continuously open for feedback, and that's still enough for me.

**Pull request closed without merging**
