### PR TITLE
Adds the Vortex Luxury Emergency Shuttle

### PR DESCRIPTION
**Pull request by ChromeFoxxity**
## About The Pull Request

Adds a very expensive, yet luxury shuttle for people to buy on the communications console. Includes a massive list of items that normally a shuttle wouldn't have. Can be bought on the Comms Console for 300k credits, EMAG not required.

Spare unique Head of Staff MOD's in Command's E.V.A. room.

NTC and Blueshield get CentCom MODsuits, Corporate, and Asset Protection. (it's the emergency shuttle, the round is basically over).

Shuttle comes with fully operational atmospherics, shocked window grilles, emergency window shutters in all rooms and garbage disposals.

Shuttle also comes with a cleanbot, hygienebot, medbot, and two secbots, one in brig, and one in common seating.

Command have 2 Authentication Devices, 3 mini energy guns in bridge, with 3 spare telescopic batons, a boozemat, as well as a combat medkit. Along with their unique Tarkon protolathe reskinned to be a Command protolathe. Not to also forget, a Request Console with announcement access.

Medical has advanced medical kits, a SAD, advanced surgery tools, vendors to vend supplies, a limbgrower with two spare beakers of synthflesh, as well as a Protolathe.

Security has 2 spare batons, a set of Redsec armor, an old SecTech (Non-Armadyne security vendor), Mindshield box, and a spare SC-2 Energy Carbine.

Engineering has the basics, but advanced tools, a corpse and 3 SMES's full of power to charge the window grilles. As well as 4 spare engineering MODsuits. Engineering also has a box of materials, to insert into the protolathes.

Atmospherics has the basics, but smart foam grenades incase of breaches in the shuttle, RPD's for no reason, and advanced tools. As well as 2 spare Atmospheric MODsuits.

# It's been tested, all works fine.

## Why It's Good For The Game

It's a good change for the game to give crew a different means of escape, after getting tons of money for a good job of Cargo, they deserve a nice trip home in one of the best evacuation shuttles. 

## After attempting to run.
image

## Looking In-Game.
image

## Changelog

:cl:
add: Added the Vortex-Class Luxury Evacuation Shuttle.
/:cl:

# Vortex-Class Luxury Evacuation Shuttle
image

### CODE REVIEW

**Comment by Arturlang** [comment]
Change your byond version into something that works, 515.1642 works, and actually test it.

**Comment by ChromeFoxxity** [comment]
> Change your byond version into something that works, 515.1642 works, and actually test it.

Yeah, I'll try. I just for some reason couldn't figure that out. One second.

**Comment by YakumoChen** [comment]
20k is paltry for "giving the crew overpowered gear"
Maybe 200k?

**Comment by ChromeFoxxity** [comment]
> 20k is paltry for "giving the crew overpowered gear". The QM can make that without effort on any given shift. Maybe 250k?

Let's put it this way. It's basic gear, considering it's gonna most likely be researched before they even start evacuation. And the fact that the Protolathes are also basic, just mobile. It's not exactly overpowered when it's on a ship that is leaving to end the round anyway, I could raise it to around 50k or 40k too.

**Comment by Doom-external** [comment]
I think the CC modsuits are too much, even if the round is _about_ to end, it hasn't ended yet and those are decently powerful, no matter who gets their hands on them in that time.

**Comment by ChromeFoxxity** [comment]
> I think the CC modsuits are too much, even if the round is _about_ to end, it hasn't ended yet and those are decently powerful, no matter who gets their hands on them in that time.
> 
> The shuttle itself looks promising, and should definitely sit at 40-50K.

Reminder, the CC Modsuits are access-locked, but I guess that doesn't stop people from hacking into them. What do you suppose I replace them with? I kinda wanted to give Rep a suit of their own, and the only one that really works with that is Corporate.

**Comment by NanoCats** [comment]
> > I think the CC modsuits are too much, even if the round is _about_ to end, it hasn't ended yet and those are decently powerful, no matter who gets their hands on them in that time.
> > The shuttle itself looks promising, and should definitely sit at 40-50K.
> 
> Reminder, the CC Modsuits are access-locked, but I guess that doesn't stop people from hacking into them. What do you suppose I replace them with? I kinda wanted to give Rep a suit of their own, and the only one that really works with that is Corporate.

You can disable the access requirements, and given that most people don't know how to hack modsuits, I think you should, given the gimmick is that it's an extremely pricy shuttle and people probably aren't going to have much time to fuck with it.

**Comment by YakumoChen** [comment]
> > 20k is paltry for "giving the crew overpowered gear". The QM can make that without effort on any given shift. Maybe 250k?
> 
> Let's put it this way. It's basic gear, considering it's gonna most likely be researched before they even start evacuation. And the fact that the Protolathes are also basic, just mobile. It's not exactly overpowered when it's on a ship that is leaving to end the round anyway, I could raise it to around 50k or 40k too.

One of each unique head of staff modsuit is not "unique gear"

Making it such a high price for such an obscenely geared shuttle makes buying it actually special. 

Cargo will always have an easy time making at least 100k in any given shift, this will just usurp the piercing shuttle or whatever as the current "expensive shuttle buy" in any given shift if the price is so low.

Not to mention all the extra gear makes hijacking a lot harder.

**Review by lessthnthree — APPROVED** [review]

**Pull request merged**
