### PR TITLE
Peacekeeper Job

### PR DESCRIPTION
**Pull request by ReturnToZender**
## About The Pull Request

This PR adds a new Security roleplay role, the Peacekeeper. It doubles as a learning job, and will be used to ease Security members into the job, as well as allowing for players who want to roleplay to have a position that doesn't take up normal Security Officer slots.

Part of the fabled Bubberstation RP update.

To-do:
Give the Peacekeeper jumpsuit a jumpskirt sprite.
Give the Peacekeeper a role icon, as well as an icon for the secHUD that's unique to it.

This PR is drafted until the sprites for this are ready.

## Why It's Good For The Game
Adds a much-needed roleplay role to Security, that should make playing as Security much more bearable if you're not looking to just hunt antags.

## Proof Of Testing
image
image
image

## Changelog

:cl: ReturnToZender
add: A new Security roleplay-only role, the Peacekeeper! Serve in negotiations and act as a more lite version of Security while you train for the job.
/:cl:

### CODE REVIEW

**Review by Majkl-J — COMMENTED** [review]
What is the mechanical purpose because these just seem like extra hands the sec really doesn't need, especially with how jumpy everyone is with arming up and lethaling antags recently. 

Also unrelated but an instant knockdown gun that can only be countered by a select few pieces of equipment is probably not too good as a beginner weapon (Especially since no glasses or secmasks block it, which will probably result in terrible friendlyfire)

**Comment by ReturnToZender** [comment]
> What is the mechanical purpose because these just seem like extra hands the sec really doesn't need, especially with how jumpy everyone is with arming up and lethaling antags recently.
> 
> Also unrelated but an instant knockdown gun that can only be countered by a select few pieces of equipment is probably not too good as a beginner weapon (Especially since no glasses or secmasks block it, which will probably result in terrible friendlyfire)

It's a learning job and it adds a much-needed roleplay role to the Security department. It allows someone to play a very lite Security officer without much equipment.
Sec masks block pepperballs, don't they? I know gas masks do.

**Comment by Majkl-J** [comment]
> > What is the mechanical purpose because these just seem like extra hands the sec really doesn't need, especially with how jumpy everyone is with arming up and lethaling antags recently.
> > Also unrelated but an instant knockdown gun that can only be countered by a select few pieces of equipment is probably not too good as a beginner weapon (Especially since no glasses or secmasks block it, which will probably result in terrible friendlyfire)
> 
> It's a learning job and it adds a much-needed roleplay role to the Security department. It allows someone to play a very lite Security officer without much equipment. Sec masks block pepperballs, don't they? I know gas masks do.

Sec masks don't block pepperspray, neither do glasses or most other equipment, and pepperballs are objectively better than most nonlethal options, 90% of the time they will be better than a disabler since it's an instant knockdown and the list of pepper immune items is really inconsistent and snowflaked

**Comment by CMDR-Gungnir** [comment]
May want to change its name since Peacekeeper is one of the more commonly chosen alt-titles for Security Officers, and a lot of existing gear is "Peacekeeper's (X)"

**Review by projectkepler-ru — CHANGES_REQUESTED** [review]
the name of the job needs to be changed because Peacekeepers are already used by most of sec equipment

We could have it named something like  Dispute Officer or Arbiter
(Don't forget to set their RPG title too to something like Fixer)

**Comment by Swiftfeather** [comment]
This is months inactive (aside from master merges), feel free to reopen if you get back to it.

**Pull request closed without merging**
