### PR TITLE
Remove backup calling

### PR DESCRIPTION
**Pull request by Shadow-Quill**
## About The Pull Request

Removes the backup feature from sechailers.

## Why It's Good For The Game

I've seen a lot of complaints about how the Sechailer's ability to, in one click, declare that you need help, and you're in X area isn't a super great feature. Sure, there are counterplays, but I think all in all, this feature is best replaced with ".s I need help in Dorm 4!"

Notably, because it's an action button, you can bind a key to activate it — don't even need to be accurate in a panic click, just hit J or something, and you summon the boys in redblue.

## Proof Of Testing

I deleted the file.

## Changelog
:cl:
del: Security hailers can no longer call for backup with one button. Back to speaking in your headsets!
/:cl:

### CODE REVIEW

**Comment by VickiMorris** [comment]
You'll need to remove the line from the tgstation.dme file as well

**Comment by sippykot** [comment]
yeah, i don't like this one

**Comment by rintherat** [comment]
if they do stay, I wish they weren't EARRAPE levels of loud

**Comment by MajManatee** [comment]
At the very least make it preventable with an EMP or some other counter

**Comment by Majkl-J** [comment]
> At the very least make it preventable with an EMP or some other counter

It already is, a jammer should work too though I have never extensively tested that.

**Comment by StrangeWeirdKitten** [comment]
No, this isn't something I'm going to remove.

**Pull request closed without merging**
