### PR TITLE
Removes Akula Lore Protection

### PR DESCRIPTION
**Pull request by StrangeWeirdKitten**
## About The Pull Request

Allows more customization

## Why It's Good For The Game

I don't like arbitary restrictions on species.

## Proof Of Testing

One line change

## Changelog

:cl:
config: Removes Akula Lore protection (Allows edit to species)
/:cl:

### CODE REVIEW

**Review by Majkl-J — CHANGES_REQUESTED** [review]
_Glares in modularity_

**Comment by ReturnToZender** [comment]
LET'S FUCKING GOOOOOOO

**Comment by ReturnToZender** [comment]
also set it to false instead

**Comment by Majkl-J** [comment]
> also set it to false instead

It's false by default

**Comment by StrangeWeirdKitten** [comment]
> _Glares in modularity_

>:( it's one line, but fine dad

**Review by Majkl-J — APPROVED** [review]

**Pull request merged**
