### PR TITLE
Remove flip sickness for freerunners

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request

Puts back in the check for freerunning trait when flipping. Also moves synthetic vomit to the vomit proc instead of typechecking on the emote.

## Why It's Good For The Game

The 8 points lets them flip.

## Proof Of Testing
<details>
<summary>Screenshots/Videos</summary>

image

</details>

## Changelog

:cl: LT3
fix: Freerunners are immune to flip and spin sickness
/:cl:

### CODE REVIEW

**Comment by Swiftfeather** [comment]
think we could slap this on spinning too?

**Comment by lessthnthree** [comment]
Yeah

**Comment by NargaInDisguise** [comment]
> think we could slap this on spinning too?

Make *spin require the trait? Or am I mis-interpreting?

**Comment by lessthnthree** [comment]
> > think we could slap this on spinning too?
> 
> Make *spin require the trait? Or am I mis-interpreting?

TG put a restriction on *spin so we'll make it unrestricted with the quirk.

**Review by Swiftfeather — APPROVED** [review]

**Pull request merged**
