### PR TITLE
Makes ascensions flavor only

### PR DESCRIPTION
**Pull request by nikothedude**
## About The Pull Request

Title.

You get an achievement, you functionally ascend, everything. However, you get no buffs.
Rewrites some descs of final rituals and ascension notifications to reflect this.

## Why It's Good For The Game

A criticism of "removing ascension" is that you're basically removing a core part of heretic. While I disagree, and stipulate that heretic can survive without ascension, I hope this might strike a middle ground, as ascension still exists as an incentive that communicates that you "won".

As previously mentioned, heretic ascensions are incredibly problematic. See https://github.com/Bubberstation/Bubberstation/pull/2078 for my previous criticisms.

I would also like to reflect burger's sentiment that heretic ascension represents a carrot-on-the-stick for our more gamer players, who obtain what is basically a psuedo-murderbone pass upon obtaining it. Escalation is relaxed, and more freedom is given to kill people. For a "gamer" player, this is a holy grail.

By removing the incentive of relaxed escalation and extreme power, we might be able to slow heretic to a point where A. People are more happy to interact with it (cannot actually end the round if we let them go), and B. Heretics are more encouraged to be a bit more creative with their antag

I think this PR should be, at minimum, test-merged, to see what effects it might have

## Proof Of Testing

<details>
<summary>Screenshots/Videos</summary>

I really wish I could load this up and test it, but I am notoriously bad at testing antag changes, esp prog antags
(It compiles, though)

</details>

## Changelog

:cl:
balance: Ascensions no longer have any material impact on the game other than an announcement
/:cl:

### CODE REVIEW

**Comment by Doom-external** [comment]
Im Sexmaster and I support this PR

**Comment by BurgerLUA** [comment]
I'm a master of sex and I support this PR.

**Comment by BurgerLUA** [comment]
This PR needs to be merged because it's clear that no matter what other things is done to heretic, people still game in order to get that sweet ascension.

Bubberstation has greentext and objectives removed and I don't think maintainers are interested in adding it because it causes the mentality that you need to get that greentext in order to "win" as antag, yet we have heretic ascensions which does that, and more.

Once a heretic ascends, it always results in a murderbone fest where heretics think the rules don't apply to them anymore and you're free to wreck. Not only that, but a lot of ascensions are just straight up "everyone dies" or something just as serious.

**Comment by GoreDem** [comment]
does this re-enable the disabled ascensions tho

**Comment by Arturlang** [comment]
There's no point to having ascensions if they're just flavour only, nobody is going to bother doing them unless they really want the achivements, if you're going to do this, I'd rather if you completely removed them

**Comment by nikothedude** [comment]
> There's no point to having ascensions if they're just flavour only, nobody is going to bother doing them unless they really want the achivements, if you're going to do this, I'd rather if you completely removed them

Traitors still do their objectives, despite getting no reward. The greentext is enough.

**Comment by Mitryll** [comment]
This basically kills the point of ascension. Why would you sacrifice anyone if you can't even do the last part that the sacrifices are meant to be a stepping stone to?

**Comment by nikothedude** [comment]
killing the main part of ascension is the goal yes

but if traitor proves anything it proves that meaningless goals with no reward is incentive enough for most players

**Comment by Mitryll** [comment]
> killing the main part of ascension is the goal yes
> 
> but if traitor proves anything it proves that meaningless goals with no reward is incentive enough for most players

Traitor was designed from the ground up to be a more free form antagonist and even its gearing system reflects that. Heretic on the other hand was always designed around the end goal of ascension and its power scaling as it gets closer and closer to doing so, removing ascensions basically just forces you to do Feast of the Owls every round, which is fun for a little bit as a naturally less freeform antag with your gearing and flavor options, will eventually result in not much being done with Heretic ever.

**Comment by nikothedude** [comment]
> There's no point to having ascensions if they're just flavour only, nobody is going to bother doing them unless they really want the achivements, if you're going to do this, I'd rather if you completely removed them

For the record if you'd merge a straight ascension removal I would absolutely go back and reopen my PR that did it

**Comment by nikothedude** [comment]
> > killing the main part of ascension is the goal yes
> > but if traitor proves anything it proves that meaningless goals with no reward is incentive enough for most players
> 
> Traitor was designed from the ground up to be a more free form antagonist and even its gearing system reflects that. Heretic on the other hand was always designed around the end goal of ascension and its power scaling as it gets closer and closer to doing so, removing ascensions basically just forces you to do Feast of the Owls every round, which is fun for a little bit as a naturally less freeform antag with your gearing and flavor options, will eventually result in not much being done with Heretic ever.

Look I'm not arguing this is a perfect fix, but I think you're really overblowing the issue here
The only thing changing is the massive power spike after ascension, which improves a lot of the issues I laid out in the PR body, mainly being paranoia of heretics (literally why ever treat heretics well since their end goal is to become insanely powerful) and what burger said

Heretics still progress, they still CAN ascend, but they don't have that power spike

**Comment by Mitryll** [comment]
> Heretics still progress, they still CAN ascend, but they don't have that power spike

Then what's the point? You might as well just ahelp for a custom announcement at that rate and have nothing different functionally happen.

**Comment by nikothedude** [comment]
the _point_ is to _win_

as i said before, traitors pursue their objectives for the SOLE REASON of "winning"

they dont get anything. they dont get anything except a greentext. heretic gets more, actually, heretic gets a full announcement and an achievement

i dont think the gearing/prog process would actually have much of an impact on how often people try to pursue ascension since it just. doesnt make sense? you say heretic si built around progression towards ascension and this doesnt change that, you just get closer and more powerful until you eventually just   win

again, the only difference is that you dont get overwhelmingly powerful and dont get relaxed escalation etc etc

**Comment by BurgerLUA** [comment]
It legitimately bothers me that, despite being an action-**roleplay** server, people are claiming that heretic is dead without ascensions because there is no end goal.

Despite many heretics not ascending, people still have fun with heretics because it can still provide action and roleplay. You don't need ascensions, or the goal of ascension, in order to have a good experience with heretic.

**Comment by StrangeWeirdKitten** [comment]
So the heretic will ascend. Then basically have a custom announcement that tells everyone to kill them still. This really isn't all that convincing for me versus just doing what I already said in #2080

Specifically this comment. 

image

**Comment by StrangeWeirdKitten** [comment]
The other really only problematic path I can think of is Knock, because all it does is spawn endless waves of murderbone mobs.

**Comment by Razurath** [comment]
Didn't we also double the sac requirements in another PR? So you have to, as per your objectives, kill eight people (two command staff) and 'survive' because after you get your funny announcement which makes you open game if all the bodies you've left behind didn't, and you get nothing for it. No other antag that isn't itself a round ending entity has this level of kill requirement and isn't either incredibly powerful at start or consistently die more then they get close to winning such as blob, space dragons, nukies and lone ops, they are all murderous antags and are geared as such. 

I think the discussion needs to look less at heretic ascension and more in how we handle heretics as an antag. They can RP, we've seen some fantastic heretic players who try their best to RP, but a trend I've seen is either heretics rp and don't do much as antags or they go murderbone because any attempt to RP and to make sacrifices just gets them absolutely dog piled and their round fucked sideways because they're treated as the threat they MIGHT become. This alteration to ascensions might change that some, but now risking the fury of station and ERT teams would be to... greentext. Some folks would do it, but I am pretty sure plenty of folks would just turn off heretic.

If the antag as an entity is so universally hated for how it reaches the culmination of its objectives and ascends to demi-god status, then why don't we either remove it or make it on par with nukies where only one heretic will spawn and the ROE is clear on both sides that they ARE a round ender?

**Comment by BurgerLUA** [comment]
Heretics design on this server is having its cake and eating it too.

It feels like we're trying to the both extremes of action and roleplay by giving it absurd metaprotections (roleplay) and then by allowing absurd mechanics (action) to take place. What ends up happening is that the action side abuses the metaprotections and you'll usually have a round once a week where heretic games the system without breaking any specific rules and gets their funny ascension.

**Comment by Razurath** [comment]
I didn't think we had metaprotections for any antag here?

**Comment by BurgerLUA** [comment]
> I didn't think we had metaprotections for any antag here?

Sorry, was a typo just meant space law protections.

I meant space law protections. Being a heretic alone is not considered a crime, thus allowing antagonists to basically get away with stealth ascending. Space Law says that while heretics are considered EORC, it should only apply to "significant threats" which just makes security officers uneasy whenever they want to arrest a heretic who isn't doing anything.

**Comment by SpringSkipper** [comment]
I would much rather see ascension paths be more balanced out with regard to eachother and for the outliers (worm, void, rust) to be less explosive/disruptive to the round. But that requires more dev effort than just removing them I suppose and I have no plans to make those changes myself.

**Comment by StrangeWeirdKitten** [comment]
This has been open for a few weeks and I'm just going to be the one to say no. I've pretty much said what needed to be said above and in the other heretic PRs.

**Pull request closed without merging**
