### PR TITLE
de-snowflakes basic floor tiles. syncs them to the better tg default.

### PR DESCRIPTION
**Pull request by axietheaxolotl**
## About The Pull Request

see title. currently, basic floor tiles are running an old old snowflaked tau ceti port. SR didn't want to update then, maybe bubber wants to update now.

image

## Why It's Good For The Game

looks significantly better, imo. they make take some getting used to, but I think if you look at it objectively, you can see that they're better.

## Proof Of Testing

see body.

## Changelog

:cl:
imageadd: brings default floor tiles up to /tg/ default.
/:cl:

### CODE REVIEW

**Comment by ReturnToZender** [comment]
These look cool, I never thought it was any different elsewhere. Cool!

**Comment by StrangeWeirdKitten** [comment]
Just deleting a file will not be permanent. You need to comment out the entirety of ``modular_skyrat\modules\aesthetics\floors\code\floors.dm``

**Review by StrangeWeirdKitten — CHANGES_REQUESTED** [review]
You need to comment out the entirety of ``modular_skyrat\modules\aesthetics\floors\code\floors.dm`` as deleting files will only show their return next upstream

**Comment by Swiftfeather** [comment]
If you get back to this, feel free to re-open.

**Pull request closed without merging**
