### PR TITLE
Upstream merge 2024/3a

### PR DESCRIPTION
**Pull request by Majkl-J**
## About The Pull Request

Updates us to Skyrat's 8fc795c4cbc9f65e3dbdd7adb22487e74463339c

## Why It's Good For The Game

image

## Proof Of Testing

If it compiles we will hopefully be in the clear

## Changelog

N/A

### CODE REVIEW

**Comment by Majkl-J** [comment]
meRN

**Comment by Majkl-J** [comment]
Maps passed hell yes

**Comment by nevimer** [comment]
I will fix this up

**Comment by Majkl-J** [comment]
Stuff to fix up (Will keep updating as more comes up): 
 - Override map votes to be multiple select again
 - Fix up @BurgerLUA 's reactor to whatever new standard tg made up

**Comment by projectkepler-ru** [comment]
holy fucking shit all the check passed im literally crying

**Comment by Majkl-J** [comment]
> holy fucking shit all the check passed im literally crying

Now to just squash our fixes and tell nevi to merge it with each commit

**Pull request merged**
