### PR TITLE
Frees the Flips

### PR DESCRIPTION
**Pull request by YakumoChen**
## About The Pull Request
Disables cringe code that disables *flip-ping unless you have an 8 point quirk

## Why It's Good For The Game

Flips are based

## Changelog

:cl:
balance: Everyone can now *flip freely again
/:cl:

### CODE REVIEW

**Comment by nevimer** [comment]
I don't really want to see people flipping down the halls.

**Comment by YakumoChen** [comment]
You're okay with blatant copyright infringement in a shoddy joke pr but sprites doing a 360 is too much?

**Comment by Cyprex** [comment]
Which PR even?

**Comment by nevimer** [comment]
You don't need to get offensive and vaguepost in a PR that doesn't even build.

**Pull request closed without merging**
