### PR TITLE
[it's almost kinda modular] sec/medhud resprites: the citadel port

### PR DESCRIPTION
**Pull request by zeroisthebiggay**
## About The Pull Request

ports various hud sprites from ~~citadel~~ citadel as a port of a port, with the original heralding from https://github.com/shiptest-ss13/Shiptest/pull/1469 with a couple extra touchups to make them what's essentially just the current sprites but a little bit brighter and easier to read
also changes the sechud icons for the departmental guards to just be the normal security officer icon but with a different departmental background
why was the supply guard `. . !`
why was the engineering guard a `thing`
why was the medical guard a weird ass circle that looked almost `identical` to the virologist's job icon
idk
it's much easier to tell that they're a departmental guard when they have the security officer job icon

too lazy to post images just look at icondiffs and complain

## Changelog

:cl:
image: huds
/:cl:

### CODE REVIEW

**Comment by nevimer** [comment]
poke me after it's 7 days old and ill merge it, its testmerged

**Comment by retlaw34** [comment]
Hi, I'm the original spriter for this (https://github.com/shiptest-ss13/Shiptest/pull/1469)

I would really appreciate if it was ported as it originally was rather than porting the extremely butchered citadel port.

Also, you should probably credit where you are porting it from, usually by dropping a link to the original or names of who did the sprites originally

**Comment by zeroisthebiggay** [comment]
> Hi, I'm the original spriter for this ([shiptest-ss13/Shiptest#1469](https://github.com/shiptest-ss13/Shiptest/pull/1469))
> 
> I would really appreciate if it was ported as it originally was rather than porting the extremely butchered citadel port.
> 
> Also, you should probably credit where you are porting it from, usually by dropping a link to the original or names of who did the sprites originally

hi i'm really a fan of your sprites as i was the person who `'extremely butchered'` them when i brought them to citadel `(unsure how they were 'butchered'; changes i made were extremely minor and were mostly just to keep visual fidelity with citadel's boomer artstyle)`

i'm on my laptop right now so i can't make any changes to revert it to 'as it originally was' and i most likely won't be doing that due to how their original iterations had flaws with the furry codebase archetype
more specifically with how sprite sizes increase and can fuck with how the `notches` on health bars in unappealing ways. the flatter health bars may look less visually unique and may essentially just be a brighter version of the originals but they don't look wonky as soon as someone's sprite size increases `(extremely common on furry servers)`

i'll happily add a link to your original pr in the body of this pr but you'll have to shed some light on what exactly you mean by making it exactly as it was. there's nothing wrong with your sprites however i felt some of them out of place among others `(specifically it was just the health cross icon to the left of the health bar; it looked kinda 'three dimensional' and weird to me in my personal opinion)`

**Comment by retlaw34** [comment]
Hey, apologies about the butcher comment, i just only saw another person using my sprites without credit again and expected the worst like before, you're fine

I play here sometimes and was a bit upset to see edited versions of my sprites, that I thought were worse but seeing your thinking behind the changes it's fine

Yeah and thanks for putting credit again, just keep it in mind for the future

**Pull request merged**
