### PR TITLE
Is that a [REDACTED] reference??

### PR DESCRIPTION
**Pull request by Scuhf-git**
## About The Pull Request

Adds TEN new pairs of horns including three large pairs (32x48), all sprited by Scuhf_[#6640]

Large Horns (32x48)
image

Horns (32x32)
image

## Changelog

:cl:
add: Crippled Bull Horns
add: Hollow-Points Horns
add: Ticket Rack Horns
add: Hopeful Horns Horns
add: Analytical Antlers Horns
add: Spiders Spikes Horns
add: Broad Curls Horns
add: Painted Points
add: Who's Horns?
add: High-rise Horns
/:cl:

### CODE REVIEW

**Comment by Scuhf-git** [comment]
And God said, "Let there be light," and there was light.

**Comment by SomeDongus** [comment]
image

**Comment by Scuhf-git** [comment]
image

**Comment by NotMergot** [comment]
no way

**Pull request merged**
