### PR TITLE
[modular] makes organs stink

### PR DESCRIPTION
**Pull request by nevimer**
## About The Pull Request
Organs now stink when rotting. Immersive!

## Why It's Good For The Game

Adds the benefit of evidence a body is somewhere nearby, and pretty negligible punishment for collecting corpses. Entirely negated by using epi-pens and stasis beds, morgue trays, pretty much anything that stops rot. 

## Changelog

:cl:
balance: organs emit miasma, when they rot, until they're dead. 
/:cl:

### CODE REVIEW

**Comment by Majkl-J** [comment]
The kitchen freezer becoming more of a deadzone by the day

**Comment by nevimer** [comment]
honestly I should make being below 0c prevent rot.

**Comment by Cyprex** [comment]
On tg I think this caused atmos churn & enabled miasma gas farms- not sure what the current state there is- but we could definitely give this a try!

**Comment by NithaIsTired** [comment]
just saw this, it IS being used for farms and all hallways are just miasma

**Comment by OceanFish1** [comment]
I think TG had miasma corpses removed for reasons that we see now: money farms and annoying diseases.

**Comment by nevimer** [comment]
That's the point. It's a small amount of content. Also, bodies don't endlessly emit miasma like before.

**Comment by Majkl-J** [comment]
> That's the point. It's a small amount of content. Also, bodies don't endlessly emit miasma like before.

Small amount of content that makes the station uninhabitable incase someone kills PunPun and lets him just lay there or opens one of the used xenobio pens

**Comment by Tupinambis** [comment]
Dead bodies releasing miasma was removed for a reason. People don't want to get sick because they dared to recover a corpse, and nobody wants to get sick from pun pun dying.

Not to mention how annoying it is for atmos to deal with and the performance hits.

**Comment by SovietSpaghetti** [comment]
This is awful, miasma builds up crazy fast in any area that anyone is taking any organ damage at all. It was at levels where you could see the stuff hanging in the air on a shuttle with no dead people at all. Also you can't carry around organs to eat anymore or anything because they'll rot and give you and everyone else on the station every disease imaginable. Apparently it's also triggering with any type of organ damage too, like from multiver lung damage or alcohol liver damage.

**Comment by Eastwardrope** [comment]
So I think I found a serious bug with this. People seem to generate miasma endlessly despite being fully alive for ZERO reason up to about .8 percent of a standard atmosphere. It also randomly spikes for ZERO reason across an entire room. I saw this happen as AI where rooms completely disconnected (Bar and Chaplains quarters) which had no corpses or organs in them and were clean had miasma levels as if someone was rotting there. The only constant between them is 1 person standing still. Something seems fishy there.

**Comment by mcmeiler** [comment]
I love having brown particles on every tile in the station because someone is dead in medical.

**Comment by silverplatedelta** [comment]
While I do think this could be interesting from a flavor point of view, the air alarm threshold for miasma is VERY low, not to mention scubbers don't filter it my default. Having now played several rounds of atmospherics, its incredibly annoying to have to de-miasma cargo and medbay every ten seconds, plus anyone who opens a maint shaft floods their department with the stuff, as maint monkies exist.

If this is implemented, miasma either needs to be scubbed by default on ALL air alarms, or B less needs to be emitted.

**Comment by nevimer** [comment]
> While I do think this could be interesting from a flavor point of view, the air alarm threshold for miasma is VERY low, not to mention scubbers don't filter it my default. Having now played several rounds of atmospherics, its incredibly annoying to have to de-miasma cargo and medbay every ten seconds, plus anyone who opens a maint shaft floods their department with the stuff, as maint monkies exist.
> 
> If this is implemented, miasma either needs to be scubbed by default on ALL air alarms, or B less needs to be emitted.

have you looked at the last two commits. i swear. 

> I love having brown particles on every tile in the station because someone is dead in medical.

it used to require 60 moles but i changed it to like, 3, and they're still not showing up because of how much has to spread.

**Comment by silverplatedelta** [comment]
> > While I do think this could be interesting from a flavor point of view, the air alarm threshold for miasma is VERY low, not to mention scubbers don't filter it my default. Having now played several rounds of atmospherics, its incredibly annoying to have to de-miasma cargo and medbay every ten seconds, plus anyone who opens a maint shaft floods their department with the stuff, as maint monkies exist.
> > If this is implemented, miasma either needs to be scubbed by default on ALL air alarms, or B less needs to be emitted.
> 
> have you looked at the last two commits. i swear. this was accounted for - the default settings been set to miasma and co2, the scrubber alert thresholds have been raised to 1 to warning, 3 for alarm, for ALL gasses that are not co2, o2, or n2.
> 
> > I love having brown particles on every tile in the station because someone is dead in medical.
> 
> it used to require 60 moles but i changed it to like, 3, and they're still not showing up because of how much has to spread.

I wrote this comment after round end but  before the above commits were added. please ignore my comment, you fixed all of this XD

**Comment by YakumoChen** [comment]
Add an isliving check so that living people don't produce miasma

**Comment by nevimer** [comment]
> Add an isliving check so that living people don't produce miasma

isliving will always be true unless the organs are separated from the mob.

isliving checks for if the mob is a subtype. the code is on the organs, not the mob. if we just check the parent mob, it will never run.

what you mean is owner.stat

**Comment by BurgerLUA** [comment]
I actually remember implementing something similar on citadel.

What I recommend here is adding a threshold for miasma diseases so that it isn't just prob(0.1 * moles) determining if someone gains a disease. Even if the chance is extremely low, it is still possible to get diseases even if there is something like 0.1 moles in the air.

**Comment by BurgerLUA** [comment]
Another thing that I recommend is limiting the pool of symptoms you can get with miasma borne disease. Sometimes RNG can seriously mess up the station. I implemented one a bit back with food germs, and it can probably be used here.

/datum/disease/advance/floorfood

**Comment by StrangeWeirdKitten** [comment]
image

This is pretty awful to deal with and almost impossible to clean up when there's 0.02 mols of miasma sitting in the hallway. I've played this on the side of both medical and engineering.

**Comment by StrangeWeirdKitten** [comment]
will need to be discussed with #645

**Comment by Majkl-J** [comment]
Superceded by https://github.com/Bubberstation/Bubberstation/pull/860

**Pull request closed without merging**
