### PR TITLE
Ports Lima Station from TaleStation

### PR DESCRIPTION
**Pull request by INKVD**
## About The Pull Request

Ports LimaStation from [TaleStation](https://github.com/TaleStation/TaleStation)
Full credits to the mappers at [TaleStation](https://github.com/TaleStation/TaleStation) & [RussStation](https://github.com/RussStation/RussStation)

_Taken from https://github.com/TaleStation/TaleStation/wiki/LimaStation_

**About**
LimaStation is comprised of two Z levels, the bottom (top) and the top (bottom).

**Bottom Level**
Limas first floor comprises of never-ending maintenance tunnels. However, the HFR room, Chemistry Lab, Xenobiology slime pens and some service/common areas can be found down here (like botanys bee room).

**Upper Level**
Limas second floor (main floor) comprises the bulk of the departments, as well as the general common areas (bar for instance).

Directly north is arrivals, dorms and some common areas.

Security occupies the north west portion of the station, with the chapel right next to it.

Going east, science occupies most of the eastern wing of Lima.

South east is where the Bridge, and further out, AI sat/Tcomms is located.

South west is atmospherics, with directly west being the bulk of engineering and the engine room itself.

In the center of the station is the bulk of service on the left, with medical on the right.

Cargo is south of the bar, but north of departures.

**LimaStation History**
LimaStation is originally from [RussStation](https://github.com/RussStation/RussStation), but was ported by [SQNZTB](https://github.com/sqnztb) on December 8th, 2020 to [TaleStation](https://github.com/TaleStation/JollyStation-Commit-Archive/commit/331c2f04cb426ae60922037c0ec249819792ae1d). It was merged into code on January 28th, 2021.

Since the initial port, LimaStation has gone under many drastic changes since it was brought to the (formerly) JollyStation. LimaStation was original one Z level, however, a [rework](https://github.com/TaleStation/TaleStation/commit/cd2ac245b7d025283e883cb3bcc7c6370d2652a6) on August 11th, 2021 by [SQNZTB](https://github.com/sqnztb) revived Lima to be what we know it as today, making it Multi-Z.

## Changelog

:cl:
add: Lima Station map, ported from TaleStation. A modest map for modest people.
/:cl:

### CODE REVIEW

**Comment by Detective-Google** [comment]
played decently, the staircases on the lower level could use signs on them giving an indication of what's above. 

also the medbay probably needs remapping entirely, especially the floors.

**Comment by zeroisthebiggay** [comment]
please stop porting maps

**Comment by Vynzill** [comment]
the cargo windoor at the desk and the disposal windoor next over both lack regular cargo-tech access.

**Comment by Jolly-66** [comment]
You should attribute the codebases you're getting this map from in your CL, just as a note :)

**Review by Jolly-66 — COMMENTED** [review]
You should include a plaque, or take ours.

https://github.com/TaleStation/TaleStation/blob/36fb9d8d1a049b1f03c170ff6bedcee30443f0ba/talestation_modules/code/mapping_module/static_plaques.dm#L3

**Comment by zeroisthebiggay** [comment]
> please stop porting maps

addendum: i've looked at the map and it doesn't look `too` bad

**Comment by Jolly-66** [comment]
I don't know Bubber at all, but you should consider swapping all (tg) dept sec with (SR) dept guards. If you run both, then don't do what I'm recommending.

image

**Comment by zeroisthebiggay** [comment]
> > please stop porting maps
> 
> addendum: i've looked at the map and it doesn't look `too` bad

addendum addendum: i don't like it

**Pull request merged**
