### PR TITLE
Adds a new cloak sprite.

### PR DESCRIPTION
**Pull request by AllCorruptingWyrm**
## About The Pull Request

This PR adds a new cloak sprite, not one to the loadout menu.
image
I dont own this sprite, credit goes to whoever made it obviously.

## Why It's Good For The Game
More diversity is nice, but also good for funny event stuff.

## Proof Of Testing

It compiles.

## Changelog

:cl:
add: new cloak
/:cl:

### CODE REVIEW

**Review by projectkepler-ru — CHANGES_REQUESTED** [review]
where in the hell did you even get that, this might cause issue if whoever  made it come knocking at our door

**Comment by Swiftfeather** [comment]
You can't just take a sprite and say "credit goes to whoever made it"

You've gotta show us who made it and what copyright is attached.

**Comment by theselfish** [comment]
The sprite is from Splurt.

**Comment by theselfish** [comment]
This PR is also just the sprite, by the way. No actual code.

**Comment by AllCorruptingWyrm** [comment]
> where in the hell did you even get that, this might cause issue if whoever made it come knocking at our door

Its a port from Splurt.

**Comment by projectkepler-ru** [comment]
> > where in the hell did you even get that, this might cause issue if whoever made it come knocking at our door
> 
> Its a port from Splurt.

put it on the PR body itself

**Comment by projectkepler-ru** [comment]
> This PR is also just the sprite, by the way. No actual code.

Yeah was about to ask about that -_>

**Comment by StrangeWeirdKitten** [comment]
Splurt is not going to knock on our door over this. They're rebasing to us anyway and I'm sure they won't complain if we add some of their loadout items. Infact, add more of them.

In the future please just link where you got the actual sprites from. Attribution is needed to link the repo at the bare minimum.

**Pull request closed without merging**
