### PR TITLE
Removes Vore

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Xenos can only devour mobs that have a ventcrawler trait (Monkeys, most Simplemobs), assuming all other checks have passed.

## Why It's Good For The Game

Xenos having the ability to eat people and put them in gay baby jail is pretty strong. This only makes it so that smaller creatures and monkeys can be devoured, as not to ruin their ability to use monkeys at the start of their creation.

## Changelog

:cl: BurgerBB
balance: Xenos can only devour mobs that have a ventcrawler trait (Monkeys, most Simplemobs), assuming all other checks have passed.
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
you can gib the xeno from the inside if you have anything sharp on you, and xenos can only really do this if they've stunned you anyway, not sure why this needs to be removed outside of making a PR with a meme title

**Comment by projectkepler-ru** [comment]
the PR title gave me a heart attack

**Comment by ReturnToZender** [comment]
Burger made this PR just so he could title a PR "removes vore" absolute legend

**Comment by destrucktoid** [comment]
Agree with YakumoChen here. I don't see why this is needed outside of meme title.

**Comment by BurgerLUA** [comment]
It's a legitimate PR. It doesn't make sense to me that Xenos can devour people, but those people aren't normally able to ventcrawl.

Also it's a balance concern.

**Review by StrangeWeirdKitten — CHANGES_REQUESTED** [review]
I think if you eat something that can't ventcrawl, you shouldn't be allowed to ventcrawl with the person inside you. Otherwise eating someone has a huge timer and it is extremely noticeable because it's loud as hell.

**Comment by BurgerLUA** [comment]
> I think if you eat something that can't ventcrawl, you shouldn't be allowed to ventcrawl with the person inside you. Otherwise eating someone has a huge timer and it is extremely noticeable because it's loud as hell.

Out of the scope of this PR.

**Comment by StrangeWeirdKitten** [comment]
> Out of the scope of this PR.

I'll bring it up to another maintainer for their opinion before I immediately close this. However, keep in mind this balance change in its current state does not have my approval.

**Comment by StrangeWeirdKitten** [comment]
I asked. Basically agreed that this change is arbitrary. I'm closing this PR.

**Comment by nevimer** [comment]
Test it still works and it's in

**Comment by BurgerLUA** [comment]
ye

**Comment by BurgerLUA** [comment]
image

Works.

**Comment by BurgerLUA** [comment]
you know if this PR was merged, we could say that /tg/station has more vore content than bubberstation

**Review by Majkl-J — APPROVED** [review]

**Comment by Majkl-J** [comment]
Would be cooler if it checked for a linked ghost/client but this also works.

**Pull request merged**
