### PR TITLE
[READY] Fixes Integration Tests

### PR DESCRIPTION
**Pull request by BurgerLUA**
This is the PR that fixes the integration tests so that we can stop seeing funny red checkmarks.

Contains map changes, icon changes, and everything changes.

### CODE REVIEW

**Comment by BurgerLUA** [comment]
auto code owner requests are a mistake

**Comment by nevimer** [comment]
thanks, I'll merge this after upstream merge

**Comment by BurgerLUA** [comment]
Converting to a draft because of map conflicts and I could probably do more with this PR.

**Comment by BurgerLUA** [comment]
This is ready to be merged.

**Comment by BurgerLUA** [comment]
I can't seem to fix the shadekin issue with the screenshot comparisons because I don't know how that system works. Someone will need to do that.

**Comment by magatsuchi** [comment]
image

**Pull request merged**
