### PR TITLE
Unskyratifies the batons and double esword.

### PR DESCRIPTION
**Pull request by Moostard**
## About The Pull Request
Brings back TG balance to the batons and double energy sword.
Batons now deal appropriate(original) stamina damage and apply confusion effect.
Double esword is no longer worse at blocking than normal esword.

I did a local test and it worked. Please test merge first just in case anyway.

## Why It's Good For The Game
More balanced melee combat. "High risk high reward".

Batons were nerfed out of spite and dislike for stun combat, making them deal pathetic stamina damage. Knockdown being the only thing keeping them from being "useless". This and lethals being absurdly powerful (guncargo and cmgs) do not promote nonlethal takedowns at all. These changes will allow antags and security to use their batons more confidently without resorting to lethals.

Double esword was nerfed in response to that. This change makes the desword once again the feared weapon worth its cost.

## Changelog

:cl:
balance: Batons are back with their original TG power.
balance: Double energy sword is no longer worse at blocking than normal esword.
/:cl:

### CODE REVIEW

**Comment by Serxule** [comment]
batons are unbalanced being 1 hit win weapons

**Comment by Moostard** [comment]
> batons are unbalanced being 1 hit win weapons

They are not 1 hit win weapons.
Currently you need 4 hits to stun a UNARMORED target (who can also run in a straight line away from you).
Due to batons respecting armor now, anyone with 5 energy armor needs 8 hits with a baton to be stunned. (baton has 10 hits max with starter cell).

If batons are so unbalanced and op, why arent people buying them every shift?
Because they are not.

**Comment by Serxule** [comment]
> > batons are unbalanced being 1 hit win weapons
> 
> They are not 1 hit win weapons. Currently you need 4 hits with a standard baton to stun an UNARMORED target (who can also run in a straight line away from you). Due to batons respecting armor now, anyone with 5 energy armor needs 8 hits with a baton to be stunned. (baton has 10 hits max with starter cell).
> 
> If batons are so unbalanced and op, why arent people buying them every shift? Because they are not.

read what i said slower, im saying making them a 1 hit win is unbalanced

**Comment by StrangeWeirdKitten** [comment]
It's not even that bad. You stun baton, step back, let them drop, then open fire or go in for another baton.

**Comment by Moostard** [comment]
> > > batons are unbalanced being 1 hit win weapons
> > 
> > 
> > They are not 1 hit win weapons. Currently you need 4 hits with a standard baton to stun an UNARMORED target (who can also run in a straight line away from you). Due to batons respecting armor now, anyone with 5 energy armor needs 8 hits with a baton to be stunned. (baton has 10 hits max with starter cell).
> > If batons are so unbalanced and op, why arent people buying them every shift? Because they are not.
> 
> read what i said slower, im saying making them a 1 hit win is unbalanced

TG baton also is not 1 hit win weapon.
You need solid 3 hits to properly stun an unarmored target :)
Our players do not lack the creativity and effort and are using stims to counteract batons and stuns in general.

**Comment by Serxule** [comment]
> > > > batons are unbalanced being 1 hit win weapons
> > > 
> > > 
> > > They are not 1 hit win weapons. Currently you need 4 hits with a standard baton to stun an UNARMORED target (who can also run in a straight line away from you). Due to batons respecting armor now, anyone with 5 energy armor needs 8 hits with a baton to be stunned. (baton has 10 hits max with starter cell).
> > > If batons are so unbalanced and op, why arent people buying them every shift? Because they are not.
> > 
> > 
> > read what i said slower, im saying making them a 1 hit win is unbalanced
> 
> TG baton also is not 1 hit win weapon. You need solid 3 hits to properly stun an unarmored target :) Our players do not lack the creativity and effort and are using stims to counteract batons and stuns in general.

lol no? 1 hit = confusion, knockdown, and itemdrop, second hit is hardstun. why do you think everyone on tg says batong is 1 hit win

**Comment by destrucktoid** [comment]
I'm fine with these changes, security right now goes to lethals to moment they so much as hear rumours of their being an antag. Buffing their non-lethals is a good change. I do however disagree with the return of the confusion status effect, i think the stun baton making your movement into a RNG nightmare after 1 hit is bad for combat. 

TL:DR, good change but i would personally prefer no confusion.

**Comment by destrucktoid** [comment]
> > > > > batons are unbalanced being 1 hit win weapons
> > > > 
> > > > 
> > > > They are not 1 hit win weapons. Currently you need 4 hits with a standard baton to stun an UNARMORED target (who can also run in a straight line away from you). Due to batons respecting armor now, anyone with 5 energy armor needs 8 hits with a baton to be stunned. (baton has 10 hits max with starter cell).
> > > > If batons are so unbalanced and op, why arent people buying them every shift? Because they are not.
> > > 
> > > 
> > > read what i said slower, im saying making them a 1 hit win is unbalanced
> > 
> > 
> > TG baton also is not 1 hit win weapon. You need solid 3 hits to properly stun an unarmored target :) Our players do not lack the creativity and effort and are using stims to counteract batons and stuns in general.
> 
> lol no? 1 hit = confusion, knockdown, and itemdrop, second hit is hardstun. why do you think everyone on tg says batong is 1 hit win

Itemdrop is avoided if you lie down before the knockdown takes effect.

**Comment by Moostard** [comment]
> I'm fine with these changes, security right now goes to lethals to moment they so much as hear rumours of their being an antag. Buffing their non-lethals is a good change. I do however disagree with the return of the confusion status effect, i think the stun baton making your movement into a RNG nightmare after 1 hit is bad for combat.
> 
> TL:DR, good change but i would personally prefer no confusion.

That is the point of this PR :)
Its less of a buff, but nerf "revert".

I tested the confusion and it does not RNG your every move.
Unarmored targets have it worse, of course.
I feel like the energy batons (stunbaton and contractor baton) should have the confusion applied due to them using "electricity", while the normal sticks do not (but have instant knockdown).

**Comment by destrucktoid** [comment]
> > I'm fine with these changes, security right now goes to lethals to moment they so much as hear rumours of their being an antag. Buffing their non-lethals is a good change. I do however disagree with the return of the confusion status effect, i think the stun baton making your movement into a RNG nightmare after 1 hit is bad for combat.
> > TL:DR, good change but i would personally prefer no confusion.
> 
> That is the point of this PR :) Its less of a buff, but nerf "revert".
> 
> I tested the confusion and it does not RNG your every move. Unarmored targets have it worse, of course. I feel like the energy batons (stunprod, stunbaton and contractor baton) should have the confusion applied due to them using "electricity", while the normal sticks do not (but have instant knockdown).

Personally i just have an issue with abilities that make your character harder to control, especially in combat situations. I can however understand why it's there.

**Pull request merged**
