### PR TITLE
[Modular] Adds new disabler sounds from Daedalus

### PR DESCRIPTION
**Pull request by ReturnToZender**
## About The Pull Request
Makes the Disabler look and sound like a taser.

PR is tested and fully functional :)

## Why It's Good For The Game
The disabler sucks, so this PR makes it look and sound cooler

## Changelog

:cl:
add: New disabler sounds and visuals
/:cl:

### CODE REVIEW

**Review by Majkl-J — CHANGES_REQUESTED** [review]
Reskin the disabler color to be in line with the projectile color

**Comment by ReturnToZender** [comment]
> Reskin the disabler color to be in line with the projectile color

https://github.com/Bubberstation/Bubberstation/assets/110273561/8934dd98-3272-4aa9-852e-5645f6e7e1ef
https://github.com/Bubberstation/Bubberstation/assets/110273561/b6dd7eb3-6569-4312-836e-a697a5a8b6ff

**Comment by Majkl-J** [comment]
> > Reskin the disabler color to be in line with the projectile color
> 
> https://github.com/Bubberstation/Bubberstation/assets/110273561/8934dd98-3272-4aa9-852e-5645f6e7e1ef https://github.com/Bubberstation/Bubberstation/assets/110273561/b6dd7eb3-6569-4312-836e-a697a5a8b6ff

Whilst yes, it looks and sounds cool, and I really wanna see it ingame: the projectile is yellow, but the disabler is blue. This might cause readability issues and should be fixed one way or another (Making the disabler ball blue, or making the disable mode color blue)

**Comment by zeroisthebiggay** [comment]
it sounds like a cheesegrater and looks too much like a taser to be a disabler

**Comment by Kapu1178** [comment]
These are Goonstation assets and must be placed in a location that marks them as CC-BY-NC-SA 3.0

**Comment by ReturnToZender** [comment]
> These are Goonstation assets and must be placed in a location that marks them as CC-BY-NC-SA 3.0. It's called the Disabler MK. II on Daedalus because it's mechanically distinct from the old Disablers, it's odd to carry the name change.

Thanks Kapu!

**Comment by ReturnToZender** [comment]
> > > Reskin the disabler color to be in line with the projectile color
> > 
> > 
> > https://github.com/Bubberstation/Bubberstation/assets/110273561/8934dd98-3272-4aa9-852e-5645f6e7e1ef https://github.com/Bubberstation/Bubberstation/assets/110273561/b6dd7eb3-6569-4312-836e-a697a5a8b6ff
> 
> Whilst yes, it looks and sounds cool, and I really wanna see it ingame: the projectile is yellow, but the disabler is blue. This might cause readability issues and should be fixed one way or another (Making the disabler ball blue, or making the disable mode color blue)
> 
> The MCR for me personally suffers the same issue, blue and yellow are generally nonlethal where red is lethal, and the gun colors should align with the laser/projectile color. The MCR colors are blue, which has caused me to believe for a while you can switch modes on it, and I am probably not the only one.

Agreed, I'm gonna see if I can get some yellow sprites

**Comment by ReturnToZender** [comment]
Drafting this because of the work it needs done, will mark as ready for review when it _is_ ready for review again

**Comment by ReturnToZender** [comment]
Closed due to stale, will get back on this at a later time.

**Pull request closed without merging**
