### PR TITLE
Mouseover Highlights while holding shift

### PR DESCRIPTION
**Pull request by nevimer**
## About The Pull Request
Add's mouseover highlights. Ported from Nebula. 

## Why It's Good For The Game

Accessibility + gameplay

## Proof Of Testing

<summary>

https://github.com/user-attachments/assets/7e069682-88d4-4239-9bfd-b04f290cacf0

</summary>

</details>

## Changelog

:cl:
add: clientside mouseover highlights for objects while holding shift
/:cl:

### CODE REVIEW

**Comment by lessthnthree** [comment]
The game option pref to turn it off/on needs more before it will be functional.

**Comment by Arturlang** [comment]
Integration tests fail

**Comment by LSommers** [comment]
Not gonna lie, this _lowers_ accessibility for me- I was struggling to pick up items due to the giant text and image popping up when I tried to look at and grab something out of a pile. I also had to repeatedly ask in OOC where the option to disable it even was, as I assumed it was in RuneChat or the UI area, rather than gameplay.

**Comment by Hemlock32** [comment]
How is, showing the exact same item I'm already looking at, but, with text and an obnoxiously large outline around it, in any way helping people click items?
I can already tell what I'm hovering over by the text at the top of the screen, bottom left of the screen, or, in the chat by shift clicking it. If you need to grab something specific out of a stack of items, alt click menu exists for that with a search bar

This is so intrusive and in the way, and, so much unnecessary visual clutter
It makes it harder to see anything and makes me want to avoid accidentally hovering over something close while holding shift

**Comment by lessthnthree** [comment]
The preference should be better described and include the tooltip that explains what exactly it is doing.

**Comment by Kepteyn** [comment]
The preference to disable this feature needs to be clearer. Please move it to the tooltips section. Perhaps also having it off by default would be better, I imagine it's very offputting to other players as well.

**Pull request closed without merging**
