### PR TITLE
15% chance of breaking a glass table on 3rd slap

### PR DESCRIPTION
**Pull request by tmyqlfpir**
## About The Pull Request

This PR introduces a change to slapping behavior for glass tables. Upon the last slap on a glass table, it will roll a 15% chance (cursed trait 30%) to break the table for the epic lols and funny.

## Why It's Good For The Game

Adds needed comedy, saves the game. Improves the experience by 100%

Trust me guys.

## Proof Of Testing

https://github.com/Bubberstation/Bubberstation/assets/80724828/dc6f3cf1-39b7-4f41-8441-66d2ba304e23

It only executes the break with glass tables. Other tables are unaffected.

Untitled

## Changelog

:cl:
add: Slapping glass tables have a 15% chance (cursed 30%) of breaking on 3rd slap
/:cl:

### CODE REVIEW

**Comment by destrucktoid** [comment]
Probably shouldn't make you randomly fall over if you smash it, I also think 50% is a bit too high for something likes of this. I'd personally like to see it lower, up to whatever the maintainers think though ultimately.

**Review by Majkl-J — CHANGES_REQUESTED** [review]
Make it cause wounds upon the slapping limb

**Comment by StrangeWeirdKitten** [comment]
tbh I'd rather it be like 5-10 percent.

**Comment by StrangeWeirdKitten** [comment]
> > Probably shouldn't make you randomly fall over if you smash it.
> 
> I'll try to look into this.
> 
> > Make it cause wounds upon the slapping limb
> 
> Sure I'll try it.
> 
> > I also think 50% is a bit too high for something likes of this.
> 
> > tbh I'd rather it be like 5-10 percent.
> 
> That'd be so rare, I want it to be a humous punctuation mark upon the most delicate table surfaces. Perhaps 25% instead?

10 percent wouldn't be rare, I personally feel it would be more funny if the chance happened 1/10 times you smacked a table, then get yelled at, versus it happening most the time. You feel?

**Comment by ReturnToZender** [comment]
I have no idea what could have possibly caused this PR but I like it

**Comment by StrangeWeirdKitten** [comment]
I'll settle for 15 :)

**Comment by IgiariValkyr** [comment]
> Having the Hulk trait will do more damage and increase the wound chance percentage.

Hulk should smash the table first slap, but that's just me.

**Review by Majkl-J — APPROVED** [review]
Code looks good to me.

**Pull request merged**
