### PR TITLE
Wawastation (#82298)

### PR DESCRIPTION
**Pull request by nevimer**
- [x] #82282
- [x] map in aux base how the hell did i forget it
- [x] fill out maints
- [x] properly test the goddamn thing
- [x] fix major cameranets
- [ ] fix any issues
- [x] write a proper pr body

## About The Pull Request

adds this map to the map rotation

bottom level (24.5.2024)
StrongDMM-2024-05-24 06 59
36

upper level (24.5.2024)

image

## general map details and department stuff
- the station is more focused on the bottom level, so falling in doesnt roundremove you
- this is an asteroid station, so assistants can larp as dorfs and mine towards the sweet loot
- there is plenty multiz usage
- service is the center of the station

**Service** - Is the center of the station. Arrivals docks directly in the middle of the station next to Upper Service, so bar might get more traffic. Not much different than normal Service, but janitors closet is also present here, he sleeps on the floor. We do not talk about the janitor. Above Bar is Library and Hydroponics with an overlook to look at bar. The Theater has a big curtain and a podium directly in the bar.

29.3.2024

ezgif-1-4549df2db8

**Civilian** - Also in the center of the station, next to bar. There isnt much to talk about dorms, its pretty normal.

**Cargo** - Absence of chutes that go to departments, reminder that mail sorting is a thing. Cargo bay is a big open area with a boutique/shop facing primary hall that starts closed, and Cargo has its own crate elevator. Theres upper Cargo where mining, bitrunning and a secure warehouse is located (There may be a murder scene). The quartermasters office spans two z-levels and is relatively compact. Not much else different from regular cargo. ~~Oh also the QM starts with an empty PML-9 and a mostly functional rocket~~

29.3.2024

ezgif-1-4d6bfe6c07

**Medical** - Large centralized medbay, also two z-levels. There is a public waiting room with triage and a reception. There is also an inner elevator for the crippled. There are two medbay-access patient rooms that are unrestricted from the inside, and two operating rooms. Medbay has its own rad shelter. The virologist does not get their own satellite, but is still relatively secure.

29.3.2024
https://i.ibb.co/hs9kKbV/ezgif-1-f7b697b067.gif (large gif)

**Command** - AI Sat transit tube access is here. HoP has an open stall facing primary hall, ~~and maybe a piano trapdoor~~ pretty classic bridge, Captain does not get his own office but gets a really comfortable quarters with his own emergency mass ejection for abandoning ship. The council meeting room is present above bridge, with ERT Ferry dock docking inside adjacent to the council room.

**Security** - Mostly bottom z level security. Very compact brig cells, and a meeting room that everyone that is related to security may spawn in if youre lucky. Warden has a weapon handout point facing the inner security hall and the equipment room. Reeducation chamber has a shocked grille treadmill. HoS and Warden Room and armory are on the upper z-level, and warden has a VERY good overlook over permabrig. Armory is seperated into nonlethal to mostly nonlethal and lethal.

29.3.2024

ezgif-1-d833de73fc

**Science** - Also pretty centralized, breakroom with a smoking corner, two z levels and a big overlook. RD office overlooks toxins and bomb site. Genetics and RD Office is on the upper floor, with a science exclusive monkey exhibit. Xenobio is thick due to proximity to bomb site, otherwise normal.

29.3.2024

ezgif-1-4f8814ece9-1

**AI Sat** - Okay at this point assume any department is multiz. The antechamber is an elevator and the turrets are on said elevator. The elevator may be sent to the top level by engineers, where the AI core is. Telecomms is on the bottom level, and AI core is above it. Contains a borg entertainment room, and also the upload. The elevator being raised is necessary to properly enter AI Room.

**Engineering** - Contains a less stale but still average and less than optimal SM setup. Prone to catastrophic disaster. The SM Room is two levels and very open, and CE has a trapdoor directly into the shard. Turbine is above atmospherics, so is the crystallizer. The HFR and main atmos and distribution room are on the bottom level. Piped by **Kendra Hunter**. Contains a built in electrolyzer corner so atmos mains stop gutting the aesthetics to place down some dumb machine.

## Why It's Good For The Game

another interesting map into the roster, different from the other multiz maps in the form that you dont get stuck in hell by falling down a hole

todo write better section

## Changelog
:cl:
add: wawastation, the station map
/:cl:

---------

Co-authored-by: Jeremiah <42397676+jlsnow301@users.noreply.github.com>
# Conflicts:
#	_maps/_basemap.dm
#	code/modules/awaymissions/gateway.dm

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
sound: added/modified/removed audio or sound effects
image: added/modified/removed some icons or images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by Shadow-Quill** [comment]
Currently no way onto the interlink, although all latejoins spawn directly onto the map in the arrivals shuttle.

**Comment by Shadow-Quill** [comment]
The cryopod in the arrivals area reports stored crew over the Interdyne radio.

**Comment by BurgerLUA** [comment]
image

The heavy crowbar spawn here does a not of damage per hit (6.8 hits to kill).

**Comment by BurgerLUA** [comment]
Current (opinionated) issues:
- Maintenance doors are missing a lot of names. A lot of them are just "maintenance airlock". This can be fixed with the autoname door helper.
- There are a lot of shocked grilles in maintenance, especially at the end of straight hallways. With the new power addition, this is painful and slightly unfair to high ping users.
- Gibtonite can spawn in the asteroid rock (I THINK), leading to a possibly very easy way to antagonists/assistants to get explosives.

**Comment by Kajortoq** [comment]
My primary opinion, and complaint after it was brought to my attention is there's no NTR office. I feel like if the warden gets a bedroom the NTR should have an office.

**Comment by TheGandalf85** [comment]
Engineering doesn't seem like it had enough time in the oven. There's no engineering modular computers outside of what I'm assuming to be the CE's room, so no engineer can really check the power levels there. Usually there's a lot of those status computers sprinkled around as gribble and to be a neat way for engineers to eye a console. A ton of empty space in general over here that begs for decoration and use, and reading Engineering's description on the PR seems like there's not as much excitement for this department.

_Contains a built in electrolyzer corner so atmos mains stop gutting the aesthetics to place down some dumb machine._

image

I do what I want.

**Comment by Shadow-Quill** [comment]
An admin has been putting cryopods in this area, where the two weightlifting machines are
image
And I think that's a really good spot for 'em, considering cryo on basically all(?) maps tends to be near the station dorms area.

**Comment by R3dtail** [comment]
Science is generally okay.  The layout of robotics is a little wonky but it's workable.  The fact science is cut off from distro is less than ideal.  

Also, ordnance:  The air alarms in the freezer and heater arent' set up correctly, so they constantly show as having an alarm unless adjusted.    The lack of a giant O2 canister like every other station has is also a bit rough.  Sure, you can tap into distro  but that raises some problems of its own.  

The freezer chamber in particular is reversed compared to most other stations and isn't easy to tell the difference:  The injector is on the left and the scrubber is on the right.  Most stations tend to have the space around the freezer generally fit that, mixing for the injector is going to need more space to work with compared to scrubbing.  The left side of the freezer and the area around the freezer chamber is the entrance and surrouding walls to ordnance.  Just a pet peeve but it doesn't thematically feel good.  The pipes in the middle of the area  going straight through the middle also kinda feel a little rough but  every station has that issue it seems, it would just be nice to have a decent bit of space to work with even with layers.

 Not too terrible first impression wise from what I've seen.  Plenty of canisters, nothing, besides the giant canister, felt missing for a first impression.

**Comment by AllCorruptingWyrm** [comment]
To go off of what Lux said; I think the big issue with Science is the fact it isnt covered in glass window tiles. That should be fixed. I think the hallways could use more flavor too, like tile decals n stuff, but its okay.

as for sec, PLEASE PUT AIRLOCKS BY THE STAIRCASE THAT LEADS TO THE ARMORY AAAA.

**Comment by R3dtail** [comment]
Another complaint about science:  The front doors seemingly are All Access.  Anyone can just walk into the main heart of the department.

**Comment by BurgerLUA** [comment]
This should not be testmerged in its current state. I used to like the map but then the issues were just too glaring to ignore. I thought this was a WIP map or rather an abandoned map from /tg/, but no it's apparently a completed map.

It has way more issues than blueshift.

**Comment by lessthnthree** [comment]
Yeah this is a /tg/ upstream map. And yeah, it has issues as mentioned above, likely more. Needs to be fixed upstream though.

**Comment by MajorBugReports** [comment]
not a fan, unironically too many issues to list. The mapping not spacing some areas that are hit with meteors and the whiplash of spacing the main hallways like its donut station all over again.

**Comment by aKromatopzia** [comment]
I notice that a lot of the upper-z maintenance shaftways have no mini-shutter to prevent gas leaks. otherwise this map would have been great!... if it wasn't ss13. The open-air rooms make it unintuitive to work in.

**Comment by lessthnthree** [comment]
> I notice that a lot of the upper-z maintenance shaftways have no mini-shutter to prevent gas leaks. otherwise this map would have been great!... if it wasn't ss13. The open-air rooms make it unintuitive to work in.

Can you post a screenshot of what you're talking about?

**Comment by Majkl-J** [comment]
Upstreamed

**Pull request closed without merging**
