### PR TITLE
Adds Shemagh (NON-MODULAR)

### PR DESCRIPTION
**Pull request by CenkTheRaptor**
## About The Pull Request
adds a Shemagh sprite and item from Shiptest.

## Changelog
:

:cl:

add: Adds Shemagh
/:cl:

### CODE REVIEW

**Comment by ReturnToZender** [comment]
L + not modular

**Comment by CenkTheRaptor** [comment]
how do i add it to loadouts guhhh

**Comment by CenkTheRaptor** [comment]
WAIT FUCK IM DOING THIS WRONG SHIT FUCK SHIT

**Comment by CenkTheRaptor** [comment]
im so stupid this is why i probably shouldnt manually upload files and just use git

**Comment by ReturnToZender** [comment]
Cenk makes worst PR ever, asked to leave the Github

**Comment by CenkTheRaptor** [comment]
fuck im an idiot it isnt even up to date files

**Comment by CenkTheRaptor** [comment]
gonna draft this until i fix my fuck shit

**Comment by CenkTheRaptor** [comment]
FINALLY IT WORKS

**Comment by nevimer** [comment]
post screenshots of it in game on a teshari, a lizard, a vox, and a human

**Review by nevimer — CHANGES_REQUESTED** [review]
Do not edit .dmi files in anything except under modular_zubbers folder. Your changes will be lost in updates. Reset those files and put your changes into new/prexisting files in the modular_zubbers folder.

**Comment by CenkTheRaptor** [comment]
dying inside
ok ill figure it out in a bit

**Comment by CenkTheRaptor** [comment]
idk im giving up on this

**Pull request closed without merging**
