### PR TITLE
[MODULAR](if i did it right) makes plant bags usable in pocket slots

### PR DESCRIPTION
**Pull request by kaylexis**
## About The Pull Request

you can do it with the mining bags, why not the plant ones? it makes the botany belt effectively useless.
needs testing im like 80% sure it works maybe

## Why It's Good For The Game

QoL fix for my botany peeps

## Changelog

:cl:
Balance: Allows botany bags to be worn in the pocket slot
:cl:

### CODE REVIEW

**Comment by projectkepler-ru** [comment]
This is a balance change

**Comment by nevimer** [comment]
you didn't tick the new file you made, and commit the new .dme

I have filed this PR under "bug" because plants and bugs and this is certainly delivering a bug instead of a plant right now

please commit the .dme :3

**Comment by YakumoChen** [comment]
This is a pretty huge balance change and TG definitely will not accept this, as malicious botanists will have a field day

**Comment by StrangeWeirdKitten** [comment]
https://github.com/tgstation/tgstation/pull/50292 no

**Comment by YakumoChen** [comment]
> > [tgstation/tgstation#50292](https://github.com/tgstation/tgstation/pull/50292) no, this PR says why
> 
> bags can't be stored in backpacks yeah. the PR is only for them to be allowed in pockets. mining bags are the same, but plant bags just can't be used in-pocket.

Mining bags are used to hold ore, which has no functional use except to turn into metals.

 It cannot contain things like plants that can deliver deadly volumes of chemicals on impact, turn into hostile mobs, confuse and perform area denial, take over the station with kudzu, etc etc etc etc

**Pull request closed without merging**
