### PR TITLE
Lustwish holobarrier can be used for saunas

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request

Makes the lustwish holobarrier block atmos passing so it can be used for setting up saunas.

## Why It's Good For The Game

Facilitate sauna building without flooding the corridor with steam.

## Changelog

:cl: LT3
balance: Lustwish holobarrier is usable for sauna construction
/:cl:

### CODE REVIEW

**Comment by ReturnToZender** [comment]
The poor man's atmos holofan

**Comment by BurgerLUA** [comment]
I'm conflicted about how my funny meme item is being turned into a buyable atmos holofan.

The correct solution to this is to implement it so that you can combine the atmos holofan with the funny meme item to make an advanced lustwish holobarrier which has the effects of an atmos holofan, instead of being able to buy a very powerful atmos holofan.

**Comment by Hislyna** [comment]
Just buy a tiny fan for 100 creds

**Comment by lessthnthree** [comment]
> Just buy a tiny fan for 100 creds

From?

**Comment by Hislyna** [comment]
> > Just buy a tiny fan for 100 creds
> 
> From?

Imports, Cargo

**Comment by lessthnthree** [comment]
> > > Just buy a tiny fan for 100 creds
> > 
> > 
> > From?
> 
> Imports, Cargo

I will reserve my grumbling that we allow people to buy tinyfans, let alone for 100 credits and no research, for somewhere else.

**Comment by nikothedude** [comment]
im confused that noone saw the obvious conflict between making an erp item have an actual mechanical use

**Comment by StrangeWeirdKitten** [comment]
> im confused that noone saw the obvious conflict between making an erp item have an actual mechanical use

Mate this PR got closed. Clearly it's not going into the game.

**Pull request closed without merging**
