### PR TITLE
Fixes security jumpskirts

### PR DESCRIPTION
**Pull request by KathrinBailey**
## About The Pull Request
• Fixes jumpskirts being overidden by turning it into it's own type.
• Red jumpskirts and blue jumpskirts are now separate and both available in the vendor.

## Why It's Good For The Game
No more bluesec bullshittery being forced on you.

## Proof Of Testing
errr arggh

## Changelog

:cl:
fix: Blue jumpskirts should not be in the vendor's red clothing section.
fix: Red jumpskirts should be available in the game again.
/:cl:

### CODE REVIEW

**Comment by ReturnToZender** [comment]
based love you Bailey ❤️

**Comment by projectkepler-ru** [comment]
I didn't know you still play :p

**Review by Majkl-J — CHANGES_REQUESTED** [review]
image
image

**Comment by KathrinBailey** [comment]
thanks skyrat for yet again showing us how not to do modularisation
turns out the skirts get their modular stuff defined in more than one file.
image
merge pl0x @Majkl-J

**Comment by Majkl-J** [comment]
> thanks skyrat for yet again showing us how not to do modularisation turns out the skirts get their modular stuff defined in more than one file. image merge pl0x @Majkl-J

Of course they do. A certified skyrat classic.

**Review by Majkl-J — APPROVED** [review]

**Pull request merged**
