### PR TITLE
energy sec

### PR DESCRIPTION
**Pull request by W0LF-101**
Removed MCRs and SMGs from Icebox, Meta, Delta, Void Raptor and Tram Station. Added 5 SC-1s, 5 SC-2s and 5 nonlethal energy shotguns to each armoury.

Added rubber rounds to icebox, meta and delta. Added lethal rounds to tram station. Removed 3 standard armour vests (non riot/bulletproof) from void raptor.

### CODE REVIEW

**Comment by ReturnToZender** [comment]
> > Removed MCRs and SMGs from Icebox, Meta, Delta, Void Raptor and Tram Station. Added 5 SC-1s, 5 SC-2s and 5 nonlethal energy shotguns to each armoury.
> > Added rubber rounds to icebox, meta and delta. Added lethal rounds to tram station. Removed 3 standard armour vests (non riot/bulletproof) from void raptor.
> 
> the Eshotguns are so fucking insane, keep the normal shotguns there.

Or make the eshotguns' stats match the regular shotgun in #75.

**Comment by AJK7370** [comment]
remove the lethal buckshot, keep the rubbers

**Comment by W0LF-101** [comment]
Based on player feedback, removed energy shotguns and readded MCRs to fill the gap and stop a whole load of research from science being useless because no MCRs. I'm going to try and tweak energy shotguns myself later on. But right now it seems like they're so much of a problem, the best move all round is to just remove them.

**Comment by projectkepler-ru** [comment]
Are you still intending to work on this? @W0LF-101

**Pull request closed without merging**
