### PR TITLE
Viva la flip emote

### PR DESCRIPTION
**Pull request by thegrb93**
## About The Pull Request
Cherry-picks https://github.com/Bubberstation/Bubberstation/pull/802

## Why It's Good For The Game
*flip

## Changelog

:cl: ReturnToZender
add: Flip emote returns to the PEOPLE
/:cl:

### CODE REVIEW

**Comment by nevimer** [comment]
nooo

**Comment by Hislyna** [comment]
This technically would count as a balance change, considering that it would give everyone access to the "I am invincible while I flip" bullet dodger skillchip from bitrunning

**Comment by thegrb93** [comment]
People already powergame their traits just be cute and flip. The trait is pointless and pretty lame.

**Comment by thegrb93** [comment]
> This technically would count as a balance change, considering that it would give everyone access to the "I am invincible while I flip" bullet dodger skillchip from bitrunning

Everyone SHOULD have access. Why would you ever get a skill chip for something you cannot even do? Also don't forget that this is already balanced by the fact you can trip and fall if you flip too much.

**Comment by thegrb93** [comment]
The trait also makes it impossible for borgs to flip

**Comment by StrangeWeirdKitten** [comment]
No, sorry.

**Comment by thegrb93** [comment]
What'd Ozzo say?

**Comment by thegrb93** [comment]
"If characters want to do a happy flip emote, they need to pay 8 quirk points"

**Comment by thegrb93** [comment]
@StrangeWeirdKitten @nevimer You really want Novastation to have better emote accessibility than Bubberstation? https://github.com/NovaSector/NovaSector/blob/51b7ad7be674a43c84b41768a8de80c42fb6329b/modular_nova/modules/emotes/code/emotes.dm#L80

**Comment by thegrb93** [comment]
https://github.com/NovaSector/NovaSector/pull/2525#issuecomment-2117023802

**Comment by nevimer** [comment]
they can have it. If you want to flip, here are my requirements. 
1. Make it so that you have to be in peak physical fitness to flip. No damage, no wounds, no hunger, no being stuffed, have worked out recently.
2. If you fail one of the requirements, you fall flat and get stunned. 
3. If you fail multiple requirements, you injure yourself, badly if you are already in bad shape.
4. Make a drug that lets you do this, skipping the prior checks (but legs have to work)
5. [this](https://www.tmz.com/2024/10/09/ishowspeed-backflip-record-attempt/)

**Comment by thegrb93** [comment]
@nevimer ok and what about borgs?

**Pull request closed without merging**
