### PR TITLE
Revert "New Quirk : Dead Inside"

### PR DESCRIPTION
**Pull request by Majkl-J**
Reverts Bubberstation/Bubberstation#761

## Why it's good for the game
The quirk, originally intended for undead characters, and seemingly a good idea, has been used only for the meme of "Hehe look at me I am dead inside"

Additionally it's been reported as buggy several times and we in no way have the manpower nor time to maintain a meme quirk. We should maintain some level of serious and this goes directly against that.

## Changelog

:cl:
remove: Dead inside quirk
/:cl:

### CODE REVIEW

**Comment by Majkl-J** [comment]
> There hasn't been any reports on discord of the quirk being bugged as far as I know, if there was. I would have dealt with it otherwise, additionally, that sound more of a 'you' issue since ive seen hemophage and custom humanoids, me included using it like it was intended.

image
image

It isn't a "Me" issue, this is just the select issues people had on the discord (Which you didn't even bother finding), excluding the complaints I received in game about it

**Comment by Majkl-J** [comment]
> > > There hasn't been any reports on discord of the quirk being bugged as far as I know, if there was. I would have dealt with it otherwise, additionally, that sound more of a 'you' issue since ive seen hemophage and custom humanoids, me included using it like it was intended.
> > 
> > 
> > image image
> > It isn't a "Me" issue, this is just the select issues people had on the discord (Which you didn't even bother finding), excluding the complaints I received in game about it
> > Additionally, if it's meant to be used on hemophages... you could've just made it a species trait
> 
> I've checked the discord's issues list and haven't seen those posts, So i problably haven't used the search properly, either way. The only issue is the SSD's timer not showing on examine, everything else is working, even the dnr one, I rather you didn't lie about such things. And locking traits to species? Cool but nah, it is mean to be used on both hemophage and Humanoids Species because it's literally a flavor quirk.

I only go off of bug reports I received, same with several other complaints. If you wanna blame it on lying, sure, go ahead. Won't change the fact a good part of players don't like it and that it has no flavor value because aside from like 2 people most don't use it for flavor, plus it actually affects gameplay by showing up on the HUD. If you make it examine only and fix the bug with it I'm fine with that too, but as it currently stands it intrudes upon gameplay and there is a clear divide where a decent part of people dont like it.

**Comment by Detective-Google** [comment]
people use this to powergame not showing up properly on health huds to conceal their health

**Comment by StrangeWeirdKitten** [comment]
Yeah, with further thought behind this. I think this was a mistake being merged.

**Pull request merged**
