### PR TITLE
Early ports modular lasers from Nova, they can talk to you!

### PR DESCRIPTION
**Pull request by Erol509**
## About The Pull Request

Description was copy pasted from Nova [PR#561](https://github.com/NovaSector/NovaSector/pull/561)

image

These new weapons, the modular energy rifles and carbines, have many unique functions.

Each of the two weapon types has its own collection of modes, each mostly unique from the other version of the gun.

For the long rifle, these include:

Two-burst laser mode
Sniper mode with massive scope
Windup autofire disabler machinegun
Plasma grenade launcher
Plasma shotgun
And for the short carbine these include:

Hellfire laser mode
Its A Sword Now
Trickshot disabler mode
Plasma flare launcher
Micro-shotgun
Each of the two can switch between these modes with a short delay and animation, though all modes run off of the same battery. Luckily, the battery does self-recharge, though at a very slow rate.

But there's something even better for these weapons, they talk to you.
Each mode and each variant of energy gun has its own little personality with it, and it'll talk to you when certain things happen. For example, switching modes, running out of power, picking them up, and more!

While this can be disabled, that would make the persona in the gun quite sad. You wouldn't want to do that, would you?

But, and I swear this is the last thing this time. Each of these guns has a built in soulcatcher (you can access it with alt-click!) for giving your weapons some REAL personality. And now you observer mains can finally live out your dreams of being someone's weapon!

## Why It's Good For The Game

Im going to replace ERT energy weapons with these guns, author of this weapons originaly replaced MCR's with these. Perhps if people will want to, I can replace mcrs with these....

## Proof Of Testing
<details>

image

https://github.com/Bubberstation/Bubberstation/assets/81807356/a6a8c8a2-f3ee-4b30-97e2-580e42f2ae56

https://github.com/Bubberstation/Bubberstation/assets/81807356/c560e26b-5d27-493a-b067-01957e4bb81a

https://github.com/Bubberstation/Bubberstation/assets/81807356/7a36eed6-45a7-42b4-af56-cb6022f15204

</details>

## Changelog

:cl: Paxilmaniac
add: A pair of new energy weapons has been added. Coming in both long and short versions, these persona-enabled weapons have many different modes they can rapidly reconfigure themselves between to fit whatever the operator's preferences may be.
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
Pax guns are not balanced at all, was hoping this PR would not be ported, but glad it's limited to ERT

Frankly the guns are too versatile, and I heavily dislike the idea of a laser shotgun that bypasses the shotgun problem of being hard to reload

**Comment by Erol509** [comment]
> Pax guns are not balanced at all, was hoping this PR would not be ported, but glad it's limited to ERT
> 
> Frankly the guns are too versatile, and I heavily dislike the idea of a laser shotgun that bypasses the shotgun problem of being hard to reload
> 
> Talking guns are a novelty, and nothing more. I suspect users will get annoyed with it quickly, and pAI guns are unlikely to ever see use once the novelty wears off.

They are a nice flavour to the round from time to time, but yeah they can get boring if always in armory. Im not sure about balance, they are not that bad. They have self recharge but its very slow. You need 4 head taps with shotgun mode to crit someone, but. someone without any armor. The bullets eats enough power to only allow single full kill. They have disabler mode, but its not that robust.

**Comment by YakumoChen** [comment]
> > Pax guns are not balanced at all, was hoping this PR would not be ported, but glad it's limited to ERT
> > Frankly the guns are too versatile, and I heavily dislike the idea of a laser shotgun that bypasses the shotgun problem of being hard to reload
> > Talking guns are a novelty, and nothing more. I suspect users will get annoyed with it quickly, and pAI guns are unlikely to ever see use once the novelty wears off.
> 
> They are a nice flavour to the round from time to time, but yeah they can get boring if always in armory. Im not sure about balance, they are not that bad. They have self recharge but its very slow. You need 4 head taps with shotgun mode to crit someone, but. someone without any armor. The bullets eats enough power to only allow single full kill. They have disabler mode, but its not that robust.

The versatility of the modes worries me, one walks out of security committed to a loadout, one gun should not do it all without major tradeoffs (carrying another mcr barrel in your bag for example)

Self charge just inflates the gun's value even more.

Between the options and self-charge these are things I wouldn't expect to see until mid-late into a round or from security spending time farming bounties. This isn't something I'd want to see factory standard in the armoury or ordered from cargo.

**Comment by Moostard** [comment]
Those weapons seem really cool and might be able to compete with the ballistic meta due to their mode swapping and self charging.
Would be nice if they were actually obtainable as a "premium" option just like the sol rifles.

**Comment by coffeecoffeecoffee** [comment]
The idea of an energy weapon that Transformers Robots In Disguis-es into any possible configuration to fight any enemy while also being a buddy who talks to you is honestly anti-fun, and probably shouldn't have been added to Nova in their current state in the first place. Would make an EXCELLENT traitor weapon, but I sincerely hope I never see these things in the armory, the MCRs are more satisfying in almost every way besides the funny talking gun aspect.

**Comment by IgiariValkyr** [comment]
Why is this not TM'd anymore?

**Comment by Majkl-J** [comment]
I forgor 💀

**Comment by IgiariValkyr** [comment]
> I forgor 💀

It's probably best to have them TM'd again for now with MCRs being outright busted at the moment. We can replace them in round until a fix is found and merged for those.

**Comment by Majkl-J** [comment]
> It's probably best to have them TM'd again for now with MCRs being outright busted at the moment. We can replace them in round until a fix is found and merged for those.

This is only for ERTs, and I can just grab the fix

**Comment by nikothedude** [comment]
plesae remove the ability for them to self-charge, MCRs cellswapping was a bad idea for a raeson and energy guns have been historically locked to rechargers for a _good raeson_

**Comment by nikothedude** [comment]
and yes ballistics blah blah 

ballistics are badly balanced for the crew and most notably sec and there is also a raeson tg gimped most ballistics sec can easily get

**Comment by Erol509** [comment]
> plesae remove the ability for them to self-charge, MCRs cellswapping was a bad idea for a raeson and energy guns have been historically locked to rechargers for a _good raeson_

I do believe that self recharge is so slow, and low. It wont show any significant change to combat, at most giving +1 shot after few minutes after which fight would be pretty much decided.

**Comment by AllCorruptingWyrm** [comment]
I honestly love these things, I think if they were locked behind research with gradual improvements for each research, we would see less ballistic sec and instead sec relying off of these weapons instead as ballistic sec isn't good for balance.

**Comment by Erol509** [comment]
> I honestly love these things, I think if they were locked behind research with gradual improvements for each research, we would see less ballistic sec and instead sec relying off of these weapons instead as ballistic sec isn't good for balance.

We will see, they are locked behind ERT to test their balance in less direct way

**Comment by ReturnToZender** [comment]
This was like, made in January, we can merge it

**Review by Majkl-J — APPROVED** [review]
These can stay ERT only

**Pull request merged**
