### PR TITLE
The Disk is important again.

### PR DESCRIPTION
**Pull request by theselfish**
## About The Pull Request

Restores Lone Ops so Captains/Acting Captains actually grab the disk. Their singular job.

## Why It's Good For The Game

See above. I'm not great at writing this stuff, but The Captain has one mechanical function;
Protect the Disk.
We should not be having conversations and arguments about "erm actually you don't have to grab the disk". Fuck off with that.
If you cannot do the bare minimum of your job, do not play the job.

If you wish to complain, please email me at idontgiveafuck@suckmydick.com

## Proof Of Testing

It compiles.

## Changelog

:cl:
balance: You will now protect the disk again. Live in fear.
/:cl:

### CODE REVIEW

**Comment by theselfish** [comment]
It compiles, I have no idea how I'd test this, honestly.

**Comment by radarseas** [comment]
I'd put a check for heads of staff in, **plus pop**, because the issue with loneop is it barely roles when its intended to be fun _aka cap loses disk on 50ish pop but crew has enough people to have a fighting chance_ and instead rolls non-stop on like 1-16 pop... where most of the crew consists of assistants, doctors, maybe the odd CT and miner _that's going to actually have to do their job instead of run off to hunt vault_ and probably a QM or at worst an RD or CE.. let alone a HoP.. that's even considering the chance that more than one secoff exists, or any sec at all.

Believe me, extremely lowpop rounds aren't fun to have a guy with an _**L6 LMG rock up and slaughter everyone**_ without warning nor resistance about _**35 minutes into the round**_ because you literally can't do much but hope the round's traitors decide to vigilantee them, or they're just that unrobust they get owned by the clown. _which with nukie gear is pretty hard to get owned that hard._

**Comment by theselfish** [comment]
TG should have safeguards like that in place.

Otherwise, If on lowpop you can't get some tools to hack one, maybe three doors, I don't know what to tell you.

**Comment by radarseas** [comment]
> TG should have safeguards like that in place.
> 
> Otherwise, If on lowpop you can't get some tools to hack one, maybe three doors, I don't know what to tell you.

true, but here we are!

**Comment by aKromatopzia** [comment]
> TG should have safeguards like that in place.
> 
> Otherwise, If on lowpop you can't get some tools to hack one, maybe three doors, I don't know what to tell you.

there's no need to encourage greytiding

**Comment by theselfish** [comment]
> > TG should have safeguards like that in place.
> > Otherwise, If on lowpop you can't get some tools to hack one, maybe three doors, I don't know what to tell you.
> 
> there's no need to encourage greytiding

It's not greytiding to prevent the station from getting destroyed.

**Comment by BurgerLUA** [comment]
I think the PR description and the events that happened earlier today is precisely why this should remain disabled.

A new acting Captain HoP didn't secure the disk so an admin spawned a lone op. The lone op took the disc and nuked the station. Players proceeded to bully the HoP on discord and OOC for basically ruining their round. There is so much toxicity surrounding this event that I think that it's extremely detrimental to the server.

I'm fine with re-adding a lone op if it had the objective to steal the disk and maybe assassinate a random member of command as punishment, but for it to nuke the station is not really good for the server for the reasons above. Rounds shouldn't end fullstop because someone forgot to pick up a single item, especially when the crew at large are not actually really involved in this since they're not notified of impending doom like the supermatter does before it explodes or honestly anything else that can end the round for that matter.

**Comment by theselfish** [comment]
If you are too incompetent to do the simplest things, your only mechanical duty as acting Captain is picking up an item so small it can fit in a wallet or even be implanted...

Then I'm sorry, but playing Command is not for you.
On one hand, yes it's bad that happened. On the other. At what point do you look in the mirror and go "I am at fault"?

Today's round is a perfect example of why it needs to be re-enabled. Skyrat disabling it has allowed a culture of stupidity to grow even worse. If you cannot handle picking one single object up, stick to a job without responsibility, like an assistant.

The Lone Op was practically handed the disk. They walked around in a full modsuit. They even set the timer for an HOUR. Left, came back, reset the timer, set it to a better time and left. Again.
All while Security and the HoP had thumbs up their asses.
The answer to player incompetence is not to reward it, but punish it.

**Review by Majkl-J — CHANGES_REQUESTED** [review]
Maybe an automatic centcom warning when the disk wasn't secured for like 15 and then 30 minutes? 

Considering the mess you have to resolve as AC it's really easy to forget because you'll have people yelling at you from everywhere. So getting a reminder that the diskie is not tucked safely into someone's bag would be nice

**Comment by BurgerLUA** [comment]
> Today's round is a perfect example of why it needs to be re-enabled. Skyrat disabling it has allowed a culture of stupidity to grow even worse. If you cannot handle picking one single object up, stick to a job without responsibility, like an assistant.
I got news for you.

My brother in christ, we're playing an a furry erp server.

It legitimately amazes me that there exists a subset of people who act like military larping boomer gym teachers where they believe that humiliating students and subjecting them to physical and emotional abuse builds character somehow and makes the server better. It doesn't.

**Comment by theselfish** [comment]
> > Today's round is a perfect example of why it needs to be re-enabled. Skyrat disabling it has allowed a culture of stupidity to grow even worse. If you cannot handle picking one single object up, stick to a job without responsibility, like an assistant.
> > I got news for you.
> 
> My brother in christ, we're playing an a furry erp server.
> 
> It legitimately amazes me that there exists a subset of people who act like military larping boomer gym teachers where they believe that humiliating students and subjecting them to physical and emotional abuse builds character somehow and makes the server better. It doesn't.

If someone believes that having to pick up one tiny green object is emotional and or physical abuse they are not emotionally mature enough to play on this server.

**Comment by AllCorruptingWyrm** [comment]
At no point was fish ever telling people to be humiliated from playing the role, instead, they were telling people to do their job. Every SS13 server has it so the Captain/AC should have the disk or its equivalent. Do the job to standards or at least ask for help and delegate down.

**Comment by theselfish** [comment]
> At no point was fish ever telling people to be humiliated from playing the role, instead, they were telling people to do their job. Every SS13 server has it so the Captain/AC should have the disk or its equivalent. Do the job to standards or at least ask for help and delegate down.

I don't think community shaming was the intent. It's a byproduct of us making the disk useless. Because on most other servers, people point, laugh and the Captain goes "ah well, I won't do it again." Here, we whine, we complain, we demand it get removed.

**Comment by Gandalf2k15** [comment]
people probably forget the disk exists, loneop has been gone for ages

**Comment by radarseas** [comment]
> Maybe an automatic centcom warning when the disk wasn't secured for like 15 and then 30 minutes?
> 
> Considering the mess you have to resolve as AC it's really easy to forget because you'll have people yelling at you from everywhere. So getting a reminder that the diskie is not tucked safely into someone's bag would be nice

apart from needing a population lock, honestly loneop only rolls **once**, per round anyway, yeah if someone crashes out and nobody notices for about 10 plus minutes I think its good to inform people.

_buuuut_, on the flipside of the coin the NAD is the easiest thing to find, it would need the HoS dead to not notice since they have a pinpointer, plus the shield, plus the entire crew will drop everything to rumage maintenance with an announcement, I think the silent threat is fine as it is.

Blitz is the entire strength of loneops, their guns will absolutely shread unprepared crew but once crew armors and arms up they're suddenly not that formidable, they can certainly still kick ass and kill like 4 people per encounter, but attrition will win in the end.



maaaaaaaaaybe an _SSD check is fair_ plus another if its _not ever been touched during the round_. buuuut, I don't like the idea of it being missing hugboxed, otherwise its going to take someone purposefully aiming to trigger loneops for it to ever happen during a round, or exceptionally incompetent/shortstaffed crew.

If an acting captain isn't going to drop everything to secure the disk, that's on them, everything else can be ignored even if the station suffers, keeping operatives from getting the disk **should** be more important than command matters as a stationwide matter.

**Comment by StrangeWeirdKitten** [comment]
I'm not renabling lone ops without changes otherwise I would've done it weeks ago. #995 is an interesting solution. Lone ops may work for TG for specific things, but are rounds are very fundimentally diffrent to cater around the requirements the disk has. (mostly forcing it to be always on the move)

**Pull request closed without merging**
