### PR TITLE
Reverts a few of the security alert sounds back to SR's

### PR DESCRIPTION
**Pull request by iliyaxox**
## About The Pull Request

A few of Bubberstation's current security alerts have been reverted back to Skyrat's (blue, orange, amber, red, gamma).

With the previous (BurgerLUA's) PR (#580)'s main point in mind (this being, the unnecessary loudness present in most of SR's alert sounds), each and every .ogg added was refined in Audacity to decrease the peak without necessarily altering the volume.

## Why It's Good For The Game

Although "quieter" alerts were indeed necessary, some of the media added didn't match SS13's environment, and most of the time, didn't exactly make up for the threat which led to the change of alert in the first place and wasn't capable of maintaining immersion (for example, red alert being Among Us' imposter sabotage alarm sound while there's a maniac wielding a double energy sword killing security). Skyrat's are loyal to the dynamic and authenticity of the game, and certainly live up to Bubberstation's mildly chaotic rounds.

Attention! For the sake of your ears, the comparison video, because it's including /both/ loud and quieter audios, it can, obviously, be uncomfortable to your ears.

https://github.com/Bubberstation/Bubberstation/assets/64568243/f5147211-3c94-457b-89e1-cc95dfe4876b

## Changelog

🆑 Chelxox
sound: A few of the alert sounds were reverted back to Skyrat's and modified to reduce peaks and make them more comfortable to the ear.
/🆑

### CODE REVIEW

**Review by Majkl-J — APPROVED** [review]
Probably needs further discussion, but sounds so much better and less ear piercing

**Comment by nevimer** [comment]
Use compression to master at -22db, use whatever attack time sounds best.

**Comment by iliyaxox** [comment]
> Use compression to master at -22db, use whatever attack time sounds best.

Do you mean those changes to be done with the SR's OG alert files or the already-modified ones? I've tested the method with SR's and I feel like it sounds pretty much the same as the ones I displayed, if not slightly louder, but not enough to be ear piercing.

**Comment by theselfish** [comment]
Why not just revert it to the vastly superior https://github.com/Skyrat-SS13/Skyrat-tg/pull/8562 ?

**Comment by iliyaxox** [comment]
> Why not just revert it to the vastly superior [Skyrat-SS13/Skyrat-tg#8562](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8562) ?

Although I agree that PR was a very interesting project at the time, that'd be a really tight turn-of-intent and not exactly the point of this PR. The main point is to 1. Make alerts more organic (and less LRP-y such as a few of the ones we currently have) and 2. Replace them with SR's (except less ear piercing). I'll gladly close this PR if someone would be willing to mirror the one you've mentioned, though I remember a few issues with licensing following suit involving 15.ai (which was, IF I remember correctly, the reason why those changes didn't stick around SR for too long.)

**Comment by theselfish** [comment]
> > Why not just revert it to the vastly superior [Skyrat-SS13/Skyrat-tg#8562](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8562) ?
> 
> Although I agree that PR was a very interesting project at the time, that'd be a really tight turn-of-intent and not exactly the point of this PR. The main point is to 1. Make alerts more organic (and less LRP-y such as a few of the ones we currently have) and 2. Replace them with SR's (except less ear piercing). I'll gladly close this PR if someone would be willing to mirror the one you've mentioned, though I remember a few issues with licensing following suit involving 15.ai (which was, IF I remember correctly, the reason why those changes didn't stick around SR for too long.)

They were removed because Skyrat found a robotic voice that didn't pierce ear-drums "less meme-y" which I found stupid.
It could be Peter Griffin doing the voice for all I care, as long as it sounds better than Skyrat.

Though, I'm not 100% sure. What I said was what I was told, @Iamgoofball might have been told different.

**Comment by Kyogon** [comment]
I'm really hoping this is fixed up so it can merge sometime soon, I miss that red alert sound, it's probably my favorite alert sound and it sounds better like this too!

**Pull request merged**
