### PR TITLE
[UPSTREAM MIRROR] Fixes a typo in electrical damage description + prevents electrical damage from worsening during repairs + remove some nova edits

### PR DESCRIPTION
**Pull request by nikothedude**
## About The Pull Request

https://github.com/Skyrat-SS13/Skyrat-tg/pull/28445

## Why It's Good For The Game

Upstream mirror!! Yippee!!

## Changelog

:cl:
spellcheck: Fixed a typo in systemic fault's examine text
balance: Synthetic electrical damage can no longer worsen if its currently being repaired
/:cl:

### CODE REVIEW

**Review by projectkepler-ru — CHANGES_REQUESTED** [review]
Commit hash doesn't match

**Comment by nikothedude** [comment]
> Commit hash doesn't match

Not sure what that means, but I had to resolve a merge conflict in chatmessage.dm, line 124-128, because skyrat upstreamed a change we made

**Comment by projectkepler-ru** [comment]
Did you use the terminal with your upstream PR as remote or did you re-create this by hand

**Comment by nikothedude** [comment]
> Did you use the terminal with your upstream PR as remote or did you re-create this by hand

I ran git cherry-pick bbc673d via vscode terminal, which is the squashed commit of the referenced pr

**Comment by nikothedude** [comment]
If the commit hash is supposed to be the same, again, it might be because I had to solve a merge conflict

**Comment by nikothedude** [comment]
idk why but im not getting notifications for this thread

**Pull request merged**
