### PR TITLE
Echolocation 2: Witty PR title edition

### PR DESCRIPTION
**Pull request by Superhats**
## About The Pull Request
Ports (again) the Echolocation quirk from NovaSector.  (https://github.com/NovaSector/NovaSector/pull/525) A second attempt at #1333 after finally being bothered to try upstream (and failing because Skyrat doesn't have chat colors for their runechat.)

## Why It's Good For The Game
See the original PR: https://github.com/NovaSector/NovaSector/pull/525
More quirks are fun, this adds an interesting alternative for blind characters.

## Changelog

:cl:VrazzleDazzle
add: Added the echolocation quirk from Nova Sector
/:cl:

### CODE REVIEW

**Review by Majkl-J — COMMENTED** [review]
This seems like a shit ton of code for this, but eh. TMing

**Comment by ReturnToZender** [comment]
Fails linters, can't be testmerged until that's fixed

**Comment by Superhats** [comment]
I'm gonna be honest, I forgot I had this PR open. I don't play here all that often anymore, I don't know how to fix TGUI, so given this is apparently bad code, too, I'm just going to close this again. Someone else can try to port this if they're inclined.

**Comment by ReturnToZender** [comment]
> I'm gonna be honest, I forgot I had this PR open. I don't play here all that often anymore, I don't know how to fix TGUI, so given this is apparently bad code, too, I'm just going to close this again. Someone else can try to port this if they're inclined.

It was one comma

**Comment by Superhats** [comment]
That goes to show how little I understand about what I'm actually doing here. I won't be able to fix anything if the TM runs into issues so I'd rather not open that can of worms.

**Pull request closed without merging**
