### PR TITLE
Let borgs into gateway

### PR DESCRIPTION
**Pull request by thegrb93**
## About The Pull Request
Some borg players complained about this so I made a PR
## Proof Of Testing
<details>
<summary>Screenshots/Videos</summary>

</details>

## Changelog
:cl:
balance: Borgs can go into gateway now
/:cl:

### CODE REVIEW

**Review by nevimer — APPROVED** [review]

**Comment by nevimer** [comment]
add testing video and ill merge it

**Review by lessthnthree — APPROVED** [review]

**Comment by thegrb93** [comment]
Idk how to set up gateway destinations to test it. Do you gotta copy something to config/away_missions?

**Comment by Erol509** [comment]
> Idk how to set up gateway destinations to test it. Do you gotta copy something to config/away_missions?

Load away mission verb, then select one from your repo files

**Comment by thegrb93** [comment]
> > Idk how to set up gateway destinations to test it. Do you gotta copy something to config/away_missions?
> 
> Load away mission verb, then select one from your repo files

I get this, which lets me browse, but I still don't know where the .dmm I need to load is...

image

**Comment by Arturlang** [comment]
all the gateway maps are in _maps/RandomZLevels

**Comment by thegrb93** [comment]
Found it. I also had to teleport to 'Beach' area and active the portal by touching it.

[2024-11-19 13-25-06.webm](https://github.com/user-attachments/assets/d9d4e4c8-3978-4f90-a859-e6a5750a90e8)

**Pull request merged**
