### PR TITLE
Fix NorthStar CI failure

### PR DESCRIPTION
**Pull request by TealSeer**
## About The Pull Request

Add `/area/nearstation` to the second Z level of the NorthStar ERT Bay template as it was loading in as `/area/space` and making CI sad.

## Why It's Good For The Game

One less check failure.

## Proof Of Testing

I ran the checks before/after I prommy

<details>
<summary>Screenshots/Videos</summary>
hi :)
</details>

## Changelog

:cl:
fix: Fix missing areas in NorthStar ERT Bay
/:cl:

### CODE REVIEW

**Comment by TealSeer** [comment]
They're inventing new failures to hurt me

**Comment by StrangeWeirdKitten** [comment]
Northstar is not a map maintained by us. So feel free to fix by purging

**Comment by TealSeer** [comment]
OK so that wasn't a new error it was a very unlikely combination of events where a maintenance loot spawner spawned a haunted toolbox and then the haunted toolbox teleported outside the station before the test ran so it was technically an object without an area. I love this game

**Comment by lessthnthree** [comment]
I removed Northstar from CI, so... problem solved!

**Comment by TealSeer** [comment]
let's fucking goooo, should I close this then?

**Comment by lessthnthree** [comment]
Yeah, might as well. If we ever run Northstar again, we'd pull a fresh copy from TG master.

**Pull request closed without merging**
