### PR TITLE
adds missing raptor borg sprites & fixes raptor borg sprite eyes

### PR DESCRIPTION
**Pull request by aKromatopzia**
## About The Pull Request

adds PK, syndie, fancyraptor for service & CC sprites for raptorborg. quick and dirty.
It compiles, it seems to work. All is well.

Since service was made to be a white raptor, this one is grey in comparison. along with a brighter flank-mark. 
### pk:
widerobot_pk Screenshot_46

service [not new, just comparing to above]:
widerobot_serv Screenshot_47

### cc:
only the raptor is my work, the vale sprites go back to the original artist, QuartzAdachi
widerobot_cc Screenshot_51

### syndie:
sheet

## eye fix
after
Screenshot_52
before
Screenshot_53

## Why It's Good For The Game

it's missing and that irritated me
then I fell down a rabbit hole of fixing things

## Changelog

:cl:
add: raptorborg peacekeeper sprite
add: raptorborg cc sprite
fix: raptorborg eye overlays by making a - to _
removed: one pixel which caused asymmetry for no reason
???: Made sec and syndie raptors angry
/:cl:

### CODE REVIEW

**Comment by StrangeWeirdKitten** [comment]
Please add pictures.

**Comment by aKromatopzia** [comment]
> Please add pictures for everyone else to look at a glance. But I'm glad to add peacekeeper raptor sprites :)

right yes, was getting the screenshots. done now

**Comment by StrangeWeirdKitten** [comment]
> > Please add pictures for everyone else to look at a glance. But I'm glad to add peacekeeper raptor sprites :)
> 
> right yes, was getting the screenshots. done now

Looks awesome.

**Comment by theselfish** [comment]
I don't even like these things, but this makes them look far better.


P.S; Replace the Service Model with the fancyborg, the one with the top hat.
The service one doesn't scream service already.

**Comment by aKromatopzia** [comment]
> I don't even like these things, but this makes them look far better.
> 
> P.S; Replace the Service Model with the fancyborg, the one with the top hat. The service one doesn't scream service already.

the eye thing is how they were supposed to look actually, it just got ported incorrectly.

also I'm not going to add a top hat to the service model - fancyborg already exists and the sprite sheet doesnt have that kind of real estate sadly

**Comment by theselfish** [comment]
> > I don't even like these things, but this makes them look far better.
> > P.S; Replace the Service Model with the fancyborg, the one with the top hat. The service one doesn't scream service already.
> 
> the eye thing is how they were supposed to look actually, it just got ported incorrectly.
> 
> also I'm not going to add a top hat to the service model - fancyborg already exists and the sprite sheet doesnt have that kind of real estate sadly

You're misunderstanding.
I think you should replace the current model WITH the Fancyborg.

**Comment by aKromatopzia** [comment]
> You're misunderstanding. I think you should replace the current model WITH the Fancyborg.

that's... already in the game? why would I need to do that

**Comment by StrangeWeirdKitten** [comment]
This is off topic, and raptor borgs aren't going to be removed.

**Review by Majkl-J — APPROVED** [review]
Actually feeling embarassed because I triple checked my work and couldn't notice that I used a dash instead

**Comment by theselfish** [comment]
> This is off topic, and raptor borgs aren't going to be removed.

You're also misunderstanding.

I am saying, that the sprite we have for the service raptor borg, the white one, should be replaced with this.
image
Not to remove raptors.

**Comment by aKromatopzia** [comment]
> > This is off topic, and raptor borgs aren't going to be removed.
> 
> You're also misunderstanding.
> 
> I am saying, that the sprite we have for the service raptor borg, the white one, should be replaced with this. image Not to remove raptors.

if you give me the entire sprite sheet ill make a variant sure

**Comment by theselfish** [comment]
> > > This is off topic, and raptor borgs aren't going to be removed.
> > 
> > 
> > You're also misunderstanding.
> > I am saying, that the sprite we have for the service raptor borg, the white one, should be replaced with this. image Not to remove raptors.
> 
> if you give me the entire sprite sheet ill make a variant sure

https://files.catbox.moe/qi4xi7.dmi
There.
It's in the other codebase raptor borg sprites.

**Review by Majkl-J — APPROVED** [review]
No idea how I missed my review being needed, but merge ready, gonna give it just 12 hours because it's been ready for weeks

**Pull request merged**
