### PR TITLE
Ports GAS

### PR DESCRIPTION
**Pull request by nevimer**
https://github.com/Skyrat-SS13/Skyrat-tg/pull/22123

Dead skyrat PR, I am interested in it. Gonna testmerge. Don't expect GAS to be permanent.

### CODE REVIEW

**Comment by BurgerLUA** [comment]
Not sure what the lore is for the species, but on other servers there is some pretty questionable lore that might be p r o b l e m a t i c for an ERP server. I suggest that there is established custom lore with this PR

**Comment by zeroisthebiggay** [comment]
No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No.

**Comment by BurgerLUA** [comment]
If people think GAS are too OP or whatever, they could always be an off-station role.

**Comment by StrangeWeirdKitten** [comment]
GAS is severely unfinished and adding sprite variations is an awful task (that no one upstream is willing to do) to implement anyway. Non-standard species just suck, immensely. Honestly, it would be better to just hope for skyrat to do it unless someone's willing to sit down and trudge through all the sprites.

**Comment by Zirok-BYOND** [comment]
@TeshariEnjoer

**Comment by TeshariEnjoer** [comment]
> @TeshariEnjoer

Hello I here. How I can help?

**Comment by Zirok-BYOND** [comment]
What happens to the preferences of the people who have GAS characters if this ever gets unmerged?

**Comment by TeshariEnjoer** [comment]
> > > @TeshariEnjoer
> > 
> > Hello I here. How I can help?
> 
> We're a Skyrat Downstream, I figured you'd want to know that we're interested in something you made!

In general, they are more than working. And I fully implemented them, but already on another server. look at my active. PR. in general, in the state that they are here more than working. just need a little information in the code. since TG recently changed the code of the races.

**Comment by nevimer** [comment]
> What happens to the preferences of the people who have GAS characters if this ever gets unmerged?

They become humans.

**Comment by projectkepler-ru** [comment]
this is possibly the biggest crossover event i've ever seen

**Comment by nevimer** [comment]
Closing because the OG author can re-pr it. We can till TM closed PR's

**Comment by coffeecoffeecoffee** [comment]
Hi, I have some playtesting feedback for serpentids! They look and feel generally amazing to play - the way people seem to treat me as one is exactly what I want out of playing a giant freaky bug alien, without it getting disrespectful or obnoxious. People seem to be able to engage with it maturely. The variety of clothing items that actually work with their sprite is surprising. However:

—Belts work when facing forwards and back, but are hovering in the air when facing right or left. If the belt was offset right/left a certain amount, it would work without needing any other changes to the sprite.
—Armbands look REALLY good when first put on, but seem to migrate upwards into space above the serpentid over time for some reason.
—Serpentid eyes don't show bright colors well and make them look dark and muddy - probably a simple issue with the base sprite that'd be easy to fix by lightening it up a little.
—Many genital options work great facing forwards and back but need to be offset a fair bit when facing left and right.
—It would be extremely nice (cursed) to be able to use tits on serpentids, and I think you'd only have to shift them upwards on their sprite for them to work if you wanted to make that an option.

Balance wise:
— The (extremely limited) spaceworthiness they bring to the table feels good and doesn't let you do too much. I definitely wasn't able to sustain a fight against a blob in vacuum for very long and had to repeatedly come back, but it felt tenable, like having to come up for air in an underwater level. I cannot reasonably chase things out there for a significant distance or anything. 10/10
— The clothing items they can and can't wear feels well thought out and fair. I'm definitely able to play effectively without suit slots.
— Their limited advantages fall off pretty hard later into the game and against any kind of major threat - they start to feel extremely frail with only their natural armor against major threats like spiders, where everybody else is wearing armor vests and modsuits.

I don't think I've laughed as hard as I did when I discovered all the hats serpentids can wear in a long, long time. Extremely underrated addition. 👍

**Comment by UntoldTactics** [comment]
As said by TeshariEnjoyer, they've already managed to port the more complete version to another server [https://github.com/Fluffy-Frontier/FluffySTG/pull/62](url)

Probably get that updated code and bring it here, then see how that goes if it is integrated well. The only issue with GAS I can forsee at the moment is the need for sprites, be it for items they wear or for their body sprite itself, considering whilst it works fine for bay they look kinda janky here. Some of the stuff in that more complete PR may also need to be touched upon or changed. (Also they look too small by default, I think.) 

I like GAS and I think its a shame that they aren't easy to add to other servers and that even most baycode servers abstain from em, but yeah, there's a reason for that, it's goddamn hard to get them integrated well.

**Comment by ReturnToZender** [comment]
This needs to be fullmerged instead of constantly testmerged, we have a lot of GAS players and they aren't keen on having their character deleted every upstream merge @nevimer

**Comment by pitaden** [comment]
Jumpsuits, gloves, and neck items are currently offset incorrectly on GAS for all directions
largeprotectedsnake

**Comment by StrangeWeirdKitten** [comment]
Sadly GAS is depreciated code where the original PR was closed on skyrat and the original author doesn't seem to have any plans to make them return. I can't merge this in their current state, and understand that making a non-human sprite species is a very massive task.

- The species is very bare. The only thing going for them is that they look alien.
- Sprites. Go look how at Teshari as an example and the amount of work went into that species alone.
- Maintainability. It's not going to be feasibly maintained. I don't have anyone lined up to bring all the sprites in line. I doubt it's ever going to happen. This is fundamentally why it was closed on Skyrat 

If anyone cares enough to keep GAS around, you are free to open a PR and we can make a plan to reintroduce them, but understand that a ton of work will be required to get this species anywhere close to our current species standards.

**Comment by SonicGotNuked** [comment]
Sorry to all the characters I just broke.

**Comment by IgiariValkyr** [comment]
Add back the laugh and scream.
image

**Pull request closed without merging**
