### PR TITLE
[Early Pull] New Loadout

### PR DESCRIPTION
**Pull request by StrangeWeirdKitten**
image

### CODE REVIEW

**Comment by StrangeWeirdKitten** [comment]
- Renaming items
- Missing ckey donator items

**Comment by StrangeWeirdKitten** [comment]
This doesn't touch the database. So it should be safe to test merge and yank from the server. Though there might be a crashing issue that will need to be investigated.

**Comment by nikothedude** [comment]
nova is already doing this and started earlier than you guys, might be worth looking into how theyre implementing it

**Comment by nikothedude** [comment]
o wait is this am erge off usptream

**Comment by StrangeWeirdKitten** [comment]
bless waterpig for also helping with this.

**Comment by plsleavemealon** [comment]
Some things from the current test merge on live:

First, why was the "other" category reduced from 3 to 2, is this just a typo?  If not that just removes my ability to have my carefully crafted items that were tailored specific for my character.  If you are afraid of people "gamering" with the medkits....shove the medkits into their own category, and only let people pick 1.

Second, it appears to be missing categories, like formal outfits and miscellaneous outfits.

Third it appears to be causing some sort of input spam, as opening a category causes a _lot_ of "your previous action was ignored" to show up in the chatbox

**Comment by Majkl-J** [comment]
> Some things from the current test merge on live:
> 
> First, why was the "other" category reduced from 3 to 2, is this just a typo? If not that just removes my ability to have my carefully crafted items that were tailored specific for my character. If you are afraid of people "gamering" with the medkits....shove the medkits into their own category, and only let people pick 1.

Probably tg values. Will update independently

> Second, it appears to be missing categories, like formal outfits and miscellaneous outfits.

Merged into suits and uniforms from what I can see and seeing as no loadout defines existed for it even before
image


> Third it appears to be causing some sort of input spam, as opening a category causes a _lot_ of "your previous action was ignored" to show up in the chatbox

Can't reproduce, probably just some tgui race condition or bug with a byond version

**Comment by Majkl-J** [comment]
> Edit: Example of items missing: Formal Evening Gown, Pink Clown Dress, and virtually any other item from those 2 categories
> 
> Edit 2: If they were supposed to be merged into one category (oof that would be a gigantic category...), they presently aren't as all items from them are not there.

I see, it's missing the bubber ones, skyrat repathed all their ones (See recolorable shorts for example). Well since this is stopping me from upstreaming so we get other shit fixed I'll merge this and fix those independently

**Comment by plsleavemealon** [comment]
If only things were easy x-x

**Comment by plsleavemealon** [comment]
I really hope this didn't straight up delete my items descriptions.  I won't be turbo fucked because I have it saved on a txt, but god if it did its going to be so annoying.

**Comment by StrangeWeirdKitten** [comment]
> I really hope this didn't straight up delete my items descriptions. I won't be turbo fucked because I have it saved on a txt, but god if it did its going to be so annoying.

Item descriptions are still intact.

**Comment by plsleavemealon** [comment]
OK good.  Now to hope that the bug preventing us from setting the item description gets fixed so I can fix my characters deleted dress (and thankfully re-added, ty waterpig for fixing that so fast), since her the description was deleted along with the item when it was sadly removed from being able to be chosen by mistake.

**Comment by IgiariValkyr** [comment]
List of items that show as errors or wrong icon:

**Head:**
- Cattleman Hat, Security
- Colourable Back Bow
- Colourable Large Bow
- Colourable Maid Headband
- Colourable Small Bow
- Colourable Sweet Bow
- Deputy Hat
- Flat-Brimmed Hat
- Flat-Brimmed Hat with Cowl
- Poly Flat Cap
- Recolorable Cattleman Hat
- Recolorable Wide-Brimmed Cattleman Hat
- Sheriff Hat
- Wide-Brimmed Cattleman Hat, Security
- Wide-Brimmed Feathered Hat
- Wide-Brimmed Hat
- Winter Cowboy Hat

**Other:**
- Asexual Flag
- Bisexual Flag
- Korpstech Poster
- Lesbian Flag
- Pansexual Flag
- Rainbow Flag
- Royal Zippo (not showing overlay)
- Standard Power Cell
- Toaster Implant
- Trans Flag
- Wildcard Ingredient Box
- Zippo Lighter (not showing overlay)

**Uniforms:**
- All Shorts
- Cableknit Sweater
- Keyhole Sweater
- Recolorable Jean Shorts
- Red Shorts
- All Trekkie Uniforms (not showing shirts)

**Suits:**
- Anubite Headpiece (it's headwear in the suit section)
- All Hoodies
- All "Shirts" (hawaiian, graphic shirts, etc)
- Cardigan
- Colorable Duster
- Colorable Peacoat
- Colourable Heart Sweater
- Colourable Warm Coat
- Colourable Warm Sweater
- Flannel Shirt
- Mothic Flightsuit
- Mothic Mantella
- Recolorable Tailored Jacket
- Recolorable Tailored Short Jacket
- Recolorable Winter Coat
- Urban Coat
- Varsity Jacket

**Shoes:**
- All Sneakers
- Colorable Cloth Wraps
- Colorable Leg Wraps

**Comment by Erol509** [comment]
Dragon Maid Dress is also gone

**Pull request merged**
