### PR TITLE
Medical Cyborg Instantaneous Injection Nerf, Mutually Exclusive with Haloperidol Removal

### PR DESCRIPTION
**Pull request by Alecksohs**
## About The Pull Request

Adds a 1 second injection time to the injection period of the cyborg hypospray. This is faster than the typical injector.

Video is 3 seconds. I've sped it up after recording.

https://github.com/Bubberstation/Bubberstation/assets/32783144/ab2b847a-b830-4898-ab5c-ec13bb5f9af0

## Why It's Good For The Game

Cyborg Chemical ClickCombat on any module degrades the combat of the game, making borgs an unnessicary "AVOID AT ALL COSTS DO NOT ROLEPLAY" if you're an antagonist. No more. Players now have time to react before they get pricked. In order for a borg to detain a player using chemicals, they must sideways the enemy. This could be through flashes, knocking them over with a dragged banana, among other methods. This makes borgs easier to roleplay with, less mechanics focused and most importantly, removes the medical cyborg from the front lines. Hallelujah. 

## Changelog

:cl:
balance: Added an Injection Timer to the Borg Hypospray
/:cl:

### CODE REVIEW

**Comment by destrucktoid** [comment]
The exact thing you are after, removing medical borgs from the frontlines and moving them to a support role, can be done just by removing haloperidol from their injector without the stupid 1 second injection mechanic.

**Comment by DuffCreeper** [comment]
It would've been easier to move Haloperidol to being a hacked module chem with less questioning by players rather than changing it like this.

Besides mediborgs shouldn't be on the frontlines regardless and changing this to be a hacked module will solve that issue full stop without changing how their tool functions.
(Plus a borg asking for hacked modules is a tad eyebrow raising)

**Comment by Alecksohs** [comment]
Keep in mind this PR is ideally mutually exclusive with my seperate PR. The maintainer posed two ideas so I went ahead and made both. I prefer this one but I can see the strengths of both and don't mind getting either.

**Comment by DeerJesus** [comment]
I support this heavily on the basis that peacekeeper borgs are kinda annoying

**Comment by nevimer** [comment]
We merged the haloperidol removal.

**Pull request closed without merging**
