### PR TITLE
Adds a mood penalty for death, plus new quirk that negates it.

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Adds a mood penalty for death. The mood penalty can be removed by having a great sanity, and a good mood.
Adds a quirk that prevents the mood penalty from being applied.

## Why It's Good For The Game

Needs more penalties for death, even if it's minor like mood.

## Changelog

:cl: BurgerBB
add: Adds a mood penalty for death, plus new quirk that negates it. The mood penalty for death can be removed by having a great sanity and a good mood.
/:cl:

### CODE REVIEW

**Comment by BurgerLUA** [comment]
draft because untested

**Comment by Majkl-J** [comment]
The penalty for death is not getting to play

**Comment by nevimer** [comment]
We talked about death punishments a few days before you made this. I think it's a good pr. I will review it in a bit. Death will have consequences here post revival.

**Comment by 50Potas50water** [comment]
> The penalty for death is not getting to play

unless you're a miner you get revived within a few minutes

**Pull request closed without merging**
