### PR TITLE
The Space MP5

### PR DESCRIPTION
**Pull request by Offwrldr**
## About The Pull Request

Recently, a fellow by the name of Cato Christopher made me aware of a conversion kit within the game that is unimplemented. From what I could see, it was possibly never completed - the RomTech SMG, a conversion of the Sindano to make it fully-automatic. The magazine sprite, for example, was incorrectly aligned with the original sprite. There was talk in the code about making it researchable. I have taken it in as my own.

Introducing the _Shaytan_.

Sprite-000ddd2

Description: A Romulus-produced conversion kit. This kit comes with a modified sear to enable seamless full-automatic fire - at the cost of fire-select function. This kit includes an alloy and polymer body, a proprietary **integrated flashlight**, an **alternate handguard and modified barrel for the addition of universal suppressors**. Accepts any standard Sol pistol magazine.

It has been tested. It passed. See performance [here.](https://github.com/Bubberstation/Bubberstation/pull/2194#issuecomment-2406524916)

image_2024-10-10_184048524

BONUS ROUND: I modified my own dono sprite. It works. It is added to the MultiSec wardrobes. It has identical stats to baseline Sec armors.

EDIT:
The original collared vest:
image
The new collared vest:
image

## Why It's Good For The Game

It adds diversity to the Sec weapons pool. To prevent abuse, I made it pricey to order from Cargo. It also does not show up on the Armory menu (I think) of Sec's Cargo orders - meaning they have to GO to Cargo to order it. The fire-rate can also be adjusted to make it work better for gameplay reasons.

## Proof Of Testing

image
image

## Changelog
:cl: Bangle
add: Added new mechanics or gameplay changes - added Shaytan SMG conversion kit to Cargo. Added the BNGL Collared Vest to MultiSec - it has identical stats and I don't wanna lock it behind a donowall.
add: Added more things - added Shaytan SMG conversion kit
image: added/modified/removed some icons or images - changed a bunch of the sprites, including my own Collared Vest
spellcheck: fixed a few typos - changed descriptions and renamed my Collared Vest. I think it's the BNGL Collared Vest now.
code: changed some code - see above.
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
How does the fire rate compare to just spam-clicking the SMG its made from? What's the DPS?

Price shouldn't be a balance factor if the gun is overpowered for sure (800 really isn't that much either)

**Comment by Offwrldr** [comment]
> How does the fire rate compare to just spam-clicking the SMG its made from? What's the DPS?
> 
> Price shouldn't be a balance factor if the gun is overpowered for sure (800 really isn't that much either)

The Sindano has a fire-delay of 0.2 seconds, whereas the Shaytan fires at a fire-delay of 2 (_which I believe is tick-related? There's no indicator as far as what that 2 represents_). The Sindano fires in bursts of 3, making it devastating in close-range combat, and the Shaytan fires one round per click. The Shaytan has a spread of 4 while the Sindano has a spread of 7.5 - making the Shaytan more accurate.

As far as damage, I will run a test to determine how long it takes an unarmored opponent to fall from both the Sindano and Shaytan, then post the results here.

Mind you - **this is intended as an upgrade to the Sindano.** Putting obstructions in the way of having it right off the bat is what I'm attempting to do with the pricing.

**Comment by YakumoChen** [comment]
> this is intended as an upgrade to the Sindano.

Gun balance, especially ballistic balance, is a pretty contentious issue, which is why I'd be skeptical of a PR like this in the first place. There's nothing wrong with making this a side-grade in some way instead.

**Comment by Offwrldr** [comment]
> > this is intended as an upgrade to the Sindano.
> 
> Gun balance, especially ballistic balance, is a pretty contentious issue, which is why I'd be skeptical of a PR like this in the first place. There's nothing wrong with making this a side-grade in some way instead.

That can be done. Raise the fire-delay on the Shaytan to balance the accuracy. Current performance is below:

https://github.com/user-attachments/assets/324f3144-02fe-4202-8277-484af2f3543a

No idea if this will embed...

**Comment by Offwrldr** [comment]
I did take a look at the price tag. Currently, seen in the screenshot of the Import Screen, the price is PAYCHECK_COMMAND * 8? Something like that. For reference, the Marksman Elite is the same price. I raised the price somewhat, so now it would be 1000cr to purchase. Which is a lot. Meaning, most players would need to rely upon the budget to purchase these until further into the round, at which point, antags are already making a mess of things.

**Comment by projectkepler-ru** [comment]
Hi, I am the current headmaintainer of skyrat and the original PR author for the gun
we had an idea to make it rapid firing in the same way the rom carbine currently is
However, due to time constraint and my focus being shifted toward the upstream merge of TG with @Majkl-J 
This did not get completed

This actual gun itself may get removed from skyrat or subject to changes in the future
Thank you for improving my awful idea nonetheless

**Comment by Offwrldr** [comment]
> Hi, I am the current headmaintainer of skyrat and the original PR author for the gun we had an idea to make it rapid firing in the same way the rom carbine currently is However, due to time constraint and my focus being shifted toward the upstream merge of TG with @Majkl-J This did not get completed
> 
> This actual gun itself may get removed from skyrat or subject to changes in the future Thank you for improving my awful idea nonetheless

It was a good idea - and one that will hopefully be implemented.

**Comment by projectkepler-ru** [comment]
Your stuff looks fine! and in all honesty I like the idea of having some stuff ya get from cargo
I'll look more into this sometime
Hit me up if you had anymore ideas on discord

**Comment by Offwrldr** [comment]
Demonstration of the new collared vest:



Unfortunately, I am an idiot and merged a bunch of prior PRs into this one. It should be mergeable without issues, as it's the same files as in the other PRs. I've gone ahead and nuked my directory to prevent this from happening again.

@projectkepler-ru will do!

**Comment by Offwrldr** [comment]
I'm just closing this PR because this is a nightmare of commits on top of commits and file conflicts. I'll make a new PR when I rebase and link this one in there.

**Pull request closed without merging**
