### PR TITLE
Removes Code Delta from Malf AI because I played a round of Malf AI once.

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

A remake of #936. It turns out that I've been cooking the whole time and Malf AI is still bad.

Malfunctioning AIs can no longer purchase the "Nuke Station" module.

### What Currently Happens

- AI starts acting up and does the mandatory minimum amount of roleplay to do bad shit.
- Malf AI mostly silent for the round as they gain enough CPU to do powers. Basically greenshift for 1 hour 30 mins.
- Malf makes unreasonable demands from the crew, either demanding that they do some difficult or absurd task.
- Crew refuse because that's weird.
- Malf starts using malf powers.
- One person freaks the fuck out and screams malf.
- People start cutting cameras.
- Malf gets upset and goes code delta over the most minor shit because they wanted an excuse to blow up the station.

(PICK ONE)

- Malf gets steamrolled as everyone rushes the core, and the shuttle gets called because medbay/engineering/whatever are completely uninhabitable and everyone wants to go home.

OR

- Malf had their cyborgs make a fortress of doom:tm: and is basically unstoppable because no one wants to thermtie through 50 layers of rwalls.

### What Was Promised

Maintainers said they were going to make Malf Doomsday more regulated, such as asking admin permission first, but these regulations never happened.

Several features that promised to fix code delta malf AI being bad were added but they never actually did anything to solve malf.

Admins promised to punish bad malf players but that doesn't stop new malf players from doing bad stuff but that wasn't a preventive measure and people still go code delta over nothing.

## Proof Of Testing

If it compiles, it works.

## Changelog

:cl: BurgerBB
del: Malfunctioning AIs can no longer purchase the "Nuke Station" module.
/:cl:

### CODE REVIEW

**Comment by ReturnToZender** [comment]
Burger was always cooking with the malf AI change and he still is today

**Comment by AllCorruptingWyrm** [comment]
Yeah this was a blunder, I dont think it shouldn't have been undone.

**Review by projectkepler-ru — APPROVED** [review]
Im  on the fence about this but I also dont really know, its one of the few AI that has the power to **actually end the round**  but it's objective are mostly to just kill people, so, w/e

**Comment by pixelkitty286** [comment]
Just remove the round ending part of it blowing up APCs would be interesting as it don't kill every one.

**Comment by aKromatopzia** [comment]
Unfortunately necessary if nobody can think of some-way better to be interesting than nuke

**Review by Majkl-J — APPROVED** [review]
Yea it's not suited for our server. Beside there's more fun ways to overwhelm the station than just this. If someone comes up with any cool ideas on how to make it at least interesting we can readd it later

**Pull request merged**
