### PR TITLE
[BOUNTY] Adds Kinetic Gauntlets

### PR DESCRIPTION
**Pull request by NullDagaf**
## About The Pull Request

Adds a new ~~fauna fighting~~ mining tool, the Kinetic Gauntlets. Purchasable for only 1250 mining points, this weapon offers an unique glass-cannon approach to fighting hostile fauna through literally uppercutting the beasts to death.

https://github.com/Bubberstation/Bubberstation/assets/55005783/f5fa6f15-f88c-4be2-85db-e884eb01f546

The short of it is: 
- The gauntlets take 1.5 seconds to deploy/retract, during which a hefty slowdown is applied
- The fists track attack cooldown separately, and are switched between on attack
- Mark detonation occurs when you punch a thing twice in rapid succession
- When a mark detonation occurs, both you and the target are pushed away from each other

Adding a tail spike does what you'd expect.

https://github.com/Bubberstation/Bubberstation/assets/55005783/e5a31507-0421-4382-8f0f-9db9c3a8db85

For those that only care about numbers, it's
- 15 damage per fist (same as a survival knife)
- 50 damage on mark detonation, 30 on backstab (same as crusher)
- 0.8 second delay between individual fist hits (same as everything)
- 1.5 seconds to deploy/retract the gloves

Also refactors the kinetic crusher and fixes bubblegum's trophy not giving you extra damage.

## Why It's Good For The Game

More variety, more things to spend mining points on, more gooder code, more swag.

## Proof Of Testing

[Screenshots are lame, here's a video of me fighting hierophant.](https://www.youtube.com/watch?v=Q4n3A4hLASs)

## Changelog

:cl:
add: adds kinetic gauntlets
fix: demon claws now correctly increase the force of whatever they're attached to
/:cl:

### CODE REVIEW

**Comment by NullDagaf** [comment]
Please pass checks it's 5 AM

**Comment by NullDagaf** [comment]
FUCK
firefox_9mX4u9OmNB

Okay whatever i'll fix this tomorrow

**Comment by Majkl-J** [comment]
> FUCK firefox_9mX4u9OmNB
> 
> Okay whatever i'll fix this tomorrow

Kinekick greaves when

**Comment by Superhats** [comment]
This PR broke crusher trophies. Now trying to detach a trophy causes it to permanently be impossible to pick up, and has it just snap to the crusher's location on click.

**Comment by NullDagaf** [comment]
> This PR broke crusher trophies. Now trying to detach a trophy causes it to permanently be impossible to pick up, and has it just snap to the crusher's location on click.

Ack. Thought I fixed that.

**Comment by NullDagaf** [comment]
I'll test if that fix works in a bit. IRL stuff.

**Comment by NullDagaf** [comment]
That should do it.

**Comment by Majkl-J** [comment]
Unrelated but I do have a working debugger for release 515 if you want that contact me on the discord. Testmerging again

**Review by Majkl-J — CHANGES_REQUESTED** [review]
You need to fix the unintended segfault loop when qdelling

**Comment by Nicolai904** [comment]
this pr breaks crusher and makes them able to be fired with one hand + ignore the cooldown of shooting and hitting as well making crusher drop if you try to use it with one hand on empty tile which should not do anything or if you try to attach trophies with one hand which i noticed from playing while this was tmed

**Comment by NullDagaf** [comment]
> this pr breaks crusher and makes them able to be fired with one hand

Fixed.
> \+ ignore the cooldown of shooting and hitting 

Felt clunky to have the shooting cooldown affect the hitting one, so removed it.
> as well making crusher drop if you try to use it with one hand on empty tile which should not do anything 

Fixed.
> or if you try to attach trophies with one hand which i noticed from playing while this was tmed

Fixed.

As a bonus, you can now hit objects (not mobs) when unwielded, for 0 damage.

**Comment by Nicolai904** [comment]
you could hit objects even before and still do damage one handed to objects  and its fine to change the cooldown of shooting and hitting  just please do say it in the pr what you actually change

**Comment by NullDagaf** [comment]
Done with this server.

**Pull request closed without merging**
