### PR TITLE
Head Convert Device for HeadRevs

### PR DESCRIPTION
**Pull request by Erol509**
## About The Pull Request

Adds a device for headrevs to remove mindshields and to convert command staff.

-To remove a mindshield, it takes 30 seconds;
-To convert a Head of Staff, it takes 60 seconds.

Tested with late-join HeadRev antag:

-HeadRev death causes Station victory;
-HeadRev converting Head causes Revolution victory;
-Head death causes Revolution victory;

## Why It's Good For The Game

Alternative way for headrevs to win by converting head of staff by removing COMMAND status from them, basically un-commanding them and removing from list of targets.

## Proof Of Testing

Doesnt crash, yet to be tested ingame. Just picked it up. 

## Changelog
:cl: larentoun
add: Head Convert Device for HeadRevs, which allows to remove mindshields and to convert heads of staff
/:cl:

### CODE REVIEW

**Comment by Wolf-751** [comment]
mindshield shouldn't be removable expect for surgery its literally designed to stop quick secuirty conversions.If you want it removable make it like the conversion rack for bloodsuckers where you get to choose to convert or not.

**Comment by Erol509** [comment]
> mindshield shouldn't be removable expect for surgery its literally designed to stop quick secuirty conversions.If you want it removable make it like the conversion rack for bloodsuckers where you get to choose to convert or not.

With current surgery levels, you can remove mindshield in like 20 seconds if you know the surgery and you are quick enough on random table or floor.

**Comment by Arturlang** [comment]
This makes headrevs way more easily detectable just by searching.

**Comment by Erol509** [comment]
> This makes headrevs way more easily detectable just by searching, using a mindshield requires you to suspect revs, a flash can be excused since you can obtain one in-round, but this is a clearly antag item on a antag that's designed to be difficult to detect without a mindshield

This PR might be obsolete, after Swift finishes their RR optin. Because every command member will have it forced to YES. So, it wont matter if you fry their brain and remove them from the round.

**Comment by Swiftfeather** [comment]
Waiting on help from majik, but here's the baseline pr upstream.

https://github.com/Skyrat-SS13/Skyrat-tg/pull/27473

**Comment by Cyprex** [comment]
Removing mindshields is a no from me, there are already options for this in-game(Surgery). Making command convertible is an option, but I'm thinking it needs to be **very** apparent to anyone that this has happened- otherwise this is too much of a buff to revs.

**Comment by Redrover1760** [comment]
> Removing mindshields is a no from me, there are already options for this in-game(Surgery). Making command convertible is an option, but I'm thinking it needs to be **very** apparent to anyone that this has happened- otherwise this is too much of a buff to revs.
> 
> Overall I think it's good to have rev be doable in a less bloody way.

Maybe make any converted heads of staff have a flashing red R on any sechuds would work.

**Comment by R3dtail** [comment]
> 
> This PR might be obsolete, after Swift finishes their RR optin. Because every command member will have it forced to YES. So, it wont matter if you fry their brain and remove them from the round.

Making  command players forced to opt in to yes just sounds like a recipe for disaster.  Why should people actively trying to RP be forced to  accept that they'll be RR'd for playing a role that makes sense for their character if they're putting forth the effort to RP.     That basically just cements that you're expecting people to have to be gamers to keep up with how loud  antags can be and that's counterintuitive to a place designed to be a roleplaying server.

**Comment by Swiftfeather** [comment]
> > This PR might be obsolete, after Swift finishes their RR optin. Because every command member will have it forced to YES. So, it wont matter if you fry their brain and remove them from the round.
> 
> Making command players forced to opt in to yes just sounds like a recipe for disaster. Why should people actively trying to RP be forced to accept that they'll be RR'd for playing a role that makes sense for their character if they're putting forth the effort to RP. That basically just cements that you're expecting people to have to be gamers to keep up with how loud antags can be and that's counterintuitive to a place designed to be a roleplaying server.

then comment on the PR that is making that change and not this completely unrelated one.

Closing because this is stale and I agree with cyprex

**Pull request closed without merging**
