### PR TITLE
Hugboxes Scrubber Event by giving the dangerous and safe variants a whitelist.

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Hugboxes Scrubber Event by giving the dangerous and safe variants a whitelist.

## Current Safe Chems
`
	/datum/reagent/consumable/salt,
	/datum/reagent/consumable/flour,
	/datum/reagent/blood,
	/datum/reagent/water,
	subtypesof(/datum/reagent/lube),
	/datum/reagent/carbon,
	/datum/reagent/space_cleaner,
	subtypesof(/datum/reagent/carpet),
	/datum/reagent/drying_agent,
	subtypesof(/datum/reagent/glitter),
	/datum/reagent/firefighting_foam,
	/datum/reagent/cellulose,
	/datum/reagent/medicine/dermagen,
	/datum/reagent/medicine/regen_jelly,
	/datum/reagent/baldium,
	/datum/reagent/concentrated_barbers_aid,
	/datum/reagent/barbers_aid,
	/datum/reagent/hair_dye,
	/datum/reagent/water/salt,
	/datum/reagent/medicine/mine_salve,
	/datum/reagent/consumable/tinlux,
	/datum/reagent/consumable/tearjuice,
	/datum/reagent/consumable/condensedcapsaicin,
`

## Current Dangerous Chems

`
	/datum/reagent/consumable/frostoil,
	/datum/reagent/hydrogen_peroxide,
	/datum/reagent/water/holywater,
	/datum/reagent/uranium,
	/datum/reagent/fuel,
	/datum/reagent/ants,
	/datum/reagent/thermite,
	/datum/reagent/clf3,
	subtypesof(/datum/reagent/toxin/acid),
	/datum/reagent/medicine/rezadone,
	/datum/reagent/toxin/plantbgone,
	/datum/reagent/napalm,
	/datum/reagent/medicine/polypyr,
	/datum/reagent/medicine/strange_reagent,
	/datum/reagent/consumable/liquidelectricity,
	/datum/reagent/medicine/c2/synthflesh,
	/datum/reagent/medicine/c2/hercuri,
	/datum/reagent/flightpotion,
`

## Why It's Good For The Game

Picking a completely random reagent for dangerous scrubbers is kind of bad because there a lot of a crazy/bad/round removing/whatever reagents out there, and that could exist in the future.

That's why a whitelist for safe and dangerous reagents was introduced. Reagents were chosen based on whether or not they had a mob touch proc to them, or a turf touch proc to them.

## Proof Of Testing

image

## Changelog

:cl: BurgerBB
balance: Hugboxes Scrubber Event by giving the dangerous and safe variants a whitelist.
/:cl:

### CODE REVIEW

**Comment by nevimer** [comment]
The code already does this, I believe. Anything weird is admin selected. This is likely to affect just the admin selected random button?

**Comment by BurgerLUA** [comment]
> The code already does this, I believe. Anything weird is admin selected. This is likely to affect just the admin selected random button?

Depending on the severity of the event selected, the event has a chance to select "dangerous" reagents, which is considered just a random reagent in the code (that is allowed to be random).

**Comment by Majkl-J** [comment]
As far as I'm aware the only scrubber event type that can run currently is the most basic and weak one

**Comment by Swiftfeather** [comment]
I like the one that makes the purple hands try to get you

**Comment by nevimer** [comment]
> > As far as I'm aware the only scrubber event type that can run currently is the most basic and weak one
> 
> With 0 percent dangerous. Pretty sure an admin forced a dangerous one yesterday during the Biodome round leading to this.
> 
> Also @BurgerLUA this PR ignores and reverts the changes made to the reagents list back in #1137
> 
> Your PR description of the current safer chems is wrong, did you actually look at the list you're deleting?
> 
> Your new safer chems list should just be the modular_zubbers one with perhaps eigenstate and such pulled out.

yeah, that was multiver.

**Comment by lessthnthree** [comment]
> > > As far as I'm aware the only scrubber event type that can run currently is the most basic and weak one
> > 
> > 
> > With 0 percent dangerous. Pretty sure an admin forced a dangerous one yesterday during the Biodome round leading to this.
> > Also @BurgerLUA this PR ignores and reverts the changes made to the reagents list back in #1137
> > Your PR description of the current safer chems is wrong, did you actually look at the list you're deleting?
> > Your new safer chems list should just be the modular_zubbers one with perhaps eigenstate and such pulled out.
> 
> yeah, that was multiver.

It's not just multiver.

Literally look at the two lists with your eyes. You are vastly changing what is in the safe chems list, removing a bunch and adding others including some that were previously removed in another PR.

image

**Comment by lessthnthree** [comment]
For example, space drugs, spray tan, pax, gravitum, only at a cursory glance.

**Comment by BurgerLUA** [comment]
I don't know where to start because you've left like 4 comments on this all of the place and most of them are not very good.

Yes, this reverts the changes that existed in modular. The lists were moved to global lists so I can use subtypesof() without error. I decided to start from scratch by focusing on mob_touch and turf_touch reagents because those are the most interesting ones.

The behavior of which reagent it picks was replaced so it only uses that list and not the old safe variable that was built into the event, meaning it won't pick whatever skyrat or /tg/ has for reagents and isntead use the custom system of global lists.

I tested this PR (See this PR of me literally testing it) and ran the most dangerous scrubber event multiple times. If you look at the list, the dangerous chems are not actually that bad, with some having an extremely minimal effect (slight toxins damage).

If the PR ends up making the event more dangerous, then I could easily change the variable saying which percentage of affected scrubbers spew dangerous reagents.

**Comment by BurgerLUA** [comment]
> I like the one that makes the purple hands try to get you

I can add and remove chems upon request.

**Comment by lessthnthree** [comment]
Yeah I'm not worried much about the dangerous chems, it's mainly the new chems list takes out some of the amusing ones.

Throw
/datum/reagent/consumable/char
/datum/reagent/gravitum
/datum/reagent/pax
/datum/reagent/spraytan
back in and it's fine.

**Comment by Swiftfeather** [comment]
Put he's grasp back in

**Comment by BurgerLUA** [comment]
Growth Serum, Gravitum, Laughter, Char, Colorful Reagent were added to safe chems.

Space Drugs, Shrooms, and Helgrasp was added to dangerous chems.

Glitter and Carpet were already existing in safe chems.

**Comment by lessthnthree** [comment]
Spray tan has voice lines like char, should be a safer chem.

**Comment by BurgerLUA** [comment]
> Spray tan has voice lines like char, should be a safer chem.

Spray tan coloring is irreversible. It cannot be removed with the SAD or showering.

**Comment by lessthnthree** [comment]
> > Spray tan has voice lines like char, should be a safer chem.
> 
> Spray tan coloring is irreversible. It cannot be removed with the SAD or showering.

Really? Damn. Oh well.

**Pull request closed without merging**
