### PR TITLE
Upstream oct 25 2023

### PR DESCRIPTION
**Pull request by nevimer**
for the CI run, and because waterpig likes seeing these even if they're speedmerged

### CODE REVIEW

**Comment by StrangeWeirdKitten** [comment]
There's some mapping stuff that's failing CI

**Review by BurgerLUA — APPROVED** [review]
code looks good 👍

**Comment by BurgerLUA** [comment]
> There's some mapping stuff that's failing CI

Maps are fine, it's just failing create and destroy errors with it spawning tram stuff, and there is a bad icon with the secmed helmet.

**Comment by StrangeWeirdKitten** [comment]
image

**Comment by StrangeWeirdKitten** [comment]
I removed the pleasure boat. I'm fixing the elevators on Biodome. Skyrat is removing security medic sprites so the icon for the helmet broke. The bitrunner landmarks are now actually an object which is much more sane. Some tram windows on emergancy_burgerstation got purged from the codebase, so I replaced them with aesthetically pleasing pod windows.

I have no fucking clue how TG maps the elevators. So biodome elevators are still broken, but hopefully this will resolve CI

**Comment by StrangeWeirdKitten** [comment]
I fixed the elevators. Hopefully, it will resolve all the CI

**Comment by bunny232** [comment]
is.. this the pr causing whatever the fuck is going on this round

**Pull request merged**
