### PR TITLE
Work in progress - new antag type Derelict AI

### PR DESCRIPTION
**Pull request by Odairu**
## About The Pull Request
Adds 2 new antag types, the derelict AI and its host.

Derelict AI:
A new modsuit is spawned in (sprites and whatnot to come later) at a random location on station with an AI inside (this is a fully functional AI, controls doors, can have shells, etc) Objectives are still TBD.
It will not be able to be removed from the suit, and the modsuit, once put on cannot be removed by the wearer which leads me to....

Derelict Host:
The crewmember who puts this modsuit on their back will find that they no longer can remove the suit, it 'binding' itself to the wearer. They will also gain the 'Derelict Host' antag datum in which they will share the objectives of the AI as well as an extra objective to keep the suit on their person.
The suit can only be removed via another player removing it from them, in which case they will also lose the antag datum, I'll probably give them some flavor message along the lines of "the last thing you remember clearly was putting on that mod control unit, everything since then is a haze" or something like that, or maybe not IDK yet.

Essentially the AI's whole goal is to get someone to wear the suit, then the pair together attempt to complete its objectives. Yes this means that seeing the suit is a free pass for antag since you can just /put it on/ and gain the datum.

Yes this is literally just venom

## Why It's Good For The Game
AI players are already fairly limited in their antag capabilities given they don't have many options that can roll antag on their job, this gives the people that enjoy AI another antag type to play (albeit a midround ghost role) and is a team antag that doesn't convert the entire station, which allows for the cooperation of two players to accomplish common goals (its blood brothers but better c:) 

## Proof Of Testing
This is still a draft

## Checklist of things that need done from when I made this PR

- [x] get the AI to properly spawn as the ai_assistant in the modsuit
- [x] allow borgs to be slaved to the new AI, but disallow law changes to said AI and slaving of newly created borgs automatically
- [ ] finish the two antag datums, add their objectives and whatnot
- [ ] add a check in the host antag datum for the modsuit, probably when they enter a body if that body doesn't have the mod, remove the datum
- [ ] give the AI the ability to teleport to a new random station turf if its not being worn (so it can escape from softlocks)
- [x] new mod module that swaps the minds of the AI and wearer (swaps back when deactivated)
- [ ]  give the Host some cool stuff so its actually worth picking it up (this will be up to maintainers how much fun is allowed)

## Changelog

:cl:
add: Adds 2 new antags - Derelict AI and Derelict Host
add: a new fused modsuit unique to this antag
/:cl:

### CODE REVIEW

**Comment by NargaInDisguise** [comment]
The ai player who wants to antag more making an ai antag type, clearly no bias here whatsoever 

I do like the idea though, I just hope people don't go out of their way to be like OH FREE ANTAG STATUS!!!

**Comment by destrucktoid** [comment]
Sounds to me a lot like it's going to be similar gameplay to cortical borer with silicon flavour

**Comment by Arturlang** [comment]
Maybe let the AI in the modsuit crawl around slowly without a holder and forcefully make someone enter, what if just nobody is willing to put it on their own?

**Comment by projectkepler-ru** [comment]
this just sound like a worse, significantly more conspicious borer

**Comment by Odairu** [comment]
> this just sound like a worse, significantly more conspicious borer

I dint really think the comparison is apt given the similarities start and end at "they share the same body"

**Comment by NargaInDisguise** [comment]
> Maybe let the AI in the modsuit crawl around slowly without a holder and forcefully make someone enter, what if just nobody is willing to put it on their own?

This is exactly what I hope this DOESN'T turn into, please don't create another forced-conversion antag. 

If you want to incentivize picking up the modsuit, let it be one of the special modsuits, elite/contractor+/asset protection/dsquad/etc etc. Let the AI choose which modsuit type on roundstart as well, maybe?

**Comment by Odairu** [comment]
> > Maybe let the AI in the modsuit crawl around slowly without a holder and forcefully make someone enter, what if just nobody is willing to put it on their own?
> 
> This is exactly what I hope this DOESN'T turn into, please don't create another forced-conversion antag.
> 
> If you want to incentivize picking up the modsuit, let it be one of the special modsuits, elite/contractor+/asset protection/dsquad/etc etc. Let the AI choose which modsuit type on roundstart as well, maybe?

I plan to make the modsuit generally desirable beyond "its free antag" yeah

**Comment by Odairu** [comment]
> Maybe let the AI in the modsuit crawl around slowly without a holder and forcefully make someone enter, what if just nobody is willing to put it on their own?

Modsuit AIs can already crawl around, but I might make it so the AI can choose to force you to wear the suit if you're holding it, rather than the AI just trying to sneak next to someone

**Comment by aKromatopzia** [comment]
I can't foresee anybody being trusted to not just meta the antag by dragging it to the cremator or such. So a dud event where it spawns blank modsuits or modsuits with regular pAIs enabled could help perhaps?

**Comment by Arturlang** [comment]
> Modsuit AIs can already crawl around, but I might make it so the AI can choose to force you to wear the suit if you're holding it, rather than the AI just trying to sneak next to someone

You're going to have to add a way for it to force someone to wear it in some method.

**Comment by Odairu** [comment]
> > Modsuit AIs can already crawl around, but I might make it so the AI can choose to force you to wear the suit if you're holding it, rather than the AI just trying to sneak next to someone
> 
> You're going to have to add a way for it to force someone to wear it in some method.

Yeah the more I work on this/think about it the more Im coming to this conclusion

**Comment by coffeecoffeecoffee** [comment]
I don't think the host should automatically necessarily share the AI's objectives automatically; I think it really should be up to roleplay, rather than "HEY FREE ANTAG STATUS IF YOU PUT THIS ON!!"

**Comment by Odairu** [comment]
> I don't think the host should automatically necessarily share the AI's objectives automatically; I think it really should be up to roleplay, rather than "HEY FREE ANTAG STATUS IF YOU PUT THIS ON!!"

its a team antag

**Comment by StrangeWeirdKitten** [comment]
This is stale. Feel free to reopen.

**Pull request closed without merging**
