### PR TITLE
Subverts Democracy and destroys the Meta-Icebox-Delta voting cycle by adding negative voting multipliers to recently played maps.

### PR DESCRIPTION
**Pull request by BurgerLUA**
Draft because controversial.

## About The Pull Request

Your vote for a map only counters 75% if the vote was a recently played map.
The last 4 rounds are considered recently played maps (not the last 4 maps, which means that if the cycle (from most recent to least recent) was  "icebox, delta, delta, meta, biodome", it will only count icebox, delta, meta.
If a map was voted for twice in the last 4 rounds, it cannot be chosen.

## Why It's Good For The Game

It sucks seeing server status and the map rotation is just:

ICEBOX, DELTA, META, ICEBOX, DELTA, META, TRAM, ICEBOX, DELTA, META, ICEBOX, DELTA, META, TRAM with the occasional biodome, limastation, or burgerstation map vote because it's lowpop and it seems only lowpop people like those maps.

## Changelog

:cl: BurgerBB
add: Your vote for a map only counters 75% if the vote was a recently played map (recently refers to the last 4 rounds).
add: If a map was voted for twice in the last 4 rounds, it cannot be chosen.
/:cl:

### CODE REVIEW

**Comment by BurgerLUA** [comment]
legitimately suprised that this pr doesn't have 10 downvotes

**Comment by YakumoChen** [comment]
What if the maps are being voted because people enjoy playing on them...?

**Comment by Tupinambis** [comment]
Tbh people play on the same few maps because a lot of the maps in rotation are kinda mid or bad. This just forces people to play on worse maps more often, which I don't think really benefits anyone.

**Comment by ChakatStormCloud** [comment]
Finally, not that meta and delta are bad, they're good, but for the love of god some variety pleeeease. I want to see tram more, with atleast the occasional lima/northstar/voidraptor.

**Pull request merged**
