### PR TITLE
[MIRROR] Echolocation quirk from Nova Sector

### PR DESCRIPTION
**Pull request by Superhats**
## About The Pull Request
Ports the echolocation quirk from Nova. See the original PR https://github.com/NovaSector/NovaSector/pull/525

## Changelog

:cl:VrazzleDazzle
add: Added the echolocation quirk from Nova Sector
/:cl:

### CODE REVIEW

**Comment by Swiftfeather** [comment]
Obligatory "will upstream take this?"

**Review by Majkl-J — COMMENTED** [review]
Might be worth it taking it to upstream

Also shush Swift

**Comment by Superhats** [comment]
I really don't want to be dealing with Skyrat's upstream so I'm gonna be closing this.

**Comment by nevimer** [comment]
this doesn't actually need to go upstream

**Comment by Swiftfeather** [comment]
If you get back to this feel free to re-open when it's ready. I'd still recommend trying upstream too.

**Pull request closed without merging**
