### PR TITLE
Hugboxes Shocked Grilles (Again)

### PR DESCRIPTION
**Pull request by BurgerLUA**
A reopen of #1626, with extra code for allowing ragecages.

## About The Pull Request

Grilles connected to a powernet (aka shocked grilles) on map load are automatically destroyed if they reach the following conditions:
- The grille does not have a window attached
- The grille is on the station level.
- The grille is not next to any other grilles (cardinal directions only).

This means that rage cages, space ruins, and secure areas are not affected.

## Why It's Good For The Game

Some current maps (Wawastation, Effigy Sigma, Limastation) have an abudnency of shocked grilles in maintenance. Personally, I think this is a bad design choice as many of these shocked grille locations are at the end of long hallways, making it incredibly likely for someone to lag into a shocked grille.

Even though I made a PR that nerfed electrocution damage to not instantly kill you while full health, shocked grilles are still pretty deadly especially since you can run into more than one (or the same one) if you're lagging.

## Proof Of Testing

Untested.

## Changelog

:cl: BurgerBB
del: Removes most shocked grilles in maint. Rage cages are unaffected.
/:cl:

### CODE REVIEW

**Comment by StrangeWeirdKitten** [comment]
I think it's just bad map design overall and I would rather just see them removed since they're specifically on our maps alone. This is still not really needed even with the work arounds provided.

**Comment by StrangeWeirdKitten** [comment]
Oh yeah that's basically what this does. nvm then

**Comment by StrangeWeirdKitten** [comment]
I'll discuss this, but it's still far better to just remove them on all our maps since those are the primary choices. This could be test merged during the Effigy event though.

**Comment by BurgerLUA** [comment]
> I'll discuss this, but it's still far better to just remove them on all our maps since those are the primary issues. This could be test merged during the Effigy event though. Also wawa station just sucks and I'm unsure how much future it has in our rotation.

I'd be happy with removing Wawastation from rotation.

**Comment by StrangeWeirdKitten** [comment]
> > I'll discuss this, but it's still far better to just remove them on all our maps since those are the primary issues. This could be test merged during the Effigy event though. Also wawa station just sucks and I'm unsure how much future it has in our rotation.
> 
> I'd be happy with removing Wawastation from rotation.

later i'll probally make a testing CI to see how many shocked grills we have. But my primary issue is when they're just scattered around main maint hallways. Idrc if they're in a secluded room.

**Comment by StrangeWeirdKitten** [comment]
> > I'll discuss this, but it's still far better to just remove them on all our maps since those are the primary issues. This could be test merged during the Effigy event though. Also wawa station just sucks and I'm unsure how much future it has in our rotation.
> 
> I'd be happy with removing Wawastation from rotation.

yeah this map has a lot of issues. Consider it done.

**Comment by BurgerLUA** [comment]
> > > I'll discuss this, but it's still far better to just remove them on all our maps since those are the primary issues. This could be test merged during the Effigy event though. Also wawa station just sucks and I'm unsure how much future it has in our rotation.
> > 
> > 
> > I'd be happy with removing Wawastation from rotation.
> 
> yeah this map has a lot of issues. Consider it done.

:eyes:

**Comment by StrangeWeirdKitten** [comment]
My criteria for offending maint grills (which are really the only issue) is when they're scattered in main maint pathways. Feel free to remove them from Lima. The Effigy maps *might* have a couple, but tbqh we're only running them for a month and they're being shipped as is.

**Pull request closed without merging**
