### PR TITLE
Improves Harm Alarm cosmetic code and adds customization.

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Harm alarm is now improved by changing the sound played, the default message, and the ability to change the message.

https://github.com/Bubberstation/Bubberstation/assets/8602857/32430605-63cf-4c9e-97bb-8ec992dbd81f

## Why It's Good For The Game

"Human Harm" is outdated given that everyone is a white haired catgirl woman.

## Changelog

:cl: BurgerBB
add: Harm alarm is now improved by changing the sound played, the default message, and the ability to change the message.
/:cl:

### CODE REVIEW

**Comment by nevimer** [comment]
prove it, show it in here

**Comment by nevimer** [comment]
prove it, show it in here

**Comment by BurgerLUA** [comment]
> prove it, show it in here

It came to me in a dream (one sec).

**Comment by BurgerLUA** [comment]
> prove it, show it in here

OP updated with video

**Comment by GrayRachnid** [comment]
Really minor nitpick. The original harm alarm has a different message that clearly implies the alarm is broken or being overused. Can that be re-added to the emagged alarm as a prefix or a suffix? Yes I know it's very obvious when it's emagged by the fact that you're floored after it's used but I still think this is flavor that should be preserved.

**Comment by BurgerLUA** [comment]
> Really minor nitpick. The original harm alarm has a different message that clearly implies the alarm is broken or being overused. Can that be re-added to the emagged alarm as a prefix or a suffix? Yes I know it's very obvious when it's emagged by the fact that you're floored after it's used but I still think this is flavor that should be preserved.

The emagged one shows bigger text, which is red.

**Pull request merged**
