### PR TITLE
New Infinidorm Rooms: Ports Beach Condo From Nova, Adds Station Side

### PR DESCRIPTION
**Pull request by Kepteyn**
## About The Pull Request

This ports the Beach Condo made by ZergPower on Nova, and adds Station Side, a station-and-maints themed room, to the options for the ghost cafe dorm rooms.

https://github.com/NovaSector/NovaSector/pull/795 < original condo PR.

302818267-ee7fed05-7684-4540-9022-d611bc25aacf

st2

## Why It's Good For The Game

The beach condo ZergPower made is awesome, and it's a shame it's not available here. Well, this adds it and a brand new dorm room too! Simply provides more options for ghost cafe nerds to play out their scenes.

## Proof Of Testing

Tested locally. Old and new options are available and work.

st2

st2

st 1

## Changelog

:cl:
add: Added Beach Condo and Station Side to ghost-cafe infinidorm options.
/:cl:

### CODE REVIEW

**Review by Majkl-J — COMMENTED** [review]
Could you take this upstream?

**Comment by Kepteyn** [comment]
> Could you take this upstream?

Could you elaborate, please? Thank you.

**Comment by Majkl-J** [comment]
> > Could you take this upstream?
> 
> Could you elaborate, please? Thank you.

PRing this to skyrat, which would avoid you having to make edit comments and mean we get it anyhow

**Comment by Kepteyn** [comment]
> > > Could you take this upstream?
> > 
> > 
> > Could you elaborate, please? Thank you.
> 
> PRing this to skyrat, which would avoid you having to make edit comments and mean we get it anyhow

Ah, I see what you mean. Will do that.

**Pull request closed without merging**
