### PR TITLE
Minor donator item fixes

### PR DESCRIPTION
**Pull request by Scuhf-git**
## About The Pull Request

Fixes some minor problem with a dono item.

## Changelog

:cl:
fix: Winter Jacket sprite
fix: Syndicate Jacket name typo
/:cl:

### CODE REVIEW

**Comment by Scuhf-git** [comment]
oopsie poopsie

**Review by KathrinBailey — APPROVED** [review]

**Comment by KathrinBailey** [comment]
fix conflicts so I can merge it :(

**Comment by Scuhf-git** [comment]
amazing, outstanding, incredible work by me

**Comment by Scuhf-git** [comment]
i'm going to close this for a bit because i'm that stupid, but i'll get around to fixing it when I get enough time to.

**Comment by Scuhf-git** [comment]
@KathrinBailey :)
Hi, is it possible for this to just be fucking deleted from all of time and space because I fucked up while tired and not paying attention and pushed my horn sprites to this :)

**Pull request closed without merging**
