### PR TITLE
Ports F3-LINE borgs!

### PR DESCRIPTION
**Pull request by pixelkitty286**
## About The Pull Request

This PR ports F3-LINE borgs from Citadel RP.
https://github.com/Citadel-Station-13/Citadel-Station-13-RP/pull/4625

Cat borgs are a mostly finished sprite set from Citadel roleplay meaning they are missing sitting and belly up sprites.

## Why It's Good For The Game

Have you ever wanted to play a cat borg or be an annoying little meower of a robot well now you can meow all you want!

All seriousness we don't have any cat borgs and I think they would make a adorable addition to the server wile as a cyborg option. I'd love to see them bash your skulls in with their mggaowing mrrpness.

## Proof Of Testing

dreamseeker_qXQhtK6KmF

dreamseeker_CtX9co5fhG

dreamseeker_VGjlD3hI57

dreamseeker_Sb6aZmfZ6j

## Changelog

:cl:
add: F3-LINE
image: added felibot_all.dmi
code: modular robot_model.dm
/:cl:

### CODE REVIEW

**Comment by ReturnToZender** [comment]
They seem extremely smol. Thumbs-up

**Comment by theselfish** [comment]
They're the same size as roombas by the look of it, but I like em.
Though I'm biased.

**Review by Majkl-J — APPROVED** [review]
The size of the sprite WOULD be an issue if there weren't smaller borgs anyhow. Otherwise code looks solid + you took the time to show them off which shows that they do work

**Comment by zeroisthebiggay** [comment]
> The size of the sprite WOULD be an issue if there weren't smaller borgs anyhow. Otherwise code looks solid + you took the time to show them off which shows that they do work

i just wanna say that just because there `is` small borg sprites shouldn't excuse the fact that they're directly advantageous over others

roomborgs are a disaster to humanity and should be shot

**Comment by destrucktoid** [comment]
have to agree here, i don't think we should be adding another set of small sprite borgs. The downside of roomba borgs and the omni borg is that not many people actually like how those look and don't pick them on that basis. I can see lots of people choosing this model though because it actually looks good and with how small it is that likely will be a problem.

**Comment by Majkl-J** [comment]
The small size will be looked into if it turns out to be an issue. It is out of scope for this PR, but if these start a problem I will simply add a new borg trait that gives smol sprites negative armor or something to balance them out

**Comment by pixelkitty286** [comment]
> The small size will be looked into if it turns out to be an issue. It is out of scope for this PR, but if these start a problem I will simply add a new borg trait that gives smol sprites negative armor or something to balance them out

Please do so if this does become a issue I was thinking of doing some stuff in a future PR to small borgs.

**Comment by SonicGotNuked** [comment]
There’s already systems in place to add invisible sprite “hitboxes” (like cables) if there is an issue. There’s solutions to size concerns

**Pull request merged**
