### PR TITLE
Reworks Borers Slightly

### PR DESCRIPTION
**Pull request by Icarus-The-Sun**
## About The Pull Request
Redoes Borer paths, swapping what abilities are exclusive to a path, and adds a new ability, called torment, to diveworms and hivelords. Torment is essentially an upgraded internal fear. Adds the Invasive trait to high tier Diveworms and Hivelords, letting them bypass gear. In a working state, tested in game.
[https://discord.com/channels/1059199070016655462/1061433713088536706/1142182949568139304]

## Why It's Good For The Game
Borers often go purely symbiote when enabled, and a small rework to what each path can do, and isolating their main abilities/giving them new choices, can encourage variety in what a player chooses for a path.

## Changelog

:cl:
add: Reworked borer trees
add: Two reproductive abilities for non-Hivelords (Parasitic Egg Production for Diveworms, and Symbiotic Egg Production for Symbiotes)
add: Torment ability for Diveworms/Hivelords
add: Invasive Trait for Non-Symbiotes
add: Adds a new Lidopaine variant for Borers.
add: Adds that Lidopaine variant to Diveworms' learnable chems. For the extra "fuck you".
/:cl:

### CODE REVIEW

**Comment by nevimer** [comment]
Video you testing this

**Comment by Majkl-J** [comment]
Well I am not buying borer eggs as tot if the meth deals brain damage, it's like the only reason to even make such a risky investment. Maybe giving it a OD would be better?

**Comment by Icarus-The-Sun** [comment]
> Well I am not buying borer eggs as tot if the meth deals brain damage, it's like the only reason to even make such a risky investment. Maybe giving it a OD would be better?
That's a fair point, though ANY borer can easily heal the damage through mannitol. I see your point about an overdose though! Borers would naturally spawn again with this PR, so traitors wouldn't be the only source, but it'd be good to have them be a somewhat decent tool still.

**Comment by nevimer** [comment]
> Well I am not buying borer eggs as tot if the meth deals brain damage, it's like the only reason to even make such a risky investment. Maybe giving it a OD would be better?

it already did this

**Comment by Icarus-The-Sun** [comment]
> > Well I am not buying borer eggs as tot if the meth deals brain damage, it's like the only reason to even make such a risky investment. Maybe giving it a OD would be better?
> 
> it already did this

Ah. Because it was a type of meth. Right. Fuck.

**Comment by StrangeWeirdKitten** [comment]
Closing because borers are currently broken and we need to fix them with dynamic before I start reconsidering any reworks.

**Pull request closed without merging**
