### PR TITLE
Adding Jackal tail

### PR DESCRIPTION
**Pull request by Kingsley-95**
## About The Pull Request

Taking a tail from another server and porting it over here

Adding new tail sprites

## Why It's Good For The Game
More customization, more fun

## Proof Of Testing

image
image
image
image
image

<details>
<summary>Screenshots/Videos</summary>
Set above for screenshots of the new customization option. Was mainly using this to start learning the code base and see if I could get my development environment set up. Things are looking good on that end
</details>

## Changelog

:cl:
add: Black-Backed Jackal tail
/:cl:

### CODE REVIEW

**Comment by ReturnToZender** [comment]
This is awesome, why does your test character have no legs?

**Comment by Kingsley-95** [comment]
> This is awesome, why does your test character have no legs?

Figured it'd show the sprite more clearly!

**Review by lessthnthree — APPROVED** [review]

**Comment by lessthnthree** [comment]
@Kingsley-95 Heyo, please run tools\dmi\resolve icon conflicts.bat!

**Comment by Kingsley-95** [comment]
> @Kingsley-95 Heyo, please update to master and run tools\dmi\resolve icon conflicts.bat!

@lessthnthree Conflicts resolved. Handy tool there!

**Pull request merged**
