### PR TITLE
[Draft] [MDB IGNORE] Adds back Tesla and Particle Accelerator for old engineering enjoyers

### PR DESCRIPTION
**Pull request by Erol509**
## About The Pull Request

Here are my plans:
Tesla makes crazy ammount of power per zap, so it will be late project that costs 20k cr or even more to buy required parts. I dont plan it as a round start engine, but a extra project for old engineering enjoyers...Just like me

Rad collects could also by something that might be added with this PR, not obtainable but in the future, you can also power station from lord singulo. 

## Why It's Good For The Game

image
image

## Changelog

:cl:
add: Tesla, Particle Accelerator

### CODE REVIEW

**Comment by projectkepler-ru** [comment]
Put your PR on draft

**Comment by Erol509** [comment]
Thanks for review, honestly Im not sure if its a good PR either. Tesla is easy to contain, makes crazy ammounts of power, and there doesnt seem to be a way of nerfing it without reworking flags and tesla code. And I dont have skill in coding to  do so. Tesla might be just unneded dream of mine, so I might consider closing it.

**Comment by Erol509** [comment]
Yeah, this PR doesnt make much sense. I dont want to clog the codebase with low quality code, which I wont maintain later on, because I wont know how. This code is partialy taken from yog and old tgstation files. Like I said above, tesla doesnt make much sense in 2023. All what remains are good old days, everything what was nice had to end one day. I was too hyped about adding it. Thank you tf for reviews and sorry for your wasted time.

**Comment by Erol509** [comment]
Will fully reopen when I will fix and implement everything

**Pull request closed without merging**
