### PR TITLE
Makes the Prybar Bulky (and adds it back to the RCF)

### PR DESCRIPTION
**Pull request by StrangeWeirdKitten**
Reverts Bubberstation/Bubberstation#1378

## About this PR

Prybar changes. Simply adds bulk to them.

## Why it's good for the game

I think an overall thing that people don't consider in regards to item balance is that bulk massively changes the utility of something. I'm not against it being able to pry open doors, but it can be the size of the robotics mech crowbar in game.

## Proof of Testing

It has girth and compiled and it was too big for my bag.

## Changelog

🆑
balance: Prybars are added back to the colony fabricator, but they are bulky items now.
/:cl:

### CODE REVIEW

**Comment by NargaInDisguise** [comment]
While I think making it bulky is a good balance change, the RCF continues to be an incredibly strong printer that cargo buys immediately on round start. I just don't think it should be able to print breaching tools period.

**Comment by SonicGotNuked** [comment]
> While I think making it bulky is a good balance change, the RCF continues to be an incredibly strong printer that cargo buys immediately on round start. I just don't think it should be able to print breaching tools period.

I agree. I’m debating on if the prying needs to be removed completely or just given from the cargo shuttle at a 300-400 price tag

**Comment by NargaInDisguise** [comment]
> I agree. I’m debating on if the prying needs to be removed completely or just given from the cargo shuttle at a 300-400 price tag

Make it only a restricted import that requires the cargo-side to order it, that way it can atleast be cancelled or you can figure out who bought it from the manifests. Theres also the potential of just, not letting cargo print/buy breaching tools for no reason, but its a can of worms no matter what way it goes.

**Comment by SonicGotNuked** [comment]
> > I agree. I’m debating on if the prying needs to be removed completely or just given from the cargo shuttle at a 300-400 price tag
> 
> Make it only a restricted import that requires the cargo-side to order it, that way it can atleast be cancelled or you can figure out who bought it from the manifests. Theres also the potential of just, not letting cargo print/buy breaching tools for no reason, but its a can of worms no matter what way it goes.

It’s already a restricted import at 100 cr. But I’m not entirely comfortable of having easily accessible round start breaching tools in cargo.

**Comment by Swiftfeather** [comment]
I'm still of the opinion it should be flat out removed from player acquisition.

**Comment by NargaInDisguise** [comment]
I also think completely removing it is an entirely valid option. If you need a breaching tool as a job that requires one, jaws of life still exist anyways.

**Comment by Superhats** [comment]
I'm also of the opinion that the RCF needs _less_ utility given to it. It's already a very, very popular purchase you see almost every round in places like cargo and the medbay.

**Comment by StrangeWeirdKitten** [comment]
I've had some more thought to this and I will be removing the door forcer functionality entirely.

**Comment by Superhats** [comment]
> I've had some more thought to this and I will be removing the door forcer functionality entirely.

I'm all for it, but what differentiates them from crowbars if that goes away? I don't think prybars do anything else special?

**Comment by Majkl-J** [comment]
Seeing the current meta stabilize, it seems as if this isn't really needed? The need to actually ask cargo to buy it seems to work, making people either actually seek it out, or simply not carry it on them due to it being an actual hassle to obtain. We can also just role restrict it to engies if it shows up as a major issue again.

**Pull request closed without merging**
