### PR TITLE
Interdyne update, RIP DS-2.

### PR DESCRIPTION
**Pull request by kaylexis**
## About The Pull Request

After the brutal annihilation of DS-2 i believe many of you are infuriated with its destruction!
Thus i bring to YOU: a better interdyne! woo!
If you complain about the whole server going to it, they wont. Limited to 8 sleepers, and 2 of them are prison ones.
send complaints to butters. I QUOTE HIM NOW: "oh my god it's beautiful it's sexy I love it"
## Changelog

:cl:
add: Mini brig and armory(keycard locked, hidden somewhere)
add: Mini perma(including prison slop! YUM!)
fix: Removal of the debug smes, replacing the entire eng area with a turbine.
add: Moving of the Master At Arms and Admiral things and sleepers from DS-2 to interdyne
/:cl:

### CODE REVIEW

**Comment by Cyprex** [comment]
The CL needs to specify that it's for DS-2(if it is)
Make sure the turbine actually works.

**Comment by kaylexis** [comment]
> The CL needs to specify that it's for DS-2(if it is) Make sure the turbine actually works.
Not for DS-2, and I'm like 99% sure the turbine works. I'll localhost test it later, but there is one issue in both maps with the deck officer windows having lava underneath them, which I'll be fixing soon.

**Comment by kaylexis** [comment]
zelp

**Comment by kaylexis** [comment]
OK AT THIS POINT, I UH. AM JUST GOING TO REMAKE IT, WHOLE NEW LAYOUT AND EVERYTHING. THESE ERORRS ARE A NIGHTMARE

**Comment by kaylexis** [comment]
all errors are dumb and stupid and shouldnt exist but do anyways because for some reason everything hates me and wants me to suffer god i hate this why did i ever decide to do this auuuuuuuuuuughhhhhhhhh

**Comment by Cyprex** [comment]
Some of these CI errors sure are weird, feel free to bug me about them!

**Review by KathrinBailey — CHANGES_REQUESTED** [review]
Sorry that this took so long but unfortunately, bigger isn't exactly what we were going for. The ruin is already colossal.
Try trimming down on some of the giant 3-wide hallways and removing the superfluous bedrooms that are used as spawn-points. Remove the art room, library, barber, medbay lobby and whatever hallways you can. You're probably gonna have to do a lot of redesigning here.
Also guh, why are you changing the .dme?

**Comment by kaylexis** [comment]
> Sorry that this took so long but unfortunately, bigger isn't exactly what we were going for. The ruin is already colossal. Try trimming down on some of the giant 3-wide hallways and removing the superfluous bedrooms that are used as spawn-points. Remove the art room, library, barber, medbay lobby and whatever hallways you can. You're probably gonna have to do a lot of redesigning here. Also guh, why are you changing the .dme?

the .dme was changed???? weird af

**Comment by kaylexis** [comment]
making an entirely new remake this is no longer supported

**Pull request closed without merging**
