### PR TITLE
RULE 1: Always keep the muzzle pointed in a safe direction

### PR DESCRIPTION
**Pull request by Swiftfeather**
## About The Pull Request

Removes gun safeties. BETTER FOLLOW RULE 1 OF GUN SAFETY BETTER NOW!

This is actually extremely noninvasive as far as uhhh uhhh uhhh modularity goes because it's just ONE file, all I had to do was disable the add component part of the proc but the proc is still defined so it doesn't error out on the guns that get the proc in other files.

## Why It's Good For The Game

I just find them really annoying.

Also the bigger thing, there's a very strong supermajority for removing it in the [suggestions](https://discord.com/channels/1059199070016655462/1071095123145924679/1212230353561849857) channel.

image

## Proof Of Testing

I loaded in, joined as captain, picked up all the guns in the armory and didn't see safeties on ANY of them.

## Changelog

:cl:Swiftfeather
del: Removed gun safeties.
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
Reminder gun safeties were added originally as an April fools joke

**Comment by Swiftfeather** [comment]
> Reminder gun safeties were added originally as an April fools joke

October 2020 really odd time to do april fools

**Comment by projectkepler-ru** [comment]
Does anyone here actually benefit from the safety function? I always just kept my active hand the one not holding the gun so I can always try to shield shove first

**Review by Majkl-J — CHANGES_REQUESTED** [review]
This is not a very good way to go about this
comment out the single line in code/modules/projectiles/gun.dm#L85

**Review by Majkl-J — APPROVED** [review]
May they be gone, I think nobody will dispute this

**Pull request merged**
