### PR TITLE
Add Marish and Shadekin Empathy

### PR DESCRIPTION
**Pull request by nevimer**
## About The Pull Request

Adds Marish and Shadekin Empathy

## Why It's Good For The Game

Species lore shadekins.

## Proof Of Testing

https://github.com/Bubberstation/Bubberstation/assets/77420409/ce047836-57e6-4dcb-a9a2-82cdb42ad7d0

## Changelog

:cl: nevimer, roachwitharoach
add: Added Marish and Shadekin Empathy as languages. 
icon: added two icons for shadekin languages
/:cl:

### CODE REVIEW

**Comment by SovietSpaghetti** [comment]
Didn't this get removed from xenohybrids because it was overpowered to have a wireless communication system that nobody could track, listen in on, or disable without being the species? This also makes shadekin just a flat upgrade to humans with no downside whatsoever, there was a reason they were whitelisted on Virgo and every other server they're on.

**Comment by nevimer** [comment]
> Didn't this get removed from xenohybrids because it was overpowered to have a wireless communication system that nobody could track, listen in on, or disable without being the species? This also makes shadekin just a flat upgrade to humans with no downside whatsoever, there was a reason they were whitelisted on Virgo and every other server they're on.

This lets you talk to other shadekins, not xenos. Big stretch of balance.

**Comment by destrucktoid** [comment]
> > Didn't this get removed from xenohybrids because it was overpowered to have a wireless communication system that nobody could track, listen in on, or disable without being the species? This also makes shadekin just a flat upgrade to humans with no downside whatsoever, there was a reason they were whitelisted on Virgo and every other server they're on.
> 
> This lets you talk to other shadekins, not xenos. Big stretch of balance.

Crew abductors have to go through a million downsides in order to get this and people still complain it's overpowered for the same reasons sovietspaghetti brought up. Meanwhile here they just get it because "It'll be funny" whilst also having no negative balance added to the species in order to justify getting it. Heck, they can still speak normal languages unlike abductors who can't speak anything else so it's even better than abductors.

Tell me, why is this justified balance wise again? I genuinely see no reason for them to get such a powerful mechanic.

**Comment by nevimer** [comment]
If you want species to have abilities that set them apart from humans, go ahead.

**Comment by destrucktoid** [comment]
> If you want species to have abilities that set them apart from humans, go ahead.

It's not about setting them apart from humans, it's about giving them something that is quite clearly overpowered. If i made a species that got a passive 30% damage resistance with no downsides and people then say "that's overpowered", me saying "it sets them apart from humans" doesn't make that change any less overpowered.

**Comment by Odairu** [comment]
> > If you want species to have abilities that set them apart from humans, go ahead.
> 
> It's not about setting them apart from humans, it's about giving them something that is quite clearly overpowered. If i made a species that got a passive 30% damage resistance with no downsides and people then say "that's overpowered", me saying "it sets them apart from humans" doesn't make that change any less overpowered.

They get a lower health pool on virgo, presumably to make up for this, which I wouldn't mind, but also I don't think at current its really a big deal.

**Comment by Odairu** [comment]
> Didn't this get removed from xenohybrids because it was overpowered to have a wireless communication system that nobody could track, listen in on, or disable without being the species? This also makes shadekin just a flat upgrade to humans with no downside whatsoever, there was a reason they were whitelisted on Virgo and every other server they're on.

they are whitelisted on virgo and chompers because they give them 90000 extra abilities on top of this, and they want people to play them lore accurately, the whitelists there have absolutely NOTHING to do with them having empathy as a language

**Review by projectkepler-ru — APPROVED** [review]
Not really a balance concern,  if people are being beaten because someone has better team coordination than them?
Social Skill Issue

**Comment by destrucktoid** [comment]
> > Didn't this get removed from xenohybrids because it was overpowered to have a wireless communication system that nobody could track, listen in on, or disable without being the species? This also makes shadekin just a flat upgrade to humans with no downside whatsoever, there was a reason they were whitelisted on Virgo and every other server they're on.
> 
> they are whitelisted on virgo and chompers because they give them 90000 extra abilities on top of this, and they want people to play them lore accurately, the whitelists there have absolutely NOTHING to do with them having empathy as a language

My point however isn't to do with shadekin on virgo or chomper's or any other server. It's to do with the fact that abductors have the exact same thing, with many downsides associated with it and i've still heard people complain about it. Meanwhile this just gives you something only abductors had before without any downsides. It's dictionary definition power creep.

**Comment by destrucktoid** [comment]
> Not really a balance concern, if people are being beaten because someone has better team coordination than them? Social Skill Issue

Better team coordination is one thing, coordination that you literally cannot stop short of cutting out their tongue is another. Normally if i want to stop someone screaming for help i can remove their headset. Lets say i'm a vampire and i want to thrall you, i mesmerize you and then remove your headset. Boom, you can't call for help. With shadekin and abductors however they can just call for help and i cannot stop them because there is literally no feasible way for me to do so.

**Review by StrangeWeirdKitten — APPROVED** [review]
Mar Mar Mar Mar Mar

**Comment by Swiftfeather** [comment]
image

**Comment by Redrover1760** [comment]
You could also make them not need to breath to survive

I dunno, things.

**Comment by projectkepler-ru** [comment]
> You could also make them not need to breath to survive
> 
> I dunno, things.

honestlly considering how fucking overpowered not needing internal can be

I dunno

**Comment by Superhats** [comment]
Shadekin in Deathmatch can hear and speak to people on the station with Empathy

**Comment by GoreDem** [comment]
Empathy doesn't work properly on other species.

**Comment by nevimer** [comment]
> Empathy doesn't work properly on other species.

That's intended. You need the organs to communicate properly.

**Pull request merged**
