### PR TITLE
The berserk ability cannot be used in pressurised areas 

### PR DESCRIPTION
**Pull request by xPokee**
## About The Pull Request
Does as the title says, makes it so that the berserk ability from the berserker armour and the dragonslayer armour cannot be used while in pressurised areas (such as on-station). This does NOT change any stats of the armours.
## Why It's Good For The Game
I'll admit I went a bit too far with the dragonslayer sword nerf, so this should hopefully be a better nerf for the dragonslayer and berserker armour set that removes the potential for absurd combos of this ability plus whatever weapon hitting absurdly fast on-station.
## Proof Of Testing
It compiled, ran, and was fully tested to work.
## Changelog
:cl:
balance: the berserk ability can no longer be used in pressurised areas, such as on-station
/:cl:

### CODE REVIEW

**Comment by projectkepler-ru** [comment]
okay this is actually a somewhat interesting way to balance it

**Review by StrangeWeirdKitten — APPROVED** [review]

**Comment by YakumoChen** [comment]
The armour values are still pretty problematic when upgraded (it's literally 75 brute and 50 in its other stats), I think the armour is still the main issue with it

**Comment by Majkl-J** [comment]
> The armour values are still pretty problematic when upgraded (it's literally 75 brute and 50 in its other stats), I think the armour is still the main issue with it

Please consult the drake armor
by all means it's just slightly better than it which is hopefully fine
```
/datum/armor/cloak_drake
	melee = 65
	bullet = 15
	laser = 40
	energy = 40
	bomb = 70
	bio = 60
	fire = 100
	acid = 100
	wound = 10
```

**Comment by YakumoChen** [comment]
> > The armour values are still pretty problematic when upgraded (it's literally 75 brute and 50 in its other stats), I think the armour is still the main issue with it
> 
> Please consult the drake armor by all means it's just slightly better than it which is hopefully fine
> 
> ```
> /datum/armor/cloak_drake
> 	melee = 65
> 	bullet = 15
> 	laser = 40
> 	energy = 40
> 	bomb = 70
> 	bio = 60
> 	fire = 100
> 	acid = 100
> 	wound = 10
> ```

Drake armour has next to no bullet resist

Marked one has all of that and _40_ bullet armour. It's literally near deathsquad in values.

**Comment by projectkepler-ru** [comment]
I fully support this since its a fairly clever work around that doesnt make the armour useless. Because if I spent time readying to kill the most durable megafauna it'd better drop something I can actually use tbh

**Comment by Razurath** [comment]
https://github.com/Bubberstation/Bubberstation/pull/2293

This is currently open pending merge is a pretty heavy nerf for the armor, can we pick one or the other on this?

**Pull request merged**
