### PR TITLE
[Ready] Makes it so that only melee weapons can dismember because I shot a guy with a pistol once and all their organs came out.

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Only melee weapons can disembowel/dismember via damage via wounds. This does not affect other sources of disembowel/dismember.

Codewise, it checks if there is a damage_source. Only melee weapons have a damage source. Ranged weapons don't have a damage_source. Funny fix for it, but it werks.

## Why It's Good For The Game

This is effectively prevents security from disemboweling since there are no lethal melee options available to them. This is good because it prevents the awkwardness of bringing an organless criminal's corpse to medical and medical giving you the Formaldehyde stare.

## Proof Of Testing

Tested.

## Changelog

:cl: BurgerBB
balance: Only melee weapons can disembowel/dismember via damage via wounds. This does not affect other sources of disembowel/dismember.
/:cl:

### CODE REVIEW

**Comment by Majkl-J** [comment]
I am opposing this for several reasons:
1. Sec do not have lethal melee roundstart. They can however purchase a sword or dagger with decent wound chance from cargo, and many do because the current meta is scarp with antistun chems, in which lethal melee is the only real counter. Sec will also probably not be lacking in this field forever as some plans for melee/bayonets are in the talks.
2. You can only disembowel someone in hard crit, so this doesn't just magically happen to someone alive (Unless the guy you shot happened to be in hardcrit). If sec keeps firing/slashing someone after they have fallen into crit, it's on them. The organs don't magically disappear and can be brought into medbay with the body. Putting them back in is one surgery and a few do_after calls for each organ

```
// from code/modules/surgery/bodyparts/parts.dm#L50-L53
/obj/item/bodypart/chest/can_dismember(obj/item/item)
	if(owner.stat < HARD_CRIT || !contents.len)
		return FALSE
	return ..()
```

Gonna let other maintainers have input

**Comment by projectkepler-ru** [comment]
> Gonna let other maintainers have input


idk most antag love to gut the fuck outta me when i sec

**Comment by Redrover1760** [comment]
Security shoots you until you are dead, without fail. This is why people get dismembered/de-organed/etc.

If security wants to stop dismembering/gutting people they should stop murdering crit individuals.

**Comment by Moostard** [comment]
Shooting peoples arms or legs off is sometimes a desired outcome depending on circumstances. This kinda makes it impossible and worrying that a medic will give you a stare is not something people care for most of the time.

**Comment by nevimer** [comment]
You know what, I'd probably like to see players being less aggressive with each other and going for overkill. It's mostly an issue with players going overboard, but I do think that bullets shouldn't gut people.

**Comment by projectkepler-ru** [comment]
> You know what, I'd probably like to see players being less aggressive with each other and going for overkill. It's mostly an issue with players going overboard, but I do think that bullets shouldn't gut people.

welll I think it doesn't help that it gets really frustrating at time chasing one guy across the whole yard

**Comment by Razurath** [comment]
> You know what, I'd probably like to see players being less aggressive with each other and going for overkill. It's mostly an issue with players going overboard, but I do think that bullets shouldn't gut people.

I mean, you hit someone with the right load, at the right range, you will put their shit on the floor. Maybe just make it so pistols and lasers don't disembowel, leave it for anything bigger that is kinetic?

**Comment by Redrover1760** [comment]
> I mean, you hit someone with the right load, at the right range, you will put their shit on the floor. Maybe just make it so pistols and lasers don't disembowel, leave it for anything bigger that is kinetic?

Lasers don't disembowel or delimb already. Only brute damage does.

**Comment by nikothedude** [comment]
dude this didnt have to be merged, you couldve just done cranial fissures, stg

**Pull request merged**
