### PR TITLE
[MODULAR] Ashwalker-friend

### PR DESCRIPTION
**Pull request by lurzefromgermany**
## About The Pull Request

Makes the Drake non-agro to Ashwalkers!

To thank the Ash drakes for their newfound peace, the ashwalkers have a new ritual to perform

They will need a cooked Goliath steak, A legion skull, Watcher sinew, and a regenerative core

Doing so will grant the ashwalker with 1 Drakebait ( Seasoned Goliath meat) 

they will now need to present the meat to an ashdrake, the ash drake will eat it and award them with x amount of Ashdrake hide (currently one, can be increased later)

You can also eat the meat itself I guess...

Oh, and now Ashwalkers are in their faction properly now.

https://github.com/Bubberstation/Bubberstation/assets/70082939/12d522b9-ec7a-4d9d-96de-d21ef8153251

## Why It's Good For The Game

 Enhances role-playing opportunities.
Promotes cooperation among players.
Adds diversity to gameplay.
Offers clear incentives for engagement.
Improves faction integration.
Allows for future expansion and adaptability.
Boosts storytelling and immersion in the game world.
 

## Changelog

:cl:
add: New Ashwalker ritual (Drake offering)
add: Seasoned Goliath Meat
add: Ashwalker faction tag
add: A way for Ashwalkers to get drake hide
balance: Ash Drake no longer angry at Ashwalkers
/:cl:

### CODE REVIEW

**Comment by lurzefromgermany** [comment]
Something not noted, Is that it also displays a message in chat when the drake eats the meat.

**Comment by Oscari-pog** [comment]
This is drake armor essentially for free.

**Comment by lurzefromgermany** [comment]
> This is drake armor essentially for free.

Not exactly, Its changing out killing 1 ash drake for a guaranteed set of ash drake armor, For the alternative for ashwalkers, to make Seasoned Goliath meat, when given to a ash drake, gives 1 hide. To make the meat 1. you need to be Ashwalker. 2 You need to kill multiple Legions to get a legion skull, and core, 2 kill goliaths for the meat, 3 kill multiple watchers for the sinew. Butchering is RNG the mobs aren't guaranteed to drop the items you want.  For ashdrake armor, you need ten hides, Meaning you have to repeat this process over.

**Comment by YakumoChen** [comment]
> You need to obtain Legion skulls

You need a crusher to obtain these, how are ashwalkers getting crushers?

**Comment by YakumoChen** [comment]
> Enhances role-playing opportunities.
Promotes cooperation among players.
Adds diversity to gameplay.
Offers clear incentives for engagement.
Improves faction integration.
Allows for future expansion and adaptability.
Boosts storytelling and immersion in the game world.

How does your PR accomplish any of these goals?

**Comment by lurzefromgermany** [comment]
> How does your PR accomplish any of these goals? This comes off as just a load of buzzwords to me.

Enhanced Role-Playing Opportunities: The pull request introduces a new ritual for Ashwalkers to perform, providing them with a role-playing activity centered around thanking the Ash Drakes. Players can choose to engage in this ritual and immerse themselves in the game's lore and storytelling.

Diverse Gameplay: The pull request adds specific crafting ingredients required for the ritual, such as a cooked Goliath steak, Legion skull, Watcher sinew, and a regenerative core. This diversity of items introduces new gameplay elements like hunting, gathering, and crafting, enriching the overall gaming experience.

Clear Incentives: Players are rewarded with Drakebait (Seasoned Goliath meat) and Ashdrake hide for completing the ritual. These rewards provide a clear incentive for players to participate in the new content, as they gain tangible benefits from their actions.

**Comment by lurzefromgermany** [comment]
> > You need to obtain Legion skulls
> 
> You need a crusher to obtain these, how are ashwalkers getting crushers?
False,
image

> Did you actually test collecting these items or did you just spawn them in on your video?
Yes I played ashwalker before making this PR, you should play too before commenting

> Since when did butchering lavaland mobs have an RNG component? They always drop the same things?
false once again 
image

I recommend playing Shaft-miner or Ashwalker.

> Functionally with this change, it requires killing only three watchers, three goliaths, and 5 legions (not counting the unobtainable skulls) for ash drake armor, which, to say the least, is not much.

The above statements prove this false as well.

**Comment by Majkl-J** [comment]
> Functionally with this change, it requires killing only three watchers, three goliaths, and 5 legions (not counting the unobtainable skulls) for ash drake armor, which, to say the least, is not much.

It's ashies, not your super-power omega-chad dual pka weilding miner who just killed bubblegum and still came for more

**Comment by YakumoChen** [comment]
> I recommend playing Shaft-miner or Ashwalker.

I have a thousand hours in shaft miner and I've personally never butchered a lavaland animal and not had all items under the butcher results spawn. The only way I could think of otherwise is using an abysmally shitty butchering tool or something, I'd have to look up the code

I don't see how farming animals on lavaland Contributes To The Roleplay Experience other than obtaining the drake armour for essentially free, which I guess you can roleplay giving to someone else. Or stopping miners from killing the drake, which ash walkers already do.

**Comment by lurzefromgermany** [comment]
> > I recommend playing Shaft-miner or Ashwalker.
> 
> I have a thousand hours in shaft miner and I've personally never butchered a lavaland animal and not had all items under the butcher results spawn. The only way I could think of otherwise is using an abysmally shitty butchering tool or something, I'd have to look up the code
> 
> I don't see how farming animals on lavaland Contributes To The Roleplay Experience other than obtaining the drake armour for essentially free, which I guess you can roleplay giving to someone else. Or stopping miners from killing the drake, which ash walkers already do.

What is this logic? Kill the drake, the armor is essentially for free.

**Comment by YakumoChen** [comment]
> What is this logic? Kill the drake, the armor is essentially for free.

I think you forgot to pass GO on the "kill the drake" part there

**Comment by nevimer** [comment]
you must fix the dme issue being out of order

**Comment by lurzefromgermany** [comment]
> you must fix the dme issue being out of order

done did

**Comment by StrangeWeirdKitten** [comment]
I don't think Ashwalkers need free drake armor without killing the drake. They already have innate melee armor just by species alone.

**Comment by StrangeWeirdKitten** [comment]
Ash walkers already get a 0.8 brute modifier (20 percent). They don't need free ash drake armor.

**Pull request merged**
