### PR TITLE
Campaign Trail: Fixes the obj sprites of some hats.

### PR DESCRIPTION
**Pull request by theselfish**
## About The Pull Request

Title.
I also fixed an oversight from my last PR.

I also merged another loadout folder into the main one because holy shit we need to start cutting down on that and organizing it.

## Why It's Good For The Game

Objs should be clickable.
File structures should be easy to use.

## Proof Of Testing

TBD

## Changelog

:cl:
del: Tiny loadout folder is now annexed into the bigger one.
qol: Drill hats are clickable and are in the command vendor. (Thanks to F13 for the OBJ sprite.)
/:cl:

### CODE REVIEW

**Comment by theselfish** [comment]
Okay, fuck this /obj/machinery/vending/access/command shit.

**Comment by theselfish** [comment]
@Majkl-J Unrelated conflict, I think?

**Comment by theselfish** [comment]
image
Same with the rest. I got...Distracted playing around.

**Review by Majkl-J — APPROVED** [review]
I FORGOT TO REVIEW THIS

**Pull request merged**
