### PR TITLE
[DONE] Adds the weakness to sol quirk

### PR DESCRIPTION
**Pull request by Arturlang**
## About The Pull Request
You know how bloodsuckers are weak to Sol? Now you can be too! Only as a hemophage.
Features included: The very same warnings and UI that bloodsuckers get to know when they are in danger!
This quirk also makes healing in a coffin cost only half blood, neat huh?

## Why It's Good For The Game
People wanted to suffer, and why am I to deny them pain?

## Proof Of Testing
HUD/ burning / healing works fine

## Changelog

:cl:
add: Adds the hemophage-only quirk, Sol weakness
code: Refactors the sol subsystem so that itself decides if it should run or not based on if anyone is using it.
code: Refactors bloodsucker UI elements so that they can function fine outside a bloodsucker antag datum
code: bloodsucker_blood_volume, humanity_lost, bloodsucker_level and bloodsucker_level_unspent are now private variables due to them being used for UI updates, if you need to change them, use the procs that are written in the autodoc
code: Quirk species whitelists no longer use bitflags, but use the species ID's. Easily allowing you to add new whitelists without having to mess around with making a new bitfield
/:cl:

### CODE REVIEW

**Comment by Yanziko** [comment]
So, I'm not a hemophage player myself, but as a question, you mentioned that it won't make healing in a coffin require blood? If that's a mechanic by default, cool, but weird. But I feel like as a negative quirk, this shouldn't give any buffs necessarily. That's just my cup of tea.

**Review by Majkl-J — CHANGES_REQUESTED** [review]
The checks need to be made to pass

Probably do it by building off the edits on code/datums/quirks/_quirk.dm#L70 and the #82 PR

**Comment by Tupinambis** [comment]
Not a fan, this gets into pseudo antag territory because three vampire tells (coffins, needing to leave to go to coffin, dying to sol) become just a normal part of the species. We did this with sort of thing with xenohybrids and it didn't work wel.

**Comment by AllCorruptingWyrm** [comment]
I'm a big fan of this, I think this really much helps with preventing "meta detectiveness" in regards to who is the antag this round, plus, I'd like to larp as a vampire and build that aesthetic and its nice to have mechanics to support that.

**Comment by Majkl-J** [comment]
> Not a fan, this gets into pseudo antag territory because three vampire tells (coffins, needing to leave to go to coffin, dying to sol) become just a normal part of the species. We did this with sort of thing with xenohybrids and it didn't work wel.

Exactly why it should be added nobody should be able to just meta something because haha coffin

**Review by Majkl-J — APPROVED** [review]
Great job. I'll testmerge this for a few days then give the green light

**Comment by radarseas** [comment]
a few things...

1: this should **not** be a negative -6 quirk, if anything it should be more of a neutral quirk considering the following other things I've found.

2: it provides a rather large mood buff in fact for resting in a coffin, a very, _very_, large mood buff that SHOULD ONLY BE A VAMP THING, that doesn't seem very, negative? In fact this is without hypersensitive and monkey blood feeding I'm already max mood. **FUCK.**

3: yes I'm aware you heal but still, that's more positive than negative, especally how easily coffins can be made and that sol is only like, every 20ish minutes.

4: making it a negative over neutral almost if, anything encourages people to take this, for points.. considering it mimics an antagonist (bloodsuckers) very, very closely in behavior, it probably shouldn't be encouraged as a pick.

5: it still mentions final death, _which makes no sense as a hemophage._

**Comment by Arturlang** [comment]
> a few things...
> 
> 1: this should **not** be a negative -6 quirk, if anything it should be more of a neutral quirk considering the following other things I've found.
> 
> 2: it provides a rather large mood buff in fact for resting in a coffin, a very, _very_, large mood buff that SHOULD ONLY BE A VAMP THING, that doesn't seem very, negative? In fact this is without hypersensitive and monkey blood feeding I'm already max mood. **FUCK.**
> 
> 3: yes I'm aware you heal but still, that's more positive than negative, especally how easily coffins can be made and that sol is only like, every 20ish minutes.
> 
> 4: making it a negative over neutral almost if, anything encourages people to take this, for points.. considering it mimics an antagonist (bloodsuckers) very, very closely in behavior, it probably shouldn't be encouraged as a pick.
> 
> 5: it still mentions final death, _which makes no sense as a hemophage._

-2 or 0 would be best y'think? I was told to make it rather high with how it could potentially kill you. I'll remove the positive mood buffs too

**Review by Majkl-J — CHANGES_REQUESTED** [review]
I agree that this should not grant antag level positive mood bonuses, however all the other points are invalid once these are removed/have an alternate version tuned down to +2 at most.

As for the healing, already was a thing on hemophages, they can keep it.

**Comment by Arturlang** [comment]
Actually yeah, I could reduce the mood bonuses to something milkd

**Comment by Majkl-J** [comment]
> Actually yeah, I could reduce the mood bonuses to something milkd

Keep the mood debuff at a higher value still, -5, -4 ish

**Comment by Arturlang** [comment]
> > Actually yeah, I could reduce the mood bonuses to something milkd
> 
> Keep the mood debuff at a higher value still, -5, -4 ish

bad sleep is already a -3 for closet, -6 for burning, I'm just reducing the positive buff to 4 from 10

**Comment by Arturlang** [comment]
@Majkl-J @radarseas  What should be the quirk cost? 2+ or -2?

**Comment by Arturlang** [comment]
@radarseas Can you tell me anything more about the timer being de-synced? More specifics? Are you sure the timer was completely off kilter that it displayed 11 minutes when you had 30 seconds left?

**Comment by Arturlang** [comment]
Another thing I'm wondering is if I should make the hemophage healing not occur during Sol, for quirk-holders, so it doesn't unnecesarily use the blood if you're in a closet

**Comment by SovietSpaghetti** [comment]
Considering how bloodsuckers an antag are built around powerscaling silently, much like heretics, I don't think making them harder to tell is a great idea, especially if it's encouraged by making it a negative quirk. Bloodsuckers were designed without having hemophages (an easy excuse to build up blood) already, and now there's another easy excuse as to the other major tell. Even disregarding that, it seems like it'd be a pain for security or medical. Imagine having to yank someone out of a cell and take them to their maint corner because they'll die otherwise, or have someone jump off your operating table to run to their coffin. Or what if nobody responded at all? I see lots of potential for people to just be forgotten about and die like this.

**Comment by Arturlang** [comment]
> Considering how bloodsuckers an antag are built around powerscaling silently, much like heretics, I don't think making them harder to tell is a great idea, especially if it's encouraged by making it a negative quirk. Bloodsuckers were designed without having hemophages (an easy excuse to build up blood) already, and now there's another easy excuse as to the other major tell. Even disregarding that, it seems like it'd be a pain for security or medical. Imagine having to yank someone out of a cell and take them to their maint corner because they'll die otherwise, or have someone jump off your operating table to run to their coffin. Or what if nobody responded at all? I see lots of potential for people to just be forgotten about and die like this.

Don't worry I'm going to make a PR at least testing making bloodsuckers only able to level up from drinking blood from sentient people. As for the latter, this is a opt-in quirk, completely optional to get, if you feel like going through some pain.

**Comment by Arturlang** [comment]
Timers seem to be running normally on the testmerge and local

**Comment by Majkl-J** [comment]
A coffin isnt the one thing to spot bloodsuckers and definitely shouldnt be. Nor should be someone just walking away from work. What should be enough to sus them out is actual abilities and the other structures typical of a bloodsucker. If you wanna play to win, sure, but you're gonna need to do some more effort to prove a bloodsucker than just finding random coffins.

From a quick search over rules on some servers that have bloodsuckers: Fulp imposes metaprotections on knowing about antags and what they do, Yogstation even explicitely has coffins metaprotected

I believe this is a nice way to both prevent metagaming and give players more options with their characters. I am willing to discuss the balance of this quirk, but the decision on the core idea staying is final

**Comment by Arturlang** [comment]
> I'd personally keep it in line with neutral quirks since we already have some that do actively hinder you, such as phobias _(which I might add can range from decently annoying to absolutely crippling) (these blind and hardstun you, nasty if someone yells "big pharma" over comms and you get trammed on the tram rail because you can't move)_.
> 
> Or aren't particularly more bad than good _(ageuisa for example prevents you tasting stuff but it also lets you eat stuff like mold or rats as humans as well as normal food without worrying about food buffs/debuffs)_
> 
> Or transhumanist which is a free cyborg limb plus buffs around people with cybernetics but debuffs around those without arguments.
> 
> I'd argue maybe -2 would work, as a negative, but if its a hemophage only thing, it'll probably be milked by other races, its better to keep it neutral like custom turf emote stuff in my opinion.

It's currently hemophage only and a -4, non-hemophages should be unable to select them, tell me if they can

**Comment by radarseas** [comment]
> It's currently hemophage only and a -4, non-hemophages should be unable to select them, tell me if they can

you can change to hemophage race, select it and change back.

**Comment by Majkl-J** [comment]
> > It's currently hemophage only and a -4, non-hemophages should be unable to select them, tell me if they can
> 
> you can change to hemophage race, select it and change back and it stays weirdly.

Oh amazing.

**Comment by Arturlang** [comment]
> > It's currently hemophage only and a -4, non-hemophages should be unable to select them, tell me if they can
> 
> you can change to hemophage race, select it and change back and it stays weirdly.

Will fix it JS side

**Comment by StrangeWeirdKitten** [comment]
The core PR itself is given my support aswell. Bloodsuckers suffer a little because there's no metaprotection and coffin = antag. I think it's fine to give a hemophage character the option. While I'm not the best open arbitar of TG balance, this is the type of stuff TG does to make blatent antag signs a more common thing so they're not immedietly rushed down. (Fake armblades, rips in reality toys, etc). Balance stuff and overall ability can always be adjusted, but the core quirk itself is approved by me aswell.

**Comment by Arturlang** [comment]
In trying to fix the issue with quirks saving after changing species, I happened to refactor how quirk species whitelists work, which instead of a bitflag and a hardcoded list, now only require a list variable on the quirk itself, this was far far harder than you'd think it would be, due to initial() not being able to get lists

**Comment by Arturlang** [comment]
I'd update the TM and see how this works out, this is now a refactor of species whitelists, sorry.

**Review by Majkl-J — APPROVED** [review]
I've heard no real balance complaints (Aside from very select members of the community stating the same points I already dismissed). We can merge this now and make adjustments later if the need be

**Pull request merged**
