### PR TITLE
Moonstation Linter Fixes and other stuff.

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Fixes Moonstation linters (hopefully).
Fixes floating air alarm in the AI upload.
Repaths most of the water spawns.
Adds a hidden pulse rifle.
The public mining elevator can now go down to lavaland.
Adds more carpet to dorms.

## Why It's Good For The Game

Fixes good.

## Proof Of Testing

If it compiles, it werks.

## Changelog

:cl: BurgerBB
fix: Fixes some moonstation issues.
/:cl:

### CODE REVIEW

**Comment by Swiftfeather** [comment]
> I'm sorry a HIDDEN PULSE RIFLE???

Is just like mojang's removed herobrine changelog it's fine.

**Comment by Swiftfeather** [comment]
Error: [15:02:14] Runtime in code/__HELPERS/_planes.dm,102: The liquid input pump (/obj/machinery/plumbing/floor_pump/input/on/directional/east) was expected to have a TOPDOWN_LAYER

**Comment by Shadow-Quill** [comment]
The floor pumps are causing CI to fail because of https://github.com/Skyrat-SS13/Skyrat-tg/issues/29105

**Comment by BurgerLUA** [comment]
> The floor pumps are causing CI to fail because of [Skyrat-SS13/Skyrat-tg#29105](https://github.com/Skyrat-SS13/Skyrat-tg/issues/29105)

thank you for figuring this out, I was wondering if it was a Moonstation issue or what.

Making this a draft until I restore the pipes to their former glory. I gotta re-add them because I thought them existing on moonstation caused issues.

**Comment by Shadow-Quill** [comment]
Yeah, 'tis only the liquid pumps causing things to fail. At the very least, you could remove them from wherever they exist to at least have CI working for the repo.

**Comment by BurgerLUA** [comment]
good to merge if this passes linters

**Comment by Swiftfeather** [comment]
I cry every time, openspace runtime

**Comment by BurgerLUA** [comment]
what in the fuck happened

**Comment by BurgerLUA** [comment]
branch appears to be fucked, opening a new pr

**Pull request closed without merging**
