### PR TITLE
Prevents the Dauntless from making boulder retrieval matrices

### PR DESCRIPTION
**Pull request by ReturnToZender**
## About The Pull Request
Miner beware! There is a Syndicate man under your home stealing your hard-earned boulders.

Because the Dauntless receives tier 4 parts roundstart, if they build a boulder retrieval matrix after mining tech is researched, their own retrieval matrix has priority over the station one, causing all the boulders to go to Cybersun. *shakes fist

Note that this doesn't affect autolathes producing boulder smelters or refineries, only the matrixes used to steal boulders from miners,

## Why It's Good For The Game
Stops the Dauntless from ruining the station's material supply roundstart using boulder retrieval matrixes

## Proof Of Testing
Sci Imprinter:
image

Offstation Imprinter:
image

## Changelog

:cl: ReturnToZender
fix: Cybersun and Tarkon can no longer produce boulder retrieval matrixes to steal from the station roundstart.
/:cl:

### CODE REVIEW

**Comment by shellspeed1** [comment]
At some point we are going to need to address the material quantity balance as well for the boulder miners. The station should not have over 700 sheets of bluespace and diamond.

**Comment by ReturnToZender** [comment]
> At some point we are going to need to address the material quantity balance as well for the boulder miners. The station should not have over 700 sheets of bluespace and diamond.

definitely agree but out of scope here

**Comment by StrangeWeirdKitten** [comment]
> At some point we are going to need to address the material quantity balance as well for the boulder miners. The station should not have over 700 sheets of bluespace and diamond.

TG issue

**Comment by Mewchild** [comment]
I'd like to pose a question: Does this affect the interdyne/icebox map as well? Mining is a large part of the gameplay loop on interdyne, and normally, boulder machines only get built after syndicate miners have tapped their own vents. Also, a boulder refinery can be called down as a reward from the mining vendor, costing roughly 800 points.

**Comment by ReturnToZender** [comment]
> I'd like to pose a question: Does this affect the interdyne/icebox map as well? Mining is a large part of the gameplay loop on interdyne, and normally, boulder machines only get built after syndicate miners have tapped their own vents. Also, a boulder refinery can be called down as a reward from the mining vendor, costing roughly 800 points.

Yes, it does. The refinery itself is fine, it's specifically the boulder matrix that causes issues currently.

**Comment by Odairu** [comment]
> At some point we are going to need to address the material quantity balance as well for the boulder miners. The station should not have over 700 sheets of bluespace and diamond.

this is also not difficult to have done in early round if you have a competent atmos tech anyway

**Comment by StrangeWeirdKitten** [comment]
This hasn't been an issue and the station makes so many mats anyways.

**Comment by ReturnToZender** [comment]
image

It's still a problem

**Pull request closed without merging**
