### PR TITLE
[Non-Modular Because Globalvars suck ass] Mirror-Nova: "Girl Dinner: Adds Mariinsky Ballet Company Chassis"

### PR DESCRIPTION
**Pull request by IgiariValkyr**
### This will be a 1:1-ish paste of the Nova PR's description. I noticed that the actual pull from Nova did not edit the RD's labcoat like it says it does.

This PR adds:

A new synth chassis, Mariinsky Ballet Company. Sprite inspired by Signalis and Atomic Heart.

## Why It's Good For The Game

More synth character customization. Peg legs have been requested for a long time, especially in the wake of Signalis' release. The sprite is compatible with most hairstyles and clothing.

### Nova's Screenshots
304930570-1a99a916-0be7-4f2e-87d2-98656448daa7
304930656-3c8a2637-8129-400b-b9f7-d262355cce6c

## Changelog

:cl:
add: Parts from a discontinued synth chassis line from the Mariinsky Ballet Company is making rounds on the black market - now available to install for synths and chromed up organics!
/:cl:

### CODE REVIEW

**Comment by IgiariValkyr** [comment]
So to fully describe my issues with making this modular:

- It turns out you can't have a modular system load _globalvars/lists.dm, then the second also load _globalvars/lists.dm. This throws duplicate errors, even if you cut it down to bare minimums.
- As much as I tried, it would not load the ipc_parts.dm file from the modular_zubbers folder, even when I had it pointed the right way. Was probably being overwritten by Skyrat's. Keep in mind for the future if Skyrat ever adds new synth frames.
- When it wasn't pulling the ipc_parts.dm file right, it was pulling null icons, which also fucked up a lot of other options in the character creation panel.

It's in. It works. I'm not doing another fucking thing with it outside look at reviews for edits.

**Comment by IgiariValkyr** [comment]
Wew. Narrowly avoided linters with the bad maps no one cares about (this isn't a map PR anyways)

**Comment by PaznerIV** [comment]
I really like this however walking around barefoot gives off the sound those of organic feet, so I was wondering if maybe if we could get 'shoes' that blend with the legs that we could get apart of our load outs

**Comment by Lutowski** [comment]
Hi, I'm the person who made this sprite. Thanks for porting this over! The labcoats had to be done in a different PR by Golden's request, so you're welcome to port that too.

**Comment by IgiariValkyr** [comment]
> Hi, I'm the person who made this sprite. Thanks for porting this over! The labcoats had to be done in a different PR by Golden's request, so you're welcome to port that too if I never get around to it.
> 
> (psst, you can also recolor the head!)

You're welcome. Apologies for never asking about porting it over. Shame I can't get the globalvars to work without overwriting a whole file, but I've seen a few people actually using the chassis and they seem happy having it here.

**Comment by projectkepler-ru** [comment]
If this doesnt exist already on SR you should probably put it there

**Comment by Cyprex** [comment]
lgtm, could be PRed to upstream Skyrat, could be PRed here! This seems fine to merge to me!

**Review by Majkl-J — APPROVED** [review]

**Comment by IgiariValkyr** [comment]
Immediately ate shit. Not sure from what, but someone didn't read the //BUBBER EDIT comments. Uh oh.

**Comment by glitchbow** [comment]
(Staring hard into the camera like it's The Office)
I really like this chassis so please fix this, thank you. ♥
I'm just glad it was a coding oopsie and not someone from Nova malding that their sprites are seeing use on other servers.

**Comment by IgiariValkyr** [comment]
> (Staring hard into the camera like it's The Office) I really like this chassis so please fix this, thank you. ♥ I'm just glad it was a coding oopsie and not someone from Nova malding that their sprites are seeing use on other servers.

I'll have it re-added again soon. Might bug the shit out of Ozzo so I know how to modularize the globalvar list this time so it doesn't get immediately wiped.

**Pull request merged**
