### PR TITLE
[I'm back.] Removes Firefly from NTC

### PR DESCRIPTION
**Pull request by ReturnToZender**
## About The Pull Request
Knock knock. The MX-17 Firefly fires stardust shells from the pistol. These stun shells are extremely powerful and available roundstart. Also, it's a second gun and I want only one gun.
image

## Why It's Good For The Game
Brings the NTC down to a similar level as their fellow heads of staff, returning them to their RP role status quo.

## Proof Of Testing
image

## Changelog

:cl: ReturnToZender
balance: NTC no longer gets Stardust shells, they get only their laser.
/:cl:

### CODE REVIEW

**Review by Swiftfeather — APPROVED** [review]
I agree with the stardust being an absurd roundstart item. I also really like stealing this pistol from the NTR and decimating people with it. Will wait for another maintainer to merge it

**Comment by RenScorch** [comment]
Made me log in just to say that this is why no one can have anything nice or fun.

**Comment by StrangeWeirdKitten** [comment]
yeah this is absurd lol

**Review by StrangeWeirdKitten — APPROVED** [review]

**Comment by ReturnToZender** [comment]
Ready for TM/merging ^^

**Pull request merged**
