### PR TITLE
Reset the Gateway to TGstation, allowing cyborgs to enter

### PR DESCRIPTION
**Pull request by nevimer**
## About The Pull Request
Very short sighted to mess up the gateway like this only because black mesa is the only gatway ran upstream
Why should be suffer mediocrity? 
Merge only after update from upstream
## Changelog

:cl:
code: Gateway now functions as it does on TGstation
/:cl:

### CODE REVIEW

**Comment by Majkl-J** [comment]
image
Should I... ask?

**Comment by nevimer** [comment]
Part of the branch it was based of of, to stay fresh

**Comment by nevimer** [comment]
poke me to redo this better later

**Comment by Sweettoothart** [comment]
Pai's cant use the gateway either

**Pull request closed without merging**
