### PR TITLE
Fixes Quirks Not Actually Working

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Fixes Quirks Not Actually Working

## Why It's Good For The Game

Fixes Quirks Not Actually Working

## Proof Of Testing

Untested. Just like last time :^)

## Changelog

:cl: BurgerBB
fix: Fixes Quirks Not Actually Working
/:cl:

### CODE REVIEW

**Comment by BurgerLUA** [comment]
Basically it checks the balance in two different areas which is fucking stupid but whatever.

**Comment by Majkl-J** [comment]
This works no need to have a draft

**Review by Majkl-J — APPROVED** [review]

**Review by Majkl-J — CHANGES_REQUESTED** [review]
I was informed these dont work

**Comment by BurgerLUA** [comment]
> I was informed these dont work

Nope, that's why it's a draft.

**Comment by BurgerLUA** [comment]
Closing because this is too time consuming and hard to fix.

**Pull request closed without merging**
