### PR TITLE
Yes AIs in modsuits

### PR DESCRIPTION
**Pull request by ReturnToZender**
## About The Pull Request
Removes the Skyrat edit barring AIs from entering MODsuits

PR is fully tested and ready to go

## Why It's Good For The Game
There's a woman in my MODsuit that calls me stud muffin.
image

## Changelog

:cl:
add: AIs go in MODsuits
/:cl:

### CODE REVIEW

**Review by nevimer — CHANGES_REQUESTED** [review]
bubber blocks not removal

**Comment by ReturnToZender** [comment]
> bubber blocks not removal
grumbles

**Review by Majkl-J — CHANGES_REQUESTED** [review]
Can be modularised by overriding
```
/obj/item/mod/control
	allow_ai = TRUE
```
in a modular file

**Comment by StrangeWeirdKitten** [comment]
> Can be modularised by overriding
> 
> ```
> /obj/item/mod/control
> 	allow_ai = TRUE
> ```
> 
> in a modular file

This is true @ReturnToZender.

**Comment by ReturnToZender** [comment]
Moved the override to the modular file, tested and it works! :D

**Pull request merged**
