### PR TITLE
(Somewhat) ports forging unleashed from Xyelrat.

### PR DESCRIPTION
**Pull request by theselfish**
## About The Pull Request

Title.
https://github.com/Skyrat-SS13/Skyrat-tg/pull/25861

The only part I left as is was the blacklisted regents. As funny as a cum spear would be...

## Why It's Good For The Game

Let's be honest. Forging is a bit boring after a while. You can only do so much.
Getting to create a pizza or meat sword injects some life into it.

Also this hard edits a Skyrat file, but due to the current situation, I'm unsure on the policy on that.

I was intending to port https://github.com/GalacticStation/GalaxiaStation/pull/13 but we've not merged the renaming PR required for it. 
"Why not do it yourself" you might say.
Because Ozzo is doing an upstream merge PR and I'd rather not conflict with that.

## Changelog

:cl:  jjpark-kb (ported by Cursor)
add: Meat swords are back on the menu.
/ :cl:

### CODE REVIEW

**Comment by jjpark-kb** [comment]
Ahh, perhaps you can at least relax on some of the reagents?

**Comment by theselfish** [comment]
Unsure on that. Ask a maintainer.

**Comment by projectkepler-ru** [comment]
?

**Comment by theselfish** [comment]
> ?

Forging Regents have a blacklist.
image

**Comment by projectkepler-ru** [comment]
> > ?
> 
> Forging Regents have a blacklist. image

that much im aware

**Comment by theselfish** [comment]
> > > ?
> > 
> > 
> > Forging Regents have a blacklist. image
> 
> that much im aware

Balance is much more of a maintainer thing, I feel the blacklist is a bigger deal than this PR.

**Comment by theselfish** [comment]
These are both in https://github.com/Bubberstation/Bubberstation/pull/897

**Pull request closed without merging**
