### PR TITLE
Adds nearly every item to the game into maintenance.

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Nearly every single item in the game has been judged on an arbitrary criteria, organized, and put into maintenance loot if I think it should be in maintenance loot.

## jesus fucking christ

Okay so I basically scanned through every item in the game to see if it's not too OP, and I added it into maintenance loot. The PR is still a draft because I need to rest and look at it tomorrow to see if I missed anything (and also fix the almost guaranteed compile errors from the PR because there are likely missing commas and stuff). It took me about 5 hours of work to do the nonsense of creating a 2247 line list of items in the game as well as assigned weights to make the insane stuff rare and the useful stuff common.

This shouldn't be merged when it's done, but rather test merged for a period of maybe a month so people can give feedback about items being common and items not being common. Some people might be worried that the amount of items would be too high and shit would be near guaranteed to spawn, but I've made similar PRs across several coderbases that are like this so that maint loot is varied and balanced.

## Todo list

- [x] Fix compile errors.
- [x] Increase the density of loot spawns so there is more loot to play around with.
- [x] Do a quick double-check to see if the weights make sense.
- [x] 1 month testmerge.
- [x] Get berated by people who think that adding an secret ultra-rare meteor pen to a possible loot option is a terrible idea.
- [ ] Merge.

## Changelog

:cl: BurgerBB
add: Nearly adds every single item in the game into maintenance. Quintuples loot spawns in most places.
/:cl:

### CODE REVIEW

**Comment by Cyprex** [comment]
I haven't looked at the individual items yet, but... this might actually be workable! I'll have to look into this!

**Comment by BurgerLUA** [comment]
PR passes all unit tests except the qdel one on some maps, which throws errors on the mixed light tube box(not touched in this pr) and something to do with the holopara (also not touched in this PR)

**Comment by TripleShades** [comment]
Hey make sure you're excluding the base items that others use to inheret if they're not unique/stand-alone, so we dont get shit like "This is an eyepatch hud! What kind of hud? Nothing!" or "This is a generic refill container" where it's a literal nothing because it wasn't meant to be spawned.

**Comment by BurgerLUA** [comment]
> Hey make sure you're excluding the base items that others use to inheret if they're not unique/stand-alone, so we dont get shit like "This is an eyepatch hud! What kind of hud? Nothing!" or "This is a generic refill container" where it's a literal nothing because it wasn't meant to be spawned.

I need a list of items that are showing up that aren't supposed to because there isn't really a good way for me to know if it's an item that shouldn't be spawned.

**Comment by nevimer** [comment]
Close to merging.

**Comment by TripleShades** [comment]
Still getting instances of base items.
Off the top of my head: coupons.

**Comment by Serxule** [comment]
some of the shotgun rounds shouldnt be in (pretty sure the rip round just instantly gibs whatever limb it hits or just instakills)

**Pull request merged**
