### PR TITLE
Smuggler Satchel Overhaul

### PR DESCRIPTION
**Pull request by BurgerLUA**
Probably the second coolest thing I made (second to the map I made). Everything is tested and works.

### Smuggler Satchel Placement
Smuggler satchels now have reworked and complex spawn locations,. They will no longer be haphazardly placed in random locations. The spawning locations will use the following criteria:
- Spawning locations have maintenance and the prison prioritized.
- The tile actually must be a removable tile.
- The tile cannot be tile that shows piping or wiring, such as a catwalk or glass floor tile.
- The tile must not be in a planetary area.
- The tile must have regular round-start atmos.
- The tile must contain at least one dense object.
- The tile must not contain a dense anchored object.
- The tile not be within 8 tiles of another smuggler's satchel.

While the current smuggler satchel count is 10, sometimes only 6-7 spawn (on metastation, at least) because of how limited space is with the current spawn conditions.

### Smuggler Satchel Contents
Smuggler satchel contents will now contain 3 auto-generated contents taken directly from the traitor uplink, with the following criteria:
- The item must not exceed 3 telecystals in price.
- The item must not be limited to nuke ops or clown ops, or both.
- The item must not be a limited stock item.
- The item must not be a "restricted" item (this is only used for Traitor Deathmatch VR, to prevent funny things that affect the station, like an announcement).
- The item must not be a storage item, including boxes.

With that criteria, these are the following items and their weights (higher is more frequent) with satchel spawns.
```
/obj/item/ammo_box/foambox/riot = 2.25
/obj/item/ammo_box/magazine/m9mm = 9
/obj/item/ammo_box/magazine/m9mm/ap = 2.25
/obj/item/ammo_box/magazine/m9mm/hp = 1
/obj/item/ammo_box/magazine/m9mm/fire = 2.25
/obj/item/toy/cards/deck/syndicate = 9
/obj/item/traitor_spraycan = 9
/obj/item/clothing/glasses/sunglasses = 9
/obj/item/clothing/mask/gas/syndicate = 9
/obj/item/stack/telecrystal = 9
/obj/item/grenade/clusterbuster/soap = 1
/obj/item/grenade/c4 = 9
/obj/item/gun/ballistic/automatic/pistol/toy/riot = 2.25
/obj/item/soap/syndie = 9
/obj/item/tram_remote = 2.25
/obj/item/computer_disk/syndicate/camera_app = 9
/obj/item/card/emag/doorjack = 1
/obj/item/disk/nuclear/fake = 9
/obj/item/healthanalyzer/rad_laser = 1
/obj/item/stack/sticky_tape/pointy/super = 9
/obj/item/syndicate_contacts = 1
/obj/item/nifsoft_remover/syndie = 1
/obj/item/crowbar/power/syndicate = 1
/obj/item/clothing/gloves/tackler/combat/insulated = 2.25
/obj/item/syndie_glue = 1
/obj/item/dnainjector/clumsymut = 9
/obj/item/mmi/syndie = 2.25
/obj/item/mod/module/springlock/bite_of_87 = 2.25
/obj/item/mecha_parts/mecha_equipment/concealed_weapon_bay = 1
/obj/item/clothing/shoes/chameleon/noslip = 2.25
/obj/item/card/id/advanced/chameleon = 2.25
/obj/item/multitool/ai_detect = 9
/obj/item/language_manual/codespeak_manual/unlimited = 1
/obj/item/toy/plush/carpplushie/dehy_carp = 9
/obj/item/pen/edagger = 2.25
/obj/item/suppressor = 1
/obj/item/melee/baton/telescopic = 2.25
/obj/item/mod/module/visor/thermal = 1
/obj/item/mod/module/visor/night = 2.25
/obj/item/mod/module/chameleon = 2.25
/obj/item/mod/module/plate_compression = 2.25
/obj/item/mod/module/noslip = 2.25
/obj/item/clothing/suit/armor/vest = 9
/obj/item/clothing/suit/armor/bulletproof = 1
/obj/item/clothing/head/helmet/swat = 2.25
/obj/item/flashlight/lantern/syndicate = 2.25 
```

Also 1 random drug is added, from the old smuggler satchel code (Also fireworks because that's classic).

### Smuggler Satchel Locating
Smuggler satchels can no longer be found with regular t-ray scanners or by observing via ghost. In order to see them through tiles, you have to emag a t-ray scanner to find them through the tiles. They of course can be found by other methods, such as actually searching under hiding spots where they'd be!

To make things easier for the antag (and to make an emag purchase worth it), smuggler satchel locations are now more visible with a special underfloor graffiti that is picked up via an emagged t-ray scanner,

### Extras

Sunglasses, the syndicate toolbelt, and the syndicate toolbelt now show up in the uplink for low TC costs so (some of them) show up in the smuggler's satchel.

## Why It's Good For The Game

eh

## Changelog

:cl: BurgerBB
balance: Smuggler satchels now have intelligently generated random locations, contain much better equipment (on average), and can no longer be picked up via observing or a regular t-ray scanner. T-ray scanners can be emagged to see smuggler satchels. Smuggler satchels are now easier to see.
/:cl:

### CODE REVIEW

**Comment by nevimer** [comment]
This will need a lot of discussion

**Comment by DeerJesus** [comment]
this aint really it chief- this will moreso just lead to people crowbarring the floors of an entire department for tot loot as nontot. also these smugglers items are way too good. also you can buy smugglers satchels

**Comment by BurgerLUA** [comment]
> this aint really it chief- this will moreso just lead to people crowbarring the floors of an entire department for tot loot as nontot. also these smugglers items are way too good. also you can buy smugglers satchels

Ones bought from the uplink are empty.

**Comment by BurgerLUA** [comment]
Also with the this system, a smart player could find a smuggler's satchel with minor time and effort.

**Comment by YakumoChen** [comment]
This just takes an item that anyone can find and use mostly filled with innocent items and makes it basically an antag-only item or will make prisoners / security tear up the prison floors every round for illegal tech

**Comment by Detective-Google** [comment]
this is a lot of uplink creep and slip immunity is normally almost entirely inaccessible for crewside for a reason. We shouldn't be encouraging people to go around crowbarring up under every machine or locker in their department because there might be gamer loot in it.

**Comment by Detective-Google** [comment]
overall; smuggler satchels are already *very* strong and really don't need a buff in the first place. the ability to hold way more normal size items is already pretty busted

**Comment by StrangeWeirdKitten** [comment]
Smuggler satchel does not need an airlock override card, super glue, and other powerful traitor gear and gamer loot. I think they're fine as is, as the biggest use for them is it's a free satchel.

**Comment by destrucktoid** [comment]
yeah i agree with the sentiment of others here, this is a bad change. Smuggler's satchels as it is are basically used to unlock illegal tech and for extra storage space. Adding a stack of **9** telecrystals to a smugglers satchel is just... Wow.

**Comment by Majkl-J** [comment]
Stale. Ask for a reopen when work on this begins again

**Pull request closed without merging**
