### PR TITLE
[Review ready] New mutation - Strong legs

### PR DESCRIPTION
**Pull request by Maia-J**
## About The Pull Request

Adds a new mutation - Strong Legs

This mutation allows you to leap around, just like a bunny! The leap allows you to hop across tables, chasms, and smack through regular windows. Smacking through reinforced windows not advised

## Why It's Good For The Game

It's silly, and we kinda lack exclusive mutations, so.

## Proof Of Testing

TBD

<details>
<summary>Screenshots/Videos</summary>

</details>

## Changelog

:cl:
add: Strong legs mutation, for leaping around
/:cl:

### CODE REVIEW

**Comment by ReturnToZender** [comment]
Can you make this let me crush someone's head with them thanks

**Comment by projectkepler-ru** [comment]
> Can you make this let me crush someone's head with them thanks
> 
> I'm okay with it being an ERP only thing

second this

**Comment by nikothedude** [comment]
Is this that one goof pr with the bunny infusion

**Comment by Majkl-J** [comment]
> Is this that one goof pr with the bunny infusion

Yes but coded from the bottom up by me so it's probably worse in every way (I still gotta optimize the code)

**Comment by RimiNosha** [comment]
This is in the wrong folder, please move it to bubber's folder.

**Comment by Majkl-J** [comment]
> This is in the wrong folder, please move it to bubber's folder.

I'm aware and I don't really mind much I'm gonna have to go through both and merge them into one `modular_bubber` folder eventually so I'd rather have it together in skyrat's mutation folder for the sake of my sanity so I don't have to micromanage 5 folders when I'll be moving stuff

**Pull request merged**
