### PR TITLE
Nerfs the Abductor Baton

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Reduces abductor baton knockdown time from 14 seconds to 4 seconds.
Reduces abductor baton sleep time from 2 minutes to 30 seconds.
Increases abductor cuff time from 3 seconds to 5 seconds.

Abductor Baton recall now only works when you're on the ship.

## Why It's Good For The Game

Abductor baton is one of the most hugboxed items in the game. Not only does it have a one hit guaranteed knockdown of 14 ENTIRE SECONDS, but it also has:

- A cuff mode that cuffs people in 3 seconds.
- A sleep mode that sleeps people for 2 whole minutes.
- A recall feature that teleports the baton to your hand if you drop it.

Meanwhile in the past 6 years or so, /tg/, skyrat, and bubberstation have been moving away from instant one-click stun combat, yet the abductor baton has remained untouched. Not to mention a weapon recall feature for when you actually lose an encounter and drop your baton.

It's amazing to me that people complain about security hugbox meanwhile we have something like this in code.

## But this makes abductor harder!

Abductor is supposed to be hard. You're supposed to ambush unsuspecting crew and not always win that encounter. You literally have several fallbacks (baton recall, teleport, etc) to prevent yourself from getting caught.

In no universe is it sane for a midround ghostrole antag to be able to take on 5 people at once with a baton because one click is all you need.

## Proof Of Testing

Untested.

## Changelog

:cl: BurgerBB
balance: Nerfs the Abductor Baton
/:cl:

### CODE REVIEW

**Comment by destrucktoid** [comment]
First off, normal stamcrit is about 10 seconds till recovery, this change makes it so that your abductor baton stuns for 4 seconds.
Second off, increasing the handcuff time to 5 seconds makes it longer than normal handcuffs
Third off, 30 seconds is nowhere near enough time in a realistic scenario to actually get the scientist down to scan to bring you up to do the surgery on you.
Fourth off, _You made it so the stun lasts less time than it takes to actually cuff them with your changes_.
Fifth off, Stamcrit lasts about 10 seconds, the changes you made to the abductor baton make it so that a _normaly security stun baton_ is more effective at keeping someone stunned.

This entire stream of changes screams to me entirely of you having a personal vendetta against Abductors. Abductors are one of the strictest antags out there when it comes to admin oversight. You cannot go around killing people on abductor because doing so WILL get you bwoinked, even TG has it where abductors cannot go around killing people and need to actually abduct people. The baton is so strong _because_ it is an abductor. Getting stunned and slept like an abductor does to you in almost any other context means death, abductors just experiment on you instead. Going around mass stunning people in any situation except self defence _will_ get you bwoinked because again, they are one of the antags with the strictest admin oversight.

These changes are terrible and massive overkill for an antagonist that doesn't really need nerfs. They are easy to run away from if you see them coming, if you don't see them coming then that's a scenario where you should lose to them anyway. These changes are not a good change for the antagonist or the game and clearly were not thought through or tested in any meaningful way to see if they were realistically viable.

**Comment by AllCorruptingWyrm** [comment]
Abductors very rarely have Admin oversight, in fact, the only antags that do have oversight are Malf Ai as a staffie has to approve Delta (afaik), anyway with that said Abductors recently got ruled that strapping them to tables/chairs is a bug so this nerf is pretty deserved.

**Comment by StrangeWeirdKitten** [comment]
Abductor baton sleep is already 30 seconds due to a nerf I already merged. The only alternative nerf I'll accept is adding a cell charge to the baton. (Yes I looked into this and it requires extensive edits and a bit more work due to how item paths are)

**Comment by Majkl-J** [comment]
`modular_zubbers/code/game/objects/items/abductor.dm#L4`

Sleep is already 30, no more nerfs to non-lethal options are being considered as of current

**Comment by BurgerLUA** [comment]
> `modular_zubbers/code/game/objects/items/abductor.dm#L4`
> 
> Sleep is already 30, no more nerfs to non-lethal options are being considered as of current (Except a rework of the baton itself)

This makes zero sense. Why specifically go "no nerfs against non-lethal options allowed?" when the method of takedown shouldn't be the sole determination of why it shouldn't even be looked at.

**Comment by Majkl-J** [comment]
> This makes zero sense. Why specifically go "no nerfs against non-lethal options allowed?" when the method of takedown shouldn't be the sole determination of why it shouldn't even be looked at.

You can still try and rework it into using a cell. The whole role is seeing its rework currently so adding extra weight in modular edits could just slow that down

**Comment by BurgerLUA** [comment]
> > This makes zero sense. Why specifically go "no nerfs against non-lethal options allowed?" when the method of takedown shouldn't be the sole determination of why it shouldn't even be looked at.
> 
> You can still try and rework it into using a cell. The whole role is seeing its rework currently so adding extra weight in modular edits could just slow that down

"We're not accepting nerfing non-lethals."
"However you can nerf it by making it use a cell."

christ dude just because it's not your idea doesn't mean it shouldn't be accepted

**Comment by BurgerLUA** [comment]
Also the draft WIP abductor PR that you're referring to has not touched abductor balance in the slightest and only touches objectives. Adjusting 3 variables via modular edits won't slow anything down in the slightest.

**Comment by Cyprex** [comment]
For the duration of the balance freeze I will not be accepting abductor nerfs. It's a freeze for a reason. We do not want to constantly have these conversations.

As to this PR: Abductors fundamentally have very strong nonlethal melee options. This is good because it helps stop them from killing others, which synergizes well with them not being supposed to kill people. They are also very similiar to revenants, in that they are rather limited in what they can do, and rather hard to kill in return.
Rather than go toe-to-toe with them in melee just shoot them.

**Comment by BurgerLUA** [comment]
> For the duration of the balance freeze I will not be accepting abductor nerfs. It's a freeze for a reason. We do not want to constantly have these conversations.
> 
> As to this PR: Abductors fundamentally have very strong nonlethal melee options. This is good because it helps stop them from killing others, which synergizes well with them not being supposed to kill people. They are also very similiar to revenants, in that they are rather limited in what they can do, and rather hard to kill in return. Rather than go toe-to-toe with them in melee just shoot them.
> 
> Edit: I just learned the freeze is over- Abductor nerfs are still very likely a no from me for the above reasons!

Pretty sure the rules stop them from killing others unless in obvious self defense. They're supposed to experiment on crew, but not interfere in means other than experimentation.

Abductors should have good stun equipment but not 14 WHOLE SECONDS OF IT. People gave me shit for making stealth implants a 4 second stun on cardboard breaks, but for some reason we're okay with 14 seconds on a baton that is just given freely to abductors.

**Pull request closed without merging**
