### PR TITLE
[Revert/Partial Rework] progressive traitor exists again

### PR DESCRIPTION
**Pull request by Odairu**
## About The Pull Request
Reverts the change that removed secondary objectives (and thus progtot) from traitors, while also removing TC gain from the secondary objectives.

## Why It's Good For The Game
When a traitor can't think of anything to do they have a list of things that they could go accomplish that will put them in conflict with other players. Without the incentive of gaining TC from these objectives, they no longer are required like they once were when we used to have progtot, and ultimately do not serve any mechanical benefit/advantage to the player. This removes the worst part of progtot (silently doing objectives while amassing massive amounts of TC to then 1 v 9 security at 2 hours) while still giving players a more comprehensive list of things to do.

## Proof Of Testing
Only issue is a visual bug where when you complete an objective depending on lag it will show it as awarding TC, but even if you hit the button while it says this, it awards none as intended. Elsewise works perfectly fine 

https://github.com/Bubberstation/Bubberstation/assets/39929315/9959ad37-3100-4281-9389-0a4af7d08a6d

## Changelog

:cl:
add: progtot back into rotation
balance: progtot no longer gains TC
/:cl:

### CODE REVIEW

**Comment by nevimer** [comment]
this won't work

**Comment by Wolf-751** [comment]
Why would i do secondary objectives if they do not reward me with tc ? simple i would not. Human beings are risk vs reward driven creatures,without the reward for the risk the risk is not taken,similarly why do i traitor if all my gimmick objectives auto complete themselves? I do not because there is no reward to do anything thus traitor is in a limbo of doing fuck all every round because there is no pull to do anything meaningful in the round except doing the once in a in a blue moon normal traitor objective that gets silently done anyways without any interaction between crew or security.

**Comment by Odairu** [comment]
> Why would i do secondary objectives if they do not reward me with tc ? simple i would not. Human beings are risk vs reward driven creatures,without the reward for the risk the risk is not taken,similarly why do i traitor if all my gimmick objectives auto complete themselves? I do not because there is no reward to do anything thus traitor is in a limbo of doing fuck all every round because there is no pull to do anything meaningful in the round except doing the once in a in a blue moon normal traitor objective that gets silently done anyways without any interaction between crew or security. The second point of prog traitor was to get traitors back into a round if sec caught them,currently if security catches you its game over for you on your traitor round,so people do not take the risks to interact with security because of the base 25 tc being your hard locked amount to 'win'.

if you don't plan on doing the secondary objectives if they don't give TC, then why does it matter if its in the game or not. This makes it no longer a 'requirement' by making it have no incentive, the intention is for people that can't think of something to do to now have something to do.

**Comment by Wolf-751** [comment]
> > Why would i do secondary objectives if they do not reward me with tc ? simple i would not. Human beings are risk vs reward driven creatures,without the reward for the risk the risk is not taken,similarly why do i traitor if all my gimmick objectives auto complete themselves? I do not because there is no reward to do anything thus traitor is in a limbo of doing fuck all every round because there is no pull to do anything meaningful in the round except doing the once in a in a blue moon normal traitor objective that gets silently done anyways without any interaction between crew or security. The second point of prog traitor was to get traitors back into a round if sec caught them,currently if security catches you its game over for you on your traitor round,so people do not take the risks to interact with security because of the base 25 tc being your hard locked amount to 'win'.
> 
> if you don't plan on doing the secondary objectives if they don't give TC, then why does it matter if its in the game or not. This makes it no longer a 'requirement' by making it have no incentive, the intention is for people that can't think of something to do to now have something to do.

currently traitors dont do anything they have no reason to,once in a blue moon do they actually attempt to fight but most of the time traitors are just doing nothing because they find no point in doing gimmicks and at the same time they cannot recover once they lose.

**Comment by Moostard** [comment]
I prefer progtot over normal and gimmick traitor.

This is because gimmick objectives are a guaranteed greentext, so usually those traitors do not do anything during the round. 
Normal traitor usually ends in a quick objective rush or a last minute rush, which once again causes nothing to happen during the round.
Progtot makes traitors actively do things that doesnt go the usual "fight sec, fight command, ignore everyone else" loop.
People hated it, because their safe bubbles were popped once traitors were given objectives to sabotage their department.
I dont know man, but the server advertises itself to have antags, so complaining about being affected by some antag is just funny in a bad way.

Progtot should give TC rewards, but some objectives that are insanely easy should just disappear.
All pet killing (including EN).
Stealing boards that you can just PRINT. Seriously, this is the easiest thing ever.
I would say that a final objective like romerol could be available, as it is quite interesting and takes ACTUAL effort to do compared to "lmao round is over" final objectives.

Like others said, why take the risk if there is no reward?
Plus, traitors wont be able to farm TC that easy with the current space law. Before it was a 10 minute break, now it can end in perma if they get caught twice or so.
And if only serious objectives are left, like the bomb scan thing, murders, lathe and ORM sabotages, destroying blackboxes and stealing valuable items, it will be much much harder to farm in the first place.
Most of that TC farming was done on lowpop anyway.

**Comment by ReturnToZender** [comment]
The unit test contains a part that checks if a progression objective's reward is zero. You'll need to remove that check to pass tests.

**Comment by radarseas** [comment]
**one** important thing, this will only apply to **roundstart traitors.**, latejoiners gotta are infils which only get contractor as their prog option, which is arguably superior.

Its a bit iffy if they lack any gains at all even for the more riskier objectives. there should be TC for objectives that actually have some big risk to them, like assassinations, kidnapping, console hacking, etc. If anything the issue is being _guarrented_ more objectives if you complete your secondaries, _no matter how fast you do them._

**especally lowpop, highpop progtot arguably works _really_ nicely now we don't have guarrenteed antagonist spam.**

better idea, just disable it for lowpop rounds. Its somewhat okay with higher pops as long as roundstart tots are tweaked down, so we get more infils/sleepers.

**Comment by Majkl-J** [comment]
You need to do this again from a clean rebased branch as it causes conflicts that make it unable to be TMd

**Pull request closed without merging**
