### PR TITLE
Adds Moon Station: AKA Burgerstation 2

### PR DESCRIPTION
**Pull request by BurgerLUA**
Draft because it needs some final touches, and the CI checks need to be enabled for this map.

## About The Pull Request

https://www.youtube.com/watch?v=Sr57Je1fVvM

map updated

Re-adds Burgerstation, except it's called Moon Station now.

## Why It's Good For The Game

it's not lmao

## TODO

- [x] Fix CI map errors/warnings.
- [x] Re-add all the hallway robot pathing nodes.
- [x] Test disposals + mail.
- [x] Fix arrivals shuttle
- [x] Test powernets.
- [x] Test supermatter + supermatter waste disposal.
- [x] Test clown chamber.
- [x] Remove all security cameras and replace them with custom ones.
- [x] Test camera visibility.
- [x] Test maint club + theatre buttons.
- [x] Test security timers.
- [x] Test ERT and whiteship shuttle docks.
- [x] Test the map itself with a testmerge.
- [x] Adjust map according to feedback.

## Changelog

:cl: BurgerBB
add: Adds Moon Station
del: Removes Burgerstation
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
I'm not sure the station needs an entire, fully built second engine on top of the supermatter.

**Comment by YakumoChen** [comment]
image
this needs an additional safety, otherwise people coming down the chute are very likely to be lava'd

**Comment by YakumoChen** [comment]
image
Xenobio could stand to be trimmed down a little. The cells are too large and you can make more cells by giving them only one window of seperation

It could also do with some de-isolation like modern TG maps. Add more windows instead of r-walls.

**Comment by BurgerLUA** [comment]
image

**Comment by BurgerLUA** [comment]
Assuming it passes linters, this map is ready for live testing.

**Comment by BurgerLUA** [comment]
(Just keep in mind there will be bugs).

**Comment by BurgerLUA** [comment]
Tram is failing, so is blueshift.

**Comment by ReturnToZender** [comment]
Pretty much just a net improvement from the original Burgerstation, will make edits to this comment with things I notice.

Left side of the Medbay could use an extra door. Note that if you're approaching from below, you have to walk around. Bit of a nitpicky thing.
image

**Comment by StrangeWeirdKitten** [comment]
Galactic Materials Marked needs to be removed due to the infinite money. Stonks are too strong

**Comment by lessthnthree** [comment]
Add all the available navigation waypoints so that players can use the navigate feature to find things and learn the map.

**Comment by BurgerLUA** [comment]
> Add all the available navigation waypoints so that players can use the navigate feature to find things and learn the map.

Those should exist. If there are some missing, post them here.

**Comment by StrangeWeirdKitten** [comment]
Ordnance is missing a holofan and there needs to be a way to enter the freezer chamber since the doors are bolted.

**Comment by lessthnthree** [comment]
Missing light fixtures here

image

**Comment by lessthnthree** [comment]
These three hallway doors have no access permissions set

image

**Comment by Icarus-The-Sun** [comment]
There's an administrative circuit in science rather than a normal circuit in science, which can cause confusion for new players.

**Comment by BurgerLUA** [comment]
> There's an administrative circuit in science rather than a normal circuit in science, which can cause confusion for new players.

Please elaborate

**Comment by Sylphet** [comment]
There's no wrench in medbay, players can't wrench the tanks for the cryopods without one. Also dorms have no bolts, not sure if that's fixed yet.

**Comment by BurgerLUA** [comment]
> There's no wrench in medbay, players can't wrench the tanks for the cryopods without one. Also dorms have no bolts, not sure if that's fixed yet.

Both have been fixed in latest. The server just needs to update.

**Pull request merged**
