### PR TITLE
(Mostly-Modular) SSV Dauntless - Interdyne Rework

### PR DESCRIPTION
**Pull request by StrangeWeirdKitten**
#481 Yeah I fucked up and my original PR closed.

image

## About The Pull Request

Replaces Interdyne only on Lavaland with an entirely new syndicate outpost. It combines what made DS-2 so beloved with Interdyne.

## Why It's Good For The Game

Interdyne is old. It's lived out a good life, and when DS-2 was remapped, people shifted more towards playing on DS-2. Sadly it was removed, but I've spent the time to completely map an entirely new ship that combines both DS-2 and Interdyne. It still takes up relatively the same footprint. Now, everything is focused internally, with two bluespace miners that have to be set up, and a prisoner spawner. All and all, let's try something new and Bubber flavored.

**Edit:** Cybersun is an incredibly shallow ghost role and it only breeds boredom, which then is sated in two ways: 

- Space tide with syndi gear and the syndicate faction tag
- Screw with the station

Neither really is the goal for this server and this is being edited after discussion with both Cheeto and Ozzo after apparently ruin blacklist doesn't work on the config. 

## Testing / Tour
Raw video. Buttons do work.

https://youtu.be/BHbOIwpqQqY

## Changelog

:cl: Danger Kitten
add: Lavaland has more Syndicate presence. SSV Dauntless has landed.
remove: Cybersun no longer spawns.
/:cl:

### CODE REVIEW

**Comment by Detective-Google** [comment]
>>   Is this ready to be testmerged? I want to try it.
>
>Sorry I haven't worked on it, I reformatted my computer and didn't ever redownload git. I'll try to finish some stuff up today. Big >changes I have planned
>
>    Removal of some of the suits. I'm thinking 1 blood red and the elite suit.
>    Some dense walls around the base. Slightly wider footprint, but this is to stop stray colossus shots from detonating one of the >explosive R_walls and chain-reacting the entire base
>
>>   This isn't true. Only Colossus has 100% AP and even then it's only in the projectiles, not melee attack
>
>The lethality of Colossus does not come from his melee. It usually ends up with a shotgun to the face. Regardless, I aim to give at >least a 40-minute head start to miners. That's plenty of time to be outpaced. Comparatively, it's melee armor. That's what mining >armor is strongest. (drake has 70 percent melee protection)
>
>    Otherwise it will be a pain in the ass to upgrade the turbine. No it cannot be upgraded by a BSRPED, it has to be done by >hand.
>
>Every map needs you to work around the turbine. Just pull out the middle, upgrade the two sides, and slot it back in. I'm really >not going to make it look weird and diagonal for this slight 30 more second work around. It will still produce plenty of power
>
>>    I'd also consider widening the moat, albeit that would add extra footprint to the map, the current interdyne base has the >turrets only firing a little past the lava, which serves as a good deterrent to people hanging around nearby or trying to cross it >but is unlikely to snipe players digging around. Wider lava would also help to reinforce the encouragement against leaving >implicit in the design.
>
>Dense walls will fix this issue.

These all look like good steps, still not a fan of the elite MOD but it's not the end of the world.

The dense walls are very nice for getting trolled by colossus spawns, so many rounds of walking on eggshells. one round we had to buy an SM shard from the station and *launch* it at one to get it off our door.

Even though there's not a distinct "mining bay", I'd like it if the Interdyne special "Express Only" mining vendor was around somewhere, since you can't build a new one otherwise; and "Mary Sue, Syndicate Operative, has ordered mining supplies that will arrive on the shuttle!" is silly.  

I'll definitely miss having dedicated miners since that was my favorite thing to do; but that's just a personal opinion more than any distinct balance consideration.

**Comment by dominuslucian** [comment]
Just a few things I noticed the first round I played, not sure if any of them are addressed but I'll list a few that I remember:


Turrets are set to shoot slimes, meaning that the first round we played the windows got smashed and BZ was released onto the station.

There's a wiring error in the syndicate security area next to the Holding Cells APC where the APC isn't wired up to the Grid
image

For some reason we have hardsuits instead of modsuits in the armoury (not sure if this is intentional or not but at least MODsuits make some sense whereas hardsuits don't have any purpose at all on lavaland)

I noticed that Syndicate heads of staff have complete access to other heads of staff's private quarters and to the Syndicate armoury. This was abused the very first shift we played when the RD stole a sniper rifle and used it to magdump 50 monkeys for seemingly no reason. (This is more a personal gripe than anything else, not too sure how the code relating to access requirements work but ill write it anyway)

This one's really minor, but someone brought it up during the round so I'll mention it and that's the lack of a library console in the Syndicate permabrig. I guess prisoners really love their books.

Apart from those gripes, I do like what's been done with it and having to manually power the base with the turbine was a nice touch so I'd say overall it's good but needs a few touch-ups.

**Comment by StrangeWeirdKitten** [comment]
> These all look like good steps, still not a fan of the elite MOD but it's not the end of the world.

I honestly don't believe the syndicate mod suit makes much of a difference armor-wise when everything on lavaland does melee damage. I'm not giving them actual mining suits (which can be added for the increased armor) or ming cards which can buy the SEVA suit for lavaland storm protection. Overall the ash drake suit is much better. 

> Even though there's not a distinct "mining bay", I'd like it if the Interdyne special "Express Only" mining vendor was around somewhere, since you can't build a new one otherwise; and "Mary Sue, Syndicate Operative, has ordered mining supplies that will arrive on the shuttle!" is silly.

I probably can just replace the mining vendor board with the Interdyne one inside the ancient protolathe. It would defiantly help all ghost roles.
 
> I'll definitely miss having dedicated miners since that was my favorite thing to do; but that's just a personal opinion more than any distinct balance consideration.

I think the people who contribute to the main station should have priority (and 40 40-minute head start) to the megafauna rush. I did a lot of Interdyne mining. Trust me, I really enjoyed it. But at the end of the day, the NT miners are the most important people in Lavaland from a gameplay perspective while everyone else is a ghost role.

**Comment by StrangeWeirdKitten** [comment]
> It might be nice to add  antagpanel_category = ANTAG_GROUP_SYNDICATE to their job datum if possible to separate dauntless members from crew members on the observer board.

Feels like antag panel bloat and I don't even think Ashwalkers should get this.

**Comment by StrangeWeirdKitten** [comment]
image

**Comment by Detective-Google** [comment]
the pizza spawner can randomly have bomb pizzas and is close enough to the self destruct it's led to the entire base being vaporized at least once. Funny but probably unintended

**Comment by StrangeWeirdKitten** [comment]
> the pizza spawner can randomly have bomb pizzas and is close enough to the self destruct it's led to the entire base being vaporized at least once. Funny but probably unintended

Already addressed them

**Comment by Majkl-J** [comment]
Please add a condiment master and fix this single door's accesses
image

**Comment by Majkl-J** [comment]
image
move it somewhere not above the chair, maybe above the table

**Comment by StrangeWeirdKitten** [comment]
> Please add a condiment master and fix this single door's accesses image

done

**Comment by StrangeWeirdKitten** [comment]
**I added a Dauntless lawset**

```	
inherent = list("Operations: You are on a secret Syndicate Spy Vessel. Preserve and maintain the secrecy and integrity of the Dauntless and its crew.",
		"Prioritize: Carry out orders as directed by Dauntless operatives according to rank and role.",
		"Survive: Your secrecy must be maintained. Do not allow external tampering or damage to your equipment."
)

**Pull request merged**
