### PR TITLE
Reagent forging no longer makes healing completely free of charge

### PR DESCRIPTION
**Pull request by Majkl-J**
## About The Pull Request

Reagent weapons now take significant hits to their durability from transferring reagents.

Imbuing requires some skill now

## Why It's Good For The Game

Simply put, staves trivialize healing. All you need is a singular smith to dish out 1 libital staff, as medbay starts with just enough roundstart to make this possible. (I counted this and there is just enough in gels, with enough granibitaluri to make a fair bit more staves for minor damage)

The reagent injected is also always 100% purity, which further more makes this comically primitive. You as a chemist need to put it about 10 minutes of effort in order to make every other form of healing useless. This inevitably will result in more inexperienced players too, as there is no longer a need to learn on how to get 100% purity, or how to do basic forms of damage tending efficiently. Learning optimal ways to do something shouldn't bypass the basic mechanics, but be an extension of them. The current state of the staff is able to entirely bypass this line of thought

## Changelog

:cl:
balance: Reagent weapons now get damaged upon reagent transfer
balance: Imbuing once again needs actual skill
/:cl:

### CODE REVIEW

**Comment by Superhats** [comment]
I'm biased as someone who uses staves a ton but I feel like the prep time involved more than compensates for reagent staves having infinite chems. 100u of chems is a lot, when most chems only need 5-10u to do their thing. Going through the whole logistics of imbuing a staff is significantly more effort when making a couple medical gels would last the whole round anyway.

Them taking damage seems reasonable, but I feel like nerfing the attack rate of staves would just make them completely pointless, given they already only inject 1u as-is.

Generally they're a niche mechanic as-is and this feels like a very unprompted nerf to me.

**Comment by Majkl-J** [comment]
> I'm biased as someone who uses staves a ton but I feel like the prep time involved more than compensates for reagent staves having infinite chems. 100u of chems is a lot, when most chems only need 5-10u to do their thing. Going through the whole logistics of imbuing a staff is significantly more effort when making a couple medical gels would last the whole round anyway.
> 
> Them taking damage seems reasonable, but I feel like nerfing the attack rate of staves would just make them completely pointless, given they already only inject 1u as-is.
> 
> Generally they're a niche mechanic as-is and this feels like a very unprompted nerf to me.

Their attack speed went from 400ms to 1000ms, which honestly barely changes anything in the grand scheme of things, just makes them take the same time to inject 5u as it would take feeding someone a pill

**Comment by Superhats** [comment]
> > I'm biased as someone who uses staves a ton but I feel like the prep time involved more than compensates for reagent staves having infinite chems. 100u of chems is a lot, when most chems only need 5-10u to do their thing. Going through the whole logistics of imbuing a staff is significantly more effort when making a couple medical gels would last the whole round anyway.
> > Them taking damage seems reasonable, but I feel like nerfing the attack rate of staves would just make them completely pointless, given they already only inject 1u as-is.
> > Generally they're a niche mechanic as-is and this feels like a very unprompted nerf to me.
> 
> Their attack speed went from 400ms to 1000ms, which honestly barely changes anything in the grand scheme of things, just makes them take the same time to inject 5u as it would take feeding someone a pill

Alright, that's a bit more valid.

**Comment by sneksnek** [comment]
Reagent staves as current will deliver a statistical 5.5 units of a chemical in the same time it takes to feed a pill without nitrile gloves. With nitrile gloves, the time to feed a pill is halved, so a staff will be able to deliver 2.75 units of a chemical in the time it takes to feed a pill. Nitrile gloves are adequately accessible by medical staff so I do not see their quantity as a limiting factor to consider.

Pills can administer much more than 5.5 or 2.75 units in both conditions regardless. This means they greatly eclipse the rate that chemicals can be administered compared to a staff. As well, they can administer more than two chemicals at once. You do not need to interact with a patient further after administering a single pill. Finally, pills can be instantly ingested if used by the patient themselves. I do not think a staff will make pills obsolete, nor do I think it makes other means of administering chemicals or surgery obsolete.

Reagents metabolize every 2 seconds, meaning a 1 second swing rate of staves will do nothing to slow down the healing rate of a singular patient (most healing chemicals have 0.2u metabolization). One could somewhat easily juggle two staves with four different brute healing chemicals and keep up on the metabolization. The slower swing speed only affects someone going around and constantly hitting multiple targets with the staff, which I do not believe is a common condition. With this all said, I think the staff swing speed nerf is a mostly pointless change.

The organ damage is egregious. 5 liver and stomach damage a swing is high, even with the swing speed nerf. If imbued with maintenance tar, a single swing and full metabolization of 1 unit of maintenance tar deals 12.5 liver damage. This means it would take 9 swings to fully damn someone's liver to death (not 8 since the liver would heal a few points in the time). This is less swings than it would take formerly with a maintenance tar staff, albiet the staff could be swung faster and inject the necessary chemicals to kill the liver quicker. At any rate, I think the organ damage is too great, even if not weaponized. A single unit of libital deals 1.5 liver damage normally. Hitting someone with a libital reagent staff will make it deal over four times as much total liver damage, as well as stomach damage.

Lastly, in support of a nerf: generating the reagents necessary for a staff is trivial. You can grind two ointments for 100u lenturi to make a lenturi staff and slapdashly toss 35u phenol, nitrogen, and oxygen in a beaker to make 100u of libital for a staff. It takes minimal effort to make the chemicals necessary. 

I think it would be better to stop at durability loss to prevent spamming staves too much, if that is the presented concern. I would also advocate for lowering the purity of staff-sourced chemicals to 75%, but I do not know how difficult that may be to change.

**Comment by Quill-Weave** [comment]
Hi! This commit seems like a bad idea!

Right, so a few things;

1. Reagent items are already weaker than the Shamshir and other Blacksteel items, and having them break apart defeats the point of them; you're putting a ton of a chemical into the item so you do not have to make it anymore. Chemicals damaging organs is generally tied to fermichem balancing and not reagent item balancing.

2. Chemists can also produce a way larger volume of pure reagents than the staff. If it's 1 unit per hit, and a 0.4 hit cooldown, it takes 60 seconds of whacking a person straight to inject them with what three 50u patches could apply - not that you should. With a 1 second cooldown, that's 60 units, sure - but you can easily make 100+ units in chemical form in under a minute with most common chemicals.

3. Ash walkers, Hermits, and other ghost roles/jobs can come to rely on reagent items for supporting their generally awful medical abilities. In addition to this fact, staves also let you control dosage to ensure you do not inject too much of a chemical into somebody. You could argue that staves could be weaponized for this purpose, but then why not just use a normal reagent item, or dip arrows in chemicals? In addition to this, not all chemicals are pure from plants; imbuement is one of few ways to purify them, to my knowledge. 

I personally propose a different change, if you are so concerned about reagent items stepping on the toes of chemists; Why not make it so that imbuement takes Legendary blacksmithing again? This way, John Shoeeater the Moth can't grind a bunch of ambrosia and make a quaalude stick in under five minutes of round time.  

I also read Sneksnek's post - he has a lot of good points on it. There's a bunch of random items that can be ground into huge piles of reagents for staves, but this can again be fixed by simply putting imbuement reagents back up to 200u each.

All in all, I don't really like the idea of this change - do you have any reasoning that supports this huge nerf beyond what you've already posted?

**Comment by Majkl-J** [comment]
Alright, let's break it down one by one. Hope I don't miss any points mentioned here.

## Firstly, organ damage being "Too much" concerns.
image
Mind you, killing someone's liver doesn't down them instantly, only starts ticking toxin damage up. Plus you literally buff your enemy for the time being before their liver gives out. So making a sword is generally more optimal, even against armor targets it will simply be more reliable and actually cause a slowdown. But sure, I'll make the max organ damage the staff can deal to be 2.5, and lower the max to 50.

## Repair concerns
image
image
I have no idea if you just don't know this, or tried to say this in bad faith to make me reconsider. Considering it is said directly in the examine, I am picking the second option. Your staff is almost broken down? Go visit the smith.

Staves have 200 integrity, with -3 a hit a reagent you still have 2/3 of your investment repayed before you need repairs

## Controlling dosage 
_oh look there is a tool made specifically for this_
image
image
image
and guess what, with these changes it is exactly as fast as the staff when giving 2u, and can also give 5u, outspeeding it!

## Chemists producing large amounts of pure chems
Yes, I know. They can easily do that. I have more than enough hours on chemist to roundstart create enough basic damage type chems at 100% purity.

But you know, new chemists can also just let the smith pour 60% purity libital on a sword and learn nothing. The issue here is they don't have to know how to make 100% purity anything, they can just... roundstart make a heal all that doesnt use anything else afterward


_Unrelated, I have been told that there is no check that prevents imbuing before the forge is upgraded. It seems someone just sloppily removed it, or that it was never there, as I see no checks for it anywhere in the code that allows you to imbue. Even though all the mentions of it in the code seem to imply you need to be of legendary skill to upgrade it and allow it. So that will also be fixed_

**Comment by aKromatopzia** [comment]
Stuff like this is why reagent weapons should have stayed mostly-restricted to the primitive ghost roles.

**Comment by Majkl-J** [comment]
> Stuff like this is why reagent weapons should have stayed mostly-restricted to the primitive ghost roles. Balancing items that were not meant for mass crew use, to compensate for crew use feels silly.

This balancing act partly reverts parts of skyrat's "Forging unleashed" PR by bringing back the damage from reagent transferring, which also happened to allow these for station use. Meaning ghost roles used to have to deal with their reagent weapons slowly ticking up in damage as they were used.

**Comment by sneksnek** [comment]
> Mind you, killing someone's liver doesn't down them instantly, only starts ticking toxin damage up. Plus you literally buff your enemy for the time being before their liver gives out. So making a sword is generally more optimal, even against armor targets it will simply be more reliable and actually cause a slowdown.

A dead liver is game over. Nobody in medbay is going to heal it if the target is an antagonist and there aren't any easily accessible ways to heal it. I do not think anyone prepares for having their liver killed.

The buff from maintenance tar is almost entirely meaningless to one wielding the staff. You most likely won't be stunning them and even if you were, it's not very good (it's 25% as effective as meth).

You can wield a weapon that deals damage in the other hand and use it both between the cooldown of using a staff and the metabolization of the maintenance tar, so you are still capable of damaging an opponent (albeit not as effectively as hitting them with a sword instead). As long as you keep hitting them with the staff within 10 seconds of each hit, the rate of liver death will not be impeded. A staff's organ damage will entirely pierce armor as well and ignore any brute healing the opponent may have.

I do not see the point of organ damage or the swing speed reduction. Limiting a staff's total healing potential to 66% (durability is 200, each swing consumed 3 durability, each swing yields 1 unit, so 66.66 units can be distributed before breaking) of what 100 units of a 100% pure chemical could do is essentially the same as making it output chemicals at 66% purity in the long run.

**Comment by Majkl-J** [comment]
> Nobody in medbay is going to heal it if the target is an antagonist and there aren't any easily accessible ways to heal it.

Why would sec carry a staff when they have way better weapons at hand? And if a random greytider does, we have a thing for that, it's called "getting banned for validhunting". Plus I already lowered it to at most 50% organ damage, so this point is invalid anyhow.

> You can wield a weapon that deals damage in the other hand and use it both between the cooldown of using a staff

I'm not even gonna explain, just look into how `changeNext_move()` works and come back. Or try to do this yourself, ingame, we do have it testmerged and you get all the smithing tools in the cafe if you want a calm testing area. Or just ahelp it if you want the tools for it in there. Point invalid.

> Limiting a staff's total healing potential to 66% (durability is 200, each swing consumed 3 durability, each swing yields 1 unit, so 66.66 units can be distributed before breaking) of what 100 units of a 100% pure chemical could do is essentially the same as making it output chemicals at 66% purity in the long run.

You can repair it. That's like the entire point of this change, it makes it that if you wish to get repayment on the investment, you have to put in more interdepartmental interaction, and it makes the healing not completely free. Go to the blacksmith sometime if you want to maintain the infinite healing, let them smack it a few times, bam, done. If you do not wish to do that just use a hypospray. You know, the thing that medbay has like 20 of

> I do not see the point of organ damage or the swing speed reduction.

The organ damage is there to make it straight up slightly worse than other medical options. It is a ghetto tool, and you are whacking someone with it hard. Speed reduction is there to make it ever so slightly worse than a baseline hypospray, which is a tool specifically designed for the niche the current staff occupies

**Comment by sneksnek** [comment]
> Why would sec carry a staff when they have way better weapons at hand? And if a random greytider does, we have a thing for that, it's called "getting banned for validhunting". Plus I already lowered it to at most 50% organ damage, so this point is invalid anyhow.

Sec doesn't need to. The initial argument didn't pertain to sec specifically. Blacksmithing reagent items are used primarily by non-security from what I've observed. I wasn't suggesting that the staff user was validhunting either and there are use cases that don't involve validhunting (defending oneself or their department for example). The point was that it was very abusable without the cap. The lessened organ damage and cap ameliorates the issue regarding that but I think it is still too heavy a penalty for medical use which I will touch on more below.

> I'm not even gonna explain, just look into how changeNext_move() works and come back.

Alright, my understanding on how this worked was incorrect. The bit about hitting between full metabolization still applies but is not as relevant with the organ damage cap. It would take a minimal 11 swings now, but more if it was swung after the cap. In a realistic conflict it would likely take more. So I will consider this not an issue as well.

> You can repair it. That's like the entire point of this change, it makes it that if you wish to get repayment on the investment, you have to put in more interdepartmental interaction, and it makes the healing not completely free.

I don't disagree with this part. I was attempting to say it was a good way to decrease staff spam since one would need to take the time to repair it. A full durability staff would have the total healing capability of 67 units. My reasoning was that this serves as enough of a nerf to staves alone.

> The organ damage is there to make it straight up slightly worse than other medical options. It is a ghetto tool, and you are whacking someone with it hard. Speed reduction is there to make it ever so slightly worse than a baseline hypospray, which is a tool specifically designed for the niche the current staff occupies

It is already worse than other medical options for reasons I stated in my initial post. To reiterate, for the medical department, pills and patches can administer more chemicals at a much higher rate, can be distributed to the crew en masse, can administer more unique chemicals than one staff can at once, and only require one interaction to administer (you don't need to bonk them with a staff repeatedly). Hyposprays and gels also share three of those four listed qualities (you could distribute them but pills and patches suffice). Not to mention how many staves you would need to make to cover all the bases and seiver doesn't work with them. I heavily disagree that they trivialize healing and make every other form of healing useless.

For a ghetto tool accessible by non-medical crew, it is powerful, but I think the durability change is enough of a deterrent. I don't think an average greyshirt needs that much raw healing chemicals anyways.

To finally touch on organ damage, the cap eliminates the issue of killing organs because of the high quantity of libital or lenturi necessary to kill the liver and stomach respectively, even if said organs hypothetically had 50 damage. But with that said, I do not agree with the reasoning behind the organ damage in the first place because staves are already worse than orthodox forms of healing in multiple ways.

**Comment by Majkl-J** [comment]
I cut the organ damage in favour of making imbuing not roundstart

**Comment by sneksnek** [comment]
oh. i am blind. cool beans

**Comment by Majkl-J** [comment]
> oh. i am blind. cool beans

I did forget to push it in time, but yeah. Currently it's just the damage + needing the skill to actually imbue and repair imbued, and the speed change

**Comment by Quill-Weave** [comment]
Right, so some replies.

1. Honestly, the organ damage and nerfs in general seem ham-fisted and against a problem that does not really exist, especially the swing speed. These things don't impose on chemists. I will put it bluntly; Reagent weapons do not make Chemistry worse, or steal it's job. 

2. Repair hammers are inexpensive to make. You can go to the techfab and the library or garden and make it; this is just a huge nerf for people who don't have them, namely, ASH WALKERS and ghost roles. Your proposed changes make the game harder and less pleasant for people who already play it in a more challenging way, and; 

3. Trailing on that point, Ash Walkers don't have those. You ignored my giant point about how your proposed changes ruin things for ghost role players. I've consulted other ashies. This is a bad change for a community that you never addressed other than saying "this is the less extreme option" when you are literally PRing it back in.

4. Staves are not a ghetto tool. Reagent stuff/forging is a involved process, and the staff is literally intended as the harmless way to transfer reagents, so. Why add harm? Doesn't that go against the entire point? 


Also making imbuing skill related is a good balance change/fix, as opposed to the entire nerf on staves, so credit where credit is due.

**Comment by Majkl-J** [comment]
> Right, so some replies.
> 
> 1. Honestly, the organ damage and nerfs in general seem ham-fisted and against a problem that does not really exist, especially the swing speed. These things don't impose on chemists. I will put it bluntly; Reagent weapons do not make Chemistry worse, or steal it's job.

The organ damage is no longer there. I removed it from the PR body and literally said I removed it in favour of making it need smithing skill to imbue and repair imbued. The speed has been changed to make it actually worse than a hypospray when microdosing chemicals, as before it actually outsped it on all settings. It isn't stealing it's job, but it creates a shortcut for new players as it is easier than actually learning anything. All of these I specifically outlined

> 2. Repair hammers are inexpensive to make. You can go to the techfab and the library or garden and make it; this is just a huge nerf for people who don't have them, namely, ASH WALKERS and ghost roles. Your proposed changes make the game harder and less pleasant for people who already play it in a more challenging way, and;
> 3. Trailing on that point, Ash Walkers don't have those. You ignored my giant point about how your proposed changes ruin things for ghost role players. I've consulted other ashies. This is a bad change for a community that you never addressed other than saying "this is the less extreme option" when you are literally PRing it back in.

Ashies literally get hammers. There is no special "Repair hammer", and if they lose it, they can craft a primitive one.
This is not me "Ignoring your point". This is me calling it irrelevant, because frankly, it is. Please stop making shit up about how repairing works. It isn't even that tedious to repair, it takes around 10 hits to repair most almost broken tools. On a 1 second cooldown. I doubt you even consulted ashies, because I did ask about how those changes affected them and got that they didnt even feel it. 
image


> 4. Staves are not a ghetto tool. Reagent stuff/forging is a involved process, and the staff is literally intended as the harmless way to transfer reagents, so. Why add harm? Doesn't that go against the entire point?

If they are intended to be a "Harmless way to transfer reagents", there's also: Hyposprays, syringes, pills, patches, syringes. They should not bypass any of these, let alone be better. Most nonmedical healing ways are balanced by causing some level of harm, for example the bible. But either way, the harm is no longer there.

**Comment by Quill-Weave** [comment]
1. That's good. The organ damage was just bad. 

2. I know it's the primitive hammer - however, unlike your average spaceman, it's relatively easy for a newer ashie to pick it up, walk off, and bang, you gotta make a new one. Which also makes getting items themselves harder, but that's an entirely different can of worms. Please don't get so hostile towards critique; I am merely giving my opinion, not trying to start a rumble with you.

3. My understanding is that you did not cite how these changes would change their gameplay in your PR. A lot of it was station-centric. 

4. How many ghost roles can access a chemmaster or hypospray to make the aforementioned patches and such? Outside of Tarkon/Syndicate/etc; Think Hermits, Ice/Ash Walkers, etc.

I digress; of all the changes proposed here, I favor just slapping on the old skill gate and calling it a day is the reasonable approach. Any other changes to the staff, at least with the current state of the game, doesn't seem to line up well with the numbers proposed by Sneksnek, among other unforeseen things.

If your current plan is to just add the skill gate to imbuing, and nothing else, I support that. Honestly it was a bit appalling having random people build smithies to zero-skill spam reagent imbued stuff.

**Comment by aKromatopzia** [comment]
> This balancing act partly reverts parts of skyrat's "Forging unleashed" PR (which also happened to allow imbues for station use) by bringing back the damage from reagent transferring. Meaning ghost roles used to have to deal with their reagent weapons slowly ticking up in damage as they were used.
> 
> This is the less extreme option.

I am aware, I'm saying it would be better to just re-restrict the content and make a skillchip or skill-based requirement for imbues again. Besides that, the weapon damage on successful injection isn't even all too bad.

> I know it's the primitive hammer - however, unlike your average spaceman, it's relatively easy for a newer ashie to pick it up, walk off, and bang, you gotta make a new one. Which also makes getting items themselves harder, but that's an entirely different can of worms. Please don't get so hostile towards critique; I am merely giving my opinion, not trying to start a rumble with you.

Also the hammer is like 5 iron sheets. Like... this is a non-issue.

**Comment by Majkl-J** [comment]
Cooldown effects removed, the effort needed with the new skill requirements makes this already a pain

**Comment by KeRSedChaplain** [comment]
As an ashwalker player I support this PR because 90% of ashie reagent equipmenthealing comes from reagent armor, not staves. I've never even seen anyone MAKE a staff to begin with because they're hot garbage for fighting the fauna over literally everything else we can make, and mindbreaker toxin swords are more than enough to game on a carbonmob target. I can also corroborate that the only increase in knowledge about chemistry I've gained with reagent forging in general is just how to get libital and aiuri(?) as an ashwalker and what chemicals actually work well when infused (GOD I WISH I COULD MAKE COFFEE + PROBITAL ARMOR AS AN ASHIE RAAAAAAGH!!!)

**Pull request merged**
