### PR TITLE
removes raptor borgs

### PR DESCRIPTION
**Pull request by tf-4**
## About The Pull Request

removes raptor borgs

## Why It's Good For The Game

they look really awful
like the sprites are REALLY bad
they look extremely out of place compared to everything else and the spritework itself is just straight up low quality

image

## Proof Of Testing

image

## Changelog
:cl:
del: Removed Raptor borg sprites
/:cl:

### CODE REVIEW

**Comment by ReturnToZender** [comment]
📞 my agents

**Comment by StrangeWeirdKitten** [comment]
No, why? Because they are immensely popular and we've already had contributions to make their sprite work better.

**Comment by StrangeWeirdKitten** [comment]
> Where are these sprite contributions? They're not on live and I don't see an open PR.
> 
> 
> 
> Also "this thing is popular" is really not a reason to keep something. It looks extremely out of place.

There's been sprite edits to raptor borgs. They are a very fresh addition.

Overall the biggest thing that can happen to them which we've discussed is shrinking their sprite size. But I'm not going to flat remove them over something very subjective and certainly is model to model. They are not perfect, and can be improved on, and have already shown some promise on that. Because at the end of the day, somehow raptor Borgs got pretty close to popularity as Vale.

**Comment by StrangeWeirdKitten** [comment]
> Where are the sprite edits? The only pr I can see is a sprite fix, which isn't really the same thing.
> Popularity is really a non factor. Something being popular doesn't make it look good and this is very representative of that. 

The sprite fixes done to them are considered part of maintaining their sprites.

I'm sorry TF-4, while I respect your input. I'm not going to arbitrarily shit on a bunch of Borg players over a sprite they themselves are picking, and playing solid characters around. Especially when just now people are bringing up their sprite concerns more directly, especially when myself included don't really find them that bad. They are mediocre, but remain distinct enough between each model. 

My only criticism with them comes down to them being a little flat when taking a closer look. But this can easily be fixed with a little extra shading.

**Pull request closed without merging**
