### PR TITLE
[UPSTREAM] [TM Only] Human AI, Veteran advisor and associated PRs

### PR DESCRIPTION
**Pull request by Swiftfeather**
## About The Pull Request

Upstream merge PRs: 
https://github.com/Skyrat-SS13/Skyrat-tg/pull/26823
https://github.com/Skyrat-SS13/Skyrat-tg/pull/26667
https://github.com/Skyrat-SS13/Skyrat-tg/pull/26720
https://github.com/Skyrat-SS13/Skyrat-tg/pull/26912

## Why It's Good For The Game

wooohooo human AI 

## Proof Of Testing

I'm gonna watch the test here and if it passes. This is my first upstream PR waterpig just taught me how to cherry pick n shit.

### CODE REVIEW

**Comment by IgiariValkyr** [comment]
Shouldn't this stuff be somewhere in #1293?

**Comment by Majkl-J** [comment]
```
code/__DEFINES/qdel.dm:22:warning: #warn TG0001 qdel REFERENCE_TRACKING enabled
loading interface/skin.dmf
modular_zubbers/code/modules/hydroponics/gene_modder.dm:376:error: issiliconoradminghost: undefined proc
modular_zubbers/code/modules/hydroponics/gene_modder.dm:386:error: issiliconoradminghost: undefined proc
code/datums/station_traits/job_traits.dm:212:error: department.remove_job: undefined proc
code/datums/station_traits/job_traits.dm:211:warning (unused_var): department: variable defined but not used
```

**Comment by Majkl-J** [comment]
> Shouldn't this stuff be somewhere in #1293?

We do not talk about that PR

**Comment by Swiftfeather** [comment]
> Shouldn't this stuff be somewhere in #1293?

I looked at all the PR titles and didn't see it.

**Comment by Swiftfeather** [comment]
> ```
> code/__DEFINES/qdel.dm:22:warning: #warn TG0001 qdel REFERENCE_TRACKING enabled
> loading interface/skin.dmf
> modular_zubbers/code/modules/hydroponics/gene_modder.dm:376:error: issiliconoradminghost: undefined proc
> modular_zubbers/code/modules/hydroponics/gene_modder.dm:386:error: issiliconoradminghost: undefined proc
> code/datums/station_traits/job_traits.dm:212:error: department.remove_job: undefined proc
> code/datums/station_traits/job_traits.dm:211:warning (unused_var): department: variable defined but not used
> ```

image

**Comment by nevimer** [comment]
just ask me to pull these from upstream and ill do it without you needing to make a PR, ill do it now

**Comment by nevimer** [comment]
actually I could just normal merge this and it will be chill

**Comment by Swiftfeather** [comment]
> just ask me to pull these from upstream and ill do it without you needing to make a PR, ill do it now

Just saving you time (and learned how to do it)

**Comment by Swiftfeather** [comment]
the only thing I wanna be sure I did right was our zubbers stuff here https://github.com/Bubberstation/Bubberstation/pull/1391/commits/0524e8357a2833f181861d8692c36f091d11f209

**Comment by Swiftfeather** [comment]
random integration tests stop failing challenge (impossible)

**Comment by Swiftfeather** [comment]
Upstream has been done, and there was much rejoicing as we absorb all the new bugs

**Pull request closed without merging**
