### PR TITLE
Ports Biodome from Orbstation

### PR DESCRIPTION
**Pull request by nevimer**
## About The Pull Request
Ports: https://github.com/lizardqueenlexi/orbstation/pull/454 by [Profakos](https://github.com/Profakos)
and all it's follow up PR's and fixes.

Biodome is an incredible map, with tons of character and polish. Originally created for [Orbstation](https://orbstation.space/), Biodome will surely be a beloved map here aswell. 

biodome_2

biodome_1

## Changelog

:cl:
add: Biodome map, ported from Orbstation! A large vacation themed map!
/:cl:

### CODE REVIEW

**Comment by BurgerLUA** [comment]
Only 3 issues I've spotted while playing.

There isn't many maintenance trash piles (the piles that everyone can loot once, for a delay) compared to other maps.

There is a bit of a balance issue with some areas of the station with respect to floor breaches. The upper level of the station overhangs a lot in some areas, dropping directly below to a space turf. This means if you fall, you're stranded in the middle of space, which can make it difficult for paramedics to revive you.

Another thing is that some high security areas on the lower floor, like the armory or the plasma tank in atmos, can be breached from above in some places.

**Comment by KathrinBailey** [comment]
My "does it fit standards" quality gripes so far are the prison's inconsistent usage of reinforced walls.
The interior of the prison should all be regular walls, and the connection points to space and the rest of the station reinforced.
Prison walls connecting prison rooms to other prison rooms should be regular walls.

There's a lot of whacky stuff here, but from a quick glance, that kinda stands out immediately.

**Comment by nevimer** [comment]
I'm merging so we can get on with PR's to improve it

**Comment by Zirok-BYOND** [comment]
https://github.com/Bubberstation/Bubberstation/actions/runs/5434999440/jobs/9883792498#step:10:59
This has lots of legitimate CI failures like this that should have been fixed before it was merged

**Comment by nevimer** [comment]
> https://github.com/Bubberstation/Bubberstation/actions/runs/5434999440/jobs/9883792498#step:10:59
> This has lots of legitimate CI failures like this that should have been fixed before it was merged

The only real one is an emission overlay for a map specific vending machine. Not a big deal, and other people wanted it merged so they could edit it.

**Comment by Profakos** [comment]
The leaves are indeed an eyesore, but only because they are codersprites and couldn't get around to fixing them. They are a sad necessity to divide up the air simulation of the open dome into more manageble chunks, without putting windows everywhere. The contrast between grass and the tiles is fair point, I should have used dark stone. 

The fake pits are there because that area is called The Grotto, and the escape area is meant to be a horrible tacky lazertag/gift shop area. It just got, uh, a bit large because the cargo shuttle would overlap with certain big shuttles otherwise.  

Also thank you KathrinBailey for pointing out the prison issue, I have fixed those walls now.

**Pull request merged**
