### PR TITLE
Changes the Arm Blade's stats to those of TG

### PR DESCRIPTION
**Pull request by KazooBard**
## About The Pull Request

The Arm Blade is remarkably weak despite being a staple weapon of the changeling. Thus, its stats change as following:
(Old)
   wound_bonus = -20
   bare_wound_bonus = 20

(New)
    wound_bonus = 15
    bare_wound_bonus = 10
    armour_penetration = 35

## Why It's Good For The Game
 
 Any crewmember can have a changeling tier weapon. Volt heart solves all EMP issues, and even if, not everyone has an EMP on them to fight. Weapons that can be mass produced to arm security should not make an antagonist's special thing look like a joke. (20 more AP and 40 more wound bonus, same damage, can even get more damage for less AP if you emag it)

Comparing it to the energy sword, another staple antag weapon a pattern can be easily seen: The difference between the two is 15 wound bonus to the side of the arm blade and 50 block chance to the side of the esword.

Now way more equivalent - one allows you to have essentially two projectile shields and the other lets you inflict grevious wounds. Antagonist weapons are expected to be about the same strenght for common ones, as seen by the fact the energy sword has the same AP as an armblade originally. 

I am confident this weapon is more fair considering  AP rounds and Fletchettes which are seen every round that make a joke of most antags. Then add up the fact of security number advantage, even with regular allstars, an implanted arm blade just better in getting combatants to retreat.

## Proof Of Testing

It compiles, it's 4 numbers changed and fiddling with indents for VSC to stop screaming at me

## Changelog

:cl:
balance: The arm blade's stats change to match other antag weaponry [0 ->35 AP, -20 ->15 WND, 20 -> 10 BWND)
/:cl:

### CODE REVIEW

**Review by StrangeWeirdKitten — APPROVED** [review]

**Comment by StrangeWeirdKitten** [comment]
There was a rebalance a year ago on TG and it seems we didn't get it

**Comment by KazooBard** [comment]
> There was a rebalance a year ago on TG and it seems we didn't get it. DNM until upstream is merged 

When do we usually merge upstream anyways? I'm out of the loop completely on that

**Comment by StrangeWeirdKitten** [comment]
https://github.com/Bubberstation/Bubberstation/pull/2220

This pulls the entirety of TG onto our codebase. So this PR might become irrelevant since the change may already be heading down

**Comment by KazooBard** [comment]
> https://github.com/Bubberstation/Bubberstation/pull/2220
> 
> This pulls the entirety of TG onto our codebase. So this PR might become irrelevant since the change may already be heading down

It looks to have not changed with the upstream

**Comment by StrangeWeirdKitten** [comment]
It's reset to TG now

**Pull request closed without merging**
