### PR TITLE
Adds the CheyTac Intervention from Modern Warfare 2

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Adds the CheyTac Intervention from Modern Warfare 2. I'm sick and tired of Syndicate noobs using overpowered .50 semi-automatic BMGs instead of using a real gun like the CheyTac Intervention from Modern Warfare 2. I am willing to fight on the Xbox 360 Rust 1v1 intervention only to get this PR merged.

Comes with an icon made by me.

image

Sound is something I ripped from the internet, so sorry for the bad quality.

## Changelog

:cl: BurgerBB
add: Adds the CheyTac Intervention from Modern Warfare 2
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
> Sound is something I ripped from the internet, so sorry for the bad quality

...was it an open sourced sound?

**Comment by BurgerLUA** [comment]
only one way to find out

**Comment by YakumoChen** [comment]
> only one way to find out

Don't PR copyrighted material?

**Comment by BurgerLUA** [comment]
> > only one way to find out
> 
> Don't PR copyrighted material?

it is sound mixed so I'm sure it counts as fair use as it is transformative.

**Comment by YakumoChen** [comment]
> > > only one way to find out
> > 
> > 
> > Don't PR copyrighted material?
> 
> it is sound mixed so I'm sure it counts as fair use as it is transformative.

If this is a serious comment I'm concerned for your outlook

"I remixed the sound slightly" is the same attitude as someone who recolours another person's hard worked sprite and passed it off as their own original creation.

You admit to ripping this sound off the Internet with no credit and play off someone's effort as your own.

**Comment by BurgerLUA** [comment]
honestly personally I think there are bigger issues with the sound that I chose than it potentially being copyright

**Comment by YakumoChen** [comment]
I don't know what could be a bigger issue than literal theft?

**Comment by BurgerLUA** [comment]
> I don't know what could be a bigger issue than literal theft?

Triple Homicide.

**Comment by Troontjelolo** [comment]
1_5yuEeuuCz89WGvaBQnqyzA

**Comment by nevimer** [comment]
I'd replace the HOS's guns with it TBH

**Pull request closed without merging**
