### PR TITLE
Adds Monkeydone, a chemical that transforms monkeys into humans.

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Adds Monkeydone, a chemical that transforms monkeys into humans. 

It can be made by mixing 10u Unstable Mutagen + 10u Mutadone + 1u Salt to make 1u Monkeydone. ~~Works best if salt is collected directly from heretic mains.~~

The inverse purity (50%) makes Monkey Energy. So that's how it's made!

CMO also gets a bottle of the stuff in their lockers.

## Why It's Good For The Game

Upstream removed the ability to turn monkeys into humans via mutadone. People did not like this.

## Proof Of Testing

Tested. Everything works.

## Changelog

:cl: BurgerBB
balance: Adds Monkeydone, a chemical that transforms monkeys into humans. It can be made by mixing 10u Unstable Mutagen + 10u Mutadone + 1u Salt to make 1u Monkeydone.
/:cl:

### CODE REVIEW

**Review by Majkl-J — CHANGES_REQUESTED** [review]
Whilst this is cool, there's no real way for 90% of players to know the recipe as most use the tg or skyrat wikies, and the limited supply being locked in the CMO locker. (Also the pills have the wrong reagent)

Options to fix this:
1. Revert the mutadone change back to the old functionality
2. Make some available in the nanomed, and provide some IC way to know the recipe.

**Comment by BurgerLUA** [comment]
> Whilst this is cool, there's no real way for 90% of players to know the recipe as most use the tg or skyrat wikies, and the limited supply being locked in the CMO locker. (Also the pills have the wrong reagent)
> 
> Options to fix this:
> 
> 1. Revert the mutadone change back to the old functionality
> 2. Make some available in the nanomed, and provide some IC way to know the recipe.

There are some that spawn in the CMO's closet.

**Comment by Arturlang** [comment]
Why not... bring back cloning? Make it cost something, some effort at least, but it only clones humanoid bodies with no minds.

**Comment by BurgerLUA** [comment]
> Why not... bring back cloning? Make it cost something, some effort at least, but it only clones humanoid bodies with no minds.

Out of the scope of this PR.

**Comment by Majkl-J** [comment]
> There are some that spawn in the CMO's closet.

It should be more accessible to average medical staff + this doesnt solve the issue of no way of knowing the recipe for 90% of players

**Comment by BurgerLUA** [comment]
> > There are some that spawn in the CMO's closet.
> 
> It should be more accessible to average medical staff + this doesnt solve the issue of no way of knowing the recipe for 90% of players

You can check the recipe for it in the chem dispenser. Much like some of the skyrat chems, all it takes is for knowledge of it to exist for people to start looking up the recipe for it via the chem dispenser and start using it.

**Comment by Iamgoofball** [comment]
what if you just used the genetics machinery in genetics

**Comment by BurgerLUA** [comment]
The problem with using genetics is that it requires genetics. Sometimes, people aren't playing genetics and genetics isn't even connected to medical anymore.

This is a good solution because it's still better to use genetics (if there is a geneticist), but if there isn't one, you can make this sort of tedious to make chemical that'd do it for you.

**Comment by Iamgoofball** [comment]
perhaps it should mean something if the station lacks a resource or job

**Pull request merged**
