### PR TITLE
No more money 4 u

### PR DESCRIPTION
**Pull request by ReturnToZender**
## About The Pull Request
No paycheck for you. Makes Assistants spawn with 200 credits and not get paid after that, to encourage their roles as "handymen."

## Changelog

:cl:
Add: Fistful o' dollars for Assistants
Add: Empty paycheck for assistants
Add: Empty paycheck for prisoners
/:cl:

### CODE REVIEW

**Comment by ReturnToZender** [comment]
> Don't the prison vending machines cost money?

Earn your dildo.

**Comment by ReturnToZender** [comment]
Hearing prisoners need money to actually buy plants, and well, function. As an average poor hater I must reluctantly give them 200 credits as well.

**Comment by MayumiBun** [comment]
I really don't think this is a good idea tbh. This is just forcing assistants and prisoners to do bounties which prisoners can't even do without security help (aka never). 
Just ruins potential gimmicks that cost money and forces them into a gameplay loop when we really should be encouraging rp over mechanic loops.

**Review by projectkepler-ru — COMMENTED** [review]
This is bad for gameplay, if you really need it you can lower the pay check even further but otherwise flat zero income is not ideal

**Comment by Cyprex** [comment]
This is a bad idea, especially with inflation and all that stuff. IC considerations cannot justify changes that are unfun OOC.

**Pull request closed without merging**
