### PR TITLE
Buffs Peacekeeper Borg Kit

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

This should be merged after #491, if at all.

Changes non-emagged Peacekeeper borg equipment to:
- **Pepperspray** (NEW)
- Flash
- Cookie Synth
- Harm Alarm
- Extinguisher
- Projectile Dampener
- **Pillow** (NEW)
- Hug Module
- Peace Hypospray

Changes emagged Peacekeeper borg equipment to:
- All of the above.
- Hacked Peace Hypospray
- **Zipties** (NEW)
- **Stun Baton** (NEW)
- **Sechailer** (NEW)

Reworks the Harm Alarm visual message.

## Why It's Good For The Game

Peacekeeper borgs should prevent/stop harm, but not perform arrests. This kit helps peacekeeper borgs do that while still being viable for traitors to fuck with.

## Changelog

:cl: BurgerBB
balance: Reworks peacekeeper borg equipment. Changes the harm alarm sound and visual text.
/:cl:

### CODE REVIEW

**Comment by Serxule** [comment]
why do peacekeepers need to be even stronger when they can already fully cuck anyone (through modsuits afaik) with a single click (pax injector)

**Comment by YakumoChen** [comment]
Gonna be real with you homie 

Giving stamina-damaging weapons (flash notwithstanding) to the no-slowdown borg that can inject juice to prevent you from harming it makes it unironically stronger than secborgs

**Comment by YakumoChen** [comment]
Also I believe pk borgs already have a ton of emag functionality (it buffs almost every module)  and this kinda encourages security to emag the pkborgs?

**Comment by Serxule** [comment]
> Also I believe pk borgs already have a ton of emag functionality (it buffs almost every module) and this kinda encourages security to emag the pkborgs?

dont forget, illegal module is gotten fairly early on (atleast 1 hour mark) which unlocks said tech without emagging

**Comment by Kraseo** [comment]
What is this PR and why did you choose to buff the strongest cyborg module out of nowhere?

The peacekeeper toolkit is already one of if not **the** strongest anti-antag toolkits. Even without a disabler or stunbaton they can still shut down someone very fast by dumping pax into them.

When emagged, they already get a stun-baton by using the hug module (which I have to mention, alongside the disabler and pepperspray you decided to haphazardly give them would devastate either side playing against a peacekeeper). I'm not sure why you're also giving them a full secborg kit when they unlock illegal modules (again, including a disabler because ?????), but to me this shows a clear lack of research and/or care for balance.

This is an entirely unnecessary change. Reconsider this.

**Comment by YakumoChen** [comment]
My favourite part of this PR is where burger copy-pasted the harm alarm code, glossed over the part where the emag'd one gives a *four second hardstun*, and then gave the borg a disabler too.

**Comment by StrangeWeirdKitten** [comment]
Emagged Peacekeeper already has a lot of powerful stuff. They don't need a full security kit. I'll be honest, if you figured out how to move the security borg sprites over to peacekeeper with an upgrade, a lot of people will be sated.

> why do peacekeepers need to be even stronger when they can already fully cuck anyone (through modsuits afaik) with a single click (pax injector)

Synthpax lasts a really short time and they require the piercing hypospray upgrade (under medical) to do this.

**Comment by BurgerLUA** [comment]
> My favourite part of this PR is where burger copy-pasted the harm alarm code, glossed over the part where the emag'd one gives a _four second hardstun_, and then gave the borg a disabler too.

Per feedback above, it appears that I have made a mistake in terms of making the Peacekeeper borg too powerful.

As a compromise, I have removed the pillow as that pushed the power of the Peacekeeper borg to a "too powerful" status.

**Comment by Kraseo** [comment]
I don't want compromise. I want this PR closed.

There is NO reason whatsoever to kit out peacekeeper cyborgs even more than with what they already have. There is absolutely no way you looked at peacekeepers and decided it was wise they should get pepperspray, let alone a disabler, stun baton, and cuffs with illegal modules.

The point of peacekeepers is to co-ordinate with security (or other cyborgs) to take down antags (or otherwise) as non-lethally as possible. That's the point of their pax. That's the point of their tirimol. 
Giving them the tools to shut down anyone solo goes against their design entirely.

This reeks of troll PR.

**Comment by GrayRachnid** [comment]
As a peacekeeper main for a very very long time, this is a bad PR.

1) Removing the hypo
This removes the whole point of the peacekeeper? Why?
2) Adding the pepperspray
If this is replacing the hypo, i t's bad. If this is being added on its own it's unnecessary because of the flash
3) Giving it a whole secborg kit when emagged
As was said above, illegal modules are like candy for science and are gotten every round. This makes no sense and you're already making a well-rounded borg(get it, it's an egg) much stronger for no reason.

All in all, this PR does is toss the sunny side up of the peacekeeper borg into a fried mess that makes no sense. There's no reason for these changes.

**Comment by BurgerLUA** [comment]
it is actually legitimately wild that people are freaking out about this pr

**Comment by GrayRachnid** [comment]
> it is actually legitimately wild that people are freaking out about this pr

I have no idea who you're referencing, I'm simply posting my own point of view!

**Comment by BurgerLUA** [comment]
> > it is actually legitimately wild that people are freaking out about this pr
> 
> I have no idea who you're referencing, I'm simply posting my own point of view!

not you but

>I don't want compromise. I want this PR closed.

>this is literally just changing peacekeeper into a secborg, (kindly) fuck off

>This reeks of troll PR.

>My favourite part of this PR is where burger copy-pasted the harm alarm code, glossed over the part where the emag'd one gives a four second hardstun, and then gave the borg a disabler too.

like actual legitimate crybaby nonsense, if you don't like a change, calmly provide feedback instead of going full baby mode

**Comment by BurgerLUA** [comment]
> > like actual legitimate crybaby nonsense, if you don't like a change, calmly provide feedback instead of going full baby mode
> 
> call it whatever you want if you're gonna have a tantrum like this, but all of these are factual feedback, you dont have to like how they're worded but dont call other people "crybabies" because they disagree with you (and give actual reasoning) for making a borg even more OP, also that you took single sentences ooc from posts that had a lot of feedback, bad faith much?

I have adjusted the PR several time as a response to factual feedback. 

Calling the pr a troll pr or telling people to fuck off is not feedback. Don't even try it.

**Comment by Serxule** [comment]
> I have adjusted the PR several time as a response to factual feedback. Calling the pr a troll pr or telling people to fuck off is not feedback. Don't even try it.
> 
> Generally if you give feedback and then act hostile for no real reason in the middle of your sentence then I'm just going to ignore it. I don't get paid to listen to people act up so it's not worth my time to read the rest of the nonsense.

since you cant seem to see anything other than being insulted let me reword everything to be nice and wholesome and family friendly for your christian github PR:

Peacekeeper borgs are meant to reduce/stop **_harm_**, not to arrest/detain/etc threats, thats security/secborgs job, removing the peacekeeper borgs unique items and giving it multiple security items turns it into a reflavored secborg which was/is being removed for the exact reasoning of what will be said next, borgs should not be able to solo threats/antags alone nor should they be a be all end all, like the secborg was, the peacekeeper already gets two hardstuns when its emagged/illegal moduled and since illegal tech (including the illegal module) is researched every round, this would make peacekeepers a meta pick borg as they would be incredibly powerful, moreso than they already are by having pax.

**Comment by BurgerLUA** [comment]
Hypospray was readded. The OP and git message displayed this quite a bit before you wrote all that and I think you would've noticed this if you weren't here just to flame.

**Comment by BurgerLUA** [comment]
> > like actual legitimate crybaby nonsense, if you don't like a change, calmly provide feedback instead of going full baby mode
> 
> I've provided feedback. This PR is unnecessary and so far the vast vocal majority agrees with this. You can go ahead and block me like you've blocked everyone else who has mildly disagreed with every other one of your PRs so they can't provide feedback.

I've been blocking his accounts not because I disagree with him but rather the fact that he's (so far) used at least 3 accounts to be inflammatory on github for no real reason for I think stuff that happened at citadel 5 years ago.

The fact that he's unironically going around and telling people that I blocked them just depresses me.

**Comment by GrayRachnid** [comment]
The stunbaton on emag is noobbait considering the 2 hardstuns they already have that are much stronger. The zipties just make them secborg 2.0.

**Comment by BurgerLUA** [comment]
I'm getting conflicting opinions in this PR (stun baton good, stun baton bad) and I don't know which one to agree with, so I'm leaving it up to devs.

**Comment by GrayRachnid** [comment]
I get the feeling you made this PR without exploring the current, full, potential of peacekeeper borgs.

Un-emagged, peacekeepers get the following:
-Cyborg flash which knocks down anyone without eye protection
-PK Hypo which has synth-pax(underrated), dizzying solution, tiring solution(slows you down, does not stun)
-Harm Alarm (confuses everyone)
-IMPROVED barriers that block projectiles and force people to walk
-A big fire extinguisher for 10 brute damage per attack.(underrated)

Emagged peacekeepers get the following:
-The emagged hypospray from mediborgs ontop of their own(I don't need to explain how strong that is)
-Improved harm alarm that floors people, stunning them
-IMPROVED IMPROVED barriers that shock people on touch
-Shock hug(hardstuns on contact) and crushing hug(does like 20? brute damage)

Knowing this arsenal that they have right now, it makes no sense to give them a stunbaton when shock hugs are better.

I don't care much for pillows but I'm assuming they do stamina damage? That's whatever, I would've knocked people out with a fire extinguisher if I had to anyways. If you add the pillow to them then you're just giving the ability to drag people to the brig without being emagged(not their job).

The zipties are just a breach of cyborg balance, giving silicons the ability to cuff humans when they shouldn't have it in Tg's version of silicon balance is just weird. If the devs approve of it anyways then that's their call, but I think it's too strong. Especially when the borg can just kill you.

**Comment by Detective-Google** [comment]
cuffs for emagged borgs are good, disabler and stun  baton are definitely a no(especially since they get a stun when emagged anyway). 

Pillow is cute but I worry since borgs dont have stamina(one of the main downsides of the pillow is that it also fucks your stamina) it will be used to just stamcrit people without using charge. 

pepperspray is also neat assuming it has a very limited capacity- like 3-4 sprays, a big downside of the pepperspray normally is that using it while chasing people/in general you're risking spraying yourself.

however, I also think gray's point is valid and peacekeepers are already really strong and don't need to be further buffed at all.

**Comment by Detective-Google** [comment]
> > > like actual legitimate crybaby nonsense, if you don't like a change, calmly provide feedback instead of going full baby mode
> > 
> > 
> > I've provided feedback. This PR is unnecessary and so far the vast vocal majority agrees with this. You can go ahead and block me like you've blocked everyone else who has mildly disagreed with every other one of your PRs so they can't provide feedback.
> 
> I've been blocking his accounts not because I disagree with him but rather the fact that he's (so far) used at least 3 accounts to be inflammatory on github for no real reason for I think stuff that happened at citadel 5 years ago.
> 
> The fact that he's unironically going around and telling people that I blocked them just depresses me.

can you provide any evidence for this

**Comment by Detective-Google** [comment]
> I'm getting conflicting opinions in this PR (stun baton good, stun baton bad) and I don't know which one to agree with, so I'm leaving it up to devs.

I scrolled through and didn't see any "stun baton good" comments but maybe I'm just blind. although, as a reminder, they get stuns anyway so it's kinda irrelavent.

**Comment by BurgerLUA** [comment]
#504 should be merged before since people think illegal modules are too hard for the crew to obtain

**Comment by BurgerLUA** [comment]
> I scrolled through and didn't see any "stun baton good" comments but maybe I'm just blind. although, as a reminder, they get stuns anyway so it's kinda irrelavent.

>There is NO reason whatsoever to kit out peacekeeper cyborgs even more than with what they already have. There is absolutely no way you looked at peacekeepers and decided it was wise they should get pepperspray, let alone a disabler, stun baton, and cuffs with illegal modules.

> The stunbaton on emag is noobbait considering the 2 hardstuns they already have that are much stronger. The zipties just make them secborg 2.0.

One says stun baton is strong, one says stun baton is pointless.

**Comment by YakumoChen** [comment]
> One says stun baton is strong, one says stun baton is pointless.

Both opinions equate to "don't give them a baton" however?

**Comment by YakumoChen** [comment]
> #504 should be merged before since people think illegal modules are too hard for the crew to obtain

They really aren't, the syndie crate pod is a very common event, notwithstanding traitors being in the round in general.

**Comment by GrayRachnid** [comment]
I'll amend that the pillow is hilarious but I still think it's overpowered considering it uses no charge.

**Comment by chemistrymain2** [comment]
Peacekeeper cyborgs are already incredibly lethal when emagged. They really don't need a gun.

Cyborgs with guns are almost always a bad idea.

**Comment by BurgerLUA** [comment]
> Peacekeeper cyborgs are already incredibly lethal when emagged. They really don't need a gun.
> 
> Cyborgs with guns are almost always a bad idea.

Just a question, what made you think they get a gun?

**Comment by DeerJesus** [comment]
No batongs please.

**Comment by YakumoChen** [comment]
> Just a question, what made you think they get a gun?

Burger, your commits and edits to the OP are publicly logged.

**Comment by BurgerLUA** [comment]
> > Just a question, what made you think they get a gun?
> 
> Burger, your commits and edits to the OP are publicly logged.

Ok but disablers were removed from the PR quite a bit ago. That was updated in the OP and commit history.

**Comment by Detective-Google** [comment]
as it is now, PR looks fine I think, stun baton is kinda ??? when the grab hardstuns but having two modules doing mostly the same thing is more or less a nonissue.

Only other thing I'd suggest is making the pillow use charge similar to the stun batons on secborgs currently, given normally the downside to pillows is that they drop your stamina almost as much as the person you're hitting.

**Comment by destrucktoid** [comment]
This change is really unnecessary, all it does is try to turn the peacekeeper borg into yet another security borg by giving it more offensive tools. The idea behind the peacekeeper borg is to _protect people and keep the peace_. They should not be going around batonning valids, they should not be going around pillowing valids (as funny as the idea is, we both know it's just going to be used as a 5 or so hit stun baton) and they should not be going around pepperspraying valids. The tools they already have are more than enough for them to do their job in keeping the peace and protecting the crew as a whole, rather than just being a silicon security officer. Furthermore the emagged module already gives them a hardstun in the form of the hugging module and the zipties are completely unnecessary and just encourage a security borg playstyle. 

It's my opinion that this is intended to be a PR to make the peacekeeper borg into a security borg 2.0. Whilst yes, the disabler has been removed from this PR as well as a bunch of other things, the fact remains that the original intent of this PR (from what i can see) was to change the peacekeeper into a security borg with a different name. The peacekeeper borg kit is already strong enough and good enough for what it needs in keeping the peace and trying to talk to and protect people. Adding offensive tools just encourages validhunting and a more security-esque playstyle.

**Comment by nevimer** [comment]
this to me is just secborg with a worse skin..

**Comment by BurgerLUA** [comment]
> this to me is just secborg with a worse skin.. Pillow is a good add too. Same for harm alarm

I can move the pepperspray to emag tier. Would that be fine?

**Comment by BurgerLUA** [comment]
cum

**Pull request closed without merging**
