### PR TITLE
[MODULAR] contractor kit random item shuffle

### PR DESCRIPTION
**Pull request by zeroisthebiggay**
## About The Pull Request

Removes a lot of the useless or otherwise bad items from the list of random utility items that contractors can get when they spawn and replaces them with usually-considered 'good' items, hopefully aiding contractors in not getting immediately dogged on when they spawn because they rolled mulligan radlaser sentience potion, all of which being items with very little use for them.

ITEM EXPLANATIONS

PHILOSOPHY - Contractors wear a big, bulky MODsuit that screams `I'M VALID KILL ME I HAVE BIG LOOT AND MY HUGE COCK DEMANDS YOU FIGHT ME`, yet a lot of the random items that are intended to aid their otherwise vulnerable early game are tailored towards stealth and not being caught. Contractors are fundamentally not designed to be playing the stealth game when their starting equipment is all very sharply branded as Syndicate manufactured.

Obviously, you can supplement a bad starting suite with your paltry thirteen TC starting funds, but it doesn't change the fact that a contractor who got rubbish for their starting suite is going to be doing much worse than one who got an eshield, medkit, and emp kit; all of which easily being A or S grade items on the tier list. Lots of the 'good' items aren't even available in the uplink to boot, meaning if you didn't get them, you're missing out on a decent amount of power.

REMOVAL - Dartgun - This thing's pretty good for when you're doing chemical warfare, but contractors have no easy access to chemicals outside of spending their precious TC on a poison kit. Even still, it's a gimmick.
REMOVAL - Energy Dagger - Contractors get a combat knife that has similar force values to the energy dagger. As a stealth item meant to be concealed, that facet is almost useless to contractors.
REMOVAL - Sleepypen - See the above reason with the energy dagger. It's a stealth item meant to incapacitate people quietly, but you're honestly just better off two-tapping them with your stun baton and silencing them using the radio jammer you always spawn in with.
REMOVAL - Mulligan - There's very little reason to change your identity when you're wearing a fully-concealing MODsuit. Most people would rather be their OC than a randomgen human anyways.
REMOVAL - Sentience Potion - This item is so niche in its use that it's honestly baffling TG ever added it to the contractor items list. There's a chance xenobio has a fugu glanded migo for you to make your battlebeast, but more than likely you're stuck with a space carp as your very best option. Underwhelming as fuck.
REMOVAL - Radio Implant - You spawn with a radio. This is simply worthless.
REMOVAL - Tackle Gloves - Your gloves slot doesn't matter when wearing the contractor MODsuit, and you already spawn in with combat gloves.
REMOVAL - Rad Laser - See sleepy pen issues.

ADDITION - Noslips - A very cheap utility item that is normally a pretty good get. It's even apart of the normal contractor items list; it's just that good. Shuts down lots of greytide fuckery and enables slip abuse for yourself risk free. Generally great in all situations.
ADDITION - Stealth Implant - The second-most expensive on the list of contractor items, sitting just behind the energy shield. One of the greatest ways to sneak around corridors without getting spotted and makes for an easy getaway if you turn a corner before your pursuers. Thematically the best stealth item for contractors as it's useful both in and out of direct combat.
ADDITION - Cryptographic Sequencer - Way less valuable now that it's no-longer a door opener. Adds a third item to the list that directly combats cyborgs trying to validhunt you, and is arguably the best as it directly turns them against the crew.
ADDITION - Airlock Override Card - A faster-working but more situation Syndicate jaws of life. Useful for whatever you may have, just like its alternative. Bogus if you get both of them, though.
~~ADDITION - Advanced Jetpack - Easily the most experimental of all the additions. It's unmatched in space combat and makes you practically unapproachable should you choose to prioritize it over fighting on the station. Since it's situational and you're most likely not going to be doing a whole lot of actual contracting from the outside, I personally think it's fair to allow contractors to occasionally have a direct advantage in space.~~ i had a better idea that this could probably just be available through the contractor uplink which is barely used as is

## Changelog

:cl:
balance: shuffled contractor's random items to remove some of the more useless options and add better ones
/:cl:

### CODE REVIEW

**Comment by Detective-Google** [comment]
Sleepypen and radlaser are honestly probably fine to stay, -1 on the advanced jetpack, contractors spawning with a normal jetpack is definitely reasonable/good but jetpacks are already a crew upgrade and unless it's already a high chaos round security should have the opportunity to eventually match if they spend the time going to robotics.

**Comment by zeroisthebiggay** [comment]
> Sleepypen and radlaser are honestly probably fine to stay, -1 on the advanced jetpack, contractors spawning with a normal jetpack is definitely reasonable/good but jetpacks are already a crew upgrade and unless it's already a high chaos round security should have the opportunity to eventually match if they spend the time going to robotics.

i'd honestly like to see a testmerge and see how it pans out. the advanced jetpack is balanced around the fact that contractors have no real advantage to be gained in space other than evasion since all their objectives are generally stationside

ig they can cause a little bit of chaos if they just ignore being a contractor

idk maybe i'll have a eureka moment and realize it's incredibly unbalanced in my sleep

**Comment by Serxule** [comment]
the adv jetpack is a good thing, people really love trying to validhunt in space, especially with caps modsuit (which has an adv jetpack), even though contractors should be moreorless safe in space since they cant do much out there other than evade

**Comment by zeroisthebiggay** [comment]
> the adv jetpack is a good thing, people really love trying to validhunt in space, especially with caps modsuit (which has an adv jetpack), even though contractors should be moreorless safe in space since they cant do much out there other than evade

it's incredibly strong. there's no beating around the bush but also you can just kinda ignore any contractor in space because tbh they're just not worth it

it's only a chance to get the advanced jetpack and you could say the same `it's fucking busted strong` to things like the eshield since it just invalidates most of security's ranged options

**Comment by zeroisthebiggay** [comment]
after consideration i've decided to remove the advanced jetpack from the pool under the pretense that maybe later i'll add it as an alternative to the scorpion hook as a powerful and very expensive late game MODsuti upgrade from the contractor uplink

**Review by BurgerLUA — APPROVED** [review]
Code looks good.

**Comment by zeroisthebiggay** [comment]
someone'll look here eventually

**Pull request closed without merging**
