### PR TITLE
[Non-Modular] Reverts changeling balance back to TG

### PR DESCRIPTION
**Pull request by ReturnToZender**
## About The Pull Request
Deletes edited Skyrat ling stats.

## Why It's Good For The Game
Lings, as they are, even with limits, are able to spawn up to 3 times in a shift, with much more cracked abilities than they reasonably should have. This PR does nothing about the first issue, but returns them to TG values.

## Changelog

:cl:
Del: Skyrat edits buffing lings
/:cl:

### CODE REVIEW

**Comment by Cyprex** [comment]
armblade also has increased wound_power

**Comment by Oscari-pog** [comment]
Wouldnt just somewhat nerfing them rather than reducing them to TG stats be better considering the fact that security has way more tools to deal with them, notably weapons? TG security gets Laser Guns, Energy Guns, and Riot Shotguns. Skyrat security gets PDWs (With special ammo types), MCRs (good only at T4 parts, but still can get cracked with specific loadouts), and Peacekeeper Shotguns (With special shells, some of which are outright direct upgrades). HoS also gets a special gun, and this isnt mentioning what the crew and security can buy from cargo.

**Review by KathrinBailey — APPROVED** [review]
It's an improvement.

**Comment by ReturnToZender** [comment]
> I feel like returning changeling stats to TG values is unfair UNLESS you also plan on nerfing security. As someone mentioned above, Skyrat sec has access to much more powerful gear than its upstream counterpart.

I do, I have done so before, and I will do so again 😈

**Comment by DerFlammenwerfer** [comment]
> > I feel like returning changeling stats to TG values is unfair UNLESS you also plan on nerfing security. As someone mentioned above, Skyrat sec has access to much more powerful gear than its upstream counterpart.
> 
> I do, I have done so before, and I will do so again 😈

I'd like to recommend having a security nerf PR up on a separate branch that way both can be introduced and TM'd side by side.

**Comment by nevimer** [comment]
this skews the balance too wildly

**Comment by ReturnToZender** [comment]
> this skews the balance too wildly
is that a 😄 or a ☹️

**Comment by nevimer** [comment]
there is a merge conflict

**Comment by StrangeWeirdKitten** [comment]
I don't think changeling needs balance changes at this moment.

**Comment by StrangeWeirdKitten** [comment]
Yeah I'm reconsidering this

**Comment by StrangeWeirdKitten** [comment]
https://discordapp.com/channels/1059199070016655462/1071095123145924679/1168124458939203665 is the feedback thread

**Pull request merged**
