### PR TITLE
Shading + slight recoloring of Valeborgs

### PR DESCRIPTION
**Pull request by HometownFunky**
## About The Pull Request

Alright so I'm not the best spriter but someone mentioned how valeborgs were very flat colorwise. They had 0 depth and I tried giving them just that. There were also a few oddities like the janitor valeborg looking exactly like mining one, so I made them a bit distinct. The medical one had some teal accents that were again, odd and not really in line with the other medical cyborgs so I changed those too.

Tested this on a local host and it works (miraculously). It should(tm) work here too.

## Why It's Good For The Game

It should make them more in line with the rest of the sprites, or at the very least nudge them in that direction.

## Proof Of Testing

Valeborgs

## Changelog

:cl:
image: added shading to valeborg sprites and updated the colors for the vale jani/medical models.
/:cl:

### CODE REVIEW

**Review by Majkl-J — CHANGES_REQUESTED** [review]
Either take it upstream to Skyrat (And refer the PR here), or make the new icons in our modular folder and override it.

**Comment by HometownFunky** [comment]
Apologies, very new to this. Basically I place the dmi files in the bubber modular folder (and edit the paths) or pr it to skyrat, yes?

**Comment by Majkl-J** [comment]
> Apologies, very new to this. Basically I place the dmi files in the bubber modular folder (and edit the paths) or pr it to skyrat, yes?

Yup to both, personally I'd suggest going to Skyrat, I really like the work you did and am pretty sure they'll do too + you don't have to deal with modular overriding and whatnot

**Comment by HometownFunky** [comment]
Alrighty, I'll close this one now and PR it there!

**Comment by ReturnToZender** [comment]
This is good, excited to see it here.

**Pull request closed without merging**
