### PR TITLE
It's eternity in there, Briefcase Launchpad available again

### PR DESCRIPTION
**Pull request by projectkepler-ru**
## About The Pull Request
Added backhand teleporter and briefcase launch pad to traitor uplink
[The Hand Teleporter](https://en.wikipedia.org/wiki/The_Jaunt) is a device  allowing you to teleport 5 tiles infront of you, should it be a wall, it'll attempt to displace you into the nearest open tile, otherwise, you will immediately die if it fails to find a valid spot.

## Why It's Good For The Game
I asked zirok about adding back stuff skyrat removed and these two were things I feel like were extremely important to stealth antag gameplay, and, seeing we will have much more equipped security than usual? We can afford to have this

## Changelog

:cl:
balance: Readds the traitor bluespace launchpad.
/:cl:

### CODE REVIEW

**Comment by OceanFish1** [comment]
With progtots? Yeah, but withought them? What's the point? Bully security until they cryo?

**Comment by projectkepler-ru** [comment]
> With progtots? Yeah, but withought them? What's the point? Bully security until they cryo?

@StrangeWeirdKitten

**Comment by Detective-Google** [comment]
briefcase launchpad is a classic item with well balanced pros and cons whereas the hand tele is just a regenerating bluespace crystal and is absolutely miserable to deal with- to the point skyrat removed it because the only real solution to dealing with it is immediately gunning the person down. in other words, +1 to launchpad readd, -1 to hand tele add

**Comment by Weblure** [comment]
Definitely add the briefcase launchpad back, Skyrat had literally no valid reason to remove it. They just went "we're removing this because we don't like it and no we don't want your feedback" and that was that.

**Comment by Weblure** [comment]
> the hand tele is just a regenerating bluespace crystal and is absolutely miserable to deal with

Sounds like there's a pretty significant difference between them, though.

Bluespace crystals:
- Limited quantity
- Teleports you a random distance in a random direction (Making it hard to use strategically)
- May teleport you into a wall, space, or other hazards
 
Bluespace stunprod:
- Rechargeable, can be upgraded to be used dozens of times on a single charge
- Teleport you a random distance in a random direction (Making it hard to use strategically)
- May teleport you into a wall, space, or other hazards
- Can be used on yourself or others
- A stun effect is applied, both to yourself and others (Making it an ineffective escape tool)

Hand Teleporter:
- Infinite(?) use (and I assume it's on a cooldown?)
- Teleports you directly forwards by 5 tiles
- Will not teleport you into walls but...
- Will instantly RR you if there's no valid teleport location

The hand tele sounds like a very high risk, high reward item, but I'm not sure if it's balanced in a way that's very fun for either party. I've never used it or seen it used before, but from the sound of it, it seems like a tool that helps you be nearly uncatchable, until you suddenly and randomly die from bad luck. Chasing someone that can instantly and strategically teleport through walls isn't very fun for security, and instantly dying to RNG isn't fun for the antagonist, plus neither outcomes are very conductive to roleplay.

The briefcase is fine because it requires genuine stealth gameplay. You can't hide it in your backpack, it's very conspicuous when deployed, it's noisy when used, and it takes a lot of time and planning to execute. You also can't go any further than 7 tiles and it gets left behind when you to teleport, making it a lot harder to get into highly-secure areas with it. The hand tele, on the other hand, just sounds like a cheat version of an airlock emag that bypasses R-walls, bolted doors, and double doors in a single use while not leaving any traces behind, and can be used again and again to get deeper and deeper into any part of the station.

**Comment by destrucktoid** [comment]
> > the hand tele is just a regenerating bluespace crystal and is absolutely miserable to deal with
> 
> Sounds like there's a pretty significant difference between them, though.
> 
> Bluespace crystals:
> 
> * Limited quantity
> * Teleports you a random distance in a random direction (Making it hard to use strategically)
> * May teleport you into a wall, space, or other hazards
> 
> Bluespace stunprod:
> 
> * Rechargeable, can be upgraded to be used dozens of times on a single charge
> * Teleport you a random distance in a random direction (Making it hard to use strategically)
> * May teleport you into a wall, space, or other hazards
> * Can be used on yourself or others
> * A stun effect is applied, both to yourself and others (Making it an ineffective escape tool)
> 
> Hand Teleporter:
> 
> * Infinite(?) use (and I assume it's on a cooldown?)
> * Teleports you directly forwards by 5 tiles
> * Will not teleport you into walls but...
> * Will instantly RR you if there's no valid teleport location
> 
> The hand tele sounds like a very high risk, high reward item, but I'm not sure if it's balanced in a way that's very fun for either party. I've never used it or seen it used before, but from the sound of it, it seems like a tool that helps you be nearly uncatchable, until you suddenly and randomly die from bad luck. Chasing someone that can instantly and strategically teleport through walls isn't very fun for security, and instantly dying to RNG isn't fun for the antagonist, plus neither outcomes are very conductive to roleplay.
> 
> The briefcase is fine because it requires genuine stealth gameplay. You can't hide it in your backpack, it's very conspicuous when deployed, it's noisy when used, and it takes a lot of time and planning to execute. You also can't go any further than 7 tiles and it gets left behind when you teleport, making it a lot harder to get into highly-secure areas with it. The hand tele, on the other hand, just sounds like a cheat version of an airlock emag that bypasses R-walls, bolted doors, and double doors in a single use while not leaving any traces behind, and can be used again and again to get deeper and deeper into any part of the station.

The problem is that syndies lack any form of easy escape. It's all well and good saying it hurts roleplay to have the hand teleporter, however the problem is that roleplaying as an antagonist always results in you getting caught because security just slowly groups up around you till at the end of your conversation it's a 1v5. The hand teleporter is there to help you escape that. Changelings have escape options in the form of their abilities, EMP to disable stun batons as well as fleshmend, armor and changeling haste. Heretics have teleport spells and jaunts, cult has teleportation, abductors have teleportation, clock cult USED to have teleportation (RIP reebe), point being antagonists need a disengage mechanic, for traitors handheld teleporter WAS that disengage mechanic.

**Comment by YakumoChen** [comment]
Description is not accurate, hand tele should be described as it is
"A handheld device that teleports the user 4-8 meters forward."

Aside from this, the hand tele needs some VERY heavy handed nerfs, as someone who used it before. 

The recharge time needs to be upped significantly, like 30 seconds per charge at minimum, and three charges at most. This brings it closer to the likes of Ninja sword or doormag to at least give your pursuer a window to more easily catch you.

**Review by Majkl-J — COMMENTED** [review]
This needs a further balance discussion regarding the hand teleporter.

**Review by StrangeWeirdKitten — CHANGES_REQUESTED** [review]
I've made a decision, and the hand teleporter is not coming back. The only reason why this item is being considered is because there's a possibility to be instantly gibbed. 

If an items balance is surrounded by the possibility to instantly gib you, that item is fundimentally bad. 

The briefcase launchpad is fine, but keep the hand teleporter commented out.

**Comment by StrangeWeirdKitten** [comment]
I've made the changes, this is merge ready

**Review by StrangeWeirdKitten — APPROVED** [review]

**Pull request merged**
