### PR TITLE
The Ash Swordsman

### PR DESCRIPTION
**Pull request by KeRSedChaplain**
## About The Pull Request
Adds in a craftable kinetic crusher for the ashwalkers, available after the cursed knife ritual. Same stats as the regular crusher, but with 5 extra armor penetration (from the 10 AP the regular one has)

## Why It's Good For The Game
I just thought it'd be a neat addition, considering the current lavaland fauna is balanced around miners with all their fancy tools and equipment, with ashwalkers being a bit of an afterthought to the mob changes. Hopefully, this should alleviate a bit of the annoyance of fighting the fauna as one.

## Proof Of Testing
It compiles just fine, and code-wise it's just an edited kinetic crusher. The sprites appeared to render just fine, but due to my lack of artistic skill the onmob icons aren't the highest of quality.
image

## Changelog

:cl:
add: Adds the Necropolis Greatsword, an ashwalker variant of the kinetic crusher.
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
Our upstream is already adding an ashwalker crushers so this will soft conflict with the upstream

**Comment by KeRSedChaplain** [comment]
Would it be a good idea to make this into an upgrade of the one upstream's adding? Or just wait for it to come down and then make edits to the one added?

**Comment by YakumoChen** [comment]
I'm not sure why ashwalkers need to have an upgraded one? Ashwalkers in general are already quite strong.

**Comment by Erol509** [comment]
> Would it be a good idea to make this into an upgrade of the one upstream's adding? Or just wait for it to come down and then make edits to the one added?

you can try for TM, and then replace the one arriving from upstream if you like to

**Review by Majkl-J — COMMENTED** [review]
I'm putting this on hold due to the new smithing PR on skyrat. See #26729

**Comment by KeRSedChaplain** [comment]
want me to close it for the moment, then? Or just leave it open for now

**Comment by YakumoChen** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/26730

**Comment by Majkl-J** [comment]
> want me to close it for the moment, then? Or just leave it open for now

Leave it open until we see what skyrat does

**Comment by Superhats** [comment]
The skyrat PR has been in dev hell for 30 days 🥺

**Comment by KeRSedChaplain** [comment]
Would a TM be possible so I can gauge whether or not I should make the sword function differently to a regular crusher? I have ideas but I'm just unsure how much it'll affect ashies as-is, and the upstream PR has been marked as stale twice

**Comment by KeRSedChaplain** [comment]
the upstream PR's been merged over there, pog

**Comment by KeRSedChaplain** [comment]
Gonna close this for the moment until I decide on another way to implement at least the sprite

**Pull request closed without merging**
