### PR TITLE
Re-add and update Kilostation

### PR DESCRIPTION
**Pull request by ChakatStormCloud**
## About The Pull Request
Adds Kilostation back in, fully reverting it's deletion and adding it in as a bubber map.

I've fully brought Kilo up to date and added in the coroners office and bitrunner's den as best as I could, as well as adding a smattering of those fancy new digital clocks, and bandaids. As far as I can tell it's ready to go.

And I figure 75 is a good max player count for Kilo, it **is** pretty cramped, could do 80 though maybe.

## Why It's Good For The Game
Kilostation is an amazing lowpop map and is well loved, and didn't deserve to be killed off.
This will add a new map to use during low-pop other than birdshot and voidraptor.

## Changelog
:cl:
add: Re-added Kilostation
add: Bitrunner Den and Coroners office crammed into Kilostation
fix: More things than I care to list to get Kilo up to date
fix: Aligned Kilo's arrival dock with both shuttle doors.
config: Made Kilostation voteable up to a max player count of 75 by default
/:cl:

### CODE REVIEW

**Comment by Majkl-J** [comment]
Above 50 it will be cramped

**Comment by nevimer** [comment]
> Above 50 it will be cramped

We have configs for that

**Comment by ChakatStormCloud** [comment]
> Above 50 it will be cramped

It originally had **no** max limit by default, and the only station that does have a max is birdshot with 66.
So I figured it would be a good place to start.

**Comment by Majkl-J** [comment]
Bitrunner den is missing the vendor

**Comment by ChakatStormCloud** [comment]
> Morgue is missing its coroner vendor

that's intentional due to the space limitations.

**Comment by nevimer** [comment]
good to merge?

**Comment by ChakatStormCloud** [comment]
> good to merge?

Haven't heard any complaints, though I noticed the delam suppression system wasn't spawning in my local build. So there's some things I still want to check next time it get's voted in.

**Comment by ChakatStormCloud** [comment]
There, that's the last issue I know about. Give that commit a couple days in test merge and if nothing else pops up I'd say it's good to go.

**Comment by projectkepler-ru** [comment]
> good to merge?

Don't merge yet

**Comment by projectkepler-ru** [comment]
I'll check your map out and get back to you in 1-3 days if I notice any issues

**Comment by nevimer** [comment]
We've playtested this a few times and it's good. Barring some like, recent-ish changes it's great. Thanks!

**Pull request merged**
