### PR TITLE
Adds Changeling Zombies (Now 99% more changeling integration)

### PR DESCRIPTION
**Pull request by BurgerLUA**
## For Admins

To give the infection to a specific person, add the Changeling Zombie antagonist type (under changeling) in the antag panel.

To run the specific event that spawns the drop pod, Run the Stray Cargo Pod event with /datum/supply_pack/misc/changeling_zombie as the delivery type.

To spawn the crate that contains the zombie viruses, spawn /obj/structure/closet/crate/medical/changeling_zombie

## About The Pull Request

Adds Changeling Zombies to the game. This is meant to replace RNA zombies and Tumor Zombies as a balanced, updated, and functional alternative.

### Equipment

Changeling Zombies are equipped with changeling armor (without helmet), and two changeling blades. They have passive regeneration over time, are immune to oxy/tox damage, immune to airlock shocks, resist cold and low pressure, do not breathe, do not hunger, and have thermal vision. They also can regenerate lost limbs 30 seconds after a limb has been lost.

Changeling Zombies cannot interact with complex machinery or tools, pick up items (they have armblades for hands), or use guns of any kind. Their limbs are also very easy to dismember.

### Infection

You can get infected by being ling absorbed from a changeling. There is generally a 30 second minimum grace period before you transform.

You can get infected by getting hit with a Changeling Zombie blade. Infection only occurs if blood effects show up.

While infected, you will slowly take toxin damage over time. Upon death, you will revive in 2 minutes, becoming a mindless Changeling Zombie with one goal: to infect others.

Note that Teshari, Monkeys, Vox, and any future species with custom body sprites or armor restrictions can't be infected.

Changelings are automatically immune to the Changeling Zombie disease.

### Cure

If you're husked from a changeling, being unhusked will also remove the Changeling Zombie infection, as long as you have not transformed yet.

Dying as a Changeling Zombie will cure you of the disease. 

If you're not a Changeling Zombie yet, but are still infected, you are able to be cured if you reach critical condition with 100 toxin damage or more, and then have that toxin damage removed to 0.

Basically, to cure someone, wait until they enter critical condition with 100 toxin or more, then pump them with anti-toxins.

Note that you are not immune to the disease once cured.

## Why It's Good For The Game

Tumor Zombies in its current state are way too infectious and unbalanced. They are meant as a round-ender where one can basically fuck up the entire crew. This effect is worse on bubbers because of high pop and a playerbase not familiar/gamer enough to kill zombies.

RNA Zombies is too buggy and has some very questionable features, such as corpse gibbing. I played a round as that and it inspired me to remake that.

## Proof Of Testing

Tested semi-extensively.

## TODO Checklist

- [x] Allow medical analyzers to detect infections.
- [x] Add a way to get infected outside of getting infected by others (patient zero).
- [ ] Live Server Testing
- [ ] Speedmerge

## Changelog

:cl: BurgerBB
add: Adds Changeling Zombies to the game. This is meant to replace RNA zombies and Tumor Zombies as a balanced, updated, and functional alternative.
add: Being husked/absorbed from a regular Changeling turns you into an unaligned/unaffiliated changeling zombie. Note that this also cures your husk infection once turned.
/:cl:

### CODE REVIEW

**Comment by KazooBard** [comment]
MOM
Mom look they added prototype to SS13 (but lore accurate)

**Comment by KazooBard** [comment]
What the hell why is it so massive I'm sorry first time posting picture :sob:

**Comment by Wolf-751** [comment]
I like this conceptually the thing is that it should be curable like romeral because that is what people are used to. It lets medical have a good logical purpose to the gameplay loop of a zombie outbreak and does not just lead to the situations of oh im infected ill just cuff myself let them kill me and be ok afterwards.Making it rapidly kill you then turn you into a changeling zombie on infection is better conceptually  and makes it so that medical got to work fast to remove the tumor or you start to get more and more zombies as the infection spreads.Bio gear should also protect you from the infection as it makes the very very rare times you have it actually worth it.

**Comment by projectkepler-ru** [comment]
> I like this conceptually the thing is that it should be curable like romeral because that is what people are used to however placing the infected organ inside the chest makes it a little bit harder to deal with than just cutting the head off,gutting will not remove the parasite it will just make it so that the dead person takes longer to revive it has to be removed medically. It lets medical have a good logical purpose to the game-play loop of a zombie outbreak and does not just lead to the situations of oh im infected ill just cuff myself let them kill me and be ok afterwards.Making it rapidly kill you then turn you into a changeling zombie on infection is better conceptually than having it turn you in two minutes and just kill you quickly in a cuffed state. This makes it so that medical got to work fast on you to remove the tumor or you start to get more and more zombies as the infection spreads and rapidly changes people.Bio gear should also be able to protect you from the infection as it is the very rare times you have it that makes it actually useful.


if its in the chest ust stabbing them till their organ fallout work too

**Comment by Wolf-751** [comment]
> > I like this conceptually the thing is that it should be curable like romeral because that is what people are used to however placing the infected organ inside the chest makes it a little bit harder to deal with than just cutting the head off,gutting will not remove the parasite it will just make it so that the dead person takes longer to revive it has to be removed medically. It lets medical have a good logical purpose to the game-play loop of a zombie outbreak and does not just lead to the situations of oh im infected ill just cuff myself let them kill me and be ok afterwards.Making it rapidly kill you then turn you into a changeling zombie on infection is better conceptually than having it turn you in two minutes and just kill you quickly in a cuffed state. This makes it so that medical got to work fast on you to remove the tumor or you start to get more and more zombies as the infection spreads and rapidly changes people.Bio gear should also be able to protect you from the infection as it is the very rare times you have it that makes it actually useful.
> 
> if its in the chest ust stabbing them till their organ fallout work too

I suggest it does not fall out rather it makes the death revival much longer ie the parasite has to go through the trouble of actually repairing all that damage,what should be doable is that you can stick a knife in there after gutting to rip it out forceably to stop it from coming alive again if you really need to put them down without medical.

**Comment by NargaInDisguise** [comment]
I personally don't like that the only way to cure it is to BECOME a zombie THEN die again, because this could lead to being placed on a stasis bed for the entire rest of the round. Give some way to cure it and I'm fully on board.

**Comment by BurgerLUA** [comment]
> I personally don't like that the only way to cure it is to BECOME a zombie THEN die again, because this could lead to being placed on a stasis bed for the entire rest of the round. Give some way to cure it and I'm fully on board.

Actually with the most recent commit (undocumented) if you have more than 100 toxins, then cure all those toxins, you're cured.

**Comment by NargaInDisguise** [comment]
> > I personally don't like that the only way to cure it is to BECOME a zombie THEN die again, because this could lead to being placed on a stasis bed for the entire rest of the round. Give some way to cure it and I'm fully on board.
> 
> Actually with the most recent commit (undocumented) if you have more than 100 toxins, then cure all those toxins, you're cured.

Okay yeah, thats pretty cool then. Should also make sure that SOMEWHERE on a med-scanner it mentions this as well. (When you push it to testing phase) :thumbs_up:

**Comment by nevimer** [comment]
What if being absorbed made you one?

**Comment by BurgerLUA** [comment]
> What if being absorbed made you one?

Holy hell this is actually a good idea and a great alternative to husking.

**Comment by sunofang** [comment]
Idea's great, and the gameplay is fun. But the cure really ought to be easier. Maybe use the RNA equipment to allow people to make a cure. Because waiting until people reach crit from toxin, and then healing them is really difficult in a crisis scenario.

**Comment by BurgerLUA** [comment]
> Idea's great, and the gameplay is fun. But the cure really ought to be easier. Maybe use the RNA equipment to allow people to make a cure. Because waiting until people reach crit from toxin, and then healing them is really difficult in a crisis scenario.

I keep getting told that the cure is super easy. I don't know what to really think.

**Comment by RadiantFlash7** [comment]
> > Idea's great, and the gameplay is fun. But the cure really ought to be easier. Maybe use the RNA equipment to allow people to make a cure. Because waiting until people reach crit from toxin, and then healing them is really difficult in a crisis scenario.
> 
> I keep getting told that the cure is super easy. I don't know what to really think.

Mixed opinions on it. It's 'easy' in that if you combine toxins meds, it's easy to fix. otherwise it takes ages and you gotta baby sit it with only one type of med. Or atleast, it was, before the latest change you have there, buffing toxins.

However, one complaint I /do/ have, is that biosuits do nothing. They really should prevent infection, frankly.

**Comment by BurgerLUA** [comment]
> > > Idea's great, and the gameplay is fun. But the cure really ought to be easier. Maybe use the RNA equipment to allow people to make a cure. Because waiting until people reach crit from toxin, and then healing them is really difficult in a crisis scenario.
> > 
> > 
> > I keep getting told that the cure is super easy. I don't know what to really think.
> 
> Mixed opinions on it. It's 'easy' in that if you combine toxins meds, it's easy to fix. otherwise it takes ages and you gotta baby sit it with only one type of med. Or atleast, it was, before the latest change you have there, buffing toxins.
> 
> However, one complaint I /do/ have, is that biosuits do nothing. They really should prevent infection, frankly.

The armblades only infect if blood is drawn. Unfortunately bio suits don't prevent that.

**Comment by RadiantFlash7** [comment]
> > > > Idea's great, and the gameplay is fun. But the cure really ought to be easier. Maybe use the RNA equipment to allow people to make a cure. Because waiting until people reach crit from toxin, and then healing them is really difficult in a crisis scenario.
> 
> > > 
> 
> > > 
> 
> > > I keep getting told that the cure is super easy. I don't know what to really think.
> 
> > 
> 
> > Mixed opinions on it. It's 'easy' in that if you combine toxins meds, it's easy to fix. otherwise it takes ages and you gotta baby sit it with only one type of med. Or atleast, it was, before the latest change you have there, buffing toxins.
> 
> > 
> 
> > However, one complaint I /do/ have, is that biosuits do nothing. They really should prevent infection, frankly.
> 
> 
> 
> The armblades only infect if blood is drawn. Unfortunately bio suits don't prevent that.

I mean, is there a way to add a check for a biosuit in the code for infection? Cause otherwise, the biosuits are useless for their main role. 

It also means medical staff are incredibly easy to infect and they're the main ones treating the infected. The moment they're turned, It's more or less game over for the station.

**Comment by theselfish** [comment]
Burger buddy. This is...

An antag who's entire way of defeating them is 'instantly kill them or they'll infect you' isn't a roleplay antag. It's not conductive to the server as nerds say. Every round we've had zombies they end the station. It's revs but revs can instantly infect people. People here are too stupid to instantly start killing the zombies, so the entire station ends up infected.

**Comment by Shadow-Quill** [comment]
Currently, they're too powerful for how difficult it is to cure 'em.
One good zombie can basically kill the station, especially if a zombie revives _in_ medical.

**Comment by nevimer** [comment]
The infection should be visible and they shouldn't be able to spread easily. Maybe being super slow moving...

**Comment by RadiantFlash7** [comment]
I gave this a shot as changeling the past round. I infected I think, 4 people total via absorbtion over the course of it. Medbay was struggling to juggle babysitting multiple patients until one zombie got loose (intentionally by me) in medbay, and infected the doctors. At which point the shift was toast.  Frankly, Infection NEEDS to be tied to bioarmor on things- and I really, don't think changelings should be able to cause round-ending stuff by simply absorbing someone. It's extremely easy to do.

I could see it as a rare thing like blob- But having it on command is definitely too much, my god.

**Comment by BurgerLUA** [comment]
Mass balance change.

## Additions:
- Changeling Zombies created by Changelings can no longer infect.
- Changeling Zombies created by the event have an 80% chance to infect.
- A cooldown for infections has been implemented, which is 3 seconds.

## Changes:
- Base wound bonus is now -21 (Previously -30)
- Unarmored wound bonus is now 9 (Previously 15).
- Having 100 toxins and dying is enough to transform you (previously 200).
- A minimum 50 toxin damage is required to enter the cure stage (previously 100).
- Base toxin damage per second with the infection on living beings has been reduced to 0.5 (previously 1).
- Base toxin damage per second with the infection on dead beings has been reduced to 1.5 (previously 3).

**Comment by BurgerLUA** [comment]
This has been ready to go for a while now.

**Comment by nevimer** [comment]
testmerge again time

**Comment by StrangeWeirdKitten** [comment]
Doesn't compile.

**Comment by BurgerLUA** [comment]
gee i wonder why

**Comment by nevimer** [comment]
ill merge this when its building

**Pull request merged**
