### PR TITLE
Increases the chances of the Wizard Die of Fate event running.

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Increases the chances of the Wizard Die of Fate running from a weight of 1 to a weight of 3.
For reference, Blob has a weight of 10.

## Why It's Good For The Game

I've personally never seen this event actually trigger because it's so rare.

## Proof Of Testing

Untested :)

## Changelog

:cl: BurgerBB
balance: Increases the chances of the Wizard Die of Fate event running.
/:cl:

### CODE REVIEW

**Comment by NargaInDisguise** [comment]
Is there the possibility that it hasn't spawned at all because we're using storyteller?

**Comment by Majkl-J** [comment]
> Is there the possibility that it hasn't spawned at all because we're using storyteller?

Nah it's in the storyteller panel with a 0.05% spawnchance

**Review by Majkl-J — CHANGES_REQUESTED** [review]
You can now actually move it into the specific track folder on storyteller

**Review by Majkl-J — APPROVED** [review]

**Comment by Majkl-J** [comment]
I forgot le merge button

**Pull request merged**
