### PR TITLE
Massive Overhaul of the Dauntless (Ready)

### PR DESCRIPTION
**Pull request by shellspeed1**
## About The Pull Request

I just spent like the past 10 hours reworking the Dauntless map in a post exam haze. Pretty much hit everything in some way or another excluding the science area. I'm pretty much throwing this up than heading off to pass out.

image

Bluespace Miners: Due to its current position being annoying to both the kitchen and medical, it was moved to virology where it is only annoying to medical. The current space does support additional miners which may be an issue. Let me know if it is. 

Engineering: The atmos tanks were shrunk to 2x1 with no space in between the cells. Two additional tanks were added with gas miners for CO2 and N2O. Additionally an electrolzyer was added. One additional SMES unit was also added, however like the others it starts off totally discharged. Lastly, if I did it right a 10 MJ capacity cell should be in atmos. Powerflow monitoring computer moved to the window along with the incinerator monitoring computer. Alert monitoring computer added. Turbine space increased and input was moved to the north of the burn chamber. 

Medical : Removed the vending machine with grenade supplies as it was redundant. Used space gained from removal of the miners to rework the position of the surgical table most commonly used. Removed one of the syndicate sleepers as they are redundant and moved some emergency supplies over to where it was. **Added a genetics setup.** Let me know if this is an issue as it was added in response to some issues with humonkeys apparently not being good enough for dissection. Removed one operating bay to replace virology. Removed one stasis bed. Added a limb grower. Removed the crematorium as we have the option to toss bodies out on lava if we really need to dump one and can't use the gibber. Dead bodies added to morgue for flavor.

Brig: Holding cell replaced with a fully functional holding cell minus a potential access issue I might still need to resolve. Cell comes with a folding chair, toilet, and awful mattress and is strategically placed to annoy the brig sergeant. Interrogation room upgraded with an intercomm for listening in by 3rd parties. Kitchen provided to prisoners upgraded with frontier equipment, including a flat pack drink dispenser and food replicator. Smart Fridge set to food provided to alleviate lag related to massive amounts of plants as it can happen. Bit running was moved to where the MAA's office was. MAA's Office moved to old Liason's office. Gave MAA's cat a toy.

Kitchen & Bar: Fridge moved to be south of the kitchen using part of the space where the bluespace miners used to be. Additional space used to increase size of kitchen to make it more useable. Smart fridge set for food put in wall to bar. Chopping block, deep fryer, and food replicator added to the kitchen. Coffee maker added to the bar along with the toy mech display from the bridge. Butchering Knife and meathook added to the freezer. One pacified syndicate mouseoperative added to eat any lose crumbs.

Disposals: Lost a tile in height to support changes to engineering.

Cargo Bay: Added grating over cables and ducting to maintain OSHA compliance.  Additionally, per events giving the dauntless permission to mine, added a mining slot and equipment.

Bridge: Added a comms monitoring setup.

Sauna : Given a pool and two bins of towels stacked on top of each other.

Liason's office: Moved to be over by the crew area. Now features an interdyne fax machine so they can represent an actual corporation. **Massive buff given in the form of a fountain pin.** Provided an in office coffee maker and carp skin chair.

Virology: Moved to medical with several tiles claimed from the lava to make it fit. Miasma can moved to storage. Monkey provided replaced with one that has human legs. I blame budget cuts.

Science : Added gas compressor and anomaly refinement. This should provide partial coverage for mandatory experiments with further support coming soon. Additionally slightly expanded xenobio and created a separate circuits lab. Added an interdyne lathe.

image

Vault: Given a red circuit tile. **An emag was also placed in the safe in case any of the preemagged machines the Dauntless gets are busted.** Its also handy for exploring stuff like illegal fish in the portal/ Let me know if this is problematic.

Dorms: Various posters have been put up. Dorms were given a second couch for CAS or UNUM as we can have up to 8 crew members and 3 prisoners. Each dorm room was given a plushie.

## Why It's Good For The Game

Beyond adding plushies to dorms, makes the ship in general far more useable, adds the ability for detainment of rowdy crew and or prisoners outside of the weird solitary cell in the back which is  rather lacking, and in general provides more space to roleplay.

## Proof Of Testing

Here is a pic from current engineering that I just snapped.

image

## Changelog

:cl:

Add: Dauntless has been vastly reworked.
Add: The Interdyne Protolathe has been added. It is essentially a reskinned Tarkon Lathe.
Add: Space Dauntless has been vastly reworked

/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
> Added a genetics setup.

This messes with the station I believe, gene discoveries are global

**Comment by shellspeed1** [comment]
> > Added a genetics setup.
> 
> This messes with the station I believe, gene discoveries are global

I swear, you are going to make me tear out my hair at this point. Is this something that significantly effects the round or is even traceable to dauntless. If so, do I need to gut the ability of the dauntless or interdyne to do genetics research?

**Comment by IgiariValkyr** [comment]
> > > Added a genetics setup.
> > 
> > 
> > This messes with the station I believe, gene discoveries are global
> 
> I swear, you are going to make me tear out my hair at this point. Is this something that significantly effects the round or is even traceable to dauntless. If so, do I need to gut the ability of the dauntless or interdyne to do genetics research?

Genetics has no way to trace who unlocks what, but yes it is linked to the station. This can be fixed down the line with code considering we have a whole research server for Interdyne itself that was never mapped in for whatever reason because no one wanted to have to research things on their own there.

**Comment by shellspeed1** [comment]
> > > > Added a genetics setup.
> > > 
> > > 
> > > This messes with the station I believe, gene discoveries are global
> > 
> > 
> > I swear, you are going to make me tear out my hair at this point. Is this something that significantly effects the round or is even traceable to dauntless. If so, do I need to gut the ability of the dauntless or interdyne to do genetics research?
> 
> Genetics has no way to trace who unlocks what, but yes it is linked to the station. This can be fixed down the line with code considering we have a whole research server for Interdyne itself that was never mapped in for whatever reason because no one wanted to have to research things on their own there.

Its been mapped in and in use for about a month and a half. You are making it sound like I need to get them setup with the other half of that which is their own lathe which limits what they can and cannot build.

**Comment by IgiariValkyr** [comment]
> > > > > Added a genetics setup.
> > > > 
> > > > 
> > > > This messes with the station I believe, gene discoveries are global
> > > 
> > > 
> > > I swear, you are going to make me tear out my hair at this point. Is this something that significantly effects the round or is even traceable to dauntless. If so, do I need to gut the ability of the dauntless or interdyne to do genetics research?
> > 
> > 
> > Genetics has no way to trace who unlocks what, but yes it is linked to the station. This can be fixed down the line with code considering we have a whole research server for Interdyne itself that was never mapped in for whatever reason because no one wanted to have to research things on their own there.
> 
> Its been mapped in and in use for about a month and a half. You are making it sound like I need to get them setup with the other half of that which is their own lathe which limits what they can and cannot build.

My fault for thinking it wasn't added then because I actually haven't played dauntless in a while.
But... mm... let me look at something real quick. It might be how other machines are and auto-link to the closest server.

**Comment by shellspeed1** [comment]
If its based on tech web, than it should be a non issue as all syndicate facilities feature automatic syncing to the interdyne techweb. (This includes DS-2). If its global than its an issue.

**Comment by IgiariValkyr** [comment]
> If its based on tech web, than it should be a non issue as all syndicate facilities feature automatic syncing to the interdyne techweb. (This includes DS-2). If its global than its an issue.

GOOD NEWS. IT ATTACHES TO THE CLOSEST TECH WEB. YOU ARE GOOD FOR GENETICS BULLSHITTERY

**Comment by shellspeed1** [comment]
Woo.

**Comment by shellspeed1** [comment]
Should be good for a test merge at this point, at least I think.

**Comment by IgiariValkyr** [comment]
Oh. While I'm thinking about it. You updated the space_dauntless file too, right?

**Comment by shellspeed1** [comment]
> Oh. While I'm thinking about it. You updated the space_dauntless file too, right?

I want to get the lavaland one nailed down first

**Comment by shellspeed1** [comment]
I will be out of town for the next few days, in the meantime let me know if any other issues come up that need to be addressed.

**Comment by Majkl-J** [comment]
> I will be away for the next few days, in the meantime let me know if any other issues come up that need to be addressed.

image

Missing tiling

**Comment by YakumoChen** [comment]
The fax machine appears to be non-emagged

**Comment by shellspeed1** [comment]
> The fax machine appears to be non-emagged in the Liason's office, if that's intended

Fixed.

**Comment by shellspeed1** [comment]
> > I will be away for the next few days, in the meantime let me know if any other issues come up that need to be addressed.
> 
> * Missing tiling
>   image
> * Waste disposal door is missing disposalpipe
> * Missing curtain on fridge
>   image

Tiles fixed, I removed the hand dryer and spare button as well. Added curtain to fridge AND window.

**Comment by shellspeed1** [comment]
Needs an updated test merge at this point

**Comment by StrangeWeirdKitten** [comment]
image

Can you have this RnD computer spawned in and constructed on round start? It would help medigate the occasional bug where the Interdyne techweb starts to have trouble and bricks itself.

**Comment by shellspeed1** [comment]
> image
> 
> Can you have this RnD computer spawned in and constructed on round start? It would help medigate the occasional bug where the Interdyne techweb starts to have trouble and bricks itself.

I'll give it a try.

**Comment by StrangeWeirdKitten** [comment]
as long as its stored research tree (forgot the exact var name) properly links to the interdyne techweb, it should be fine.

**Comment by shellspeed1** [comment]
> as long as its stored research tree (forgot the exact var name) properly links to the interdyne techweb, it should be fine. I'm pretty sure there's a wider bug at play when the techweb breaks I still need to dig a bit deeper on,

We can force connection on it so long as the R&D server in the vault is properly sync'd using a multitool.

**Comment by shellspeed1** [comment]
image

Should be working.

**Comment by IgiariValkyr** [comment]
From what I remember, it will connect to the closest server by default on construction. If one isn't close by, THEN it will connect to the station one. So as long as Interdyne has their own server, it should connect right to it on load.

**Comment by StrangeWeirdKitten** [comment]
> From what I remember, it will connect to the closest server by default on construction. If one isn't close by, THEN it will connect to the station one. So as long as Interdyne has their own server, it should connect right to it on load.

there is something that's wrong with the interdyne techweb on a deeper scale and this is a temporary midigation.

**Comment by shellspeed1** [comment]
> From what I remember, it will connect to the closest server by default on construction. If one isn't close by, THEN it will connect to the station one. So as long as Interdyne has their own server, it should connect right to it on load.

> > From what I remember, it will connect to the closest server by default on construction. If one isn't close by, THEN it will connect to the station one. So as long as Interdyne has their own server, it should connect right to it on load.
> 
> there is something that's wrong with the interdyne techweb on a deeper scale and this is a temporary midigation.

The dauntless techweb is automatically applied based on the specific ruin iirc. So if you were to spawn in DS-2, Interdyne, or dauntless and build a machine it should automatically sync to the interdyne technet. One of the dauntless map change PRs a while back introduced that feature and it could be why there is an issue.

**Review by Majkl-J — APPROVED** [review]
I'd say this currently looks good, any of the future research stuff should be atomized once we find the source of the bug (i.e., done individually of this PR). Feel free to copy the edits over on the space dauntless

**Comment by Majkl-J** [comment]
(Come to think of it, I wonder if I could make a spacial turf that creates lava/space depending on what type of z level it's in)

**Comment by Majkl-J** [comment]
Just say when

**Comment by shellspeed1** [comment]
Go for it

**Pull request merged**
