### PR TITLE
Makes the christmas tree safe

### PR DESCRIPTION
**Pull request by StrangeWeirdKitten**
## About this pull request

It makes the christmas tree spawner safe

## Why it's good for the game

Because I got a piece of paper and someone else got a chronos modsuit. I don't need to explain why getting debug and admin gear is very broken.

## Changelog

🆑
balance: The christmas tree will be safe next year
/:cl:

### CODE REVIEW

**Comment by StrangeWeirdKitten** [comment]
it ends in like 2 hours anyway

**Comment by StrangeWeirdKitten** [comment]
For next year

**Comment by Detective-Google** [comment]
it's 5 days out of the whole year to let people see all the weird and wacky unobtainium coder items in the game, honestly I think it should just be left up to whatever admins are online and just "yknow I don'tt feel like dealing with the inveitable christmas tickets this round" Could also take the citadel route and nuke the maint spawn presents so that you only get one 'hit' of the metaphorical slots per round, which cuts down on this a lot. most maps have ~20 presents spawn in maint which means a few people are getting outsized chances at silly items, as well as presents being theoretically infinite since one of the cargo orders has maint spawns in it.

**Comment by Bapldap** [comment]
The grinch who stole Christmas 🎄 🥶

**Comment by StrangeWeirdKitten** [comment]
> it's 5 days out of the whole year to let people see all the weird and wacky unobtainium coder items in the game, honestly I think it should just be left up to whatever admins are online and just "yknow I don'tt feel like dealing with the inveitable christmas tickets this round" Could also take the citadel route and nuke the maint spawn presents so that you only get one 'hit' of the metaphorical slots per round, which cuts down on this a lot. most maps have ~20 presents spawn in maint which means a few people are getting outsized chances at silly items, as well as presents being theoretically infinite since one of the cargo orders has maint spawns in it.

if maint loot can spawn xmas gifts that can give debug items, that's a oversite.

**Comment by kiwedespars** [comment]
hates fun

**Comment by nevimer** [comment]
it's not fun for the staff or the players really when there is dumb conflict surrounding gifts every round.  not to mention debug items.

**Comment by kiwedespars** [comment]
> it's not fun for the staff or the players really when there is dumb conflict surrounding gifts every round. not to mention debug items.

five days out of the year, it's fun for the players because people get fun shit :p

**Comment by StrangeWeirdKitten** [comment]
Then don't run around hunting people with insta kill admin guns or get a ninja modsuit and spam make assault Borgs to hunt someone down. There's two options, I can bwoink people who abuse debug gear or I can fix the bwoink bait. I'm sure everyone who's got a debug item and ruined another person's round with it can attest they'd much rather enjoy the second option.

**Pull request merged**
