### PR TITLE
Gibs PhazeJump if he joins with a pref different from bottom-sub

### PR DESCRIPTION
**Pull request by Majkl-J**
image

### CODE REVIEW

**Review by nevimer — APPROVED** [review]

**Comment by Mitryll** [comment]
Extremely important to the game and adds massive QoL to the codebase. Wonderful PR, please speedmerge.

**Comment by FoxxyRenamon** [comment]
Approved by Head-admins.

**Comment by Erol509** [comment]
This has to be merged

**Review by lessthnthree — APPROVED** [review]

**Comment by Shadow-Quill** [comment]
LGTM

**Comment by PhazeJump** [comment]
I'm actually gonna bite you, Waterpig

**Comment by ElisavetPinko** [comment]
I'm Elly, and I approve this message.

gibuj się subie.

**Comment by StrangeWeirdKitten** [comment]
Moving this to server side code so being a bottom can never be coded out

**Pull request closed without merging**
