### PR TITLE
Featherweight quirk one hand carry

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request

Changes the piggyback mechanic so featherweight mobs can ride with only a single hand.

## Why It's Good For The Game

Lightweight, more mobility. Adds a bit to the quirk other than just visual change.

## Changelog

:cl: LT3
balance: Featherweight quirk allows mob carrying with a single hand
/:cl:

### CODE REVIEW

**Comment by ReturnToZender** [comment]
Speedmerge

**Comment by YakumoChen** [comment]
Officer piggyback meta so both of them can shoot guns while stacked now?

**Comment by The-Sun-In-Splendour** [comment]
Please don't merge this piggybacking is cancer and I am 99% sure some dude will use this with their metabuddy to be buddy cop without any of the downsides of the duo being as fast as the slowest member.

**Comment by lessthnthree** [comment]
If you think sec players and such are going to abuse it, yeah okay will pax the featherweight rider.

**Comment by YakumoChen** [comment]
Pax means you can still fire a disabler or joust with a baton

**Comment by lessthnthree** [comment]
Right now I don't feel like spending more time bubble wrapping this because security players can't be trusted.

**Pull request closed without merging**
