### PR TITLE
[NON_MODULAR] Add Imaginary Friend Implanter

### PR DESCRIPTION
**Pull request by stoneman2**
## About The Pull Request
Adds an imaginary friend implanter that gives you permanent Imaginary Friend brain damage, should be removable.
Sold at the computer vendor, since the pAI is there. Similar concepts, right?

## Why It's Good For The Game
For players who wishes to play around with Imaginary Friend, here it is! It is technically contraband, if security wishes to do something about it. If not, let players actually experience imaginary friends without going through brain damage farming.
Only two available!!

Imaginary Friend is such a cool feature. Shame it isn't at all accessible. Barely anyone know about it at all.
-best friend for only 100cr!!
-new bestie

## Changelog

:cl:
add: Added the imaginary friend implanter inside the computer vendor in the contraband section.
/:cl:

### CODE REVIEW

**Comment by projectkepler-ru** [comment]
I assume this is hand tested ?

**Comment by stoneman2** [comment]
Yep, tested it.

**Comment by stoneman2** [comment]
It gotta be? I'll fix it if you'd like!

**Comment by stoneman2** [comment]
Yeah, I see the error of my ways

**Pull request closed without merging**
