### PR TITLE
Hop recolor

### PR DESCRIPTION
**Pull request by 567Turtle**
## About The Pull Request

So, somebody remade all of the HoPs clothing sprites, except the cape, so the cape looked really out of place. All i did was recolor the cape so now it doesnt look like ass.

https://user-images.githubusercontent.com/91508746/218345289-0182b30f-dc7c-4d4b-a241-7dc89fa86785.mp4

## Changelog

:cl:
add: New HoP cloak sprites
/:cl:

### CODE REVIEW

**Review by KathrinBailey — CHANGES_REQUESTED** [review]
make it modular :(

**Comment by 567Turtle** [comment]
> make it modular :(

es a sprite how :(

**Comment by Cyprex** [comment]
Why are both neck.dmi & cloak.dmi changed?

**Comment by 567Turtle** [comment]
> Why are both neck.dmi & cloak.dmi changed?

I went and looked, I don't know actually? It's really weird, I might just make this PR again since this ones kinda fucked

**Comment by 567Turtle** [comment]
#42

**Pull request closed without merging**
