### PR TITLE
[Modular] Adds new wideborgs

### PR DESCRIPTION
**Pull request by ReturnToZender**
## About The Pull Request

This adds new wideborgs to the game: The Corrupt borg and Corrupt alt borgs, as Peacekeeper sprites. Big and scary, these guys look like they bite.

image
image
image

## Why It's Good For The Game
More variety is always good for the game!

## Changelog

:cl: ReturnToZender
add: Corrupt and Corrupt Alt borg sprites to the peacekeeper tab!
fix: code cleanup in the borg modular file, fixed a typo, added a missing mapload
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
Post pics of each type
Also the one example shown looks nothing like the borg type it is supposed to model. Variety is nice but it needs to visually conform to an archetype for ease of identification

**Review by projectkepler-ru — COMMENTED** [review]
These uh.. are not very obvious visually that they are peacekeeper borg

**Comment by ReturnToZender** [comment]
> These uh.. are not very obvious visually that they are peacekeeper borg
In that case I can swap them to miner, they were originally a security model but we don't have security borgs, so

**Comment by ReturnToZender** [comment]
Linters are broke because new variables, gonna update them once I'm done fixing the Directory

**Comment by YakumoChen** [comment]
add pictures of all the borg types

**Review by StrangeWeirdKitten — CHANGES_REQUESTED** [review]
I'd rather they be mining borgs. Peacekeeper needs to be kept visually distinct.

**Comment by Strazyplus** [comment]
The corrupt hound was a syndicate cyborg skin if I recall.

**Comment by ReturnToZender** [comment]
Gotta resolve some merge conflicts, closing this for now to do so

**Comment by ReturnToZender** [comment]
Continued in #1029

**Pull request closed without merging**
