### PR TITLE
Disables Station Blackout and Random Machine Languages Station Traits

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Disables the Station Blackout and Random Machine Language station traits.

## Why It's Good For The Game

Station Blackout would kill all the lights on station. This was awful, especially if there was no janitor.

Random Machine Language would give a random language to every machine that speaks and every bot. This was annoying since it affected cryo announcements and arrivals announcements.

## Proof Of Testing

If it compiles, it werks.

## Changelog

:cl: BurgerBB
del: Disables Station Blackout and Random Machine Languages Station Traits
/:cl:

### CODE REVIEW

**Review by Majkl-J — APPROVED** [review]
The language one should've been gone sooner. Would be nice to add some more neat traits in the future (Nonstandard ai lawset trait when? :eyes:)

**Comment by BurgerLUA** [comment]
> The language one should've been gone sooner. Would be nice to add some more neat traits in the future (Nonstandard ai lawset trait when? 👀)

This is actually already a trait.

**Comment by Majkl-J** [comment]
> > The language one should've been gone sooner. Would be nice to add some more neat traits in the future (Nonstandard ai lawset trait when? 👀)
> 
> This is actually already a trait.

Is that disabled? I swear I never see it

**Comment by IgiariValkyr** [comment]
Does this fully kill both, cause I was going to forceroll a blackout today.

**Comment by BurgerLUA** [comment]
you should be able to forceroll still

**Pull request merged**
