### PR TITLE
Upstream 12/19/2023

### PR DESCRIPTION
**Pull request by StrangeWeirdKitten**
This breaks absolutely EVERYTHING. Do not merge. There still needs to be a lot of work.

This is ushering in an era of 515. I think we need to eventually bite the bullet and pull from our ball and chain.

- Polish guns or whatever need to be commented out until their balance is addressed
- CI and the labler was touched. Someone should probally make sure it's not broken.
- Clone damage was removed
- The changelog is absolutely fucked right now. 
- I removed kilo station automatters from skyrat. We need to fix this. Perferably by removing all the auto mappers since they are not needed
- There's probally a ton of other crap. This will need extensive test merging if it even compiles. 
- Also the debugger might not even work. 
- **extensive** refactoring of TGUI. 

## Stuff fixed because they messed with this
🆑
fix: Shadekin is fixed (with other misc bubber sprites)
/:cl:

### CODE REVIEW

**Comment by Majkl-J** [comment]
I'll poke around with the debugger and see if it works right

**Comment by StrangeWeirdKitten** [comment]
image

**Comment by BurgerLUA** [comment]
For maintenance loot and arcade loot, just delete the lines containing the missing objects.

For the RBMK2, it looks like they changed how flags work.

Following offending flags: CONDUCT_1, NODECONSTRUCT_1

**Comment by BurgerLUA** [comment]
CONDUCT_1 should be changed to CONDUCTS_ELECTRICITY
NODECONSTRUCT_1 should be changed to NO_DECONSTRUCTION

**Comment by StrangeWeirdKitten** [comment]
> CONDUCT_1 should be changed to CONDUCTS_ELECTRICITY NODECONSTRUCT_1 should be changed to NO_DECONSTRUCTION

👍

**Comment by StrangeWeirdKitten** [comment]
The security medic hud is the interdyne agent hud now. So this will need to be obviously resprited later.

**Comment by StrangeWeirdKitten** [comment]
Inferno for TGUI was removed completely. I'll need to figure this out later. Mostly for our fishing and character directory.

**Comment by StrangeWeirdKitten** [comment]
TGUI got thrusted from Inferno to React. Yeah, our TGUI code is a little busted.

**Comment by Erol509** [comment]
Wow, looking at the changed code freezed my browser..

**Comment by StrangeWeirdKitten** [comment]
I fucked up my commit history

**Pull request closed without merging**
