### PR TITLE
bullet faster

### PR DESCRIPTION
**Pull request by 567Turtle**
## About The Pull Request

Bullets now move a bit faster, they were pretty slow before to the point where if you were happy and healthy enough you could straight up outrun them. This doesn't (shouldn't) effect other projectiles.

## Proof of Testing

<details>
<summary>

https://user-images.githubusercontent.com/91508746/217381151-26f8f7d7-9d03-45a7-a602-16143c773f8a.mp4

</summary>
  
</details>

## Changelog

:cl:
balance: Bullets move a little bit faster
/:cl:

### CODE REVIEW

**Comment by Cyprex** [comment]
This has massive balance implications. I'm still inclined to merge this. Note that Various skyrat bullets override this variable, so this PR won't affect those.

**Comment by 567Turtle** [comment]
> Note that various Skyrat bullets override this variable, so this PR won't affect those.
>
I'm aware! My line of thinking was if the SR c*ders went out of their way to change a specific bullets speed they probably had a reason to, I could adjust their speeds to close match this closer but it was a minority so I decided I'd leave it.

**Comment by KathrinBailey** [comment]
I'm a bit sceptical on if bullets even need this buff when full auto is so prevalent and lasers are so weak right now.
The bullets already seem fairly quick, maybe if you can outrun them, the problem is movement speed and not bullet speed?
Why did you want to make bullets faster? @567Turtle

**Comment by 567Turtle** [comment]
Changing movement speed was my original idea so I asked bubbers to change the movement speed to just be a bit slower since that's a TGS thing and he said no because of how much stuff is balanced around movement speed (i.e. getting sucked out of atmosphere)

**Comment by 567Turtle** [comment]
ready to be merged :)

**Comment by ChungusGamer666** [comment]
Good PR :)

**Comment by Cyprex** [comment]
Yeah let's just not.

**Pull request closed without merging**
