### PR TITLE
Fixes old feeler code

### PR DESCRIPTION
**Pull request by Aphast**
## About The Pull Request
Butters ruined my years old shitcode feelers, ergo I have fixed them, yes, deleting the line is the only way it works, dont ask me i dont know why. It is valve levels of shitcode.

And yes i have triplechecked this

## Changelog
Fixes a broken code [comment ](https://github.com/Bubberstation/Bubberstation/pull/137)line to allow sprite displaying again

:cl:
del: Commented out line from neck and head accessories
/:cl:

### CODE REVIEW

**Comment by nevimer** [comment]
This PR does nothing. A comment isn't considered at all for compiling, and it's existence has zero impact. It may be working for you because you're making a PR from a really old version of the game before it broke, probably.

**Comment by Aphast** [comment]
Actually for whatever reason it does matter, the file used to work previously until a comment was added, this happened when i was doing this work for TE aswell. and my byond is fully up to date aswell and on main server it doesnt work. I also fresh cloned the repository from last night ergo an old version is nigh impossible

**Comment by Aphast** [comment]
The only way the sprite displays is by either deleting the line, or re-adding the commented line as proper code

**Comment by nevimer** [comment]
Literally impossible. The server is running code 4 months newer than the branch you've this PR from. This repo is way out of date.

**Comment by Aphast** [comment]
this is forked from the master i dont see how it could be 4 months older, git desktop cloned the repo and says master is up to date, the branch isnt based off of the referenced PR its based on master just linking to what originally broke the sprite

**Comment by nevimer** [comment]
The server isn't running master. It's running code from the update PR. The repo here hasn't merged that yet, and so much has changed in that time period.

**Comment by Aphast** [comment]
How would one go about contributing and attempting to fix the issue in said branch?

**Comment by Majkl-J** [comment]
> The server isn't running master. It's running code from the update PR. The repo here hasn't merged that yet, and so much has changed in that time period.

I know and I utterly hate some of the stuff it broke (Can't wait to give sec medic medbay access back the moment it's merged into master)

**Comment by Aphast** [comment]
considering this seems like it wont work due to branch issues, going to go ahead and close this

**Comment by nevimer** [comment]
> How would one go about contributing and attempting to fix the issue in said branch?

You can make a pr branched off my branch, but, because of how skewed that is, it will be MESSY. I honestly wish the maintainers would merge my PR so that things could be fixed on it. The long time-gap is making people very confused.

**Comment by Aphast** [comment]
> 

i suppose i will try that later, and yes, very very confused

**Comment by Aphast** [comment]
> > How would one go about contributing and attempting to fix the issue in said branch?
> 
> You can make a pr branched off my branch, but, because of how skewed that is, it will be MESSY. I honestly wish the maintainers would merge my PR so that things could be fixed on it. The long time-gap is making people very confused.

its the :overlay branch correct?

**Comment by nevimer** [comment]
yep

**Pull request closed without merging**
