### PR TITLE
Buffs Engineers by adding atmos access

### PR DESCRIPTION
**Pull request by ReturnToZender**
## About The Pull Request
Normally, Station Engineers do not need access to atmospherics, as N2 has been traditionally sufficient to power the station. However, due to recent changes, Engineers need alternative gasses in the Engine. As a bandaid measure, this PR gives Station Engineers atmos access by default, even on highpop.

## Why It's Good For The Game
Engineers can now set up the Engine, so people play Station Engineer more instead of Atmos Tech

## Proof Of Testing
image

## Changelog

:cl: ReturnToZender
balance: Engineers can now access atmos by default
/:cl:

### CODE REVIEW

**Comment by BurgerLUA** [comment]
Back in my day, I remember this topic would cause heated debate on balance.

Do engineers have atmos access? If engineers have atmos access, then atmos tech would just be a less engineer.

**Review by nevimer — APPROVED** [review]

**Comment by Majkl-J** [comment]
Cmon guys I just froze balance a day ago

**Comment by nevimer** [comment]
> Cmon guys I just froze balance a day ago

I got so excited seeing something that I wanted and should have done like a year ago

**Comment by Swiftfeather** [comment]
implying engineers couldn't set the engine up before thonk.jpg

**Comment by Cyprex** [comment]
Not a fan, just hack in?

**Comment by shellspeed1** [comment]
> implying engineers couldn't set the engine up before thonk.jpg
> 
> if they couldn't set it up with two cans of n2 and a can of plasma giving them atmos access won't help at all.
> 
> I disagree with this PR

Because we need more power. Basic bitch N2 engines are not cutting it anymore with the current power changes. Having access to at least CO2 is helpful for this.

**Comment by Erol509** [comment]
Yeah, you can always just hack in. Engineers get door wires skill chip, while atmos techs dont.

**Comment by Odairu** [comment]
> Yeah, you can always just hack in. Engineers get door wires skill chip, while atmos techs dont.

I shouldn't have to hack into a door to fulfil the basic needs of the station

**Comment by destrucktoid** [comment]
> > > Back in my day, I remember this topic would cause heated debate on balance.
> > > Do engineers have atmos access? If engineers have atmos access, then atmos tech would just be a less engineer.
> > 
> > 
> > The real lore is that Atmos Tech and Station Engineer were always the same job
> 
> Mood, was thinking that too.
> 
> They should share the same access tbh.

at that point just make them the same role with atmospheric technician being an alternative job title for engineer, similar to how xenobiologist is for science

**Comment by ReturnToZender** [comment]
> Because we need more power. Basic bitch N2 engines are not cutting it anymore with the current power changes. Having access to at least CO2 is helpful for this.

I tested on localhost and an N2 engine using every tesla coil and emitter in Secure Tech storage is barely able to scrape the 2.5MW requirement, CO2 definitely helps though

**Comment by Swiftfeather** [comment]
Alright do the solars then, order a teg, rebalance sm output with a pr, you don't need to give engis atmos access.

**Pull request closed without merging**
