### PR TITLE
[WIP] Re-adds a hugboxed and improved lone operative antagonist type

### PR DESCRIPTION
**Pull request by BurgerLUA**
WIP. Untested and uncompiled.

## About The Pull Request

Adds a new "Opportunistic Operative" antagonist type that is spawned if the disk is ignored for too long.
Opportunistic Operatives have an objective to steal the disk and hijack the emergency shuttle. They also have an objective to kill the Captain (or a head of staff if none exists), as well as the chance to kill people who are in view of the disk.

Opportunistic Operatives are not ghost roles and instead are picked from those who have both the traitor and operative preference set to enabled. They spawn with a regular traitor uplink, and a pinpointer to track the disk.

## Why It's Good For The Game

Alternative to #991. Instead of a nuke going off and interrupting the round because a captain was afk for 10 minutes without telling anyone, this just gives someone traitor with objectives to kill and hijack the shuttle.

Bubberstation is falling down a hole of punishing players for no real reason other than they think that it builds robustness or "improves" a players ability to play. I hope I don't have to make alternative middle ground measures in the future.

## Proof Of Testing

WIP. Untested and uncompiled.

## Changelog

:cl: BurgerBB
add: Adds a new "Opportunistic Operative" antagonist type that is spawned if the disk is ignored for too long.
Opportunistic Operatives have an objective to steal the disk and hijack the emergency shuttle. They also have an objective to kill the Captain (or a head of staff if none exists), as well as the chance to kill people who are in view of the disk.
/:cl:

### CODE REVIEW

**Comment by CameronWoof** [comment]
This feels significantly better than threatening the nuclear destruction of a round over the disk. I'm not a huge fan of the "punishment" design meta, exactly, but this correctly "punishes" the person or people who have actually done something "wrong" by failing to secure and adequately take the disk for walkies, rather than the entire station. 

I also like that it hires in-house instead of incentivizing people to lurk as a ghost for the chance to ruin the round for people based on some random technicality. 

Big improvement over base lone op imo.

**Comment by Redrover1760** [comment]
A regular traitor uplink to hijack, steal the NAD, and kill the captain?

Seems kinda underpowered

**Comment by StrangeWeirdKitten** [comment]
I'm willing to try this one out.

**Comment by Formerxboxgamer** [comment]
Someone please tell me what the functional difference between this hijack objective and a nuke with a 10 minute timer. Seems like the issue in the first PR was the round ending. What exactly do y’all think a traitor who just killed the captain and has to hijack is going to do? NOT call the shuttle?

**Comment by Swiftfeather** [comment]
This is months stale. Feel free to re-open if you come back to it.

**Pull request closed without merging**
