### PR TITLE
Minor quality of life changes to Tarkon and Charlie

### PR DESCRIPTION
**Pull request by TreePizza**
## About The Pull Request

Minor fixes and qol to Tarkon.
Changes Charlies spawners to actually spawn you instead of bumblechuck the nobody.

## Why It's Good For The Game

Admins no longer have to go through the headache of fixing someone who goes to Charlie every single time.

## Proof Of Testing

https://github.com/Bubberstation/Bubberstation/assets/164035230/39f6b703-9d2a-4622-8ae7-55ee9c6b1b4a

## Changelog

:cl:
add: 2 hidden Xenoplush for Monophobia characters, one on each station.
qol: Charlie pods now have pref and loadout spawning. 
fix: A light has been added to Tarkons freezer and an additional one to Tarkons kitchen. Added that awkwardly missing window to the top airlock and deleted the equally awkward single disposal pipe that was underneath it.
:cl:

### CODE REVIEW

**Comment by Majkl-J** [comment]
Assigning myself, please refrain from providing any technical reviews to this one, only balance concerns and such

**Review by projectkepler-ru — APPROVED** [review]
Glossary glance over the changes don't impact balance in any meaningful nor tangible way, do consider upstreaming this however.

**Comment by IgiariValkyr** [comment]
I thought the whole point of Charlie was "this station is from before NT started hiring all the weird races, so it's just humans".

**Comment by Majkl-J** [comment]
> I thought the whole point of Charlie was "this station is from before NT started hiring all the weird races, so it's just humans".

The amount of ahelp "Please fix my prefs" would say otherwise

**Comment by TreePizza** [comment]
I'm probably just going to push these changes upstream to Skyrat once I ~figure out how the fuck Fax machines work so that I can put one on Tarkon.~

**Pull request closed without merging**
