### PR TITLE
Reduces the amount of ruin Z levels

### PR DESCRIPTION
**Pull request by StrangeWeirdKitten**
We have memory issues and we need to start cutting down on it. I'd rather keep our ghost roles intact and the Interlink intact with this being the first solution.

Halves the amount of ruin Z levels that spawn. (7 to 4 by default)

### CODE REVIEW

**Comment by NargaInDisguise** [comment]
Will this overall decrease the amount of ruins to explore? If so that'll be a little sad.

**Comment by Majkl-J** [comment]
> Will this overall decrease the amount of ruins to explore? If so that'll be a little sad.

Yes but the only other short term option is lowering the player cap or somehow getting lummox to make the engine 64bit

**Comment by Swiftfeather** [comment]
> > Will this overall decrease the amount of ruins to explore? If so that'll be a little sad.
> 
> Yes but the only other short term option is lowering the player cap or somehow getting lummox to make the engine 64bit

we should get lummox to update it to 64 bit. That seems like the easiest choice :)

**Comment by NargaInDisguise** [comment]
> > Will this overall decrease the amount of ruins to explore? If so that'll be a little sad.
> 
> Yes but the only other short term option is lowering the player cap or somehow getting lummox to make the engine 64bit

Augh...
Goodbye space exploration, you will be missed...

**Comment by MajManatee** [comment]
Can we increase ruins per Z level slightly to try and compensate?

**Comment by Hemlock32** [comment]
7 to 4 is an absurd decrease, as if space isn't already neutered and barren enough as is.

**Comment by ReturnToZender** [comment]
> [Hemlock32](/Hemlock32)
WD: Server crashed! Rebooting...

**Comment by StrangeWeirdKitten** [comment]
I haven't touched the ruin tokens so theoretically the same amount should spawn. 

I'll investigate later to see if this is the case.

**Comment by StrangeWeirdKitten** [comment]
I increased the tokens from 10 to 16 for hopefully better ruin density. It's going to be monitored though, but there was a very substantial improvement on memory and ultimately we have to look at cutting *something*.

**Comment by Cyprex** [comment]
👍 Pretty simple change, easily reverted once we get memory under control. Vaguely related- when I profiled init times w/ tracy it was shown that we spend a ton of time trying (and failing) to place down ruins, was this addressed at some point?

**Comment by StrangeWeirdKitten** [comment]
> 👍 Pretty simple change, easily reverted once we get memory under control. Vaguely related- when I profiled init times w/ tracy it was shown that we spend a ton of time trying (and failing) to place down ruins, was this addressed at some point?

Yes that was when the config had 80 space ruin tokens in it. I killed that number (currently it's 16)

**Pull request merged**
