### PR TITLE
Nerfs RPED alt sounds.

### PR DESCRIPTION
**Pull request by NullDagaf**
## About The Pull Request

Makes the alternate BRPED sound rarer.

## Why It's Good For The Game

I hate it, therefore it's good.

### CODE REVIEW

**Comment by Serxule** [comment]
shooom
shooom
shooom
shooom
shooom
shooom
shooom
shooom
shooom
shooom
shooom

**Comment by projectkepler-ru** [comment]
merge this one

**Comment by projectkepler-ru** [comment]
@ReturnToZender  good to merge

**Comment by NullDagaf** [comment]
Why was that turned into a draft. @KathrinBailey

**Review by projectkepler-ru — APPROVED** [review]
seems fine

**Pull request merged**
