### PR TITLE
Relentless heartbeat is knowledge-free to pick

### PR DESCRIPTION
**Pull request by delingar**
## About The Pull Request

The Relentless Heartbeat is 0 cost knowledge now

## Why It's Good For The Game

It's not poggers, when you have to spend knowledge to reroll one last target, that is went fucking in dorms. We are RP-ERP oriented server and antags can't break into dorms, at least without consensual approval

## Proof Of Testing

TVW0CpcnHO

## Changelog

:cl:
qol: Relentless Heartbeat costs 0 knowledge
/:cl:

### CODE REVIEW

**Comment by ReturnToZender** [comment]
This is actually a really good idea, thanks for this one Delingar

**Comment by destrucktoid** [comment]
Antags can actually break into dorms, they are not protected under the rules (unless the rules have changed). People however assume you cannot. You cannot however break into the interlink, in which case you are shit out of luck unless you ahelp for a new target (which admins usually give).

**Comment by delingar** [comment]
> Antags can actually break into dorms, they are not protected under the rules (unless the rules have changed). People however assume you cannot. You cannot however break into the interlink, in which case you are shit out of luck unless you ahelp for a new target (which admins usually give). 
> 
> That's not to say i think this is a bad idea, i do think that this is a good idea to do regardless.

1. I've got luck to get on admin, who send me to do heartbeat. I'm very greedy, when it comes to spend tc/knowledge 

2. Heretics are not usually have enough time to talk with admin after they make such a noise

**Comment by destrucktoid** [comment]
> > Antags can actually break into dorms, they are not protected under the rules (unless the rules have changed). People however assume you cannot. You cannot however break into the interlink, in which case you are shit out of luck unless you ahelp for a new target (which admins usually give).
> > That's not to say i think this is a bad idea, i do think that this is a good idea to do regardless.
> 
> 1. I've got luck to get on admin, who send me to do heartbeat. I'm very greedy, when it comes to spend tc/knowledge
> 2. Heretics are not usually have enough time to talk with admin after they make such a move. 80% ratio that victims will cry to admins.
> 3. 60% chance, that victim will go to interlink dorm
> 4. 

Rules have been changed then from last i recall, either that or i'm mis-remembered an admin ruling from a while ago that was made in a round i was in. My bad for saying so, either way; point you have refuted asides, a good change. Although as per ERP rule 3, if you ahelp for a new target because your current one is "in a scene in a private space, you should ahelp to get a new target." So admins _should_ give you a new target.

**Comment by delingar** [comment]
> > > Antags can actually break into dorms, they are not protected under the rules (unless the rules have changed). People however assume you cannot. You cannot however break into the interlink, in which case you are shit out of luck unless you ahelp for a new target (which admins usually give).
> > > That's not to say i think this is a bad idea, i do think that this is a good idea to do regardless.
> > 
> > 
> > 
> > 1. I've got luck to get on admin, who send me to do heartbeat. I'm very greedy, when it comes to spend tc/knowledge
> > 2. Heretics are not usually have enough time to talk with admin after they make such a move. 80% ratio that victims will cry to admins.
> > 3. 60% chance, that victim will go to interlink dorm
> > 4. 
> 
> Rules have been changed then from last i recall, either that or i'm mis-remembered an admin ruling from a while ago that was made in a round i was in. My bad for saying so, either way; point you have refuted asides, a good change. Although as per ERP rule 3, if you ahelp for a new target because your current one is "in a scene in a private space, you should ahelp to get a new target." So admins _should_ give you a new target.

As i said, i got a moment, when i was just sent to use heartbeat, when my last target went erping

**Comment by Moostard** [comment]
Feels like some people could keep rerolling the targets untill they get the easy ones if it is free. You could call it "Path of least resistance".

**Review by projectkepler-ru — APPROVED** [review]

**Comment by destrucktoid** [comment]
> Feels like some people could keep rerolling the targets untill they get the easy ones if it is free. You could call it "Path of least resistance".

Not as easy as you'd think, re-rolling uses a book and a harebell, books can be obtained at the library fairly easily, harebells on the other hand are actually quite limited, i do not believe botany can actually grow them and they are only obtainable from the chapel; ergo you only have about 5 re-rolls maximum.

**Comment by delingar** [comment]
> > Feels like some people could keep rerolling the targets untill they get the easy ones if it is free. You could call it "Path of least resistance".
> 
> Not as easy as you'd think, re-rolling uses a book and a harebell, books can be obtained at the library fairly easily, harebells on the other hand are actually quite limited, botany cannot easily grow them due to the fact that they do not have a seed for it and need to get a seed from the harebells in the chapel, this is something they will literally never do unless you happen to have a botanist heretic, thus in most rounds they are only obtainable from the chapel; ergo you only have about 5 re-rolls maximum.
> 
> Furthermore, this PR only changes it so the relentless heartbeat knowledge is free, it doesn't make it so you get it immediately, in order to even unlock it you need to be on T2 heretic spells.

T3*

**Comment by destrucktoid** [comment]
> > > Feels like some people could keep rerolling the targets untill they get the easy ones if it is free. You could call it "Path of least resistance".
> > 
> > 
> > Not as easy as you'd think, re-rolling uses a book and a harebell, books can be obtained at the library fairly easily, harebells on the other hand are actually quite limited, botany cannot easily grow them due to the fact that they do not have a seed for it and need to get a seed from the harebells in the chapel, this is something they will literally never do unless you happen to have a botanist heretic, thus in most rounds they are only obtainable from the chapel; ergo you only have about 5 re-rolls maximum.
> > Furthermore, this PR only changes it so the relentless heartbeat knowledge is free, it doesn't make it so you get it immediately, in order to even unlock it you need to be on T2 heretic spells.
> 
> T3*

Relentless heartbeat unlocks after you acquire any of the T2 spells such as void phase, ergo making it unlock at T2 (at least according to the TG heretic wiki page)

**Review by Majkl-J — APPROVED** [review]
The reasoning is solid

**Pull request merged**
