### PR TITLE
Remove AI Upload Boards from all printable sources

### PR DESCRIPTION
**Pull request by Alecksohs**
## About The Pull Request

Removes the AI upload boards from the techfab, among other printable sources.

## Why It's Good For The Game

This will be a bit, so make sure to read it before just deciding that you don't want the removal to happen.

AI Subversion has been occuring far more often than desired. The reason for this uptick in occurance is due to the availability of the AI upload board to be printed by anyone with research access. It has gotten so bad that there have been rounds with as much as 33 law changes due to this. AI players have been upset over how often it has been occuring due to how jarring it is to constantly be subverted. As an pro-antag player, I believe that antagonists should have a far more difficult time hacking an AI. There are several ways to truly hack the AI. Right now, we have given the antag players a crutch, allowing them to have easy pickings for subversion of the AI, making the concept of a subverted AI stale.

In a recent round, an admin player carded an AI player, leaving them stuck for the entire round (round removal) in a bag. The reason given was that an antag had constructed an AI upload, and had printed many AI law boards. The admin was the captain, and couldn't trust the AI given how easy it was for them to be hacked. The admin went, of course, unpunished due to the clear justification that they had. Their decision was logical. The AI was too easy to hack, and they couldn't trust the AI. Why not card them? 

This shows a clear problem with the concept of being able to print a law board. Due to the availability, an antag can cause so much chaos with such a simple board that it is easier to roundremove the AI than it is to continue playing with them in the round. If the AI upload was harder to obtain, then there would be no reason to roundremove the AI. The justification would be gone, and a player who would remove the AI from play would have far less reason to do so, which could lead to rightful punishment of said player.

The solution is to make the board scarce. I have removed it from printing. It is now located in the tech-storage. Additionally, it has been added to every AI Upload by attaching onto the round default board spawner, spawning an additional AI Upload Board. This has been added so that it spawns in an additional secure location, to help quell maintainer fears about lack of ability to fix a subverted AI. Past this, if the player decides to destroy all AI uploads, then a command officer must CC request a new AI upload, or can call an admin spawned Engineering ERT to fix the situation. Otherwise, the antag player should be given their victory. The administration can dictate if this was powergaming or not, that isn't my problem. 

This will reduce the amount of AIs being subverted. Until Storyteller works malf in, it could reduce it drastically. This is expected. This is desired. There is no other way to reduce AI subversion from "too much".  The way to solve this problem is to fix the bad game design, not to throw rules on top of it.

PR made by the request of an AI player

## Proof Of Testing

I ran it.

image

## Changelog

:cl:
balance: Removed AI law board from printing, New one in AI upload

/:cl:

### CODE REVIEW

**Comment by Alecksohs** [comment]
this is my first time doing modularization so I hope I did it right

**Comment by JohnFulpWillard** [comment]
People subverting the AI has always been sort of a trend that people do, get bored of, then move onto other things, then repeat. Dunno if it justifies removing it but god it does get incredibly annoying during the times it is trendy to do it.

**Comment by AllCorruptingWyrm** [comment]
I really hate carding a non malf AI who is constantly getting subverted. I played Captain once and someone kept on subverting them and I know that if you get carded, you basically can't do anything unless you're put into a shell. It's not fun, especially when sec is demanding you card them, completely unaware of how shitty it is to be carded.

**Comment by Redrover1760** [comment]
Notes:

Mass desubversion can be done with crew with an AI upload built outside the AI's reach, and its not fun for the Antag who stole tech storage board or whatever.

Even if every AI upload is destroyed, law changes can also be done through the AI core itself by clicking on it with a board. You can also do law changes on borgs this way as well with an open cover.

The idea of someone having to steal a board out of secure tech storage creates a trail and a theft. It creates a story and also a goal for crew to get back the board to resecure the AI. Before, this is impossible with the infinite printing boards. Not only with this change an AI will get to enjoy being subverted with the ability of people to unearnedly quietly desubvert the AI in maint is zero, but also subversion requires effort and criminal activity. Its a good change, simple as.

**Review by projectkepler-ru — COMMENTED** [review]
Have the staff in question ever been reprimanded? because that sounds really awful if it was true. 


Regarding the change itself, It should still be possible to obtain more board eitherway, and shouldn't be a limited resource. From my view here it's not about what to do if the upload, the core itself and the spare board are not reachable, because in the case where all of those is true. You usually have a problem that lies beyond the AI being subverted and it may be easier to just obliterate the AI from orbit.  

I'm not opposed to the idea of removing it from the printer as subverting the AI is something I do and I don't enjoy it being easily reverted, but. It's also a risk I take into account for as the AI isn't something that will always be on my side.

**Comment by Alecksohs** [comment]
> Have the staff in question ever been reprimanded? because that sounds really awful if it was true.
> 
> Regarding the change itself, It should still be possible to obtain more board eitherway, and shouldn't be a limited resource. From my view here it's not about what to do if the upload, the core itself and the spare board are not reachable, because in the case where all of those is true. You usually have a problem that lies beyond the AI being subverted and it may be easier to just obliterate the AI from orbit.
> 
> I'm not opposed to the idea of removing it from the printer as subverting the AI is something I do and I don't enjoy it being easily reverted, but. It's also a risk I take into account for as the AI isn't something that will always be on my side.


The staff hasn't been reprimanded to my knowledge. They didn't do anything wrong either. They played the logical conclusion of bad game design. Reprimanding this admin for doing what the game design that maintainers have knowing allowed to stay in the game inspires you to do is silly.

The board should very much be a limited resource. I went in depth as to why it should be a limited resource. If the player wants another board, adminbussing a new board is a valid answer via CC. Otherwise, reprimand the player for powergaming by getting rid of every board, as it could be considered bad faith play. It was brought up by Redrover that the core is a law upload point. Meaning, as long as the AI core exists, it can be uploaded to. This further strengthens the argument that a wireless, instantly constructable with no multitool linking machine to change the laws of the AI being able to be printed an unlimited amount of times is bad game design and has caused lots of grief with silicon players and antag players alike. 

If the AI has been subverted, and you need to get into the AI sat, cutting the power is a valid answer. Paradise Station has moments where the crew will storm the AI sat if the AI is subverted and they can't fix it. Its a fun moment where everyone works together to fix the AI. It inspires RP within the crew and brings risk and reward to the game.

**Comment by Redrover1760** [comment]
> If the AI has been subverted, and you need to get into the AI sat, cutting the power is a valid answer. Paradise Station has moments where the crew will storm the AI sat if the AI is subverted and they can't fix it. Its a fun moment where everyone works together to fix the AI. It inspires RP within the crew and brings risk and reward to the game.

Mhm! When the AI can't be unsubverted remotely by the careful machinations of antagonists, which is quite difficult especially on some maps- The AI discretely removing the upload boards from sat and Core isn't too hard where both are on a dedicated Sat, but when the upload is in the middle of bridge that's pretty damn hard- The crew getting together to unsubvert AI the good ol fashioned way through an AI core raid is a lot more engaging and interactive than upload consoles.

I'm not really sure where one would put another AI upload board outside of AI territory. Perhaps removing the one in the core (Which is basically useless, considering the fact that the AI core is generally right there anyways) and putting it in RD's office is a good way to go about things. Its not super centralized but still in science, and its a secure area which already contains an AI core board, and considering RD is basically head of research and silicons they should be the one who secures the "spare upload board" or so. That makes it so robbing the RD or their office when they leave it in their locker becomes another point for antags to try and subvert the AI or try to prevent the AI from being desubverted, and makes narrative sense.

**Comment by Tupinambis** [comment]
All AI Uploads show up on the GPS, so if someone is spam uploading laws the solution is to simply track the illegal upload via GPS and throw the person who was doing it into the brig. 

This is probably good design but it'd be nice to have a single upload you could buy via uplink, or to maybe remove uploads from the GPS , if we're gonna make them a limited item.

**Comment by Redrover1760** [comment]
To be fair, you can just screwdriver the upload console and it wont have a gps signal anymore. Its not like the boards are tracked, just active consoles.

**Comment by YakumoChen** [comment]
The board itself should be made to be GPS trackable, not the console, they would fix most problems with mass, repeated subversion

Keep in mind making the board unprintable will just result in a traitor securing both upload boards and then the AI being permanently subverted.

**Comment by Alecksohs** [comment]
> The board itself should be made to be GPS trackable, not the console, they would fix most problems with mass, repeated subversion
> 
> Keep in mind making the board unprintable will just result in a traitor securing both upload boards and then the AI being permanently subverted, which in turn will justify round-removing the AI.

The occurrence of this could be seen as bad-faith powergaming just like stealing every techfab board. Otherwise, the crew must now directly interact with the AI if they want to unsubvert it. That is good game design.

**Comment by YakumoChen** [comment]
Powergaming would be command securing the spare board from tech storage

Telling the AI to prevent further law changes after subversion (by having the other board removed) is just good traitor sense

**Comment by Alecksohs** [comment]
> Powergaming would be command securing the spare board from tech storage
> 
> Telling the AI to prevent further law changes after subversion (by having the other board removed) is just good traitor sense

And if done smoothly, forces the crew to interface with the AI itself, storming the core and changing its laws directly, rather than roundabout finding ways to change it. If the sat is rendered useless after storming, relocation of the core to bridge isn't uncommon on other servers.

**Comment by YakumoChen** [comment]
A good antag AI avoids this by just moving their core to somewhere unfindable, like in a walled off maint hole.

I do not think encouraging the AI sat to be fortified (by borgs) and stormed / the crew killing the AI is something that should be encouraged to happen on every other traitor round, instead of just on rounds with malf

**Comment by Alecksohs** [comment]
> A good antag AI avoids this by just moving their core to somewhere unfindable, like in a walled off maint hole.
> 
> I do not think encouraging the AI sat to be fortified (by borgs) and stormed / the crew killing the AI is something that should be encouraged to happen on every other traitor round, instead of just on rounds with malf

Hypothetical rounds are easy to imagine "well what if I just do this" and that isn't how balance should be discussed. Yes, the ideal traitor would perfectly relocate the AI core after silently obtaining and destroying every core board. This is an issue inherent to the AI's conceptual role. That isn't the topic at hand, though. The topic at hand is people mass-creating AI upload boards which catches the AI player in the middle of the mess constantly getting their laws changed. The fact is that if we make AI subversion harder, less antags will do it. That is a good thing.

**Comment by YakumoChen** [comment]
The AI being subverted is a conceptual part of the AI's role. It is also a very powerful role that leans towards helping the station. 

Making the AI harder to subvert skews the power balance and making the boards impossible to create opens up far too many problems with how the balance of upload boards and rogue AIs is handled.

The actual solution is to keep the AI as easy to subvert as it is, and make catching rogue uploaders easier.

**Comment by YakumoChen** [comment]
This makes it incredibly easy for one party to control both upload boards. The AI can effectively stonewall stealing the tech storage upload simply by keeping the door bolted and keeping a camera trained on it as well.

One of the most integral parts of interacting with the AI is that one should never be sure if the AI can be trusted. This is a paranoia game.

If it is a simple matter to determine if the AI is at risk of subversion simply by tracking the exactly 2 upload boards that can exist, it utterly destroys any semblance of paranoia, and ultimately is bad for the game.

**Comment by Alecksohs** [comment]
> The AI being subverted is a conceptual part of the AI's role. It is also a very powerful role that leans towards helping the station.
> 
> Making the AI harder to subvert skews the power balance and making the boards impossible to create opens up far too many problems with how the balance of upload boards and rogue AIs is handled.
> 
> The actual solution is to keep the AI as easy to subvert as it is, and make catching rogue uploaders easier.

Why does the AI need to be easy to subvert? The AI isn't an antag's pocket tool. They're a player. A player who follows their laws. As shown by other stations, making it hard doesn't disrupt game balance in the slightest. It improves game balance and allows AI players to enjoy their rounds far more. Disrupting mass-creation of AI upload boards prevents the critical balancing flaw of an infinite struggle between the command uploading AI reset, and the antagonist uploading custom laws. Limiting them to what exists on the map inversely fixes many problems that is caused by having them as infinite resources.

I don't see this as a valid solution. I know many players who don't either. Making "rogue uploaders easier to capture" is simple in concept, but then you'd have to balance literally every TG item so that they're "easier to catch", which is immensely silly and out of scope of this PR. The fact that an antagonist could keep printing them and just use broken items to permanantly evade and then destroy the techfabs so that you can't fix it, and boom you're in the same problem.

This isn't a one way bridge. This is the nature of limited resources.

**Comment by YakumoChen** [comment]
> Why does the AI need to be easy to subvert? 

The tradeoff for being the most powerful role on the station is that it should be difficult for the station to keep its allegiance. Being subverted is a core part of playing AI and the primary risk one should expect to face while playing as one.

**Comment by Alecksohs** [comment]
> > Why does the AI need to be easy to subvert?
> 
> The tradeoff for being the most powerful role on the station is that it should be difficult for the station to keep its allegiance. Being subverted is a core part of playing AI and the primary risk one should expect to face while playing as one.

The current system isn't risk. When said "risk" that you identify it as is that the AI gets round removed for bad game design, it should be fixed. This PR fixes it. No more unlimited boards. You can go ahead and PR board tracking, sure. But that doesn't solve the issue of infinitely creatable boards. The boards, like techfabs, should be a limited resource due to how powerful they are. The "core part" of playing AI currently is heavily cheapened by how ridiculously easy it is to subvert an AI. No player has fun when the AI is constantly having it's laws changed because some antagonist has printed 90 boards and stashed them around the station.

**Comment by YakumoChen** [comment]
If an AI player dislikes the idea of being spontaneously switched to serve a different faction with no way they can predict or track

The best solution would be for them to not play AI.

Again, making boarda trackable solves all issues with catching rogue uploaders, without needing to make the AI impossible to balance as far as subversion.

**Comment by YakumoChen** [comment]
> The "core part" of playing AI currently is heavily cheapened by how ridiculously easy it is to subvert an AI.

This is in fact what makes it a core part of playing AI. Being easily subverted is the entire point.

**Comment by Redrover1760** [comment]
>Making the AI harder to subvert skews the power balance and making the boards impossible to create opens up far too many problems with how the balance of upload boards and rogue AIs is handled.

You don't understand, it makes unsubverting AI much harder too. It makes AI law changes happen less, in both directions. Less people easily subvert the AI with zero effort. Less random roboticists print AI upload boards and a law board and go into maint and reset the AI. I have done this before on tgstation, its pathetically easy for anyone with science access or even engineering to subvert or unsubvert an AI.

**Comment by Alecksohs** [comment]
> If an AI player dislikes the idea of being spontaneously switched to serve a different faction with no way they can predict or track
> 
> The best solution would be for them to not play AI.
> 
> Again, making boarda trackable solves all issues with catching rogue uploaders and the "30 law changes" problem, without needing to make the AI impossible to balance as far as subversion.

An AI player doesn't have to dislike being spontaneously switched to dislike being changed back and forthe back and forthe in a round without a lick of roleplay, and then be round removed by an admin because the antagonist player can produce unlimited boards. Refer back to the entire discussion as to why that is bad. You've been given reasons why your answer isn't a workable solution. It doesn't solve anything. You haven't said why removing AIs from printable sources is so impossible to balance. The problem we are currently facing is that AI boards are too easy to obtain, making AIs be yanked back and forthe wirelessly making them barely a player. There is no paranoia nor mystery in an AI constantly being subverted. When an **admin** thinks the best way to deal with a problem of an AI being 24/7 resubverted, with the security team overwhelmed by the antagonist's metaplaying balance, is to round remove the player, we have a problem. The problem isn't with the admin choosing to card the AI. It is beyond understandable at that point. Their reason made sense. The fact of the matter is that it is too easy to hack an AI.

**Comment by YakumoChen** [comment]
That all sounds like issues unrelated to your PR or why it's good for the game.

The best way to deal with upload wars is to just follow the GPS

**Comment by Alecksohs** [comment]
> That all sounds like issues unrelated to your PR or why it's good for the game.
> 
> The best way to deal with upload wars is to just follow the GPS
> 
> The AI should be easy to subvert, otherwise it should not be the powerful role it is.

The AI shouldn't be easy to subvert. It should require planning to have the amount of power that you describe on your side. I don't see how you're missing this. Every other server without AI boards have perfectly healthy AI gameplay. We clearly don't.

**Comment by YakumoChen** [comment]
> The AI shouldn't be easy to subvert. It should require planning to have the amount of power that you describe on your side. I don't see how you're missing this. Every other server without AI boards have perfectly healthy AI gameplay. We clearly don't.

I disagree. The AI is too powerful of an asset to keep reliably on the side of the station, and it ruins the paranoia of the AI's trustworthiness.

Essentially this leads to a loop of AI is subverted once, moved to the bridge where it can never be subverted again, and the round intrigue in silicons becomes static.

**Comment by YakumoChen** [comment]
Or someone steals the one actually stealable board on the station and then starts a round-long upload war or something and... oh, you don't actually solve your issue, do you?

**Comment by Odairu** [comment]
> All AI Uploads show up on the GPS, so if someone is spam uploading laws the solution is to simply track the illegal upload via GPS and throw the person who was doing it into the brig.
> 
> This is probably good design but it'd be nice to have a single upload you could buy via uplink, or to maybe remove uploads from the GPS , if we're gonna make them a limited item.

this is a nice thought, however, unless you're constantly holding a GPS its not going to do you any good, because what happens is you make the upload, it pops up on GPS, you put the laws, you decon the upload, and it disappears from the GPS. The whole process takes about 7 seconds from when it appears to when it disappears

**Comment by YakumoChen** [comment]
> > All AI Uploads show up on the GPS, so if someone is spam uploading laws the solution is to simply track the illegal upload via GPS and throw the person who was doing it into the brig.
> > This is probably good design but it'd be nice to have a single upload you could buy via uplink, or to maybe remove uploads from the GPS , if we're gonna make them a limited item.
> 
> this is a nice thought, however, unless you're constantly holding a GPS its not going to do you any good, because what happens is you make the upload, it pops up on GPS, you put the laws, you decon the upload, and it disappears from the GPS. The whole process takes about 7 seconds from when it appears to when it disappears

It sounds like you should start troubleshooting the problem by fixing this issue before the nuclear option that doesn't actually resolve your problem

**Comment by YakumoChen** [comment]
> 2: Making the boards tracked instead of just the consoles would also be a good immediate change

Do that first, and PRs like this can come if it is still somehow a problem (despite this being the actual problem, not the ease of printing boards)

> 3: AI policy has changed so that AI's can't even tell people no

Irrelevant 

> Its completely unbalanced on side of the antags

Good? Antags are given the tools to sabotage, this is the whole point

**Comment by ReturnToZender** [comment]
## WARNING: Invalid research design with ID aiupload detected in node Artificial Intelligence[ai_basic] removed. in code/controllers/subsystem/research.dm at line 205 src: Research usr: .

**Comment by Odairu** [comment]
> WARNING: Invalid research design with ID aiupload detected in node Artificial Intelligence[ai_basic] removed. in code/controllers/subsystem/research.dm at line 205 src: Research usr:
> 
> Fails this test :(

Ill make a PR that does the samething but better:tm:

**Comment by Alecksohs** [comment]
> WARNING: Invalid research design with ID aiupload detected in node Artificial Intelligence[ai_basic] removed. in code/controllers/subsystem/research.dm at line 205 src: Research usr:
> 
> Fails this test :(



> > WARNING: Invalid research design with ID aiupload detected in node Artificial Intelligence[ai_basic] removed. in code/controllers/subsystem/research.dm at line 205 src: Research usr:
> > Fails this test :(
> 
> Ill make a PR that does the samething but better:tm:

Nothing wrong with that. My first modularization test. If someone else can handle the code far better I have zero problem with it. I wanted to start the discussion back up, though.

**Comment by Alecksohs** [comment]
> WARNING: Invalid research design with ID aiupload detected in node Artificial Intelligence[ai_basic] removed. in code/controllers/subsystem/research.dm at line 205 src: Research usr:
> 
> Fails this test :(

My fault, I forgot to remove that. I'll fix that real quick.

**Comment by pixelkitty286** [comment]
You know if you remove AI and cyborg uploads and someone needs to do a law change to them to un-subvert them it means they will 100% be round removed and I do believe silicon players will be very angry to know they can't be revived for the entire round at any point because their laws are permanently broken. I do believe the only other way to "fix laws" is to be completely disassembled and reassembled to hopefully un-fuck the laws if the AI is not malf because borgs sync to AI on assembly.

**Comment by aKromatopzia** [comment]
> You know if you remove AI and cyborg uploads and someone needs to do a law change to them to un-subvert them it means they will 100% be round removed and I do believe silicon players will be very angry to know they can't be revived for the entire round at any point because their laws are permanently broken. I do believe the only other way to "fix laws" is to be completely disassembled and reassembled to hopefully un-fuck the laws if the AI is not malf because borgs sync to AI on assembly.

there are ways to unsubvert the AI which don't include the upload.

**Comment by StrangeWeirdKitten** [comment]
#1339 see this PR why

**Pull request closed without merging**
