### PR TITLE
Resizable Viewport

### PR DESCRIPTION
**Pull request by nevimer**
## About The Pull Request

Makes the game more playable on anything that isn't a 1920x1080 monitor. Solves the widescreen issue. Brings the game to somewhat modern game capabilities. 
http://streamasaurus.com/sharing/dreamseeker_Kb8n5A8LuL.mp4

This is totally not modular. 

## Changelog

:cl:
code: Edits the skin.dmf file to support viewport changes.
refactor: Changes how the viewport code works radically. You can now scale your game and panels to any size/resolution combo you feel comfortable.
config: Added new config limits for the variable viewport.
server: Added new config limits for the variable viewport.
/:cl:

### CODE REVIEW

**Comment by ReturnToZender** [comment]
I'd really like to see this added, personally. :)

I heard TGstation didn't accept it because reasons, but as someone with a big monitor, I'd love to be able to zoom in and have the HUD adjust dynamically.

**Comment by BurgerLUA** [comment]
Did some testing on this per request and the HUD is very messed up. Here is a quick diagnosis so far:

For screenlocs:

CENTER works properly.
LEFT works properly.
TOP works properly.

RIGHT does not work properly.
BOTTOM does not work properly.

WEST, NORTH, EAST, SOUTH all work properly.

Not sure what the cause of this, but it's pretty weird. BOTTOM is apparently now the same as TOP.

**Comment by Majkl-J** [comment]
Stale. Reopen when you work on this again

**Comment by Majkl-J** [comment]
You know the drill, stale

**Pull request closed without merging**
