### PR TITLE
Allows HFZ to have digitigraded legs.

### PR DESCRIPTION
**Pull request by Adrian16199**
(Hopefully)

## About The Pull Request
As the title implies.

## Why It's Good For The Game
Surely an anthro could be a zombie aswell, so i say let them.

## Proof Of Testing
Uh- *Im sure it will be fine*

## Changelog

:cl:
add: HFZ can have digitigrade legs now.
/:cl:

### CODE REVIEW

**Comment by Adrian16199** [comment]
> make your changelog just smth like add: HFZ can be digitigrade
> 
> Also, please don't edit core code. Put it in modular_zubbers/master_files

oh uh-
Sorry .w.

**Comment by projectkepler-ru** [comment]
does anyone actually know if this work

**Comment by StrangeWeirdKitten** [comment]
fix linters

**Comment by aKromatopzia** [comment]
PR's still open so im checking in to say you can fix linters by moving this stuff from zombies.dm into the already-existing zombie.dm, or updating the dme to have #include "modular_zubbers\code\modules\mob\living\carbon\human\species_types\zombies.dm"

**Comment by Adrian16199** [comment]
> PR's still open so im checking in to say you can fix linters by moving this stuff from zombies.dm into the already-existing zombie.dm, or updating the dme to have #include "modular_zubbers\code\modules\mob\living\carbon\human\species_types\zombies.dm"
> 
> As it stands currently the file isn't being read by the executable.

I was told to uh, make it into a bubber file to not mess with the main files so i will try the second one

**Comment by aKromatopzia** [comment]
> I was told to uh, make it into a bubber file to not mess with the main files so i will try the second one

oh yeah so long as it's in modular_bubber it'll be a bubber file, zombie.dm is free to edit for this server's purposes. I think I first left that comment when you edited the zombie.dm in core tg code

**Comment by aKromatopzia** [comment]
It's functional yup

**Review by StrangeWeirdKitten — APPROVED** [review]

**Pull request merged**
