### PR TITLE
restaurant portal can be moved w/ wrench

### PR DESCRIPTION
**Pull request by Daved27hundred**
## About The Pull Request

The portals that spawn the tourist bots can be unbolted from the floor, pulled around, and rebolted somewhere else.

## Why It's Good For The Game

These things are immovable and it gets annoying when you have to build around them because of that, especially if you don't even use them.

I initially made them destructible but this is a far better fix

## Changelog

:cl:
:qol: restaurant portal can bolted and unbolted
/:cl:

### CODE REVIEW

**Comment by StrangeWeirdKitten** [comment]
> Alternatively, I could keep the flag and make the thing boltable/unboltable if shown how

Just make it unboltable.

**Review by StrangeWeirdKitten — CHANGES_REQUESTED** [review]
Just make it unboltable since it's not an item you can ever reconstruct.

**Comment by Daved27hundred** [comment]
ok i think this should work, but Im gonna need to look at it ingame. Let's see if I remember how to boot up my own world again.

**Comment by Daved27hundred** [comment]
image
Success! I'll change the thing.

**Pull request merged**
