### PR TITLE
Reverts "Subverts Democracy and destroys the Meta-Icebox-Delta voting cycle by adding negative voting multipliers to recently played maps. (#554)"

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Reverts #554

## Why It's Good For The Game

Ok so basically since the PR, people haven't really been voting anymore because they feel like their vote doesn't matter as much (It literally and technically doesn't) and as a result, people have been only voting for meme-tier maps like Tramstation and Birdshot because one guy who isn't planning on voting next round spams 'VOTE BIRDSHOT YEAAAAAAAAAAAAAAH" and that's the only time people vote.

A unironic cycle of Icebox-Metastation-Deltastation is better than an ironic cycle of Kilo-Tram-Birdshot.

## Changelog

:cl: BurgerBB
del: Removes the 75% weight for recently played maps.
/:cl:

### CODE REVIEW

**Comment by ReturnToZender** [comment]
This is the funniest burger PR please speedmerge

**Comment by Majkl-J** [comment]
Wh could've seen this one coming

**Comment by BurgerLUA** [comment]
> Wh could've seen this one coming

No one.

The concern was that occassionally a few maps that not many people liked would get put into rotation. There was no concern about it actually causing people not to vote for maps anymore.

**Comment by Majkl-J** [comment]
> > Wh could've seen this one coming
> 
> No one.
> 
> The concern was that occassionally a few maps that not many people liked would get put into rotation. There was no concern about it actually causing people not to vote for maps anymore.

People literally complained that it will make votes not matter on the original PR.

**Comment by BurgerLUA** [comment]
> > > Wh could've seen this one coming
> > 
> > 
> > No one.
> > The concern was that occassionally a few maps that not many people liked would get put into rotation. There was no concern about it actually causing people not to vote for maps anymore.
> 
> People literally complained that it will make votes not matter on the original PR.

no they didn't

**Comment by StrangeWeirdKitten** [comment]
most of this is off-topic, and I've marked it as such. But I'll merge this.

**Pull request merged**
