### PR TITLE
Upstream 24 10a

### PR DESCRIPTION
**Pull request by Majkl-J**
Oh dear lord help us all

### CODE REVIEW

**Comment by Swiftfeather** [comment]
waterpig is cracked, he's cooking with gas

**Comment by Majkl-J** [comment]
> waterpig is cracked, he's cooking with gas

I left the gas on and I'm about to ignite the stove (git merge --ff-only)

**Comment by Arturlang** [comment]
Holy

**Comment by StrangeWeirdKitten** [comment]
The reckoning.

**Comment by Majkl-J** [comment]
I'm boutta mergeeeee

**Pull request merged**
