### PR TITLE
Reverts some nerfs to the bulldog

### PR DESCRIPTION
**Pull request by GoreDem**
## About The Pull Request
Removes the untoggleable burst fire and extremely long fire delay (the low fire delay was the thing that made it good) from the bulldog
Edit: Apparently the burst fire is toggleable, might add it back again to see how stupid the gun becomes with it

Also babby's first pr or second
I don't rmemeber

## Why It's Good For The Game
Bulldog is in a weird spot where it fires really slowly and has a burst on top of it so the burst accomplishes nothing, this was due to 2 prs nerfing/buffing it on SR/tg.

## Proof Of Testing
I have not tested this pr but it's like two lines

## Changelog

:cl:
add: buffed bulldog back to a usable state
/:cl:

### CODE REVIEW

**Comment by AllCorruptingWyrm** [comment]
What are the stats compared to the bartender shotgun again?

**Comment by GoreDem** [comment]
> What are the stats compared to the bartender shotgun again?
Doesn't matter but very much better

**Comment by GoreDem** [comment]
> > What are the stats compared to the bartender shotgun again?
> 
> Doesn't matter but very much better

For reference: it has a double-decker magazine and a 1.2 damage MULTIPLIER, way slower firing speed and burst fire (this pr changes the latter two)

**Review by projectkepler-ru — CHANGES_REQUESTED** [review]
do this upstream or do this modularly

**Comment by GoreDem** [comment]
> do this upstream or do this modularly

How would I do it modularly? (Sorry babby's first pr)

**Comment by projectkepler-ru** [comment]
> > do this upstream or do this modularly
> 
> How would I do it modularly? (Sorry, babby's first pr)

You can have the code path and the variable you want changed in a modular bubber folder

**Comment by StrangeWeirdKitten** [comment]
Sure

**Pull request merged**
