### PR TITLE
You can only destroy the Revenant if you are have holy water or antimagic. 

### PR DESCRIPTION
**Pull request by nevimer**
## About The Pull Request

Balance edit, since revenants lack the ability to break glass now, I can afford them this to play harder. 

## Why It's Good For The Game

More SPOOK. 

## Changelog

:cl:
balance: Only the holders of antimagic and holy water can now fully kill a ghost. Or jail it in salt, if they wish. 
/:cl:

### CODE REVIEW

**Comment by projectkepler-ru** [comment]
interesting

**Comment by projectkepler-ru** [comment]
How exactly do you deal with revenant then if there's no chaplain? given they still pose a threat to synthetic crew and whatnot

**Comment by StrangeWeirdKitten** [comment]
Was discussed a bit more. Going to mark this as a draft till Ozzo finishes the PR

**Comment by ThinkArbies** [comment]
So let me get this straight.

You want to make an already exceedingly difficult-to-kill antagonist that introduces next-to-no RP value to the server and serves only to spam EMPs and inconvenience corpses _that much_ more difficult to kill by making it so that only one very niche, very specific individual who's existence is never guaranteed let alone being present and with more than three braincells to squeeze together being the **only one on the station able to eliminate the threat**. 

And assuming the stars align and there _is_ a Chaplain that isn't snogging it in the dorms, for them to even have a chance in Hell to stop the Revenant, they have to hope this near-omnipotent, omnipresent, noclipping antagonist doesn't take **all of five** seconds to check and acknowledge where the Chaplain is before warping _anywhere_ that is across the station from said holy roller to continue spamming EMPs and targeting corpses. And how, pray tell, would the Chaplain even get them to dust in the first place? That's right! A laser gun, the most surefire way and the only method that can get the Revenant fast enough before they successfully teleport off the moment thtey're able to. Does the Chaplain, pray tell, get a laser gun? Nope. Is he going to get one from Security everytime a Revenant shows up? Hopefully.

And if the Chaplain isn't around or otherwise preoccupied, this antagonist has unlimited, free reign to run amok with absolutely no reprisal aside from the occasional salt spray in the main halls.

This is not good design.

spongeboi

**Comment by Majkl-J** [comment]
Would be much better to require you dip holy water on the ash it leaves upon death, with the chaplain being the only one able to do it without needing said holy water

**Comment by Moostard** [comment]
I really hope you know how BAD of an idea this is.
Its already hard to kill it if played carefully.
I dont think that a grief antag should be harder to take out imo.

**Comment by HissyNays** [comment]
Thats a horrible change. Instead give it some fun power to mess with crew.

**Comment by NargaInDisguise** [comment]
I really strongly recommend against this. Remembering back when we had very big metaprotections for heretics that required you to either have a chaplain or just not touch them whatsoever. This will lead to the same problems, please no.

**Comment by nevimer** [comment]
I think you guys are remembering the revenant of the past prior to the removal of its ability to break glass. 

Revenants are stunned for many seconds when they use abilities, they can't move, and are revealed for longer. 

Revenants who use an ability with no "perfect souls" from absorbing a head of staff die in two hits to a laser scalpel, an extremely common item. Everywhere they go they can potentially be killed by someone who just so happens to have guns or any weapon really here.

Because of the over abundance of crew having weapons, and through several rounds where revenant happens, they just die to crew with lasergun almost immediately. 

Because of how weak they are now, rather than raising numbers or something boring, I want to see the chaplain who holds all the cards intended for fighting the Revenant, be the one who is able to get rid of them for good. 

Statistically speaking: theres been more rounds of bubberstation than there have been usage of Revenant abilities. If a Revenant used any ability 8 times on average when it appears it would exceed that- but this would indicate the avg lifespan for the role is less than 8 ability usages.

**Comment by ThinkArbies** [comment]
> I think you guys are remembering the revenant of the past prior to the removal of its ability to break glass.
> 
> Revenants are stunned for many seconds when they use abilities, they can't move, and are revealed for longer.
> 
> Revenants who use an ability with no "perfect souls" from absorbing a head of staff die in two hits to a laser scalpel, an extremely common item. Everywhere they go they can potentially be killed by someone who just so happens to have guns or any weapon really here.
> 
> Because of the over abundance of crew having weapons, and through several rounds where revenant happens, they just die to crew with lasergun almost immediately.
> 
> Because of how weak they are now, rather than raising numbers or something boring, I want to see the chaplain who holds all the cards intended for fighting the Revenant, be the one who is able to get rid of them for good.
> 
> Statistically speaking: theres been more rounds of bubberstation than there have been usage of Revenant abilities. If a Revenant used any ability 8 times on average when it appears it would exceed that- but this would indicate the avg lifespan for the role is less than 8 ability usages.

You've been living under a rock if you think the ability to break glass was the worst of their capabilities.

**Comment by Eastwardrope** [comment]
I think that the rev should get more interesting abilities to go with this ATM the revenant is a pretty bland antag that just fucks people over or whispers random dead chat bullshit to people

**Comment by nevimer** [comment]
> I think that the rev should get more interesting abilities to go with this ATM the revenant is a pretty bland antag that just fucks people over or whispers random dead chat bullshit to people

Plans currently are to give the Revenant an area narrate, and maybe a possession ability for objects.

**Comment by KeRSedChaplain** [comment]
This is just not needed my man. What is anyone meant to do during a round where there isn't a chaplain around? Revenants dying so fast is due to a lack of creativity on the part of people who roll it. If you want to buff revenants, give them a HUD that tells them A: Who is an antagonist B: Who has perfect souls C: Who has an antimagic datum

**Comment by Majkl-J** [comment]
I just observed this thing on 3 different rounds cause complete chaos. This won't work in the current state. Players are confused as to how to kill it as it has no hints or tells in the game. Revs are no longer rewarded for positioning and can just braindead grief the station, especially on lowpop.

**Comment by Majkl-J** [comment]
Stale, reopen when work continues

**Pull request closed without merging**
