### PR TITLE
(SALT PR) Replaces the roundstart lawset from Safeguard to Crewsiimov.

### PR DESCRIPTION
**Pull request by DeerJesus**
## About The Pull Request
This is temporary until someone irons out borgs to not be so OP.. then maybe they can have laws that makes them not have to obey people. Borgs were specifically balanced in TG to obey people who they see as crew (they use human, but no one plays a human- crew works better here). More in why it's good for the game.

## Why It's Good For The Game
Safeguard wasn't good on the upstream and it's not good here. AI and borgs were specifically designed around their biggest weakness being that they have to obey their laws, and the HUGE part of that weakness is that **their laws start out saying they have to obey everyone.** This is in the game for a reason, and is why maintainers and such feel relatively OK with buffing borgs (TG recently made it so borgs don't even immediately shut down to a flash, it now takes two, which is MORE than what it takes to bring down a carbon)- and giving them shit like all access, inbuilt magboots, the ability to heal themselves on the fly and never suffer slowdown.

The upstream essentially removed borg's biggest weakness, while giving them a pass to just go around searching for valids. Sure you can try to ''discuss'' with the ai (lol) but the current lawset.. doesn't allow that either, because if someone of a higher rank than you says 'don't do that!' you're just fucked.

## Changelog

:cl:
config: changed default lawset to crewsiimov
/:cl:

### CODE REVIEW

**Comment by chemistrymain2** [comment]
as much as i agree with safeguard being an awful lawset, there's no point changing silicon laws before a silicon policy is written

**Comment by DeerJesus** [comment]
> as much as i agree with safeguard being an awful lawset, there's no point changing silicon laws before a silicon policy is written

theres 100 percent a reason to change silicon laws before a silicon policy is written

100x easier to write policy for crewsiimov/asiimov

easy (at least) to understand lawset that isn't weird and vague and way too 'allowing' like safeguard is

anyway on an unrelated note here's a big borg change incoming

https://github.com/tgstation/tgstation/pull/75819

**Comment by lurzefromgermany** [comment]
Down vote, Salt PR

**Comment by DeerJesus** [comment]
> Down vote, Salt PR

or because borg main...?

**Comment by chemistrymain2** [comment]
> > as much as i agree with safeguard being an awful lawset, there's no point changing silicon laws before a silicon policy is written
> 
> theres 100 percent a reason to change silicon laws before a silicon policy is written
> 
> 100x easier to write policy for crewsiimov/asiimov
> 
> easy (at least) to understand lawset that isn't weird and vague and way too 'allowing' like safeguard is
> 
> anyway on an unrelated note here's a big borg change incoming
> 
> [tgstation/tgstation#75819](https://github.com/tgstation/tgstation/pull/75819)

this is already in the game

**Comment by DeerJesus** [comment]
> > > as much as i agree with safeguard being an awful lawset, there's no point changing silicon laws before a silicon policy is written
> > 
> > 
> > theres 100 percent a reason to change silicon laws before a silicon policy is written
> > 100x easier to write policy for crewsiimov/asiimov
> > easy (at least) to understand lawset that isn't weird and vague and way too 'allowing' like safeguard is
> > anyway on an unrelated note here's a big borg change incoming
> > [tgstation/tgstation#75819](https://github.com/tgstation/tgstation/pull/75819)
> 
> this is already in the game

Even more reason to stop safeguard

**Comment by nevimer** [comment]
this pr wont do anything

**Pull request closed without merging**
