### PR TITLE
Biodome Tweaks

### PR DESCRIPTION
**Pull request by TripleShades**
## About The Pull Request
Fixes things that were caused as a result of the previous Biodome pr I made: https://github.com/Bubberstation/Bubberstation/pull/318

## Changelog

:cl:
add: [Biodome] Missing main hall decal
add: [Biodome] Additional main hall direction indicators pointing to Science
add: [Biodome] Directional indicators for the Transportation Tube platforms
add: [Biodome] Air alarms to primary Departures area
add: [Biodome] Extra lights to primary Departures area
add: [Biodome] Air alarms to lower Security area
add: [Biodome] Airlock access check to Perma's water supply and APC room.
add: [Biodome] Missing plating underneath an airlock inside of maints
add: [Biodome] Missing wire connections to the Gulag Shuttle Dock
add: [Biodome] Missing shutters button on outside of Mech Bay
add: [Biodome] Shutters and shutter button to Research Director's office
add: [Biodome] New wall secret to compensate for layout shifting
add: [Biodome] Security now has holding cells with timers instead of The Dunk Zone
add: [Biodome] Security now has a static redsec vendor as requested
add: [Biodome] Actual solar panel assemblies to the various solar array accesses
del: [Biodome] Duplicate pipe in Mining lobby
del: [Biodome] Tcomm upper floor relay as it is no longer required for comms to work on multi-z
del: [Biodome] Duplicate keycard auth in Captain's Quarters and Bridge
fix: [Biodome] AI Sat cams are no longer on the ss13 camera network
fix: [Biodome] Boat tram aft button now properly calls the boat
tweak: [Biodome] CentComm flooring borders are now unified
tweak: [Biodome] Swapped the HoP's fax machine with the boxes next to it so you can now reach both
tweak: [Biodome] Mining lobby rooms are now under a different layout and no longer space the area round start
tweak: [Biodome] The Turbine Engine Room has been shifted down so it no longer burns a hole in Engineering's ceiling
tweak: [Biodome] Security's Locker Room entryway has been expanded by one because the automapper sometimes spawns the reloading machine in a poor spot
/:cl:

### CODE REVIEW

**Comment by nevimer** [comment]
Did you get the duped pipes in mining too?

**Comment by TripleShades** [comment]
> Did you get the duped pipes in mining too?

Only found one pipe, but it is now gone.
If there's anything else to report I would love to fix it while this is up, please.

**Comment by nevimer** [comment]
> > Did you get the duped pipes in mining too?
> 
> Only found one pipe, but it is now gone.
> If there's anything else to report I would love to fix it while this is up, please.

There are two map linting fails, one for a space turf and a few for an unconnected wire

**Comment by TripleShades** [comment]
> > > Did you get the duped pipes in mining too?
> > 
> > 
> > Only found one pipe, but it is now gone.
> > If there's anything else to report I would love to fix it while this is up, please.
> 
> There are two map linting fails, one for a space turf and a few for an unconnected wire

Found them, thank you.
As far as I can tell it looks as good as it'll get (and I wish we could figure out/fix why we're still getting other failures)

**Comment by Profakos** [comment]
"Airlock access check to Perma's water supply and APC room." Hello biodome maker here, I am just looking in these PRs to see ways I can improve my map that I haven't noticed (I have backported many things now! And eventually remake the map so people will be less likely to fall into space when a maint bomb goes off) 
Anyways,  that water and apc room is the radstorm safe area, so if you think Prisoners shouldn't access it, you might need a separate rad shelter, if there isn't one yet.

**Comment by TripleShades** [comment]
> radstorm safe area
Radiation storms do not randomly roll, they are admin-spawned only as of right now. Also, the change in access was to create parity between other maps that have "maint" rooms for the prison.

**Comment by Profakos** [comment]
I see, that explains it.

**Comment by Cyprex** [comment]
I think perma being so vulnerable is really good and interesting, and it shouldn't be hugboxed. To that end I'm against the water supply airlock being restricted from prisoners, the exposed APCs are nice too.

**Comment by Cyprex** [comment]
> The Turbine Engine Room has been shifted down so it no longer burns a hole in Engineering's ceiling

That's hilarious

**Comment by TripleShades** [comment]
> I think perma being so vulnerable is really good and interesting, and it shouldn't be hugboxed. To that end I'm against the water supply airlock being restricted from prisoners, the exposed APCs are nice too.

The only station that allows prisoners into the APC is Meta, for some reason, but I have a feeling it is due to the age of the map.
I would be willing to change it back, since nobody has done anything horrible with access to it yet.

**Comment by nevimer** [comment]
merging for the upstream merge

**Pull request merged**
