### PR TITLE
-  Changes Health modifier from 1.35 to 1

### PR DESCRIPTION
**Pull request by Yanziko**
## About The Pull Request

 All this does is make it so the carbon health is no longer at the 135 that Skyrat had it set at that we for some reason use. 

## Why It's Good For The Game

Thanks to Skyrat placing us on 135, we don't exactly have the same balance that we rely on from TG. This just puts us back to the intended balance that we are forced to update on. As far as I can tell, little has to be changed in regards to most weapons as TG ones are unchanged. 

## Proof Of Testing
image

image

## Changelog

:cl:
balance: human_health_modifier is now no longer 1.35, it is now 1.

/:cl:

### CODE REVIEW

**Review by Majkl-J — COMMENTED** [review]
Sure, we can give it a shot

**Comment by nevimer** [comment]
There is so much more that needs to be changed than just this number. Tons of skyrat over rides and mechanics that were changed.. A simple number edit will not do.

**Review by nevimer — CHANGES_REQUESTED** [review]
You need to find every skyrat override and revert it to tg, aswell. I also think TG balance sucks majorly and you're wasting your time trying to get back to that awful mess.

**Comment by Yanziko** [comment]
I'll see what I can do about the overrides, but I'd need to be given a bit more information about what I'm looking for. From what I could tell, it worked mostly fine? Every single weapon did their appropriate damage and the such, so I'm unsure what I'm looking for.

**Comment by Yanziko** [comment]
Ah, wait, I'm an idiot hah. Okay, sorry, bit new to github, I'll work on it.

**Comment by Yanziko** [comment]
I disagree that it's a major buff that will completely destroy any tactical gameplay.  For example, for the laser gun, the classic shooter, it will now take four shots instead of five. Huge buff.  I do have to agree ballistics need to be rebalanced though, but I personally am not sure what values would work best and would also need some more testing beyond the shooting I did with guns.

**Comment by BurgerLUA** [comment]
Keep in mind that people will not be happy with this change. It will kind of like be reducing movespeed by 25% or something similiar. People WILL feel it and will feel bad after a result.

**Comment by Yanziko** [comment]
I do understand that, but I would like to see if this server could be compatible with it. Also, we kind of already did reduce movespeed if I recall, albeit not to that amount, but I don't see many complaints about it. I also did some further testing and this will make batons two hit down. I'll fix it if requested but it is sort of part of the package? Iunno.

**Comment by nevimer** [comment]
Keep in mind good mood health is 162.5. It's 135 for bad moods.

**Comment by BurgerLUA** [comment]
> > Keep in mind good mood health is 162.5. It's 135 for bad moods.
> 
> Holy fuck

In 70% of cases that doesn't matter since a lot of sources of damage can give you bad moodlets (dismemberment, not enough oxygen, etc etc)

**Comment by Tupinambis** [comment]
Iffy on this, I feel like there's value to the increased TTK in that it reduces the value of first hits and stuns, slows, whatever to a lesser extent, and it generally serves TG mechanics like wounds better (even if I don't like them). More room for counterplay and turning the tables too.

I think just buffing stuff that's been left behind by the change is a better solution than basically full reverting to TG balance which isn't ideal to begin with.

**Comment by Tupinambis** [comment]
> Keep in mind good mood health is 162.5. It's 135 for bad moods.

Not completely related, but I do think this is a really bad feature that makes balance harder and makes the game feel less consistent in general.

**Comment by Yanziko** [comment]
> I think just buffing stuff that's been left behind by the change is a better solution than basically full reverting to TG balance which isn't ideal to begin with.

So, I actually wouldn't mind this being done, and if so, I would close the PR despite me actively working on fixing it, but from everything I've looked at in the code, the weapons seem to all have a base damage of somewhere around 25. The issue is purely that Skyrat guns are... almost all ballistic, giving massive wounds. If you also look at #1066, the guns there are rather unbalanced, in that they are unfairly more modular and self charging compared to the original weaponry they had (the SC-1).

**Comment by Formerxboxgamer** [comment]
> This is a major buff to nearly every antagonist short of traitor, including much more difficult to manage antagonists like blobs, spiders, dragon, etc
> 
> This will drastically increase the lethality of gameplay and will reduce combat to much less tactical play.

Crew needs to learn to fight this stuff and can do it at lower health pools. Fights on tg vs things like spiders and dragons are based on tactical shit like positioning and momentum. The soft skills that no one really thinks about that make space combat so good are way more important when you can’t face check hostiles with lots of health, armor, and high damage ballistics

**Comment by YakumoChen** [comment]
> If you also look at https://github.com/Bubberstation/Bubberstation/pull/1066, the guns there are rather unbalanced, in that they are unfairly more modular and self charging compared to the original weaponry they had (the SC-1).

Almost all the skyrat guns aren't station-available to Bubber, the best things we have are the MCR (not included in the laser capacity PR and fairly easy to balance if needed) and smiting stuff / cargo blades

As well as the ballistics which have already had a fair balance pass on them

**Comment by YakumoChen** [comment]
> > This is a major buff to nearly every antagonist short of traitor, including much more difficult to manage antagonists like blobs, spiders, dragon, etc
> > This will drastically increase the lethality of gameplay and will reduce combat to much less tactical play.
> 
> Crew needs to learn to fight this stuff and can do it at lower health pools. Fights on tg vs things like spiders and dragons are based on tactical shit like positioning and momentum. The soft skills that no one really thinks about that make space combat so good are way more important when you can’t face check hostiles with lots of health, armor, and high damage ballistics

This comment doesn't accomplish anything constructive, Bubber has a lower skill floor than TG, and a high percentage of crew doesn't contribute to high threat antags like Blob that would normally have the entire crew rallied on TG

**Comment by Formerxboxgamer** [comment]
Saying that the layers here are just worse is frankly just factually not true. Not everyone on upstreams are giga gamers and usually rounds are dictated by 3-5 people doing the right things at the right time. Same for blobs, I’ve seen bubber crews pile on just as much as tg crews. The difference is nobody is moving rechargers up to spam lasers, cargo isn’t emptying the budget, medical doesn’t have doctors setting up triage, and there aren’t 2 Durands on scene within 5 minutes of the alarm.

Beyond that though, we genuinely have it harder here because the server actually fucking works on a 3 hour round. Blob gets resources faster (or rather when they are supposed to) and rooms actually vent when spaced. 

The people who play here have it in them to fight at lower hp, and I firmly believe they will adapt accordingly and experience a better game as a result

**Comment by StrangeWeirdKitten** [comment]
Yeah this ain't a simple number change. The much better solution is to buff things that are left behind. There's signifigant amounts of stuff. (Stamina changes, etc) that skyrat gave us. I don't know why we can't focus in making our own balance then trying to revert everything to TG balance. You're going to have a much easier time justifying a buff to specific items or nerfs.

**Comment by YakumoChen** [comment]
> The people who play here have it in them to fight at lower hp, and I firmly believe they will adapt accordingly and experience a better game as a result

This is pure conjecture. The reality is that this isn't a change that will make players "just get good", that just doesn't happen.

It's more likely this will lead to unrelated balance changes (like blob and spider nerfs) and we'll be at the same spot we are right now, just with lower HP.

**Comment by Yanziko** [comment]
> Yeah this ain't a simple number change. The much better solution is to buff things that are left behind. There's signifigant amounts of stuff. (Stamina changes, etc) that skyrat gave us. I don't know why we can't focus in making our own balance then trying to revert everything to TG balance. You're going to have a much easier time justifying a buff to specific items or nerfs.

Well, if this is the case, which my own personal testing on different damage sources and types suggested otherwise, I'll go ahead and close this PR. I'll see if I can think up any proper balancing for stuff for later PRs, but we'll see.

**Pull request closed without merging**
