### PR TITLE
Box Station 2: An update to Box Station

### PR DESCRIPTION
**Pull request by shayoki**
## About The Pull Request

This update to Box Station revamps dorms, expands the brig, gives cargo a warehouse and more QOL changes.
See the changelog for a full list of changes.

Screenshots are attached below.

If anything is missing or broken, please comment on this PR regarding it.

Known Issues:
- [x] Holodeck is non-functional.

## Why It's Good For The Game

The improved areas give Box Station a fresh new look while improving roleplay quality and retaining its retro vibe.

## Proof Of Testing

Tested locally. Areas function as normal.

<details>
<summary>Screenshots/Videos</summary>

StrongDMM-2024-11-24 20 56 54

StrongDMM-2024-11-24 20 55 02

StrongDMM-2024-11-24 20 54 39

StrongDMM-2024-11-24 20 54 01

StrongDMM-2024-11-24 20 53 48

StrongDMM-2024-11-24 20 53 44

StrongDMM-2024-11-24 20 53 01

StrongDMM-2024-11-24 20 51 51

</details>

## Changelog

:cl:
map: Box Station's Brig layout has been revamped to support improvements for the department's Interrogation Room, Education Chamber, Holding Cells, Evidence Storage, Lawyer's Office, Detective's Office. The halls leading to the Brig has also been slightly expanded to accommodate for the repositioning of the Lawyer and Detective's Offices.
map: Box Station's Dorms has been expanded.
map: Box Station's Fore Starboard Maintenance has been improved to compensate for Dorm's expansion.
map: Box Station's Cargo now has a Warehouse. And Bitrunning has an exit to Aft Port Maintenance.
map: Box Station's mailing disposals properly work for the Lawyer and Detective office.
map: Box Station's MULE delivery drop-off is now at Medbay's Storage. The old spot was replaced with a west exit.
map: Box Station's Medbay now has a Synth Chute system at the Morgue.
map: Box Station's Science now has a Synth Retrieval system at Robotics.
map: Box Station's pool has been replaced with a sauna room at Dorms.
map: Box Station's Bridge has had their consoles re-ordered.
map: Box Station's EVA has been divided into two sections.
map: Box Station's Kitchen now has a table under its food processor. You are welcome waterpig.
map: Box Station's Departures has had its directional glass windows removed and replaced with hedges.
map: Box Station's fax machine inside of the Unisex restrooms in Service has been removed.

/:cl:

### CODE REVIEW

**Comment by lessthnthree** [comment]
Looks good, but the sauna should not be able to be bolted with a button. It's a public space.

A /obj/machinery/door/airlock/wood/glass would be more appropriate, and people can spray paint it if they want to block view.

**Comment by Hemlock32** [comment]
The giant open area outside security feels, unnecessary and empty
I would say either compress it down to make room for other rooms, or, fill it with a rotated, longer version of the same bench/hedge arrangement that departures has

And, with the dorm rooms moved, that entire area that was previously an open area outside the dorms (The one above the showers/theatre) feels, similarly empty and underused, and could be space used for lockers, vending machines, or just a bench and some potted plants

Cryo feels out of place now that its a floating island detached from everything

Not to mention, in general the modified areas could benefit from a couple posters and potted plants

**Comment by Hemlock32** [comment]
Okay, yeah, that new version of those areas look great now!

**Comment by Arturlang** [comment]
How the bridge laid out is really wierd and doesn't quite make sense.

**Comment by TealSeer** [comment]
There's a missing cable under this door here, meaning the drone bay isn't actually connected to station power
image

**Pull request merged**
