### PR TITLE
Nerfs electrocution damage because I died to it once

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

I ran into a door and died because there was 2+ MW in the grid. 

## About The Pull Request (For Real)

Currently, electrocution damage is balanced around having 1MW in the grid, but since we're now allowing an upwards of 4MW in the grid now, I balanced electrocution damage to that 4MW value and applied other changes.

You now take 1 damage per 30J (previously 20J). This wasn't just an arbitrary x1.5 multiplier but the math worked out.
The maximum damage you can take from electrocution is now 125 (previously 195). Maximum health is 135 for reference.
The minimum damage you can take from shocks is 10 (previously 20).

## Why It's Good For The Game

As mentioned above, electrocution damage is currently in a bad state right now since it hasn't been balanced around the new power requirement changes.

This change is also good if we actually unironically want to add malf AI back into rotation because I don't want a round where the AI insta-kills everyone because they touched a door once.

## Proof Of Testing

Untested.

## Changelog

:cl: BurgerBB
balance: Nerfs electrocution damage because I died to it once
/:cl:

### CODE REVIEW

**Comment by nevimer** [comment]
I was thinking - what if being being shocked by a door, when there's too much power on the grid, caused a localized grid check?

**Comment by Swiftfeather** [comment]
I think death by doors is excellent, and the fact skyrat babyproofed it away with apc arcing is cheap af

**Comment by BurgerLUA** [comment]
too much effort for me to do

I'm all out of coding juice right now and I'm running on fumes. I just had a shit round just now and a shit round then so I'm not feeling motivated to do anything.

**Comment by BurgerLUA** [comment]
> I think death by doors is excellent, and the fact skyrat babyproofed it away with apc arcing is cheap af

death by doors is terrible since it's

1. completely silent and invisible unless you have a diagnostic hud
2. extremely easy to do as malf/whatever
3. 60% of the time a result of EMPs, which is in extremely high supply by antags

**Comment by SpaceLoveSs13** [comment]
> I think death by doors is excellent, and the fact skyrat babyproofed it away with apc arcing is cheap af

This was done because station always needs excess power now that can kill everyone over 10 times through old apc arcing. Arcing can still happen.
Without this excess power, grid would shut down every 10 minutes someone charges something due to recent tg changes.

**Comment by Swiftfeather** [comment]
I need you to refactor this 
image

**Review by StrangeWeirdKitten — APPROVED** [review]
just needs its conflict resolved. But yes, this is very needed

**Comment by Majkl-J** [comment]
Fix the linters and conflicts, then ask for a reopen, or reopen a new one yourself

**Pull request closed without merging**
