### PR TITLE
Coffin of the Ashen Mountain: MOD ash accretion requires full suit

### PR DESCRIPTION
**Pull request by Hatterhat**
## About The Pull Request
If your MODsuit has an ash accretion module installed, retracting your MOD will cause you to lose its boons (storm resistance/armor/speedboost), because it's only supposed to give buffs while deployed (which is the whole reason you *wear* a MODsuit). Redeploying your suit reenables those functions. Original PR at NovaSector/NovaSector#598.

## How This Contributes To The Nova Sector Roleplay Experience
Encourages proper MOD usage. Reminds miners that they are mortal.

## Proof of Testing
image
## Changelog

:cl:
fix: Retracting your MODsuit with an ash accretion module enabled disables the benefits from the module.
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
Take it upstream to Skyrat, we are still a downstream.

**Comment by YakumoChen** [comment]
Take it upstream to Skyrat, we are still a downstream.

**Comment by YakumoChen** [comment]
The changes to the cargo-buyable module are also not needed here, as ash accretion is incompatible with every well-armoured modsuit on bubber.

**Comment by Hatterhat** [comment]
forgot i had this open lol

**Pull request closed without merging**
