### PR TITLE
Restores the Mini E-Gun and Hippo 25mm as orderable cargo guns.

### PR DESCRIPTION
**Pull request by ReturnToZender**
## About The Pull Request
Adds some of the forgotten weapons back to cargo, the 25mm Kiboko and the Mini E-Gun.

## Why It's Good For The Game
Variety is the spice of life! This adds back some of the missing weapons to the cargo order list.

Guns have not currently been rebalanced, but should not be much of a balance issue.

## Proof Of Testing
image
image
image

## Changelog

:cl: ReturnToZender (code)
add: Kiboko 25mm to Armory tab
add: Mini E-Gun to goodies and armory
balance: Reduces the cost of the d'Elite rifle as it is more of a side-grade now
/:cl:

### CODE REVIEW

**Comment by ReturnToZender** [comment]
Currently retaking the 25mm proof image due to changes, just a moment

**Comment by projectkepler-ru** [comment]
@ReturnToZender  the guns are renamed upstream for ur information and they arent french now

**Comment by xXPawnStarrXx** [comment]
I support the idea of the miniature laser gun, there would be no way any corporation would allow an explosive launcher on their pressurised state of the art space vessel.

**Review by Majkl-J — APPROVED** [review]
I played around with these in testing, seem reasonable balance wise, actually

**Pull request merged**
