### PR TITLE
Adds Holding Cells to Tramstation

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

image

Draft because I need to test it to see if I didn't fuck anything up.

## Changelog

:cl: BurgerBB
add: Adds holding cells to Tramstation
/:cl:

### CODE REVIEW

**Comment by Cyprex** [comment]
Best to PR this to upstream tg

**Comment by BurgerLUA** [comment]
last time I PR'd a map change that people thought was good on one coderbase to a parent coderbase, I got bullied

im good

**Comment by YakumoChen** [comment]
Why is this good for the game?

**Comment by nevimer** [comment]
We can't simply edit maps - We have to do the automapper or every time someone changes the map upstream we'd have to wipe the map again.

**Comment by BurgerLUA** [comment]
ieiahjaeklhjekl

**Pull request closed without merging**
