### PR TITLE
Donator items (runner jackets)

### PR DESCRIPTION
**Pull request by Scuhf-git**
Donator items for Kan3, they made the sprites I just put them in.

## About The Pull Request

Adds three donator jackets that the donor provided the sprites for.

## Changelog

:cl:
add: Engineer Runner Jacket (donator)
add: Syndicate Runner Jacket (donator)
add: Winter Runner Jacket (donator)
/:cl:

### CODE REVIEW

**Comment by ReturnToZender** [comment]
First of all, thanks a ton for handling this for me.
Two notes: 
-One, make sure to properly mimic TG pathing when it comes to the jackets.
-Two, make sure they aren't ckey whitelisted. What you need to append is donator_only = TRUE.

**Comment by Scuhf-git** [comment]
@ReturnToZender 
Wait does Ckey linking actually not work currently? Also this is tested, works in game, not sure about the ckey linking mumbo jumbo because I tested them without it. When tested with the linking I didn't see them in the loadout so I assumed it was working correctly.

**Comment by ReturnToZender** [comment]
> @ReturnToZender Wait does Ckey linking actually not work currently? Also this is tested, works in game, not sure about the ckey linking mumbo jumbo because I tested them without it. When tested with the linking I didn't see them in the loadout so I assumed it was working correctly.

Ckey linking works just fine, we just don't ckey-lock items.

**Comment by kaylexis** [comment]
thanks for doin this!! i cant code for shit but yay my stuffs gonna be in

**Comment by Scuhf-git** [comment]
> thanks for doin this!! i cant code for shit but yay my stuffs gonna be in

No problem, it was decent practice for something simple anyway.

**Comment by ReturnToZender** [comment]
Works fine now! Approved by me.

**Comment by Scuhf-git** [comment]
https://user-images.githubusercontent.com/128834582/231312373-81074833-073a-4975-b15f-e2ece2f9093c.mp4

**Review by KathrinBailey — CHANGES_REQUESTED** [review]
Sorry I may just be having a white woman moment here but shouldn't Kan3's stuff be tied to their ckey?

**Comment by Scuhf-git** [comment]
> Sorry I may just be having a white woman moment here but shouldn't Kan3's stuff be tied to their ckey?

That's what I had originally but Butters said to change it to dono only.

**Comment by kaylexis** [comment]
> Sorry I may just be having a white woman moment here but shouldn't Kan3's stuff be tied to their ckey?

I'm Kan3, i'd rather all donators have these items. minus the winter one.

**Pull request merged**
