### PR TITLE
Lavaland Dauntless / Removes cameras

### PR DESCRIPTION
**Pull request by StrangeWeirdKitten**
## About The Pull Request

Removes cameras.

## Why It's Good For The Game

The cameras were a mistake and they don't need them outside of xenobiology. There's a reason why I didn't map Dauntless to have cameras and I've let you all see why. (The station AI)

## Proof Of Testing

image

## Changelog

:cl:
del: Removes the Dauntless cameras
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
Just blacklist the cameranet from the AI? It should have already done that by default, but I don't know how to make it do that.

You might as well remove the camera console in the brig if its not going to be worth anything.

**Comment by StrangeWeirdKitten** [comment]
> Just blacklist the cameranet from the AI? It should have already done that by default, but I don't know how to make it do that.

The cameras are already on a seperate network. I'm willing to learn how / if you can do this if the system already exists. 

> You might as well remove the camera console in the brig if its not going to be worth anything.

I'll think of a replacement. 

> Also wouldn't the bitrunning stuff let dauntless players conflict with the station crew? Or is that the goal?

It spawns completely seperate zones. There's not going to be interaction.

**Comment by StrangeWeirdKitten** [comment]
Server stress isn't really an issue, but I'd look into the runtimes.

**Comment by StrangeWeirdKitten** [comment]
I'll map the camera console to be a generic ss13 one.

**Comment by YakumoChen** [comment]
Perhaps remove all but the Prison cameras then?

**Comment by Zergspower** [comment]
> Server stress isn't really an issue, but I'd look into the runtimes.

the biggest risk was when 2 of the same domain loaded, partly why we scrapped the idea of having ghost roles have it

**Comment by StrangeWeirdKitten** [comment]
I'm going to do some later map edits.

**Comment by StrangeWeirdKitten** [comment]
There is no need for dauntless to have any cameras except for xenobiology. It doesn't need them.

**Pull request merged**
