### PR TITLE
Departmental airlock sounds. [SEMI-Modular]

### PR DESCRIPTION
**Pull request by pixelkitty286**
## About The Pull Request
I tried porting Citadel Role play's airlock sounds over and most sounds that ported were a bit over the top, too long, or loud.

This is my second attempt on https://github.com/Bubberstation/Bubberstation/pull/1054 but with the changes that were required before it was speed merged.

Makes the new sounds a pref (off by default) so if you don't like them you can just leave them off.
## Why It's Good For The Game
Honestly I kind of liked the idea of different airlock doors having different sound effects to represent each door even if my current changes do not cover every airlock type. Command and Centcom sounding smooth and official, Security sounding secure, Engineering sounding metal and industrial, Cargo sounding a mix of industrial and mail room like, ECT. 

Sound design is one of the things that does add more flavor to a game's environment setting the tone and setting of a place.

## Proof Of Testing
<details>
<summary>Screenshots/Videos</summary>

https://github.com/user-attachments/assets/43b01469-73a1-4397-8c45-8e1e9f3cea02

https://github.com/user-attachments/assets/d646476a-9f4d-4c87-97c5-d386d9973e45

https://github.com/user-attachments/assets/f669c186-da75-4c2a-9175-3d7eb7151a53

https://github.com/user-attachments/assets/232e1fab-0b30-4f43-8396-6cddaf0ea38d

https://github.com/user-attachments/assets/319fd925-fecf-4fc1-b00c-eb43d2a82fb4

5Yro0guFh0

</details>
Note command doors are swapped and some sounds in the vids are lowered after first test merge took place.

Added new pref to be added to proof.

Added extra vid to reflect sound changed on medical airlocks.

## Changelog
:cl:
add: Door sounds from CitRP / Chomp and trimmed versions of sounds.
add: New pref for fancy and simple airlocks.
sound: added door sound files in modular sounds folder.
code: Paths for new sounds in the modular folder and non modular edit on airlock.dm
/:cl:

### CODE REVIEW

**Comment by pixelkitty286** [comment]
> Isnt the sound going to cause issues? It isnt a big deal foe me as im half deaf and play the game with audio off but idk about others

Not that I know of I've seen plenty of other servers with these similar sounds. So don't know what you mean by this.

**Comment by Arturlang** [comment]
Sounds don't seem grating to me, I like it

**Comment by Rykka-Stormheart** [comment]
The doors sound terrible if only because they're cut short/sound unnatural. (As someone who was used to the sounds from Chompcode/CitRP.

I'd level the sound out but keep the full length of them so it sounds better, otherwise it's jarring.

**Comment by pixelkitty286** [comment]
> The doors sound terrible if only because they're cut short/sound unnatural. (As someone who was used to the sounds from Chompcode/CitRP.
> 
> I'd level the sound out but keep the full length of them so it sounds better, otherwise it's jarring.

see the last PR on why i made them like this -w-

**Comment by KateAnbolho** [comment]
These noises just feel over-engineered for what our doors are. They don't fit very well with how TG made them, along with all the audio balancing issues. One single TM round also shows how easily spammable the medbay doors are with the "ping" effect.

**Comment by nikothedude** [comment]
they sound really bitcrushed 👎

**Comment by lessthnthree** [comment]
- They need to be balanced and at least relatively synced with the airlock animations.
- The medbay one is far too silent, there's no 'feedback' when you hit the door to know it triggered.

**Comment by pixelkitty286** [comment]
> * They need to be balanced and at least relatively synced with the airlock animations.
> 
>     * The medbay one is far too silent, there's no 'feedback' when you hit the door to know it triggered.

I'll look into it for now I need to find replacement sounds again...

**Comment by pixelkitty286** [comment]
Need this drafted

**Comment by ChaosCzar** [comment]
Liking some of the new sounds, though it seems like some are too long / short. Maybe the virology one could be used for R&D / Medical in general? It fits the vibe, a nice, pleasant, elevator ding sort of sound.

**Comment by RimiNosha** [comment]
Alternatively, it wouldn't be hard to make the doors open at the same speed as citcode, but the question is if the outcry would be big enough to bother doing.

**Comment by RimiNosha** [comment]
They're off by default. No one will hear these.

**Comment by pixelkitty286** [comment]
> They're off by default. No one will hear these.

would you like me to risk people complaining about them and turn them on by default?

**Comment by RimiNosha** [comment]
I see it pretty counter intuitive to spend effort on something just to have it turned off 99% of the time.

**Comment by pixelkitty286** [comment]
> @pixelkitty286 You don't need to keep hitting the update to master button. We will do it if required to resolve conflicts.

oh sorry i just remember someone saying a sync a day keeps the merge conflicts away.

**Comment by IgiariValkyr** [comment]
I still don't understand why this can't be on by default then have people turn it off instead. You're missing all the new sounds if you have it off by default which completely ruins it. You're doing work for all this for no one to hear it.

**Comment by lessthnthree** [comment]
If another maint feels it should be enabled by default so be it, but I don't support it. I don't think the sounds are yet at a quality level that warrants replacing the default.

When they are better edited in a later PR, the flip to make them default could be made.

**Comment by Screampuff** [comment]
> they sound really bitcrushed 👎

that's cause they were originally from descent 2 and 3 from the 90s, I was tweaking when I first heard them bc they're literally my favorite game series

**Comment by StrangeWeirdKitten** [comment]
I think it's fair we gave it a chance, and people aren't really a big fan, and it's not supported by multiple maintainers.

And no, I'm not going to add a default off toggle button just for door sounds.

**Comment by pixelkitty286** [comment]
This disappoints me greatly.

**Comment by Erol509** [comment]
I used the sounds myself, and they were nice.

**Comment by Rykka-Stormheart** [comment]
I really liked them :c

**Comment by IgiariValkyr** [comment]
> And no, I'm not going to add a default off toggle button just for door sounds.

Thank you for sharing my sentiment on this. Like as i said, a default off toggle just ruins all the work that you're trying to do.

**Pull request closed without merging**
