### PR TITLE
Pod ruin changes

### PR DESCRIPTION
**Pull request by kaylexis**
## About The Pull Request

Similar to #1338, but fixes the issue with the colony fab not existing by spawning a flatpacked item version in a crate.
also adds scrubbers and some more space

## Why It's Good For The Game

Podpeople haven't been updated in.. never

## Proof Of Testing

Screenshot 2024-04-08 213924

## Changelog

:cl:
add: Added more stuff to the seed vault.
/:cl:

### CODE REVIEW

**Comment by ReturnToZender** [comment]
Atomize the changes to the biogenerator

**Review by projectkepler-ru — CHANGES_REQUESTED** [review]
automapper

**Comment by StrangeWeirdKitten** [comment]
If you're going to move the flat pack to a crate, check if there's code inside DM that populates these crates with item paths and you can slide it there and remove the automapper flatpack that was merged.

Also yeah, please atomize this PR.

**Comment by TeaCommando** [comment]
Broke with the upstream merge, zelp

**Review by Majkl-J — APPROVED** [review]
I approve of merging this fucking PR

**Pull request merged**
