### PR TITLE
Rebalances syndicate firearms to be appropriately balanced for the Skyrat health increase.

### PR DESCRIPTION
**Pull request by Tupinambis**
## About The Pull Request

Buffs various syndicate "high alpha damage" weapons including the sniper rifle, revolver, and rebar gun to do roughly 1.3x their current damage to balance around the 135 HP crit threshold we have on Bubber.

Similarly, buffs various syndicate automatics and faster firing weapons with a roughly 1.3x increase in ammunition capacity

## Why It's Good For The Game

The revolver, sniper rifle, and rebar gun are balanced around doing a ton of damage when you hit, at the cost of punishing misses severely and having a limited amount of ammo. The 135 HP buff by skyrat has destroyed this balance. The sniper and revolver which are supposed to kill in 2 shots now kill in 3, and when the sniper has 6 round mags, and the revolver only has 7 shots, and the rebar gun can only load 3 at a time, this severely hampers their effectiveness.

The other weapons such as the makarov, c20-r, bulldog, m90gl, L6, etc. are balanced around having limited ammunition per magazine, especially for ops who can't really print ammo. They need to use more ammo to kill, so unsurprisingly the value of their weapons goes down.

While ops is currently bus only so it's difficult to gauge the effect this will have in a natural setting, traitors almost never purchase the makarov or the revolver, ever, and why would they when the makarov can't even kill someone with a full magazine, and the revolver can only take on two people with great accuracy before needing to reload. Alternatives are so much better that these options just get left ignored.

## Proof Of Testing

It compiles and this is just numerical edits so it's fine.

## Changelog

:cl: Tupina
balance: Makarov ammo capacity: 8 -> 10
balance: Stechkin APS ammo capacity: 15 -> 21
balance: c20-r ammo capacity: 24 -> 30
balance: m90gl ammo capacity: 30 -> 40
balance: L6 SAW ammo capacity: 50 -> 65
balance: bulldog ammo capacity: 8 -> 10
balance: Rebar gun and its syndicate variant do roughly 30% more damage, the latter critting in 3 shots.
balance: Sniper rifle ammo types now do roughly 30% more damage, critting in 2 shots.
balance: Revolver ammo types now do roughly 30% more damage, critting in 2 shots.
/:cl:

### CODE REVIEW

**Comment by destrucktoid** [comment]
Now this is going to be a controversial idea but i'm going to say it anyway...
You ready?
How about we just remove the added skyrat HP? I'm fine with stam as it is but the HP is wack.

**Comment by Tupinambis** [comment]
> Now this is going to be a controversial idea but i'm going to say it anyway... You ready? How about we just remove the added skyrat HP? I'm fine with stam as it is but the HP is wack. Otherwise we're just going to end up doing what this PR is ultimately doing, buffing weapons to their "balanced" TTK but now with 35 hp extra. Which is just stupid.

Maintainers do not want to do this, the goal was a higher TTK it's just that a few weapons absolutely need low TTKs/Shots to kill in order to be viable.

**Comment by destrucktoid** [comment]
> > Now this is going to be a controversial idea but i'm going to say it anyway... You ready? How about we just remove the added skyrat HP? I'm fine with stam as it is but the HP is wack. Otherwise we're just going to end up doing what this PR is ultimately doing, buffing weapons to their "balanced" TTK but now with 35 hp extra. Which is just stupid.
> 
> Maintainers do not want to do this, the goal was a higher TTK it's just that a few weapons absolutely need low TTKs/Shots to kill in order to be viable.

This is a slippery slope that only ever leads downwards. Next you go "Well X weapon was good before, but since Y got buffed now it's no longer seen very often. Lets buff X". Eventually you'll lead back to exactly where we were with TG balance, just now the numbers are bigger and the few weapons that haven't been touched are completely useless. Lets look at your laser buff for example. Now with lasers being stronger, it means EMP's are even more powerful due to increased laser usage. Which then means that synth players are going to push even harder for synths to not be as vulnerable to EMP's, which then leads- You see where we are going here?

changing even a small minority of guns in the short term, rather than being willing to commit to the big long term change of reverting skyrat's stupid HP change isn't a good or sustainable long term plan in my opinion. Then again, that's just my opinion.

**Comment by projectkepler-ru** [comment]
> > Now this is going to be a controversial idea but i'm going to say it anyway... You ready? How about we just remove the added skyrat HP? I'm fine with stam as it is but the HP is wack. Otherwise we're just going to end up doing what this PR is ultimately doing, buffing weapons to their "balanced" TTK but now with 35 hp extra. Which is just stupid.
> 
> Maintainers do not want to do this, the goal was a higher TTK it's just that a few weapons absolutely need low TTKs/Shots to kill in order to be viable.

was this publically said anywhere?

**Comment by YakumoChen** [comment]
> Eventually you'll lead back to exactly where we were with TG balance, just now the numbers are bigger and the few weapons that haven't been touched are completely useless.

Don't agree, the health buff has bigger effects on guns than melee because of ammo concerns. The biggest losers here are for weapons that are hard to reload (antags, lasers) and not a big deal for others (security ballistics in general, which are already powerful), they should be given some parity so they don't completely fall off (and they have)

> Lets look at your laser buff for example. Now with lasers being stronger, it means EMP's are even more powerful due to increased laser usage. Which then means that synth players are going to push even harder for synths

Lasers being the default should already be the norm, EMPs always have (and should be) a general counter to security. Synths losing here should just be an expectation of playing synth in these vulnerable roles.

**Comment by projectkepler-ru** [comment]
> > Eventually you'll lead back to exactly where we were with TG balance, just now the numbers are bigger and the few weapons that haven't been touched are completely useless.
> 
> Don't agree, the health buff has bigger effects on guns than melee because of ammo concerns. The biggest losers here are for weapons that are hard to reload (antags, lasers) and not a big deal for others (security ballistics in general, which are already powerful), they should be given some parity so they don't completely fall off (and they have)
> 
> > Lets look at your laser buff for example. Now with lasers being stronger, it means EMP's are even more powerful due to increased laser usage. Which then means that synth players are going to push even harder for synths
> 
> Lasers being the default should already be the norm, EMPs always have (and should be) a general counter to security. Synths losing here should just be an expectation of playing synth in these vulnerable roles.


Don't agree on either of the point, I would much rather see everything redone from the ground up

**Comment by HissyNays** [comment]
Syndicate weapons were fine. The health increase worked as intended. What, we gonna need to buff every other weapon aswell next to make them work "as intended"?
Sniper rifle, 357, SAW and others always remained terrifying guns without those buffs.
I highly disagree with this change.

**Comment by Majkl-J** [comment]
> Syndicate weapons were fine. The health increase worked as intended. What, we gonna need to buff every other weapon aswell next to make them work "as intended"? Sniper rifle, 357, SAW and others always remained terrifying guns without those buffs. I highly disagree with this change.

This is exactly why it's testmerged.

**Comment by GoreDem** [comment]
Makarov magazines are invisible at high bullets in magazine counts

**Comment by IgiariValkyr** [comment]
You didn't update any of the magazine icons to account for the higher count. This makes all of them show as empty until the original amount of bullets is in the magazine.

**Comment by Tupinambis** [comment]
> You didn't update any of the magazine icons to account for the higher count. This makes all of them show as invisible until the original amount of bullets is in the magazine.

I am dumb, this should be fixed now.

**Comment by Formerxboxgamer** [comment]
Throwing my 2 cents in here just to say that this is a horrible idea. Security already struggles against carbon antags like traitors and contractors because of the increased stamina health, making batons and disabler a complete jokes. Buffing syndie weapons would be a huge mistake, and swing the balance pendulum even further towards tots and nukies. Re open the health reduction PR and hold some in character classes on how to deal with blobs and shit, but this ain’t it.

**Review by Majkl-J — CHANGES_REQUESTED** [review]
Alright, after some rigorous testing, we dont really need the higher bullet damage. Thw wound chance on the weapons is already crippling and the revolver can be reloaded from any lathe.

I do however agree that the other syndicate options need the increased ammunition as the current makarov offers no window of error when used against regularly armored sec officers.

**Comment by Tupinambis** [comment]
> Alright, after some rigorous testing, we dont really need the higher bullet damage. The wound chance on the weapons is already crippling and the revolver can be reloaded from any lathe so the concerns about running out are more an issue of poor preplanning.
> 
> I do however agree that the other syndicate options need the increased ammunition as the current makarov offers no window of error when used against regularly armored sec officers.
> 
> Also needs modularity or bubber edit comments. Modularity preferred

If we're going this route I'm going to need to take a fundamentally different approach if I do anything at all. Closing this and if I get to it I might try to focus in more on TC costs and ammo caps.

**Pull request closed without merging**
