### PR TITLE
[EARLY PULL] Replace natural beheading with cranial fissures

### PR DESCRIPTION
**Pull request by StrangeWeirdKitten**
…our skull) [MDB IGNORE] (#26020)

* Replace natural beheading with cranial fissures (splitting your skull) (#80703)

## About The Pull Request

Replaces natural beheading (doing a lot of damage to the head) with cranial fissures, which split your skull in half.

dreamseeker_2023-12-31T19-38-16

While you have this wound, your eyes can be pulled out of your head with bare hands, and slipping will spill your brain out of your head.

Removes beheading objective from traitor.

Zombies can be beheaded all the same.

Any other way of beheading, such as surgery or amputation shears, is still possible.

### CODE REVIEW

**Comment by BurgerLUA** [comment]
Absolutely one of the worst PRs on this server, hands down. I am not insulting the coding ability here. The code is good but rather the way it is executed is legitimately disgusting. I get nauseated thinking about it.

There are better ways to rebalance decapitation. Adding gore porn is not one of them.

**Comment by StrangeWeirdKitten** [comment]
> Absolutely one of the worst PRs on this server, hands down. I am not insulting the coding ability here. The code is good but rather the way it is executed is legitimately disgusting. I get nauseated thinking about it.
> 
> There are better ways to rebalance decapitation. Adding gore porn is not one of them.

I agree. The sprite needs to change.

**Comment by BurgerLUA** [comment]
> > Absolutely one of the worst PRs on this server, hands down. I am not insulting the coding ability here. The code is good but rather the way it is executed is legitimately disgusting. I get nauseated thinking about it.
> > There are better ways to rebalance decapitation. Adding gore porn is not one of them.
> 
> I agree. The sprite needs to change.

It's not a sprite issue. Like right now I'm ignoring the entirety of balance here. It's the entire concept of still being alive while your brain is half exposed and can be removed by falling. That's legitimately too gruesome for me and I actually get physically ill thinking about it.

**Comment by StrangeWeirdKitten** [comment]
> Stuff

The slipping mechanic is entirely something that's TBD. This is what upstream pushed into the code and I want to sort out before we get it.

**Comment by Savotta** [comment]
> It's not a sprite issue. Like right now I'm ignoring the entirety of balance here. It's the entire concept of still being alive while your brain is half exposed and can be removed by falling. That's legitimately too gruesome for me and I actually get physically ill thinking about it.

image0

boo

**Comment by DrDogss** [comment]
> Absolutely one of the worst PRs on this server, hands down. I am not insulting the coding ability here. The code is good but rather the way it is executed is legitimately disgusting. I get nauseated thinking about it.
> 
> There are better ways to rebalance decapitation. Adding gore porn is not one of them.

Made an account just to comment on this. The sprite isnt even gruesome looking, and I know you said its not a sprite matter; instead the concept itself. I dont know if you've ever played SS13, but people can walk around with their rib cage open and their heart removed, and headless. If u get physically ill thinking about this PR u should play Escape from Nevado its a lot more friendly!  Genuinely if this makes you physically ill u should not play SS13, this is a pretty good PR idea as beheading is shitty and this is a good alternative. 
image0-6

**Comment by DrDogss** [comment]
> > Absolutely one of the worst PRs on this server, hands down. I am not insulting the coding ability here. The code is good but rather the way it is executed is legitimately disgusting. I get nauseated thinking about it.
> > There are better ways to rebalance decapitation. Adding gore porn is not one of them.
> 
> I agree. The sprite needs to change. That's really the biggest fundemental issue with it in my opinion. It's _very_ graphic more then much of anything on the codebase.

Idk how its more graphic than gibs or rotting gib pieces. The sprite looks like a head that got flattened with a rubber mallet, while theres grib sprites of people being cut in half w/ their internals outside.

**Comment by StrangeWeirdKitten** [comment]
> this is a pretty good PR idea as beheading is shitty and this is a good alternative.

Yep, the solution is pretty good, but this PR is very controversal, even between myself and Ozzo. But I 100 percent understand some of the discomfort behind it. 

I don't entirely stand by the argument that "there's already graphic stuff, so let's add more!" since that's just a logical fallicy when we're 100 percent capable of adding some basic overrides to reflavour the mechanic.

**Comment by zeroisthebiggay** [comment]
how're amputation shears affected

**Comment by StrangeWeirdKitten** [comment]
> how're amputation shears affected

Uneffected. This is only from natural decapping like someone with a d-sword or armblade or the axe. (not surgery or manual methods).

**Review by Majkl-J — COMMENTED** [review]
Most likely bricks species specific head sprites among several other things.

**Comment by Redrover1760** [comment]
Absolutely, completely hideous. I'd rather be beheaded every single time than suffer this shit.

**Comment by Majkl-J** [comment]
> Absolutely, completely hideous. I'd rather be beheaded every single time than suffer this shit.

We'll be overriding it with burger's changes

**Pull request closed without merging**
