### PR TITLE
Disables heretic ascension

### PR DESCRIPTION
**Pull request by nikothedude**
## About The Pull Request

Not actually a salt PR, I've hated ascensions since their conception and the recent ascension pushed me to make this PR.

Disables ascensions by preventing their research entirely.

## Why It's Good For The Game

Heretic ascensions are horrible for any server's RP environment, especially with the sec antag dynamic.

Heretic ascensions...
1. Completely halt the round and force it to end early (Not bad per sae, but it adds a seed of doubt into a secoffs mind if, even if theyre friendly towards antags, do I really want to let them go and potentially ruin the round ofr everyone else?)
2. Are extremely powerful and often unstoppable (Again - not bad per sae, but it reinforces the one above)
3. **Present a threat that poisons the way the crew interacts with heretics** - as I said above, why be nice to a heretic, when a sacrifice is a step closer to a round end?

Yes I know its very hard to ascend, but the reasons above apply to all levels of skill and continue to poison the environment.

## Proof Of Testing

image

## Changelog

:cl:
del: Ascensions are removed from the game
/:cl:

### CODE REVIEW

**Comment by nikothedude** [comment]
Mainly putting it here to put it under the jury of public opinion

**Comment by nikothedude** [comment]
Also, drafted pending testing

**Comment by Aisu9** [comment]
this is 100% salt PR don't even hide it, all of this because the admins allowed ONE little disaster to happen, grow up please

**Comment by nikothedude** [comment]
> this is 100% salt PR don't even hide it, all of this because the admins allowed ONE little disaster to happen, grow up please

get real and read the pr, ive always hated ascensions and this just finally pushed me over the edge to code this

**Comment by ReturnToZender** [comment]
Every coder makes a disable ascension PR, it's a rite of passage

**Comment by Aisu9** [comment]
> > this is 100% salt PR don't even hide it, all of this because the admins allowed ONE little disaster to happen, grow up please
> 
> get real and read the pr, ive always hated ascensions and this just finally pushed me over the edge to code this

then maybe you should have croyed when the heretic activity confirm, don't rain your bad humour on everyone

**Comment by pixelkitty286** [comment]
> this is 100% salt PR don't even hide it, all of this because the admins allowed ONE little disaster to happen, grow up please

I 100% agree this is a salt PR what caused this PR was an admin approved thing this is not nova station

**Comment by nikothedude** [comment]
> > > this is 100% salt PR don't even hide it, all of this because the admins allowed ONE little disaster to happen, grow up please
> > 
> > 
> > get real and read the pr, ive always hated ascensions and this just finally pushed me over the edge to code this
> 
> then maybe you should have croyed when the heretic activity confirm, don't rain your bad humour on everyone

you seem to think im the one controlling if this pr is getting merged or not, the only thing im raining is the proposal of removing it

**Comment by imedial** [comment]
You can also just change the proc that chevks for objective completions from true to false, since ascending requires objective completions

**Comment by BurgerLUA** [comment]
This PR will actually just remove all knowledge due to the "as anything" inclusion.

I'll remake this PR but in the "proper" way as I have done in the past.

**Comment by nikothedude** [comment]
> This PR will actually just remove all knowledge due to the "as anything" inclusion.
> 
> I'll remake this PR but in the "proper" way as I have done in the past.

WHOOPS

**Comment by BurgerLUA** [comment]
Also you need to make it so that every ascension also has route = null so it passes linters.

**Comment by nikothedude** [comment]
also yeah yeah i know improve not remove, id love to do that but im deeply disengaged from dm code rn 

if someone else wants to come and do taht they can

**Comment by Swiftfeather** [comment]
lmao we're not turning off heretic ascensions. I'm reducing its weight now so we don't see them as much, they share the exact same weight as spies, bloodsuckers, and lings, which is kind of absurd

**Comment by BurgerLUA** [comment]
I support this PR because heretic Ascensions are everything wrong with creating a good roleplay environment.

Ascensions encourages people to go for mechanics over interaction, which is why in most cases of ascensions it's the heretic being more into using mechanics and less into actually interacting with the crew.

**Comment by StrangeWeirdKitten** [comment]
Yeah, this isn't going to happen, the weight is being lowered and sacrafice amounts reconsidered before the nuclear option is pushed.

**Pull request closed without merging**
