### PR TITLE
Makes paper bins craftable

### PR DESCRIPTION
**Pull request by Majkl-J**
## About The Pull Request

See name.

## Why It's Good For The Game

Good to make something assistants can steal for bounties renewable

## Changelog

:cl:
qol: made paper bins craftable
/:cl:

### CODE REVIEW

**Comment by nevimer** [comment]
I think the whole bounty system sucks and I would remove it entirely

**Comment by Majkl-J** [comment]
> I think the whole bounty system sucks and I would remove it entirely

Too bad I like it and it's better than the old one

**Review by BurgerLUA — APPROVED** [review]
Looks fine, but I wonder if there would be a better way to just make it spawn an empty paper bin, not requiring paper.

**Comment by nevimer** [comment]
this is the kind of jank ss13 is about

**Pull request merged**
