### PR TITLE
Simple research changes

### PR DESCRIPTION
**Pull request by sippykot**
## About The Pull Request

Removes and adds a bunch of items to simple research to make it make more sense.
Could it be completely reworked? Yeah. But it's better to change it up than just leave it like this.

## Why It's Good For The Game

Simple research as it stands is: 
- Insanely overpowered
- Kinda useless for people that actually need it

You can handcraft a stack of omnilathe and omniprinter boards but also you cannot actually use them offstation since you can't make APC boards to power them
There's also ridiculous stuff like being able to make bluespace items and alien tech

Removing and adding the things i did lets you actually set up basics of civilization from scraps and then advance to omnilathe by using xenoarcheology 

## Proof Of Testing

I compiled it and it ran.

## Changelog

:cl:
add: adds apc boards, xenoarch gear and other useful stuff to simple research
del: removes infinite handcrafting of omnilathes/imprinters, chem dispensers, alien tech, syndie tech, etc from simple research - go crack orange rocks
/:cl:

### CODE REVIEW

**Comment by NargaInDisguise** [comment]
What... does this even do?

**Comment by sippykot** [comment]
> What... does this even do?

changes what you can makes with the simple research module
the module works around making a "research paper" from cloth and then doing a simple minigame to then let you craft some shit with iron and steel
the PR changes the items you can get from the minigame, because as it stands you can get extreme OP shit like infinite omnilathe/imprinter, chem dispenser boards, alien multitools, etc. while also being unable to actually use it as an offstation role since you can't power your op loot

**Comment by NargaInDisguise** [comment]
> > What... does this even do?
> 
> changes what you can make with the simple research module the module works around making a "research paper" from cloth and then doing a simple minigame to then let you craft some shit with iron and glass the PR changes the items you can get from the minigame, because as it stands you can get extreme OP shit like infinite omnilathe/imprinter, chem dispenser boards, alien multitools, etc. while also being unable to actually use it as an offstation role since you can't power your op loot

Genuinely had no idea you could do shit like that with literally just some cloth, that is in fact quite fucking wacky.

**Comment by fludd12** [comment]
You can make the APC board with smithing

**Comment by sippykot** [comment]
> You can make the APC board with smithing

lol what

**Comment by sippykot** [comment]
also either way being able to make omnilathes with cloth is... uhhh... bad i think

**Comment by fludd12** [comment]
> > You can make the APC board with smithing
> 
> lol what

You can craft APC, airlock, and air alarm circuits using smithing to craft an electronic template and then filling it with gold.

**Comment by StrangeWeirdKitten** [comment]
It's not really a mechanic that causes any issues other then the ocassional neglected prisoner being capable of setting up civilization from scratch (without the materials)

To be completely honest with you? With the solid bit of mind numbing clicking shapes? I'm not really in support of removing this.

**Comment by sippykot** [comment]
> It's not really a mechanic that causes any issues other then the ocassional neglected prisoner being capable of setting up civilization from scratch (without the materials)
> 
> To be completely honest with you? With the solid bit of mind numbing clicking shapes? I'm not really in support of removing this.

i mean... kinda makes xenoarch (more) useless since you can just... make infinity of the most valuable xenoarch loot...
plus alien technology and syndie gear
im not even removing it, just... well, nerfing it
so you get an autolathe instead of omnilathe for example
and adding stuff like making xenoarch gear easily

**Comment by sippykot** [comment]
> Xenoarchilogy being useless is not really the fault of simple research. It's always been neglected and useless before this came down from skyrat.

i mean maybe... but stilllll - omnilathes from cloth? x3

**Pull request closed without merging**
