### PR TITLE
[Test merge ready] Full on blueshield rework

### PR DESCRIPTION
**Pull request by Majkl-J**
## About The Pull Request

Let's be completely honest, blueshield keeps creating a lot of issues with validhunting, metagaming, powergaming, etc. Since these issues keep reappearing, and people keep complaining, me and @projectkepler-ru (Who actually has blueshield experience), rework them completely.
Also, half the time, there are way too many heads of staff to effectively defend all alone...

### Nerfs
- No longer gets command level pay
- Has sec access removed to stop them from grabbing lethals, or buying them
- Can no longer modify their own accesses
- Lowered armor levels
- Blueshields spawn in the prison, which is where blueshield players belong anyhow

### Buffs
- 6 blueshield slots to deal with the amount of heads of staff
- New wide range of weapons available as a replacement
- Beacon to request your weapons! You might get something [unexpected](https://media.discordapp.net/attachments/1086228429776621598/1222144920710545488/image.png?ex=66152627&is=6602b127&hm=bf6e5f8d2956d1c9c33d8da38b71ecbdd3271e57324bd93aae10515a2ac20781&=&format=webp&quality=lossless&width=1268&height=676) from this

## Changelog

:cl:
balance: Nanotrasen changes up their approach to blueshield funding, cutting it significantly.
/:cl:

### CODE REVIEW

**Comment by IgiariValkyr** [comment]
What a great april fools joke.
GigaChad

**Comment by Superhats** [comment]
SIX BLUESHIELDS
image

**Comment by StrangeWeirdKitten** [comment]
Unironically the better blueshield.

**Review by StrangeWeirdKitten — APPROVED** [review]

**Comment by chemistrymain3** [comment]
An impressive way to make a bad situation worse. 

Six free command radio encryption keys and sec encryption keys walking around the station + turning them into command bodyguards that in no way prevents command from just buying them the weapons themselves as they'd have command IRN access anyway.

Not to mention that the optimal validhunt tool still remains a disabler + the sec radio + the stunbaton, which they'd have, anyway.

Even in the best case scenario, this effectively adds 6 security slots, since, again, nothing stops them getting their hands on lethal weapons, and _nobody will take it away from them_, because why would they?

You cannot fix policy problems with code. Perhaps the only appropriate solution would be them not being able to modify their own access-changing it from _one_ to _six_ just means that six guys with stunbatons will converge on people + security already doing this as well.

**Comment by ReturnToZender** [comment]
Does he know chat

**Comment by Majkl-J** [comment]
> An impressive way to make a bad situation worse.
> 
> Six free command radio encryption keys and sec encryption keys walking around the station + turning them into command bodyguards that in no way prevents command from just buying them the weapons themselves as they'd have command IRN access anyway.
> 
> Not to mention that the optimal validhunt tool still remains a disabler + the sec radio + the stunbaton, which they'd have, anyway.
> 
> Even in the best case scenario, this effectively adds 6 security slots, since, again, nothing stops them getting their hands on lethal weapons, and _nobody will take it away from them_, because why would they?
> 
> You cannot fix policy problems with code. Perhaps the only appropriate solution would be them not being able to modify their own access-changing it from _one_ to _six_ just means that six guys with stunbatons will converge on people + security already doing this as well.

image

**Comment by chemistrymain3** [comment]
> Does he know chat

you'll have to forgive me after seeing storyteller for assuming people just hit crack pipes and code whatever

**Comment by projectkepler-ru** [comment]
> An impressive way to make a bad situation worse.
> 
> Six free command radio encryption keys and sec encryption keys walking around the station + turning them into command bodyguards that in no way prevents command from just buying them the weapons themselves as they'd have command IRN access anyway.
> 
> Not to mention that the optimal validhunt tool still remains a disabler + the sec radio + the stunbaton, which they'd have, anyway.
> 
> Even in the best case scenario, this effectively adds 6 security slots, since, again, nothing stops them getting their hands on lethal weapons, and _nobody will take it away from them_, because why would they?
> 
> You cannot fix policy problems with code. Perhaps the only appropriate solution would be them not being able to modify their own access-changing it from _one_ to _six_ just means that six guys with stunbatons will converge on people + security already doing this as well.



I mean

TG made it so stunbaton doesnt work outside of red alert amongst other thing

**Comment by Eastwardrope** [comment]
Honestly. I feel this should be a real change minus the meme weapons. It'd make it a lot better. I'm aware its an April fools joke(a day or so early) but I feel blueshield really do need to just not be OP hunter killers for any antag that DARES target a head

**Comment by YakumoChen** [comment]
I was reading the PR and actually agreeing with the changes until I got to the last point on nerfs, was disappointed to realise it was just a prank

**Comment by Majkl-J** [comment]
> I was reading the PR and actually agreeing with the changes until I got to the last point on nerfs, was disappointed to realise it was just a prank

Ironically this meme did show some valuable information about how effective blueshield actually is without sec comms and access (Hint: They are still very effective) so that might actually be tried not as a meme afterward

**Pull request closed without merging**
