### PR TITLE
Adds Additional Antag Objective & Replaces a weapon for the HoS

### PR DESCRIPTION
**Pull request by AllCorruptingWyrm**
## About The Pull Request

In an effort to wedge security off of ballistics beyond the shotgun and encourage energy weapons, this PR adds the **Hoshi Modular Lasercarbine** to the loadout of the HoS role, removing the old Allstar/ERT energy rifle in place of the newer and better maintained energy weapon.

## Why It's Good For The Game

A leading problem at the moment for Bubberstation balance is the fact that energy weapons aren't widely used as they are consistently outperformed by ballistics, and i'd like to use the Hoshi Carbines here as a springboard for potential balance. This PR also comes with the caveat that, well, if you lose it, you lose it, and gl getting one from the ERT. I think security would appreciate some new toys as to encourage more sec players/

## Proof Of Testing

It compiles.

## Changelog

:cl:
add: Hoshi carbine to the HoS Job
add: new antag objective to complete.
remove: old ert gun (Allstar)
/:cl:

### CODE REVIEW

**Comment by Doom-external** [comment]
Consider making this a weapon beacon or just adding it to the locker, I for one do enjoy the SC-2 that all heads get.

**Comment by R3dtail** [comment]
> Consider making this a weapon beacon or just adding it to the locker, I for one do enjoy the SC-2 that all heads get.

Most heads don't get guns.  I know for a fact ce and rd don't.

**Comment by projectkepler-ru** [comment]
> > Consider making this a weapon beacon or just adding it to the locker, I for one do enjoy the SC-2 that all heads get.
> 
> Most heads don't get guns. I know for a fact ce and rd don't.

well they don't need it but they can order it (surprisingly)

**Comment by projectkepler-ru** [comment]
Also uh
Idk but this only really affect the hos and no one else so its like????

**Comment by AllCorruptingWyrm** [comment]
> Also uh Idk but this only really affect the hos and no one else so its like????

I mean its another reason to attack the HoS and make stuff happen in round; Its more likely the HoS will have an objective weapon, so it will ensure the HoS will pick one or the other so there is conflict, in one way or another.

**Comment by projectkepler-ru** [comment]
> > Also uh Idk but this only really affect the hos and no one else so its like????
> 
> I mean its another reason to attack the HoS and make stuff happen in round; Its more likely the HoS will have an objective weapon, so it will ensure the HoS will pick one or the other so there is conflict, in one way or another.

it's not exactly 'another reason to attack the hos'  because simply comitting crime is sufficient to get sec on you, getting the hos on you is as easy as throw a bomb at someone and announcin your location

Now, An actual, honest to god review of the PR

**Comment by YakumoChen** [comment]
The HoS already has _two_ unique guns, including another energy gun. I already vehemently oppose the idea of giving security the Hoshi guns (they have MCRs already, the guns are too versatile and outclass other basic guns) and don't like the idea of power-creeping these into their arsenal.

**Comment by YakumoChen** [comment]
It's also not an "ERT" gun you're replacing, energy guns are basic weapons you can order from cargo and other heads of staff already get.

**Comment by Majkl-J** [comment]
This just adds extra stuff to the HoS' arsenal that doesn't seem really needed. Making the actual tg `obj/item/gun/energy/e_gun/hos` gun that happens to be a goal a valid option to carry would be preferable (Maybe doubling its cell charge to account for the extra health everyone has, or giving it a self charge. Something to make it work with the skyrat health buffs)

**Pull request closed without merging**
