### PR TITLE
Fixes people changing the alert level from Delta or above

### LINKED ISSUE #2706: AI - possibly captain/other people with alert access - can change alert during delta
### Client Version:

_No response_

### Issue Summary:

title

### Round ID:

6303

### Test Merge Information:

_No response_

### Reproduction Steps:

-Someone activated the onstation nuke
-Ai set alert to amber
-weird

### PR DESCRIPTION
**Pull request by rintherat**
## About The Pull Request
Title. Fixes #2706 
## Proof Of Testing

image
image

</details>

## Changelog
:cl:
fix: Fixes comm consoles being able to change alert level during Delta+
/:cl:

### CODE REVIEW

**Comment by lessthnthree** [comment]
This is TG code and should be PR'd upstream. Code should be identical.

**Comment by rintherat** [comment]
> This is TG code and should be PR'd upstream. Code should be identical.

okie dokie!

**Comment by lessthnthree** [comment]
Will merge once merged upstream on TG.

**Comment by rintherat** [comment]
https://github.com/tgstation/tgstation/pull/88711# merged!

**Pull request merged**
