### PR TITLE
[MODULAR - BLOAT EDITION] The dauntless ammo locker now actually has the correct ammo types

### PR DESCRIPTION
**Pull request by Majkl-J**
## About The Pull Request

Tried to make this modular by calling the grandparent. I failed

So I replaced the locker entirely

The Dauntless ammo locker now has 
6 normal and 2 fire Makarov mags
1 buckshot, 2 rubber, 2 slug boxes
2 soporific mags for the sniper

Also fixed a naming error

## Why It's Good For The Game

The old box contains solfed ammo that we no longer use, so I decided to replace it.

## Changelog

:cl:
fix: The dauntless now gets the correct type of ammo
/:cl:

### CODE REVIEW

**Comment by IgiariValkyr** [comment]
:point_right::point_left: Can we replace the 50 cal with a bolt action that can still use soporific rounds?

**Comment by Majkl-J** [comment]
> 👉👈 Can we replace the 50 cal with a bolt action that can still use soporific rounds?

out of scope

**Comment by nevimer** [comment]
Two dauntless PR's right now. One may conflict, we will see.

**Comment by Majkl-J** [comment]
> Two dauntless PR's right now. One may conflict, we will see.

Ill just run mapmerger if it does, merge the other one first

**Comment by Majkl-J** [comment]
Aaand done

**Review by StrangeWeirdKitten — APPROVED** [review]

**Comment by StrangeWeirdKitten** [comment]
Fix the merge conflict

**Pull request merged**
