### PR TITLE
Fixes overlay on producebin from being invisible.

### PR DESCRIPTION
**Pull request by xXPawnStarrXx**
## About The Pull Request

Just a simple oopsie fix from the port over to TGs new storage code meant the produce bin sprite wasn't updating as it was filled.

EDIT: Before I'm told to take this upstream, we're... somehow ahead of them with this code.

## Why It's Good For The Game

I wanna see how full my produce bin is. (I didn't work on cute sprites for nothing.)

## Proof Of Testing

image

## Changelog

:cl:
fix: fixed an erroneous path to make the sprite appear.
/:cl:

### CODE REVIEW

**Comment by Majkl-J** [comment]
you need to `git cherry-pick` these

**Comment by xXPawnStarrXx** [comment]
> you need to `git cherry-pick` these

You're speaking a different lingo there boss. What?

**Comment by Swiftfeather** [comment]
if this came from upstream what is the upstream PR

**Comment by Majkl-J** [comment]
> Just a simple oopsie fix from the port over to TGs new storage code meant the produce bin sprite wasn't updating as it was filled.
> 
> EDIT: Before I'm told to take this upstream, we're... somehow ahead of them with this code.

Can you link this storage code PR?

**Comment by Majkl-J** [comment]
Turns out this IS an issue on skyrat. You should get GBP and contributions from it with the way I made the skyrat PR, so hey, closing this one

**Pull request closed without merging**
