### PR TITLE
Biodome Unfuckening

### PR DESCRIPTION
**Pull request by RimiNosha**
# Tell me if anything

## About The Pull Request

So, I played on Biodome for the first time yesterday, and while I love the concept, it uh, needs work, to put it nicely.

So let's try fixing it, or die trying!

So far:
- Sec paddy bay (thanks zydras!)
- Secmed now has their locker and a proper spawn.
- Partial security remap (thanks zydras!)
- Mapped in the extra SR station pets
- SM
  - Blue wires to red so they don't perfectly align (visually) with distro pipes.
  - Replaced "dumb" pipes leading out of it with smart ones cause they're a pain in the ass to edit in editor
  - Made the room significantly bigger so you can actually DO shit in there.
  - Added scram system.
  - Moved the air alarm to between the doors, added a linked air sensor inside the SM chamber.
- Added doors to the engineering elevator.
- Upper library no longer has double walls everywhere.
- Botany
  - Swapped with the service hall
  - Now has an overpass access point to the kitchen.
  - Expanded the upper floor to have 4 trays in isolation for experiments.
  - Gave them firedoors. They had none.
  - Now has a stairway instead of ladders.
- Kitchen now has a stairway up instead of ladders.
- The bar roof has now got more seating, instead of a glass roof.
- Chapel has no more double walls
- Barbers no longer shares a wall with the teleporter room. Poor guys.
- Added blueshield office.
- Added NTR office
- Removed catwalk floors under vents/scrubbers. Ew.
- Added a few extra lights in the poorly lit central area.
- Added a few lights where portable lights were being used for lighting... for some fucking reason.
- Removed some triple walls from bridge... why?
- Arrivals
  - The hallway at the checkpoint has been widened
  - The garden upper level has been entirely scrapped and replaced with a simple walkway, no clue why it was like that, it was so damn confusing.
  - Added signage making it more clear what direction literally the entire station is.
- Added some new navigation markers, and fixed a couple of bad ones.
- Fixed all upper Z space tiles, which prevented proper multi-z navigation if you were outside the station in certain areas.
- Fixed a couple of active turfs.
- Fixed a ton of floating railings through applying a baseball bat to the knees.

**This PR is currently done, as it currently stands. More may come in a later PR depending on feedback.**

Known issues (updated as and when I get more issues I can validate):
- SM issues
- Engi and science elevator has no door
- General layout (may not be able to fix without a rework, we'll see.)
- Botany is bad
- Kitchen and botany are separate
- Not enough maints
- Chem synthesizers everywhere (low priority, I might not bother with them this PR)
- Floating railings everywhere
- Arrivals has very little signage, and has a cross section which... two of the ways lead to the same place, which is incredibly disorienting.

## Why It's Good For The Game

People won't bitch in OOC and IC about how bad the map is to play all the time, and the map will be much more fun to play, yes?

## Proof Of Testing

<details>
<summary>Screenshots/Videos</summary>

<details>
<summary>Service</summary>

Access ramp to the kitchen. This honestly might need a redesign down the road, but this will do as a quick fix.
image
image
image
image
This feels a little empty at the side, but I'm not entirely sure what I could put there.
image
image
</details>

<details>
<summary>Cargo</summary>

image
</details>

<details>
<summary>Sec</summary>

Dormsvend/cryo/borg charger
image
image
</details>

<details>
<summary>Engi</summary>

Added flatpacker (top left)
image
(Scrubber has since been added to that unterminated waste pipe)
image
</details>

<details>
<summary>Command</summary>

Blueshield
image
NTR, bridge (Removed the NTR office, I'm fucking blind and didn't see the original)
image
</details>

<details>
<summary>Arrivals/Dorms</summary>

Public garden/dormvend/signage (I've fixed the doors since, lmfao)
image
This should much more organically funnel people into the station.
image

</details>

</details>

## Changelog
:cl: Zydras, RimiNosha
map: Biodome got a ton of fixes and tweaks, send feedback to RimiNosha so more can be done!
/:cl:

### CODE REVIEW

**Comment by sippykot** [comment]
ngl, i kinda like the chem dispensers

**Review by projectkepler-ru — CHANGES_REQUESTED** [review]
Image Please?

**Comment by RimiNosha** [comment]
> Image

No, because I'm not done yet, and I know I'm going to end up moving more things around.

See MDB for current WIP stuff.

**Comment by IgiariValkyr** [comment]
Mining needs a boulder system, since there isn’t one by default. Most miners put it in the warehouse, but place it where you like

**Comment by IgiariValkyr** [comment]
Oh. And the AI needs to be moved to the top floor to function properly, unless that longstanding bug has finally been fixed by TG

**Comment by RimiNosha** [comment]
> Oh. And the AI needs to be moved to the top floor to function properly, unless that longstanding bug has finally been fixed by TG

Please describe the bug so I can see if I can replicate it.

**Comment by nevimer** [comment]
They're talking about the issue where AI's can't see huds for Z levels above them, only below. (where the mob is)

**Comment by RimiNosha** [comment]
Ah, classic.

**Review by Majkl-J — APPROVED** [review]
Fine by me from what I can see on mapdiffbot

**Comment by RimiNosha** [comment]
Which suppression system, and which button?

**Pull request merged**
