### PR TITLE
Makes Blizzard Brew and Research Rum actually mixable

### PR DESCRIPTION
**Pull request by mikederkan**
## About The Pull Request

This makes the dwarven drinks Blizzard Brew and Research rum actually mix, because as they currently stand they cannot be created without admin intervention.
This is because their recipes require "inverse" reagents, which don't actually appear in game. Low purity reagents can turn into "inverse" reagents, but they are only inverse in **name**, and instead inherit the properties of the inverse reagent. They cannot be used in mixing.
Reagents cannot require inverse reagents to create other products due to this.

## Why It's Good For The Game

Drinks should be able to be created without admin intervention.

Seriously though, besides not being mixable due to an oversight - requiring inverse reagents, something I doubt most players know about/know how to create/care about, to make gimmick drinks with no use outside of being good for a laugh or looking pretty, is a bit silly. 

Seriously, did NOBODY ever try making these drinks to find out that they don't work?

## Changelog

:cl:
fix: Nanotrasen's Dwarven Research Committee have allowed Research Rum and Blizzard Brew to be created and consumed on site once more.
/:cl:

### CODE REVIEW

**Review by ReturnToZender — COMMENTED** [review]
All of this can be modularized in another folder, but since it's just two lines, I'd recommend including a
// BUBBER EDIT
comment, at least.

**Comment by projectkepler-ru** [comment]
how the hell did it fail metastation test

**Comment by mikederkan** [comment]
why did it fail BURGERSTATION this time

**Review by Majkl-J — CHANGES_REQUESTED** [review]
The checks are skyrat shitcode dividing by zero, disregard it.

Anyhow, try making it modular with a file on modular_zubbers

``` Modular file
/datum/chemical_reaction/drink/blizzard_brew
	required_reagents = list(/datum/reagent/consumable/ethanol/iced_beer = 1, /datum/reagent/consumable/ice = 1, /datum/reagent/cryostylane = 1)

/datum/chemical_reaction/drink/research_rum
	required_reagents = list(/datum/reagent/consumable/ethanol/bananahonk = 2, /datum/reagent/medicine/neurine = 1, /datum/reagent/consumable/ethanol/grog = 1)
```

**Comment by Majkl-J** [comment]
stale, ask for reopen when modular changes are added

**Pull request closed without merging**
