### PR TITLE
Nukes the ability to buy most ballistic weapons from cargo. (correct this time)

### PR DESCRIPTION
**Pull request by DeerJesus**
## About The Pull Request
Removes the ability to buy many ballistic weapons from cargo, both as crates and as goodie packs.

last time I tried to merge from skrat instead of bubber.. whoops!

## Why It's Good For The Game
Incredibly unfun to fight against incredibly OP ballistic weapons like this. Skyrat thought it was a 'good and balanced change', well, it isn't. This is why we removed most of the ballistic weapons from the armory in the first place. This is a server with antags that sometimes want to have a chance. No completely demolishing them with your shotgun-pistol bloodloss-embed machine instantly.
Some weapons, like riot shotguns, MCRS, the plasma thrower, the detective's gun, and the pepperball, stay because they fit more in line with the game.

## Changelog

:cl:
del: Removed the ability to buy most ballistic weapons from guncargo.
/:cl:

### CODE REVIEW

**Comment by Serxule** [comment]
could the guns be re-added as like fake/toy guns? i like the aesthetic of gun cargo more than actually using them, and that could keep it. this is good though

**Comment by DeerJesus** [comment]
I’ll consider this at a later date… The guns still exist in the game but
you just can’t buy them.

**Comment by DeerJesus** [comment]
> use block comments
> 
> /* */
> 
> and `BUBBER EDIT` comments

can you give an example of what this looks like?

**Comment by DeerJesus** [comment]
> use block comments
> 
> /* */
> 
> and `BUBBER EDIT` comments

i did it

**Comment by Serxule** [comment]
oh something else though, some (not sure about all) of the weapons in the surplus crates are probably fine to stay, like the pp95, while yes it is 50rnd and fits in bags, for some reason, it is really really bad, especially compared to lasers, so i dont think itd be a problem to keep

**Comment by DeerJesus** [comment]
yea I think I kept most of the surplus crates because they’re just funny
larp items

**Comment by Majkl-J** [comment]
Thank god this doesnt prevent me from just toolboxing the contractor until he drops dead 
(Real story)

**Comment by ReturnToZender** [comment]
Based code, when it's modular I will 👍 it

**Comment by DeerJesus** [comment]
> Based code, when it's modular I will 👍 it

I wish I knew how to make this modular but it’s a deletion

**Comment by Detective-Google** [comment]
even on tg there are guns that can be ordered, while I think skyrat guncargo is overkill there needs to be some venue for new guns to be acquired.

**Comment by DeerJesus** [comment]
I think you can still order some of the guns.

**Comment by nevimer** [comment]
This removes stock TG guns. Can you remove the removal?

**Comment by Serxule** [comment]
> This removes stock TG guns. Can you remove the removal?

if you're talking about the wt550 those can only be ordered from an emagged console on TG, imports arent a thing there

**Comment by DeerJesus** [comment]
> This removes stock TG guns. Can you remove the removal?

No it does not. It just removes being able to buy specific guns from imports, and CMG crates.  All laser weapons have been unaffected and you can still buy the riot shotgun and even the peacekeeper.

You have not been able to buy the wt550 from regular tg crates for a very long time.

**Comment by Serxule** [comment]
> Just nerf bleeding wounds already and you won't ever need to worry to (salt) PR to remove most of the obtainable ballistics you see.

ballistics are strong because they're just flat strong, good damage regardless, firerate depending on damage (stronger than you realize), MUCH higher ammo capacity due to most mags being small and easily reloaded
wounds just make them even better ontop of all those

**Comment by DeerJesus** [comment]
> Just nerf bleeding wounds already and you won't ever need to worry to (salt) PR to remove most of the obtainable ballistics you see.

Would you rather a. remove the blatantly OP weapons that were only added because skyrat coders like to jerk off to 'realistic' guns or b. rework an entire fucking subsystem of the game just so you can keep larping

**Comment by CloverIsLucky** [comment]
> > Just nerf bleeding wounds already and you won't ever need to worry to (salt) PR to remove most of the obtainable ballistics you see.
> 
> ballistics are strong because they're just flat strong: good damage regardless, firerate depending on damage (stronger than you realize), MUCH higher ammo capacity due to most mags being small and easily reloaded wounds just make them even better ontop of all those
> 
> (the only exemption afaik is the pp95 which is meant to be shit)

"billistics is flit string because is flit string" no way!, ballistics is strong because you love jerking off on telling people "skill issue" and dying in less than 10 seconds with a single puncture wound triggers and that's isn't how you should deal with the main problem. Ballistics is strong because you never bother to unfuck the unbalanced shit Skyfart did to bleeding wounds in general.

**Comment by CloverIsLucky** [comment]
Excuse over excuse, over excuse to never going to nerf and ignore what it's the real main shitty problem.

**Comment by Serxule** [comment]
> "billistics is flit string because is flit string" no way!, ballistics is strong because you love jerking off on telling people "skill issue" and dying in less than 10 seconds when a single puncture wound triggers and that's isn't how you should deal with the main problem. Ballistics is strong because you never bother to unfuck the unbalanced shit Skyfart did to bleeding wounds in general.

the hells your problem?

**Comment by DeerJesus** [comment]
he probably just died to ballistics and as someone who also dies to
ballistics this is the correct response

**Comment by Serxule** [comment]
> he probably just died to ballistics and as someone who also dies to ballistics this is the correct response

i mean yeah but also this fixes part of the problem (the skyrat armory revert will fully fix the rest) so i dont know why they're... complaining about it when they clearly hate ballistics, or why they're making fun of/insulting me for... saying ballistics are strong? it really just seems like they're trying to start shit

**Pull request merged**
