### PR TITLE
Dragonslayer Nerf (Pressurized Areas Only)

### PR DESCRIPTION
**Pull request by xPokee**
## About The Pull Request
_This is part one of my Marked One on-station nerfs._
Nerfs the dragonslayer considerably when in a pressurized environment (i.e. on-station). 

For reference the original was:
force = 20
wound_bonus = 10
armour_penetration = 35
block_chance = 25

While the new variables are:
force = 18
wound_bonus = 8
armour_penetration = 15
block_chance = 10
## Why It's Good For The Game
This will hopefully cut down on people powergaming as antagonists and validhunting with miner loot by making it less viable of a weapon on-station.
## Proof Of Testing
It compiled and ran, see the screenshot below for proof of the new stats updating.
<details>
<summary>Screenshots/Videos</summary>
image
</details>

## Changelog
:cl:
balance: nerfed the dragonslayer's stats when in pressurized environments
/:cl:

### CODE REVIEW

**Review by StrangeWeirdKitten — APPROVED** [review]

**Comment by StrangeWeirdKitten** [comment]
Feel free to do something similar to the gladiator armor is that too has its issues.

**Comment by xPokee** [comment]
> Feel free to do something similar to the gladiator armor is that too has its issues.

I'm planning on it, I have something in the works, it'll require some code cleanup on the upstream to be merged first.

**Comment by StrangeWeirdKitten** [comment]
👍

**Comment by projectkepler-ru** [comment]
@StrangeWeirdKitten  Not the wisest call, the sword can't be stored on the person at all unless they have a bag of holding, also this is a loot from the hardest to kill megafauna in the game, why does it need have worse usability than an energy dagger

**Comment by EerieDream** [comment]
> @StrangeWeirdKitten Not the wisest call, the sword can't be stored on the person at all unless they have a bag of holding, also this is a loot from the hardest to kill megafauna in the game, why does it need have worse usability than an energy dagger

You just run in circles in a straight line with a BDM eye and tail spike trophy. It isn't that difficult.

**Comment by Razurath** [comment]
> > @StrangeWeirdKitten Not the wisest call, the sword can't be stored on the person at all unless they have a bag of holding, also this is a loot from the hardest to kill megafauna in the game, why does it need have worse usability than an energy dagger
> 
> You just run in circles in a straight line with a BDM eye and tail spike trophy. It isn't that difficult.

Not that easy, but sure think that.

As for the over all PR, the sword already doesn't use these stats as in game it has no block value so I am not sure why the stat block you're showing has block value on it. If we are reverting it to its original values and giving it back its block I'm all for it, but understand these stats are not accurate to current. The dragonslayer has always been a trophy weapon on station as it has never reflected the difficulty on the fight even on lavaland much less on station unless you're fighting a mob with the large datum.

**Comment by StrangeWeirdKitten** [comment]
It has a 10 block chance right now.

**Pull request merged**
