### PR TITLE
Allow heads of staff to be blind

### PR DESCRIPTION
**Pull request by Swiftfeather**
## About The Pull Request

Removes Blind from the head quirk ban list. Some staff and I feel that heads (not hos) with blind are still able to perform their job functions.

Players in head roles will still be expected to perform their entire range of head duties as they are now, even if they are blind.

## Why It's Good For The Game

Just because a character is blind doesn't mean they're not capable of holding a head position and performing their expected job duties competently.

## Proof Of Testing

I didn't test it

## Changelog

:cl:
add: Blind crew are no longer barred from being heads of staff (except HoS).
/:cl:

### CODE REVIEW

**Review by projectkepler-ru — CHANGES_REQUESTED** [review]
Couldn't the head just, be mute and take signer?

**Comment by Swiftfeather** [comment]
> Couldn't the head just, be mute and take signer?

they're gonna need it to do their job, so, they'll probably have it?

**Comment by Swiftfeather** [comment]
> Couldn't the head just, be mute and take signer?

You're right, I've readded mute to the list. This PR is just allowing blind chars to be head I guess.

**Comment by The-Sun-In-Splendour** [comment]
> > Couldn't the head just, be mute and take signer?
> 
> You're right, I've readded mute to the list. This PR is just allowing blind chars to be head I guess.

Change the title, then.

**Review by projectkepler-ru — APPROVED** [review]

**Comment by YakumoChen** [comment]
> Just because a character is blind doesn't mean they're not capable of holding a head position and performing their expected job duties competently.

How do you expect them to do that? They can't even use consoles.

> I didn't test it

Bruh

**Comment by IgiariValkyr** [comment]
> > Just because a character is blind doesn't mean they're not capable of holding a head position and performing their expected job duties competently.
> 
> How do you expect them to do that? They can't even use consoles.

Seeing-eye assistants to use the console for them.

**Comment by Swiftfeather** [comment]
> Given heads of staff are the most important roles for communication, this wouldn't work unless you force them to take signer or something

It literally already works that way.


> How do you expect them to do that? They can't even use consoles.

Tell me you haven't played blind characters. They can, the year is 2564, consoles have screen readers.

**Comment by Majkl-J** [comment]
> Seeing-eye assistants to use the console for them.

Honestly I need this as a gimmick. Just make a blind CMO and hire an assistant to do just that

**Comment by IgiariValkyr** [comment]
LET ME BE MUUUUUTE

**Comment by projectkepler-ru** [comment]
> LET ME BE MUUUUUTE

you can, it should only require that you also take signer

**Pull request merged**
