### PR TITLE
[Early Pull] Modular Engines

### PR DESCRIPTION
**Pull request by Erol509**
## About The Pull Request

Early Pull from skyrat new PR, that adds engine rotation to the station by using automapper. It adds Tesla/Singulo and means to add more engines into rotation like RM BK

More about it here 

https://github.com/Skyrat-SS13/Skyrat-tg/pull/25918

## Why It's Good For The Game

More flavour to the rounds, something different than SM all the time. SM still will appear and probably quite often, but wont always be the only engine we would set up. 

## Proof Of Testing

image

Compiles and works, still need more work on the Cobalt side, but I can add TEG engine to the rotation when Sharkening test merges it. 

## Changelog

:cl: Cobalt (Gandalf2k15)
add: Modular engine system, see:
add: LOTS OF ENGINES.
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
Don't agree. As much as I like Lord Singuloth, all of the non-SM engines are two dimensional.

 You set them up in a few minutes, you turn it on, and either you're done looking at it for the remainder of the round, or it goes loose and the round is forced to end _immediately_. At least the Supermatter detonating is usually recoverable (and has a very big failsafe early in the round)

**Comment by YakumoChen** [comment]
I can't imagine any engineering player is going to have a net gain of fun with this feature when it quickly becomes apparent how incredibly boring and stagnant the old engines are after a few rounds.

**Comment by Erol509** [comment]
And I believe many people will like the engine rotation, and seeing something different than boring, uncreative yellow crystal block. And we might also see new nice reactors in the rotation, when cobal(Gandalf) finishes their Reactor. RM BK also would be nice in the rotation.

**Comment by YakumoChen** [comment]
> And I believe many people will like the engine rotation, and seeing something different than boring, uncreative yellow crystal block. And we might also see new nice reactors in the rotation, when cobal(Gandalf) finishes their Reactor. RM BK also would be nice to see from time to time.

Maybe you should wait for more than 2 modern engine options to exist before making the PR

Calling the SM "boring" is incredibly disingenuous when you can do a bevy of interesting things with gas mixes and cooling loop design. The Supermatter is a dynamic engine compared to static old engine designs.

**Comment by Erol509** [comment]
> > And I believe many people will like the engine rotation, and seeing something different than boring, uncreative yellow crystal block. And we might also see new nice reactors in the rotation, when cobal(Gandalf) finishes their Reactor. RM BK also would be nice to see from time to time.
> 
> Maybe you should wait for more than 2 modern engine options to exist before making the PR
> 
> Calling the SM "boring" is incredibly disingenuous when you can do a bevy of interesting things with gas mixes and cooling loop design. The Supermatter is a dynamic engine compared to static old engine designs.

If you have more than 10 hours in engineering experience, you will know that setups for SM are not interesting in any way. Also, stop complaining here, its the upstream PR, Im only mirroring it, for it to be merged faster, since its a god change.

**Comment by Erol509** [comment]
10 commits just to fix linters, awesome. I hate mapping

**Comment by Trubbl3** [comment]
engine going loose is quintensensial SS13 gameplay speedmerge this please

**Comment by Cyprex** [comment]
No from me- Splurt has this and it's kinda... why? Also- engineers now need to know how to setup odd engine types. The station **depends** on power being available, having new engines that engineers now also need to know about is not great for this reason imo!

**Comment by Swiftfeather** [comment]
I like this but let's wait until upstream has more figured out on their PR.

**Pull request closed without merging**
