### PR TITLE
Improves the server by adding more Marge

### PR DESCRIPTION
**Pull request by theselfish**
## About The Pull Request

image

## Why It's Good For The Game

image
By using a team of expert analyticians they all agreed on two things; One, if I left without causing any further trouble they wouldn't call Security, and two, Bubberstation is lacking a severe amount of Marge. This PR will hopefully improve Marge statistics by 15.6% in the next quarter.

## Proof Of Testing

image

## Changelog

:cl:
add: Marge has breached containment.
/:cl:

### CODE REVIEW

**Comment by BurgerLUA** [comment]
speedmarge

**Review by BurgerLUA — APPROVED** [review]

**Review by Majkl-J — COMMENTED** [review]
I don't know if I love or hate this one

**Comment by theselfish** [comment]
> I don't know if I love or hate this one

Consider this; After marging this PR we will be the most popular Marge server on Byond.

**Comment by Majkl-J** [comment]
image

**Comment by Majkl-J** [comment]
fuck it we ball

**Pull request merged**
