### PR TITLE
Major mining renovation project

### PR DESCRIPTION
**Pull request by NanoCats**
## About The Pull Request, and why It's Good For The Game

The mining base is horribly outdated, as a QM main, I hear miners bitching about it constantly (valid). It is for this reason that I took bids for construction of a new base, Akhter Company Frontier Equipment won the bid. 

The new base has the following features: 

- Wind turbines to prevent it from immediately depowering to the chagrin of the mining team, Zender says that this is unnecessary and the prison wing SMES is to blame anyways, but I think this is cooler. Furthermore, I have a plan to improve Arc Mining for the station, and the more robust electrical subsystem is part of it!
- Perimeter defense turret system sufficient to defend the base from lesser lavaland fauna to preserve the life of prisoners, employees, and recreational visitors
- Visual overhaul, the station has been refitted with a "Pod" theme making it visually striking and differentiated from the rest of the station (and it helps give mining a cogent theme, as the base now bears a resemblance to the survival pods) 
- Integrated "Raptor" housing/garage instead of a weird barn in the middle of the map that seems like it was very much built by a coder 

## Proof Of Testing/Screenshots

image
image
image
image
image
image

Note: Power is still fucky, the amount of turbines can bee adjusted if needed. I do NOT know exactly how many I need to run the base adequately. 

KNOWN ISSUES: 

- I need to write names on the doors and fix the bolt button for the dorm rooms 
- Raptor barn needs polished up 

## Changelog

:cl:

qol: Reduxes the mining base 

/:cl:

### CODE REVIEW

**Comment by NanoCats** [comment]
OK I just want to tell whoever made the linter that they can fuck off.

**Comment by NanoCats** [comment]
I need to figure out how to placate the stupid fucking linter because it doesn't like that I rotated some windows (fuck you fuck you fuck you fuck you)

**Comment by NanoCats** [comment]
Replaced every fucking window on the fucking map because the linter wants me to go insane so fuck it no more directional windows

**Comment by NanoCats** [comment]
ALL LINTER AND NO PLAY MAKES HOMER SOMETHING SOMETHING

**Comment by NanoCats** [comment]
OK after a lot of hair bulling NOW it's nearly done.

**Comment by projectkepler-ru** [comment]
these turret placement feels like eyesore

**Comment by NanoCats** [comment]
> these turret placement feels like eyesore

alright then you tell me where you want them, make some Xes on the map 
image

**Comment by MajorBugReports** [comment]
Nice.

**Comment by NanoCats** [comment]
> these turret placement feels like eyesore

Turrets have been moved out of the base walls and set to needspower:0

**Comment by YakumoChen** [comment]
This is not a modular PR, so changes will not stick.

**Comment by NanoCats** [comment]
> This is not a modular PR, so changes will not stick.

Kepler said they were going to help at some point

**Comment by YakumoChen** [comment]
The base has a fairly excessive number of turrets, you only really need them by the entrances, you don't need a turret on every available corner of the base. All you're really going to accomplish doing that is pissing off every megafauna into destroying the entire base.

**Comment by NanoCats** [comment]
There are less turrets than in the screenshots it's just laborious to update them after every minor revision, There have been a lot of lesser commits

**Comment by Erol509** [comment]
I wonder if you can just automapp it. Would be easier

**Comment by NanoCats** [comment]
> I wonder if you can just automapp it. Would be easier

I don't know what that is or how to use it, if you'd like to help the large scale mapping is done save for applying names to all the doors.

**Comment by NanoCats** [comment]
Here's where the turrets are now btw I asked Keppler what they thought and they were OK with the number/placement.


Furthermore, the thing that harms "megafauna that win at pvp" is not turrets, they're weak as shit compared to a mega and would lose immediately, the issue is that miners have the giga fuck hammer 9000 fully automatic gatling nuke launcher PKA that comes in 20 flavors. 

image

**Comment by StrangeWeirdKitten** [comment]
@NanoCats the primary issue is, while I love big changes like this, lavaland is primarily TG and we are restricted to either messing with the automapper or not changing it at all. The dmm file will be overwritten come next map merge.

**Comment by NanoCats** [comment]
> @NanoCats the primary issue is, while I love big changes like this, lavaland is primarily TG and we are restricted to either messing with the automapper or not changing it at all. The dmm file will be overwritten come next map merge.

Deadhand, or whatever they go by, said they would help me integrate this at some point, but really I think we could simply automapper the whole goddamn mining base, why not?

**Comment by YakumoChen** [comment]
I don't think this really adds a lot of upsides for the maintainability burden this will put on us.

**Comment by StrangeWeirdKitten** [comment]
@projectkepler-ru is free to reopen this if they get a better solution, But as it stands, it's just not compatable with upstream.

**Pull request closed without merging**
