### PR TITLE
HoP recolor 2: The Functional Boogaloo

### PR DESCRIPTION
**Pull request by 567Turtle**
## About The Pull Request

This is #41 but actually functional and modularized without fucking a bunch of stuff up somehow

## Changelog

:cl:
add: New HoP cloak sprites
/:cl:

### CODE REVIEW

**Comment by 567Turtle** [comment]
> still no sprite addition.................

it isnt working what do you WANT from me

**Comment by Panicode** [comment]
omg it's fixed how did that happen

**Comment by 567Turtle** [comment]
> omg it's fixed how did that happen

I cheated

**Comment by 567Turtle** [comment]
WHYD IT FAIL AGAIN WHAT THE FUCK I GAVE YOU THE SPRITES

**Comment by 567Turtle** [comment]
WHAT THE FUCK

**Review by KathrinBailey — CHANGES_REQUESTED** [review]
Close but no cigar, still not modular.
1. `icon_state` is not the file location, it is the file path of the icon file, which contains many `icon_state`s.
2. You need modular files to follow the exact same file path as the original code files, except they should be in modular_zubbers instead! Find where the icon for the original cloak is, then make a .dmi file of the same name and same file path in modular_zubbers.
3. You need a modular code file to override the cloak's icon variable.

If you need help, contact me or Zirok and we'll explain what you need to do. :)

**Comment by 567Turtle** [comment]
> You need modular files to follow the exact same file path as the original code files, except they should be in modular_zubbers instead!
>
Whenever I name the icon folder "icon" github and VSC don't recognize it as... Existing? It's really weird if one of you could take a look I'd appreciate it!

**Review by KathrinBailey — CHANGES_REQUESTED** [review]
Change the icon file path!

**Comment by projectkepler-ru** [comment]
lack of update on this for awhile now

**Pull request closed without merging**
