### PR TITLE
[TM Only] Nerfs blade ascension, removes Moon+Void ascension

### PR DESCRIPTION
**Pull request by ReturnToZender**
## About The Pull Request
People said no one would do this, so I did it. I personally feel that all heretic ascensions ruin any chance at any sort of fun anyone can have during the round, but this is the consensus we've reached, and I'd rather have weaker ascensions than fully powered ascensions.

Please let me know if you have any other suggestions to nerf Blade heretic

## Why It's Good For The Game
Hate ascensions, love killing heretics

## Proof Of Testing
See #1296, also it compiles

## Changelog

:cl: ReturnToZender
del: Moon and Void ascension can no longer be taken pending rework
balance: Blade heretic has received a nerf to the maximum amount of blades it can carry, as well as its self-healing capabilities
/:cl:

### CODE REVIEW

**Comment by destrucktoid** [comment]
Moon and void being removed i can understand but why the nerfs to blade? Blade isn't even the strongest combat ascension, that's rust. Blade is cool and admittedly strong but i hardly think it needs nerfs compared to the other ascensions.

**Comment by ReturnToZender** [comment]
image
It's technically possible to ascend with 99 points

**Comment by MajorBugReports** [comment]
nope.

**Comment by Redrover1760** [comment]
balance freeze?

**Comment by ReturnToZender** [comment]
> balance freeze?

This was specifically requested by maintainers in #1296 as a preferred solution

**Comment by destrucktoid** [comment]
> > balance freeze?
> 
> This was specifically requested by maintainers in #1296 as a preferred solution, I just made the code because it was relatively easy

"When people were ascending with blade, flesh, forge, rust, and void. I don't feel like these are completely arregious or entirely round ending on their own. But there's been a few new added since like Knock and Moon that are not aligned at all with the scale."

Maintainer said they don't like knock and moon, not moon and void and most definitely not blade.

**Review by Majkl-J — CHANGES_REQUESTED** [review]
After further testing, keep blade untouched. Ill discuss the knock/void with maints once they wake up.

**Comment by Arturlang** [comment]
What if instead of instant ascension, you get a warning like cult does, and the heretic has to do a long do_after or many steps? So people can try and stop them.

**Comment by destrucktoid** [comment]
> What if instead of instant ascension, you get a warning like cult does, and the heretic has to do a long do_after or many steps? So people can try and stop them. A good ascension is a climax in the heretic's path, and should be damn dangerous or round-ending threat.

The chance for people to stop them is whilst they have been sacrificing at least 5 people including a head of staff, if you're already at the point where you are ascending then you've already earnt the victory. The whole informing the whole station for blood cult thing is there to stop you speedrunning it because technically all you need is 9 people and 1 specific guy sacrificed. Heretics need to go through so many more hoops to actually ascend than blood cult does.

**Review by projectkepler-ru — CHANGES_REQUESTED** [review]
Fix your linter

**Comment by ReturnToZender** [comment]
> Fix your linter

The only way to fix this linter is to comment out the check 😭

**Comment by projectkepler-ru** [comment]
> > Fix your linter
> 
> The only way to fix this linter is to comment out the check 😭
dude the unit test literally tells you what to do

**Comment by KazooBard** [comment]
> What if instead of instant ascension, you get a warning like cult does, and the heretic has to do a long do_after or many steps? So people can try and stop them. A good ascension is a climax in the heretic's path, and should be damn dangerous or round-ending threat.

Blood cult is informed about cause it's at least 9 people. This is magic joe with a sharp sword we're talking about. If people get the chance to stop an ascencion 9/10 they'll get 5 mechs and 4 officers on them.

**Comment by ReturnToZender** [comment]
Closed due to Burger doing this better in #2080

**Comment by nikothedude** [comment]
@ReturnToZender plesae reopen this moon ascension is available rn and is a massive fuckfest

**Comment by John-Dang** [comment]
Yeah you seriously need to re-open this, there were literally 56 lunatics last round, I counted.

**Comment by Rykka-Stormheart** [comment]
I'd like to keep Void Ascension, it's really cool and doesn't have the mass conversion stuff Moon does.

Also. I'd like to point out, people getting salty over Heretic ascensions, do you get salty when a blob wins and insta deltas/roundends the station? Etc etc.

Heretic Ascension is a round-ending threat, and the double ascension was on a clown round, with 120 people, and the first helped the second ascend.

**Pull request closed without merging**
