### PR TITLE
[NON-MODULAR] comments out the russian revolver just straight up fucking RRing you

### PR DESCRIPTION
**Pull request by zeroisthebiggay**
## About The Pull Request

the russian revolver being what's essentially a toy to play russian roulette just fucking RRing you is so incomprehensibly stupid because while some may justify it as `it raises the stakes` in fact all it does is make no one ever want to play russian roulette because if you lose you get to sit out of the round for the next two hours. lmao!!! fun!!!!!!!

## Why It's Good For The Game

someone might say that it's bad for roleplay to encourage people to shoot themselves without being permanently morgued but holy shit who cares at this point. if we have suicide enabled then if someone really just wants to be out of the round then they can just suicide with the russian revolver instead of going through the effort to target their head and spin the chamber to blow their brains out.

## Changelog

:cl:
del: the russian revolver should no longer cause you to be permanently dead when used for roulette
/:cl:

### CODE REVIEW

**Comment by Oscari-pog** [comment]
If you want to avoid the RR then dont aim for your head

**Comment by AtlasRules** [comment]
> If you want to avoid the RR then dont aim for your head

aight but like, it kills IPCs who have the brain in their torso though

**Comment by zeroisthebiggay** [comment]
> If you want to avoid the RR then dont aim for your head

ok but the game chastisizes you for being a little baby bitch for aiming anywhere else

it's a stupid change that isn't implied anywhere on the item itself that it'll RR you and i reckon you could probably pretty easily trick people into playing just to kill themselves and be permanently removed from being able to play in the round due to its ambiguity

**Comment by Serxule** [comment]
it rrs y ou now? when tf did that get added

**Comment by zeroisthebiggay** [comment]
> it rrs y ou now? when tf did that get added

https://github.com/Skyrat-SS13/Skyrat-tg/pull/20475

**Comment by projectkepler-ru** [comment]
> me when I kill myself but wait no I didn't actually mean it

True

**Review by projectkepler-ru — APPROVED** [review]

**Comment by Oscari-pog** [comment]
> > If you want to avoid the RR then dont aim for your head
> 
> ok but the game chastisizes you for being a little baby bitch for aiming anywhere else
> 
> it's a stupid change that isn't implied anywhere on the item itself that it'll RR you and i reckon you could probably pretty easily trick people into playing just to kill themselves and be permanently removed from being able to play in the round due to its ambiguity

IDK maybe shouldnt have suicide be a "haha funni!!!" but thats just me

**Comment by StrangeWeirdKitten** [comment]
I think if you don't want to take the risk of getting RR'd, then you shouldn't use it. I would rather just have a prompt or an examination warning that it can RR you.

**Pull request closed without merging**
