### PR TITLE
Dullahanborg

### PR DESCRIPTION
**Pull request by Cecily-C-Catherine**
Adds new borg sprites for each department

## About The Pull Request

Adds new borg sprites for each department

## Why It's Good For The Game

More borg sprites

## Proof Of Testing

https://cdn.discordapp.com/attachments/391076853034516483/1257865496435490846/dreamseeker_7pmm4K1Sgi.png?ex=6685f608&is=6684a488&hm=49d923b81235b78e937b78a12cf646dd007af9cb6924fc6937695591c3de536e&

## Changelog

:cl:
add: Added new sprites and code to allow the choosing of sprites
/:cl:

### CODE REVIEW

**Comment by StrangeWeirdKitten** [comment]
Very cool looking! I've never seen these types before. Are these custom made or are they a port from another codebase?

**Comment by Cecily-C-Catherine** [comment]
> Very cool looking! I've never seen these types before. Are these custom made or are they a port from another codebase?

It was done in part by Toriate and me with some canabalism of meka here and there.

**Comment by StrangeWeirdKitten** [comment]
Sounds really awesome. I'll go ahead and review then test merge them to see how they work!

**Comment by IgiariValkyr** [comment]
Upsetting that dullahans are made possible with borgs before the halloween code was fixed for humans. Smh big sad

**Comment by StrangeWeirdKitten** [comment]
image

Very minor critique. The left thigh looks a bit jutted out from the perspective it's supposed to be in. Is mostly hand adding a bit of thickness to the overall look. But overall, these are extremely solid looking sprites and I love them a lot and I'll enjoy them being added.

**Review by Cyprex — APPROVED** [review]
Went over code + Icon Diffs, looks good!

**Pull request merged**
