### PR TITLE
Redsec cosmetics part 2

### PR DESCRIPTION
**Pull request by Deek-Za**
## About The Pull Request

Made some more tweaks to the redsec cosmetic options on gear.

Adds a **new icon** sprite for the red sec gloves that falls in line with the other security gloves aesthetic. And naturally updates the old reskin option to this new one.
image

Changes jackboots option to a pair of jackboots with redstriping.
image

Allows for Red Sec Armor cosmetic with red striping instead of black with blue striping
image

Allows red sec Belt option
image

## Why It's Good For The Game

Well when I originally put up the redsec reskinning PR I had a number of options I wanted to come back too that I thought would need some sprite work done. Turns out I just overlooked two of the sprites already existing in the game but unused. Added a new icon(gloves) to accommodate the last item using a really dated sprite.
Now you can run redsec without having bits of your armor/belt still showing some blue. Less clashing and overall better look.
image Old vs New image

Update:
Added Red sec huds per @Moostard's request.
image 
image

Don't know why I didn't think about that originally!

## Changelog

:cl:
add: Added redsec armor and belt reskin option
fix: Adjusted redsec boots sprite to be more in-line with peacekeeper style
image: Added new sprite for redsec gloves in peacekeeper style
/:cl:

### CODE REVIEW

**Review by Majkl-J — APPROVED** [review]
Expands on previous modularity so no issue there.
Code approved.

(Also I really love the spritework but I have no say in that, so)

**Comment by Deek-Za** [comment]
> Are you able to get red huds? If not, that would be a nice addition too.

Now that I'm back home I went ahead and snuck that one in.
However the only minor issues is that the reskin option unfortunately uses the same hot key as the adjust option. Which causes some issues with certain items(Most notably why it's not easy to swap winter coats). For the secHUDs, this mostly means that even though you change to red huds, the toggle-able screen overlay color will always be blue regardless unless the glasses spawn in as the red variant originally. I do wanna address this bigger issue sometime in the future though. But that's a whole different PR
Plus I don't think anyone uses the actual sunglasses color overlay toggle anyways? It doesn't really add anything of value.

**Review by Majkl-J — APPROVED** [review]
Awesome, unless there will be more requests, ready to merge

**Comment by theselfish** [comment]
I would request the Armadyne stuff to be a skin, but I can do that in a separate PR.

**Comment by Majkl-J** [comment]
I forgot to merge this last time waiting for the checks. Silly me

**Pull request merged**
