### PR TITLE
Crew monitor sorting overhaul

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

image

Adds a new icon for near crit.
Heads are sorted at the top of the manifest.
(Not pictured) Heads are now blue instead of poop gold.
Prisoners and assistants are given their own new colors.
(Not pictured) Unknowns are placed below assistants, above prisoners.
Central Command roles are placed above captain.
Other roles (mostly off-station) are placed below prisoners.
A crewmember with 50 or more damage is placed at the top, regardless of rank. The higher the damage, the higher they are placed.

## Why It's Good For The Game

This willl help medical players (and the AI) no get eye strain when scrolling through the list of 60 crewmembers to see which one is fucked.

## Changelog

:cl: BurgerBB
qol: Improves the crew monitor sorting and design so it's less annoying to use.
/:cl:

### CODE REVIEW

**Comment by TripleShades** [comment]
You should pr this upstream.

**Comment by StrangeWeirdKitten** [comment]
This PR is so based. Thanks Burger

**Comment by BurgerLUA** [comment]
> This PR is so based. Thanks Burger

bless

**Comment by StrangeWeirdKitten** [comment]
> > This PR is so based. Thanks Burger
> 
> bless

Honestly, this would be something that would be really nice of us to be sent upstream and TM'd here until it gets merged.

**Comment by nevimer** [comment]
run prettier

**Comment by BurgerLUA** [comment]
> run prettier

Not sure what you mean aaaa. Is that a program?

**Comment by nevimer** [comment]
> > run prettier
> 
> Not sure what you mean aaaa. Is that a program?

It is a CI requirement, it's a VSC plugin you run on the file to force it to conform to intent and other standards. It's automatic when bapped.

**Comment by BurgerLUA** [comment]
> > > run prettier
> > 
> > 
> > Not sure what you mean aaaa. Is that a program?
> 
> It is a CI requirement, it's a VSC plugin you run on the file to force it to conform to intent and other standards. It's automatic when bapped.

I don't use VSC. Is there a way to run it via an executable or command?

**Comment by BurgerLUA** [comment]
I just manually edited the files :^)

**Comment by Majkl-J** [comment]
> I just manually edited the files :^)

based

**Pull request merged**
