### PR TITLE
Restores the Plant Gene Editor, a tool from ancient times.

### PR DESCRIPTION
**Pull request by shellspeed1**
## About The Pull Request
A longgggggggggg time ago  botany used to have a tool known as the plant gene editor. Essentially you would take a packet of seeds, put it in this machine with a disk and you could copy traits to the disk or from it. This machine dramatically speeds up botany and in my experience helps to encourage the department to share. If nothing else, its something that will help bubber stand out from similar codebases.

I have performed basic testing on this, confirming that the disks and machine are printable, can edit plant traits, and stats, and lastly ensured basic functionality of other botany tools.

## Changelog

:cl:
add: Plant Gene Editor readded.
/:cl:

### CODE REVIEW

**Comment by Serxule** [comment]
hmm i sure wonder why it was removed

**Comment by TheObserver-sys** [comment]
Incredibly based.  The reworked botany has been designed to be entirely too slow and impotent, and that's literally the antithesis of an enjoyable job. In fewer words: Speedmerge cheese and thanks.

**Comment by Serxule** [comment]
anyways to elaborate, it was removed because its horribly unbalanced, it enables powergaming, and makes it much easier, basically encouraging it, and botany already has a powergame problem

**Comment by TheObserver-sys** [comment]
> anyways to elaborate, it was removed because its horribly unbalanced, it enables powergaming, and makes it much easier, basically encouraging it, and botany already has a powergame problem

It was removed because Arcane's rework was originally meant to be a bit more ambitious and creative, but like most reworks TG does, fell very flat on its face, broke the entire job for a time, and needed about 20 PRs (hyperbole, but slight) to be brought to a playable state. Also, TG loves to fix what isn't broken under the buzzword of powergaming, and leave it at that.  The state of the job now is.. lacking, horribly so. It takes a significantly long time to get anywhere useful, nearly impossible to create well crafted plants without an ocean of fertilizers, and a long period of carving genes off like you're a mad butcher. This is incredibly painful time investment, with half, if not a quarter of the effective power of other time consuming jobs on station, which can powergame infinitely harder than local gardener.

**Comment by Cyprex** [comment]
No.

**Comment by Majkl-J** [comment]
I personally like the new botany more, feels calm and not too rushed. But I do agree it has a issue with minmaxing being basically impossible to do in a reasonable time.
On the other side, returning this creature of a distant past will remove any sort of involvement/challenge once you get the best stats (Extremely easy to do with some even obtainable roundstart).

**Comment by Cyprex** [comment]
> But I do agree it has a issue with minmaxing being basically impossible to do in a reasonable time, which needs to be somehow fixed.
That sounds like a good thing? I've played rounds on tg where botanists murderboned with their (powerful) weapons from botany, and this wasn't after an hour of botany either.

**Comment by SomeDongus** [comment]
This would make botany actually enjoyable again, please god merge this.

**Comment by TheObserver-sys** [comment]
> > But I do agree it has a issue with minmaxing being basically impossible to do in a reasonable time, which needs to be somehow fixed.
> > That sounds like a good thing? I've played rounds on tg where botanists murderboned with their (powerful) weapons from botany, and this wasn't after an hour of botany either.

So you died to a deathnettle. That's called a plant problem, not an entire system wide issue. You don't throw the baby and bathtub out with the bathwater unless you are TG. And last I checked, we're not TG. Tune down the nettle damage and call it a day

As for the point of removing "challenge", it doesn't, and it won't. To be able to extract those top tier stats, you need an upgraded manipulator, T4 across the board. I have enough challenge getting science to stop huffing their own hot air long enough to research even basic plant tools needed to craft plants worth a damn, let alone upgrade the bay.

On top of the previous point, the manipulator *intentionally* cannot modify the instability, nor extract it, which means in the process of planting, stat bleed can and will occur, requiring you to keep watch and re-apply fertilizer to ensure the statlines are preserved. This also doesn't bring back the truly brainless era of the Gaia Rush into top tier bioweapons, so the workload is still immense even with the aid -- it just makes it easier to make mixed plants for use in medicine making and for botanical use.

**Comment by TheObserver-sys** [comment]
To put a lot of my points in fewer words:
Maybe we should nerf the individual plants instead of the whole system.

And

Tedium with no payoff isn't fun. I'm tired of pretending that it is.

**Comment by Majkl-J** [comment]
> On top of the previous point, the manipulator intentionally cannot modify the instability, nor extract it

This is not intentional, it just happens to be THAT old. Not that instability is an issue really, you lower it first with some base stuff fertilizers and THEN you apply the stats, leaving them unaffected. Or you activate autogrow, which if I am not mistaken removes any chance of mutation.

As for the other points: Valid. I do keep forgetting that tg did nerf it before the rework to actually not just give you prod speed 1 and yield 10 on base parts (God that was an era)

**Review by KathrinBailey — CHANGES_REQUESTED** [review]
I'm not sure on this one either for the same reason: powergaming.

Regardless, this doesn't pass tests anyway so that'd need to be fixed if we were to even test-merge it.
There are some QOL things we can do for Botany but I'm not sure if this is one of them.

**Comment by shellspeed1** [comment]
> I'm not sure on this one either for the same reason: powergaming.
> 
> Regardless, this doesn't pass tests anyway so that'd need to be fixed if we were to even test-merge it. There are some QOL things we can do for Botany but I'm not sure if this is one of them.

Aren't tests borked right now?

**Comment by TheObserver-sys** [comment]
With all due respect, all linters are failing across like, 80% of the PRs on the codebase. That's not a unique problem with just this PR.

**Also** this is hardly powergaming on the levels of the days of eld -- the job is still intensive, this just restores a part that makes it less significantly less tedious.

**Comment by shellspeed1** [comment]
Okay, finally back at home and can pay attention to this.

> I'm not sure on this one either for the same reason: powergaming.
> 
> Regardless, this doesn't pass tests anyway so that'd need to be fixed if we were to even test-merge it. There are some QOL things we can do for Botany but I'm not sure if this is one of them.

If your issue is power gaming I am honestly confused here. 
First of all, who are we looking at in regards to power gaming? If its security using the plants, just why? They have stun batons, mcrs, and all sorts of other goodies plus numbers. Why would they give up shit that they start with that's stronger and can be upgraded even further if science is semi competent.

Moving onto the general crew weaponizing botany. Why bother when you can put in almost none of the effort and get guns from cargo, mechs from robotics, or just a spear and a bola. Cargo guns can be acquired with about 20 minutes worth of work just going around and stealing plasma from maint generators or getting materials through mining and selling it via cargo. The spear and bola are just a few minutes worth of work and are about as deadly in addition to being ranged. The best part is, all of this is ignoring xenobiology which straight up has admin heals that teleport you away and are just as reproducible as botany plants used to be when we had the plant gene editor in the past.

The final group to look at is antags, and to be blunt for them its a mix of security and average crew for them. They can utilize the plants and might actually have a reason for it, but they have other gear which is just as strong if not stronger which can be acquired with far less effort and time investment. Bombs are dirt easy to make for example and can be used as one of the easiest tools for murder in the game. The sleepy pen is effectively a silent version of death nettles that you can reuse too on top of that. 

If you really want to argue that this will encourage power game, it might be better to look at it from the medbay side. Suddenly, medical might have access to things like earthsblood, strange reagent, or nutriment. The thing is, that the healing chems that can be made exclusively by botany aren't really useful in a fight. Earthsblood inflicts pacifism, strange reagent only provides revival, and nutriment is only good with an additional chemical that you have to get from medical. If your problem here is power gaming I'm just not seeing it here.

**Comment by shellspeed1** [comment]
So it has been brought to my attention that apparently there is zero intention of actually going for this. I am going to go ahead and close this.

**Comment by nevimer** [comment]
I think I merged a different of the same thing a bit back ago

**Pull request closed without merging**
