### PR TITLE
Removes pitbull gorillas from cargo

### PR DESCRIPTION
**Pull request by Swiftfeather**
## About The Pull Request

why did they add these. I, as much as the next dragon, think pitbulls suck, but this is kinda unnecessary. 

## Why It's Good For The Game

Lol. Lmao.

## Proof Of Testing

If github compiles it, it works

## Changelog

:cl:
del: Removed hostile pitbull crates.
/:cl:

### CODE REVIEW

**Review by BurgerLUA — APPROVED** [review]
1984

**Comment by theselfish** [comment]
Person who added them here; It's funny. It's also a reading comprehension test. The one labelled 'pedigree stud' is safe, the one with a big warning in the description is not. 


Also do this upstream or make them contraband or smthin.

**Review by Majkl-J — CHANGES_REQUESTED** [review]
Make them emag only

**Comment by pixelkitty286** [comment]
> Make them emag only

god please no just gone all together, if you witnessed the emag rounds of them being spam bought and landing in random location then instant killing people you would know that it kills masses of people from their 3 to 4 hit basis combined with fast speeds

**Comment by StrangeWeirdKitten** [comment]
Some thought behind this and I am going to agree to their removal. Especially since emagging cargo consoles can be done via a screwdriver

**Comment by BurgerLUA** [comment]
Removal is the best option since they were lazily made. They're a subtype of gorilla and they do gorilla things, such as make gorilla noises.

**Comment by nevimer** [comment]
If someone wants them back, emag only.

**Comment by StrangeWeirdKitten** [comment]
AND comment out the for for(var/i) in its generate proc. Three gorillas are insane.

**Pull request merged**
