### PR TITLE
People who sign up roundstart get triple the starting cash compared to latejoiners.

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

People who sign up roundstart get triple the starting cash compared to latejoiners.

## Why It's Good For The Game

This should hopefully encourage people to sign up shift start. People who are late for work are generally paid less.

## Proof Of Testing

Untested, but it should work :)

## Changelog

:cl: BurgerBB
add: People who sign up roundstart get triple the starting cash compared to latejoiners.
/:cl:

### CODE REVIEW

**Review by projectkepler-ru — APPROVED** [review]
Great idea

**Comment by BurgerLUA** [comment]
Fun fact, the original code I had in mind was going to be STARTING_PAYCHECKS + src.payday, but this would've been disasterous as the payday proc is a multiplier of how many paychecks someone gets, and src.payday is how much money someone gets per payday.

In instance of the captain, a captain would've started the round with 10,500 credits, instead of the normal 500 credits.

**Comment by ReturnToZender** [comment]
Finally, a PR for me, early bird bonus

**Comment by xXPawnStarrXx** [comment]
Could you also possibly add the caveat of joining a prioritised job gives you a bonus on starting too?

**Comment by The-Sun-In-Splendour** [comment]
Meh. Money isn't really valuable enough to make people either
1. Risk getting targetted by antagonists
2. Blind pick a job when they'd rather fill whatever's missing.

**Comment by The-Sun-In-Splendour** [comment]
Classic "mark as off-topic" anything that disagrees with your PR. This PR will not fix the "issue".

**Comment by ReturnToZender** [comment]
> Classic "mark as off-topic" anything that disagrees with your PR. This PR will not fix the "issue".
This is better feedback. Also I agree but I'll get paid more for doing what I was already doing. Stoked.

**Comment by BurgerLUA** [comment]
> Classic "mark as off-topic" anything that disagrees with your PR. This PR will not fix the "issue".

I did not mark your comment as off topic. I do not have the power to do that.

**Comment by Majkl-J** [comment]
I don't think it was me I hope

**Review by Majkl-J — APPROVED** [review]
It's not like credits matter when I can do one bounty and get all this money 10 minutes after joining

**Pull request merged**
