### PR TITLE
bluesec mekas

### PR DESCRIPTION
**Pull request by Kraseo**
## About The Pull Request

see title, adds bluesec meka sprites

## Changelog

:cl:
image: Bluesec meka sprites for security cyborgs.
/:cl:

### CODE REVIEW

**Comment by ReturnToZender** [comment]
If I had to make a guess, this is added to modular_skyrat, so editing this is likely a bad idea. Good change, but likely needs to be moved to modular_zubbers.

**Comment by Majkl-J** [comment]
Can we see the new sprite?

**Comment by zeroisthebiggay** [comment]
> Can we see the new sprite?

https://github.com/Bubberstation/Bubberstation/pull/296/checks?check_run_id=14554884698

**Comment by Kraseo** [comment]
will move to modular_zubbers today

**Comment by Kraseo** [comment]
imagen

i forgor 💀

**Comment by zeroisthebiggay** [comment]
can we give these things the stun baton tail from the redsec model because

image1image

this is visual inconsistency i really don't like

**Comment by Kraseo** [comment]
i think the medical and bluesec meka sprites are visually distinct enough from eachother, i'll talk with the person behind the sprites if a maintainer wants me to though

**Comment by Majkl-J** [comment]
I'd love the batontail back

**Comment by zeroisthebiggay** [comment]
> i think the medical and bluesec meka sprites are visually distinct enough from eachother, i'll talk with the person behind the sprites if a maintainer wants me to though

yeah but at a glance and especially in high tension situations it's hard to tell if this blue friendly looking robot is going to validhunt me or heal me

**Pull request merged**
