### PR TITLE
Adds sound effects to the subtler emote

### PR DESCRIPTION
**Pull request by Majkl-J**
## About The Pull Request

See name

## Why It's Good For The Game

https://discordapp.com/channels/1059199070016655462/1071095123145924679/1176626744783016009

## Changelog

:cl:
sound: Subtler now has a sound cue
/:cl:

### CODE REVIEW

**Comment by ReturnToZender** [comment]
The sound is "you got mail"

**Comment by zeroisthebiggay** [comment]
i really like `glockenspiel_ping` in `sound\effects` and i think it sounds less stupid and more in line for a 'hey tab in dipshit' than 'you've got mail'

https://github.com/Bubberstation/Bubberstation/assets/43571008/fb0bae2e-303e-462b-8349-ec18726491b4

**Comment by Majkl-J** [comment]
> i really like `glockenspiel_ping.ogg` in `sound\effects` and i think it sounds less stupid and more in line for a 'hey tab in dipshit' than 'you've got mail'
> 
>  glockenspiel_ping.mp4 
> also this is so easily able to be sent upstream it really isn't even funny tbh

Upstream doesn't deserve fun stuff (They do I'm just lazy)

**Review by StrangeWeirdKitten — CHANGES_REQUESTED** [review]
It's funny, but the sound is too memey for subtler. It should just be a notification jingle (like the one Zero posted) but it can be anything, really.

**Comment by Majkl-J** [comment]
> It's funny, but the sound is too memey for subtler. It should just be a notification jingle (like the one Zero posted) but it can be anything, really.

I'll go with the jingle, should work better. We should also totally testmerge this for a round or two to tweak around with the volume afterward so it isn't too loud and startling but not too silent.

**Comment by StrangeWeirdKitten** [comment]
> > It's funny, but the sound is too memey for subtler. It should just be a notification jingle (like the one Zero posted) but it can be anything, really.
> 
> 
> 
> I'll go with the jingle, should work better. We should also totally testmerge this for a round or two to tweak around with the volume afterward so it isn't too loud and startling but not too silent.

Plan on it

**Comment by zeroisthebiggay** [comment]
awesome

**Review by StrangeWeirdKitten — APPROVED** [review]

**Pull request merged**
