### PR TITLE
Brings back the old sombrero

### LINKED ISSUE #2355: Classic sombrero missing from vendors and loadout
### Client Version:

515.1643

### Issue Summary:

Over a year ago when vendor contents and loadout stuff got shuffled around, the good ol fashioned sombrero was lost, and instead replaced with the far far inferior Shamebrero. You cannot even select it as a style in the clothing vendor. 
image

Still exists, just called sombrero. Accessed by the chameleon clothes only.
image
image

Isn't she beautiful? Anywho, bring it back please. It's a splendid hat.

### Round ID:

_No response_

### Test Merge Information:

_No response_

### Reproduction Steps:

1. Go to loadout/costume vendor
2. Search for sombrero
3. Mourn

### PR DESCRIPTION
**Pull request by Maia-J**
## About The Pull Request

Reintroduces the sombrero to the vendors and adds it to the loadout.

image

As beautiful as the day we lost it. Also makes it not hide hair

closes #2355

## Why It's Good For The Game

Cool item to add to char design, and keeps you from dying on moonstation!

## Proof Of Testing

<details>
<summary>Screenshots/Videos</summary>

  image

</details>

## Changelog

:cl:
add: Sombreros return to clothes vendors and loadouts
qol: Sombreros no longer make you bald
/:cl:

### CODE REVIEW

**Comment by TacoSalad7** [comment]
I LOVE YOU

**Comment by TacoSalad7** [comment]
Also, apparently it used to make hair vanish, which is suboptimal. Could you maaaaaybe change that?

**Comment by Majkl-J** [comment]
> Also, apparently it used to make hair vanish, which is suboptimal. Could you maaaaaybe change that?

This is what I get from testing on lizards, I'll do that in an atomised PR

**Comment by Majkl-J** [comment]
nvm I did it on here

**Comment by ReturnToZender** [comment]
I like this kinda

**Review by Arturlang — APPROVED** [review]

**Comment by Sandmoney** [comment]
my favourite pr

**Pull request merged**
