### PR TITLE
Narcotics Refactor + Crystal meth and Lean

### PR DESCRIPTION
**Pull request by lpeapnni**
## About The Pull Request
Refactors the morenarcotics module from Skyrat, cleaning up the code and allowing for purity to be preserved for certain drugs' alternative forms. Also increases most drugs' addiction values and adds crystal meth, promethazine, and lean.

also the way i got this setup is that i just unticked the skyrat morenarcotics and bongs modules and added a new morenarcotics module to the bubber modules IDFK if thats the correct way of doing it but it seemed reasonable to me

## Why It's Good For The Game
The Breaking Bad RP Will Be Off The Chain...

## Changelog

:cl:
add: Added crystal meth
add: Added promethazine cough syrup and lean
balance: Increased addiction rates for most Skyrat narcotics
refactor: Refactored Skyrat narcotics code
/:cl:

### CODE REVIEW

**Comment by nevimer** [comment]
i think skyrat already had its own version of this - can you prove this works in testing videos

**Comment by YakumoChen** [comment]
Un-ticking doesn't work because of dependencies (ie cargo, loot pools) and is bad for maintaining

You might also just take this directly to skyrat first before PRing here

**Comment by TripleShades** [comment]
They closed it on Skyrat because they didn't want to deal with code standards.
I dont think that means it's acceptable to open downstream, if you're going to be like that.

**Comment by lpeapnni** [comment]
> i think skyrat already had its own version of this - can you prove this works in testing videos

ill get around to it soon

**Comment by nevimer** [comment]
poke

**Comment by lpeapnni** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAHHHHHHHHHHHHHHRRRRRRRRRRGGGGGGGGGGGHHHHHHHHHHHHHHHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by lpeapnni** [comment]
> i think skyrat already had its own version of this - can you prove this works in testing videos

Hopefully This Works

https://github.com/Bubberstation/Bubberstation/assets/126727752/f6c6ff45-e24d-469f-a340-7da83dc0405e


https://github.com/Bubberstation/Bubberstation/assets/126727752/e945bf4d-2dd6-4b0b-8ae9-3f77252f70d2


https://github.com/Bubberstation/Bubberstation/assets/126727752/871022ea-8a6c-4049-8d3a-af93ab0143cb

**Comment by YakumoChen** [comment]
Your map edits are not going to work, doubly because you unchecked the files they path to, so next time we merge from upstream the codebase will flip out

**Review by BurgerLUA — CHANGES_REQUESTED** [review]
These needs to be more modular. Unfortunately we are basically stuck with any Skyrat pathing names because if they add or change new stuff to the path, we have to follow it or shit will break.

**Comment by StrangeWeirdKitten** [comment]
I don't find Golden's code review completely unreasonable and there needs to be some modularization. It didn't look like something that would've been shot down. I am not comfortable with merging a PR on our repo when the author didn't want to work around some basic and reasonable coding standards.

**Comment by StrangeWeirdKitten** [comment]
I want the code standards from Golden's review before I consider having this merged. If it comes down here, it needs better modularization. You'll have better chance reopening this PR on skyrat in its current state.

**Pull request closed without merging**
