### PR TITLE
[NO GBP] [MANUAL MIRROR] Mirrors 4 synth wound PRs from skyrat, made by yours truely

### PR DESCRIPTION
**Pull request by nikothedude**
## About The Pull Request

https://github.com/Skyrat-SS13/Skyrat-tg/pull/26367
https://github.com/Skyrat-SS13/Skyrat-tg/pull/26368
https://github.com/Skyrat-SS13/Skyrat-tg/pull/26366
https://github.com/Skyrat-SS13/Skyrat-tg/pull/26365

## Why It's Good For The Game

Read the PRs

## Proof Of Testing

See the PRS

### CODE REVIEW

**Comment by StrangeWeirdKitten** [comment]
based

**Comment by StrangeWeirdKitten** [comment]
Is this on Skyrat or is this on Nova? Yes, there's a diffrence. We do not downstream from Nova. We're still downstreaming from Skyrat.

**Comment by nikothedude** [comment]
> Is this on Skyrat or is this on Nova? Yes, there's a diffrence. We do not downstream from Nova. We're still downstreaming from Skyrat.

both, im porting from skyrat here

see the linked prs in the pr body

**Comment by StrangeWeirdKitten** [comment]
> > Is this on Skyrat or is this on Nova? Yes, there's a diffrence. We do not downstream from Nova. We're still downstreaming from Skyrat.
> 
> both, im porting from skyrat here
> 
> see the linked prs in the pr body

Oh I'm blind, but yeah. In the future you don't need changelogs for mirrors.

**Comment by Cyprex** [comment]
Isn't this already in the upstream merge?

**Comment by nevimer** [comment]
pending upstream merge check

**Pull request closed without merging**
