### PR TITLE
Removes the n-spector contraband scanning

### PR DESCRIPTION
**Pull request by StrangeWeirdKitten**
Remake of #1868 due to master breaking.

## About The Pull Request

What the title says. The gates still function as intended.

## Why It's Good For The Game

This is a very arbitary magic wand device. I know there's a few things that block it (like smuggler satchels), but security should still search people manually and not walk up and scan them while they're typing. The gates themselves are fine.

## Proof Of Testing

It works.

## Changelog

:cl:
balance: N-Spect no longer has the capability for mobile contraband scanning.
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
This is an extremely bad change that undermines the entire point of the mechanic. People should just stop walking around with 24 pounds of contraband on them 24/7.

**Comment by projectkepler-ru** [comment]
> This is an extremely bad change that undermines the entire point of the mechanic. People should just stop walking around with 24 pounds of contraband on them 24/7.
> 
> Ban the people who are NRP walking up and scanning people. This is an administrative issue. Admins should do their job.

im with goof on this one it's already against the rules @StrangeWeirdKitten

**Comment by RadiantFlash7** [comment]
This is kind of a silly change. You need to stand still for 4 seconds while someone scans you as it is. If the scanner wasn't there, the person would just ask to see your bag and search you.

Hell, the scanner isn't supposed to pick up stealth contraband gear, so it's actually probably better for an antag to get scanned vs full strip searched.

**Comment by AllCorruptingWyrm** [comment]
thinking it over, I think this PR would benefit if it showed what can and cant the scanner find @Iamgoofball

**Comment by RadiantFlash7** [comment]
> thinking it over, I think this PR would benefit if it showed what can and cant the scanner find @Iamgoofball 

Per the PR that added it: image

**Comment by Redrover1760** [comment]
A lot of the fun of the game is trying to hide your contraband on your body when you get searched. This device seems silly and makes searching people too easy in my opinion.

**Comment by StrangeWeirdKitten** [comment]
When I have the time, I'll reintroduce an edit that's better thought out I had in mind

**Pull request closed without merging**
