### PR TITLE
Removes the donator requirement from loadout flowers.

### PR DESCRIPTION
**Pull request by xXPawnStarrXx**
## About The Pull Request
I don't see why the flowers are locked behind donator anymore, since you can literally get weed, liberty caps and a whole damn toolbox in the loadout.

## Why It's Good For The Game
Pretty flowers?

## Proof Of Testing
I can't show the testing, because I'm automatically given dono access on my own server.

## Changelog

:cl:
code: removed donator requirement from loadout flowers.
/:cl:

### CODE REVIEW

**Comment by ReturnToZender** [comment]
Modularize it and set them to DONATOR_ONLY = FALSE instead of removing their donator subtype

**Review by StrangeWeirdKitten — CHANGES_REQUESTED** [review]
What Zender said

**Comment by xXPawnStarrXx** [comment]
> Modularize it and set them to DONATOR_ONLY = FALSE instead of removing their donator subtype

I did it the way I did first time, because I didn't think there WAS a modular file, considering there's 2. I found the strange, misplaced one first. I've now resolved that.

**Review by Majkl-J — APPROVED** [review]
Ready to merge

**Pull request merged**
