### PR TITLE
Gives Ninjas and Contractors anti-theft explosive implants

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Alternative to #575

Ninjas and Contractors now have anti-theft explosive implants. These implants cause a light detonation on activation (after a telegraphed visual/audio delay), and gib the user. The implants only active on death or attempted implant removal, and cannot be manually activated.

## Why It's Good For The Game

Solves the issue of the crew gaining antag/ninja equipment without breaching the station too easily. While the crew can steal the antag's stuff on non-lethal capture, they cannot do this on lethal capture (which is much easier).

## Changelog

:cl: BurgerBB
add: Ninjas and Contractors now have anti-theft explosive implants. These implants cause a light detonation on activation (after a telegraphed visual/audio delay), and gib the user. The implants only active on death or attempted implant removal, and cannot be manually activated.
/:cl:

### CODE REVIEW

**Comment by nevimer** [comment]
I would prefer if people who removed the modsuit would activate a large-ish bomb that telegraphs to everyone it's going to blow up. The modsuit getting into the hands of crew was the root of the problem.

**Comment by StrangeWeirdKitten** [comment]
This will need discussion with #625

**Comment by bunny232** [comment]
Given these do not allow manual activation will atropine disable these implants allowing us to safely remove the modsuit.

**Comment by BurgerLUA** [comment]
> Given these do not allow manual activation will atropine disable these implants allowing us to safely remove the modsuit.

You can remove the modsuit, still. The implant will detonate if you die.

**Comment by StrangeWeirdKitten** [comment]
We're trying something else out for a short bit regarding #625

**Pull request closed without merging**
