### PR TITLE
Station power is finally stable and intelligent, can you believe it? [TM ONLY]

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request

Early ports of TG PR 84983 and 85043, Skyrat edits PR TBA.

modular_zubbers/master_files/code/modules/power/smes.dm will be removed once I've made the Skyrat edit upstream.

## Why It's Good For The Game

Fixes a myriad of power issues such as emitters dying due to low powernet power, shield gens, introduces intelligent APC charging. Powering the station with solars is actually viable to a degree, and solars actually assist in trickle charging.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

image

image

All APCs receive enough charging to maintain functionality. No more half the station at 100% and half at 0%.

image

Engine maintains power priority

</details>

### CODE REVIEW

**Review by Majkl-J — APPROVED** [review]

**Comment by StrangeWeirdKitten** [comment]
God bless

**Comment by StrangeWeirdKitten** [comment]
Seems like a TM only type of deal until you get the upstream sorted

**Comment by lessthnthree** [comment]
> Seems like a TM only type of deal until you get the upstream sorted

Yeah, it's marked TM only for that purpose. Will revise once I've done it upstream but the sooner we get this, the better.

**Comment by StrangeWeirdKitten** [comment]
> > Seems like a TM only type of deal until you get the upstream sorted
> 
> Yeah, it's marked TM only for that purpose. Will revise once I've done it upstream but the sooner we get this, the better.

I can't read 🙃

**Pull request closed without merging**
