### PR TITLE
Replaces the Oh Hi Daniel shuttle with something else

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

image

Why yes, I watched several of the same clip of the Room several times to get the layout just right.

## Why It's Good For The Game

The Oh Hi Daniel shuttle is much more chaotic on here than it is on /tg/ due to the fact that anyone can spam alcohol at the vendor and then flood the entire shuttle with very flammable liquid. Causes a lot of headaches for admins, so I decided to remove that aspect for it and then pretty much change it completely because I'm legitimately wild.

## Proof Of Testing

Draft because untested.

## Changelog

:cl: BurgerBB
add: Replaces the Oh Hi Daniel shuttle with a similar shuttle.
/:cl:

### CODE REVIEW

**Comment by OceanFish1** [comment]
Oh, hugobx, Daniel!

Have you considered just removing the bottles and booze-o-mat and leave it as it is?

**Comment by BurgerLUA** [comment]
> Oh, hugobx, Daniel!
> 
> Have you considered just removing the bottles and booze-o-mat and leave it as it is?

This PR practically does that while making the shuttle arguably more cramped.

**Comment by BurgerLUA** [comment]
image

image

Before and after comparison

**Comment by BurgerLUA** [comment]
Correction: The PR is a big of a hugbox because it has 2 extra tiles of walkable space.

**Comment by Majkl-J** [comment]
> Correction: The PR is a big of a hugbox because it has 2 extra tiles of walkable space.

Guess I'll be forced to close it then, this is unacceptable. 😏

**Comment by OceanFish1** [comment]
> Correction: The PR is a big of a hugbox because it has 2 extra tiles of walkable space.

you added two more rooms to that place, it's a huge amount of hugbox

**Comment by theselfish** [comment]
I was against this at first but noticing you recreated the whole ass apartment.
Hell yeah.

**Review by Majkl-J — APPROVED** [review]
I assume you tested it judging from your last commit name.

**Comment by BurgerLUA** [comment]
> I assume you tested it judging from your last commit name.

Yes.

**Pull request merged**
