### PR TITLE
You now need to spend 30 minutes in a round to be able to vote on transfer

### PR DESCRIPTION
**Pull request by Maia-J**
## About The Pull Request

You need to spend 30 minutes in game, living, and not afk, to be able to vote on a transfer.

Pros: 
 - Ghostroles get to vote again after spending enough time in a round
 - Leaving midround, or getting RRd still allows you to have a vote

Cons:
 - You have to actually play the game for 30 minutes (Impossible)

## Why It's Good For The Game

It gives our beloved ghost roles their vote back, and also still keeps ghosts from having a say in the game after not playing for the whole round.

## Proof Of Testing

I bashed two clients together on a test server. It is working

## Changelog

:cl:
qol: Makes the vote requirements code not terrible by allowing anyone with some effect on the round to use it
/:cl:

### CODE REVIEW

**Comment by Cyprex** [comment]
Are you eligible for a vote if you were alive for 30+ minutes at some point, but are now a ghost?

**Comment by Majkl-J** [comment]
> as long as you have spent a cumulative 30 minutes in round over any amount of characters you'll be eligible. But note that this ties into the existing playtime tracking system- in the DB this is only counted in 10 minute increments, this may well apply here too, so in practice you might(?) need to play a little more to get 3 10 minute chunks.

This is intentional to add a slight variation to the actual times and prevent people easily tracking it

**Comment by ReturnToZender** [comment]
based

**Comment by Iamgoofball** [comment]
This should still allow crewmembers on the station to vote regardless

**Comment by Majkl-J** [comment]
> This should still allow crewmembers on the station to vote regardless

No because then people can hop into the round for 5 minutes just to quickly get in a round end vote.

**Comment by Iamgoofball** [comment]
>No because then people can hop into the round for 5 minutes just to quickly get in a round end vote.

this is a stupid opinion and admins should be banning people who join exclusively to vote

**Comment by FoxxyRenamon** [comment]
> > No because then people can hop into the round for 5 minutes just to quickly get in a round end vote.
> 
> this is a stupid opinion and admins should be banning people who join exclusively to vote, this is not hard for admins to track at all

Would you like to tell the staff they must pay attention and ban anyone who votes after just joining a round, or do you have an actual useful suggestion and change to this PR?

**Comment by Majkl-J** [comment]
The general consensus in the team is that ghosts and players who do not participate in the round should not get their part in the vote. 30 minutes has been chosen as the lowest amount of time spent in order to have some meaningful impact on the round.

**Comment by Iamgoofball** [comment]
>Would you like to tell the staff they must pay attention and ban anyone who votes after just joining a round, or do you have an actual useful suggestion and change to this PR?

Code solutions are a hammer; we smash a lot of collateral when we use it. Admin solutions are the precision instruments. This is a situation where the precision instruments should be getting used so people who are actively participating in the ground do not get screwed out of voting in said round because they were at 29 minutes out of 30 or because DB polling hadn't counted time yet.

**Comment by Redrover1760** [comment]
> > Would you like to tell the staff they must pay attention and ban anyone who votes after just joining a round, or do you have an actual useful suggestion and change to this PR?
> 
> Code solutions are a hammer; we smash a lot of collateral when we use it. Admin solutions are the precision instruments. This is a situation where the precision instruments should be getting used so people who are actively participating in the ground do not get screwed out of voting in said round because they were at 29 minutes out of 30 or because DB polling hadn't counted time yet.

I don't think that's an issue considering that transfer votes are every 30 minutes now, it makes sense to have it set at 30 minutes playing in order to be able to vote.

**Comment by Snellie12** [comment]
Honestly I feel this makes the most sense as to what the voting should be. Everyone that actually cares about the round gets to have a say in what happens on if they continue or not. 

Will this result in, sometimes, a large amount of active ghost roles (Dauntless/Ashwalker/etc) voting and making Continue win? Yes. But so what? Cryobeds exist for a reason; if you don't want to keep playing, just go Cryo. If Vote Majority says continue, you are not forced to stay in the round.

**Comment by Majkl-J** [comment]
> Will this result in, sometimes, a large amount of active ghost roles (Dauntless/Ashwalker/etc) voting and making Continue win? Yes. But so what? Cryobeds exist for a reason; if you don't want to keep playing, just go Cryo. If Vote Majority says continue, you are not forced to stay in the round.

You can also hop on in thirty minutes and still have your vote, which means you can go take a break and vote once you come back. This wasn't the case before.

**Comment by Snellie12** [comment]
> > Will this result in, sometimes, a large amount of active ghost roles (Dauntless/Ashwalker/etc) voting and making Continue win? Yes. But so what? Cryobeds exist for a reason; if you don't want to keep playing, just go Cryo. If Vote Majority says continue, you are not forced to stay in the round.
> 
> You can also hop on in thirty minutes and still have your vote, which means you can go take a break and vote once you come back. This wasn't the case before.

Exactly. If someone REALLY wants their role that badly; they can just join pre-30 (not hard to do , because iirc, votes for rotation are 2:30. Just join before 2 hours)

I'm not entirely sure, but I just know that this is more fair for everyone.

**Review by projectkepler-ru — APPROVED** [review]
Tested for multiple days, certainly an improvement

**Pull request merged**
