### PR TITLE
Some tail fixes

### PR DESCRIPTION
**Pull request by thegrb93**
## About The Pull Request
Cherrypicks of some fixes I did. https://github.com/Skyrat-SS13/Skyrat-tg/pull/25635 https://github.com/Skyrat-SS13/Skyrat-tg/pull/25636

Haven't tested here yet, but works great on skyrat

## Why It's Good For The Game
Bug fixes for tail wagging

## Changelog

:cl:
fix: Lizard tail spines disappearing when wagging
fix: Vox can wag tail now
/:cl:

### CODE REVIEW

**Comment by nevimer** [comment]
it's a cherry pick, so it is not subject to modularity.

**Comment by nevimer** [comment]
im testmerging as I am sure we had it working already from a TG fix, but let's see

**Comment by Majkl-J** [comment]
> im testmerging as I am sure we had it working already from a TG fix, but let's see

Not entirely since spines were handled differently by skyrat

**Comment by thegrb93** [comment]
Tried in-game with the test merge and it's working well. @Majkl-J @nevimer

**Comment by StrangeWeirdKitten** [comment]
it's in the game now without this PR

**Pull request closed without merging**
