### PR TITLE
Is that a PDA in your pocket or are you just happy to subtle me

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request

Port of subtle PDA messaging from Effigy (https://github.com/effigy-se/effigy-se/pull/785)

When you begin a PDA message with the "#" symbol, it is marked as "subtle" stopping it from being shown to **ghost chats**. For when you have something you REALLY wanna roleplay but you only want a certain someone to see it (unless your PDA gets stolen, good luck explaining it then.)

A rigged message (PDA Bobm (spelt correctly)) will never be subtle, ever.

Also adds public logging for non-subtle PDA messages.

Closes https://github.com/Bubberstation/Bubberstation/issues/1788

## Changelog

:cl: LT3, vinylspiders, LordVoidron
add: Private (subtle) PDA messaging by adding "#" to start of message
qol: Added button to NTOS messenger TGUI to toggle private messaging
admin: Public logging for non-subtle PDA messages
/:cl:

### CODE REVIEW

**Comment by ReturnToZender** [comment]
Not sure how I feel about subtle PDA messages, there's been basically zero cases of abuse, but I do really like the PDA public logging fix. Can you atomize that?

**Comment by lessthnthree** [comment]
> Not sure how I feel about subtle PDA messages, there's been basically zero cases of abuse, but I do really like the PDA public logging fix. Can you atomize that?

Yeah

**Comment by StrangeWeirdKitten** [comment]
I'm fine with subtle PDA messages purely to decide if you don't want ghosts to see it. It still logs, and if security can still check it, then it's all good for me. I don't really see any abuse that could come out of it.

**Comment by lessthnthree** [comment]
Yeah there was no change to the logging. Still shows up on the console and all, just not to ghosts.

**Comment by lessthnthree** [comment]
Will come back to this later.

**Pull request merged**
