### PR TITLE
Cyborg-Reverse-Nerf

### PR DESCRIPTION
**Pull request by lurzefromgermany**
**About this PR.**

This PR adds in the Advanced plasma cutter for mining cyborgs, the crew monitor for Medical, as well as some bug fixes for the surgical processor. The BSRPED for engineering cyborgs, and the electrical welding tool upgrade. All items have been added to the techweb and fabricator. Attached is a file of the changes in action.

https://github.com/Bubberstation/Bubberstation/assets/70082939/1a7567d7-1be1-4443-8391-45ab8b18e191

**Why is it good for the game?**

This is good for the game, as it makes a cyborg player's job less mundane and encourages them to work just as hard as they used to. Medical borgs having Crew monitors allow fewer people to be dead in maints, while relying less on organic labor. 
The plasma cutter upgrade will encourage mining cyborgs to actually mine once again, This is great, and allows the regular miners to be even more reckless. 
BSREP for engineer cyborg, Cyborgs might once again upgrade machines for you, The old RPED required you to take apart the machine, Ain't no one got time for that.
Electrical welder upgrade for engineer cyborg. Allows for a better welder, just like the crew! 

I will stress, All the changes I have made are upgrade cards, meaning you don't have to give them to the cyborg. All the things I touched I have implemented duplication protection. 

**Change Log**

Change 1.
 lines 107 through 132 Added in the advanced plasma cutter upgrade to mining cyborgs, this was removed a few years back, re-adding it. Cyborgs will not have a plasma cutter at all, until the plasma cutter upgrade is installed. Duplication protection included

Change 2.
Added lines 533-538 Duplication prevention
Added lines 542-544 remove the surgical drapes from borgs when the surgical processor is inserted into the borg.
Added lines 551-554, re-add the surgical drapes when the surgical processor is removed.
This change was done to fix borg inventory clutter, The surgical processor does the same job as surgical drapes.

Change 3
 Changed lines 653 from var/obj/item/storage/part_replacer/cyborg/RPED to var/obj/item/storage/part_replacer/bluespace/RPED

Added comments to code

giving cyborgs a Blue space version when the upgrade is installed, rather than the bad regular one.

Change 4. 
Lines 657-685 Added in the crew monitor upgrade for medical borgs. Duplication prevention as well.

Change 5.
Lines 775-809 Added the electrical welding tool upgrade to cyborgs, removes the original welder when installed, and gives the old one back when uninstalled.

Change 6. 
Added the plasma cutter and crew monitor Borg upgrade to the mechfabricator_designs.dm
added the flag for research in all_nodes.dm the flags are  borg_upgrade_advcutter, borg_upgrade_monitor, and borg_upgrade_ewelder

Change 7. 
Added duplication protection on the RPED(line 653)

UPDATED CHANGES 1
removed the code I added for crew monitor, It's a duplicate now of an existing feature. Changed the Icon on the existing feature to be more accurate.

UPDATED CHANGES 2
Cyborgs could not refill the plasma cutter. So I change to code to make their plasma cutter take from their battery instead. Their plasma cutter can be recharged by charging.  Currently costs 300 power per shot. (Needs Balance checking)

:cl:
add: Advanced Plasma Cutter Upgrade for Mining Cyborg.
add: Electrical Welding tool for Engineering Cyborg.
balance: Changed the cyborg RPED upgrade to a BSPRED.
fix: Cyborg Rped can no longer be duplicated.
fix: Cyborg Surgical processor can no longer be duplicated.
fix: Cyborg Surgical processor now replaces drapes when installed.
fix: UI icon for the Crew monitor, now shows as the Crew monitor, instead of the Pinpointer, for Medical Cyborgs.
/:cl:

### CODE REVIEW

**Comment by Majkl-J** [comment]
Ok I actually wanted to add a crew monitor program but this works too

**Comment by destrucktoid** [comment]
Mediborgs already had a crew monitor though? It was locked behind a upgrade and if you didn't have the upgrade you could always use the one at medbay. Which to be fair was done quite frequently anyway.
Also i disagree with the BSRPED for engi borgs. Your statement that you had to deconstruct the machine to upgrade is completely false. You just need to screwdriver open the maintenance port which was still quite easy to do as a Engi borg.

**Comment by lurzefromgermany** [comment]
> Mediborgs already had a crew monitor though? It was locked behind a upgrade and if you didn't have the upgrade you could always use the one at medbay. Which to be fair was done quite frequently anyway. Also i disagree with the BSRPED for engi borgs. Your statement that you had to deconstruct the machine to upgrade is completely false. Once you have the regular RPED upgrade You just needed to screwdriver open the maintenance port which was still quite easy to do as a Engi borg.


1. yeah, they had the crew monitor... years ago. I readded it. You're thinking of the crew pinpointer, which could be coded out as the superior lifeline program exists.
2. the storage space in the RPED is complete dogcrap. Do you even see people use the normal RPED? No, they just wait until the BSRPED. It's tedious and there is no point to it.
3. All this PR does, is bug-fix some existing things, and then re-add some things that were removed, The borgs even used to get an experimental welder, but I opted to use the Electrical welder. The crew monitor was also something they used to have, I re-added it because I never see anyone besides myself purchase the handheld crew monitor from the vendor.
4. This is a QoL update, the cyborgs are not getting the upper hand from this update. These tools are all optional upgrades, that reduce the time it takes to do a basic task, These tools are also all obtainable by crew.

**Comment by magatsuchi** [comment]
will look at later today

**Comment by YakumoChen** [comment]
Please follow the correct format for your changelog

**Comment by YakumoChen** [comment]
> The borgs even used to get an experimental welder, but I opted to use the Electrical welder. 

This is a very large balance change as it allows cyborgs to freely heal and do so much faster

**Comment by YakumoChen** [comment]
>  Added in the crew monitor upgrade for medical borgs. 

This was likely removed to make it harder for borgs to "harm alarm" and run around freely doing so. I think it's fine if borgs have to stick to the medbay lobby if they want to harm alarm the crew monitor

**Comment by TripleShades** [comment]
>     1. yeah, they had the crew monitor... years ago. I readded it. You're thinking of the crew pinpointer, which could be coded out as the superior lifeline program exists.

They actually, legitimately, have it as an upgrade. It's not labeled properly, so you wouldn't know you have it unless you see the button in the top left.
>     2. the storage space in the RPED is complete dogcrap. Do you even see people use the normal RPED? No, they just wait until the BSRPED. It's tedious and there is no point to it.

You can actually print and load multiple RPED modules onto your borg. Is it stupid? Yes. Does it work? Also yes.

Also, the electrical welder is a huge buff, unless you're going to have it take from their internal cell, since it almost never runs out of charge even on the default power cell it uses. There's no reason to give them this huge advantage.

**Comment by lurzefromgermany** [comment]
> 



> Please follow the correct format for your changelog

pay me

**Comment by lurzefromgermany** [comment]
> You can actually print and load multiple RPED modules onto your borg. Is it stupid? Yes. Does it work? Also yes.
Yeah, however, that was unintended, they still had the old style of dupe protection, which no longer works. which is why I changed it in the code with this PR.

> Also, the electrical welder is a huge buff, unless you're going to have it take from their internal cell, since it almost never runs out of charge even on the default power cell it uses. There's no reason to give them this huge advantage.
That seems more like an issue with the electrical welder itself, But also remember, there are IPC/synth crewmates too!

**Comment by lurzefromgermany** [comment]
> > Added in the crew monitor upgrade for medical borgs.
> 
> This was likely removed to make it harder for borgs to "harm alarm" and run around freely doing so. I think it's fine if borgs have to stick to the medbay lobby if they want to harm alarm the crew monitor

It was removed long ago to encourage regular players to play the EMT job more thoroughly, all that changed was that Borgs no longer did it, and the issue stayed the same.

**Comment by yourdoom9898** [comment]
The cyborg crew pinpointer gives access to  *both* the aformentioned crew pinpointer and crew sensor manifest, and is therefore redundant.

**Comment by YakumoChen** [comment]
> > 
> 
> > Please follow the correct format for your changelog
> 
> pay me

PRs are called Pull Requests because they are a Request, not a Demand.

**Comment by lurzefromgermany** [comment]
> PRs are called Pull Requests because they are a Request, not a Demand.

And free code is a gift, not an entitlement.  My change log notes exactly what I did.

**Comment by YakumoChen** [comment]
> > PRs are called Pull Requests because they are a Request, not a Demand.
> 
> And free code is a gift, not an entitlement. My change log notes exactly what I did.

You're contributing to a codebase. Nobody is going to treat your code like a gift from the heavens. If anything, people who have commented clearly don't want it.

**Comment by lurzefromgermany** [comment]
> Your changelog is bad and won't show up in game.

Yeah will update it, changing some things

> * Crew monitor upgrade was specifically removed to stop borgs jobstealing from paramedics and harmalarming (they still do this but it helped)

Turns out, crew monitor wasn't removed, just the location was changed, So i'm removing that section of code. and changing the icon to be accurate.

> * electrical welding tool is infinite free self heal

Even so, still the same for synthetic crew members, the issue is with the welder itself

> * advanced plasma cutter is less egregious but just unnecessary powercreep

Power creep? It just makes mining faster. 

> * BSRPED is not great, it'd be better to just expand the capacity of the borg RPED a _bit_

But why? that's just a more tedious thing.

**Comment by YakumoChen** [comment]
> Even so, still the same for synthetic crew members, the issue is with the welder itself

Borg balance is not the same as synth balance (ignoring the fact synths aren't terribly well balanced to begin with)

> Power creep? It just makes mining faster.

That's literally what power creep is...

**Comment by lurzefromgermany** [comment]
Update 1, removed obsolete crew monitor code I added, a feature already exists. Changed the icon for that feature to properly reflect what it is, using the "scanner" icon for the UI. 

Removed typo from code.

added corrected changelog

**Comment by Majkl-J** [comment]
> > Power creep? It just makes mining faster.
> 
> That's literally what power creep is...

Does it make it better than a regular miner? No? Then I dont see the powercreep

**Comment by lurzefromgermany** [comment]
Update 2- 
Found a bug, Cyborg plasma cutter could not be recharged... Due to Borg's not having a hand to refill the plasma cutter.
Cyborg Plasma cutters now use the Borgs cell. 300 energy a pop. Needs balance checking.  To change how much each shot takes change the number in plasma.dm

**Comment by Strazyplus** [comment]
> Update 2- Found a bug, Cyborg plasma cutter could not be recharged... Due to Borg's not having a hand to refill the plasma cutter. Cyborg Plasma cutters now use the Borgs cell. 300 energy a pop. Needs balance checking. To change how much each shot takes change the number in plasma.dm

Not sure if this would be easy to achieve.
What about the recharger silo link. when recharging it gives the cyborg materials. could have that fuel the  plasma cutter. in addition I would suggest make it so it still uses small bit of energy from the cyborg to fire the plasma cutter.

**Comment by lurzefromgermany** [comment]
> Not sure if this would be easy to achieve. What about the recharger silo link. when recharging it gives the cyborg materials. could have that fuel the plasma cutter. in addition I would suggest make it so it still uses small bit of energy from the cyborg to fire the plasma cutter for realism than simply balance reasons.

Plasma cutters in real life use [electricity](https://www.youtube.com/watch?v=9qXja6MEsdE). 

Check to link to learn more! While adding plasma makes a miner makes sense, volatile fuel combustion makes the power.
Borgs are already massive machines. Right now, the current change I made, Is that the Plasma cutter uses the borgs battery.

**Comment by DeerJesus** [comment]
> > Not sure if this would be easy to achieve. What about the recharger silo link. when recharging it gives the cyborg materials. could have that fuel the plasma cutter. in addition I would suggest make it so it still uses small bit of energy from the cyborg to fire the plasma cutter for realism than simply balance reasons.
> 
> Plasma cutters in real life use [electricity](https://www.youtube.com/watch?v=9qXja6MEsdE).
> 
> Check to link to learn more! While adding plasma makes a miner makes sense, volatile fuel combustion makes the power. Borgs are already massive machines. Right now, the current change I made, Is that the Plasma cutter uses the borgs battery.

Plasma cutters in real life don’t shoot laser beams.

**Comment by TripleShades** [comment]
Noticed that one (possibly both) medical antag modules have both drapes and surgery scanner, if you want to make that consistant

**Comment by Detective-Google** [comment]
having played with the electric welder upgrade now it's definitely pretty busted, and running out of welding fuel isn't really a big deal anyway. should remove that part.

**Comment by YakumoChen** [comment]
Roll back the drapes thing, there's no need to sacrifice player confusion for a single inventory space.

**Pull request merged**
