### PR TITLE
Bubber CI checks

### PR DESCRIPTION
**Pull request by MosleyTheMalO**
## About The Pull Request
Adds support for bubber-related code for the CI checks

## Why It's Good For The Game
Helps ensure code sanity.

## Proof Of Testing
CI checks

### CODE REVIEW

**Comment by ReturnToZender** [comment]
This looks cool as heck but it's totally beyond me, can you explain what this is doing?

**Comment by BongaTheProto** [comment]
> This looks cool as heck but it's totally beyond me, can you explain what this is doing?

enables the code sanity checks that TG and skyrat use for bubber modular code

**Comment by ReturnToZender** [comment]
> > This looks cool as heck but it's totally beyond me, can you explain what this is doing?
> 
> enables the code sanity checks that TG and skyrat use for bubber modular code

Thank you, I understand now

**Comment by StrangeWeirdKitten** [comment]
Config updated

**Comment by nevimer** [comment]
Probably fine

**Comment by MosleyTheMalO** [comment]
@ReturnToZender @nevimer @StrangeWeirdKitten Is there any reason why `modular_zubbers\code\datums\materials\basemats.dm.` isn't included in tgstation.dme?

**Comment by StrangeWeirdKitten** [comment]
> @ReturnToZender @nevimer @StrangeWeirdKitten Is there any reason why `modular_zubbers\code\datums\materials\basemats.dm.` isn't included in tgstation.dme?

Primarily because it was causing major CI failures on its own. Feel free to delete it.

**Comment by nevimer** [comment]
Do not merge until upstream merge and ensuring nothing unintended is in the difference.

**Comment by MosleyTheMalO** [comment]
> Primarily because it was causing major CI failures on its own. Feel free to delete it.
very well

**Pull request merged**
