### PR TITLE
Adds old-style variants to drake and bone armor sets

### PR DESCRIPTION
**Pull request by aKromatopzia**
I found the old sprites and I put them back as a new item. Extremely cheap crafting recipe with the base one to recolour. I am not making it a resprite alt-click menu because it is a toggled suit and already has an alt-click function. The crafting recipe is item + 5 volcanic ash.

## Why It's Good For The Game

the new one looks cool, but the colours don't match the actual ash drake and whoever made it neglected to rest how it'd look on the lizards using it.

## Proof Of Testing
waw. Upper is human, lower is digi
Screenshot_97

Added a skull (bleached) variant reskin that makes a snout hole because I can
Screenshot_98
Screenshot_100

Also re-enabled hair on the drake armor because apparently this was requested. funny enough the skull helmet has its own defines which do this, already. Note that this only applies to the bleached variant, because I am lazy to make an entirely identical "ochre" drake armor except with different clothing flags; and due to item bloat.
Screenshot_99

Recipes:
Screenshot_101
Screenshot_102

## Changelog

:cl:
add: Bleached (old) drake suit armor, bleached (old) bone armor, and a new appearance for snouted skull helmet wears; and corresponding crafting recipes to swap between appearances
code: moved nerd (DOTA) suit into new armor_digi under custom_zubbers
/:cl:

### CODE REVIEW

**Comment by NargaInDisguise** [comment]
YEAAAHHH!! WOOOO YEAAAHH BABYY!!! WOOHOOOO!!

**Review by projectkepler-ru — CHANGES_REQUESTED** [review]
add a

`_t` state  for when it's toggled, you can just copy the base variant and not do any adjustment.

**Comment by aKromatopzia** [comment]
> add a
> 
> `_t` state for when it's toggled, you can just copy the base variant and not do any adjustment.

fiksed

**Comment by aKromatopzia** [comment]
oh hey found bone sprites one moment

**Review by projectkepler-ru — APPROVED** [review]

**Comment by aKromatopzia** [comment]
Alright now im done

**Comment by aKromatopzia** [comment]
> Wouldn't this be a lot simpler as just an alt click reskin for the armor?

Hoods can't be alt-click reskinned. For the bone and skull armors yes; For the ash drake no.

**Comment by projectkepler-ru** [comment]
> Wouldn't this be a lot simpler as just an alt click reskin for the armor?

It would be, yes, but also not really necessary, a refactor for this could be done if someone were so inclined

**Comment by aKromatopzia** [comment]
Oh oops didn't mean to make it a draft. But anyways, confirmed that you can't even make it on Skyrat either as a reskin because it acts weird when you move var/hoodtype from toggles.dm to items.dm

**Comment by aKromatopzia** [comment]
drafting because I currently can not fix the pr

**Pull request closed without merging**
