### PR TITLE
Lore updates that mef wanted

### PR DESCRIPTION
**Pull request by Szyszkrzyneczka**
I definitely forgot to include many species because now the returns must be a list of strings and not a string :)
I will fix this tomorrow

## About The Pull Request

Adds lore updates that mef and co made,

## Why It's Good For The Game

Idk mef wants it
## Proof Of Testing

Workie fine :)
## Changelog

:cl:
code: lore updates + species lore is now a list of strings instead of a string
/:cl:

### CODE REVIEW

**Comment by Szyszkrzyneczka** [comment]
I don't know why the fuck are these tests failing I didn't do shit to maps

**Comment by Majkl-J** [comment]
> I don't know why the fuck are these tests failing I didn't do shit to maps

Docker's down

**Comment by Erol509** [comment]
Instead of adding 10 milion files for each race, wouldnt it be better to append that into one file?

**Comment by Szyszkrzyneczka** [comment]
Tbh I did that to follow the file structure tg has, and also for future changes that would be done to any of those species so that all of the changes to one of the species made on bubber are in one file

**Comment by KazooBard** [comment]
Your pfp makes me immediately trust you and all you do. Please start balancing the code. - Glue sniffer

**Comment by nevimer** [comment]
What's the status on this?

**Comment by Szyszkrzyneczka** [comment]
Idk I guess the status is we wait until the the rest is written or sth, unless there are merge conflicts the pr can be merged

**Comment by projectkepler-ru** [comment]
Progress report please

**Comment by Szyszkrzyneczka** [comment]
failed checks are map related you can merge this

**Review by projectkepler-ru — COMMENTED** [review]
You don't have to put bubber edit on those thing, they're already bubber modular folder

**Comment by Szyszkrzyneczka** [comment]
Anything else you want me to do before I remove the comments? I want to make it all a one commit then be done with this pr.

I got a fetish pr to finish

**Review by Majkl-J — APPROVED** [review]

**Comment by Majkl-J** [comment]
Is this merge ready in your opinion? Looks fine by me

**Comment by Szyszkrzyneczka** [comment]
If there are no merge conflicts this can be merged.


When I checked there were no issues but on the offchance the tgui crashes, it just means that a species lore request proc sends a string instead of a list of strings.

Leaving this here in case someone in the future encounters this error

**Pull request merged**
