### PR TITLE
Removes The Clown storyteller making all event weights the same.

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Removes The Clown storyteller making all event weights the same.

## Why It's Good For The Game

This is a feature many don't know about. I just learned about this feature looking through the code and this set off warning flags in my head.

The code sets all weights to 1 for each of the tracks. This means that meteors has the same chance as a electrical storm. I'm sure there is some nuiance I'm missing here (such as the interactions with thresholds), but that's still insane to me.

## Proof Of Testing

If it compiles, it works.

## Changelog

:cl: BurgerBB
del: Removes The Clown storyteller making all event weights the same.
/:cl:

### CODE REVIEW

**Comment by plsleavemealon** [comment]
I am pretty sure that is the point of the clown though.  Its supposed to choose any event at pure random with no care for how destructive (or not) that event might be.

**Comment by Majkl-J** [comment]
> I am pretty sure that is the point of the clown though. Its supposed to choose any event at pure random with no care for how destructive (or not) that event might be.

It is stated in its description, and is a fairly recent change to make clown actually interesting as there's otherwise no reason not to pick a different high intensity teller.

**Comment by Arturlang** [comment]
image
The entire point of the clown is that it sets the weights the same, it's even described in the storyteller description explicitly. If you don't like that, remove the entire storyteller instead, otherwise there's not much point to having it vs the others

**Comment by Doom-external** [comment]
That's the point of the clown, and I personally love that it does that. It brings up events that aren't usually seen on other rounds, though maybe you could add some kind of extra cooldown on it being voted if you think it's rolled too often.

**Pull request closed without merging**
