### PR TITLE
[Modular] GooglyFox's Map Updates

### PR DESCRIPTION
**Pull request by ChromeFoxxity**
## About The Pull Request

I was always a fan of the IRS Pirates, it was the most fun I had as a pirate. So I gave them a little bit of a loot adjustment, and a new ship design. I also had the most fun as a Cybersun Ghost Role. So I decided to also add that onto the new map wagon. The Satellite was just to kill time.

I have tested the ship, and it works perfectly fine. Not sure about the IRS one, or the satellite.

## Why It's Good For The Game

I always wanted to see these look better, especially the forgotten ship. So I decided to do it myself, and make them shine brand new.

## Changelog

 I added a elite mod suit, and also a custom fleet console in the Captain's office. I have also added a few more clothing options, as well as a few new items to help them keep themselves busy. I also added a FAX machine as well. And a Holopad in the bridge. Almost all of these are to talk with Interdyne, or whatnot.

:cl:
add: Added Elite Modsuit, and Custom Fleet Console in Captain's office. I added actual cybersun headsets in their lockers, and guerilla gloves in the captain's locker. I added a FAX machine in the captain's office, and a Holopad in the bridge. I added more vendors, and a nice little scene in the conference room. I added new equipment in the lockers, I also added more wear for the captain, and a telescopic baton in the security room. I added one more syndicate mod suit, and added a morgue tray.
add: I barely touched new stuff for the IRS ship, but added a disabler in the prison area, and added marine security armor in the lockers instead of the default ones. I also just added a few more stuff, and bodies in the CentCom Satellite. Such as corpses, and whatnot. I added more stuff in the listening station. Also recreated Interdyne Research Base, and added new outfits, and ID's, and coded corpses.
/:cl:

image
image
image
image
image

### CODE REVIEW

**Comment by StrangeWeirdKitten** [comment]
If you're intending these to replace existing space ruins, then you'll need to add the necessary code changes. (Look at #520 if you want to see how I did it with Dauntless)

Except Cybersun. I'm fine with merging the map itself so it'll exist in the codebase, but Cybersun isn't coming back.

**Review by StrangeWeirdKitten — CHANGES_REQUESTED** [review]
If you're intending these to replace existing space ruins, then you'll need to add the necessary code changes. (Look at https://github.com/Bubberstation/Bubberstation/pull/520 if you want to see how I did it with Dauntless)

Except Cybersun. I'm fine with merging the map itself so it'll exist in the codebase, but Cybersun isn't coming back.

**Comment by ChromeFoxxity** [comment]
> If you're intending these to replace existing space ruins, then you'll need to add the necessary code changes. (Look at #520 if you want to see how I did it with Dauntless)
> 
> Except Cybersun. I'm fine with merging the map itself so it'll exist in the codebase, but Cybersun isn't coming back.

I'm not necessarily sure where to add the maps to. I've looked over the files a bit, and only seen the dauntless spawn code.

**Comment by StrangeWeirdKitten** [comment]
Any more added ruins will need to be atomized. (Made in a separate PR) since I still need to go through each one by one.

**Comment by Majkl-J** [comment]
I wanna know, are you still willing to work on this? I'd hate to see all the effort go to waste just because the original handling maintainer retired

**Comment by ChromeFoxxity** [comment]
> I wanna know, are you still willing to work on this? I'd hate to see all the effort go to waste just because the original handling maintainer retired

I'd love to, I just would love to see some of my work given the day of light in this server sometimes.

**Review by Majkl-J — CHANGES_REQUESTED** [review]
Ruin names should be with underscores and all lowercase. Also no need for extra descriptive names as the filenames are not what shows ingame.
(Example: `Fake Relay Station Snow.dmm` -> `fake_relay_snow.dmm`)

You'll need to give each of the ruins a `/datum/map_template/ruin/space/bubber`, with some extra legwork needed to get them to read the correct file and spawn. See `modular_skyrat/modules/mapping/code/space.dm`, `code/datums/ruins.dm`, and `modular_zubbers/maps/offstation/dauntless/code.dm` for a grasp on how to do it.

**Comment by ChromeFoxxity** [comment]
> Ruin names should be with underscores and all lowercase. Also no need for extra descriptive names as the filenames are not what shows ingame. (Example: `Fake Relay Station Snow.dmm` -> `fake_relay_snow.dmm`)
> 
> You'll need to give each of the ruins a `/datum/map_template/ruin/space/bubber`, with some extra legwork needed to get them to read the correct file and spawn. See `modular_skyrat/modules/mapping/code/space.dm`, `code/datums/ruins.dm`, and `modular_zubbers/maps/offstation/dauntless/code.dm` for a grasp on how to do it.

I see, thank you. But I'm not sure if I'll continue on this PR attempt. Space ruins aren't exactly pretty, and they probably aren't meant to be. I wanted to add extra fluff, and all, but the fluff I added are more stuff like desks, lore, and just a better looking shape. But then again, not everyone goes in space, so not everyone will even see, or care of these additions. Cybersun ship was also removed, so that unfortunately isn't coming back, no matter how much I'd love to play it here and there. I'm just not sure it's worth it.

**Comment by ChromeFoxxity** [comment]
Same goes for the syndicate comms agent, that is an extremely rare spawn, and might not even be worth it.

**Comment by ChromeFoxxity** [comment]
Plus I pushed this PR back when I barely knew how to use GitHub, and now I know I've been using the wrong map type, I was using DMM, and not TGM. Whatever map code they use here.

**Comment by Majkl-J** [comment]
> Plus I pushed this PR back when I barely knew how to use GitHub, and now I know I've been using the wrong map type, I was using DMM, and not TGM. Whatever map code they use here.

Should be easy to convert with the mapmerge tool under the tools folder, with some minor tweaks to stuff that may have changed. StrongDMM should help

Otherwise it is all up to you if you wish to continue the work or not, but I am gonna provide help if you decide you want to continue working on this, but won't hold it against you if you don't.

**Comment by Majkl-J** [comment]
Taken you have not chosen to work on this further. Oh well. closing due to stale

**Pull request closed without merging**
