### PR TITLE
Kangaroo Tail (Alt)

### PR DESCRIPTION
**Pull request by Scuhf-git**
## About The Pull Request

Adds an alternative version of the kangaroo tail for an option.

image
image
image
image

## Changelog

:cl:
add: Kangaroo Tail (Alt)
add: Kangaroo Tail sprite alternative
/:cl:

### CODE REVIEW

**Comment by Scuhf-git** [comment]
Messed something up, made this PR to late at night.

**Comment by Scuhf-git** [comment]
> Messed something up, made this PR to late at night.

Nvm just paranoid

**Comment by projectkepler-ru** [comment]
This work ? @Scuhf-git

**Comment by Scuhf-git** [comment]
@projectkepler-ru 
It works, tested in a private host and all, if it doesn't then scream at me and i'll fix it asap.

**Comment by Scuhf-git** [comment]
@projectkepler-ru 
Is this ok to fully merge and close now? Just wondering as i'm ready to PR some donator stuff.

**Pull request merged**
