### PR TITLE
[DNM] Moves the claw implant to 6 points

### PR DESCRIPTION
**Pull request by Majkl-J**
## About The Pull Request

This is one of the possible resolutions to the whole claw discussion.

The alternative is nerfing the weapon, as removal is downright just stupid.

## Why It's Good For The Game

We have decided that a roundstart weapon with less power than a kitchen knife is apparently too good to be only a 4 quirk point cost.

See here:
https://discord.com/channels/1059199070016655462/1162423073673322537

## Changelog

:cl:
balance: Razor claw implant point cost 4 -> 6
/:cl:

### CODE REVIEW

**Comment by nevimer** [comment]
I don't know... punching is more robust but doesn't cause bleed...

**Comment by Majkl-J** [comment]
> I don't know... punching is more robust but doesn't cause bleed...

Do chime in on it you're the maintainer here

**Comment by StrangeWeirdKitten** [comment]
> I don't know... punching is more robust but doesn't cause bleed...

The claw implant set to knife mode are a subtype of knives and they have the same attack value. But they're also undroppable. I would rather remove all its attack force and make people to buy the sharpening stone from an emagged cargo console if they want to cause any real damage with them.

**Comment by StrangeWeirdKitten** [comment]
what I said before

**Pull request closed without merging**
