### PR TITLE
racism.exe

### PR DESCRIPTION
**Pull request by NPC1314**
## About The Pull Request

Sooner or later some of the cringe and hugbox stuff that helped make Skyrat bad has to go.
Might as well start here.

Roundstart races commented out
Hemophage & Xeno hybrid

## Why It's Good For The Game

Both are far better as antags. Having them neutered on station crew that act exactly like any other crew is cringe.
Been tried for ages, never seen it done well, let it die. Or just keep adding cringe in endless layers of absolute garbo.
I'm doing my part, are you doing yours?

## Changelog

:cl:
del: Comments out roundstart hemophage and xeno hybrid
/:cl:

### CODE REVIEW

**Comment by Serxule** [comment]
you realize xeno hybrid isnt a literal xeno right

**Comment by Icarus-The-Sun** [comment]
We don't actually have implemented vampire antags at this time, and xenohybrids aren't actual xenos.

**Comment by zeroisthebiggay** [comment]
> cringe

okay buddy roleplays are inherently kind of cringe but removing character features from a roleplay server is what we in the business refer to as a way to antagonize your own playerbase

**Comment by Gr33d-y** [comment]
what a dreadful PR

**Comment by nevimer** [comment]
No. Doesn't work like this.

**Pull request closed without merging**
