### PR TITLE
[Modular] Doubles the amount of sacrifices required to ascend

### PR DESCRIPTION
**Pull request by Odairu**
## About The Pull Request
does as the title says

## Why It's Good For The Game
this makes it significantly less feasible a heretic can ascend before they've been noticed doing heretic things

## Proof Of Testing
image
(there being less than 2 heads of staff with minds adds 2 to the required number, so anywhere from 6-10 targets is possible)

## Changelog

:cl:
balance: nerfs heretics ability to ascend
/:cl:

### CODE REVIEW

**Comment by lilBlovy** [comment]
I dont play antags at all but I feel like making it more likely that you are the target of a heretic will make it more likely that you get caught out of left field without a real way to defend your self and sacrificed. I feel like the original 5 targets is more than fair since ascensions are rare even with 5. Its healthier for it to be not near impossible for antags to achieve it.

**Comment by BurgerLUA** [comment]
I appreciate a solution but this won't solve the issue. A common "meta" of heretics is to ask targets to willingly sleep on their ritual. If they say no, they just murder them.

The issue with ascensions is not only the effects of ascensions, but the fact that there are a few people on here who intentionally go out of their way to try and ascend. This leads to less focus on roleplay, and more focus on mechanics.

**Comment by projectkepler-ru** [comment]
Let me think about it

**Comment by NargaInDisguise** [comment]
> I appreciate a solution but this won't solve the issue. A common "meta" of heretics is to ask targets to willingly sleep on their ritual. If they say no, they just murder them.
> 
> The issue with ascensions is not only the effects of ascensions, but the fact that there are a few people on here who intentionally go out of their way to try and ascend. This leads to less focus on roleplay, and more focus on mechanics.

Yeah it's exactly this, it isn't that heretics don't get caught generally, it's that the heretics that play often ask for a willing sac, then just go murderbone if they don't get it. This doesn't make them "more likely to get caught," it makes them more likely to annoy the fuck out of people who don't want a gamer heretic to go through 10 sacs to ascend. This just ramps up mechanics and encourages murderbone to get their objective.

**Comment by Odairu** [comment]
> > I appreciate a solution but this won't solve the issue. A common "meta" of heretics is to ask targets to willingly sleep on their ritual. If they say no, they just murder them.
> > The issue with ascensions is not only the effects of ascensions, but the fact that there are a few people on here who intentionally go out of their way to try and ascend. This leads to less focus on roleplay, and more focus on mechanics.
> 
> Yeah it's exactly this, it isn't that heretics don't get caught generally, it's that the heretics that play often ask for a willing sac, then just go murderbone if they don't get it. This doesn't make them "more likely to get caught," it makes them more likely to annoy the fuck out of people who don't want a gamer heretic to go through 10 sacs to ascend. This just ramps up mechanics and encourages murderbone to get their objective.

This was explicitly done because a heretic in fact did simply stealth ascend. People dont like ascending more than they dont like the antag doing itd mechanics, this is a way for ascensions to become rarer without comepletely removing them.

**Comment by destrucktoid** [comment]
> > > I appreciate a solution but this won't solve the issue. A common "meta" of heretics is to ask targets to willingly sleep on their ritual. If they say no, they just murder them.
> > > The issue with ascensions is not only the effects of ascensions, but the fact that there are a few people on here who intentionally go out of their way to try and ascend. This leads to less focus on roleplay, and more focus on mechanics.
> > 
> > 
> > Yeah it's exactly this, it isn't that heretics don't get caught generally, it's that the heretics that play often ask for a willing sac, then just go murderbone if they don't get it. This doesn't make them "more likely to get caught," it makes them more likely to annoy the fuck out of people who don't want a gamer heretic to go through 10 sacs to ascend. This just ramps up mechanics and encourages murderbone to get their objective.
> 
> This was explicitly done because a heretic in fact did simply stealth ascend. People dont like ascending more than they dont like the antag doing itd mechanics, this is a way for ascensions to become rarer without comepletely removing them.

This _is_ de facto removing them. It's already nigh impossible to ascend most shifts with 5 sacrifices, doubling that is incredibly stupid. 
Furthermore, an anecdote of a single shift is _not_ a valid reason to do such a drastic balance change to Heretic. If stealth heretic of this degree becomes the meta then nerfs and changes should be considered. Jumping straight to doubling heretic sacrifices needed to ascend because a heretic in a single shift managed to ascend completely stealthily is both a bad solution and a drastic overreaction.

**Comment by AllCorruptingWyrm** [comment]
I'm not sure where the story of this being a one shift thing is being spread but that's absurdly false.  I've seen heretics do the most bare minimum RP with the strongest abilities in the game to get sacrifice targets. I've literally seen a Heretic sacrifice a head of staff in front of the entirety of Medbay while security was typing, leading to people getting (naturally), very annoyed in post round.

With that said, "oh well why dont we just police them-" No. These type of incidents are totally okay so its very much clear that rules aren't going to change how heretic functions. I think its absolute insanity that heretic players can do the most subpar RP they can to get the bare minimum of """"""""willing"""""" sacrifices and expect everyone to forget how they abused peoples trust in under three days. Heretic sacrifices should not be easy or willingly, they should be difficult, or at least dont merge this PR, bump heretic down from eotc and disable ascensions as a whole but this won't deal with the root problem of the antag, that being its made for tg and not Bubber.

**Comment by Arturlang** [comment]
If this is something that's neccesary to not remove ascensions, i'm all for this feature

**Comment by projectkepler-ru** [comment]
@Arturlang  historically, decisions made regarding antag has always been because there is a massive conflict of desired results
mechanically, well, the heretic is doing exactly what they're supposed to be doing, but characteristically, it's quite shitty
It's undeniable there are still the exact type of heretic that tzuler talked about
This PR was made in lue of a decision that did not reach maintainers.

@AllCorruptingWyrm 
perhaps it's the time those thing are brought up on a table and smacked with a bat until someone has a bright idea on what to do

and lastly
To all the end user whom may find this PR appealing, or appalling. Do consider that heretic itself is an extremely varied experiences for both the player and for the station goer
With each of the path having varying effects on the round itself, the effect that the heretic may produce and even the impact on each encounters can be heavily varied based on both experience, the type of heretic and ultimately. the willingness for that heretic to act. 

That being said, it is not to say within bubber, it has not been consistently poor, due to players of interests often not holding back. Communication between antag v protag always has been subpar, leading to needless death of players who don't want to get involved but want to partake in specific aspect of SS13 (ergo, medical, engineering or being an annoying mailman)
It's been a struggle ever since 2023 to find that middleground.  Now if it really had to come to it I wouldn't remove heretic nor double the ascension but I would've definitely reached out to Alexis Kennedy to ask about the game and see if I can get some inspiration for how we should proceed

**Comment by Redrover1760** [comment]
I think the main issue with heretics is that there is only one set of objectives for a heretic to have, necessitated by the fact that ascension was tied to completing the objectives a heretic has. And the fact that heretic is completely designed around tg and the set of objectives given. It doesn't encourage creativity whatsoever.

I don't really feel like this pr would help unfortunately.

**Comment by projectkepler-ru** [comment]
@Redrover1760  what do you suggest

**Comment by KeRSedChaplain** [comment]
my take is that ascensions themselves shouldn't be as simple to perform, it only takes 3 corpses to do any ascension so you can just grab 3 monkey cubes or just ascend in the morgue.

I think the materials should be based on the specific path chosen, like maybe ash would require ash _piles_, a lit bonfire, the caster at a certain high temperature, or some other fire-related item combination that'd be more fitting/harder to get than just 3 corpses

**Comment by IgiariValkyr** [comment]
Triple it. We just had two heretics ascend on the same shift.

**Comment by Rykka-Stormheart** [comment]
> Triple it. We just had two heretics ascend on the same shift.

That was a 120 pop shift, and a Clown round, AND the second heretic ascended after the first helped them do so. They were teaming up AND one ascended first and helped the other.

Very unusual circumstances.

**Comment by KazooBard** [comment]
> Triple it. We just had two heretics ascend on the same shift.

Okay so heretics have to kill 6-8 random people, how healthy for the game do you think it will be if 9-12 random people have to go into the timeout dimension and wait for medbay to patch them up before continuing their own business instead of the 5 minute shuttle ride that happens when round ends? 

Do you think heretics have to game more or less to get more kills in a given timeframe?

**Comment by Rykka-Stormheart** [comment]
> > Triple it. We just had two heretics ascend on the same shift.
> 
> Okay so heretics have to kill 6-8 random people, how healthy for the game do you think it will be if 9-12 random people have to go into the timeout dimension and wait for medbay to patch them up before continuing their own business instead of the 5 minute shuttle ride that happens when round ends?
> 
> Do you think heretics have to game more or less to get more kills in a given timeframe?

This. You increase the kills, you **force** heretics to have to gamer harder if they want to ascend. As it stands, ascension is still really fucking hard unless you're hyper robust, or get lucky and Sec is distracted.

**Comment by KazooBard** [comment]
> > > Triple it. We just had two heretics ascend on the same shift.
> > 
> > 
> > Okay so heretics have to kill 6-8 random people, how healthy for the game do you think it will be if 9-12 random people have to go into the timeout dimension and wait for medbay to patch them up before continuing their own business instead of the 5 minute shuttle ride that happens when round ends?
> > Do you think heretics have to game more or less to get more kills in a given timeframe?
> 
> This. You increase the kills, you **force** heretics to have to gamer harder if they want to ascend. As it stands, ascension is still really fucking hard unless you're hyper robust, or get lucky and Sec is distracted.

Kind of like that clown round had 2 rad storms and a dragon that killed all the targets… weird

**Comment by Rykka-Stormheart** [comment]
> > > > Triple it. We just had two heretics ascend on the same shift.
> > > 
> > > 
> > > Okay so heretics have to kill 6-8 random people, how healthy for the game do you think it will be if 9-12 random people have to go into the timeout dimension and wait for medbay to patch them up before continuing their own business instead of the 5 minute shuttle ride that happens when round ends?
> > > Do you think heretics have to game more or less to get more kills in a given timeframe?
> > 
> > 
> > This. You increase the kills, you **force** heretics to have to gamer harder if they want to ascend. As it stands, ascension is still really fucking hard unless you're hyper robust, or get lucky and Sec is distracted.
> 
> Kind of like that clown round had 2 rad storms and a dragon that killed all the targets… weird. But pff, noooo, its the amount of kills that’s the problem, not stupid random bs falling into place!

AND, as mentioned, the antags helping each other. (Which, for heretics, is allowed). It was a perfect storm of "everything went right AND it was a Clown round"

**Comment by StrangeWeirdKitten** [comment]
guys it's been 12 hours since _that specific round_. It's time to stop arguing in a PR that was merged over three months ago.

**Pull request merged**
