### PR TITLE
Removes the quirk gifted.

### PR DESCRIPTION
**Pull request by Yanziko**
## About The Pull Request

this just gets rid of the quirk gifted.

## Why It's Good For The Game

why the fuck are we giving people free points in the first place? negative quirks are meant to make it so people have downsides to their positives, not just let people have whatever they want. 

## Proof Of Testing

image
note the lack of the quirk gifted

## Changelog

:cl:
del: gets rid of gifted

/:cl:

### CODE REVIEW

**Review by Majkl-J — CHANGES_REQUESTED** [review]
This will need discussion between maintainers. Feel free to point out anything you could get for 6 quirk points to put you at a serious mechanical advantage

**Comment by YakumoChen** [comment]
Razor claw implants

**Comment by projectkepler-ru** [comment]
> Razor claw implants

elaborate

**Comment by YakumoChen** [comment]
They are knives that can't be disarmed, and notably allow you to do eyestabs

**Comment by projectkepler-ru** [comment]
> They are knives that can't be disarmed, and notably allow you to do eyestabs

the first part is whatever, there are like, worse thing you can do with that is not even the fact you have a knife. , though the second part can be touched on

**Comment by YakumoChen** [comment]
You can also buy a thing from cargo to make them 15 force knives you can't disarm near roundstart

**Comment by Majkl-J** [comment]
> They are knives that can't be disarmed, and notably allow you to do eyestabs

You mean the ones nobody uses because they actually just suck in any practical combat situation? Also if those are the one issue, just nerf their damage or make them retract on knockdown

**Comment by projectkepler-ru** [comment]
> You can also buy a thing from cargo to make them 15 force knives you can't disarm near roundstart

you can also do a lot of thing that's worse than stabbing people, also if this was genuinely an issue you can message or ping me @especiallystrange on discord because I am a lot more active when it come to the balancing

**Comment by Yanziko** [comment]
> This will need discussion between maintainers. Feel free to point out anything you could get for 6 quirk points to put you at a serious mechanical advantage

1. night vision, 4 points, allows a serious advantage in low light conditions due to the fact you can see where others cannot.
2. hardened soles, 2 points, completely prevents getting glass sharded
3. linguist/bilingual, 4 points both, allows way more languages than is normal which provides minor advantage in a few scenarios
 (side note, somebody should make buff bilingual, it costs the same for less) 

those are the only three i can think of off the top of my head, but you also have to understand that this can be added onto two point negative quirks which are practically free for 8 points for things like free running, which completely negates fall damage.

**Comment by projectkepler-ru** [comment]
> 
> 1. night vision, 4 points, allows a serious advantage in low light conditions due to the fact you can see where others cannot.
> 2. hardened soles, 2 points, completely prevents getting glass sharded
> 3. linguist/bilingual, 4 points both, allows way more languages than is normal which provides minor advantage in a few scenarios
>    (side note, somebody should make buff bilingual, it costs the same for less)
> 
> those are the only three i can think of off the top of my head, but you also have to understand that this can be added onto two point negative quirks which are practically free for 8 points for things like free running, which completely negates fall damage.

1, this is a thing that exist in TG and I have that quirk on all my char while still having  no actual practical downside
2.  so?
3. This is so fucking specific that I cant even perceive it as an issue

**Comment by Yanziko** [comment]
i'm simply stating which perks that are actually pretty good and provide an advantage that can be bought with 6 free points with no downside. 

also, second one is actually pretty strong if you play for example ashwalker, though admittedly is far stronger in codes without lizards able to wear shoes..

**Comment by projectkepler-ru** [comment]
> i'm simply stating which perks that are actually pretty good and provide an advantage that can be bought with 6 free points with no downside.
> 
> also, second one is actually pretty strong if you play for example ashwalker, though admittedly is far stronger in codes without lizards able to wear shoes..

holy shit I had no idea ashwalker can't wear shoes

**Comment by Majkl-J** [comment]
The decision has been made. The quirk will stay.

**Pull request closed without merging**
