### PR TITLE
kill people with a rock

### PR DESCRIPTION
**Pull request by The-Sun-In-Splendour**
## About The Pull Request
cain-and-abel-1-1342035817

## Changelog

:cl:
add: you can now kill people with a rock
/:cl:

### CODE REVIEW

**Comment by yorii** [comment]
I would honestly try to PR this to tgstation instead so we can receive it downstream.

**Comment by The-Sun-In-Splendour** [comment]
> I would honestly try to PR this to tgstation instead so we can receive it downstream.

downstreams and upstreams are agents of moloch also the item in question isn't on tg

**Comment by yorii** [comment]
yeah sorry, I assumed the blacksmith

> > I would honestly try to PR this to tgstation instead so we can receive it downstream.
> 
> downstreams and upstreams are agents of moloch also the item in question isn't on tg

Haha true indeed, and yeah I jumped the gun a bit before realizing rocks aren't a common ss13 item :p

**Comment by Elli-Skala** [comment]
> ~I would honestly try to PR this to tgstation instead so we can receive it downstream.~
> 
> nvm this isn't from tgstation

Actually it's from skyrat

**Review by Majkl-J — APPROVED** [review]
/modules/stone/code/stone.dm is my new favorite filepath

**Comment by Majkl-J** [comment]
Also I have been told this is the Rust update

**Comment by projectkepler-ru** [comment]
Me about to kill the next person who tells me that NTC is an erp role

**Review by StrangeWeirdKitten — APPROVED** [review]

**Pull request merged**
