### PR TITLE
Ports #28102 from upstream

### PR DESCRIPTION
**Pull request by theselfish**
## About The Pull Request
https://github.com/Skyrat-SS13/Skyrat-tg/pull/28102

## Why It's Good For The Game

I want the drip.

## Proof Of Testing

bnmkpsra3lna1

## Changelog
:cl:
add: Some unused items found their way to the command vendor. And a new coat!
fix: Added some missing HoS items to the ComDrobe
/:cl:

### CODE REVIEW

**Review by projectkepler-ru — COMMENTED** [review]
uh let me check with @waterpig about this since it's not a player-facing change

**Comment by theselfish** [comment]
> uh let me check with @waterpig about this since it's not a player-facing change

This adds items to a vendor. You might be thinking of https://github.com/Bubberstation/Bubberstation/pull/1624

**Comment by projectkepler-ru** [comment]
> > uh let me check with @waterpig about this since it's not a player-facing change
> 
> This adds items to a vendor. You might be thinking of #1624


No
I specifically am asking because the PR lack a commit history.

**Comment by theselfish** [comment]
> > > uh let me check with @waterpig about this since it's not a player-facing change
> > 
> > 
> > This adds items to a vendor. You might be thinking of #1624
> 
> No I specifically am asking because the PR lack a commit history.

I don't really know how to do a commit history.
Exact same PR as I made upstream.

**Comment by projectkepler-ru** [comment]
> I don't really know how to do a commit history. Exact same PR as I made upstream.

eeeh in that case it's whatever.
the point of that being github will assume whenever you upload something that you are the original author of it, commit history is important if you're downstreaming stuff

but if you are the one doing it both up there and down here then it dosen't really matter

**Comment by theselfish** [comment]
> > I don't really know how to do a commit history. Exact same PR as I made upstream.
> 
> eeeh in that case it's whatever. the point of that being github will assume whenever you upload something that you are the original author of it, commit history is important if you're downstreaming stuff
> 
> but if you are the one doing it both up there and down here then it dosen't really matter

image
See?

**Review by Majkl-J — CHANGES_REQUESTED** [review]
Gonna need you to git cherry-pick this one

The commit hash doesn't add up with the skyrat one (`4764b9d4f126f9cabbef32f14a25429e62620412`)

**Comment by Majkl-J** [comment]
If you already have a git remote setup this should be as easy as fetching it, otherwise it's:
`git remote add Skyrat https://github.com/Skyrat-SS13/Skyrat-tg`
`git fetch Skyrat`
`git cherry-pick 4764b9d4f126f9cabbef32f14a25429e62620412`

**Comment by theselfish** [comment]
@projectkepler-ru @Majkl-J Think I done it right?

**Comment by Majkl-J** [comment]
Merged with upstream

**Pull request closed without merging**
