### PR TITLE
Reworks Stamcrit, Buffs Batons + Disablers to compensate.

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Stamcrit has been reworked. Previously, getting stamcritted would make you unable to move for the duration and unable to get up, but that has been replaced with not being able to use items and unable to get up.
You are paralyzed for 4 seconds when entering stamcrit for the first time, with a visible message about you collapsing.
Currently, the chance to resist out of grabs is 60% per try, and when you have 80 or more stamina damage, that chance is 30%. This PR makes it that if you're also incapacitated from a stamcrit, the total combined chance is 15% per try.

Stunbatons deal 45 stamina damage per hit (from Skyrat's 35, from /tg/'s 60).
Stunbatons now have an attack delay of 2 seconds (from 2.5 seconds).
Stunbatons now have zero knockdown on hit (from 5 seconds).
Stunbatons now knock you down for 3 seconds on hit if you're clumsy (from 15 seconds).
Stunbatons no longer have a delayed knockdown effect.

Note that this does not affect Beepsky for Beepsky is a god and no dogshit nerf PR can touch him.

Changes the collapse emote from unconscious to paralyze, as I think this was the unintended behavior in the first place given how it is used in radiation code.

## Why this is good.

Stun based combat is pretty bad. Nearly every coderbase has removed stuns in some capacity or is in the process of removing stuns in favor of different mechanics. The core reason is that it really isn't fun not being able to do anything because someone hit you once or twice.

To compensate the additional time of arresting someone and the added difficulty of arresting more than one person at once, the security equipment that deals stamina damage has been buffed.

Note that this PR is a double edged sword because previously, people could use items even when in stamcrit. Now this changes it in favor of being able to crawl away.

## How do I arrest/capture/etc?

Do what you normally do, but when they're on the ground, grab (passively, aggressively if you want to be sure) and cuff.  This will of course take longer, even with the Stunbaton buff.

## Why isn't [insert mechanic here] affected/addressed?

Because I forgot it existed. If you think something should be affected by this PR, then please comment below and make sure to smash that like button and hit that subscribe button. Also ring that bell and turn on notifications, and be sure to subscribe to my OnlyFans.

## Changelog

:cl: BurgerBB
balance: Reworked how stamcrits affect humanoid mobs by allowing stamcritted people to move, but not use items.
balance: Stunbatons no longer knockdown on hit (or after a short while), but deal more stamina damage and have a higher attack speed.
balance: Changes the collapse emote from unconscious to paralyze. This only affects manual usage from the emote as well as automatic usage from radiation poisoning.
/:cl:

### CODE REVIEW

**Comment by nevimer** [comment]
this is the dota patch we have been waiting for

**Comment by kiwedespars** [comment]
is this a joke pr i can't tell

**Comment by BurgerLUA** [comment]
> is this a joke pr i can't tell

no it's actually serious :(

**Comment by nevimer** [comment]
ill testmerge this soon, it seems promising?

**Comment by kiwedespars** [comment]
ok well.

looks awful and i don't have to see a testmerge to understand that. stun-based combat is meh, this is true, but tg has this weird mix of stam-and-stun combat. stamina combat imo is like citadel's where you have knockdowns and shit.

>To compensate the additional time of arresting someone and the added difficulty of arresting more than one person at once, the security equipment that deals stamina damage has been buffed.

this does nothing because you're just allowing them to crawl away without being able to stop them at all. if you understand the current iteration of combat you know that stamina, unlike cit's stam combat, doesn't trickle back in. it comes back all at once after a set amount of time

>Note that this PR is a double edged sword because previously, people could use items even when in stamcrit. Now this changes it in favor of being able to crawl away.

kinda??? not really. people can't shoot you with a weapon inhand or stab you, they're stunned after they go into stamcrit. right now they're just weirdly not getting an overlay applied nor are they being forced to drop their inhands.

when i think stuncombat i think the vg-esque rocket tag where, the moment you're hit, you cannot do anything for [x] amount of time. this just looks frustrating from a security standpoint but hey man you do you

**Comment by BurgerLUA** [comment]
> ok well.
> 
> looks awful and i don't have to see a testmerge to understand that. stun-based combat is meh, this is true, but tg has this weird mix of stam-and-stun combat. stamina combat imo is like citadel's where you have knockdowns and shit.
> 
> > To compensate the additional time of arresting someone and the added difficulty of arresting more than one person at once, the security equipment that deals stamina damage has been buffed.
> 
> this does nothing because you're just allowing them to crawl away without being able to stop them at all. if you understand the current iteration of combat you know that stamina, unlike cit's stam combat, doesn't trickle back in. it comes back all at once after a set amount of time
> 
> > Note that this PR is a double edged sword because previously, people could use items even when in stamcrit. Now this changes it in favor of being able to crawl away.
> 
> kinda??? not really. people can't shoot you with a weapon inhand or stab you, they're stunned after they go into stamcrit. right now they're just weirdly not getting an overlay applied nor are they being forced to drop their inhands.
> 
> when i think stuncombat i think the vg-esque rocket tag where, the moment you're hit, you cannot do anything for [x] amount of time. this just looks frustrating from a security standpoint but hey man you do you
> 
> in addition: something something the real "one hit win" of tgcombat is stunbaton -> shove. which also gets mitigated by the incredibly easy to acquire pump-up or whatever that lets you shrug off specifically stunbaton hits. i also don't know how this fixes it being a one hit win since you're going down into stamcrit, which now just locks you to crawling away annoyingly rather than actually fighting back?

To stop someone after you stun them, grab them. I tested everything against a very uncooperative monkey and I was able to grab them and perform arrests.

**Comment by ReturnToZender** [comment]
Monkeys WERE harmed in the making of this PR.

**Comment by kiwedespars** [comment]
>To stop someone after you stun them, grab them. I tested everything against a very uncooperative monkey and I was able to grab them and perform arrests.

what does this prove. monkeys do literally nothing after you aggrograb them

**Comment by kiwedespars** [comment]
overall

stunbatons deal 15 more stamina, meaning they stamcrit in 3 hits instead of 4.
detective's baton/telescopic batons stamcrit in 3 hits instead of 4
batons lose their ability to disarm because um i guess idk.
"reworks" stamcrit into being able to crawl which means
- you get grabbed off the bat after being stamcrit, otherwise nothing has really changed other than that people just can't tell if someone is actually stamcrit now since there's no indicator

disablers get their ammunition count doubled despite the nerfs being targeted towards batons more i guess? if you really wanted to buff them could just buff the travel speed of disablers by like 30%.

i'll check tomorrow and actually lab the stuff though, this is less of a rework and more of a "i hate knockdowns and disarms grr" pr

**Comment by BurgerLUA** [comment]
There seems to be a lot of misunderstandings with this PR. I'll try to address them as they come along.

A way to tell if someone has been stamcrit is if they've fallen on the ground after you've hit them a few times.

The stamcrit changes affect anything that deals stamina damage.

The stunbaton changes only affect stunbatons (battery powered ones), not detective's baton or telescopic batons.

Maintenance pump-up is still useful as it gives you the TRAIT_BATON_RESISTANCE trait, which makes you immune to the knockdown effects of any batons that cause knockdowns, such as the detective's baton or telescopic batons.

Batons do not disarm anymore, but on stamcrit they prevent you from using the items in your hand.

**Comment by kiwedespars** [comment]
>A way to tell if someone has been stamcrit is if they've fallen on the ground after you've hit them a few times.

i guess. i'd just like the old dark overlay back because it made the most sense

>The stamcrit changes affect anything that deals stamina damage.

how does it justify going from 20 disabler shots to 40. this is a pretty massive buff?

>The stunbaton changes only affect stunbatons (battery powered ones), not detective's baton or telescopic batons.

fair i misread what was getting touched

>Maintenance pump-up is still useful as it gives you the TRAIT_BATON_RESISTANCE trait, which makes you immune to the knockdown effects of any batons that cause knockdowns, such as the detective's baton or telescopic batons

ig just seems strange to nullify it as a chem aside from fighting the detective/heads

>Batons do not disarm anymore, but on stamcrit they prevent you from using the items in your hand.

you were never able to use items in your hand while in stamcrit, because of TRAIT_INCAPACITATED. you just don't drop your inhand if you were already resting by the time you got stamcrit, which admittedly should be fixed for clarity's sake

i want to just ask what's the positive of changing stamcrit. stunbatons getting a nerf i can see, valid, but changing stamcrit to be an annoying crawl does nothing for the combat nor does it make any improvement on it, and i especally don't see it justifying **doubling** the ammo count of disablers.

**Comment by Hatterhat** [comment]
does shoving someone who's down from stamcrit cause the shove-chain paralyze or no

**Comment by BurgerLUA** [comment]
> does shoving someone who's down from stamcrit cause the shove-chain paralyze or no

This PR doesn't alter how or when stamcrit removes itself, or stamina damage when you already have stamcrit.

**Comment by Majkl-J** [comment]
Why do we even need this in the first place? We aren't exactly a heavy combat/antag focused server in the first place, pretty sure most people have tot off, as I see only like 8-9 players roll tot constantly.

**Comment by zeroisthebiggay** [comment]
how the fuck do you even handcuff people
why do you consider this a baton buff

**Comment by Higgin** [comment]
> Contributor

monkeys don't break out of shit, they don't do a thing after aggro-grabs - with the aggro-grab nerfs in #242 and how nerfed a lot of SR nonlethal stuff is, I do not see this working well. Maybe try a TM, but on all principles, seems like a bad idea.

**Comment by splood** [comment]
this sucks bollocks
the pr makes it so stamina damage behaves like any other damage type, but you regenerate it
a better alternative is to use fucking buckshot because at least they wont get back up 5 seconds later

**Comment by Higgin** [comment]
You need hard disables at some point, and people in stamcrit couldn't use stuff in-hand before either (i.e. lings, martial artists, nightmares) - not at all a fan of this in play, it leads to a lot more free wiggling around, and the mild buffs to damage (still far sub tg in the baton's case) do not remotely compensate.

**Comment by Majkl-J** [comment]
I saw 5 sec have trouble with ONE antag (Round 1570) this shit is completely broken and doesn't belong on here, put it on like a combat server

**Comment by kiwedespars** [comment]
i re-iterate:

is this a joke pr lol?

**Comment by Fragenstien** [comment]
This should be unmerged. The effect has been security resorting to lethals due to losing their ability to stun people. Because moving interrupts things like cuffing and grabs, the fact that people in stam-crit can crawl forever means they can't be apprehended without putting them into crit lethally.

**Comment by Majkl-J** [comment]
Relevant conversation
image

**Comment by BurgerLUA** [comment]
Did you guys try grabbing the person who on the ground?

**Comment by BurgerLUA** [comment]
There are two types of grabs. There is the ctrl click drag grab and then there is the actually using an empty hand to grab. Many of the people who are complaining to me are reporting that they are trying to grab people with items in hands and aren't properly grabbing people.

**Comment by BurgerLUA** [comment]
People were complaining about not being able to tell that someone was actually knocked down, and not just faking it, so I added a visual "collapse" indicator when someone enters stamcrit. As a bonus, collapsing now paralyzes you for 4 seconds.

**Comment by Majkl-J** [comment]
Still, why do we need this even? Getting hit thrice with a baton is already pretty hard (Unless you suck), and seccies do need nonlethal takedown methods. The only thing this really achieves is making combat slightly more annoying when you already won at it.

**Comment by Majkl-J** [comment]
What I feel you fail to understand here is the difference between stun based combat (Tasers are a great example - took one hit to stun) and combat that ends in a stun, where once you lose the exchange (After 3 hits with a melee only weapon), you get punished for losing the exchange - stunned.

There are very specific places where stuns are needed to make combat not annoying. If my target can still crawl around after I won the exchange, all this achieves is making it more annoying for me to finish them.

**Comment by BurgerLUA** [comment]
Batons literally took 1 hit to stun because they had a delayed knockdown effect.

**Comment by kiwedespars** [comment]
> Batons literally take 1 hit to stun because they had a delayed knockdown effect on top of the initial knockdown effect.
> You cannot gaslight me into thinking this PR isn't needed.

finally he's revealing his true agenda. you can nerf batons you can do whatever, except there's a billion better ways of going about it rather than making combat more clunky. there's no gaslighting because this pr ISN'T needed. it's disingenuous to pose this as a "stamcrit rework + baton and disabler buff!"

- disablers don't need 40 shots, they just need their projectiles to be 30% faster, that way most players can actually land it. if you think otherwise, i think you genuinely haven't engaged in the combat
- batons need to just have a delayed knockdown. again, that's what it was prior. there was no instant knockdown otherwise trading with a contractor would be a valid strategy. this allows them to disarm people who don't actively do the bare minimum to avoid it, whether it be resting or using pump-up, which they should considering how easy it is to get.
- the stamcrit rework is worthless. this doesn't change "stun combat." get rid of it, it just makes the game clunkier.
- even a four second paralyze isn't going to make it okay. literally just fix the overlay, holy shit why are there so many unnecessary changes just to try and push your own idea.

so much unnecessary shit in this pr

**Comment by kiwedespars** [comment]
> Batons literally take 1 hit to stun because they had a delayed knockdown effect on top of the initial knockdown effect.

this explains so much on it's own though because there's no initial knockdown effect. you genuinely just haven't played security yet you want to touch it so badly

if you're talking about detective's baton, telebaton, contractor, i suppose that's valid?

except this pr doesn't target those so i don't know what you're going for in the fucking slightest

**Comment by BurgerLUA** [comment]
who are you

**Comment by kiwedespars** [comment]
arreksuru/suru can you answer the above points

**Comment by Detective-Google** [comment]
in the rounds it was testmerged it led to a situation where stun batons could not be relied upon to truly neutralize a threat meaning that everyone involved was just itching to pull out their gun /harm baton and just crit the person so they stopped bloody wiggling around as they  tried to cuff them.

 This played out in a round I was in where a contractor was effectively mobbed by security, at least 4 people with batons I think more, and, it was just impossible to cuff the guy, he kept wiggling away. aggro grab? he'd resist and break it, the dude was flopping around genuinely for a minute or two all the while everyone is trying their hardest not to just crit him so he stops moving.

stun batons are already generally considered worse than just shooting people bc blood loss is so damning, so making them even less appealing just makes the lethals even moreso. Do we really wanna encourage 'i use the shotgun' further.

**Comment by BurgerLUA** [comment]
Right, I probably should've done this earlier and put the foot down considering that all the code changes were basically lost in a sea of complaints and a lot of what I've seen is quite outdated and/or misinformed. I've been avoiding responding to comments because people are being excessively rude and I'd thought they'd get bored by now.

# Here is what stunbatons do, as of now in this PR and the changes.

Stunbatons take 3 hits on someone to enter stamcrit. On the 3rd hit, you'll go into stamcrit if you haven't regenerated your stamina by then.
- On entering stamcrit, you will collapse and be unable to move for 4 seconds. If you took maintenance pump-up, this effect is not applied. 
- While in stamcrit, you will not be able to use items, be on the floor, and be allowed to move (assuming nothing is preventing you from moving). 
- While in stamcrit, it will be harder to resist grabs.

Disablers effectively have their capacity doubled.
Stun batons now have less of a delay.

# Intent (of this PR).

Stun based combat is terrible and needs to be tweaked slowly. No one really likes the stamina system, so that is being tackled first by changing how stamcrit works. Making a single PR that changes nearly every aspect of stun-based combat will not work because sudden changes upset people. As of right now, I legitimately cannot give a shit right now about people complaining about other mechanics (shoves, slips, etc) because that is outside the scope of this PR.

The disabler change was added to offset the nerf to stamcrits since group arrests would be a little more difficult.

# How to deal with situations.

Hit assistant with stunbaton repeatedly.
If they keep resisting, grab them.
If they resist the grabs, use flashes and pepperspray.
If they resist the flashes and pepperspray, beat them.

**Comment by Higgin** [comment]
i'm less convinced as this goes on, i'd rather we hew to the current balance than anything that's been proposed here.

**Comment by Majkl-J** [comment]
> i'm less convinced as this goes on, i'd rather we hew to the current balance than anything that's been proposed here.

Same, honestly this caused too much of an uproar and I do not wanna hear of any stun-stam changes anymore. Just keep it as-is, and if what burger is saying about people moving away from it, someone will solve it upstream, probably without it being a half-arsed PR that was tested on monkeys.

**Comment by BurgerLUA** [comment]
Uproar was basically caused by a handful of people who, for some reason, became super aggressive here and on discord about the PR and already decided it was shit before any testing was made.

After testing was made, people encountered (or more accurately, basically heard someone talk about the encounter) a singular issue where a security team struggled to detain 1 person and after that, they then declared the PR to be turbo shit.

Changes were then made to reflect it but people threw their hands in the air and declared it's still shit because 

"is this a joke pr haha is this a joke hahahaha" (????)
"you don't play security" (?????????)
"you can't even bother to read the code" (this was over because I said "Batons literally take 1 hit to stun because they had a delayed knockdown effect on top of the initial knockdown effect." when I meant "delayed knockdown effect on top of the initial stam effect"
"bubberstation is not a combat server" (which I guess means combat never happens?)

image

**Comment by Higgin** [comment]
> Changes were then made to reflect it but people threw their hands in the air and declared it's still shit because

for what it's worth, I made a lot of contributions and tweaks on hestia before it went down. i pretty massively changed the combat balance there.

the contributions and the hours i had playing sec and command didn't necessarily make those changes better for the game or to use.

and i've got a lot more hours in sec on SR, where the situation was both arguably worse (grabs were stronger for everyone off of any knockdown, not just stamina knockdowns) and yet still comparable to here (batons being nerfed heavily compared to /tg/, where i've also played quite a bit of sec.) 

image
image


and not as many, but still quite a few more than that here, where we've made the change to unfuck grabs being as good as they were...

this PR would be better if grabs were better, but grabs being better like they were was not good. 

this PR and this overall approach is not good. this is not needed, especially not the stamcrit stuff - all it does is give more play to a part of /tg/ combat that is already massively frustrating, crawl combat, and make it nigh-on impossible to keep somebody locked down even after investing significant effort into them. batons occupy a place of practically last resort compared to a lot of security's other tools right now, where applicable, but they have value against antags who might, say, have sunnies, bowmans, and scarp, as a weapon of last resort. making it require repeated reapplications after stamcrit to keep somebody still, with a very short timer (four seconds isn't hardly enough to cuff somebody,) runs up hard into the fact that a lot of antags have or bring inherent EMPs, and you're often dealing with multiple enemies. with 4+ hits to down somebody in a lot of fights, that charge is disappearing fast, and it very quickly becomes more practical to just crit the motherfucker and kill them if they heal. 

the attack delay and marginal stamina damage buff (i think we could go to /tg/'s 60, flatly, and be fine) are both immaterial benefits unless you've got bolas (they're good, folks) and only make bolas more necessary if you were going to run into an enemy you have to use batons against (see above.)

as arreksuru brought up, you can counter the first-hit knockdown (even avoiding dropping your stuff, or being vulnerable to a paralyze kick) just by laying down, or using pump-up, or any other variety of chems and tricks out there.

but removing the first-hit knockdown, and then needing four+ more hits to stamcrit if they're dodging, and then needing to reapply it to keep them down, multiple times (when say, you're dealing with somebody in a flash-protected syndie MOD, or they're crawling around giving people avulsions with an armblade and EMP screeching) shows a terrible, surface-level awareness of the balance considerations around batons that tg does the hard work on. 

disablers suck because people can easily outrun the projectiles, even here, but moreso here because our higher overall stamina and their lowered damage means the application of slowdown from a few successful hits isn't meaningful enough to help anchor those needed to take somebody down. 

i am amazed there has been no mention in this PR of flashes except by proxy as a 'here, I guess it's the thing you can use when your baton runs out of charge' - even if they go out from one EMP (which batons, balanced for two-tap stamcrit on tg, don't for a reason - it's to make them a reliable fallback option, at some level, and keep people from stealing or converting everything into a police baton every round) flashes are about as close to oldschool tg tasers/batons as sec has these days on people who don't have them. something like 90-120 damage, instant knockdown, and every secoff has protection from them unless they chose a quirk against it. 

I think you should take these changes upstream and float them there.

**Comment by BurgerLUA** [comment]
The reason I posted my playtime is because someone claimed that I had no hours in security and that I couldn't read code. It was not meant as a "I am more experienced than you" but rather that I actually have hours in security and I know how things work.

Crawl combat won't apply here because you cannot use items while knocked down due to stamcrit, and personally I think having the ability to move around is miles better than being stuck on a tile unable to do anything. This is what the PR here is for. If someone wants to make a PR that completely removes crawl combat and stuns, then they are free to do so and I think touching shoves/disarms/crawling/etc in this PR would not be atomized.

Changes are not going upstream because Skyrat does not have a good grip on balance and I am banned from their discord for pissing off the host to properly discuss things. For things like bugfixes, sure, but for changes that affect Bubberstation's environment, I think balance changes should go here.

**Comment by Higgin** [comment]
>Let me be clear, I didn't mean SR, I meant tg.

**Comment by BurgerLUA** [comment]
> Let me be clear, I didn't mean SR, I meant tg.

/tg/ is way different and for me to arrive there and make a balance PR despite not playing on a /tg/ server in for over a year would not be healthy for their coderbase

**Comment by Higgin** [comment]
> > Let me be clear, I didn't mean SR, I meant tg.
> 
> /tg/ is way different and for me to arrive there and make a balance PR despite not playing on a /tg/ server in for over a year would not be healthy for their coderbase

tg is where you're going to get the most useful and thorough feedback on these changes because tg is where the mechanical game is most intense and varied.

We want to be able to run that game here - like you said, combat happens even if we're more of an "RP" server. So is Manuel.

We want the game to be fun and hold up well. If it passes muster at tg, it's going to be consistent with the game design considerations of people who are only interested in making the competitive game better.

I don't see anything in this PR really addressing the RP consequences. Until there's a proprietary case for Bubber (like fixing one of SR's mistakes,) we should probably look to tg or at least be willing to test and float our ideas there.

**Comment by zeroisthebiggay** [comment]
sometimes i ask myself how someone can keep arguing this hard over a pr with such an overwhelmingly negative response. i've barely seen anyone in the comments and not even a `singular` positive reaction on the text body itself.

obviously a vast majority of the playerbase doesn't look at the github because they're afraid of code but that accentuates the idea that making batons needlessly complex to where the 'combo' to stun someone is having to beat them several times and then aggrograb them during an unexplained four second grace period before having to figure out whether or not they're just 'soft stunned' and trying to crawl away or 'active' and are just hiding the fact they could pull out a gun and shoot you at any moment

at this point just hold a discord poll of whether or not the playerbase sees these changes as `positive` and close it based on that because i'm speaking with confidence that i imagine the results would likely be pretty glaring towards one side or the other

**Comment by zeroisthebiggay** [comment]
> sometimes i ask myself how someone can keep arguing this hard over a pr with such an overwhelmingly negative response. i've barely seen anyone in the comments and not even a `singular` positive reaction on the text body itself.
> 
> obviously a vast majority of the playerbase doesn't look at the github because they're afraid of code but that accentuates the idea that making batons needlessly complex to where the 'combo' to stun someone is having to beat them several times and then aggrograb them during an unexplained four second grace period before having to figure out whether or not they're just 'soft stunned' and trying to crawl away or 'active' and are just hiding the fact they could pull out a gun and shoot you at any moment
> 
> at this point just hold a discord poll of whether or not the playerbase sees these changes as `positive` and close it based on that because i'm speaking with confidence that i imagine the results would likely be pretty glaring towards one side or the other

addendum: just realized that making baton stuns grab resist based literally makes batons rng incarnate
why
why do we need rng to be the deciding factor
why can't we just let skilled players win the engagement
why can i just win the baton war because i pressed b and rolled a funnier number than my attacker
why

**Comment by BurgerLUA** [comment]
Overwhelming negative feedback =/= two to three people typing up a storm.

**Comment by Majkl-J** [comment]
> 



> Overwhelming negative feedback =/= two to three people typing up a storm.
> 
> Resisting grabs is not pure RNG but rather weighted RNG. If you were stunbatoned into stamcrit and then grabbed, you will have an extremely low chance to actually resist out of a grab.
> 
> Fighting baton on baton is more "skill based" in my PR because it isn't a fight between who can land the first hit in a funny (and honestly dogshit) combat system where the sprite is the hitbox (but not really, even worse considering the movement system means that where your sprite is doesn't actually mean where you are), but rather several in a short period.

> first hit
Did you just disregard the entire lay down point, which might even give you a slight split second advantage due to said hitbox being different

**Comment by zeroisthebiggay** [comment]
> Overwhelming negative feedback =/= two to three people typing up a storm.

everyone i've spoken to seems to not like this but sure let's focus on the vocal minority `(the entire composition of the people who browse the github)`

> Resisting grabs is not pure RNG but rather weighted RNG. If you were stunbatoned into stamcrit and then grabbed, you will have an extremely low chance to actually resist out of a grab.

rng is rng
you're still gambling your life on a diceroll

> Fighting baton on baton is more "skill based" in my PR because it isn't a fight between who can land the first hit in a funny (and honestly dogshit) combat system where the sprite is the hitbox (but not really, even worse considering the movement system means that where your sprite is doesn't actually mean where you are), but rather several in a short period.

everything i've seen about this pr just seems to make baton fights even more into rocket chases that are still going to come down to 'who lands the first hit' since whoever gets hit first is going to have stamina slowdown and thus be `substantially` easier to be danced in and out of range

that's partially to  be blamed on tg's high movement speed yes but this just makes baton fights rocket chase duels that are only marginally better than trying to break someone's leg with a high force weapon

after the rocket chase you then have to gamble victory based on rng grab resists! fun!

**Comment by BurgerLUA** [comment]
> > Overwhelming negative feedback =/= two to three people typing up a storm.
> > Resisting grabs is not pure RNG but rather weighted RNG. If you were stunbatoned into stamcrit and then grabbed, you will have an extremely low chance to actually resist out of a grab.
> > Fighting baton on baton is more "skill based" in my PR because it isn't a fight between who can land the first hit in a funny (and honestly dogshit) combat system where the sprite is the hitbox (but not really, even worse considering the movement system means that where your sprite is doesn't actually mean where you are), but rather several in a short period.
> 
> > first hit
> 
> Did you just disregard the entire lay down point, which might even give you a slight split second advantage due to said hitbox being different

yeah I did because that might be the craziest thing i've ever heard

**Comment by Majkl-J** [comment]
Im happy this shit is almost dead, someone finish it off please

**Comment by BurgerLUA** [comment]
It's not dead in the slightest wtf are you talking about

**Comment by Majkl-J** [comment]
Its been inactive for like a week and untestmerged for about double that.

**Comment by BurgerLUA** [comment]
There are like 57 open pull requests right now and about 10 of them are already testmerged. That doesn't mean a thing.

**Comment by BurgerLUA** [comment]
New change: Currently, the chance to resist out of grabs is 60% per try, and when you have 80 or more stamina damage, that chance is 30%. This PR makes it that if you're also incapacitated from a stamcrit, the total combined chance is 15% per try.

**Comment by The-Sun-In-Splendour** [comment]
Bad pr

**Comment by BurgerLUA** [comment]
Might remake at a later date.

**Pull request closed without merging**
