### PR TITLE
Lunchboxes

### PR DESCRIPTION
**Pull request by Sylphet**
## About The Pull Request

This PR adds lunchboxes, available in your loadout under "other". It can only hold food and drinks, and it's limited to 4 slots so you can't stuff it with 12 big bite burgers and never visit the kitchen again.

There's seve- ...uh, _**six**_ options to pick from, those being -
- Nanotrasen
- Medical
- Safety Moth
- Hearts
- Corgi
- Rabbit
- the other one

## Why It's Good For The Game

It adds cute RP stuff, you can pack lunches for your friends, you can take your food to go if you're in a hurry - but not so much food that you don't need to go to the kitchen anymore.

## Proof Of Testing

lunchbox

## Changelog

:cl:
add: adds lunchboxes that hold food and drinks to the loadout
image: added lunchbox sprites
/:cl:

### CODE REVIEW

**Comment by BurgerLUA** [comment]
~~Lunchboxes are powergaming.~~

**Comment by Sylphet** [comment]
ok

**Comment by YakumoChen** [comment]
I'd remove the stripes on the sides, it makes them look like medkit resprites.

Maybe have the handles look more simple so they don't look like big briefcases? They could probably be smaller overall.

**Comment by StrangeWeirdKitten** [comment]
Aurora has some good lunchbox sprites if you want to do (credited) sprite pulls from another codebase.

**Pull request merged**
