### PR TITLE
Flotilla Station

### PR DESCRIPTION
**Pull request by nevimer**
Flotilla Station PR for testmerging purposes. 
Map needs a lot of work, still? We'll find out. 

https://github.com/Skyrat-SS13/Skyrat-tg/pull/20922
All credits to this PR.

### CODE REVIEW

**Comment by EvenInDeathIStillServe** [comment]
Why do we still need more maps, exactly?

**Comment by Oscari-pog** [comment]
Bro theres a .357 in the bridge - and shotgun ammo boxes that can spawn with the Gateway exclusive rounds, including the RIP rounds, which are just, comically lethal. Also we dont need more massive maps.

**Comment by zeroisthebiggay** [comment]
> Why do we still need more maps, exactly?

**Comment by Serxule** [comment]
i dont mind more maps but maps that are split apart like this are generally disliked and make it far, far harder for moving around, and negatively impacts most antags

**Pull request closed without merging**
