### PR TITLE
The Great Akula Lore Rewrite

### PR DESCRIPTION
**Pull request by okithedoki**
## About The Pull Request

Changes the descriptions of the Akula species, shoredress, and flags to match the updated Akula lore.

## Why It's Good For The Game

Removes the pesky Skyrat lore, and begins to usher in the new, Bubberized Akula lore, giving players better context.

## Proof Of Testing

image

## Changelog

:cl:
add: Akula now have a proper description and lore.
tweak: Akula wetsuits, flags, and CC uniform descs edited to conform to new Akula lore.
/:cl:

### CODE REVIEW

**Comment by sippykot** [comment]
i see a problem with it... like, it just re-describes a bunch of stuff, changing the context
and has the same problem as the Tiziran changes where you just had the flag renamed without changing
also the descriptions for the wetsuits are... less descriptive

**Review by Majkl-J — COMMENTED** [review]
Feel free to make the examine_more more descriptive but thank god the regular desc is finally short

**Comment by sippykot** [comment]
looking at the loadout again... we already have 2 shork flags, and this renames both into the Akulan ones... even the one with the literal shark teeth bite mark
we really should leave one as the "old"/royalist flag

**Comment by okithedoki** [comment]
Alright, let me address the concerns



> i see a problem with it... like, it just re-describes a bunch of stuff, changing the context and has the same problem as the Tiziran changes where you just had the flag renamed without changing also the descriptions for the wetsuits are... less descriptive

That is the entire point. The old descs make reference to things that aren't canon in places, and dear lord the massive textwall of the old suits was annoying as hells. The objective was to de-novelize the old, lengthy descs and put them more in line with the descs of every item from the rest of the game. In the future I may use examine_more to provide better detail, but I feel like it'd be nicer for the players to be able to describe their own stuff, customized to their liking.



> looking at the loadout again... we already have 2 shork flags, and this renames both into the Akulan ones... even the one with the literal shark teeth bite mark we really should leave one as the "old"/royalist flag

This is a sprite issue. Both the banner and the flag have the same sprite when folded out because of wackiness. I originally WAS going to have one be the flag of the Kingdom of Agurrkal, but when I found out both were the literal same flag I thought that would be too confusing. I hate that one flag has a different scheme folded up than it does when deployed.
So, if you know any spriters who will remake one of the flags, I will gladly change that flag to a Kingdom of Agurrkal one when they do.

**Comment by Majkl-J** [comment]
> So, if you know any spriters who will remake one of the flags, I will gladly change that flag to a Kingdom of Agurrkal one when they do.

Try asking Cepha, she's a good bean when it comes to spriting

**Review by Majkl-J — APPROVED** [review]

**Pull request merged**
