### PR TITLE
Dismemberment from wounds only works if the target is not conscious (soft crit, hard crit, unconscious, dead).

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Dismemberment from wounds only works if the target is not conscious (soft crit, hard crit, unconscious, dead). This includes decapitation, limb removal, and disembowelment.

## Why It's Good For The Game

Boy I sure love getting hit once and getting instantly disemboweled due to how RNG works.
Boy I sure love getting decapitated near constantly because I was shot in the head by a skyrat-balanced bullet.
Boy I sure love waiting 10 minutes for all my organs to be inserted again, only to wait another 10 minutes because the doctor didn't notice that all of them rotted.
Boy I sure love spending 15 minutes in the medical bay while some stuttering Teshari player with the flavortext "dogborgs only" ignores my decapitated head in medical bay because it blends in with the clusterfuck of clutter on the ground.

Nah but seriously this is good for the game because of balance reasons. Skyrat balance is legitimately wack with how much brute damage was put into rotation, especially when combined with the clusterfuck that is the /tg/station wounds system. Previously before all these new features, decapitation was very rare and only seen with stuff like dswords and ling blades.

## Changelog

:cl: BurgerBB
balance: Dismemberment from wounds only works if the target is not conscious (soft crit, hard crit, unconscious, dead). This includes decapitation, limb removal, and disembowelment.
/:cl:

### CODE REVIEW

**Comment by destrucktoid** [comment]
How about instead of making this salt change this you instead help with the effort to remove all the "skyrat balanced" weapons? Decapitation and dismemberment are key features of weapons such as the (d)esword. This change indirectly nerfs those for no reason other than salt PR. A legitimate combat tactic is to attack people's legs with the desword or esword to dismember them and knock them to the ground. This change just... makes that not happen which makes no logical sense, no sense balance wise and nerfs weapons which have high dismemberment chance for no reason.

**Comment by BurgerLUA** [comment]
> How about instead of making this salt change this you instead help with the effort to remove all the "skyrat balanced" weapons? Decapitation and dismemberment are key features of weapons such as the (d)esword. This change indirectly nerfs those for no reason other than salt PR. A legitimate combat tactic is to attack people's legs with the desword or esword to dismember them and knock them to the ground. This change just... makes that not happen which makes no logical sense, no sense balance wise and nerfs weapons which have high dismemberment chance for no reason.

nah

**Comment by YakumoChen** [comment]
Limit it to decaps and disembowls

**Comment by nevimer** [comment]
I think this goes against game mechanics. I think wounds should happen more and health bar should happen less.

**Comment by BurgerLUA** [comment]
> I think this goes against game mechanics. I think wounds should happen more and health bar should happen less.

I'm fine with wounds happening more, but decapitations and disembowelments are very against progression and encourage antagonists to instead just make it a soft requirement to invest in armor if you're ever doing combat. I've unironically seen some heretics ditch the robes they get and just use bulletproof armor and helmets from the armory to protect against bullet wounds.

**Comment by destrucktoid** [comment]
> > I think this goes against game mechanics. I think wounds should happen more and health bar should happen less.
> 
> I'm fine with wounds happening more, but decapitations and disembowelments are very against progression and encourage antagonists to instead just make it a soft requirement to invest in armor if you're ever doing combat. I've unironically seen some heretics ditch the robes they get and just use bulletproof armor and helmets from the armory to protect against bullet wounds.

I'm calling cap on this, heretic robes are some of the best armor in the game, even vs bullets. Why would they ditch them in favour of bulletproof armor?

**Comment by nikothedude** [comment]
Unless you changed something down here, you cant actually get decapped/disembowled until you're in hardcrit

image

**Review by Majkl-J — CHANGES_REQUESTED** [review]
Make it modular

**Comment by BurgerLUA** [comment]
> Make it modular

you literally cannot

**Comment by Majkl-J** [comment]
> > Make it modular
> 
> you literally cannot

You can

**Comment by Majkl-J** [comment]
Just make a override with a super call to the original

`if(owner && owner.stat == CONSCIOUS)
		return
..()`

**Comment by StrangeWeirdKitten** [comment]
```
/obj/item/bodypart/chest/can_dismember(obj/item/item)
	if(owner.stat < HARD_CRIT || !get_organs())
		return FALSE
	return ..()
```


This already exists. It just handles dismemberment via hard crit and this change would be redundant because you're already unconscious when you are in this state. I'm closing this PR because the code already handles dismemberment through hard crit and this makes no difference when you're slashing someone with an e-sword.

**Pull request closed without merging**
