### PR TITLE
Click First Combat (Part 1 | The Batonq Knockdown Removal)

### PR DESCRIPTION
**Pull request by StrangeWeirdKitten**
## About The Pull Request

- Security batons knockdown time removed. This also effects cattleprod, teleprod, and telecrystal prod (security baton is the parent)
- Contractor baton knockdown removed
- Baton boomorange unchanged. (This is subject to change, but this requires a research)
- Reduces the price of the contractor baton to 4 TC from 7 TC

## Why It's Good For The Game

We had a large staff meeting last night and we had a conversation with how to handle antag versus security interactions and how sometimes people do not respect the roleplay of the other side. We've discussed how both antagonists and security sometimes have massive advantages to whoever could click first. I think there needs to be a distinction between batons that either have knockdown (telescopic) as a primary purpose, **or** have stamina damage to wear you down.

**Stamina damage remains unchanged.** The security baton will still floor you after 3 hits and the contractor baton after 2.

This is a balance change that will gradually look into **any and all** combat items. I will be looking at both security gear and antag gear. There's a lot on the latter end, so *please point me to anything you feel like should also be looked at*

I will tackle the abductor baton in a seperate PR since that's a whole 'nother beast

## Proof Of Testing

I tested it.

## Changelog

:cl:
balance: Knockdown removed from the following batons: Contractor, Security, Teleprod, Telecrystalprod, and Cattleprod
balance: Contractor baton reduced to 4 TC from 7 TC
/:cl:

### CODE REVIEW

**Comment by BurgerLUA** [comment]
I tried doing this 1 year ago (or at least, something similiar) in #288 

It was generally regarded as a bad PR but this is when we had github mains so it might go over well this time.

**Comment by Redrover1760** [comment]
Removing the added knockdown is different than totally reworking stamcrit 

Eh, I've always wanted the knockdown gone from normal batons. It makes winning fights so easy and allows combos like baton knockdown > paralyze > free baton hit

**Comment by StrangeWeirdKitten** [comment]
> I tried doing this 1 year ago (or at least, something similiar) in #288
> 
> It was generally regarded as a bad PR but this is when we had github mains so it might go over well this time.

I'll take a look through. But genuially I don't really want to touch stamina. The biggest issue I have with it is how a single baton hit practically places someone in a major disadvantage because all you need to do is time it correctly by going

Baton > Back Up > Wait for Knockdown > Baton > Backup

**Comment by HissyNays** [comment]
This mainly seems like a major nerf to security first and foremost.
I don't see the reason for it. You just take away something and give nothing in return.
Such change will turn stun batons pretty much useless against anyone that is armed. 
The massive advantage on who clicks first however is still there, especially on antagonist side.

**Comment by SonicGotNuked** [comment]
> This mainly seems like a major nerf to security first and foremost. I don't see the reason for it. You just take away something and give nothing in return. Such change will turn stun batons pretty much useless against anyone that is armed. The massive advantage on who clicks first however is still there, especially on antagonist side.

Start listing items dude

**Comment by Redrover1760** [comment]
Batons will be strong no matter what. They're 60 damage statsticks and also inflict confusion. Worse case scenario, you reduce the cooldown for followup baton hits if its that bad to compensate for the removed slowdown.

**Comment by HissyNays** [comment]
> Batons will be strong no matter what. They're 60 damage statsticks and also inflict confusion. Worse case scenario, you reduce the cooldown for followup baton hits if its that bad to compensate for the removed slowdown.

When was the last time you played? Batons don't inflict confusion, they also have terribly long cooldown after every hit.

**Comment by Moostard** [comment]
Im not sure this is needed nor it is a good idea, unless you plan to change how a LOT of things work in the game.

Disablers already outdamage batons due to the slow attack speed of batons(this is why people back up after a hit. Its to avoid being hit yourself while you cannot attack again). Plus they are much safer to use cause they are ranged and mindshield pins ensure that it wont be used against you while you can lose a baton.

Of course the person to click the other first has the advantage.
Melee combat should be risky and this indirectly buffs things like scarp, which is already incredibly powerful.

There are stims designed to help regen stamina and/or fight the knockdown effect itself and they are not hard to make at all. It is just laziness or players own choice to not buy stimulants instead of another murdertool for example.

You are punishing people for using weapons designed to stun while things like water, soap and pushes can knock you down.
Also there are things like heretic grasp, cult stun, brawl vamp ability or weapons like powerfist that instantly knock you down and most of them also give you lots of damage as a bonus.

5 stamina damage difference is nothing in comparison to normal sticks with instant knockdown and no battery usage.

Batons are affected by armor and require more hits if said armor is decent. Iirc its energy armor. Meaning that 3 hits only apply to unarmored and low energy armor targets.

In the end, nerfing nonlethal tools only encourages lethal approach for antags and security.

**Comment by HissyNays** [comment]
> > This mainly seems like a major nerf to security first and foremost. I don't see the reason for it. You just take away something and give nothing in return. Such change will turn stun batons pretty much useless against anyone that is armed. The massive advantage on who clicks first however is still there, especially on antagonist side.
> 
> Start listing items dude

BOLA. First and foremost all of bola types. You hit with it and you already set up your target for easy kill. And reinforced bola takes forever to take off and applies a hard stun.

Shove can be used to stun if against a wall.

357 kills incredibly fast and even faster after the buff.
Pepperspray, flash, powerfist, many heretic abilities, vampire abilities, rocket gloves, meathook, xenobiology time stop, ninja's net, changeling's cryo sting, nightmare's armblade, sleepy pen, energy crossbow.

All of these can be used for sudden attack to easily win a fight, and many of these are knockdown if not straight up stun.

You're forcing balance hell on your self. Rather than heavily nerfing, you could adjust the baton so it's not one hit stun but still remains as viable as before. Or just don't touch it, it works too.

And even if you manage to fix all of the above with idea to make surprise attacks more difficult, people WILL find a way to surprise attack effectively anyways.

**Comment by HissyNays** [comment]
Biggest and most fun way to deal with it would be just coding in ability to force your self to get up via right click at cost of some stamina like on some other servers.
However this drasticly lifts the skill ceiling of combat which often ends up upsetting people who don't like to get invested in combat and learning it.

**Comment by NargaInDisguise** [comment]
> Biggest and most fun way to deal with it would be just coding in ability to force your self to get up via right click at cost of some stamina like on some other servers. However this drasticly lifts the skill ceiling of combat which often ends up upsetting people who don't like to get invested in combat and learning it.

I like the idea of a force-standup ability that costs stamina.

**Comment by StrangeWeirdKitten** [comment]
I appreciate the well thought out responses

Right now the PR is primarily in testing for a couple days because you can't poke and prod good balance without first letting it having its chance on the live server and seeing what comes out of it. I can smack dudes all day with batons on local, but that doesn't tell me if it's a good idea or a bad idea. **What does help** is that TG removed stamina damage and knockdown from fists. 

> Batons will be strong no matter what. They're 60 damage statsticks and also inflict confusion. Worse case scenario, you reduce the cooldown for followup baton hits if its that bad to compensate for the removed slowdown.

I will consider the possibility of lowering it to 2 seconds, from 2.5 seconds if this is required before reinstating the knockdown. But as always, batons work best in duos and security isn't a one person army. I'm not just thinking about the antag facing a 1 on 1. If I want people to roleplay with security, then I need it to be less suicidal to your antag round to do so. But I am not making the mistake of keeping it just to the one side again. I have more items in mind that we might need to touch up seperately. I'm not going to ever perfectly solve this, but that's not a justification to keep things as they are.

> Disablers already outdamage batons due to the slow attack speed of batons(this is why people back up after a hit. Its to avoid being hit yourself while you cannot attack again). Plus they are much safer to use cause they are ranged and mindshield pins ensure that it wont be used against you while you can lose a baton.

Disablers are good at stamina, but not mobility restriction. Stamina damage already slows you down majorly. But yes, it's brutal when combined with the knockdown effect. But saying that this change is unneeded while providing an even more powerful example then what I already said doesn't really justify it either. Two wrongs don't make a good. 

> Melee combat should be risky and this indirectly buffs things like scarp, which is already incredibly powerful.

I assure you. I will be looking at SCARP. It was buffed recently ish. 

> You are punishing people for using weapons designed to stun while things like water, soap and pushes can knock you down.
Also there are things like heretic grasp, cult stun, brawl vamp ability or weapons like powerfist that instantly knock you down and most of them also give you lots of damage as a bonus.

I don't find the entire concept of knockdown a bad thing. I said knockdown should not be paired with major stamina loss.

General antag abilities in the meantime will be another thing I look at. Trust me, this isn't the only PR I'll open.

> 5 stamina damage difference is nothing in comparison to normal sticks with instant knockdown and no battery usage.

It also is a 4 second cooldown. This makes a major diffrence alone.

>There are stims designed to help regen stamina and/or fight the knockdown effect itself and they are not hard to make at all. It is just laziness or players own choice to not buy stimulants instead of another murdertool for example.

Why would I want people to do this when most people in security are scared to do this on the vague idea admins will bwoink them, which has unfortinately happened. I'm not balancing this game around chemicals and I'm not telling the admins that everyone should use combat chems, and these will also be addressed in the future. This is an entirely diffrent beast to tackle and I have a few vague ideas. The traitor stim pen costs 5 TC for a reason.

>Batons are affected by armor and require more hits if said armor is decent. Iirc its energy armor. Meaning that 3 hits only apply to unarmored and low energy armor targets.
>
>In the end, nerfing nonlethal tools only encourages lethal approach for antags and security.

People who wear heavy armor are typically going to have some sort of weapon behind it. I don't see entirely what this 
Security doesn't typically lethal an unarmed, unarmored, and not teleporting antag because admins already do a pretty good job stopping that. We're not TG. TG has some good stuff, and some weird stuff in regards to balance. If the server was LRP, I'd agree. But we're not. 

>You're forcing balance hell on your self. Rather than heavily nerfing, you could adjust the baton so it's not one hit knockdown but still remains as viable as before. Or just don't touch it, it works too.

It's already very viable. It's a three hit knockdown now. That's all I'll say regarding this.

>Biggest and most fun way to deal with it would be just coding in ability to force your self to get up via right click at cost of some stamina like on some other servers.
>However this drasticly lifts the skill ceiling of combat which often ends up upsetting people who don't like to get invested in combat and learning it.

I appreciate the idea, but I'm not going to agree with it. My primary goal is to still have a solid combat, but to not make the first hit the indecisive one. People enjoy chaos. People enjoy things happening to them. What they don't enjoy is a sense of things ending the moment it sometimes starts or chasing someone in a circle for over 30 minutes.

This is nowhere close to being merged currently unless it proves itself.

**Comment by ReturnToZender** [comment]
Good luck, Sonic! Make us proud

**Comment by destrucktoid** [comment]
This game and many others will always be whoever clicks first wins, this change and as many changes as you like will not change that. What you are doing by removing stun baton knockdown doesn't help the situation overall, just addresses one of the most commonly used tools in sec's arsenal and encouraging them even more to go use ballistics and kill everything that moves. Stun batons are good for the game _because_ they are so strong and they encourage you to get into melee range which is where most antagonists also want you to be. If this nerf goes through then i can easily foresee sec completely forgoing the stun baton in favour of other tools that play around ranged options such as mass disabler and ballistics instead, which would be even more disastrous IMO. 

The reason for this is because one of the biggest reasons the baton is so strong isn't it's 60 stam damage. It's the knockdown, knockdown in this game is incredible, it forces you to drop whatever you have in your hand, it slows you down dramatically, opens you up for a shove stun, harder to resist out of grabs along with various other reasons why it's so strong. Genuinely if this change goes through then whenever i'd be HoS i would instead swap my stun baton for a telebaton from one of the heads of staff because that would genuinely be more useful to me than a stun baton that doesn't do knockdown.

**Comment by Redrover1760** [comment]
> > Batons will be strong no matter what. They're 60 damage statsticks and also inflict confusion. Worse case scenario, you reduce the cooldown for followup baton hits if its that bad to compensate for the removed slowdown.
> 
> When was the last time you played? Batons don't inflict confusion, they also have terribly long cooldown after every hit.

Confusion

Confusion is a status effect that gives an RNG chance to randomize your movement. Its been on stunbatons for ages on tg, and it still is on it here.

**Comment by Redrover1760** [comment]
> 5 stamina damage difference is nothing in comparison to normal sticks with instant knockdown and no battery usage.
> 
> Batons are affected by armor and require more hits if said armor is decent. Iirc its energy armor. Meaning that 3 hits only apply to unarmored and low energy armor targets.
> 
> In the end, nerfing nonlethal tools only encourages lethal approach for antags and security.

Batons bypass all armor. No armor in the game will stop you from taking full stamina damage from a baton. Energy armor only effects disablers/tasers/ebows.

**Comment by StrangeWeirdKitten** [comment]
> Yep, Stun batons have a much faster cooldown. Also, the knockdown time of a stun baton is a full 5 seconds in the before this PR. Brutal.

It was delayed. You'd only be knockdown for a fraction of a time AFTER five seconds. There's an override in the proc coded in to add this. But you could just learn the timing and time it right.

> Only concern is that it gives telescopic batons a huge edge over batons in one on one fights. One guy with a police baton is likely beating a stun baton use

Perhaps. But admittidely I don't want to remove the knockdowns from telebatons. They don't do nearly as much stamina damage to warrent that and you have plenty of options to retalliate against it.

**Comment by HissyNays** [comment]
> > Yep, Stun batons have a much faster cooldown. Also, the knockdown time of a stun baton is a full 5 seconds in the before this PR. Brutal.
> 
> It was delayed. You'd only be knockdown for a fraction of a time AFTER five seconds. There's an override in the proc coded in to add this. But you could just learn the timing and time it right.
> 
> > Only concern is that it gives telescopic batons a huge edge over batons in one on one fights. One guy with a police baton is likely beating a stun baton use
> 
> Perhaps. But admittidely I don't want to remove the knockdowns from telebatons. They don't do nearly as much stamina damage to warrent that and you have plenty of options to retalliate against it.

You want to nerf "who hits first wins" but letting telebaton stay king? It's not stamina damage that wins for telebatons, it's knockdown and disarm. 
Telebaton hit => shove => spam disabler at the guy => you win. 
The part where you telebatonned the guy already wins the entire fight, not because it does stamina damage but because it disarms and knocks down. You can remove stamina damage entirely from telescopic baton and it will still remain king.
I can see all smart traitors buying telescopic baton if this pr goes through, it will be hell for security.

**Comment by Redrover1760** [comment]
There is a million things that'd have to be reworked for this kind of thing to do well even if I think that stun knockdown combat is just kinda boring in general. I like the concept but many antags have just as nasty stuff that were designed to be deadly melee tools on par with knockdown stun batons and telescopic batons.

**Comment by Moostard** [comment]
> > 5 stamina damage difference is nothing in comparison to normal sticks with instant knockdown and no battery usage.
> > Batons are affected by armor and require more hits if said armor is decent. Iirc its energy armor. Meaning that 3 hits only apply to unarmored and low energy armor targets.
> > In the end, nerfing nonlethal tools only encourages lethal approach for antags and security.
> 
> Batons bypass all armor. No armor in the game will stop you from taking full stamina damage from a baton (Maybe except some forms of reactive anomaly armor). Energy armor only effects disablers/tasers/ebows. Tg made it this way to decrease the importance of armor in terms of combat. Even the most heavily armored nuke op takes 60 stamina damage on stun baton hit. (Really, it shows that you don't have experience with baton based combat, no offense. Sec armor has energy 4, which would reduce 60 stamina damage stunbaton hit to a pathetic 36, requiring 4 hits to even stamcrit someone. Ablative armor has Energy 6, making that 24 stamina damage, which would mean 6 stun baton hits to stamcrit...)

I remember there was a PR before that made baton respect armor. Seems it is no longer the case or something. I might have mixed up servers.

**Comment by Ashrollen** [comment]
> I tried doing this 1 year ago (or at least, something similiar) in #288
> 
> It was generally regarded as a bad PR but this is when we had github mains so it might go over well this time.

It will go same way. I already shifted to detective baton. Expect to see more people stockpiling them. Entire PR looks like soon we will just shoot each other. It was like this during hf blade security and ended poorly. Now i can assure you, people will drastically fast stop using those.

**Comment by projectkepler-ru** [comment]
To those unaware, Yes, Stamina Damage from disabler is affected by armour

stamina damage from stun baton is not.

**Comment by AllCorruptingWyrm** [comment]
Honestly,  I just had a contractor round and I realized how useless the baton is but that comes from the fact that everything is so powercrept. With that said, all a baton nerf is gonna do is encourage lethalsec and with the amount of uncontainable antags, yeah its bad.

**Comment by StrangeWeirdKitten** [comment]
Yes, I find the issue of baton + hitting against a wall an issue. It seems like upstream has a reasonable issue with it too. https://github.com/tgstation/tgstation/pull/82231

Security already lethals antags anyway when the antag has a gun or is also incredibly lethal in general. If you're a spooky scary vampire, a lunatic heretic with your blade, or a ninja with a sword. I don't necisiarrily see the issue with you getting shot. 2 dudes running in with a baton will already reasonably knock even the most armored nuclear operative on their ass in a few seconds.

**Comment by StrangeWeirdKitten** [comment]
Feedback that was collected and the following adjustments will be made
- Cooldown reduced to 2 seconds, from 2.5 seconds.
- Contractor baton cooldown reduced from 2.5 seconds to 1.5 seconds. (I understand that it needs to be a little bit more of a quicker item)
- I will be introducing a test of an upstream PR.

**Comment by destrucktoid** [comment]
> Security already lethals antags anyway when the antag has a gun or is also incredibly lethal in general. If you're a spooky scary vampire, a lunatic heretic with your blade, or a ninja with a sword. I don't necisiarrily see the issue with you getting shot. 2 dudes running in with a baton will already reasonably knock even the most armored nuclear operative on their ass in a few seconds.

And so your solution to security lethaling most antags, is to give them more reasons to lethal every antag by making the stun baton useless? How does this make combat in any way better for either side? This change just encourages security to use lethals in every circumstance rather than in most circumstances. We already have Burger giving every sec officer a handgun, we don't need to give them even more reasons to use it.

**Comment by KeRSedChaplain** [comment]
This will definitely not make sec use lethals more frequently than they already do. What I myself forsee happening is that sec won't use batons to combo into just decapping/gunning down someone as much, which is what my personal issue with the baton knockdown is.

**Comment by StrangeWeirdKitten** [comment]
Security already lethals antags anyway. I'm not going to pretend the armor piercing 60 stamina damage is not an extremely viable melee weapon. Yes, I've used it. Yes, I've been able to manage fine and I don't necessarily see an issue with people using Disablers a little more. I'm not necessarily going to test merge it or close this PR. Because to be quite frank, there's probably going to be upstream changes and this whole thing would be somewhat redundant. So overall I'm waiting a little more on what is decided.

**Comment by StrangeWeirdKitten** [comment]
The baton wall shove combo PR kind of overshadows a little more of the issues for me anyway, and whether or not TG decides to merge it, I'm going to adopt it and work it into our balance

**Pull request closed without merging**
