### PR TITLE
[modular] adds back contractor and ninja microbomb implants

### PR DESCRIPTION
**Pull request by DeerJesus**
## About The Pull Request

why the fuck would we ever remove contractor and ninja microbombs dont we like want their gear to NOT BE recoverable

## Why It's Good For The Game
this is a balance change we did not approve. and it is a very bad change. even upstream hates it but it was 'by host demand'. we are not that host. people should blow up on death if they want to. ninja clan has to as well

## Changelog

:cl:
add: adds back contractor and ninja microbombs to undo the damage the awful upstream has done
/:cl:

### CODE REVIEW

**Comment by Serxule** [comment]
yeah really not to mention that spiderclan are meant to kill themselves if captured (or detonate to leave their tech unobtainable)

**Comment by nevimer** [comment]
I'd rather just soulbind the items. And make the bomb optional, as in, you have to intentionally press it.

**Comment by DeerJesus** [comment]
> I'd rather just soulbind the items. And make the bomb optional, as in, you have to intentionally press it.

a lot harder said than done. also the bomb CAN be made optional by injecting urself with atropine (which u get in ur kit) (it waits to explode until you press it, working even after death). 

 this would require 1. adding a new item thats a different microbomb
2. having to convey to new players that this microbomb is 100 percent DIFFERENT from the old microbombs

not really worth it IMO just to get around a god-awful host-forced PR

**Comment by Majkl-J** [comment]
> > I'd rather just soulbind the items. And make the bomb optional, as in, you have to intentionally press it.
> 
> a lot harder said than done. also the bomb CAN be made optional by injecting urself with atropine (which u get in ur kit) (it waits to explode until you press it, working even after death).
> 
> this would require 1. adding a new item thats a different microbomb 2. having to convey to new players that this microbomb is 100 percent DIFFERENT from the old microbombs
> 
> not really worth it IMO just to get around a god-awful OTHER-host-forced PR

Don't need to add a whole new microbomb just make one with a on_death override

**Review by BurgerLUA — APPROVED** [review]
Code looks fine.

**Comment by StrangeWeirdKitten** [comment]
This will need to be discussed with #648 and #625 on how we should handle contractors and ninja modsuits when they're captured

**Comment by StrangeWeirdKitten** [comment]
The pressing lootbox concerns are already handled. I've been discussing this with Ozzo and unfortunately, there are other plans. I'm going to close this because it's not going to get merged.

**Pull request closed without merging**
