### PR TITLE
Replaces the Meteor Shuttle with THE CUBE

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Replaces the Meteor Shuttle with THE CUBE. It's an emag only emergency shuttle that is literally just a 16x16 cube with some engines on it.

## Why It's Good For The Game

Asteroid Shuttle had a lot of issues with it actually being spawned/launche correctly so I'm removing it and replacing it with this. It is less destructive, but still very annoying and worthy of being an emag shuttle.

## Proof Of Testing

image

## Changelog

:cl: BurgerBB
del: Replaces the Meteor Shuttle with THE CUBE. It's an emag only emergency shuttle that is literally just a 16x16 cube with some engines on it.
/:cl:

### CODE REVIEW

**Comment by projectkepler-ru** [comment]
I thought this was  reference to the movie the cube, do you wanna add more to this? could be fun @BurgerLUA

**Comment by BurgerLUA** [comment]
Not sure what else I could add to it

**Comment by Majkl-J** [comment]
> Not sure what else I could add to it

Add a posibrain in the middle, since it is a "Cube"

**Comment by IgiariValkyr** [comment]
https://www.youtube.com/watch?v=C7EocA1hsCU

**Comment by lilBlovy** [comment]
It seems to mesh to much into eachother, if you were to add a variety of fresh walls and rusted walls it would look alot better/alot worse. Depending on how  you see it.

**Comment by projectkepler-ru** [comment]
I was just thinking about the cube film, if you watched it, basically it has traps in some room, and some room are safe  and the goal was to reach the exit cube

**Comment by BurgerLUA** [comment]
The cube is just a inside joke where me and some other crewmember found a blackbox in maint and we both refered to it as "THE CUBE" and worshipped it. It's unrelated to the film of the same name.

I think it being without traps is fine because during testing, it was SUPER irritating trying to get in with tools, moreso than the asteroid shuttle. I don't want to fuckover crew too much, even if it's an emag shuttle.

**Pull request merged**
