### PR TITLE
Hemophage can drink velvet kiss!

### PR DESCRIPTION
**Pull request by plsleavemealon**
## About The Pull Request
This lets hemophages drink velvet kiss and allows it to restore blood levels at the same strength as Bloody Mary (weaker than bloodshot.)

## Why It's Good For The Game
The drink is made with blood, is designed for vampires and the undead, and it gives hemophages an alternative to bloody mary and bloodshot for drinks to enjoy.

## Proof Of Testing
Works flawlessly on my private server.

## Changelog

:cl:
fix: Hemophages can now drink Velvet Kiss without vomiting
balance: Velvet Kiss is now a race drink for Hemophages (in addition to the other races that were already present!)
balance: Velvet Kiss now restores blood at the same rate that Bloody Mary does
/:cl:

### CODE REVIEW

**Review by projectkepler-ru — COMMENTED** [review]
You can do this upstream and I'd speedmerge it tbh

**Comment by plsleavemealon** [comment]
On skyrat? Sure, let me see if I can find the uh, link for the github and I'll set it up

**Comment by plsleavemealon** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/28880

**Comment by plsleavemealon** [comment]
Created PR upstream, should be handled there instead :3

**Pull request closed without merging**
