### PR TITLE
Removes all the extra crushers

### PR DESCRIPTION
**Pull request by Maia-J**
## About The Pull Request

The code is unmaintained, broken for at least 2 months now, the person responsible for adding it has left ages ago. It's basically added extra dead weight.

This won't get merged in the next 7 days in case somebody wants to pick up the pieces.

## Why It's Good For The Game

Whilst "Improve don't remove" is a good argument, leaving around code nobody's been maintaining or is willing to maintain is how one gets a broken laggy repo where half the stuff doesn't work like splurt or Nova. Maintainers can't be expected to maintain every single line) since we also have to deal with 2 upstream repos, reviewing everything, and the upstreaming itself.  

## Proof Of Testing

Revert, not much to talk about

## Changelog

:cl:
del: Removed broken unmaintained crusher code
/:cl:

### CODE REVIEW

**Comment by StrangeWeirdKitten** [comment]
Basically 2-3 weeks for this PR to sit around until the merge. The crushers are litterally broken.

**Comment by theselfish** [comment]
Maybe refactor the crusher sprites into alt click reskins?

**Comment by aKromatopzia** [comment]
what's broken about it anyways?

**Comment by Majkl-J** [comment]
> what's broken about it anyways?

Some of the special effects dont work, the ones that are meant to be single handed aren't, and nobody's bothered to fix it for a few months now

**Comment by projectkepler-ru** [comment]
soon:tm:

**Comment by Hotmud9** [comment]
What if we stole the code from monkestation who actually got it working

**Pull request merged**
