### PR TITLE
Resets plant DNA manipulator to its tg state.

### PR DESCRIPTION
**Pull request by Swiftfeather**
## About The Pull Request

Removes plant dna manipulator.

## Why It's Good For The Game

The plant dna manipulator ruins any balancing attempts in the rest of botany. Keeping its functionality directly contradicts the idea of balancing botany. This is why tg removed it.

## Proof Of Testing

It compiled

## Changelog

:cl:
del: Removed plant DNA manipulator
/:cl:

### CODE REVIEW

**Review by StrangeWeirdKitten — APPROVED** [review]

**Comment by BurgerLUA** [comment]
I am usually the first person to resort to removing something if it's OP instead of seeking other solutions, but I genuinely think that this is a player issue.

Things to solve people abusing the DNA manipulator:

- Make it clear in Space Law that producing dangerous chemicals in botany is not allowed, even if it is in botany.
- Give security more tools to deal with botany abuse, such as weedkiller grenades.
- Get admins to bwoink people for using plants to validhunt, and encourage people to ahelp botany validhunting.
- Nerf specific insane traits, such as dank vesicles.


The DNA manipulator was removed from /tg/ because it was a much faster way to obtain the traits of things you want. With us having 2-3 hour rounds, there is literally no point in removing the DNA manipulator because you can gain the same OP plants with pollination, grafting, and genetic shearing. It will just take more time.

**Review by Majkl-J — CHANGES_REQUESTED** [review]
I'll reiterate what I said in maintainerchat, but wiping all the work put in to make it work is not what I believe is the approach.

Moving it behind rarer or harder to gain research (alien/illegal tech) and removing it from roundstart is a better idea. Plus keeping it in the code means we can adminbus it or custom disks in for gimmicks if people want and ahelp/opfor for it

**Comment by plsleavemealon** [comment]
I don't think this is necessary at all.

A) it is hardly abused, so when it is, bad actors can be dealt with on a case by case basis.

B) it enables for a lot of fun and engaging gameplay, which would be straight up removed if this gets pushed live

C) it makes botany much more fun to do, and lets players experiment more

What benefit truly is gained from removing this?  What gameplay is actually enhanced by its removal?

**Comment by IgiariValkyr** [comment]
Let me just slide this in here as a reason why it should be removed:

image

**Comment by plsleavemealon** [comment]
OK, so a single bad actor made an extreme deathmix, big deal.  It probably took them a long time to get all the plants for those traits too.

You can also use the DNA manipulator for many beneficial things, such as medicinal production, or improving the quality of veggies that are being used for food such as by splicing a higher vitamin production (such as from peas or sweet potatoes) into the plant.

**Comment by AllCorruptingWyrm** [comment]
What about Xenobiology though? there are far more pressing nerfs that should be done first.

**Comment by Razurath** [comment]
I mean if we're trying to balance anything that can be manipulated by bad actors with to much skill, we should just remove chemistry and virology. 

And I get it you're not saying to remove botany, but the tool you're trying to take away is used for good things far more often then it's used for bad. There are folks who can make some fearsome plants, but removing this will only slow them down some. I know who made the thing you shared, this won't stop those from happening. 

What it will do is make the lives of other botany players harder. Balances should not be issued out in the basis of "some people do bad" but rather should be done on the basis of whether or not it dramatically alters gameplay cycles. 

As much as I dislike that bows got nerfed, their original place was preserved by making them still powerful for ice and ash walkers which was their purpose. This isn't fixing a cycle of gameplay, it's just removing something outright to try and stop a "problem" that is barely that. We have rules in place preventing the abuse of chemistry and virology by antags and to an extent non antags, maybe it would be better to create rules both IC and OOC to cover botany as well

**Comment by ReturnToZender** [comment]
> I mean if we're trying to balance anything that can be manipulated by bad actors with to much skill, we should just remove chemistry and virology.
> 

Virology was removed

**Comment by plsleavemealon** [comment]
> > I mean if we're trying to balance anything that can be manipulated by bad actors with to much skill, we should just remove chemistry and virology.
> 
> Virology was removed

Its functionality still exists, even if TG has the wacky idea to remove it outright.

**Comment by Razurath** [comment]
> > I mean if we're trying to balance anything that can be manipulated by bad actors with to much skill, we should just remove chemistry and virology.
> 
> Virology was removed

Lol no it wasn't, the specific job was removed the labs are still there. Now every doctor gets access. I made a no resp virus yesterday to chill with the ice walkers

**Comment by Fluffy-kitt** [comment]
> Let me just slide this in here as a reason why it should be removed:
> 
> image

Hey uh; As the person who made this plant-

The DNA machine was never used to make it. that just sat in mutagen for half a hour.

**Comment by shellspeed1** [comment]
> > Let me just slide this in here as a reason why it should be removed:
> > image
> 
> Hey uh; As the person who made this plant-
> 
> The DNA machine was never used to make it. that just sat in mutagen for half a hour.

Can't you get that with just L4Z using an upgraded tray?

**Comment by Erol509** [comment]
> > > Let me just slide this in here as a reason why it should be removed:
> > > image
> > 
> > 
> > Hey uh; As the person who made this plant-
> > The DNA machine was never used to make it. that just sat in mutagen for half a hour.
> 
> Can't you get that with just L4Z using an upgraded tray?

mutagen is faster

**Comment by Majkl-J** [comment]
Yeah no the fix to the abuseable mechanics is better

**Pull request closed without merging**
