### PR TITLE
Revert "Loadout adjustments."

### PR DESCRIPTION
**Pull request by sippykot**
Reverts Bubberstation/Bubberstation#2398

Could we not merge nerfs that get almost purely negative feedback, that even the author was seemingly convinced out of pulling as per the discussion? I don't understand why it was merged... Sorry if it's rude but, i'm just confused.

Edit: people keep discussing the original PR, so when evaluating reverting it, make sure to check the discussion on #2398

### CODE REVIEW

**Comment by Arturlang** [comment]
@sippykot Mainly because of the powergaming issues of the loadout items it added, can you justify why you think this would be a good thing to have, this does really give you a lot of resources you don't normally get

**Comment by ChromeFoxxity** [comment]
> > @sippykot Mainly because of the powergaming issues of the loadout items it added, can you justify why you think this would be a good thing to have, this does really give you a lot of resources you don't normally get
> 
> ...does getting a really basic medkit or medipen set really negatively affect the balance? - you could use "powergaming" to argue for removal of many, many other things... At which points it's just a general loadout nerf... which was talked down, but the medical part of it specifically was merged because (???). If anything we should add the synth medkit to the loadout to compliment the current medkits, not remove them. It's just annoying and encourages people to steal the emergency medkits from lockers roundstart so that they are empty when the station is actually in an emergency.

Let's be fair here, even in an emergency, everyone ditches the emergency medkits (most of the time), and immediately go for Medbay. And they would most likely go for Medbay lobby's medkits, or maybe something in maintenance. Or just buy their own firstaid. Or steal from medbay.

**Comment by Arturlang** [comment]
And everyone having their medkits would heavily invalidate needing to buy new medkits from cargo, which medical can do themselves if they find the need to do so, and having 2 medkits roundstart is incredibly powerful, essentially meaning you're pretty much set for the round in terms of medicine for the average damage that you're likely to suffer. The 4 autoinjectors you get are very powerful and getting them roundstart is really really strong, not to mention the other medkit's suture kits and burn kits. And the intent of the loadout is to let you get mostly non-mechanical stuff, not something that is incredibly powerful, like a full set of tools or powerful medicine that you can't quite easily get otherwise without paying for it.

**Comment by sippykot** [comment]
> And everyone having their medkits would heavily invalidate needing to buy new medkits from cargo, which medical can do themselves if they find the need to do so, and having 2 medkits roundstart is incredibly powerful, essentially meaning you're pretty much set for the round in terms of medicine for the average damage that you're likely to suffer. The 4 autoinjectors you get are very powerful and getting them roundstart is really really strong, not to mention the other medkit's suture kits and burn kits. And the intent of the loadout is to let you get mostly non-mechanical stuff, not something that is incredibly powerful, like a full set of tools or powerful medicine that you can't quite easily get otherwise without paying for it.

yeah i dont think anyone would like that kind of nerf... it's literally just making people grind for stuff roundstart
which is exactly why the feedback to the PR was what it was

**Comment by NargaInDisguise** [comment]
Only bring back the basic medkit please. The deforest ones were definitely powercreep.

**Comment by Strazyplus** [comment]
It was a quality of life feature. Calling it a power gaming or forced interaction with cargo or medical as a good thing when everyone is busy at round start as a good thing, isn't. 

I really dislike when PRS that are clearly not popular, disliked,and heavily criticized get merged, clearly it needs to be looked into and considered before being merged.

**Comment by StrangeWeirdKitten** [comment]
listen, I ain't going to pretend the basic medkit is going to make and break things because people don't do some of the silly minmaxing you can do on TG as an assistant. (The frontier one is definitely going to be gone), but that PR was merged with pretty much the majority of the maintainer team chipping in and agreeing that the loadout overall should be primarily focused on menial items that are mostly for flavour. (I'm fine with an empty medkit you can stock). It's basically that these things should have a credit cost behind them, some form or another (maybe even 

Overall, no the PR is not going to get reverted. Spending a minute to download the cargo app on your PDA then running down to the department when cargo threw it on the floor in the lobby is not really that far out of your way. It just requires cargo to be working. 

These items should have a cost behind them, whether it be time or your round start money if someone wants to circle back and impliment the idea of a shop menu that pre-spends your starting cash (one of the maintainers might do this, but it ain't a promise)

**Comment by sippykot** [comment]
yeah, sorry, i hate it
hopefully ill be able to readd them or something similar in the future

**Comment by YakumoChen** [comment]
> ...does getting a really basic medkit or medipen set really negatively affect the balance? 

Yes

**Pull request closed without merging**
