### PR TITLE
New (to yall) lizard frills - Split

### PR DESCRIPTION
**Pull request by MajManatee**
## About The Pull Request

Icon by https://github.com/Mqiib

A port of https://github.com/yogstation13/Yogstation/pull/12383
Adds new frills, as seen below
316283473-287948cc-d023-4b4b-8b08-8db1d107281a

316283306-085d5d23-adc3-4481-ab4d-b3f5c1e74fa0

316283317-25723c93-7964-41c4-b226-07f5061260c5

316283323-8a1bbd35-419f-46db-aa81-3ee8bc078549

316283335-82fdea1e-ec9a-426e-b3f3-da56b8ee7563
## Why It's Good For The Game
More customization is good
## Proof Of Testing
<details>
<summary>Screenshots/Videos</summary>
See above
</details>

## Changelog
:cl:
image: New lizard frills, (Axolotyl based)
/:cl:

### CODE REVIEW

**Comment by projectkepler-ru** [comment]
You can have new stuff on bubber modular folder but we aren't merging skyrat stuff anymore so it should be fine

**Comment by Mqiib** [comment]
Please credit the original maker of the sprites (me)

**Comment by MajManatee** [comment]
third time porting it, i knew i forgot something

**Comment by projectkepler-ru** [comment]
> third time porting it, i knew i forgot something

happens

**Pull request merged**
