### PR TITLE
Removes the mask FOV

### PR DESCRIPTION
**Pull request by Majkl-J**
## About The Pull Request

Holy shit

## Why It's Good For The Game

Everyone hates it

## Proof Of Testing

I would actually resign if this was proven to not be tested (I did test it on the regular gas mask)

## Changelog

:cl:
del: The mask FOV is gone
/:cl:

### CODE REVIEW

**Comment by StrangeWeirdKitten** [comment]
(I hate it too)

**Comment by ReturnToZender** [comment]
SO BASED

**Comment by NargaInDisguise** [comment]
MY FUCKING HERO

**Comment by pixelkitty286** [comment]
BASED

**Pull request merged**
