### PR TITLE
Upstream 7 31 2024

### PR DESCRIPTION
**Pull request by ReturnToZender**
## About The Pull Request
upstream merge

## Why It's Good For The Game
new shit

## Proof Of Testing
it doesn't compile, yet, but it's mostly stuff in our code

### CODE REVIEW

**Comment by ReturnToZender** [comment]
Don't read the branch name

**Comment by lessthnthree** [comment]
image

**Comment by nevimer** [comment]
TEST YOUR PULL REQUESTS

**Comment by StrangeWeirdKitten** [comment]
This broke... everything

**Comment by Majkl-J** [comment]
I think this is an important lesson for myself

**Pull request merged**
