### PR TITLE
Start of a goon chat PR kinda

### PR DESCRIPTION
**Pull request by ReturnToZender**
## About The Pull Request
This PR looks to use https://github.com/Monkestation/Monkestation2.0/pull/294 as a base to create preferenced vocal barks.

I feel like the code could be improved, though, so I'm waiting for review.

## Why It's Good For The Game
Silly little voice sounds 

## Proof Of Testing
This doesn't currently compile, I'm posting this for review purposes

## Changelog

:cl: ReturnToZender, dwasint (Monkestation)
add: Goon vocal barks (the beginnings of a vocal bark system)
/:cl:

### CODE REVIEW

**Comment by nevimer** [comment]
no reintroducing goon folders and assets. they are oooold and removed from tg a long while ago.

**Comment by Erol509** [comment]
Bear in mind that we probably cant take sounds from goonstation, and I that they are probably using them.

**Comment by ReturnToZender** [comment]
> Bear in mind that we probably cant take sounds from goonstation, and I that they are probably using them.

We can, as long as it's properly attributed to them-- at least, according to Kapu, who knows better than me.

**Comment by thegrb93** [comment]
Spurt's system is better than goon's imo.

**Comment by Erol509** [comment]
So, liners and CI is fucking up on every map, thats bad.

**Comment by ReturnToZender** [comment]
Closed due to the new fluffy frontier vocal barks doing this for me

**Pull request closed without merging**
