### PR TITLE
Removes CENTCOM channel from NTRep, Blueshield

### PR DESCRIPTION
**Pull request by ReturnToZender**
## About The Pull Request
Comments out CENTCOM access from the NTRep and Blueshield headsets. They serve little purpose, the CENTCOM frequency cannot go down (although it's minimally useful because only these two roles get the channel) and it's pretty weird for the Blueshield to hear Deathsquad chatter.

## Changelog

:cl:
del: headset_cent NTRep
del: headset_cent Blueshield
/:cl:

### CODE REVIEW

**Comment by Draggeru** [comment]
I feel like it may be a good idea to give them an alternative radio channel that can go down, having the rep and blueshield be able to communicate any CC orders outside of command or security channels is a roleplay benefit. Especially if the captain or hos needs to be demoted or private orders need to be given

**Comment by Higgin** [comment]
It might honestly be better to give Deathsquads one of their own if that's the primary pain-point. When inspectors or ERTs show up, they have the centcom channel, and they're often there because of something the NTR did - it makes sense for them to be able to talk directly.

**Comment by ReturnToZender** [comment]
> It might honestly be better to give Deathsquads one of their own if that's the primary pain-point. When inspectors or ERTs show up, they have the centcom channel, and they're often there because of something the NTR did - it makes sense for them to be able to talk directly.

Such as through the Command channel or PDAs, both of which are afforded to ERTs and command officers, respectively?

**Review by BurgerLUA — CHANGES_REQUESTED** [review]
You should just remove the lines outright instead of commenting out the changes.

**Review by BurgerLUA — APPROVED** [review]
Nevermind, forgot this is a modular coderbase xd

**Comment by projectkepler-ru** [comment]
This seems unnecessary

**Pull request closed without merging**
