### PR TITLE
[Fixes Modularity] Removes ballistic weapons from command, gives proper eguns except it's not stale

### PR DESCRIPTION
**Pull request by zeroisthebiggay**
## About The Pull Request

yes this is literally just a pr made because Zender isn't updating his PR and it's gone stale/it's at the back of the github/noone is paying attention to it
this is probably going to get closed and i fully expect it to get closed as soon as Zender returns from their brainfog and presses the sync branch button but until then i'd like for this PR to exist as a temporary measure for discussion about the change and or for potential testmerges

## Why It's Good For The Game

Zender's PR was made before the `Why It's Good For The Game` question was in the default PR format so here's just my opinion.

heads of staff shouldn't be given guns that rival armory weapons in gross firepower when they're supposed to be vulnerable targets for antag objectives. stealing the nuclear authentication disk is much harder when the captain pulls out his ruptured cavity cannon and promptly rearranges your blood vessels. not to mention the fact that https://github.com/Bubberstation/Bubberstation/pull/403 exists as a hallmark to tell you how poorly designed and thought out these guns actually fucking are in terms of balance.

roundstart crew ballistics are cringe. the wounds system clearly was not designed around crew being so easily able to inflict bone breaks and pierce wounds.

## Changelog

:cl: ReturnToZender
Del: QM's sports rifle
Del: Captain's Osprey
Del: NT Rep's pistol
Del: Security Medic's pistol
Add: Captain e_gun
Add: NT Rep e_gun
Add: Security Medic disabler
/:cl:

### CODE REVIEW

**Comment by TetrakoHateThis** [comment]
I have never once witnessed an antag have difficulty overcoming the Archangel/Osprey/M5A. Hell, I rarely see them get used in effective combat, and all this PR does is homogenize things for the worse in an RP server, unless you plan to give them unique energy guns.

**Comment by zeroisthebiggay** [comment]
> I have never once witnessed an antag have difficulty overcoming the Archangel/Osprey/M5A. Hell, I rarely see them get used in effective combat, and all this PR does is homogenize things for the worse in an RP server, unless you plan to give them unique energy guns.

or you could just suffice with not having a massive woundbonus handcannon for your powertrip 'roleplay'

**Comment by kiwedespars** [comment]
>I have never once witnessed an antag have difficulty overcoming the Archangel/Osprey/M5A.

i've seen antags get domed absolutely by command having extremely powerful guns for no reason other than power fantasy

archangel
60 damage
-45 woundbonus
10 armor pen

osprey
40 damage (base)
37 damage - 40 armor pen (ap)
60 damage (revolver tier) (hp)

m45a
30 damage
30 woundbonus

archangel 60 damage, one shot slows you down or outright disables a limb of your choice (leg lol!)
osprey, very solid all around, high potential damage and also losing almost nothing from going armor pen
m45a uses the fuckoff hos revolver rounds except without a clunky reload. 60 wound-damage = bleeding wounds = Weeping Avulsion

**Comment by lurzefromgermany** [comment]
alistar 2 carbine kinda poo poo

**Comment by nevimer** [comment]
The merge conflicts, batman (rebase)

**Pull request closed without merging**
