### PR TITLE
Makes default Akula outfits not include the fishbowl

### PR DESCRIPTION
**Pull request by ReturnToZender**
## About The Pull Request
I hate this fucking fish bowl

## Why It's Good For The Game
My species can breathe air just fine

## Proof Of Testing
It compiles

<details>
<summary>Screenshots/Videos</summary>

</details>

## Changelog

:cl: ReturnToZender
del: Akula are no longer forced to wear the fish bowl
/:cl:

### CODE REVIEW

**Comment by Majkl-J** [comment]
You can just throw it away or not wear it. My akula does wear it for example. It's a silly part of their species

**Comment by sippykot** [comment]
just take it off... this only makes it harder to have the fishbowl if you want it

**Comment by RimiNosha** [comment]
Just add it to the loadout, then whoever wants it can have it.

**Comment by ReturnToZender** [comment]
> Just add it to the loadout, then whoever wants it can have it.

It is in the loadout!

**Comment by RimiNosha** [comment]
Then I don't see any issues with removing it from default.

**Comment by sippykot** [comment]
> Then I don't see any issues with removing it from default.

what about spawned in characters
like... i really, really don't see the point of this pr
it has... no benefit (just take the hat off) and might cause issues down the line for other people

**Comment by Majkl-J** [comment]
Just take the fishbowl off

**Pull request closed without merging**
