### PR TITLE
shakey shakey my tail is snakey

### PR DESCRIPTION
**Pull request by Moribun**
also know as moribund gives you sum tail

## About The Pull Request

adds nightstalker tail sprite and stuff to make it work

## How This Contributes To The Skyrat Roleplay Experience

modularized it. did the shit.... its all there no need to count it

## Proof of Testing
 it was tested. it works

## Changelog

I added a sprite...its modular...its coded it wont conflict even if you guys decide to keep pulling from the upstream
:cl:
shit was added
/:cl:

### CODE REVIEW

**Comment by Cyprex** [comment]
Looks good to me! Will merge in 24h!

**Review by KathrinBailey — CHANGES_REQUESTED** [review]
Follow correct modularisation. All files should be in the same place you'd find them outside of modular_zubbers.
Basically, if someone is in Bubberstation/code/game/blahblah
Your file should be in modular_zubbers/code/game/blahlah
Your .dm file must be located in `modular_zubbers/code/modules/mob/dead/new_player/sprite_accessories/dm`.
Your icon file must be located in `modular_zubbers/icons/mob/species/mutant_bodyparts.dmi`.

Do not copy how Skyrat does modularisation.

**Comment by Moribun** [comment]
you could of fixed that pathing in 2 fucking seconds. told butters this fucking modularization was gonna be issue causing

**Comment by Cyprex** [comment]
> you could of fixed that pathing in 2 fucking seconds. told butters this fucking modularization was gonna be issue causing
And so could you? I'm not sure what you're trying to get at with talking to Butters like this!

**Pull request closed without merging**
