### PR TITLE
Fixes a deadly catwalk on lavaland

### PR DESCRIPTION
**Pull request by CenkTheRaptor**
## About The Pull Request
Fixes this really fucked up catwalk in the lavaland base I'm PRETTY SURE is just there to fuck with people. Literally if you have even a tiny amount of lag you're almost guaranteed to waltz directly into the lava. I have seen at least me and maybe one other person fall for frankly, a random trap. 

I have not tested my changes but I don't believe a map change necessitates testing.

## Why It's Good For The Game
Less people will die (or more likely be removed from the round) while trying to explore the maintenance at the lavaland base.

## Proof Of Testing
<a href="https://gyazo.com/cc2a12f4770015d0551de57455177d83">Image from Gyazo</a>

<a href="https://gyazo.com/1e0683867232c00ee8cff753b91883fd">Image from Gyazo</a>

## Changelog

:cl:
fix: A catwalk bridging between the Lavaland Base's maintenance tunnels is no longer as treacherous as before.
/:cl:

### CODE REVIEW

**Comment by CenkTheRaptor** [comment]
ah fuck i forgot to delete those extra pipes i think woops

**Review by Majkl-J — COMMENTED** [review]
Unless you make this an automapper thing or bring it upstream this will be gone next upstream pull

**Comment by CenkTheRaptor** [comment]
uhhh. how do i make it an automapper thing?

**Comment by YakumoChen** [comment]
Take it upstream

**Comment by YakumoChen** [comment]
image
and remove the pipes here

**Comment by Majkl-J** [comment]
Take upstream

**Pull request closed without merging**
