### PR TITLE
Reverts the custom map rotation code because it seems to keep causing more problems than it solves

### PR DESCRIPTION
**Pull request by Maia-J**
## About The Pull Request

See name

## Why It's Good For The Game

Fixes empty votes being created, autorotation just picking a map because there's nothing else for it to pick, etc, etc

## Proof Of Testing

Werks fine on local

## Changelog

:cl:
del: Reverted map voting back to the tg system
/:cl:

### CODE REVIEW

**Comment by BurgerLUA** [comment]
Not being able to vote should've been fixed with https://github.com/Bubberstation/Bubberstation/pull/1916

**Comment by Majkl-J** [comment]
> Not being able to vote should've been fixed with #1916

From today
image

**Comment by projectkepler-ru** [comment]
It didn't JUST fail
it repeatedly tried to do a vote but because there was no map it just kept doing a re-vote

**Comment by BurgerLUA** [comment]
pain, this is the first time I'm hearing about this

**Comment by BurgerLUA** [comment]
I do not think an outright removal is the solution here. The map rotation tweaks were added for a reason. This prevents rounds from being meta/delta/icebox constantly and I have a feeling that behavior will continue if my changes are reverted.

Just fix the issue with lowpop and it will be fine.

**Comment by BurgerLUA** [comment]
See #2054

**Comment by Swiftfeather** [comment]
We'll see if burger's logic repair in #2054 works uwu

**Pull request closed without merging**
