### PR TITLE
[Non-modular] Removes blueshield defender energy carbine 

### PR DESCRIPTION
**Pull request by Swiftfeather**
## About The Pull Request

Removes the energy carbine with tasers from blueshield loadout

## Why It's Good For The Game

it's rapid fire tasers 

## Changelog

:cl:
del: Blueshields no longer get a taser gun in their choice beacon.
/:cl:

### CODE REVIEW

**Comment by projectkepler-ru** [comment]
Done in [This](https://github.com/Bubberstation/Bubberstation/pull/1485) PR

**Comment by Swiftfeather** [comment]
> Done in [This](https://github.com/Bubberstation/Bubberstation/pull/1485) PR

yea that's this pr

**Comment by projectkepler-ru** [comment]
nice job supershit :sob: I meant [this ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/27409)

**Comment by StrangeWeirdKitten** [comment]
Can someone fix linters with this PR. All you need to do is replace FeatureDropdownInput with createDropdownInput

'''
packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/bubbers/entombed.tsx(6,3): error TS2724: '"../../base"' has no exported member named 'FeatureDropdownInput'. Did you mean 'createDropdownInput'?'''

**Comment by StrangeWeirdKitten** [comment]
nvm #1486

**Pull request merged**
