### PR TITLE
Misc SolFed weapon fixes (Not balance)

### PR DESCRIPTION
**Pull request by ReturnToZender**
## About The Pull Request

This PR fixes the Carwo d'Elite being called a Sniper Rifle, when it's more accurately a Marksman rifle.

Additionally, the Renoster Shotgun said that additional ammo was sold separately. This is patently false as it comes with two boxes of buckshot. The description has been fixed.
Finally, advanced ammo boxes can be crafted using cardboard, much like the old TG ammo boxes.

## Why It's Good For The Game

The gun nuts are outside my home, please speedmerge

## Proof Of Testing
image
image
image
image

## Changelog

:cl: ReturnToZender (Code)
fix: The Shotgun crate now properly reports that it contains two boxes of buckshot.
fix: Updates the description for various shotgun ammo boxes to match the real amount of ammo they store.
add: You can now create advanced shotgun ammo boxes using cardboard.
spellcheck: The Carwo d'Elite rifle is properly marked as a Marksman Rifle, instead of a Sniper Rifle.
/:cl:

### CODE REVIEW

**Comment by ReturnToZender** [comment]
Tested advanced shotgun ammo boxes and they're slightly more convenient versions of the regular ammo boxes you can acquire. Technically you can store an additional box on your belt with the advanced boxes, giving you one additional reload.

**Comment by IgiariValkyr** [comment]
I’m a gun nut and would like this speedmerged

**Review by projectkepler-ru — APPROVED** [review]

**Comment by projectkepler-ru** [comment]
> Tested advanced shotgun ammo boxes and they're slightly more convenient versions of the regular ammo boxes you can acquire. Technically you can store an additional box on your belt with the advanced boxes, giving you one additional reload.
> 
> If that's too much, I can adjust the boxes so they don't fit on the belt.

not an issue

**Comment by projectkepler-ru** [comment]
If nothing else come up I'll merge this

**Comment by projectkepler-ru** [comment]
Upsream actually renamed how the guns are named for some now

**Comment by ReturnToZender** [comment]
> Upsream actually renamed how the guns are named for some now

sobs. Are they Bulgarian or something now?

**Pull request closed without merging**
