### PR TITLE
Updates Ashwalker Spawn on Non-Icebox Maps

### PR DESCRIPTION
**Pull request by Myphicbowser**
## Changelog

:cl:
qol: Separates the Tool area and Bedroom
qol: Slightly expands the entire Area
qol: Expands the Farming Area
/:cl:

### CODE REVIEW

**Review by projectkepler-ru — COMMENTED** [review]
screenshot?

**Comment by Myphicbowser** [comment]
image
Yes yes, I forgor the screenshot

As you can see, expanded, more organized farming area, guaranteed no rocks outside the main entrance, separated the toolshed from the bed rooms etc etc

**Comment by Myphicbowser** [comment]
I already updated and fixed the Missing Tiles
Please merge it whenever possible!
I'm such a stupid moron

**Comment by NullDagaf** [comment]
For the record, this just looks straight-up ugly. I'm all for re-doing how the ashwalker base looks if it's an actual improvement, but this ain't it.

**Comment by Myphicbowser** [comment]
I respect your opinion, however a lot of people really like this

I've seen massive amounts of Ashwalkers recently, and I know a lot of people who think this is an improvement

**Comment by projectkepler-ru** [comment]
are there any more changes being made for this @Myphicbowser

**Review by KathrinBailey — CHANGES_REQUESTED** [review]
I just want a few questions answered @Myphicbowser
1. Why surround the entire ash base with indestructible walls?
2. What are you adding that the old ruin doesn't have already?
3. Why create extra empty unused space within the ruin?

**Comment by Myphicbowser** [comment]
> 1. Why surround the entire ash base with indestructible walls?
It was already partially surrounded by indestructible walls, but I just finished it out, still multiple ways into the base. It also protects the rest of the structure if a very destructive boss is activated nearby, nobody likes joining a heavily damaged ghost spawn

> 2. What are you adding that the old ruin doesn't have already?
Nothing, I just organized it, made the structure overall unified in design, and protected it from outside threats. It puts them more in line with my lore, but that's a tertiary concern

> 3. Why create extra empty unused space within the ruin?
So people have more farming space, more room to do small scale things safely, and more importantly so it doesn't feel cramped and gross.

**Comment by projectkepler-ru** [comment]
is this still being worked on? @Myphicbowser @KathrinBailey

**Comment by Myphicbowser** [comment]
As far as i'm concerned @projectkepler-ru, it's done

**Comment by nevimer** [comment]
this conflicts now sadly

**Pull request closed without merging**
