### PR TITLE
amonugs

### PR DESCRIPTION
**Pull request by tf-4**
https://github.com/Bubberstation/Bubberstation/pull/428

:cl:
del: removed among us mobs
/:cl:

### CODE REVIEW

**Comment by ReturnToZender** [comment]
Make them a playable species instead

**Comment by nevimer** [comment]
merging in a few days if uncontested

**Comment by DeerJesus** [comment]
i contest this love my little among nuts

**Comment by Detective-Google** [comment]
> > merging in a few days if uncontested
> 
> 🥺

🥺

**Comment by Daved27hundred** [comment]
they are gone. we are free

**Pull request merged**
