### PR TITLE
Storyteller 2.1 - How did we miss this edition

### PR DESCRIPTION
**Pull request by Majkl-J**
## About The Pull Request

So the recent storyteller 2.0 update revealed a lot of funny underlying issues that we never noticed... somehow???

### Roundstart check being fucked
Turns out, only the roundstart events were able to roll, even when it was not roundstart. This resulted in some.. funny bugs to say the least, and also meant antag caps were never checked.

### Antag caps
Turns out these never worked! The math used GLOB.antagonists which is a static list of all antag datum types and not a list of living antags.

### Antag type limits
These were never checked before spawning when they should be checked so they don't waste a roll.

## Why It's Good For The Game

It actually makes shit work

## Changelog

:cl:
fix: Storyteller now actually rolls stuff correctly and in respect to the antag cap
/:cl:

### CODE REVIEW

**Comment by NargaInDisguise** [comment]
Oh! This explains so much! Holy shit no wonder!

**Review by nevimer — APPROVED** [review]

**Comment by ReturnToZender** [comment]
Waterpig yet again being the GOAT

**Comment by coffeecoffeecoffee** [comment]
Incredibly cool and great work, but while we're at it can we lessen the restrictions on rounds where shit actually happens to once every 2 rounds yet, or do we need 6 hours of nothing happening before we can be trusted with antaggies?

**Comment by coffeecoffeecoffee** [comment]
This appears to have fucked antagonist spawns even on high-intensity "gamer" rounds. They are no longer spawning.

**Comment by Erol509** [comment]
> This appears to have fucked antagonist spawns even on high-intensity "gamer" rounds. They are no longer spawning with this testmerged.

Antag scales with sec alive. If there is no sec, none will spawn. Or at most 1 per antag cap.

**Comment by Arturlang** [comment]
> > This appears to have fucked antagonist spawns even on high-intensity "gamer" rounds. They are no longer spawning with this testmerged.
> 
> Antag scales with sec alive. If there is no sec, none will spawn. Or at most 1 per antag cap.

So, the meta is to never go security so no antags spawn?

**Comment by coffeecoffeecoffee** [comment]
> > This appears to have fucked antagonist spawns even on high-intensity "gamer" rounds. They are no longer spawning with this testmerged.
> 
> Antag scales with sec alive. If there is no sec, none will spawn. Or at most 1 per antag cap.

That explains it, but is an awful, awful, awful sink-or-swim system. The experience of being the only sec player is fucking horrendous and mind-numbing to experience for, say, an entire night.

**Comment by Majkl-J** [comment]
> That explains it, but is an awful, awful, awful sink-or-swim system. The experience of being the only sec player is fucking horrendous and mind-numbing to experience for, say, an entire night.

Wait until you hear how dynamic handles it (Aside from roundstart it cant spawn more antags unless there's sec, scoryteller copies this)

**Pull request merged**
