### PR TITLE
Adds a space gateway area to Moonstation so people can fuck off in space

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Adds a space gateway area to Moonstation so people can fuck off in space.

image

## Why It's Good For The Game

I was told people don't like my map because they want space ruin ghost roles to split the pop further (you literally have like 20 different ghost roles that do this).

## Proof Of Testing

It probably doesn't work, actually. I can't get space ruins to spawn but it's probably because of low memory mode. Let's find out together.

## Changelog

:cl: BurgerBB
add: Adds a space gateway area to Moonstation so people can fuck off in space.
/:cl:

### CODE REVIEW

**Comment by BurgerLUA** [comment]
no idea why this freaks out tests

**Comment by ReturnToZender** [comment]
Moonstation not having space ghost roles is based, actually

**Comment by nevimer** [comment]
> ## About The Pull Request
> 
> Adds a space gateway area to Moonstation so people can fuck off in space.
> 
> image
> ## Why It's Good For The Game
> 
> I was told people don't like my map because they want space ruin ghost roles to split the pop further (you literally have like 20 different ghost roles that do this).
> ## Proof Of Testing
> 
> It probably doesn't work, actually. I can't get space ruins to spawn but it's probably because of low memory mode. Let's find out together.
> ## Changelog
> 
> 🆑 BurgerBB add: Adds a space gateway area to Moonstation so people can fuck off in space. /:cl:

It would be cooler if it wasn't a gateway but instead a shuttle that takes you to and from an orbital base

**Comment by BurgerLUA** [comment]
> Moonstation not having space ghost roles is based, actually

honestly it might be, but if no one wants to play the map because of that then I'm conflicted about my own PR

It sucks that Moonstation hasn't been played since 33 rounds ago as of this comment. I asked why no one wants to play Moonstation and people said they can't play dauntless and this PR is a solution to that.

**Comment by Majkl-J** [comment]
> It sucks that Moonstation hasn't been played since 33 rounds ago as of this comment. I asked why no one wants to play Moonstation and people said they can't play dauntless and this PR is a solution to that.

This is doubly weird then because dauntless used to spawn on Moonstation lavaland just find

**Comment by AllCorruptingWyrm** [comment]
I honestly just think its because of the new icebox map and voting changes

**Pull request closed without merging**
