### PR TITLE
[Salt PR] Mutes dchat by default because I heard them complain once

### PR DESCRIPTION
**Pull request by ReturnToZender**
## About The Pull Request

If a salt PR removes salt, is it more or less salty? This is the salt paradox.

This PR makes it so that deadchat is muted by default at roundstart. It does not (currently) discriminate between observers and dead players, no one will be able to use deadchat. Simple as.

I'm chuckling a bit at this one, but I'm sure everyone knows why this is here.
GDavdh0WYAI3eXR

(Please note that this is only semi-serious and I won't get mad if this gets rejected :P if anything I expect it)

## Why It's Good For The Game
Deadchat is a cesspit, and observer mains add no value to a round. Disabling it would lead to a net positive experience for everyone observing.

## Proof Of Testing
image

## Changelog

:cl: ReturnToZender
fix: Deadchat is no longer able to be spoken in unless explicitly enabled by admins (for things like polls and offering event rolls!)
/:cl:

### CODE REVIEW

**Comment by AllCorruptingWyrm** [comment]
thank mars

**Comment by ReturnToZender** [comment]
> thank mars

I've literally never seen you on this github before but I am glad you are here

**Comment by Iamgoofball** [comment]
this is a terrible idea imho, talking in deadchat is fun and passes the time when you die, also not being able to discuss the ongoing round with other fellow dead people is dumb

**Comment by Swiftfeather** [comment]
You get rid of the people who get excessively upset in deadchat. You don't get rid of deadchat. 

"Wow this person/few people just raged and said some awful shit in deadchat. Let's turn off deadchat so that they can never do it again instead of getting rid of this person/people."

**Comment by BurgerLUA** [comment]
To be fair to Zender, they had this idea for at least 1 month, I think because I remember them discussing this with me and some other people.

Deadchat is indeed a cesspit and it pains me that every time I look at it it either consists of:
- People complaining about antags not going hard enough.
- People complaining about people who died recently for not going hard enough.
- People complaining about security arresting antags that were murdering crew.
- People complaining about people outside their metaclique.
- People cheering on the mass murdering antagonist for amusing them while they wait to get blob, spiders, ninja, or other.

Want to discuss something? Do it in OOC. Ez pz.

**Comment by StrangeWeirdKitten** [comment]
> To be fair to Zender, they had this idea for at least 1 month, I think because I remember them discussing this with me and some other people.
> 
> Deadchat is indeed a cesspit and it pains me that every time I look at it it either consists of:
> 
> * People complaining about antags not going hard enough.
> * People complaining about people who died recently for not going hard enough.
> * People complaining about security arresting antags that were murdering crew.
> * People complaining about people outside their metaclique.
> * People cheering on the mass murdering antagonist for amusing them while they wait to get blob, spiders, ninja, or other.
> 
> Want to discuss something? Do it in OOC. Ez pz.

this sums it up. If Zender doesn't like d-chat. If the admins agree with this. Then goodbye d-chat. 

> You get rid of the people who get excessively upset in deadchat. You don't get rid of deadchat.
> 
> "Wow this person/few people just raged and said some awful shit in deadchat. Let's turn off deadchat so that they can never do it again instead of getting rid of this person/people."
> 
> Sets a really bad precedent.

this is a nifty idea and all, but also admins are volinteers and on top of managing whatever issues happens in the game, they're also expected to nuke people out of d-chat. 

I'm going to smack the "staff discussion" lable on this. Since admins can decide themselves what they want to deal with or keep.

**Comment by Swiftfeather** [comment]
> To be fair to Zender, they had this idea for at least 1 month, I think because I remember them discussing this with me and some other people.
> 
> Deadchat is indeed a cesspit and it pains me that every time I look at it it either consists of:
> 
> * People complaining about antags not going hard enough.
> * People complaining about people who died recently for not going hard enough.
> * People complaining about security arresting antags that were murdering crew.
> * People complaining about people outside their metaclique.
> * People cheering on the mass murdering antagonist for amusing them while they wait to get blob, spiders, ninja, or other.
> 
> Want to discuss something? Do it in OOC. Ez pz.

Okay. I'll discuss the round I'm observing and ask questions about what people are doing in game that I don't understand to OOC. Sounds good.

**Comment by Sylphet** [comment]
I do not have the words to describe how much I hate this idea. Observing is incredibly fun when I don't have the energy to play and this would delete the thing I spend more than half my time on bubberstation enjoying in one singular PR.

**Comment by StrangeWeirdKitten** [comment]
We can also start flat out muting it more liberally, but then people complain when it's muted. Or we could start noting people who get a little too emotional. But overall I'd rather the first option before the nuclear option or even the pruning option. So we'll try that. Admins for now on do not need to justify when and for how long they mute d-chat for. Don't bother them when they do.

**Comment by StrangeWeirdKitten** [comment]
Ok I instructed staff to kill d-chat and OOC at the drop of the dime. We'll try the less nuclear approach first.

**Pull request closed without merging**
