### PR TITLE
Removed skyratified armories, reverting them to tg standard gearsets.

### PR DESCRIPTION
**Pull request by Tupinambis**
## About The Pull Request

Removes the skyrat armory overrides and converts Void Raptor's armory to TG standards. Essentially this means:
CMGs, MCRs, Smartguns, Peacekeeper Shotguns are gone. Eguns, Laser Guns, Disablers, and Riot Shotguns are in.

## Why It's Good For The Game

The game is balanced around security having rechargeable energy weapons pretty much across the board, with their only ballistic option taking time to reload, being a bit harder to store backup ammo for, and punishing misses. The current weapon set flies in the face of balance and can end up screwing the crew or antags over. 

CMRs are the worst offender given that they are functionally just lower damage C-20rs that are very effective at wounding, do a ton of damage, and generally make uplink weapons look bad in comparison with a lot more room for error than standard tg ballistic options with EMP immunity to boot. MCRs go in the direction of being nearly useless without upgrades, and being terrible against threats like blobs due to their overheat mechanic. Moving back to standard TG affair feels like a good step in fixing some of the balance problems skyrat has introduced.

## Changelog

:cl: Tupina
balance: The roundstart armory on all maps has had its skyrat weapons replaced with standard TG weapons.
/:cl:

### CODE REVIEW

**Comment by IgiariValkyr** [comment]
Please keep the smartrifle? :<

**Comment by ReturnToZender** [comment]
Absolutely AWESOME, been waiting for this forever

**Comment by Serxule** [comment]
peacekeeper shotguns are actually worse than riot shotguns

**Comment by StrangeWeirdKitten** [comment]
#361 NEEDS to be merged with this if it goes through

**Comment by Tupinambis** [comment]
> peacekeeper shotguns are actually worse than riot shotguns

From what I can tell they're just reskins, but if you could point me to where they actually get nerfed I'll look into changing it.

**Comment by Serxule** [comment]
> > peacekeeper shotguns are actually worse than riot shotguns
> 
> From what I can tell they're just reskins, but if you could point me to where they actually get nerfed I'll look into changing it.

peacekeepers have a smaller mag capacity, i think its 2 less than the riot shotty

**Comment by YakumoChen** [comment]
I swore we had a PR that did this already but I think it was overwritten by skyrat code

anyway when are we getting the red security vendors in the armoury again

**Comment by nevimer** [comment]
The problem with editing voidraptor is that it may not stay forever, but, merging anyways.

**Pull request merged**
