### PR TITLE
Removes code that allows you to mutate any Botany trait

### PR DESCRIPTION
**Pull request by ReturnToZender**
## About The Pull Request
Deletes 6 lines that make it so _every_ trait is mutatable, fixing the problem with the DNA manipulator (worth noting the problem itself was not the manipulator it was some lines of code that allowed any trait to be selected)

Also steals #1614 

## Why It's Good For The Game
Prevents any future issues of Botany powergaming by mutating anti-magic deathnettles that do 95 brute, then turn into a killer tomato when you click them in hand

## Proof Of Testing
image
I cannot add it :(

## Changelog

:cl: ReturnToZender, Shellspeed (DNA machine fix)
balance: Plants can no longer mutate traits that were specifically marked as not mutatable
Fix: Plant DNA manipulators now properly respect upgrades
/:cl:

### CODE REVIEW

**Comment by shellspeed1** [comment]
Not really theft chief, I thought we were just going to remove the gene editor.

**Review by Majkl-J — CHANGES_REQUESTED** [review]
Since we're already here and this is the most likely one to pass in, could you get rid of the single letter vars as well?

**Comment by ReturnToZender** [comment]
> Since we're already here and this is the most likely one to pass in, could you get rid of the single letter vars as well?

yeah sure

**Comment by ReturnToZender** [comment]
> Not really theft chief, I thought we were just going to remove the gene editor.

You did a great job with your code you just closed the PR so I wanted the fix to be there, it's got credit and everything ❤️ but you can reopen yours and I can take mine out if you need

**Comment by shellspeed1** [comment]
Nah, I'm not getting back to it until next week and I needed to figure out why I couldn't edit stat genes unless you figured that out already.

**Comment by ReturnToZender** [comment]
Gotta close and remake this PR sadly

**Pull request closed without merging**
