### PR TITLE
Head Convert Device for HeadRevs

### PR DESCRIPTION
**Pull request by larentoun**
## About The Pull Request

Adds a device for headrevs to remove mindshields and to convert command staff.

- To remove a mindshield, it takes 30 seconds;
- To convert a Head of Staff, it takes 60 seconds.

Tested with late-join HeadRev antag:
- HeadRev death causes Station victory;
- HeadRev converting Head causes Revolution victory;
- Head death causes Revolution victory;

TODO:
- [x] Make it multi-stage to mindshield removing/heads of staff converting;
- [x] Add more messages/animation for everyone to see what's going on. Also examine text?
- [x] Better values for do_afters
- [ ] Better name and description
- [ ] New icon???

## Why It's Good For The Game

Alternative way for headrevs to win by converting head of staff by removing COMMAND status from them, basically un-commanding them and removing from list of targets.

## Changelog

:cl:
add: Head Convert Device for HeadRevs, which allows to remove mindshields and to convert heads of staff
/:cl:

### CODE REVIEW

**Comment by StrangeWeirdKitten** [comment]
If this PR comes through, I'll be comfortable in enabling revolution again. 😃

**Comment by larentoun** [comment]
> If this PR comes through, I'll be comfortable in enabling revolution again. 😃

I would like to hear what values will be reasonable? I think of 60seconds for either action, but segmented in 4 stages 15 seconds each

**Comment by StrangeWeirdKitten** [comment]
> > If this PR comes through, I'll be comfortable in enabling revolution again. 😃
> 
> 
> 
> I would like to hear what values will be reasonable? I think of 60seconds for either action, but segmented in 4 stages 15 seconds each

We can try this.

**Comment by The-Sun-In-Splendour** [comment]
I feel like maybe it should be some kind of structure that the Head Revs can craft/build/droppod in and strap the command staff in it to convert them. Maybe even make it loud and obvious that command staff is being brainwashed?

**Comment by destrucktoid** [comment]
> I feel like maybe it should be some kind of structure that the Head Revs can craft/build/droppod in and strap the command staff in it to convert them. Maybe even make it loud and obvious that command staff is being brainwashed, like an announcement or something?

i agree here, command staff are usually excluded from mind shielding because they can't be revved, imagine turning the HoP into a rev and having them walk into security and kill the remaining heads because nobody knew they were made into a rev. This definitely needs to become "audible" in some way.

**Comment by StrangeWeirdKitten** [comment]
@larentoun is this ready to be tested out code wise? Mostly the icon can be changed later further down the line if you manage to make a codersprite or find one somewhere.

**Comment by larentoun** [comment]
> @larentoun is this ready to be tested out code wise? Mostly the icon can be changed later further down the line if you manage to make a codersprite or find one somewhere.

Sorry for the delayed answer, got sick for the last two weeks (holy, that was a long sickness)

It should be ready code-wise, yes. I've done tests as written in the PR description.

**Comment by larentoun** [comment]
> the one issue I can, see is... headrevs somehow losing their device (not spawned in/gibbed and brain transfer/robbed and looted and revived later somehow/fullstripped and heretic sacced/contracted in a room with N2O and having their bag left behind/podperson revival/etc) and having to resort to decap RRing again. might be a good idea to make it craftable exclusively by revheads like traitor uplink beacons? with a naturally steep price.

Could be reasonable, yes, but need head-maint or anyone's else approval for that

**Comment by Majkl-J** [comment]
Stale. Ask for reopen when work continues

**Pull request closed without merging**
