### PR TITLE
[Ready] Adds Big Bertha, a unique one-of-a-kind two-handed shield for security that blocks (almost) everything.

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Adds Big Bertha, a unique one-of-a-kind two-handed shield for security that has a base 100% chance to block. This is reduced by 1 per point of armor penetration the damage deals.
Big Bertha spawns in the armory. **Only one exists.**
Big Bertha **slows you down when carried**, and **can only be carried with two hands**. Has about the same offensive capabilities as a toolbox.
When you block with the shield, it will deal half the damage blocked as stamina damage to you, as long as the damage is above 10.
There is a chance to drop the shield when you block with it, equal to how much damage to your stamina you have.

## Why It's Good For The Game

Security needs something for situations where there are only 2 officers and there is a stealth box dsword hardsuit adrenals cqc stim meth cocaine omnizine changeling heretic on the loose being super aggressive.

Since there is only one, it basically just means you shouldn't engage this person as an antagonist with traditional weapons. This means that there are diminishing returns with it when you have lets say 5 security officers, as only one of them can actually carry it.

It's not good for chasing down antagonists since it does have a slowdown. Note that it can't be affected by xenobiology speed potions because Big Bertha is just so darn fat.

There is only one fear that I have with the weapon, and that is if a holopara user gets the shield somehow and glues it to their hand. Admins should deal with this by sending a deathsquad in.

## Proof Of Testing

image
_Pictured: Warden out of brig._

image
_Pictured: The shield doesn't make you immortal._

## Changelog

:cl: BurgerBB
add: Adds Big Bertha, a unique one-of-a-kind two-handed shield for security that blocks literally everything. It spawns in the Armory.
/:cl:

### CODE REVIEW

**Comment by ReturnToZender** [comment]
This is hilarious.

**Comment by Redrover1760** [comment]
That's cool but... How do you kill someone with 100% Block chance, without resorting to explosions or plasmafires?

**Comment by BurgerLUA** [comment]
> That's cool but... How do you kill someone with a 100% Block chance unbreakable shield, without resorting to explosions or plasmafires? Maybe make it like 80-90% Block chance to be on par with the xenobio two handed shield instead? Well, honestly, the lack of offensive capabilities does make it very niche regardless, but being truly invincible is a bit silly.

I tried fighting colossus with it and I still died so you're not immortal.

I'll be entirely honest and say I don't know why you can die with the shield since everything in code makes it seem like you're immortal.

**Comment by projectkepler-ru** [comment]
> That's cool but... How do you kill someone with a 100% Block chance unbreakable shield, without resorting to explosions or plasmafires? Maybe make it like 80-90% Block chance to be on par with the xenobio two handed shield instead? Well, honestly, the lack of offensive capabilities does make it very niche regardless, but being truly invincible is a bit silly.



the same way you kill a person with sleeping carp

**Comment by Superhats** [comment]
It also has slowdown so you can just walk away from them.

**Comment by Majkl-J** [comment]
https://github.com/Bubberstation/Bubberstation/pull/1544/commits/da595daa51d7383ca80d3b358baf321a40ba697d


https://github.com/Bubberstation/Bubberstation/assets/49160555/0ca2cb45-e1a8-4926-b9e5-7da3d497fb10

**Comment by KazooBard** [comment]
> > That's cool but... How do you kill someone with a 100% Block chance unbreakable shield, without resorting to explosions or plasmafires? Maybe make it like 80-90% Block chance to be on par with the xenobio two handed shield instead? Well, honestly, the lack of offensive capabilities does make it very niche regardless, but being truly invincible is a bit silly.
> 
> the same way you kill a person with sleeping carp

You can just stunbaton a sleeping carp user thrice if they're on stims since 90% of stims in game do not make you stun baton proof. This has no counterplay except explosives if a baddie gets it. Stand in corner with carp to deflect all projectiles and bash at their heads until dead

**Comment by Redrover1760** [comment]
> > That's cool but... How do you kill someone with a 100% Block chance unbreakable shield, without resorting to explosions or plasmafires? Maybe make it like 80-90% Block chance to be on par with the xenobio two handed shield instead? Well, honestly, the lack of offensive capabilities does make it very niche regardless, but being truly invincible is a bit silly.
> 
> I tried fighting colossus with it and I still died so you're not immortal.
> 
> I'll be entirely honest and say I don't know why you can die with the shield since everything in code makes it seem like you're immortal.

Colossus is not a good estimation of "average antagonist" or well, antagonist in general. Its a megafauna, with energy bolts that pierce all armor, including shields.

**Comment by Arturlang** [comment]
Sounds like a nightmare to fight against. It really should not be 100% block, maybe close to it, and should *really* have durability, but you could make the broken state repairable

**Comment by projectkepler-ru** [comment]
> > > That's cool but... How do you kill someone with a 100% Block chance unbreakable shield, without resorting to explosions or plasmafires? Maybe make it like 80-90% Block chance to be on par with the xenobio two handed shield instead? Well, honestly, the lack of offensive capabilities does make it very niche regardless, but being truly invincible is a bit silly.
> > 
> > 
> > the same way you kill a person with sleeping carp
> 
> You can just stunbaton a sleeping carp user thrice if they're on stims since 90% of stims in game do not make you stun baton proof. This has no counterplay except explosives if a baddie gets it. Stand in corner with carp to deflect all projectiles and bash at their heads until dead



> > > That's cool but... How do you kill someone with a 100% Block chance unbreakable shield, without resorting to explosions or plasmafires? Maybe make it like 80-90% Block chance to be on par with the xenobio two handed shield instead? Well, honestly, the lack of offensive capabilities does make it very niche regardless, but being truly invincible is a bit silly.
> > 
> > 
> > the same way you kill a person with sleeping carp
> 
> You can just stunbaton a sleeping carp user thrice if they're on stims since 90% of stims in game do not make you stun baton proof. This has no counterplay except explosives if a baddie gets it. Stand in corner with carp to deflect all projectiles and bash at their heads until dead

I love how you completely miss my mark

**Comment by projectkepler-ru** [comment]
> Colossus is not a good estimation of "average antagonist" or well, antagonist in general. Its a megafauna, with energy bolts that pierce all armor, including shields.

well yeah it isn't, no antagonist in the game has pulse rifle on hand at all time

**Review by projectkepler-ru — CHANGES_REQUESTED** [review]
So, quite frankly this shield is goddamn absurd but it's going in the right direction.
Come back when you got a way to make this reasonably beatable

**Comment by BurgerLUA** [comment]
Ready to merge, linters failing because of storyteller.

**Comment by radarseas** [comment]
okay but what if I take this, scarp, antidrop and stimpac-....


_oh dear..._

**Comment by nevimer** [comment]
let's try it, whats the worst that can happen

**Pull request merged**
