### PR TITLE
Removes Ascensions from Heretic because the Catholic Church sent me a DM

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Removes Ascensions from Heretic. They are no longer obtainable research.

## Why It's Good For The Game

The crew at large gives a very generous amount of leniency that crew have towards Heretics since we're a roleplay server first. If someone is doing obvious heretic stuff, people don't scream on comms or attempt to validhunt heretics because, again, we're a roleplay server first. If the crew are punished for allowing roleplay, then in the future they probably won't roleplay and that's extremely unhealthy for a roleplay server.

From what I usually see in maybe 1 out of 10 heretic rounds, there is a heretic who doesn't really bother to interact or roleplay with the crew and instead makes it the goal to ascend. This usually leads to one antag slot being "wasted" and not creating interesting and meaningful interactions for the round until near the very end when they decide to ascend. 

Never have I seen a heretic ascend on code amber or higher because in 99% of cases heretics usually just peaceful sacrifice monkeycubes and crew in maint or just try to speedrun all the heretic anomalies on station to get the most research.

## Proof Of Testing

Untested.

## Changelog

:cl: BurgerBB
del: Removes Ascensions from Heretic. They are no longer obtainable research.
/:cl:

### CODE REVIEW

**Comment by AllCorruptingWyrm** [comment]
https://github.com/tgstation/tgstation/pull/79788
Relevant.

**Comment by BurgerLUA** [comment]
> [tgstation/tgstation#79788](https://github.com/tgstation/tgstation/pull/79788) Relevant.

They have very good points.

The PR seems to have been closed with the reason that the OP expected heretics to change, but it's been a year and they're pretty much the same now.

**Comment by Swiftfeather** [comment]
Bad pr burger didn't test it. Of course the biggest reason it's bad is because I disagree with it. :)

**Comment by ReturnToZender** [comment]
based

**Comment by destrucktoid** [comment]
> From what I usually see in maybe 1 out of 10 heretic rounds, there is a heretic who doesn't really bother to interact or roleplay with the crew and instead makes it the goal to ascend. This usually leads to one antag slot being "wasted" and not creating interesting and meaningful interactions for the round until near the very end when they decide to ascend.

The discussion about this has been had many times before and as always the counterpoint is that the people who play mechanically and create damage on the station may not be roleplaying in the way of talking to people but they innately create roleplay around themselves as people act and react to their actions. 

> Never have I seen a heretic ascend on code amber or higher because in 99% of cases heretics usually just peaceful sacrifice monkeycubes and crew in maint or just try to speedrun all the heretic anomalies on station to get the most research.

Burger, i know you know how heretics work and we _both_ know that they don't work like this. You cannot sacrifice humonkeys for research. You cannot speedrun heretic essences to ascend. Heretic ascensions are locked behind your objectives which are usually "sacrifice at least 4 crew one of which needs to be a head of staff". 

If a heretic ascends it's very rare and when it does happen it's because they played well, either via roleplay or via mechanics. Saying that ascensions occur because we are too lenient on heretics is just straight up untrue. Security stops heretics before they can ascend 9/10. Hence why we don't have many ascensions on the server.

**Comment by Erol509** [comment]
This is a pretty good PR, would there be a way to make the ascension possible via opfor? Once in a year, would be cool to have it.

**Comment by Alecksohs** [comment]
> Hence why we don't have many ascensions on the server.
Furthermore, that is why the entire server was confused so much that both a saltpr and several admin announcements explaining what was happening was required for a simple heretic ascension occurring at 30 players

**Comment by BurgerLUA** [comment]
We don't have many ascensions because it requires heretics to basically declare war on the station. Imagine if there was a traitor item that you could get that gives you 15 extra TC but it gives you the objective of nuking the station and announces this to the crew.

**Comment by StrangeWeirdKitten** [comment]
When people were ascending with blade, flesh, forge, rust, and void. I don't feel like these are completely arregious or entirely round ending on their own. But there's been a few new added since like Knock and Moon that are not aligned at all with the scale. Personally I'm slightly more keen on adding forwarning like the crew being warned on sacrafice three, making specific ascensions like Moon and Knock (or anything else I'm missing) an opfor item.

It's not that ascension in itself is bad, entirely. It's that you can do it stealthily very easily which I find to be a major issue. It's like if cult wasn't so blatent and just suddenly spawned nar'sie in the closet with no chance for the entire crew to fight back. There's not enough forewarning.

**Comment by StrangeWeirdKitten** [comment]
> When people were ascending with blade, flesh, forge, rust, and void. I don't feel like these are completely arregious or entirely round ending on their own. But there's been a few new added since like Knock and Moon that are not aligned at all with the scale and are comparitively much more "now everyone is an antag or dead". Personally I'm slightly more keen on adding forwarning like the crew being warned on sacrafice three, making specific ascensions like Moon and Knock (or anything else I'm missing) an opfor item.
> 
> It's not that ascension in itself is bad, entirely. It's that you can do it stealthily very easily which I find to be a major issue. It's like if cult wasn't so blatent and just suddenly spawned nar'sie in the closet with no chance for the entire crew to fight back. There's not enough forewarning.

**Comment by StrangeWeirdKitten** [comment]
personally I'm very neutral on removing ascension, leaning towards yes. But if you make it an opfor item that an admin can give out or enable, then you'll get another maintainer supporting this idea. I'm not the biggest fan of hard code disables. While I know it's possible for the admin to work some VV magic to magic it back in, it's not necissarily something a lot of them know how to do and I'd honestly would rather them have the option.

**Comment by nevimer** [comment]
Honestly, I am for this. Heretic is insanely strong even with no ascension, and ascension is usually round ending. You don't need to do much to ascend, either.

**Comment by KeRSedChaplain** [comment]
As long as ascensions can still be given by admemes I'm all for this since I think a lot of the ascensions are thematic for cult RP since it's not a conversion antag like blood cult is (you don't have to worry about John Mechanics ignoring the gimmick and rushing the sacrifice target)

**Comment by destrucktoid** [comment]
image
It seems people in the discord don't want this.

**Comment by destrucktoid** [comment]
People wouldn't like that thing if it wasn't good in some way Burger. Whether that be good mechanically, good fun wise or good as a rare event upon the station. Straight up removing it or locking it behind admins (which de facto _is_ removing it) because you and a select set of other people don't like it isn't the answer. The truth of the matter is that the majority of players do like it as evidenced by the suggestion above. 

If you don't like it then improve upon it in some way or design and make a replacement system rather than just axing it out of the game. The truth of the matter is that the ascension system is well designed and robust enough that even with the lack of validhunting and the leniency that we have on the server ascensions are still incredibly rare. 

To me it feels like you are removing a big part of Heretic for no reason other than you disliking it, rather than improving on it and making a new system that achieves the goals you want whilst simultaneously managing to maintain the design and theme behind Heretics and their pursuit of power within the Mansus.

**Comment by coffeecoffeecoffee** [comment]
They are even discussing removing heretic up at TG. I have never seen ascension be good for roleplay. I think a LOT of people missed out on the vote, and I can't think of a reason why we wouldn't remove mechanics that... PREVENT people from writing in the presence of or coming near the antagonist???

Who thought they were a good idea tbh

**Comment by Swiftfeather** [comment]
I don't think this is the right direction (it's also over a month stale)

**Comment by ReturnToZender** [comment]
Burger a month later when this PR gets reviewed again because he was actually cooking the entire time

**Comment by nevimer** [comment]
it might be time

**Comment by Cyprex** [comment]
I rather dislike heretic ascensions for reasons I mentioned on Discord. That said, the playerbase overwhelmingly wants to keep them. I ran a quick poll in-game and this were the results:

Should Heretic ascensions be removed?
Winner Selection: Simple
Results:
    0% | Yes, all of them: 0
 74.4% | Only Moon should be removed/reworked: 29
 25.6% | No, they should all be left as-is: 10
 
 As such I strongly believe we should **not** remove them.

**Comment by projectkepler-ru** [comment]
> In my opinion you should look at heretic's ascension, traitor's progressive system, cult's battle, nukies, wiz grand rituals and so so on not only as RolePlay, but gameplay element. Ascension, Traitor's Roundend task, Nar'Sie summon, Nuclear Explosion etc are _rewards_ for whole hard way, made by antagonist. Game gives antagonist OP stuff or massive destructions to sit back and relax and enjoy the view. Removing ALL ascensions without giving any alternative is very bad choice. One Nova Sector's contributor said to me once: "Removing something is not good way to develop code"(ironically, but still good thought). Also, if people DO NOT WANT to remove ascensions you have to, YOU KNOW, FOLLOW PEOPLE'S CHOICE, DUDE


We've not followed the people's choices on a lot of thing. Also please do not argue in here

**Comment by Cyprex** [comment]
Instead of this let's remove/rework just Moon and maybe that one other ascension I'm forgetting about right now.

**Comment by BurgerLUA** [comment]
> Instead of this let's remove/rework just Moon and maybe that one other ascension I'm forgetting about right now.

Problem is that no one is going to do this.

**Comment by ReturnToZender** [comment]
> > Instead of this let's remove/rework just Moon and maybe that one other ascension I'm forgetting about right now.
> 
> Problem is that no one is going to do this.

You showed me how to do this with this PR, Moon ascension I'm coming for your ass

**Pull request closed without merging**
