### PR TITLE
upstream-merge 22/3/2024

### PR DESCRIPTION
**Pull request by projectkepler-ru**

### CODE REVIEW

**Comment by projectkepler-ru** [comment]
Oh my GOD

**Comment by nevimer** [comment]
why so soon

**Comment by projectkepler-ru** [comment]
> why so soon

TG added a couple new stuff that was then merged by SR and SR also added a couple new stuff that I want to see downstreamed

**Comment by BurgerLUA** [comment]
`modular_zubbers/modules/customization/modules/mob/living/carbon/human/species/tajaran.dm:23:error: ass_image: undefined var`

ass image removal

**Comment by StrangeWeirdKitten** [comment]
TG refactored ass images. :)

**Comment by pixelkitty286** [comment]
> `modular_zubbers/modules/customization/modules/mob/living/carbon/human/species/tajaran.dm:23:error: ass_image: undefined var`
> 
> ass image removal

NOOOOO FIX INSTEAD PLEASE AAAA!!

**Comment by pixelkitty286** [comment]
> TG refactored ass images. :)

where?

**Comment by projectkepler-ru** [comment]
> > TG refactored ass images. :)
> 
> where?

ass image are stored as define now instead of as variable, I could fix it but there isnt an urgency to get an upstream merge right now

**Pull request closed without merging**
