### PR TITLE
Research module fixes and small rebalances.

### PR DESCRIPTION
**Pull request by pixelkitty286**
## About The Pull Request

Some general changes and bug fixes required to keep research modules usable.

Also added on some quality of life features such as a material bag and a xenobio bag

Changed some the assembly items to be under circuits gripper.

Fixes some issues with not being able to repair synths and moves surgical drapes and bonesetter into a new small omitool.

## Why It's Good For The Game

In the current state of the research module it is broken and has lots of issues this PR is to fix some of it's issues.

## Proof Of Testing

Trust me bro I compiled it and tested it locally.

This is the new image of a fully upgraded research borg looks like.

image

## Changelog

:cl:
add: cut down omitool a small upgrade for the scanner
del: Removed old things
qol: made research borgs actually able to revive and work on synths
balance: research cyborg grippers
fix: research cyborgs not being able to repair synths. research cyborgs being able to pick up the nuke disk (oops lol).
/:cl:

### CODE REVIEW

**Comment by pixelkitty286** [comment]
I love CI errors being unrelated to my changes

**Comment by StrangeWeirdKitten** [comment]
No, the CI is definitely from this PR. The rest of the codebase CI is working fine.

**Comment by pixelkitty286** [comment]
> No, the CI is definitely from this PR. The rest of the codebase CI is working fine.

I do not see what's causing it to fail it just runtimes on monkey it says

**Comment by pixelkitty286** [comment]
never mind found it never says anything on local

**Comment by pixelkitty286** [comment]
well i can't seem to figure out why it's so mad at a properly set up tech web item

**Comment by StrangeWeirdKitten** [comment]
Make sure ``code/modules/research/designs/experisci_designs.dm is ticked.`` The reason it pops out that error is because the code is looking for a ``/datum/design`` with that specific ID. If it doesn't have it, it removes it from the techweb and errors.

**Comment by pixelkitty286** [comment]
fixed it had a small errror

**Pull request merged**
