### PR TITLE
[TM ONLY] Bridge Assistant job

### PR DESCRIPTION
**Pull request by sippykot**
## About The Pull Request

Makes Bridge Assistant a regular job

## Why It's Good For The Game

Bridge Assistant added to the job roster per popular demand:
image
to serve as an introduction/training job for command and/or RP role

## Proof Of Testing

yeah, i tested it, i swear
image

## Changelog

:cl:
add: adds Bridge Assistant to the normal job roster, with some loadout changes
del: removes Bridge Assistant station trait
/:cl:

### CODE REVIEW

**Comment by Fn-OS** [comment]
Please testmerge :(

**Comment by Swiftfeather** [comment]
This is probably gonna devalue the fun of playing bridge assistant, I'd rather not have this merged

**Comment by Arturlang** [comment]
Staff sentiment is that they do not want this, since NTC already exists, and better justification is needed than just a picture of a suggestion poll.

**Comment by pixelkitty286** [comment]
> Maintainer sentiment is that they do not want this, since NTC already exists, and better justification is needed than just a picture of a suggestion poll.

Honestly in my opinion I see this as a good introduction job for learning command instead of jumping into it and then dealing with a large responsibility of running the entire station if there is 1 other real command member. Then having to read the long SOP on how to do command and hoping you don't slip up once or you get Ahelped then command banned on the spot for not knowing how to run the entire station or what ever department head you are.

Difference with playing Bridge assistant and NTC is you don't have to spend non stop hours as a head of a department you may or may not be bad at.

Also a slight difference as well from this is it feels like a lesser blue shield that CAN take breaks unlike a blue shield and you don't have to play 🤮security. (maybe you can "assist" the NTC)

**Comment by sippykot** [comment]
changed it a little so that the BA has a silver id and doesnt roll antag, after rolling antag with one.... don't want the command to be suspicious of the BA

**Comment by sippykot** [comment]
> Maintainer sentiment is that they do not want this, since NTC already exists, and better justification is needed than just a picture of a suggestion poll.

NTC is not an introductory or low responsibility job, if anything it can get more demanding when it comes to procedural shit than Captain if Captain is the one fucking around and breaking procedure

**Comment by Swiftfeather** [comment]
> > Maintainer sentiment is that they do not want this, since NTC already exists, and better justification is needed than just a picture of a suggestion poll.

While I love the bridge assistant role, the introductory or 'low responsibility' job to learning command is playing in the departments that unlock command roles. The BA is not that.

The entire point of BA is to be a fun role that pops up once in a rare while to make command double take and go like "huh, didn't know we had one of you today."

**Pull request closed without merging**
