### PR TITLE
[MIRROR/PORT] TG/Nova firelock updates

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request

Mirrors TG and Nova firelock updates, reverting Bubberstation overrides since the underlying issue of fire detection on wall tiles was fixed upstream at TG, and merged on Bubber in the Feb 2 update.

From TG, air alarms now display the offending firedoor/fire alarm that is triggering an alarm, allowing engineers to respond to the specific problem instead of a guessing game.

Nova made a Bubber edit relating to crowbars to match, so this aligns the code and comments in modular_skyrat\master_files\code\game\machinery\doors\firedoor.dm

Retains the Bubber modification relating to firelocks remaining open when crowbarred with right-click. Firedoors will only close if the pressure is past the hazardous threshold.

## Why It's Good For The Game

Less firelock hell from the air alarms triggering everything, maintains parity with TG.

## Proof Of Testing

https://github.com/Bubberstation/Bubberstation/assets/83487515/d6faa9d8-db60-449b-9933-88ec6a1acb58

image

## Changelog

:cl: LT3
code: Parts of firelock code updated to parity with TG
/:cl:

### CODE REVIEW

**Comment by BurgerLUA** [comment]
This should be testmerged in case people prefer atmos alarm triggering instead of firelocks detecting air changes.

**Comment by lessthnthree** [comment]
Yeah, reasonable.

**Comment by aKromatopzia** [comment]
oh firelock triggering alarms sounds like something that should've been made optional by adding an air alarm module to it during construction. they just trigger from any poor air quality innately, without being attached to the air alarm?

**Comment by lessthnthree** [comment]
> oh firelock triggering alarms sounds like something that should've been made optional by adding an air alarm module to it during construction. they just trigger from any poor air quality innately, without being attached to the air alarm?

Only hazardous levels of heat, cold, or pressure.

This means when a hole or fire occurs only the firelocks in the vicinity will close, not the entire area.

**Comment by lessthnthree** [comment]
Firelocks be working good, this is fine to merge.

**Review by Majkl-J — APPROVED** [review]
We had this for a month, no complaints

**Pull request merged**
