### PR TITLE
[Non-Modular] Adds Bio-tram sprites to computer.dmi

### PR DESCRIPTION
**Pull request by ReturnToZender**
## About The Pull Request
Fixes a runtime in Biodome's tests due to their computer not having sprites in computer.dmi.

## Changelog

:cl:
Add: Tram-specific Biodome sprites added to computer.dmi.
Fix: Biodome trams now have their sprites working.
/:cl:

### CODE REVIEW

**Comment by ReturnToZender** [comment]
Looks like tgstation.dme has "interface/skin.dmf" before "interface/stylesheet.dm" for whatever reason. Maybe because skin.dmf needs to override stylesheet.dm? Unsure.

I think this is an upstream issue, but I can add a commit making these the right order.

**Comment by ReturnToZender** [comment]
Just completed testing, it fixes that runtime both in the test and in-game :)

**Comment by nevimer** [comment]
needs fixin

**Comment by ReturnToZender** [comment]
This pull request is redundant because the sprites have been added elsewhere, closing now

**Pull request closed without merging**
