### PR TITLE
[Not Modular] Climbable element now includes a check for if you're laying down when trying to climb a table, and instead puts you under it if you are

### PR DESCRIPTION
**Pull request by Odairu**
## About The Pull Request
Does as the title says

## Why It's Good For The Game
I can have cute boys under my desk now- and gives more movement options for hiding from security and whatnot, generally just cool :)

## Proof Of Testing
image

## Changelog

:cl:
add: tables can be crawled under if you're resting
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
Make it so you can't stand while under a table

**Comment by YakumoChen** [comment]
Also how does this work for shoving people

**Comment by YakumoChen** [comment]
This also is kind of a huge pain in the ass for anything melee related since you can't click on people under tables. This puts chefs on suicide watch and makes it miserable to deal with sleeping carp

**Review by projectkepler-ru — CHANGES_REQUESTED** [review]
Please hold, this may actually upset balancing

**Comment by nikothedude** [comment]
this just sounds like hell because you can attack out of it while people cant attack you since youre like. under the table and can even move around

**Comment by aKromatopzia** [comment]
> I can have cute boys under my desk now

Implying Odairuu is ever on station...

Man this is one of those PRs that are cool in theory but SS13 can't really support. Is it possible to make attacking the furnishing to also cause damage to the hider; or the hider to have longer action times/cooldowns?

**Comment by projectkepler-ru** [comment]
> > I can have cute boys under my desk now
> 
> Implying Odairuu is ever on station...
> 
> Man this is one of those PRs that are cool in theory but SS13 can't really support. Is it possible to make attacking the furnishing to also cause damage to the hider; or the hider to have longer action times/cooldowns?

Yes

**Pull request closed without merging**
