### PR TITLE
Fallout sprite updates and fixes

### PR DESCRIPTION
**Pull request by xPokee**
## About The Pull Request
Basically, there were a bunch of F13 mobs already in the code, this is the first half of my set of PRs to both make them into basic mobs and fix their sprites.
## Why It's Good For The Game
The sprites were outdated, had stray pixels, and were downright ugly due to being years old.
## Proof Of Testing
I didn't change any code besides adding a dead icon state to the sentrybot, but see below for the sprites changed or check SpriteDiff Bot
<details>
<summary>Screenshots/Videos</summary>
Before:
image

After: 
image

</details>

## Changelog
:cl:
image: replaced the outdated F13 mob sprites with their current F13 versions
/:cl:

### CODE REVIEW

**Comment by Majkl-J** [comment]
image
Are the protectbots meant to have these outlines?

**Comment by xPokee** [comment]
> Are the protectbots meant to have these outlines?

They should be pretty much transparent and won't actually show up much in game if they were ever spawned, let me grab a screenshot of how it looks in game real quick.

**Comment by xPokee** [comment]
image
@Majkl-J There's how it is in game, want me to lighten/remove the outline or is it good?

**Comment by Majkl-J** [comment]
Looks good, amazing work

**Review by Majkl-J — APPROVED** [review]

**Pull request merged**
