### PR TITLE
Femboyification Admin Smite from FluffySTG

### PR DESCRIPTION
**Pull request by ReturnToZender**
## About The Pull Request

Source Inspiration: https://github.com/Fluffy-Frontier/FluffySTG/pull/41

This PR adds an admin smite that femboyifies anyone it is used on. Specifically, it turns them into a random-colored Vulpkanin and re-does their flavor text to be more attractive.

## Why It's Good For The Game
This adds to the roleplaying experience of the server by making it so that admins can turn previously stuck-up bald human griefers into femboys fit for the roleplaying environment on Bubberstation. It even writes their flavor text for them! Wowie!

## Proof Of Testing

https://github.com/Bubberstation/Bubberstation/assets/110273561/f8c092d1-5d07-4864-89f8-55851a8719ae
## Changelog

:cl: ReturnToZender, Cachemir (Translation), K3 (Humor),
RaShCat (Original Russian version)
add: Femboyification Smite
/:cl:

### CODE REVIEW

**Comment by nevimer** [comment]
I can't imagine any scenario where anyone would use this lol

**Comment by ReturnToZender** [comment]
> I can't imagine any scenario where anyone would use this lol

I can imagine several.

**Comment by Detective-Google** [comment]
Wouldn't using this often constitute a prefbreak?

**Comment by Majkl-J** [comment]
> Wouldn't using this often constitute a prefbreak?

https://github.com/Bubberstation/Bubberstation/blob/master/code/modules/admin/smites/become_object.dm

Most of the smites are there for memes anyhow

**Comment by StrangeWeirdKitten** [comment]
Please do not get us repo quarantined and make the json read off the config

**Comment by theselfish** [comment]
> Wouldn't using this often constitute a prefbreak?

Not rea- Well yes. But, Smites are a comic effect. It's the same as getting breaded or puzzled. Most we'll see is this at EORG on Jack Grey or something.

**Comment by StrangeWeirdKitten** [comment]
Have it read from the server database / config, not the repo

**Comment by ReturnToZender** [comment]
Closed due to stale, I'm working on the Bubberstation RP update right now and can't complete this as needed

**Pull request closed without merging**
