### PR TITLE
Adds TEG [MDB IGNORE] [IDB IGNORE]

### PR DESCRIPTION
**Pull request by Erol509**
## About The Pull Request

Ports TEG from Ship Test/ Yog station, buts its still heavily under construction. Most things here dont work yet, but it doesnt crash and compiles well. It still needs a lot of work, and Im not a good coder, If I wont be able to fix it, then I will just give up on this project and close the PR...but for now, I will leave it here.

#https://github.com/yogstation13/Yogstation/pull/9195

image

TODO:

- [ ] Fix Tgui error
- [ ] Fix the ability to unanchor, open, rotate circulators/generator
- [ ] Test this, and make it actually work and generate power
- [ ] Add design boards to HFR reaserch node

I dont take any credits, TGUI was made by martinlyra. Link is in the chat below.

## Why It's Good For The Game
To be added

## Changelog

:cl:
add: TEG

/:cl:

### CODE REVIEW

**Comment by Erol509** [comment]
CI, seems to be just garbage errors

**Comment by retlaw34** [comment]
please credit where you got the TGUI interface from, which is https://github.com/shiptest-ss13/Shiptest/pull/817 by martinlyra, and is not apart of the original yogstation pull request

**Comment by Erol509** [comment]
> please credit where you got the TGUI interface from, which is [shiptest-ss13/Shiptest#817](https://github.com/shiptest-ss13/Shiptest/pull/817) by martinlyra, and is not apart of the original yogstation pull request

Will do

**Comment by Erol509** [comment]
Closing for now...TGUI beat me down with errors

**Pull request closed without merging**
