### PR TITLE
Moth buff port from Nova Sector

### PR DESCRIPTION
**Pull request by ReturnToZender**
## About The Pull Request
This PR adds the ability for moths to smell with their antennae, and also gives them a dash ability that costs stamina, reducing movement speed after the dash is triggered.

see https://github.com/NovaSector/NovaSector/pull/752 for original code.

## Why It's Good For The Game
Moth supremacy strikes again

## Proof Of Testing

https://github.com/Bubberstation/Bubberstation/assets/110273561/55225a7a-1a30-4c7a-9eea-cde7f1965903

## Changelog

:cl: Nerev4r (Code), ReturnToZender (port)
add: Moths now get a dash at the cost of stamina. You can use at most 3 dashes before entering stamcrit.
add: Flutter emote for moths
/:cl:

### CODE REVIEW

**Comment by Swiftfeather** [comment]
moth bias

**Comment by aKromatopzia** [comment]
Based and clothpilled

**Comment by Erol509** [comment]
Dash should deal more stamina.

**Comment by ReturnToZender** [comment]
> Dash should deal more stamina damage. Perhaps round it to 40 from 37.5

Having used it, I agree, 4 dashes is pretty strong. I'll start by adjusting it to 40 tomorrow.

**Review by Majkl-J — COMMENTED** [review]
How do you feel about this one? Ill give the code an extra look if you tell me this is finished on your side

**Comment by MajorBugReports** [comment]
How about 41-45 stamina and you're golden. Make sure others around you get a test blurb that you're doing said dash and maybe add couple second delay because giving someone dash boots as a non miner with immediate slowdown/wind up or massive cooldown between uses (like the dash boots) is a bit much.

**Comment by ReturnToZender** [comment]
> How about 41-45 stamina and you're golden. Make sure others around you get a test blurb that you're doing said dash and maybe add couple second delay because giving someone dash boots as a non miner with immediate slowdown/wind up or massive cooldown between uses (like the dash boots) is a bit much.

41-45 stamina is unlikely to actually change the ability in a meaningful way, but I can try it out

**Comment by ReturnToZender** [comment]
Moved to #1897

**Pull request closed without merging**
