### PR TITLE
Kilostation extra room

### PR DESCRIPTION
**Pull request by lilBlovy**
## About The Pull Request

Added a room within one of the meteorites on kilo station to be used for relaxation

## Why It's Good For The Game

It gives the map a bit more personality and makes it feel like your actually building a base within a meteorite.

## Changelog

:cl:
add: Ruin on Kilo station.
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
This will not be merged. Map changes are not possible unless they are fully modular

**Comment by lilBlovy** [comment]
> This will not be merged. Map changes are not possible unless they are fully modular

What do you mean by fully modular?

**Comment by YakumoChen** [comment]
You must use the automapper which has its module here https://github.com/Bubberstation/Bubberstation/tree/master/modular_skyrat/modules/automapper

**Comment by YakumoChen** [comment]
Non-modular changes to the base maps are not feasible because they will be overwritten by upstream pulls.

**Review by projectkepler-ru — CHANGES_REQUESTED** [review]
Automapper

**Review by Majkl-J — COMMENTED** [review]
Pretty sure Kilo is no longer an upstream map, disregard above comments until I can check.

Update: Kilo isn't on upstream

**Review by projectkepler-ru — APPROVED** [review]

**Review by Majkl-J — CHANGES_REQUESTED** [review]
Please do show a screenshot of the map change in game and I will give you my own green checkmark

**Comment by SonicGotNuked** [comment]
No, no need to use the auto mapper on kilo. Upstream no longer has kilo in the codebase.

**Comment by lilBlovy** [comment]
> No, no need to use the auto mapper on kilo. Upstream no longer has kilo in the codebase.

I will provide a picture of the changes soon then!

**Comment by lilBlovy** [comment]
image


It is a room inside the rock that is right above the chapel. It is there for a get away place for couples for RP purposes. You need to go out of your way to get there. It is marked as a ruin so it has infinite power, however it is far enough away from the station where I wont see that as an issue.

**Review by Majkl-J — APPROVED** [review]
Sure, looks nifty. If we have anyone abusing it we can always just make it require power, a quick change

**Comment by SonicGotNuked** [comment]
If it doesn’t require power, please make it require power

**Review by StrangeWeirdKitten — CHANGES_REQUESTED** [review]
Give it atmospherics and make it require power. I don't mind if it's completely separated from the station and had its own little generator and air tank, but I don't want free power rooms on the station Z level

**Comment by lilBlovy** [comment]
> Give it atmospherics and make it require power. I don't mind if it's completely separated from the station and had its own little generator and air tank, but I don't want free power rooms on the station Z level

If it does become a problem we can always add that but for now, we can experiment with it and see if it would even be a problem in the first place. Its ment to be an erp space like dorms so people shouldnt be going there except couples

**Comment by lilBlovy** [comment]
If u really think it will be a huge issue I can fix it

**Comment by StrangeWeirdKitten** [comment]
> If u really think it will be a huge issue I can fix it

Please no free power rooms on the station Z level.

**Comment by StrangeWeirdKitten** [comment]
Stale, feel free to reopen with requested changes

**Pull request closed without merging**
