### PR TITLE
Interlink Admin Office

### PR DESCRIPTION
**Pull request by IgiariValkyr**
## About The Pull Request

Makes a proper office for Centcom Administration on the Interlink. Includes a small bedroom for ERP as well.
Essentially, I've been messing around with my amazing admin powers a lot and I figured: "Hey. Why do we still do stuff from the old Centcom area when we bluespace-spawn? The Interlink was mean to make the connection between Centcom and the Station closer ever since [other server] decided 'nah fuck the old centcom building'. So here we are, a cute little office." Thus, the cute little Administrative Office was born. Yes, it's called the Administrative Office as a joke since admins will use it.

dreamseeker_2024-01-15_17-51-18

## Why It's Good For The Game

Good for the game? It's an admeme map edit! Now the old CentCom map is even more obsolete!

## Proof Of Testing

See included image.

## Changelog

:cl:
add: Centcom Administration has moved to the Interlink
/:cl:

### CODE REVIEW

**Comment by ReturnToZender** [comment]
If this gets merged before #1003, I'll add it to the new automapper file and sort out the differences

**Comment by IgiariValkyr** [comment]
Not sure why it's erroring on the integration tests for maps. Shouldn't really matter considering it doesn't even touch those map files anyways. Something about "cat: ci_test/data/logs/ci/clean_run.lk: No such file or directory".

**Comment by YakumoChen** [comment]
/shrug

Doesn't hurt, but it is inaccessible except on round end, and Centcom ghost roles still spawn on the "old" Centcomm Z, so that tends to be where admins spawn as NT roles.

**Comment by IgiariValkyr** [comment]
Current linter fails do not look like my fault. A new runtime and something about killer tomatoes. Someone rerun them and it'll be fine. I swear.

**Comment by YakumoChen** [comment]
You can rerun them from the git client but the only failing test isn't required anyway

**Review by Majkl-J — APPROVED** [review]
sex

**Comment by StrangeWeirdKitten** [comment]
Looks good.

**Pull request merged**
