### PR TITLE
Fixes Loadout Laptops

### PR DESCRIPTION
**Pull request by ShamanSliph**
## About The Pull Request
The Loadout Laptop now spawns in closed so it can fit into your bag. 

## Changelog

:cl:
fix: Modular Laptops can properly be used as loadout items
/:cl:

### CODE REVIEW

**Comment by Cyprex** [comment]
Could you instead PR this to upstream Skyrat?

**Comment by ShamanSliph** [comment]
The laptop fix was already PR' there. Thought I sent the skub changes over
there, but I seem to have forgotten to.

I'll do that today.

https://github.com/Skyrat-SS13/Skyrat-tg/pull/19624

**Comment by ShamanSliph** [comment]
For sanity, and because it was a stupid thing todo. Removed the Skub parts, and will PR them later.

**Comment by Cyprex** [comment]
We can testmerge this if you wish, but I intend to pull skyrat master soon(tm) so I see no reason to fullmerge this

**Comment by ShamanSliph** [comment]
if its super soon I can just close the PR, if not, It might not hurt to have it test merged so people can spawn with laptops till the skyrat pull happens.

**Comment by ShamanSliph** [comment]
This fix was included in the Skyrat Pull. Closing this PR now.

**Pull request closed without merging**
