### PR TITLE
You can now milk mothroaches for moth milk

### PR DESCRIPTION
**Pull request by nikothedude**
## About The Pull Request

Title.

## Why It's Good For The Game

I stared into the abyss, and it stared back.

For real though, theres no in-lore source of moth milk. To avoid the unholy suggestion (oily and salty? oh god), we should probably put it on an animal to avoid thinking we're marketing moth... _stuff_

## Changelog

:cl:
add: Mothroaches can now be milked for moth milk
/:cl:

### CODE REVIEW

**Comment by ReturnToZender** [comment]
speedmerge

**Comment by xXPawnStarrXx** [comment]
I hate this... 👍

**Review by projectkepler-ru — COMMENTED** [review]
Please add more to "why it's good for the game" before I crucify you.
What even is moth milk

**Comment by lessthnthree** [comment]
> Please add more to "why it's good for the game" before I crucify you. What even is moth milk

Exactly what you think.

```
/datum/reagent/consumable/moth_milk
	name = "Moth Milk"
	description = "Whoever thought that milking moths is a good idea was totally wrong. Is it even milk?"
	color = "#F0E9DA" // rgb: 240, 233, 218
	taste_description = "salty and oily substance"
```

**Comment by projectkepler-ru** [comment]
> > Please add more to "why it's good for the game" before I crucify you. What even is moth milk
> 
> Exactly what you think.
> 
> ```
> /datum/reagent/consumable/moth_milk
> 	name = "Moth Milk"
> 	description = "Whoever thought that milking moths is a good idea was totally wrong. Is it even milk?"
> 	color = "#F0E9DA" // rgb: 240, 233, 218
> 	taste_description = "salty and oily substance"
> ```

what in the fuck

**Comment by nikothedude** [comment]
> > > Please add more to "why it's good for the game" before I crucify you. What even is moth milk
> > 
> > 
> > Exactly what you think.
> > ```
> > /datum/reagent/consumable/moth_milk
> > 	name = "Moth Milk"
> > 	description = "Whoever thought that milking moths is a good idea was totally wrong. Is it even milk?"
> > 	color = "#F0E9DA" // rgb: 240, 233, 218
> > 	taste_description = "salty and oily substance"
> > ```
> 
> what in the fuck

i dont actually know why but posts from youa rent triggering notifications but yeah ill add a reason to add this

**Review by projectkepler-ru — APPROVED** [review]

**Pull request merged**
