### PR TITLE
Not doing portals no longer kills the dragon

### PR DESCRIPTION
**Pull request by Arturlang**
## About The Pull Request
When the dragon runs out of time to make a rift, instead of deleting the dragon, they are given the dragon depression movespeed debuff.

## Why It's Good For The Game
You are forced to get into full on combat with everyone or be literally deleted, this should give people a chance to RP as dragon, with dragon

## Proof Of Testing
Tested and it confirmed that it did not break the victory condition

## Changelog

:cl:
del: Dragon no longer gets deleted if you don't do rifts, instead you are given dragon depression, which slows you down heavily.
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
I think this is just a little short-sighted. 

The portals force the dragon to actually hunker down somewhere and do an objective as opposed to them just flying around and destroying all the windows and walls. 

Instead of flat-out deleting the dragon, it should impose a running penalty, I believe, such as ticking down their health to a cap of 50%, for example (as a really Conservative penalty)

**Comment by Arturlang** [comment]
> I think this is just a little short-sighted.
> 
> The portals force the dragon to actually hunker down somewhere and do an objective as opposed to them just flying around and destroying all the windows and walls.
> 
> Instead of flat-out deleting the dragon, it should impose a running penalty, I believe, such as ticking down their health to a cap of 50%, for example (as a really Conservative penalty) that also gets undone when they make a portal as they are supposed to.
> 
> I'm all for the idea of this PR bit there should be an incentive to not just do the opposite no-RP station grief.

Hmm, I'd instead just give them the dragon depression slowdown that they get from loosing a portal if they don't do it in time, which gets removed when they make a portal.

**Comment by YakumoChen** [comment]
As long as they have some dissuasion from just griefing with no timer, yeah.

**Comment by Arturlang** [comment]
> As long as they have some dissuasion from just griefing with no timer, yeah.

Suggestions implemented, thanks!

**Pull request merged**
