### PR TITLE
disables sloth ruin

### PR DESCRIPTION
**Pull request by sippykot**
## About The Pull Request
Disables sloth ruin using the blacklist

Should work unless the blacklist itself is broken, pretty sure Nova did it already

## Why It's Good For The Game
The sloth/orange ruin is pointless, boring, big, obstacle to navigation, and hogs space where other stuff could spawn.

## Proof Of Testing
ehhhh, if it doesnt work that would mean that the whole blacklist is broken somehow

## Changelog

:cl:
del: disables sloth ruin
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
This won't do anything, it has to be edited on the server box

**Comment by sippykot** [comment]
> This won't do anything, it has to be edited on the server box
> 
> > The sloth/orange ruin is pointless, boring, big, obstacle to navigation, and hogs space where other stuff could spawn.
> 
> That's literally the point of the ruin though?

it literally just hogs space and gets in the way - if the point of something is to be annoying and not even in a funny way, that's just an extra argument for it to not be there

**Comment by YakumoChen** [comment]
Take that up with a maintainer with box access then, but again, this PR doesn't accomplish what you think it will

Not all ruins have to be worthwhile however

**Comment by sippykot** [comment]
> Take that up with a maintainer with box access then, but again, this PR doesn't accomplish what you think it will
> 
> Not all ruins have to be worthwhile however

nova disabled it a while ago and it went well
i have no clue what we gain from keeping it
i cant think of any other lava or ice ruin that is just effectively a huge solid wall with 0 actual content

**Comment by IgiariValkyr** [comment]
While I do agree that it doesn't add anything to the server, this will have to go through the server box. Config changes here don't affect the server box itself. I was told this myself by Sharkening for my Lizard Gas PR. So try to convince them to get rid of the waste of space.

**Comment by sippykot** [comment]
> While I do agree that it doesn't add anything to the server, this will have to go through the server box. Config changes here don't affect the server box itself. I was told this myself by Sharkening for my Lizard Gas PR. So try to convince them to get rid of the waste of space.

damn...

**Comment by Odairu** [comment]
> > While I do agree that it doesn't add anything to the server, this will have to go through the server box. Config changes here don't affect the server box itself. I was told this myself by Sharkening for my Lizard Gas PR. So try to convince them to get rid of the waste of space.
> 
> damn...

You can just make a PR to tje config repo

**Comment by Majkl-J** [comment]
Yeah this should be done on the config repo like K3 said

**Pull request closed without merging**
