### PR TITLE
Removes roundstart ore silos

### PR DESCRIPTION
**Pull request by NullDagaf**
## About The Pull Request

Removes roundstart ore silos, moves the ore silo research behind advanced bluespace storage tech. The newly created empty space in the vault was making me depressed, so I added a trophy case in the silo's place. The trophies are as follows:

An used-up ~~plasma fist~~ sleeping carp scroll for Delta,
An used-up fireball spell-book for Void Raptor,
An used-up (see a pattern?) holo-parasite injector for Icebox,
And an used-up e-sword arm implant autosurgeon for Meta.

## Why It's Good For The Game

As a little history lesson, in ye-olden days, cargo used to not have ore silos at all. They had to manually distribute materials across the station, as well as handle which department got what and how much. This PR seeks to bring back that aspect of resource management that cargo hadn't had for a long while now.

As well as practically forcing inter-departamental interactions (and being a source of conflict when X department doesn't get enough resources/cargo decides this one particular department doesn't deserve any), it heavily guts the strategy of pirates rushing the vault/engineering techfab and siphoning all materials for an easy win. Also as a bonus, it gives matter bin upgrades a reason to exist (they increase the material holding size of techfabs which is completely nullified by ore silo's existence).

## Changelog

:cl:
balance: removes roundstart ore silos, moves ore silos behind advanced bluespace storage tech
/:cl:

### CODE REVIEW

**Comment by MayumiBun** [comment]
As i said before. This is a poor idea that will just make shit annoying and slow for little to no good reason imo.

**Comment by SingingSpock** [comment]
This is a horrible idea for all the many, many reasons listed in the suggestion thread. To copy/paste my summary from there: Having to manually haul each piece of material everywhere was literally nothing but a time drag with nothing interesting going on. "Pack mule" is not interesting gameplay. It also always led to certain departments _cough_ roboticists _cough_ swiping up disproportionate amounts of ores early on and leaving the rest of the station to starve.

**Comment by NullDagaf** [comment]
Replaced the plasma fist scroll with a sleeping carp one.

**Comment by toastywaffelz** [comment]
No. I do not want this to be a Death Stranding simulator.

**Comment by Serxule** [comment]
fun fact: forcing interaction does the opposite of what people want, and if anything makes the station more hostile towards eachother

**Comment by KathrinBailey** [comment]
This was tried on Skyrat to universal disapproval and hatred.

**Comment by NullDagaf** [comment]
> This was tried on Skyrat to universal disapproval and hatred.

Kids will whine when you take away their toys, yes.

**Pull request closed without merging**
