### PR TITLE
Refurbishes Derelict Tradepost ruin

### PR DESCRIPTION
**Pull request by ChromeFoxxity**
### Second refreshed ruin I've tried doing.

This PR only changes the full on design of the ruin, while not changing the layout. The only massive changes that might be of primary note would be the loot changes. Ranging to more corpses with ID's, to more two more empty magazines. As well as a new Bridge Officer's corpse in the control room. The bigger changes are to just add to the fluff of things, giving more of a backstory on the events that occured. Either way, it makes the station look better, and more realistic. 

It also makes more classic Private Security corpses with ranks, and mindshields. (giving a corpse a mindshield means almost nothing unless you are that in need of one, let's be fair here, and also makes sense since they're CentCom staff.)

There's also a Bridge Officer, (The leading officer of the tradepost) in the Control Room with all the primary control consoles, including some money that they have siphoned that is lootable.

### Credit to the original map maker. 

Old look.
image

New look.
image

## Why It's Good For The Game

As well as before, this means almost nothing other than when people decide to adventure space, or an event is hosted here. Other than that, this is just purely design, to update something that looks so out of place, while also being possibly a good spot for RP, or something of an event. Possibly.

## Proof Of Testing

image

## Changelog

:cl:
add: Refurbishes new Private Security, and Bridge Officer uniforms, and redesigns the Derelict Tradepost ruin.
/:cl:

### CODE REVIEW

**Comment by Cyprex** [comment]
Is this your own original design or is this(or parts of it) from another server?

**Comment by ChromeFoxxity** [comment]
> Is this your own original design or is this(or parts of it) from another server?

It's my own design, built from square one, and fluffed out by me. However, it's designed to keep the layout of the original ruin as close as I can make it.

**Comment by ReturnToZender** [comment]
I... don't really like the new ruin.

**Comment by ReturnToZender** [comment]
> > I... don't really like the new ruin. Doesn't visually seem better.
> 
> I'm.. Sorry, what? It's modernized. More set in our times. Unlike the old version, which is boxy, empty, and just has bland flooring. In this, I make story, give flooring details, add more rooms for staff to have used, etcetera. I also add windows, since the place just felt really suffocating. Either way, it is meant to be better.

Where's the green part from the old version?

**Comment by ChromeFoxxity** [comment]
> > > I... don't really like the new ruin. Doesn't visually seem better.
> > 
> > 
> > I'm.. Sorry, what? It's modernized. More set in our times. Unlike the old version, which is boxy, empty, and just has bland flooring. In this, I make story, give flooring details, add more rooms for staff to have used, etcetera. I also add windows, since the place just felt really suffocating. Either way, it is meant to be better.
> 
> Where's the green part from the old version?

Unfortunately I had a hard time understanding how half of that part of the station could just be replaced by the previous creatures. Nor did I not really know how they worked, the previous ruin had creatures that somehow repopulate, and contained people in pods? I have no clue how that worked. So I did it with xenomorphs instead, so I could make a story, so people have a hard time getting the good stuff.

**Comment by YakumoChen** [comment]
> Ruin with unique enemies replaced with enemy mob and its own environmental story found in half the ruins in space

>Ruin has all its storytelling done in written notes instead of the environment that is also an identical story to every other xenomorph-infested ruin

>loot includes command-level IDs and mindshields and other things to give antags/powergamers a field day if they space explore

**Comment by ChromeFoxxity** [comment]
> > Ruin with unique enemies and its own environmental story replaced with enemy mob  found in half the ruins in space
> 
> > Ruin has all its storytelling done in written notes instead of the environment that is also an identical story to every other xenomorph-infested ruin
> 
> > loot includes command-level IDs and mindshields and other things to give antags/powergamers a field day if they space explore

1. I have no idea what the Creatures even are like, I have no clue what to do with them in regards to making the story.

2. Notes is really the only way to tell a story, aside from leaving it to the player to figure out what the events were without said notes. Which might be more mysterious, but still.

3. The said command-level ID's have only CentCom access, which in result wouldn't change anything game-play wise. As Private Security already had CentCom access. (Bridge officer is also only CentCom access.)

**Comment by YakumoChen** [comment]
>     1. I have no idea what the Creatures even are like, I have no clue what to do with them in regards to making the story.

Well based on the ruin you can probably infer what they are like just looking at the map, you're just changing the ruin to be "Xenos take over a thing ruin #37"

>     2. Notes is really the only way to tell a story, aside from leaving it to the player to figure out what the events were without said notes. Which might be more mysterious, but still.

I can make sense of most the entirety of the events of the ruin just looking at the map, that's what environmental storytelling is.

>     3. The said command-level ID's have only CentCom access, which in result wouldn't change anything game-play wise. As Private Security already had CentCom access. (Bridge officer is also only CentCom access.) As well as the Mindshields are IN THE CORPSES. Antags cannot take them out, and put it in themselves. That's not how that works. And the guns however, they were already there, but with the current threat within the ruin, would make it quite hard to get to said loot.

You can mindshield yourself from a corpse with a set of surgical tools and an implanter set, actually. Space ruins should also probably not be giving away silver IDs.

**Comment by ChromeFoxxity** [comment]
> > ```
> > 1. I have no idea what the Creatures even are like, I have no clue what to do with them in regards to making the story.
> > ```
> 
> Well based on the ruin you can probably infer what they are like just looking at the map, you're just changing the ruin to be "Xenos take over a thing ruin #37"
> 
> > ```
> > 2. Notes is really the only way to tell a story, aside from leaving it to the player to figure out what the events were without said notes. Which might be more mysterious, but still.
> > ```
> 
> I can make sense of most the entirety of the events of the ruin just looking at the map, that's what environmental storytelling is.
> 
> > ```
> > 3. The said command-level ID's have only CentCom access, which in result wouldn't change anything game-play wise. As Private Security already had CentCom access. (Bridge officer is also only CentCom access.) As well as the Mindshields are IN THE CORPSES. Antags cannot take them out, and put it in themselves. That's not how that works. And the guns however, they were already there, but with the current threat within the ruin, would make it quite hard to get to said loot.
> > ```
> 
> You can mindshield yourself from a corpse with a set of surgical tools and an implanter set, actually. Space ruins should also probably not be giving away silver IDs.

To be honest, I didn't know about the implanter set, to be honest. The silver ID's, I can probably agree with, but.. It's barely even a difference in the end, because you'd still need the HoP, or access to change the access in it. The only thing I don't want to give out is a CentCom ID. To be honest, chameleon ID's can already disguise as a silver ID. I dunno, it's just for the fluff of things. I don't think a Bridge Officer would just have an outright grey ID, they were the lead officer of the Tradepost.

**Comment by ChromeFoxxity** [comment]
And to be honest. Creatures are very weak, I don't see how the Tradepost security couldn't deal with the original creature they got in the crate beforehand. You can kill them in one laser shot. The Xenomorphs however, are much stronger. And more of a threat, and way better at defending the loot in the ruin. I know Xenomorphs are an unoriginal threat, and all. But Creatures just don't seem to be very strong at defending the stuff.

**Comment by YakumoChen** [comment]
All but one of the creatures are literally named "hatchling", of course they're weak. Its only one creature of the bunch that killed the crew to begin with. 

With only two guns in the original ruin, emptied of their rounds, it tells a hell of a lot of a story, especially if you have any amount of imagination.

The ruin is already iconic, its filled with a unique enemy, but you're removing all the charm.

**Comment by ChromeFoxxity** [comment]
> All but one of the creatures are literally named "hatchling", of course they're weak. Its only one creature of the bunch that killed the crew to begin with.
> 
> With only two guns in the original ruin, emptied of their rounds, it tells a hell of a lot of a story, especially if you have any amount of imagination.
> 
> The ruin is already iconic, its filled with a unique enemy, but you're removing all the charm.

Fine. I'll attempt to redesign it to be more iconic to the previous story.

**Comment by YakumoChen** [comment]
Maybe the fact that they died before they could reload their spare magazines is an environmental story clue?

**Comment by YakumoChen** [comment]
I recall there are two guns in the ruin, and one is loaded because the guard killed himself (as evidenced by the isolated body and single empty casing on the floor.

Maybe they didn't have the budget for more magazines, maybe the map would just be completely unbalanced if there were a load of them lying around.

**Comment by ChromeFoxxity** [comment]
Also, regarding the whole Mindshield, and Silver ID's. I'm just trying to be realistic with my loot. As this is Nanotrasen Private Security, they would have mindshields. I don't know why the corpses just lack them, as dying doesn't just delete it. I mean, it might upset the balance, but it makes it feel more.. Just ICly accurate? The Silver ID's is for the bridge officer, and the NT Private Security Sergeant. It feels right, somewhat.

The magazine thing, they wouldn't be loaded, they'd be empty. I don't think they'd be too much of a powergaming thing, as security is the only one with ammunition benches, and anyone caught with an M1911 would be charged for contraband (without a gun license.)

Also, the gun with the suicided guard is empty, it has no mag in it (coded to start with no mag).

**Comment by ChromeFoxxity** [comment]
If you'd like to continue conversing about this PR, I suggest chatting in the Dusty Mapping channel instead so this isn't buried in an arguement.

**Comment by ChromeFoxxity** [comment]
> All but one of the creatures are literally named "hatchling", of course they're weak. Its only one creature of the bunch that killed the crew to begin with.
> 
> With only two guns in the original ruin, emptied of their rounds, it tells a hell of a lot of a story, especially if you have any amount of imagination.
> 
> The ruin is already iconic, its filled with a unique enemy, but you're removing all the charm.

Also, the main creature that came from the crate is only 25 health higher, so they would also die in 2 laser shots. So uh.. I don't know what to say.

**Comment by YakumoChen** [comment]
I don't think a tiny little cargo dock in the middle of space needs an entire security contingent for starters, and probably not a commanding officer.

The only ruin that needs a lot of guns is ruins like the caravan battle one, which is also filled with very dangerous enemies guarding it.

**Comment by ChromeFoxxity** [comment]
> I don't think a tiny little cargo dock in the middle of space needs an entire security contingent for starters, and probably not a commanding officer.
> 
> The only ruin that needs a lot of guns is ruins like the caravan battle one, which is also filled with very dangerous enemies guarding it.

image

**Comment by ChromeFoxxity** [comment]
image

There. Would this be rather fitting? Removed most of the security corpses, there's only two spare empty mags, two empty m1911's, and one m1911 with a full mag. (Removed the gold-trimmed m1911 from the control room).

**Comment by YakumoChen** [comment]
I still prefer the original and its simple-yet-rich design and environmental story (the blood trails to pods, the burned-out walls showing how the creature can expand and move through the station, the single nest with all the creatures together instead of spread through the station) but at least its better than xenos now.

**Comment by ChromeFoxxity** [comment]
> I still prefer the original and its simple-yet-rich design and environmental story (the blood trails to pods, the burned-out walls showing how the creature can expand and move through the station, the single nest with all the creatures together instead of spread through the station) but at least its better than xenos now.

I know, I know. But to be honest, I still want them to be guarding the loot of the ruin, as there is some money you can obtain in the control room.

**Pull request closed without merging**
