### PR TITLE
Bangle Sprites & ONE Laser Sound

### PR DESCRIPTION
**Pull request by Offwrldr**
## About The Pull Request
An effort to diversify and enhance the sprites of Sec weaponry. See [this](https://github.com/Skyrat-SS13/Skyrat-tg/pull/23424#issuecomment-1722751802) for my extensive reasoning and breakdown of _why_ I believe this to be the correct course of action.

To clarify what's changed:

1. The Marksman Rifle
2. The LMG
3. The Carbine
4. The Battle Rifle
5. The Sindano
6. The Renoster

372653181-71647083-077c-4c57-848c-dcfddba96161

I have not tested this PR. **Through faith alone**, the sprites will prevail.

## Why It's Good For The Game
Because the original sprites all had the same silhouette and color-scheme and were in need of significant change.

## Proof Of Testing
I did no testing. Reference this:
image
Sprite-0003

## Changelog
This bounces off of [this.](https://github.com/Bubberstation/Bubberstation/pull/2168).

Finally added carbine sprite.

:cl: Bangle

image: added/modified/removed some icons or images

/:cl:

### CODE REVIEW

**Comment by Offwrldr** [comment]
Update: I have accidentally added another commit because I have no idea how Github works.

Added some Renamon parts. As far as I can tell, they play well.
fawfwafwafwafafawfa
imdadadadaage
Untsssssitled

Apologies for the addition without making another PR.

**Comment by Hotmud9** [comment]
image
suppressors aren't properly attached my OCD is fucking killing me AAAAAAAAAAAAAAAAA

**Comment by Offwrldr** [comment]
> image suppressors aren't properly attached my OCD is fucking killing me AAAAAAAAAAAAAAAAA

I will test it and see what I can do. Thanks for letting me know.

**Comment by Offwrldr** [comment]
image
It's now fixed.

**Comment by CEO-Of-Dogborg-Corp** [comment]
I really do not like the door sounds, they sound very out of place, door opening and closing is too loud, bolting it too quiet

**Review by lessthnthree — CHANGES_REQUESTED** [review]
Why are there nonmodular, undocumented changes to the airlock sounds. Was this a mistake? Please remove them.

**Review by lessthnthree — APPROVED** [review]

**Pull request merged**
