### PR TITLE
Logged out ghosts get sent back into the lobby

### PR DESCRIPTION
**Pull request by Majkl-J**
## About The Pull Request

See name.

This includes checking for configs, respawn bans, and logging!

## Why It's Good For The Game

There's so many annoying ghosts without clients. I was asked to do this then.\

This does not throw you back into the lobby if you have a linked body.

## Proof Of Testing

Testing done. Seems to work as of currently, still might need some extra TM to make sure

## Changelog

:cl:
add: Ghosts without clients get sent back into the menu after a while.
/:cl:

### CODE REVIEW

**Comment by ReturnToZender** [comment]
BASED

**Comment by nevimer** [comment]
exempt it for admins? It could get annoying. Maybe do a callback after 15 mins?

**Comment by Majkl-J** [comment]
> exempt it for admins? It could get annoying. Maybe do a callback after 15 mins? (I wrote this before reading the code) (I still think 15 is good… some routers take a while to restart / connection issues to resolve)

You could just go ahead and press observe again, but sure, 15 it is

**Comment by YakumoChen** [comment]
I was sent back to the lobby after dying and closing the game

**Comment by Majkl-J** [comment]
Untestmerged. I am going to bed, this has a very big oversight with not checking for linked bodies

**Pull request merged**
