### PR TITLE
Revert "Removes the Clown dogborg sprite."

### PR DESCRIPTION
**Pull request by Odairu**
Reverts Bubberstation/Bubberstation#1858

## Why its good for the game

the clown vale sprite is purposefully bad, its funny, its rare, its the honk shell. Plus its a dog borg and I like dog borgs don't touch my babies

### CODE REVIEW

**Comment by Swiftfeather** [comment]
The dogborg clown looks atrocious and that's kind of the point. It fits the dogborg aesthetic fine.

**Comment by Iamgoofball** [comment]
>The dogborg clown looks atrocious and that's kind of the point. It fits the dogborg aesthetic fine.

this is a terrible justification, we should not intentionally have bad sprites

if the clown dogborg actually used the clown color palette it'd be at least on the level of the other terrible sprites in this sprite-pack but it doesn't and it massively suffers for it

this is an affront to clowning and should remain removed until someone wants to actually sprite a better clownborg that's shaped like a dog

i think people can survive not being a dog with a vomit inducing color palette for all of the amount of time it takes moffington to commission a better sprite like he said he might do

**Comment by theselfish** [comment]
"Oh it's a clown it looks bad on purpose" isn't an excuse. 

The Clown sprite looks good, it's aged but it looks good. The actual Clown Borg look good.

The Clown Dogborg sprite is a sprite I genuinely have no idea what server would willingly accept it if they saw it. I doubt even the wild west days of SS13 would have accepted it.

It barely even looks like a Clown, it doesn't use the clown palette, it has no Clown shoes, no Giggles von Honkers and no Clown wig.

But again. The worst issue is the Dogborg looks ugly as sin, worse than the normal dogborgs which is quite an achievement to make.
353432916-ad843a77-77c7-435e-968a-69c166a63b16

**Comment by projectkepler-ru** [comment]
> The dogborg clown looks atrocious and that's kind of the point. It fits the dogborg aesthetic fine.

You really shouldn't have unlocked the comment

**Comment by Swiftfeather** [comment]
> > The dogborg clown looks atrocious and that's kind of the point. It fits the dogborg aesthetic fine.
> 
> You really shouldn't have unlocked the comment

you knew better than I did

**Pull request closed without merging**
