### PR TITLE
Uninverts the top left corner of the treatment center in Icebox medbay

### PR DESCRIPTION
**Pull request by Shroopy**
## About The Pull Request
Uninverts the top left corner of the treatment center in Icebox medbay.

I just moved walls, floors, machinery, tables, etc. around a little bit.

## Why It's Good For The Game
Restores working space to a room that needs it more than a hallway. Makes it possible to set up a proper stasis bed-operating table-operating computer workstation in that corner, if you so please.

## Proof Of Testing
image
I checked to make sure you can use the machinery I moved around. Everything is still accessible.

## Changelog

:cl:
qol: Uninverted the inverted corner of the Icebox medbay treatment center.
/:cl:

### CODE REVIEW

**Comment by Shroopy** [comment]
This probably should actually be done upstream huh

**Comment by Superhats** [comment]
You're missing the blue decal that wraps around the wall. This is game breaking.
image
image

**Comment by Majkl-J** [comment]
Take this upstream to tg. If they happen to deny it I will be happy to reopen this and help you get it working as an automapper thing

**Comment by Shroopy** [comment]
Created an upstream PR, waiting to see how it goes.

**Pull request closed without merging**
