### PR TITLE
Disables Radiation Nebulas from occurring because something is seriously wrong with them.

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Disables Radiation Nebulas from occurring because something is seriously wrong with them.

## Why It's Good For The Game

Something seems to be lagging the hell out of the server every time this trait occurs. Radiation storms tend to do it because they have to set the weather to every single station area, which causes intense lag.

Ignoring the lag, it's extremely painful to deal with and unfun that you have to go into maints every few minutes. Since our pop is usually high, medbay usually has to deal with 10+ people who got irritated because they didn't see the messages or the lag causes them to get fucked.

## Proof Of Testing

Untested. it should work.

## Changelog

:cl: BurgerBB
del: Disables Radiation Nebulas from occurring
/:cl:

### CODE REVIEW

**Comment by IgiariValkyr** [comment]
I mean. I did say in round in OOC i was doing the storms on purpose on random chance because we were in a rad nebula. But the actual lag behind it is something that should be looked into, yes.

**Review by Majkl-J — CHANGES_REQUESTED** [review]
Disable radstorms in general in the storyteller event overrides

**Comment by StrangeWeirdKitten** [comment]
I'll test it out later.

**Comment by nevimer** [comment]
is this still true?

**Comment by BurgerLUA** [comment]
> is this still true?

Not sure tbh.

**Comment by StrangeWeirdKitten** [comment]
Gameplay reason, the trait is fine and rather uncommon. I rarely see any sort of radiation storm. Lag reasons, I need to see an actual profiler (on the server) if this is the case. So if I see it, I'll look at it and try to get it fixed before outright removing it.

**Pull request closed without merging**
