### PR TITLE
Removes security comms and access from blueshield

### PR DESCRIPTION
**Pull request by StrangeWeirdKitten**
## About The Pull Request

* Removes blueshield security comms
* Removes blueshield security accesss
* Places cargo into minimal access. (which means they have access) because either all basic department access is ok, or none of it is ok. I have no clue why skyrat did not give basic cargo access, but we'll try it

## Why It's Good For The Game

I spoke to a lot of admins and the other maintainers about this.

Every time I see the term redshield, I get a hernia. Especially when a blueshield is just doing security work. To be honest, if you don't want someone to do security work, you don't give them access to their comms and their doors. It's bwoink bait. While valid hunting is not alright for blueshield, the fundimental action of removing them off security comms and access will make this task a far more concious decision for the player. You're no longer going to have second by second snapshots of every threat and their movement.

You don't need security access, or comms, to do your job. You have a pinpointer and you're standing next to the person who can tell you everything you need to know. If there's a communication issue between command and security, and heads die, that's the consiquences when communication breaks down. It's not necisiarrily a bad thing. Command, 

Also, I threw in a bone with the cargo access. We'll try it, and it can always be adjusted.

## Proof Of Testing

image

image

## Changelog

:cl:
balance: Blueshield no longer starts with security comms or access. But they now have basic cargo access
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
Basic cargo access means they can order from the console, which is a lot of what makes blueshield powergaming a problem in many rounds

Also take away their budget access

**Review by projectkepler-ru — CHANGES_REQUESTED** [review]
If you want to fix blueshield access, we need to actually ensure they have basic access to every department, + robotic access incase of robotic head of staff. Admittedly this mean every department EXCEPT HoS, who will have to be intentionally excluded
Please do ensure they get a bonus access to security and holding cell for skeleton crew. as this is actually  going to be important.


We also need to actually fix their starting weapon but that's out of the scope of this PR and more of a problem for future calvin to worry about.

**Comment by Moostard** [comment]
I do not play that role, but...
I believe that having access to sec comms is important for the job. You can hear that "nightmare is in science" for example and move to stick to the RD.
Sec access is useful for reloading and grabbing more gear from the lathe as blueshields do it often.

"Redshield" is usually salt infused word thrown by someone who recently got sent to dchat.
Im not joking.
People like to blame blueshields as an excuse why their unstoppable OC died, even if they did not do anything.
Pretty sure such players will thank you for this PR, unfortunately.

**Comment by StrangeWeirdKitten** [comment]
> If you want to fix blueshield access, we need to actually ensure they have basic access to every department, + robotic access incase of robotic head of staff. Admittedly this mean every department EXCEPT HoS, who will have to be intentionally excluded 

It has basic access already unless I'm missing something. They don't have security access because tbh, the HoS is the least person who needs defending when that is mostly on security. I'll settle for skeleton crew though, that seems reasonable.

I'm not giving robotics access because that includes much more than just the door. They can break a window if there's an extremely dire need to get into robotics.

> Alongside giving them a special ID card that cannot accept command related access trim

Out of scope for now.

**Comment by ThinkArbies** [comment]
> Basic cargo access means they can order from the console, which is a lot of what makes blueshield powergaming a problem in many rounds
> 
> Also take away their budget access

You can't suggest taking away the budget access just because you were salty admins in the form of CC told you that the Blueshield is allowed to use the Command budget.

**Comment by Edgar-Allan-ShitPoest** [comment]
Honestly the amount people complain and try to rework blueshield you'd think redshielding is happening every round. Fact is it isn't. 
Fundamentally however, it is a mechanically oriented role expected to engage with antagonists under specific circumstances. Not only does this rework strip it of vital means of actually doing the job it was intended to - it actively punishes the blueshield role for filling the niche it was made to fill. 
Redshielding is honest to god not as big as a problem as maintainers and coders scream and insist it is. Feedback from nearly every poll and survey on the topic consistently shows that most people don't think that redshielding is as widespread a problem as all these PRs insist it is, yet people still try to shove them through. 

Please take a step back and leave blueshield alone for a few months, because with the constant looming uncertainty hanging over this role, it's actively lowering the quality of its playerpool and driving off people who play the role well and in good faith. I genuinely hope zender puts a blanket freeze on all blueshield PRs soon.

**Comment by IgiariValkyr** [comment]
### As an admin who was first for the blueshield changes, I'm doubling back on it and saying leave it alone.

The players are right and we should be policing it more as admins, rather than with code.

- If the blueshield wants to use the command budget to buy things to protect heads of staff and extra medical supplies if there's no medical staff? Let them. That budget is given access to them because they're employed by Centcom. Not security, not medical, not engineering, and certainly not cargo (even though all the Centcom ERT IDs when used on station pull from the cargo budget).
- Security comms, while being the number one complaint for "this is why they redshielded", are also vital to the job. Not every blueshield runs around with their pinpointer in their pocket constantly on. Sec comms would be an immediate way to find a head of staff being attacked, since it will likely hit there before command comms if at all. And if the criminal gets away, the blueshield can communicate it directly to security without having to walk all the way to the department and tapping on the window to hope there's an officer even inside.
- The ID Console self-access is actually in the Admin Log in our chatbox.  We can see who's doing what, and check their ID directly if they're just giving themselves all access, or if they're giving themselves just that little bit extra to perform their job easier.

**Comment by ReturnToZender** [comment]
> ## _If TG of all servers don't have to edit the blueshield code because of stuff like this, clearly it's us who are in the wrong. Not the code._

I think it's noting that TG doesn't have Blueshields

**Comment by IgiariValkyr** [comment]
> > ## _If TG of all servers don't have to edit the blueshield code because of stuff like this, clearly it's us who are in the wrong. Not the code._
> 
> I think it's worth noting that TG doesn't have Blueshields

Ok. Skyrat. Whatever. Point still stands that if they aren't neutering it like a puppy on the Price is Right, then we're the ones in the wrong with how we handle the incidents.

**Comment by Odairu** [comment]
> > > ## _If TG of all servers don't have to edit the blueshield code because of stuff like this, clearly it's us who are in the wrong. Not the code._
> > 
> > 
> > I think it's worth noting that TG doesn't have Blueshields
> 
> Ok. Skyrat. Whatever. Point still stands that if they aren't neutering it like a puppy on the Price is Right, then we're the ones in the wrong with how we handle the incidents.

you're also talking about the server known for having *terrible* balance as a justification for why balance isn't necessary. Apologies if I don't trust the server that added bloodcrawl and marked one to miner loot to know what would be balanced and healthy game design for a blueshield.

**Comment by Tupinambis** [comment]
This PR does literally nothing to address "redshielding" (it's validhunting, just call it validhunting) and just makes it harder for a blueshield to do their job. It's functionally just a nerf.

As someone who has been on all sides of this problem, it's literally just a behavioral issue. Blueshields are supposed to protect command and command staff, some decide to chase after the criminals instead of actually guarding the people and areas they're supposed to. Not having sec comms or access doesn't do anything to discourage this, if they want to validhunt they will. Usually what happens is a command member or their department is threatened, and a bad blueshield will use this as an excuse to chase the threat all around even if it means abandoning the person they are supposed to defend. 

Sec access and comms are important because the role should be "in the know" and have reasonably easy access to gear that assists them in protecting command staff. 

Ultimately blueshields are as much as RP role as every other role, so if they're not playing the role of being a guardian of command and are just chasing criminals instead, staff should handle that as the lrp behavior it is instead of pring weird non solutions like this.

**Comment by projectkepler-ru** [comment]
> Bigger issue is their silver ID that they can edit their own accesses from and having command budget.

already known

**Comment by projectkepler-ru** [comment]
> ### As an admin who was first for the blueshield changes, I'm doubling back on it and saying leave it alone.
> The players are right and we should be policing it more as admins, rather than with code.
> 
> * If the blueshield wants to use the command budget to buy things to protect heads of staff and extra medical supplies if there's no medical staff? Let them. That budget is given access to them because they're employed by Centcom. Not security, not medical, not engineering, and certainly not cargo (even though all the Centcom ERT IDs when used on station pull from the cargo budget).
> * Security comms, while being the number one complaint for "this is why they redshielded", are also vital to the job. Not every blueshield runs around with their pinpointer in their pocket constantly on. Sec comms would be an immediate way to find a head of staff being attacked, since it will likely hit there before command comms if at all. And if the criminal gets away, the blueshield can communicate it directly to security without having to walk all the way to the department and tapping on the window to hope there's an officer even inside.
> * The ID Console self-access is actually in the Admin Log in our chatbox.  We can see who's doing what, and check their ID directly if they're just giving themselves all access, or if they're giving themselves just that little bit extra to perform their job easier.
> 
> ## _If TG of all servers don't have to edit the blueshield code because of stuff like this, clearly it's us who are in the wrong. Not the code._

blueshield was first and foremost a skyrat thing, still is.

**Comment by projectkepler-ru** [comment]
> > > > ## _If TG of all servers don't have to edit the blueshield code because of stuff like this, clearly it's us who are in the wrong. Not the code._
> > > 
> > > 
> > > I think it's worth noting that TG doesn't have Blueshields
> > 
> > 
> > Ok. Skyrat. Whatever. Point still stands that if they aren't neutering it like a puppy on the Price is Right, then we're the ones in the wrong with how we handle the incidents.
> 
> If my opinion is relevant (it isn't), I do think this is a good change, but it's far too late and it's not like Redshielding is much of an issue at all these days. If it were done at the time of my original works, I'd understand, but... just repeatedly nerfing a role over time means no one's gonna play it. Sorry, gotta do it right the first time.
> 
> I do also agree that bad players need to be dealt with, but I don't even think there are that many bad players. There's literally just one, at most, that is ever discussed, that's John Redshield. The only one.

i have like three ideas to go with bs rn

**Comment by projectkepler-ru** [comment]
> This PR does literally nothing to address "redshielding" (it's validhunting, just call it validhunting) and just makes it harder for a blueshield to do their job. It's functionally just a nerf.
> 
> As someone who has been on all sides of this problem, it's literally just a behavioral issue. Blueshields are supposed to protect command and command staff, some decide to chase after the criminals instead of actually guarding the people and areas they're supposed to. Not having sec comms or access doesn't do anything to discourage this, if they want to validhunt they will. Usually what happens is a command member or their department is threatened, and a bad blueshield will use this as an excuse to chase the threat all around even if it means abandoning the person they are supposed to defend.
> 
> Sec access and comms are important because the role should be "in the know" and have reasonably easy access to gear that assists them in protecting command staff.
> 
> Ultimately blueshields are as much as RP role as every other role, so if they're not playing the role of being a guardian of command and are just chasing criminals instead, staff should handle that as the lrp behavior it is instead of pring weird non solutions like this.

i willl think about it, the access should stay but we could lose the comm.

**Comment by StrangeWeirdKitten** [comment]
The reason I bring up redshield is not entirely to say someone is a validhunter, but a fundimental issue when it comes to a roleplay role that's pseudo security. The line becomes incredibly vague, Tunnel vision exists. It's extremely easy to call someone a bad player and ban them. It's easy to call people who ahelp whiney. The lines get extremely murky, especially when admins get involved. Granted, a lot toned down when we peered into their AA centcomm IDs, and we have coming changes to blueshield gear from upstream that @projectkepler-ru made. But the solution being admin involvement isn't something that should be entirely supported and you shouldn't want that, as a player, because ss13 is an inherently complicated game. Picture this:

* Danger in science. an antag. Security gets involved, as they should, and the RD needs protection
* Antag gets in a fight with security. Of course the RD and antag will be involved.
* Antag runs. Blueshield is tunnel visioned
* Labled a valid hunter, has to defend themselves in a ticket. I don't find our admins bad, but they're human. They are not a hivemind. It's not always going to end with a "You're good". 

>If my opinion is relevant (it isn't), I do think this is a good change, but it's far too late and it's not like Redshielding is much of an issue at all these days. If it were done at the time of my original works, I'd understand, but... just repeatedly nerfing a role over time means no one's gonna play it. Sorry, gotta do it right the first time.
>
>I do also agree that bad players need to be dealt with, but I don't even think there are that many bad players. There's literally just one, at most, that is ever discussed, that's John Redshield. The only one.

Sunk cost fallicy. Unfortinately this is an issue across the entire role where every gradual adjustment to tone them down to what they were.

I was writing this and Burger dropped his PR. So imo. #1345

**Comment by StrangeWeirdKitten** [comment]
Burger told me my PR was supposed to be working along side his.

**Comment by projectkepler-ru** [comment]
It's not a matter of sunk cost fallacy, blueshield has become the intergral part of skyrat/bubber experience whether or not we realised it. It's a role that's expected because, it make sense. it's a role to protect a head of staff. when we did our meme PR we learned that one of the *actually* problematic aspect of playing blueshield was that you had to actually think of who you wanna protect,, which isn't too bad, you can decide to protect the most obvious choice being HoP, CE and CMO who don't have much in term of personal defense against majority of antag. 

I can see many reason for why BS should stay, there's many proposed change and my end goal here is to somehow appease both our direction that we want the BS to take while ensuring we aren't removing BS abilities to protect the head of staff. Of course, we have to compromise somewhere. The direction I want with the blueshield was always to give them agency to actually choose , and willingly choose to do certain thing. It'd be perhaps nice if I get to finally finish my BS Kit idea where you pick between being a more combative Blueshield vs Supportive Blueshield, allowing people like, me and rui to choose that we want to be fighting antag to protect our staff while allowing people like gavla who want to focus more on the support aspect to be a more advaned paramedic.

**Pull request closed without merging**
