### PR TITLE
Revert "Makes the christmas tree safe" (Please use broken gear responsibly)

### PR DESCRIPTION
**Pull request by StrangeWeirdKitten**
Reverts Bubberstation/Bubberstation#912

Please be nice, I'm feeling festive :)

### CODE REVIEW

**Comment by lessthnthree** [comment]
The one thing faster than Santa's sleigh: putting this into TM.

**Comment by NanoCats** [comment]
Praise be

**Comment by SteamStucKobold** [comment]
How much work would it be to have an alert/log whenever one of these not-safe items is created?  Mostly just for easier smiting of the irresponsible

**Comment by StrangeWeirdKitten** [comment]
> How much work would it be to have an alert/log whenever one of these not-safe items is created?  Mostly just for easier smiting of the irresponsible

Too much for me to care about. Mostly because I don't have a list of every admin spawned item in my head and I'd have to probably add to it as I see it.

**Comment by SteamStucKobold** [comment]
> Too much for me to care about. Mostly because I don't have a list of every admin spawned item in my head and I'd have to probably add to it as I see it.

Gotcha, gotcha.
Anyways, considering the hilarity that ensued from Fido Holmes getting an instakill rifle from Santa Claus last night, I fully support this change

**Comment by MajManatee** [comment]
It has only ever brought fun to the server. No reason not to let this stay as a permanent feature unless you HATE CHRISTMAS CHEER

**Comment by NanoCats** [comment]
I know this is a lot to ask but there is one change I'd like to make to the Christmas tree loot list.

Blacklist two things

1. Sheets of paper
2. Random modular computer parts that do nothing and nobody knows what they are

**Pull request merged**
