### PR TITLE
Makes all high heels clack like the dominant ones

### PR DESCRIPTION
**Pull request by CydiaButt13**
only the fancy ones clack rn, not sure why, working on it.

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
sound: added/modified/removed audio or sound effects
image: added/modified/removed some icons or images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Review by projectkepler-ru — CHANGES_REQUESTED** [review]
this is good, now do it on skyrat

**Comment by SovietSpaghetti** [comment]
If they're all gonna clack, make it a lot quieter. The dominant/latex heels are really loud

**Comment by StrangeWeirdKitten** [comment]
@CydiaButt13 did you do it on skyrat? It'll be fine to make it modular here and merge it.

**Comment by StrangeWeirdKitten** [comment]
Stale. Feel free to reopen.

**Pull request closed without merging**
