### PR TITLE
Adds a new Precision Ion Rifle for Security

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

image

Adds a new Precision Ion Rifle for Security. The precision ion rifle shoots 3 round bursts of Ion shot that has less radius than the ion rifle. It comes with a built-in scope and burst fire selector. This can be found in the armory alongside the existing ion rifle, as well as ordered in packs of 2 via cargo. The rifle can shoot about 15 shots before running out.

## Why It's Good For The Game

The current ion rifle has a problem where shooting it almost always results in collateral damage due to the AoE impact attack. This can be really bad in Wireweed situations as the EMP will almost always hit an air alarm, fucking over everyone else in the area.

Instead of nerfing the existing Ion Rifle, I decided to add a new Ion Rifle variant that solves that issue while also still being deadly to use.

Sprites were by me, combining a sprite I made previously with the style of the existing Ion Rifle.
Sound was by me, editing the emitter sound to be shorter and sound a little different.

## Proof Of Testing

image

## Changelog

:cl: BurgerBB
add: Adds a new Precision Ion Rifle for Security. The precision ion rifle shoots 3 round bursts of Ion shot that has less radius than the ion rifle. It comes with a built-in scope and burst fire selector. This can be found in the armory alongside the existing ion rifle, as well as ordered in packs of 2 via cargo. The rifle can shoot about 15 shots before running out.
/:cl:

### CODE REVIEW

**Comment by Majkl-J** [comment]
> Ahem, unfortunately the ion rifle no longer has a 3x3 due to being nerfed ages ago so it has been dogshit for a while. The precision rifle would end up being a better ion rifle due to the cell size.

It is 3x3 however the emp effect only moves through emp susceptible things so it may look like a 1x1 if it hits a lone human with nothing else nearby

**Comment by GoreDem** [comment]
so much for player clarity

**Review by StrangeWeirdKitten — CHANGES_REQUESTED** [review]
A 3 round burst heavy EMP is a bit too strong due to how powerful EMPs are in general. It should instead be light EMP. I'm fine with this alongside a 3x3 armory ion rifle.

**Comment by BurgerLUA** [comment]
> A 3 round burst heavy EMP is a bit too strong due to how powerful EMPs are in general. It should instead be light EMP. I'm fine with this alongside a 3x3 armory ion rifle.

I tested it against a borg, and it is about 13 shots to kill a borg.

**Comment by StrangeWeirdKitten** [comment]
The shots to kill a borg are a bit meaningless when HEAVY ions give a 16 second instant and hard stun to borgs. It also severely disables synthetic crew in ~ four shots from full health with organ damage applied. Putting it to a three burst light ion makes it far from useless.

**Comment by BurgerLUA** [comment]
> The shots to kill a borg are a bit meaningless when HEAVY ions give a 16 second instant and hard stun to borgs. It also severely disables synthetic crew in ~ four shots from full health with organ damage applied. Putting it to a three burst light ion makes it far from useless.

Not really possible to do unless you want me to do snowflake code. A range 0 EMP pulse will have a 50% chance to be a heavy, and 50% chance to be a light.

https://github.com/Bubberstation/Bubberstation/blob/2dde73e18bb2be8b5364f4ab726f5e30eb45028c/code/game/objects/empulse.dm#L23-L31

**Comment by StrangeWeirdKitten** [comment]
You can add a null check in the for() loop regarding heavy_range and make a new EMP projectile that runs null through the heavy EMP argument on the proc.

**Comment by StrangeWeirdKitten** [comment]
Alternatively we can TM it as a burst of two. I am mostly caring for keeping the TTK for synths not as high. (I love arbitrary randomness)

**Pull request closed without merging**
