### PR TITLE
New Loading Screen

### PR DESCRIPTION
**Pull request by Offwrldr**
Necessary? Absolutely not.
Will I PR it? Most definitely.

## About The Pull Request

image_2024-10-05_011103932

I wanted a more interesting loading screen.
I now have one. I offer it to you humbly.

anorther-moshed-10-05-01-02-39-566

anorther-moshed-10-05-00-42-42-083

I did wanna add this one personally, but opted to unify the rainbow effect on the current Bubber Discord icon with the general feel of things.

## Why It's Good For The Game

I think that the current loading screen, while cool and fluid, doesn't really capture the actual game in any way. Not that mine fares too much better beyond being pixel art, BUT - it has the idea that there's motion, that the players are traveling from map-to-map, which I think is a cool concept.

## Proof Of Testing

The day that I test something I PR is the day that I lose my Dunning-Kruger powers.

## Changelog

:cl: Bangle

image: added/modified/removed some icons or images

/:cl:

### CODE REVIEW

**Comment by ReturnToZender** [comment]
This may need to be stretched to the same size.

**Comment by Offwrldr** [comment]
> This may need to be stretched to the same size. Overall, pretty snazzy!

From what I've observed, I think the .gif stretches to fit the window. You're... you're gonna make me test it now.

You're gonna make me lose my powers.

**Comment by Offwrldr** [comment]
image

It works - but because the backdrop of the original loading screen was black, you didn't notice the bars on the left and right side of the screen. I will leave this up for y'all to decide upon as far as including it.

**Comment by StrangeWeirdKitten** [comment]
Keeper

**Pull request merged**
