### PR TITLE
Adds CMO turtleneck/skirtleneck to garment bag

### PR DESCRIPTION
**Pull request by Sylphet**
## About The Pull Request

Does what it says on the tin.

## Why It's Good For The Game

It's a piece of CMO clothing and should be in the garment bag. The only reason it isn't is because the fruit man said no on an entirely different server two years ago. https://github.com/tgstation/tgstation/pull/64223

150031118-129cb403-a206-4ef2-88c3-9b045366aed5

## Proof Of Testing

image

## Changelog

:cl:
fix: added cmo turtleneck/skirtleneck to garment bag
/:cl:

### CODE REVIEW

**Review by Majkl-J — CHANGES_REQUESTED** [review]
Can be made modular with

```
/obj/item/storage/bag/garment/chief_medical/PopulateContents()
	. = ..()
	new /obj/item/clothing/under/rank/medical/chief_medical_officer/turtleneck(src)
	new /obj/item/clothing/under/rank/medical/chief_medical_officer/turtleneck/skirt(src)
```

**Review by Majkl-J — CHANGES_REQUESTED** [review]
Forgot to tick it in the dme

**Comment by Sylphet** [comment]
> Forgot to tick it in the dme

Ticked it on my end but forgot to include the DME in the commit, sorry! Fixed now.

**Review by Majkl-J — APPROVED** [review]
Happens, anyhow, approval given code is nice. I see no reason not to have these.

As always, 24 hours for other maintainers/players to say something against, after which I'll merge this

**Comment by YakumoChen** [comment]
There exists a command drobe on the bridge for these very types of items

**Comment by ReturnToZender** [comment]
Looks good, Sylphet :) Keep up the good work

**Pull request merged**
