### PR TITLE
Removes surgery speed penalties for being close to people because a medical doctor told me to leave medical once.

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Removes surgery speed penalties for being close to people.

## Why It's Good For The Game

Bad feature that made medical doctor very stressful and slow during emergency situations.

## Proof Of Testing

If it compiles, it werks.

## Changelog

:cl: BurgerBB
balance: Removes surgery speed penalties for being close to people
/:cl:

### CODE REVIEW

**Comment by Wolf-751** [comment]
Id honestly like it where only medical doctor/paramedic/cmo/mortician do not get penalized with the slow down,they are experienced medical staff in lore so slow down should not affect them but it should affect everyone else normally since its stressful to operate on someone with literally no experience.
 I am more surprised by the fact that regular crew can operate and do complex surgery as good as a doctor and not get penalize with failure chance for surgeries when there is literally doctors available so failure chance is nothing,if you wanna go to a ripper doc be prepared to get fucked up.

**Comment by Arturlang** [comment]
Why not just encourage medical doctors instead to use the operating rooms? It's hard for antags to deal with all of medical happening in one room, and the stasis bed room should really only be for stabilizing, and if you want to do proper surgery, go to a quiet room like the surgery room, why else does it exist?

**Comment by Moostard** [comment]
I never understood why this was a thing.
Any emergency or just piles of bodies result in a slow treatment due to everyone walking nearby, even those that try to help you.
Some doctors take it as far as pushing people away to get their surgery speedrun any% done. I have no idea why, but that happens sometimes.
Feels like the game will improve with this feature gone.

**Comment by PawnAtWork** [comment]
> Why not just encourage medical doctors instead to use the operating rooms? It's hard for antags to deal with all of medical happening in one room, and the stasis bed room should really only be for stabilizing, and if you want to do proper surgery, go to a quiet room like the surgery room, why else does it exist?

That's literally what this is for, it's so they're penalised for doing surgery in the triage area. Yet very few do it aside. I hate how people made it possible to do surgery on the beds again.

**Review by Majkl-J — CHANGES_REQUESTED** [review]
You aren't removing a bad feature, you are buffing something skyrat added atop TG. The regular speed without the buff is the intended one by TG, so either remove the entire buff, or don't touch it. It serves its intended purpose and gives a reason to use surg rooms and to not have people running around slowing you down.

**Comment by BurgerLUA** [comment]
Maybe the buff without conditions is needed tbh

**Comment by Majkl-J** [comment]
> Maybe the buff without conditions is needed tbh

Just use the surgery computer, mixed experimental fixes everything in a blink of an eye, buff or not. Either way an incentive to actually use surgery rooms is better than a flat buff

**Comment by nikothedude** [comment]
its not a penalty, its actually a bonus if youre not in preseence of people

this is important to understand because tg doesnt have these bonuses and surgery is a lot slower

**Comment by projectkepler-ru** [comment]
This is honestly a non issue

**Pull request closed without merging**
