### PR TITLE
Persistence Base (A new offstation syndicate map) (Should be ready for test merge) (Ready for review)

### LINKED ISSUE #2386: Flaky test log_mapping: build_pipeline(): /obj/machinery/atmospherics/pipe/layer_manifold/cyan added to a pipenet while still having one. (pipes leading to the same spot stacking in one turf) around Dauntless Turbine Room (175,82,5).
Flaky tests were detected in [this test run](https://github.com/Bubberstation/Bubberstation/actions/runs/11763464587/attempts/1). This means that there was a failure that was cleared when the tests were simply restarted.
Failures:
```
log_mapping: build_pipeline(): /obj/machinery/atmospherics/pipe/layer_manifold/cyan added to a pipenet while still having one. (pipes leading to the same spot stacking in one turf) around Dauntless Turbine Room (175,82,5). at code/modules/unit_tests/mapping.dm:19
```

### PR DESCRIPTION
**Pull request by shellspeed1**
## About The Pull Request

https://youtu.be/pPhfOGnLm08?si=QC2BPGd1pcLCXTc7 <- Updated as of 10/28

This pull request provides a replacement map for the interdyne and dauntless offstation syndicate maps. It is supposed to be themed as a landcrawler and features several new roles, (~~The comms operative was removed~~) and the morale officer (The finest of waffle co. here to enforce ~~managed democracy~~ syndicate interests. The icebox map is the same size as the former dauntless map, while the new lavaland version is slightly bigger to support the turrets and energy shielding.

Speaking of, one major feature of the new maps is a double layer of energy shielding around the maps. This shielding does not recharge and is intended to take two hits. An explosion naturally can clear both layers at once and it is intended to prevent destruction by specific megafauna (colossus) while also stopping miners from getting shot if they accidentally find the ship. It does not cover the various entrances and exits so its still worth while to be careful and if need be it should be easy enough to attack the ship in a pinch.

**Weapon and armor wise, the ship has the following additions and removals** 

- All makarovs in the armory have been removed.
- One renostar shotgun has been removed from the armory
- Each non command crew  member and the comms operative starts out with a weapon selection beacon providing an option between a makrov, m1911, mini egun, or energy dagger
- Each command officer barring the MAA starts with a weapon beacon offering a choice between an ansem pistol (on par with an m1911 iirc), a stechkin APS, or a c-20r.
- The morale officer has an additional selection of a revolver (for executing dissidents) 
- The MAA has a selection between an m-90gl with only rubber grenades available, a bulldog shotgun, a c-20r, or a hos revolver 
- An infiltrator modsuit has been added minus the psi demoralizer for the corporate liason
- A honkerative modsuit has been added for the morale officer, it comes preequipped with a waddle module.

**Power supply**

Per request, the ship now features a syndicate unique power source, FISH! Make sure to pet them.

closes #2386

## Why It's Good For The Game

It has come to my attention that the interdyne offstation map which spawns on icebox has become outdated due to the fact that it only spawns on a single map. Rather than let this continue to be an issue I have elected to standardize the icemoon and lavaland maps to one single map, both to cut down further efforts of keeping up the offstation syndicate map, and to provide a map that going forward will have room for updates. Additionally, the new map will replace the icebox comms outpost, saving on space for new ruins while improving (hopefully) spawning off the offstation syndicate. 

On one final note, massive mining rigs are cool and the pumpkin spice must flow.

## Proof Of Testing

See the video linked above

<details>
<summary>Screenshots/Videos</summary>

</details>

## Changelog

:cl:
add: The Persistence land crawler has been deployed to local mineral rich areas.
/:cl:

### CODE REVIEW

**Comment by NargaInDisguise** [comment]
Important Suggestion: If this base has hostages, please god make sure they do not have round-start breakout tools.

No soda cans for thermite, no remote signallers in the lustwish, etc etc.

**Comment by ReturnToZender** [comment]
I really like some of the adjustments to this, but I do have some issues with it, personally. I'm gonna start with what I like.

1. The shields on the exterior are a great addition.
2. Some of the rooms are really cozy, and I really like the re-design of the social areas.
3. Merging the Icebox and Regular variants into one map is just a great idea. No one really likes the Icebox base and it doesn't really feel unique.

So, here are my issues:

1. The Dauntless is a small ghost role, based around a ship and Cybersun agents. Both lore-wise and in-game, how is a big boxy land-crawler going to work? How many spawns are on this station?
2. The O-shaped layout like on Box station is good for most maps, but when you're looking at a small station where you want to easily navigate, the lack of signage and the need to remember navigation details really hinders this map. The Dauntless' straight line through the middle means you can just walk from one end to the other to find where you need to be.
4. These rooms are far too boxy, and spacious. I know this is due to its design as a land-crawler, but this makes it look exactly the same as Tarkon, and the Station. The Syndicate should feel relatively cramped.
5. Ultimately, an upgrade to the Dauntless with some of its features would be an improvement over this, and it would have taken significantly less time.
6. Finally, I don't really want to see the Dauntless be made big like this. People play the Dauntless over say, Port Tarkon, because it feels notably different from the other ghost roles. That mouth-feel will be lost if it just looks like a station clone.

**Comment by shellspeed1** [comment]
> Important Suggestion: If this base has hostages, please god make sure they do not have round-start breakout tools.
> 
> No soda cans for thermite, no remote signallers in the lustwish, etc etc.

On one hand, I can appreciate the prisoner problem, and I can fix some of that by disabling loadout spawns, but asking me to make the prison escape proof is asking me to make an empty room. For fucks sake, you can escape using nothing but the microwave and a bit of metal.

**Comment by shellspeed1** [comment]
> I really like some of the adjustments to this, but I do have some issues with it, personally. I'm gonna start with what I like.
> 
> 1. The shields on the exterior are a great addition.
> 2. Some of the rooms are really cozy, and I really like the re-design of the social areas.
> 3. Merging the Icebox and Regular variants into one map is just a great idea. No one really likes the Icebox base and it doesn't really feel unique.
> 
> So, here are my issues:
> 
> 1. The Dauntless is a small ghost role, based around a ship and Cybersun agents. Both lore-wise and in-game, how is a big boxy land-crawler going to work? How many spawns are on this station?
> 2. The O-shaped layout like on Box station is good for most maps, but when you're looking at a small station where you want to easily navigate, the lack of signage and the need to remember navigation details really hinders this map. The Dauntless' straight line through the middle means you can just walk from one end to the other to find where you need to be.
> 3. These rooms are far too boxy, and spacious. I know this is due to its design as a land-crawler, but this makes it look exactly the same as Tarkon, and the Station. The Syndicate should feel relatively cramped.
> 4. Ultimately, an upgrade to the Dauntless with some of its features would be an improvement over this, and it would have taken significantly less time.
> 5. Finally, I don't really want to see the Dauntless be made big like this. People play the Dauntless over say, Port Tarkon, because it feels notably different from the other ghost roles. That mouth-feel will be lost if it just looks like a station clone.
> 
> Ultimately, they all kinda stem from "the Dauntless feels good. Like a real Syndicate ship." What makes this different from the mass-produced slop stations Nanotrasen pre-fabricates? You could argue that Cybersun is ultimately Nanotrasen's counterpart, but I feel like that would lead to a less interesting result. I love that you can feel the soul of the Dauntless just by looking at it.

Regarding point 2, the O shaped hall is something that can be worked around fairly easy by just moving several rooms up a bit. That would make it an H and that is fairly straight forward and easy to do. The only reason for it is that I wanted redundant cabling and piping through there, but there are other ways to do it. 

Regarding point 4, the problem with just upgrading the map over and over is that it continues to become more and more cramped as more stuff is added which needs to be supported. As is, we are already looking at space pods being a feature from TG that will likely need to be accommodated in addition to space needed to support plumbing, crafting factories, who knows what else. When I did the last update to the dauntless, I was already starving for space and was struggling to make it work. I could keep hacking away at it, but that will likely cause significant playability issues. 

On point 3, can you provide specifics on the rooms that you feel are too big? I was aiming for a mixture of room sizes throughout the process of designing it and some rooms are intentionally large to help support infrastructure projects and the such, like botany which was a ton of improvements that you can actually build such as self made plant trays, bees, and plumbing.

**Comment by Shadow-Quill** [comment]
I love how it looks so far, and I'm excited to try it out once we start playtesting it

**Comment by IgiariValkyr** [comment]
I still believe this should be static on Icemoon and Moonstation, then be a random 50/50 between this and dauntless on any other map.

**Comment by shellspeed1** [comment]
> I still believe this should be static on Icemoon and Moonstation, then be a random 50/50 between this and dauntless on any other map.

That could actually be explored later, like I said previously we are still ages out on this. For the moment I would like it to be the constant map so we can get everything worked out and make sure I didn't miss anything.

**Comment by Hotmud9** [comment]
These turrets start ON FIRE
image

**Comment by kassori** [comment]
The comms agent should not be in this ghost role. The comms agent is an antagonistic ghost role that is valid to search and destroy and should not be related to the hidden base in any capacity.

**Comment by shellspeed1** [comment]
> These turrets start ON FIRE image

FIxed

**Comment by Hotmud9** [comment]
Also, a few qualms:
> Research person gets a Wraith module, but does not get a MODsuit to go along with it (Nor are there any in the armory; I just want something other than what's available at the exofab)
> The Syndiecard, something that's supposed to be able to summon a ghost to become a syndicate MODsuit AI, is just a reskinned intellicard.

**Comment by shellspeed1** [comment]
> Also, a few qualms:
> 
> > Research person gets a Wraith module, but does not get a MODsuit to go along with it (Nor are there any in the armory; I just want something other than what's available at the exofab)
> > The Syndiecard, something that's supposed to be able to summon a ghost to become a syndicate MODsuit AI, is just a reskinned intellicard.

Can you actually summon an AI for it? Its intended to just be a card for the oddchance you happen to have one.

**Comment by Hotmud9** [comment]
No, you can't. It looks like the one the nukies get, but isn't.
I'd say giving the researcher these (alongside, like, a second infiltrator suit since I know the comms agent gets one for SOME reason even though they just need a chameleon mask) would allow for closer observation of the crew, as the modsuit AI will be able to get the wearer back to the Persistence with little risk to the vessel.

**Comment by NargaInDisguise** [comment]
> No, you can't. It looks like the one the nukies get, but isn't. I'd say giving the researcher these (alongside, like, a second infiltrator suit since I know the comms agent gets one for SOME reason even though they just need a chameleon mask) would allow for closer observation of the crew, as the modsuit AI will be able to get the wearer back to the Persistence with little risk to the vessel.

Just make sure the armory has 3 redsuits, its what the dauntless has. Also dauntless ghost role crew are NOT supposed to be fiddling around where the crew can hear/see them anyways, the comms agent honestly shouldn't even be a spawn here.

**Comment by shellspeed1** [comment]
> > No, you can't. It looks like the one the nukies get, but isn't. I'd say giving the researcher these (alongside, like, a second infiltrator suit since I know the comms agent gets one for SOME reason even though they just need a chameleon mask) would allow for closer observation of the crew, as the modsuit AI will be able to get the wearer back to the Persistence with little risk to the vessel.
> 
> Just make sure the armory has 3 redsuits, its what the dauntless has. Also dauntless ghost role crew are NOT supposed to be fiddling around where the crew can hear/see them anyways, the comms agent honestly shouldn't even be a spawn here.

Redsuits were redistributed to other roles for the most part. The only crew member who gets one is the engineer, for engineering work. Otherwise its command staff. As for the comms operative I'm talking to Halas on that one.

**Comment by shellspeed1** [comment]
To specify, the comms operative is not supposed to be antagonistic to the station. They should only be there to serve as a monitor and intermediary for the syndicate. Clear and simple, you're just there to be an intermediary for the Syndicate, and to keep an eye on records and such for intel reasons, but you're not on disruption-duty. If this is an issue I'll try and figure out a seperate role to replace them. In the mean time they are removed on a temporary basis.

**Comment by shellspeed1** [comment]
Comms operative was removed and replaced.

**Comment by Erol509** [comment]
Last time I played, offstation var was overriden and vendor had prices still on em. (Syndrobe)

**Comment by NargaInDisguise** [comment]
Suggestions from a round on the persistence that I was told to put here:

Morale officer kinda icky, don't like clowns in general but if it stays its your decision. REALLY don't like that they just have the ability to shoot/kill anyone they deem valid, from what I've been told?

Replace the HoS revolver with a syndicate revolver, uses .357 and the speedloaders that are already inside the armory.

The lustwish inside the hostage area still has remote signallers, even though I think you removed them in a patch...?

Xenobio needs double windows, they keep escaping apparently.

Manager role seems redundant with the Liason and has only encouraged players to try and single-handedly rule the persistence while ignoring the rest of command entirely.

**Comment by Majkl-J** [comment]
One issue I got reported was one player spawning in as operative without an ID, should be checked.

As for personally I have a few minor issues, there seems to be a lack of start/backup materials compared to dauntless, unless I was unable to find them. Also I think the main hallways should not have catwalks. They make it feel more like a maint shaft than a hallway

**Comment by Majkl-J** [comment]
Also one thing I got reported that is a big issue, scrubbers and airflow pipe layers are swapped the other way from dauntless

**Comment by ReturnToZender** [comment]
Number of spawns matters. Can it be mentioned on the PR? I think the spawns _should_ be less than 10 ideally, but I'm okay with approaching 10.

**Comment by StrangeWeirdKitten** [comment]
The same / similar amount Dauntless has is fine. I'm not really worried about an exact number of low spawns purely because we have a 120 high pop then what it used to be.

**Comment by StrangeWeirdKitten** [comment]
image

**Comment by NargaInDisguise** [comment]
> Number of spawns matters. Can it be mentioned on the PR? I think the spawns _should_ be less than 10 ideally, but I'm okay with approaching 10, like the Dauntless' 11/12. It's okay for the ghost role to have more spawns during the testmerge phase for visibility purposes, but it will need to be tweaked later.
> 
> Suggestions for reducing slots, in order of "do I think they're good.": Merge MAA and Brig Officer in role, reducing slots by 1 Merge Off Duty and General Staff. They're effectively the same in role. Reduces slots by another 1. Remove janitor, morale officer to reduce slots by 2 Remove the Cargo tech to reduce slots by 1. Most people on the Persistence can access and use Cargo, and there is no need for there to be a dedicated mining role. Reduce hostage slots by 1. Self-explanatory, it's usually good enough. Should be a last resort.
> 
> Assuming there are 15 slots, including hostages, everything except the last option would reduce the total # of slots to a more reasonable 10, which is actually lower than the Dauntless. This would be ideal.

Please absolutely do not merge MAA and Brig Officer, I genuinely want those separate. Please. Please don't do that.

**Comment by shellspeed1** [comment]
> One issue I got reported was one player spawning in as operative without an ID, should be checked.
> 
> As for personally I have a few minor issues, there seems to be a lack of start/backup materials compared to dauntless, unless I was unable to find them. Also I think the main hallways should not have catwalks. They make it feel more like a maint shaft than a hallway

Fixed issue

**Comment by shellspeed1** [comment]
> Also one thing I got reported that is a big issue, scrubbers and airflow pipe layers are swapped the other way from dauntless

That was actually a very intentional design decision. Why should the syndicate be following NT's policies on how to design bases and ships?

**Comment by Ashturian** [comment]
Hi, to add some thoughts here as a fairly regular Dauntless player. I don't think it makes sense to reduce the overall number of slots on the syndie ship given:

a. The Persistence is already much larger and can accommodate the extra players, it needs more slots, not fewer. The interest will drop off with the novelty, but that doesn't change the size of the map.

b. The roles on the chopping block are very popular ones, losing a hostage slot is painful given the competition and interesting stories that come out of them, and I think janitor and off-duty round out the core crew, and morale officer being contentious as command could afford to have it moved to a "civilian" slot instead? I'd rather have the same more hostages AND more brig-focused roles because that's largely what I'm there for.

**Comment by ChaosCzar** [comment]
Going to give my own opinion too, for what it's worth, but most of it is agreeing with Ash up above. I don't think it makes sense to drop the number of slots down, especially not to a degree that makes it less than what the Dauntless had. It is a bigger, more complete ship, that needs a slightly larger crew to fill it out. As stated before, we also have a larger surge in the player base right now, so the number of ghost roles that exist isn't neutering the main experience of the station.

Not everyone likes the station, it tends to get too "gamer" for people at times, even in roles where you tend to stay away from the action. For me personally, the station comes with a higher amount of focus, and sometimes, I want to do a job but not worry as much about everyone else around me. The Persistence is wonderful for RP, not just with the hostages, but it's just SO much easier to talk with people! There's not as much pressure about doing your job. I think it's good to have these spaces for people to hang around and engage in RP, to cool off after a stressful shift the last round, or just not have to worry about the main station.

I would be more understanding of changing the roles, rather than removing them outright. Morale Officer is like a HoP / clown hybrid, maybe lean into one or the other. Off-duty crew doesn't make too much sense- Would they even have an off-duty member on staff there? Maybe just another general staff or Command assistant. Janitor makes sense- We just had a shift where someone had to act as a janitor- Lots of spills and blood on the Persistence for them to clean!

**Comment by Hislyna** [comment]
Completely agree with the two posts above. The persistance feels great with the slots it has, its away from the station without worry, its amazing for the RP and just removing slots won't make people want to play on the station. People enjoy the persistence for completely different reasons on why one goes to the station. People are infact asking for more prisoner pods on the persistence cause even the prisoner role there is better than on station for some people.

**Comment by StrangeWeirdKitten** [comment]
I've spoken to Moff about the slots and there will be 15ish in total.

**Comment by ReturnToZender** [comment]
> I've spoken to Moff about the slots and there will be 15ish in total.

I stated that the # of slots should match the Dauntless, I never said that it should be 15. I simply stated that I was okay with it being more for testing purposes, as the Dauntless did the same so it could iron out its kinks. The end result was 12 total roles, including hostages. The persistence has 15 total roles, including hostages, and this is three more than it should have.

The Persistence having 3 additional roles is still something I'm rather firmly against, especially when some are redundant or not particularly necessary at all.

**Comment by StrangeWeirdKitten** [comment]
Moff =/= Zender. Moff is the name of the contributor for this PR.

**Comment by ReturnToZender** [comment]
> Moff =/= Zender. Moff is the name of the contributor for this PR.

oh sorry. I'm moffington so I got confused

**Comment by ReturnToZender** [comment]
> Completely agree with the two posts above. The persistence feels great with the slots it has, its away from the station without worry, its amazing for the RP and just removing slots won't make people want to play on the station. People enjoy the persistence for completely different reasons on why one goes to the station. People are infact asking for more prisoner pods on the persistence cause even the prisoner role there is better than on station for some people.

The Prisoner role on the Dauntless/Persistence is simply the best way to play prisoner, enough so that you would never play Prisoner on station. All of the shortfalls of Prisoner on-station are removed or don't exist. It is harsh but fair, as a prisoner role should be.

It's also true that people enjoy the Dauntless/Persistence for reasons different from the station-- this is inherent, it's why you play a ghost role, and why, when giving feedback on design, we are such sticklers for the mouthfeel of a ghost role, so that it doesn't replace the station. That difference makes a ghost role what it is.

With that said, the reasons that the Dauntless/Persistence are good-- that it's good for learning, gives you easy access to materials and weapons, doesn't have events getting in the way, and outlines a controlled roleplay purpose-- lead to it being abused by players who don't want to learn, and instead want to avoid the spontaneity of the station, because they're jaded or can't roleplay. 
This also happened with DS-2, and reducing the # of slots for Syndicate agents from over 20 to about 12 had a significant impact on this problem. I don't want to have to ground another friend group's favorite ghost role, so I'm a stickler for this.

People also said "we have the pop to support it right now" when DS-2 was flying. It was still a problem, and to an extent, the ghost roles will _always_ be a problem, but the important part is to keep it from getting to the point where staff have to wreck the sandcastle. I'm acutely worried about it.

**Comment by StrangeWeirdKitten** [comment]
> > Moff =/= Zender. Moff is the name of the contributor for this PR.
> 
> oh sorry. I'm moffington so I got confused

Is fine fam, but I've spoken to Moff about it. Overall with our increased server pop, I have zero concerns for this effecting much of anything, especially the station, I would rather people just have their slots and have their fun, primarily since this ghost role needs very little admin intervention. I've made the decision let them keep the clown and the janitor since people genually enjoying it while letting Moff (The contributor) have a level of freedom to decide on the roles. But overall we can always let it play out and change it later down the line as needed.

**Comment by projectkepler-ru** [comment]
image

**Comment by Hislyna** [comment]
Just an fyi for the bitrunning bit in brig. There must be a direct LOS to the server for things to work, and if any are blocked, the server will not register such. The blacked out windows, or of course the shutters being down cause it to be unusable.

**Comment by shellspeed1** [comment]
> Just an fyi for the bitrunning bit in brig. There must be a direct LOS to the server for things to work, and if any are blocked, the server will not register such. The blacked out windows, or of course the shutters being down cause it to be unusable.

You would not believe how annoying the bitrunning setup is getting to be.

**Comment by projectkepler-ru** [comment]
> > Just an fyi for the bitrunning bit in brig. There must be a direct LOS to the server for things to work, and if any are blocked, the server will not register such. The blacked out windows, or of course the shutters being down cause it to be unusable.
> 
> You would not believe how annoying the bitrunning setup is getting to be.

look at my image

**Comment by shellspeed1** [comment]
> > > Just an fyi for the bitrunning bit in brig. There must be a direct LOS to the server for things to work, and if any are blocked, the server will not register such. The blacked out windows, or of course the shutters being down cause it to be unusable.
> > 
> > 
> > You would not believe how annoying the bitrunning setup is getting to be.
> 
> look at my image

Sadly, I can't just use that solution as it provides several really easy escape methods in addition to just making the same prison science problem the mainstation has worse. What I can do is make the shutters start open and disable the window polarizer.

**Comment by Majkl-J** [comment]
How close is this to being ready to merge in your opinion

**Comment by shellspeed1** [comment]
> How close is this to being ready to merge in your opinion

Nowhere near, we are still finding small things and I just found out that crates are apparently nuked.

**Comment by Hotmud9** [comment]
Urgent issue: Apparently some crewmembers aren't starting with IFFs, and the turrets are shooting them.

**Comment by shellspeed1** [comment]
> Urgent issue: Apparently some crewmembers aren't starting with IFFs, and the turrets are shooting them.

Should be fixed.

**Comment by RimiNosha** [comment]
Issue: Comms are using normal green channels. Please use the interdyne frequency or set up a new one. Make a subtype of the radio in code when you do this, please.

**Comment by shellspeed1** [comment]
> Issue: Intercoms are using normal green channels. Please use the interdyne frequency or set up a new one. Make a subtype of the radio in code when you do this, please.
> 
> Also please double check how close the intercoms are to each other. Someone was reporting hearing up to four at once, which is way too many.

While the channels are green, the frequency is not station general. This is the same way it worked on dauntless and if you check the channel number, its well below what is accessible on a standard intercomm. I will however look into intercomm placement, something is fucky there.

**Comment by StrangeWeirdKitten** [comment]
People have kind of pointed out that there's a some power creep with some of the things persistance has over dauntless. For right now I'm kind of focused on the C-20r SMG. I feel like this is a better armory item then a sidearm for the three command members.

**Comment by NargaInDisguise** [comment]
> People have kind of pointed out that there's a some power creep with some of the things persistance has over dauntless. For right now I'm kind of focused on the C-20r SMG. I feel like this is a better armory item then a sidearm for the three command members.

I'm not comprehending this, are people complaining that the persistence has too good of weapons?

**Comment by StrangeWeirdKitten** [comment]
I'm specifically saying the SMG shouldn't be a side arm. I'm fine with the other pistols and maybe its replacement being an e-sword.

**Comment by NargaInDisguise** [comment]
> I'm specifically saying the SMG shouldn't be a side arm. I'm fine with the other pistols and maybe its replacement being an e-sword.

A side-arm on who? The MAA? The character whos entire gimmick is having a ton of big guns and an armory? Also, theres three e-swords to start with in the armory.

**Comment by StrangeWeirdKitten** [comment]
All command members get a command sidearm beacon that has this. The bigger guns (things that are not a sword or a pistol) should be religated to the armory.

**Comment by NargaInDisguise** [comment]
> All command members get a command sidearm beacon that has this. The bigger guns (things that are not a sword or a pistol) should be religated to the armory.

If you want to move the beacon weapons to the armory as well to have variety, thats more than fine. But please do let them keep their round-start one.

**Comment by StrangeWeirdKitten** [comment]
You're completely misunderstanding my point. I just want the C-20r to not be a side arm from a command beacon because it has a bit more power to it as a fairly decent nukie weapon with good ammo throughput. I'm not demanding that the armory be stripped down (because it's overall fine) or a single C-20r being placed among the MCRs and shotguns.

**Comment by NargaInDisguise** [comment]
> You're completely misunderstanding my point. I just want the C-20r to not be a side arm from a command beacon because it has a bit more power to it as a fairly decent nukie weapon with good ammo throughput. I'm not demanding that the armory be stripped down (because it's overall fine) or you can't place a single C-20r being placed among the MCRs and shotguns.

Oh no I'm mentioning that the MAA has both a round-start one AND one in their beacon. I want them to keep their round-start one on themselves.

**Comment by Hislyna** [comment]
How is this an issue when there should never be a reason for the persistence members to use such weaponry. Alongside that, all command members should be fine getting one since theres not always an MAA.

**Comment by ChaosCzar** [comment]
Is this much of an issue? I understand that the gun is strong, of course- But it's not going to see much use. Unless I'm misunderstanding something, the Persistence shouldn't be interacting with the station in that manner (open combat) without ahelps / admin events, and vice-versa. And against lavaland mobs, isn't mining equipment simply better too?

**Comment by NargaInDisguise** [comment]
I think I've been mis-interpreted. I agree with Sharkening, move+add more powerful guns to the armory and keep the beacons specifically to side-arms, with the MAA's on-spawn c20 being an exception. That's my opinion.

**Comment by StrangeWeirdKitten** [comment]
If you want admins to include Persistence in their events, they need to have some reasonable level of gear standards and not just an isolated fortress full of a bunch of nukie guns they have to then consider and worry about. I like the beacons, and I don't mind giving them toys, but they're admittidely going over the level of gear I originally gave Dauntless. On top of ordering more guns. On top of combat mechs and other mechanics they have access to.

**Comment by ChaosCzar** [comment]
Since I really do think it only matters for events and the occasional ahelp, I think it's something the station SHOULD plan around. The Persistence has less members then the station does, so they need ways to level the playing field. Being in Lavaland already means NT miners severely outclass the Persistence- We saw this happen during the Dauntless war events that happened a few months back.

In most use cases, I think the weapons being available changes literally nothing, and adds an additional balancing act if an admin is going to be running a combat event.

> If you want admins to include Persistence in their events, they need to have some reasonable level of gear standards and not just an isolated fortress full of a bunch of nukie guns they have to then consider and worry about. I like the beacons, and I don't mind giving them toys, but they're admittidely going over the level of gear I originally gave Dauntless. On top of ordering more guns. On top of combat mechs and other mechanics they have access to.

**Comment by ChaosCzar** [comment]
Also. I mean. NT can order guns. And make mechs. I don't think that's relevant, what is relevant is the available manpower.

**Comment by NargaInDisguise** [comment]
Also on the note of events, every time we've had one, it has just made crew more vitriolic towards the dauntless for like 50 rounds straight. I don't think Station vs Persistence events have ever really had a track record of doing well. Also not to mention, the miners just completely bypass any kind of combat by drawing the colossus over, which tears half the place apart (and has happened in EVERY. SINGLE. EVENT round.)

"CAN WE FUCKING BSA THEM YET" being a very common message every single time command makes the BSA (which is every other round because its a station objective that rolls all the time) has gotten pretty tiring.

**Comment by shellspeed1** [comment]
> You're completely misunderstanding my point. I just want the C-20r to not be a side arm from a command beacon because it has a bit more power to it as a fairly decent nukie weapon with good ammo throughput. I'm not demanding that the armory be stripped down (because it's overall fine) or you can't place a single C-20r being placed among the MCRs and shotguns.

per discussion, two C-20rs are now in the armory with the beacon option being replaced with energy swords. I stripped out two energy swords as well.

**Comment by shellspeed1** [comment]
> Also. I mean. NT can order guns. And make mechs. I don't think that's relevant, what is relevant is the available manpower.

NT does have to lug all of that down to the base, although there are options they to do that. For example just throwing a beacon down and piling through the teleporter.

**Comment by shellspeed1** [comment]
Please note, there is a known issue with the intercomms that I am still working on where they are for some reason broadcasting the same message like 8 times even though only one has its mic on.

**Comment by Hislyna** [comment]
How can you be an admiral of a... rig... wouldn't commander fit more if anything?

**Comment by shellspeed1** [comment]
> How can you be an admiral of a... rig... wouldn't commander fit more if anything?

Its more just to resolve issues with chain of command and what people are used to. Its a land boat.

**Comment by Hislyna** [comment]
So, found a problem if you join mid shift, no power, first person on as Admiral Rig Manager, Turns out you cant leave your quarters because the doors bolted with no power, so down disposals with you!

**Comment by shellspeed1** [comment]
> So, found a problem if you join mid shift, no power, first person on as Admiral Rig Manager, Turns out you cant leave your quarters because the doors bolted with no power, so down disposals with you!

I can come up with a better solution on that I think, disposals is valid though lol.

**Pull request merged**
