### PR TITLE
Adds GPS tags to the upload boards

### PR DESCRIPTION
**Pull request by aKromatopzia**
## About The Pull Request

https://github.com/Bubberstation/Bubberstation/pull/1339#issuecomment-2046686484

I think it's too easy to subvert silicons. I also think it's too easy to fix them. Regardless, this change targets the former. This is a direct antagonist balance change so feel free to give your opinion even if you've never hacked a silicon or been hacked as a silicon.

I do wonder why intellicards aren't gps-bugged, but I don't design the fabric of fictional reality.

Also, this tags any active consoles with the gps flag. I am not removing that for compatibility reasons.

## Why It's Good For The Game

Upload ping pong is boring.

## Proof Of Testing

Screenshot_82

## Changelog

:cl:
balance: silicon upload boards now have a GPS chip.
/:cl:

### CODE REVIEW

**Comment by ReturnToZender** [comment]
God damn, really hitting the poor boards with a double whammy

**Comment by NargaInDisguise** [comment]
> God damn, really hitting the poor boards with a double whammy

The maintainers shoot down literally every "remove printing endless ai upload boards" so this is the best we got

**Comment by StrangeWeirdKitten** [comment]
I'm already doing this on TG, guys.

**Comment by ReturnToZender** [comment]
Relevant upstream: https://github.com/tgstation/tgstation/pull/82574

**Pull request closed without merging**
