### PR TITLE
[DONE] A bunch of bloodsucker changes

### LINKED ISSUE #1180: Lizard Bloodsuckers cannot adjust body temperature.
## Issue Summary

Basically if you're warm, you will be warm forever and it will never go down naturally.
If you're cold, you will be cold forever and it will never go down naturally.

Basically if you're set on fire once or hit by a cold beam, you're fucked forever unless you have coffee or soda on you.

## Reproduction:

Be lizard bloodsucker.
Get set on fire once.
Forever burning and taking burn damage.

### LINKED ISSUE #1208: Ventrue's clan Objective is not counts as finished
## Issue Summary

If you as Bloodsucked take a Ventrue clan, make your favourite vassal new Bloodsucker, Clan objective to create new bloodsucker will count failed

## Round ID:
3669

## Reproduction:

1. Become Bloodsucker
2. Pick Ventrue Clan
3. Make Vassal
4. Make this vassal Favourite
5. Upgrade Favourite vassal to Bloodsucker
6. End round
7. See, that your clan objective counts failed

### PR DESCRIPTION
**Pull request by Arturlang**
## About The Pull Request
This adds a bunch of things as a addition to my original bloodsucker PR, there's still one PR in the plans to refactor bloodsucker abilities.
#What this adds:
- Bloodsuckers loosing the heart or brain is lethal, before you could simply walk around without a heart. Does not however cause a final death
- bloodsucker vampire bats will no longer /list you when attacking, and are also just as fast as human runspeed
- Blood cost for vassalizing was almost completely removed, now only taking tiny amounts of blood to do so.
- Dullahans can't be bloodsuckers since... their head isn't attached.
- ....buuuut bloodsuckers now kinda become helpless dullahans just with no body if they get decapicated! Funny talking head go!
- Level up cost is now 15% of max blood, down from 20%
- The stat bar will show you the threshold for exiting frenzy now too when you are frenzying.
- Maximum blood volume is shown in the stat menu as well
- Hopefully fixes some torpor loops related to frenzy
- Tremere now also get informed of how much blood they need to pay for level ups.
- Fortitude now gives you burn resistance, just 20% less than brute resistance
- Bloodsucker abilities now will show their level when you hover over them. Trust me, this was really neccessary.
- Hopefully fixes cryoing or deleted bloodsuckers not removing vassals.
- Can longer use veil while unconcious or dead
- Caps humanity lost to 50, this means a maximum of 500 blood to enter frenzy/ 10 fully drained people with clients, at this point you also loose the masquerade ability.
- Admins can now ban bloodsuckers and vassals. 
- Bloodsuckers can now mesmerize mimes
- Fat bloodsuckers are no longer unable to enter coffins. Now they resize their lair's coffin. Very obviously.
- Lizards are no longer fucked if they are on fire, they are no longer forever too hot to survive
- Going into torpor in a coffin will extinguish and set your temperature to normal
- bloodsuckers will no longer accrue toxin damage from not having a liver or having a failing one, even though they had the toxin immune trait
- synths will now heal their prosthetic limbs
- torpor start now checks for oxygen and toxin damage, and heals both completely on it's end
- Haste will remove stuns at level 3, and do a non-stunning dash
- Tremere dominate vassalizing now actually works!
- Fixes ventrue objectives not succeeding properly
- Refactors the heart thief objective and improves it by requiring it to be non-monkey hearts and letting bloodsuckers examine hearts to see if they are valid, even uses the same logic, too!
- Ventrue favorite vassal batform now has night vision, and it's spawned bats despawn once the cooldown refreshes, and halves it's cooldown to 1 minute
- Traits added to vassals get removed once they loose their antag datum, ie favorite vassal traits, or the ones gained in the process of ventrue sire-ing.
- Favorite vassals now clean up propertly when the antag datum is removed, tremere, and malkavian clean up their related additions.
- Refactors how the blood display updates, instead it now updates every time your blood level is changed, making it update far faster and only when it's needed.
- Stakes now have different properties, the normal stake is fast to stick in someone, but can fall out on it's own, the burnt one takes longer to be put in, but doesn't fall out, the silver stake is the slowest to be stuffed in someone's heart, and is the only stake to be able to cause a Final Death to a sleeping or dead bloodsucker

closes #1180, closes #1208

## Proof Of Testing
The way I develop is always run a local server and test the changes that I do, takes awhile but won't have as many bugs as a result

## Changelog

:cl:
add: Decapacitated bloodsuckers can now talk! 
add: The stat bar will show you the threshold for exiting frenzy now too when you are frenzying.
add: Bloodsucker abilities now will show their level when you hover over them. Trust me, this was really neccessary.
add: Tremere now also get informed of how much blood they need to pay for level ups.
add: At level 3, haste will now remove stuns and do a non-stunning dash
add: Bloodsucker blood display now always updates when a bloodsucker's blood level is changed
add: Bloodsuckers can now examine hearts to see if they are valid for the heart thief objective
add: Bloodsucker vassals now clean up any traits gained from their tenure as a vampire's minion.
add: Favorite vassals now properly clean up their effects once the antag datum is lost.
add: Bloodsucker synths will be able to heal their prosthetic limbs, but normal bloodsuckers still cannot.
add: When you exiit torpor as a bloodsucker, you will completely heal any toxin and oxygen damage, as you should already be immune to it. This is a safety feature.
add: Entering a coffin will normalize your temperature and extinguish you if you're on fire, if you are a bloodsucker.

fix: bloodsucker vampire bats will no longer /list you when attacking
fix: Hopefully fixes some torpor loops related to frenzy
fix: Hopefully fixes bloodsuckers cryoing not removing vassal datums
fix: Bloodsuckers can no longer use veil of many faces while unconcious
fix: lizard bloodsuckers will no longer suffer from heat for a long time
fix: The ventrue objective now properly succeeds if you have sired a vampire
fix: Livers are no longer required for bloodsuckers to live, as it caused them toxin damage which overrode the trait that made them immune to toxins.
fix: Entering torpor now accounts for all damage types, even when you should be immune to them. This is to ensure you enter torpor to heal those damage types in the case of odd behaviour.

balance: coffins should now set your temperature to normal and extinguish you.
balance: bloodsucker level up cost is now 15% of max blood, down from 20%
balance: Caps humantiy loss at 50 humanity/500 blood to frenzy, and makes it remove your masquerade ability.
balance: Bloodsucker bats now have human runspeed
balance: Blood cost for vassalizing was almost completely removed, now only taking tiny amounts of blood to do so.
balance: Fortitude now gives you burn resistance, just 20% less than brute resistance
balance: Can no longer gut bloodsuckers
balance: Bloodsuckers loosing their heart will make the vampire unable to use their abilities or even regenerateor revive via torpor, you can however regain your heart if you sleep in a coffin with a heart.
balance: Stakes now have different properties, the normal stake is fast to stick in someone, but can fall out on it's own, the burnt one takes longer to be put in, but doesn't fall out, the silver stake is the slowest to be stuffed in someone's heart, and is the only stake to be able to cause a Final Death to a sleeping or dead bloodsucker

del: Dullahans can't be bloodsuckers since... their head isn't attached
admin: Bloodsuckers and vassals can now be banned like other antags.

/:cl:

### CODE REVIEW

**Comment by Arturlang** [comment]
Oh wow, amazing, reverting changes caused me to request reviews from code owners

**Comment by Arturlang** [comment]
todo fix linters and test cryo podding more

**Comment by destrucktoid** [comment]
Can you also check ban related stuff with bloodsuckers? admins have reported having problems with regards to bloodsuckers and antagonist bans due to it not being on their menu IIRC

**Comment by Arturlang** [comment]
https://cdn.discordapp.com/attachments/1192434434440437841/1200137444566249562/2024-01-25_19-57-00.mp4?ex=65c51618&is=65b2a118&hm=f26ad2817c24a64f0a91853647a17d8c64b8e3c458ed127fdca55e4c65ddb137&

**Comment by Arturlang** [comment]
Fun fact, minds don't get deleted when their mob is gone

**Comment by Arturlang** [comment]
I'll take at testing bloodsucker bans tommorow as I need to a database setup for that, for now I'll put in a maybe-fix

**Comment by Arturlang** [comment]
Question is, do I lump bloodsuckers and vassals under the same ban, or separate them?

**Comment by Arturlang** [comment]
Tested it, added a new ban entry for specifically vassals. Just keep in mind the way that antags are replaced, if there's no other players to replace them, the banned person won't be ghosted

**Comment by Arturlang** [comment]
Would love a testmerge for this

**Comment by Arturlang** [comment]
WIP actually I need to test it a bit more locally

**Comment by Majkl-J** [comment]
Care to add a fix for https://github.com/Bubberstation/Bubberstation/issues/1180 ?

**Comment by Arturlang** [comment]
> Care to add a fix for #1180 ?

Will do

**Comment by Arturlang** [comment]
Fixed

**Pull request merged**
