### PR TITLE
Fix telecomm specialist access on Moonstation

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request

Fixes airlock access on Moonstation so the telecomms specialist job can actually get to telecomms.

## Changelog

:cl: LT3
fix: Telecomms specialist can actually access Moonstation telecomms
/:cl:

### CODE REVIEW

**Comment by BurgerLUA** [comment]
I think this might be an issue with the telecomms tech role rather than the map itself, but I'll take a look at how official maps do it.

**Comment by lessthnthree** [comment]
> I think this might be an issue with the telecomms tech role rather than the map itself, but I'll take a look at how official maps do it.

Telecomms specialist doesn't have ACCESS_ENGINE_EQUIP which is your gear room on Moon between the hallway and telecoms

**Comment by BurgerLUA** [comment]
> > I think this might be an issue with the telecomms tech role rather than the map itself, but I'll take a look at how official maps do it.
> 
> Telecomms specialist doesn't have ACCESS_ENGINE_EQUIP which is your gear room on Moon between the hallway and telecoms

Ah, I see. I could shift the entirety of the locker room around so you don't need to be in the locker room to enter it.

**Comment by lessthnthree** [comment]
> > > I think this might be an issue with the telecomms tech role rather than the map itself, but I'll take a look at how official maps do it.
> > 
> > 
> > Telecomms specialist doesn't have ACCESS_ENGINE_EQUIP which is your gear room on Moon between the hallway and telecoms
> 
> Ah, I see. I could shift the entirety of the locker room around so you don't need to be in the locker room to enter it.

Yeah if you're doing map edits in another PR I'll just close this.

**Comment by BurgerLUA** [comment]
> > > > I think this might be an issue with the telecomms tech role rather than the map itself, but I'll take a look at how official maps do it.
> > > 
> > > 
> > > Telecomms specialist doesn't have ACCESS_ENGINE_EQUIP which is your gear room on Moon between the hallway and telecoms
> > 
> > 
> > Ah, I see. I could shift the entirety of the locker room around so you don't need to be in the locker room to enter it.
> 
> Yeah if you're doing map edits in another PR I'll just close this.

This can be testmerged. I'll do a total engineering overhaul and get started on it tomorrow.

**Comment by nevimer** [comment]
merge conflict

**Comment by BurgerLUA** [comment]
this pr isn't needed anymore since it was fixed with my pr

**Pull request closed without merging**
