### PR TITLE
[Config Edit] Drastically increases space ruin budget

### PR DESCRIPTION
**Pull request by ForrestWick**
## About The Pull Request

Someone made the space ruin budget 16. Six-friggin'-teen. That's insane, that means a couple asteroids and a small ruin or two will spawn and nothing else out in space. I'm bumping it to 80 to not only give more incentive to those like myself to make some new ruins, but also to let people who are new to SS13 in general and have Bubber as their first server get a chance to see these themselves.

## Why It's Good For The Game

Space ruins and spacetiding is fun, and the amount of loot you can get isn't that bad since basicmobs are more dangerous than simplemobs, on top of some of these ruins having turrets and stuff. Would give normal crew a chance to find their own ship and make it so exiling antags into space gives them less reason to come back to station.

## Proof Of Testing

It's a config edit so it should work

## Changelog

:cl:
config: Changed spaceruin budget from 16 to 80
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
Config changes do not effect the live server

**Comment by ForrestWick** [comment]
> Config changes do not effect the live server

I hate byond sometimes

**Comment by YakumoChen** [comment]
We have a config repo if you want to affect those values

**Comment by ForrestWick** [comment]
> We have a config repo if you want to affect those values

Is there a specific link to it?

**Comment by YakumoChen** [comment]
Follow upwards to Bubberstation/

**Pull request closed without merging**
