### PR TITLE
Add catbox/imgbox to headshot regex filter

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request

Adds catbox and imgbox to allowed headshot hosting services.

## Why It's Good For The Game

It's nice to have a site where no sign up is required

## Proof Of Testing

image

## Changelog

:cl: LT3
qol: Catbox and Imgbox are now supported hosting services for headshots
/:cl:

### CODE REVIEW

**Comment by IgiariValkyr** [comment]
Can we get catbox.moe too? 👉👈

**Comment by Cyprex** [comment]
I hate this host whitelist, especially in regex form, but it is what it is!

**Comment by ReturnToZender** [comment]
If it checks that what you sent it is a .jpg file, then it should be added!

**Comment by YakumoChen** [comment]
I'm gonna remove discord and take this upstream, if you don't mind

**Comment by lessthnthree** [comment]
> I'm gonna remove discord and take this upstream, if you don't mind

Go for it

**Comment by YakumoChen** [comment]
ported up, but it won't include the NSFW/Silicon player-facing text, since that's specific to bubber

**Comment by ReturnToZender** [comment]
> ported up, but it won't include the NSFW/Silicon player-facing text, since that's specific to bubber

I believe they pull from the same regex

**Comment by YakumoChen** [comment]
F-List is still an exclusive host to this server, not Skyrat, since I don't know if they want it, so that will make a difference.

**Comment by lessthnthree** [comment]
> F-List is still an exclusive host to this server, not Skyrat, since I don't know if they want it, so that will make a difference.

I would probably just throw f-list in the SR PR. When this Bubber one was merged I was going to backport the same list.

**Review by Majkl-J — APPROVED** [review]

**Pull request merged**
