### PR TITLE
[Modular] Teshari waddle

### PR DESCRIPTION
**Pull request by ReturnToZender**
## About The Pull Request

This makes it so that all teshari have the waddle trait roundstart, making their movement unique.

PR is tested and works on localhost.

## Why It's Good For The Game
Dubious little creature getting up to mischief, this is no good

https://github.com/Bubberstation/Bubberstation/assets/110273561/d9e89e7d-d890-4df5-8afc-156662b17569

## Changelog

:cl:
add: Teshari now waddle
/:cl:

### CODE REVIEW

**Comment by izzyyes** [comment]
Augh, the beast is demonic in nature. Very icky, no good.

**Review by larentoun — COMMENTED** [review]
It could be fully modular tho...

**Comment by ReturnToZender** [comment]
> It could be fully modular tho...

You're right, gonna fix that once I'm done making waddling a quirk

**Comment by ReturnToZender** [comment]
Drafted because I have to convert this to a quirk, one Teshari said they wouldn't play if they waddled and I don't want to lose them over a waddle animation
(This comment is not a joke that is actually the reason)

**Comment by nevimer** [comment]
> Drafted because I have to convert this to a quirk, one Teshari said they wouldn't play if they waddled and I don't want to lose them over a waddle animation. (This comment is not a joke that is actually the reason)
> 
> Code is fully functional, feel free to use as a reference

Make this a trait available to the species.

**Pull request closed without merging**
