### PR TITLE
[Testmerge Only] You no longer get antag ghost prompts if you weren't even in the round.

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

You no longer get antag ghost prompts if you spawned as an observer (via main menu). You clicked observe just to observe, right?

This does not affect always-available spawns like Cyborg or Ash Walker, but rather things like event based antagonists such as Nightmare or Ninja.

Some exceptions are given to minor roles. Such as:
- Fugitives
- Paradox Clones
- Sentient Potion Spawns (Or other random sentience events)
- Ghost Anomalies
- Deathsquad (And ERT, by extension).
- Drone, Maintenance or Otherwise
-  Lavaland related roles.
- Lazarus related interactions
- Mind Transfer related interactions
- Monkey Helmets
- pAI and Posibrains
- Santa
- Servant Golems
- Bots
- All Virtual Reality related roles, except for on-station Netguardians.

## Why It's Good For The Game

https://www.reddit.com/r/SS13/comments/qa6va3/mornin_nice_day_for_freeantag_fishing_aint_it/

Bubberstation has an unironic issue of players intentionally observing just to get antagonist roles, and this has lead to a ton of toxicity in dchat as well as in the main game. I wanted to make this PR ever since there was a xeno event and the amount of observers skyrocketed from 8 to 14, then back down to 6. That round was especially bad because there were people unironically bitching about not getting a xeno role and how the existing players were "ruining the round" and "wasting the slot" because they weren't skillful players.

That's the most extreme example, but as of late there have been a lot of people who are clearly joining just to observe. I'm sure that people will attempt to bypass this PR, if implemented, by joining, immediately cryoing, then immediately joining as a xenomorph, but that means admins will have an easier time proving that someone was antag fishing.

If this negatively affects balance in some way, exceptions can be added to roles.

## Proof Of Testing

Untested.

## Changelog

:cl: BurgerBB
del: You no longer get antag ghost prompts if you spawned as an observer (via main menu). You clicked observe just to observe, right? Some exceptions are given to minor roles or virtual reality roles.
/:cl:

### CODE REVIEW

**Comment by ReturnToZender** [comment]
DANGEROUSLY based

**Comment by SovietSpaghetti** [comment]
If this actually goes through, antags like spiders or xenos or going to need to get buffed to compensate for the far fewer potential people to spawn as them. Genuinely feels like a soft removal for about half the antags on the server, considering how few people are going to want to DNR pending revival in order to play a simplemob antag for like 15 minutes at most, especially considering how rare actual round-removal is here.

**Comment by AllCorruptingWyrm** [comment]
The servers getting stale, why are we removing more antags? its all just Changelings, never tots or anything

**Comment by Majkl-J** [comment]
> The servers getting stale, why are we SOFT removing more antags? its all just Changelings, never tots or anything

Tots roll about 60% of the time but 2 out of the 3 spawns always ask to have them removed. This has been a fundemental issue for a while and I blame gimmick objectives and removing progtot for it

**Comment by nevimer** [comment]
it's a good idea, but the problem is that these antags will never see the light of day again. 

Heres better idea: move as many of the offenders to being CREW ONLY. Ninja, Contractors (rip), loneop, etc. Make em all pick from crew. Ninja should be able to be a head (rd, ce, qm, hop, cmo (we can run a trial on this, i think its cool)) (no sec ninjas) that isn't the Captain or HOS.

Revenant is picked from a person who has died, and can only be extinguished by reviving the character that died. This immediately pulls them back to their body. Make this a smite, so admins can force it on people who should be rewarded (eg, someone throws them into the SM, medical lets their body rot for 20 minutes in the lobby, robotics fails to read, etc). Rename it like, vengeful spirit. 

Blob, there is a crew variant, but it sucks at the end. That can stay ghost only. Same for blobbers. Heritage. 

ERT - both. Happens way late into the round, or sometimes you need a person who hasn't been in round.

Frequently even Ninja and Abductors fail to get any players when they roll, even with the ghost mains.

**Comment by BurgerLUA** [comment]
I tried getting Ninja to crew but I was basically skating uphill because people really want ninja to be a ghost role. I could imagine it being the same with the other antagonist types.

**Comment by theselfish** [comment]
I see a lot of people joining and instantly cryoing.

**Comment by Wolf-751** [comment]
> I tried getting Ninja to crew but I was basically skating uphill because people really want ninja to be a ghost role. I could imagine it being the same with the other antagonist types.

it should be both

**Comment by lilBlovy** [comment]
Reguardless of what anyone thinks I think a decision this large should be put up to a vote by the members of the community. With the upsides and downsides of doing this explained to them.

**Comment by lilBlovy** [comment]
But my personal take is that most ghost roles struggle to get anyone to actually do them as it stands. Making it even harder to get into the ghost roles would make those midround antags die out completely.

**Comment by Arturlang** [comment]
Problem is people just dont die enough on this server, shifts are often too calm amd safe especially with how few antags there usually are, and if you do this add the block to cryoed people too

**Comment by Redrover1760** [comment]
Ghosts roles and antags were designed around the idea that getting revived at all varied wildly and death was common and sometimes you just got desworded and decapped and have your head thrown diagonally through space, to never be recovered no matter how hard people tried, which they won't, as they're busy trying to kill the desworder and/or call shuttle to antag roll under the thin guise of roleplay. There are plenty of dead, and observers can't respawn on tg, so the people who went out of their way to observe instead of playing (and they can't take that decision back by respawning) were fairly mixed with the in round dead, often acting as extra fighters for the ghost roles that focused on mass numbers (Xenos, Spiders, Etc). Rounds only lasted an hour or less on average so it wasn't a big deal. 

Everything about Ghost roles fails to work on Bubber. Rounds last 3 hours, there is often no action whatsoever, with barely any dead and an expectation of being revived, no round removal outside of the poor traitor who broke out of perma 3 times (or the poor changeling who got valided for being a ling). Security as always works its hardest to remove the threat out of the round instead of roleplay with it, because skyrat's anti-antag culture still persists to a much lesser extent. No one dies, antags are rare, people get bored and observe, able to change their mind due to the fact you can respawn (which, to be honest, is necessary considering how long the rounds are). Ghost antags such as spider works fine, as its robust in concept and has mass numbers. Observers benefit spiders and no one loses. However, Xenos are much more rare. Assuming the queen isn't annihilated in an instant by all the bored secoffs with 1-2 hours of gear grinding, only a good 8 or so xenos might be around unless they just completely annihilate the station's security at most. Although, considering the expectation of revival, if xenos were restricted, there would be one or two xenos at most, making it just sad, unless they could get some kills and assuming the people who died want to play xeno instead of sticking to their attached furry character. 

Then, well. Solo ghost antags. Aka, hell. They roll rarely, barely any chance anyone gets it, kind of a waste of time. They're also unique roles you can't get by playing or signing up for the game normally. In an environment where plenty die all the time and never get revived, and characters and round removal aren't sacred and heresy respectively... Not ideal. Besides, considering that oftentimes people will be hunting for you to revive you, its a bit of a dick move to go antag at that point lol. Case in point, solo ghost roles do not work for bubberstation, Spiders works fine just due to the sheer numbers they're balanced around, and Xenos and Pirates are sorta in the middle of mediocrity, although Xenos are better off considering they get to kill people and have those ghosts join in as more xenos.

**Alternative Suggestion**
It's possible to make observers still be permitted to roll ghost antags but prioritize or tilt the scales of luck in the favors of the actual dead if they desire to play an antagonistic ghost role. This way, observers who are actually observing for fun can still get the chance to have fun if there's no dead around and they are observing because they want to observe or instead cryo'd, but also that they aren't taking away a decision of a person who is dead and don't feel like they can be revived.

And yeah, there's gonna be issues from this, but not any more issues that straight up banning ghost roles from observer would cause. Chief among them is probably suicide ghost rolling to get around the system. You know the drill: accidentally walking into a chasm with suit sensors off and no gps.

Incorporating solo ghost antags into crew is incredibly desirable as well, for these exact reasons, as it just allows crew to experience the rare ghost antags that they can't do normally, as well as the fact that someone who is already playing the game is likely to just be more engaged and interested in creating more interesting scenarios and roleplay than an observer coming out of the woodwork, no offense.

**Comment by Majkl-J** [comment]
I feel like it would be much better to tune back on the amount of these that spawn, or make them more minor. Probably not the way to do this.

We already kinda fought back observers by making them unable to affect transfervotes, so

**Pull request closed without merging**
