### PR TITLE
Makes all clothing renamable and redescribable with pens

### PR DESCRIPTION
**Pull request by xPokee**
## About The Pull Request
Does as the title says.
## Why It's Good For The Game
It adds for more ability to customize things in-game.
## Proof Of Testing
See the attached images.
<details>
<summary>Screenshots/Videos</summary>

image

</details>

## Changelog
:cl:
qol: all clothing can now be renamed with pens
/:cl:

### CODE REVIEW

**Comment by Majkl-J** [comment]
> You currently have a negative Fix/Feature pull request delta of -6. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

Why is this on when did we turn it on

**Comment by MajManatee** [comment]
Is this not already doable with a pen on most objects? Or through the loadout menu?

**Comment by YakumoChen** [comment]
This is going to make it extremely hard to identify what weapons people are using, especially guns. Often all you will have to identify a gun is a few pixels on the inhand otherwise. This will be Especially bad for ballistic guns which do not have high-visibility projectiles.

**Comment by YakumoChen** [comment]
This will also let people rename real melee items like eswords as "toy esword" which raises all sorts of alarms.

**Comment by YakumoChen** [comment]
> Is this not already doable with a pen on most objects? Or through the loadout menu?

Given loadout item selections are intentionally designed to not cause balance concerns, this is the only time it is generally acceptable

**Comment by lessthnthree** [comment]
You already have a label maker if you want to add a cosmetic name to something.

**Comment by Fn-OS** [comment]
I don't see a problem with this. If someone renames a gun or weapon to be misleading, I feel like that'd fall under the bad faith rule and would be Ahelp-able. I'd like to see this in-game.

**Comment by lessthnthree** [comment]
image

**Comment by Fn-OS** [comment]
> image

Oh. I see why that'd be a bad idea then

Maybe there's a way to add the previous name of the item to the logs?

**Comment by lessthnthree** [comment]
If so, it would be required to include in the PR to ensure that all logs are created with the item's actual name where appropriate.

**Comment by SapphoQueer** [comment]
Cool idea on paper, incredibly abusable in reality.

**Comment by MajManatee** [comment]
Hand labelers already allow this with all these issues solved.

**Review by Majkl-J — APPROVED** [review]

**Comment by Majkl-J** [comment]
Do mind that only loadout renames allow extended examines to show up

**Comment by YakumoChen** [comment]
This should only apply to loadout clothing, which already is renameable making this PR not useful

As a reminder clothing includes armour, modsuits, radios, etc

**Comment by lessthnthree** [comment]
Do the /obj/item/ have any var that indicates they're a loadout item? Could restrict the renaming based on that.

If it doesn't exist, maybe it can be done, then the PR can make all loadout items functional like that, not just clothing.

**Review by lessthnthree — DISMISSED** [review]
Instead of adding UNIQUE_RENAME to the typepath, change the code that spawns the loadout items to add UNIQUE_RENAME to the item when its spawned.

**Comment by YakumoChen** [comment]
image
It's already all renameable

**Pull request merged**
