### PR TITLE
[Fixes Modularity] Removes ballistic weapons from command, gives proper eguns

### PR DESCRIPTION
**Pull request by ReturnToZender**
## About The Pull Request
Brings some command roles back in line with modern TG.

## Changelog

:cl:
Del: QM's sports rifle
Del: Captain's Osprey
Del: NT Rep's pistol
Add: Captain e_gun
Add: NT Rep e_gun
/:cl:

### CODE REVIEW

**Comment by zeroisthebiggay** [comment]
i support it but i will weep for the osprey's death because i fucking love the captain just getting a comically large capital g **G**un to shoot people that they don't like

while you're at it delete the hos' armament selection beacon please because they still inexplicably get the choice of three variations of gat all of which being of varying power levels and ability to cause ruptured cavities in two shots

**Comment by Detective-Google** [comment]
basically what zero said, my only concern is that right now ballistics are so meta that this makes the captain a much easier target, since most deaths come from blood loss rather than actual damage

**Comment by zeroisthebiggay** [comment]
> basically what zero said, my only concern is that right now ballistics are so meta that this makes the captain a much easier target, since most deaths come from blood loss rather than actual damage

can someone tell me if the crazy bloodloss is a tg thing or a skyrat thing

**Comment by RuneQuesteER** [comment]
> > basically what zero said, my only concern is that right now ballistics are so meta that this makes the captain a much easier target, since most deaths come from blood loss rather than actual damage
> 
> can someone tell me if the crazy bloodloss is a tg thing or a skyrat thing

its likely TG, since TG introduced wounds, and piercing/slash wounds are incredibly lethal cause of the blood loss

**Comment by zeroisthebiggay** [comment]
@ReturnToZender you forgot to actually get rid of the nt rep's pistol because they still have it

**Comment by Zirok-BYOND** [comment]
Honestly I like this, this is nice flavour. It should be flavour though, if these weapons are very strong then I would appreciate nerfs. But I don't think we should just remove them!

**Comment by ReturnToZender** [comment]
> @ReturnToZender you forgot to actually get rid of the nt rep's pistol because they still have it

This is because certain admins are spawning it in for themselves :)

**Comment by projectkepler-ru** [comment]
While I'm pretty heart broken to see the gun go away, the direction bubberstation is taking is not one that requires them anymore.

**Review by projectkepler-ru — APPROVED** [review]
Cargo can just order guns if they realy need it so this isn't a huge loss

**Review by BurgerLUA — APPROVED** [review]
Code looks good.

**Comment by nevimer** [comment]
cherry pick the relevant commits into a new branch

**Pull request closed without merging**
