### PR TITLE
Storyteller vote reminder

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request

Since the title screen covers the active vote status icon, provides a second vote notification to latejoiners who may have joined after the first notification.

## Why It's Good For The Game

People stop going "Did I miss the storyteller vote?" / "I just got here, how do I vote in storyteller???"

## Proof Of Testing

image

## Changelog

:cl: LT3
qol: New vote reminder notification, enabled for storyteller votes
/:cl:

### CODE REVIEW

**Comment by StrangeWeirdKitten** [comment]
Based, obv just fix CI :)

**Comment by theselfish** [comment]
I'd probably make the text bigger.

But great PR yeah.

**Comment by ReturnToZender** [comment]
Hey, a miner gripe I had, resolved, thanks

**Comment by lessthnthree** [comment]
> I'd probably make the text bigger.
> 
> But great PR yeah.

Increased it a bit.

**Pull request merged**
