### PR TITLE
Adds winter coats to command vendor

### PR DESCRIPTION
**Pull request by Erol509**
## About The Pull Request

In the PR name

## Why It's Good For The Game
 Winter coats are very nice, I love them...Dont strip me from replacements
## Changelog

:cl:
add: Added winter coats to command vendor

/:cl:

### CODE REVIEW

**Review by Majkl-J — CHANGES_REQUESTED** [review]
Can be modular, example snippet that should work:

```
/obj/machinery/vending/access/command/build_access_list(list/access_lists)
	. = ..()
	access_lists["[ACCESS_HOP]"] |= list(/obj/item/clothing/suit/hooded/wintercoat/hop = 1,)
	access_lists["[ACCESS_CMO]"] |= list(/obj/item/clothing/suit/hooded/wintercoat/medical/cmo = 1,)
```

**Comment by Erol509** [comment]
> Can be modular, example snippet that should work:
> 
> ```
> /obj/machinery/vending/access/command/build_access_list(list/access_lists)
> 	. = ..()
> 	access_lists["[ACCESS_HOP]"] |= list(/obj/item/clothing/suit/hooded/wintercoat/hop = 1,)
> 	access_lists["[ACCESS_CMO]"] |= list(/obj/item/clothing/suit/hooded/wintercoat/medical/cmo = 1,)
> ```

I tried it...It doesnt work...it will replace all items in the vendor with only single winter coat

**Comment by Majkl-J** [comment]
> I tried it...It doesnt work...it will replace all items in the vendor with only single winter coat removing everything else It was modular at first....on separate file, but it just doesnt work and remove everything else in vendor

Did you remember to call parent? Seems weird for it to just wipe

**Comment by Erol509** [comment]
> > I tried it...It doesnt work...it will replace all items in the vendor with only single winter coat removing everything else It was modular at first....on separate file, but it just doesnt work and remove everything else in vendor
> 
> Did you remember to call parent? Seems weird for it to just wipe

didnt use ..(), maybe its the fault

**Comment by Majkl-J** [comment]
> > > I tried it...It doesnt work...it will replace all items in the vendor with only single winter coat removing everything else It was modular at first....on separate file, but it just doesnt work and remove everything else in vendor
> > 
> > 
> > Did you remember to call parent? Seems weird for it to just wipe
> 
> didnt use ..(), maybe its the fault

Yea that's probably it, you need to call parent for it to work!

**Pull request closed without merging**
