### PR TITLE
Revert "Revert 1858 clownborg"

### PR DESCRIPTION
**Pull request by theselfish**
Reverts Bubberstation/Bubberstation#1873

There is still no stated reason this sprite should stay.

Purposefully bad is not an excuse.

This is an affront to clowning and should remain removed until someone wants to actually sprite a better clownborg that's shaped like a dog. 

It barely even looks like a Clown, it doesn't use the clown palette, it has no Clown shoes, no Giggles von Honkers and no Clown wig.

### CODE REVIEW

**Comment by Odairu** [comment]
So make one yourself and replace it rather than just removing it.
Every clown birg sprite is pretty bad, yet you're 9nly going after the dogborg one 🤔

**Comment by theselfish** [comment]
> So make one yourself and replace it rather than just removing it. Every clown birg sprite is pretty bad, yet you're 9nly going after the dogborg one 🤔

This is just straight up false. Here are, to my knowledge, the two other clownborgs.
image
image
These are good sprites.
This.
353572044-5a0f651d-33ce-43f7-a94b-352d61646aa3
Is not.

**Comment by Odairu** [comment]
> > So make one yourself and replace it rather than just removing it. Every clown birg sprite is pretty bad, yet you're 9nly going after the dogborg one 🤔
> 
> This is just straight up false. Here are, to my knowledge, the two other clownborgs. image image These are good sprites. This. 353572044-5a0f651d-33ce-43f7-a94b-352d61646aa3 Is not.

Theres 2 others

**Comment by Iamgoofball** [comment]
Also, why was this PR speedmerged while locked? This is ridiculous. If the vore guys can put the elbow grease in to make sure their code and sprites are good and work and fit the codebase standards, the dogborg people sure as hell can put the elbow grease in.

**Review by projectkepler-ru — COMMENTED** [review]
I should've made it more clear, I merged the removal since at the time I planned to legitimately get a new sprite within the next 3-4 months as I figured "Nah not enough people play this thing anyway for anyone to notice it's gone"

After the backlash it was pretty clear that even if it was not even being played there were very vocal people wanting it to stay so it tended upbeing that the revert was done while the details are figured out. I locked the conversation on both accord as to move the flak away from the staff.

**Comment by theselfish** [comment]
> I should've made it more clear, I merged the removal since at the time I planned to legitimately get a new sprite within the next 3-4 months as I figured "Nah not enough people play this thing anyway for anyone to notice it's gone"
> 
> After the backlash it was pretty clear that even if it was not even being played there were very vocal people wanting it to stay so it tended upbeing that the revert was done while the details are figured out. I locked the conversation on both accord as to move the flak away from the staff.

If this sprite were shaped like a worm, rat, spider or dalek no one would have cared.
The only reason there was backlash was because some people can't handle being ugly dog robot models.

I don't like Dogborgs, I admit that. Even I can admit though, the 'K9' or whatever it's called type looks good as a sprite. I still think the movement states are stupid because nothing else in this game has such large, visible movement sprites but I can admit 'that's a good sprite'.

The 'Vale' (??? That name makes no sense, it's not latin for dog, it's not a landmass, it's not a reference to ASoIaF) models are ugly as a whole. They're ancient sprites we've carried around like an unwanted child for some 'unknown' reason. But even compared to the regular Vale, the Clownborg is ugly as sin, it's, like goof said, an afront to Clowning, it doesn't use the pallet of a Clown nor does it really LOOK like a Clown. 
There's no bright yellow on the Clown's trousers. It has no shoes nor bag, the 'facepaint' looks more like a skull than a clown's facepaint.

Quite frankly, for how little Clownborgs are seen (which should be zero if you ask me, Clownborgs have the issue that Janitor Borgs had), we can survive not having a fetish robot for one single module.

**Comment by StrangeWeirdKitten** [comment]
We're done going back and forward over this.

**Pull request closed without merging**
