### PR TITLE
Saddles, saddlebags, calvary

### PR DESCRIPTION
**Pull request by nikothedude**
## About The Pull Request

Port of https://github.com/NovaSector/NovaSector/pull/3112, which is a continuation of a work I stopped development on

Adds saddles, saddlebags, both of which can only be worn by quadruped taurs in the backslot

Saddles allow taurs to be piggybacked with the rider having both hands free, saddlebags allow riders to have ONE hand free, have sueprior storage, but you can altclick the wearer to access the storage

Saddles can be made from leather, saddles are avaialble in the secvend, and both saddles and saddlebags are in loadout

Part of a taur rework thingy magig I originally made for nova
Main design doc: https://hackmd.io/@NikoTheGuyDUde/rJ7C9HPe0
Quadruped design doc: https://hackmd.io/@NikoTheGuyDUde/rJzJiBPgC

## Why It's Good For The Game

Read the main design doc. In short, taurs have very exotic anatomy that isnt explored much, and the game would be greatly diversified if we added some mechanical differences.

## Proof Of Testing

<details>
<summary>Screenshots/Videos</summary>

https://github.com/user-attachments/assets/c3a48127-0c54-4b62-a450-e14e210d1f56

</details>

## Changelog

:cl:
add: Quadruped taurs can now wear saddles, which allow anyone to clickdrag themselves onto them to ride with free hands
add: Saddlebags for quadruped taurs, which are one-handed saddles that allow anyone to access their storage by alt clicking the wearer
/:cl:

### CODE REVIEW

**Comment by ReturnToZender** [comment]
Niko you are a treat

**Comment by YakumoChen** [comment]
I don't understand, what is this balanced by? This doesn't even appear to follow the goals of the design doc you created?

**Comment by YakumoChen** [comment]
I looked up the code and found out that this adds the saddles as back-slot items and the difference here is storage and storage availability. That seems a lot more reasonable but I'd appreciate if you'd outlined this in both the PR description and the hackMD

**Comment by YakumoChen** [comment]
Will this also add jousting and bucking off players like borgs do?

**Comment by nikothedude** [comment]
> I looked up the code and found out that this adds the saddles as back-slot items and the difference here is storage and storage availability. That seems a lot more reasonable but I'd appreciate if you'd outlined this in both the PR description and the hackMD

its in the hackmd

**Comment by YakumoChen** [comment]
> > I looked up the code and found out that this adds the saddles as back-slot items and the difference here is storage and storage availability. That seems a lot more reasonable but I'd appreciate if you'd outlined this in both the PR description and the hackMD
> 
> its in the hackmd

the base one probably needs a better link because I followed through and got to this https://hackmd.io/@NikoTheGuyDUde/BJG8uQyGR

**Comment by nikothedude** [comment]
Thats not the one I linked

**Comment by ReturnToZender** [comment]
Can bipeds wear these, like lizards with tailbags and such? Asking for a horse.

**Comment by nikothedude** [comment]
> Can non-taurs wear these, like lizards with tailbags and such? Asking for a horse.

nope

**Comment by YakumoChen** [comment]
> Thats not the one I linked

its linked in the main design doc under the same name, it's confusing!

**Comment by StrangeWeirdKitten** [comment]
This looks submissive and test mergable.

**Review by Majkl-J — CHANGES_REQUESTED** [review]
```
[2024-11-03 00:15:12.428] RUNTIME: runtime error: Cannot read null.body_zone
 - proc name: handle vehicle offsets (/datum/component/riding/creature/human/handle_vehicle_offsets)
 -   source file: modular_zubbers/code/datums/components/datums/riding_mob.dm,32
 -   usr: Idris Valentine (/mob/living/carbon/human)
 -   src: /datum/component/riding/creatu... (/datum/component/riding/creature/human)
 -   usr.loc: the plating (135,140,4) (/turf/open/floor/plating)
 -   call stack:
 - /datum/component/riding/creatu... (/datum/component/riding/creature/human): handle vehicle offsets(1)
 - /datum/component/riding/creatu... (/datum/component/riding/creature/human): vehicle moved(Idris Valentine (/mob/living/carbon/human), the plating (135,139,4) (/turf/open/floor/plating), 1, 0, null, 1)
 - Idris Valentine (/mob/living/carbon/human):  SendSignal("movable_moved", /list (/list))
 - Idris Valentine (/mob/living/carbon/human): Moved(the plating (135,139,4) (/turf/open/floor/plating), 1, 0, null, 1)
 - Idris Valentine (/mob/living/carbon/human): Moved(the plating (135,139,4) (/turf/open/floor/plating), 1, 0, null, 1)
 - Idris Valentine (/mob/living/carbon/human): Move(the plating (135,140,4) (/turf/open/floor/plating), 1, 0, 1)
 - Idris Valentine (/mob/living/carbon/human): Move(the plating (135,140,4) (/turf/open/floor/plating), 1, 0, 1)
 - Idris Valentine (/mob/living/carbon/human): Move(the plating (135,140,4) (/turf/open/floor/plating), 1, null)
 - Idris Valentine (/mob/living/carbon/human): Move(the plating (135,140,4) (/turf/open/floor/plating), 1)
 - Idris Valentine (/mob/living/carbon/human): Move(the plating (135,140,4) (/turf/open/floor/plating), 1)
 - ...
 - Idris Valentine (/mob/living/carbon/human): Move(the plating (134,140,4) (/turf/open/floor/plating), 9, null)
 - Idris Valentine (/mob/living/carbon/human): Move(the plating (134,140,4) (/turf/open/floor/plating), 9)
 - Idris Valentine (/mob/living/carbon/human): Move(the plating (134,140,4) (/turf/open/floor/plating), 9)
 - Idris Valentine (/mob/living/carbon/human): Move(the plating (134,140,4) (/turf/open/floor/plating), 9)
 - Idris Valentine (/mob/living/carbon/human): Move(the plating (134,140,4) (/turf/open/floor/plating), 9)
 - Idris Valentine (/mob/living/carbon/human): Move(the plating (134,140,4) (/turf/open/floor/plating), 9)
 - Idris Valentine (/mob/living/carbon/human): keyLoop(Diesel0 (/client))
 - Input (/datum/controller/subsystem/verb_manager/input): ignite(0)
 - Master (/datum/controller/master): Loop(2)
 - Master (/datum/controller/master): StartProcessing(0)
 ```

**Comment by nikothedude** [comment]
> ```
> [2024-11-03 00:15:12.428] RUNTIME: runtime error: Cannot read null.body_zone
>  - proc name: handle vehicle offsets (/datum/component/riding/creature/human/handle_vehicle_offsets)
>  -   source file: modular_zubbers/code/datums/components/datums/riding_mob.dm,32
>  -   usr: Idris Valentine (/mob/living/carbon/human)
>  -   src: /datum/component/riding/creatu... (/datum/component/riding/creature/human)
>  -   usr.loc: the plating (135,140,4) (/turf/open/floor/plating)
>  -   call stack:
>  - /datum/component/riding/creatu... (/datum/component/riding/creature/human): handle vehicle offsets(1)
>  - /datum/component/riding/creatu... (/datum/component/riding/creature/human): vehicle moved(Idris Valentine (/mob/living/carbon/human), the plating (135,139,4) (/turf/open/floor/plating), 1, 0, null, 1)
>  - Idris Valentine (/mob/living/carbon/human):  SendSignal("movable_moved", /list (/list))
>  - Idris Valentine (/mob/living/carbon/human): Moved(the plating (135,139,4) (/turf/open/floor/plating), 1, 0, null, 1)
>  - Idris Valentine (/mob/living/carbon/human): Moved(the plating (135,139,4) (/turf/open/floor/plating), 1, 0, null, 1)
>  - Idris Valentine (/mob/living/carbon/human): Move(the plating (135,140,4) (/turf/open/floor/plating), 1, 0, 1)
>  - Idris Valentine (/mob/living/carbon/human): Move(the plating (135,140,4) (/turf/open/floor/plating), 1, 0, 1)
>  - Idris Valentine (/mob/living/carbon/human): Move(the plating (135,140,4) (/turf/open/floor/plating), 1, null)
>  - Idris Valentine (/mob/living/carbon/human): Move(the plating (135,140,4) (/turf/open/floor/plating), 1)
>  - Idris Valentine (/mob/living/carbon/human): Move(the plating (135,140,4) (/turf/open/floor/plating), 1)
>  - ...
>  - Idris Valentine (/mob/living/carbon/human): Move(the plating (134,140,4) (/turf/open/floor/plating), 9, null)
>  - Idris Valentine (/mob/living/carbon/human): Move(the plating (134,140,4) (/turf/open/floor/plating), 9)
>  - Idris Valentine (/mob/living/carbon/human): Move(the plating (134,140,4) (/turf/open/floor/plating), 9)
>  - Idris Valentine (/mob/living/carbon/human): Move(the plating (134,140,4) (/turf/open/floor/plating), 9)
>  - Idris Valentine (/mob/living/carbon/human): Move(the plating (134,140,4) (/turf/open/floor/plating), 9)
>  - Idris Valentine (/mob/living/carbon/human): Move(the plating (134,140,4) (/turf/open/floor/plating), 9)
>  - Idris Valentine (/mob/living/carbon/human): keyLoop(Diesel0 (/client))
>  - Input (/datum/controller/subsystem/verb_manager/input): ignite(0)
>  - Master (/datum/controller/master): Loop(2)
>  - Master (/datum/controller/master): StartProcessing(0)
> ```

this isnt actually saddlebag code doing this

**Comment by StrangeWeirdKitten** [comment]
image

This is a little offset when riding. For comparasion, Bellow is piggy backing normally (which better aligns)

image

**Comment by Strazyplus** [comment]
this is awesome, I hope nagas get saddlebags soon.

**Comment by nikothedude** [comment]
> image
> 
> This is a little offset when riding. For comparasion, Bellow is piggy backing normally (which better aligns)
> 
> image

Intentional, I feel it better respresents someone actually sitting on the taur

**Comment by Rykka-Stormheart** [comment]
Hi! A couple bugs, as a taur enjoyer here;

- When playing as a vampire, saddlebags will get dropped off of you while you sleep, and remain "invisible" in the back slot until you pick them up from the ground and drop them.
- This happens also if you're rejuved, etc. something to do with organ code refreshes if I had to guess.
- Semi-related: When removing saddlebags from yourself, sometimes they'll just end up blank on your back and you have to do the whole pickup and drop again.


- Also, saddlebags will frequently get stuck if something removes them from you by force or otherwise. For example, I was, again, vampire, was stunned, stripped, and such, but when I got up and fled, using masquerade, I noticed I didn't have my bags on sprite. I checked, they were accessible via alt clicking myself, but otherwise functionally not there. An admin forcibly stripped all items, and they still didn't show up on the ground or in hand, and the back slot was just invisible. It took the admin in question deleting the item entirely in order for my back slot to finally clear and allow me to use other items.

The most annoying bug is mostly the saddlebags getting dropped every time you go into your coffin to sleep.

**Comment by Strazyplus** [comment]
Changes & feature wish-list: if you need a spriter to help, I am willing to help commission it.
Nagatuar tailbag & saddles.
Change/improve the saddle & saddlebags dropped sprite so its easier to see / click on.

**Comment by nikothedude** [comment]
sorry for how inactive ive been here, hyperfocusing on a starsector mod

ill probably make some time soon

**Review by StrangeWeirdKitten — CHANGES_REQUESTED** [review]
Can you make it so when the taur unequips the saddle bag, it'll drop the person. That doesn't happen.

**Comment by nikothedude** [comment]
Alright, I know I said this last time but I swear ill get on this in the next few days

I have basically stopped playing on bubber but I dont like leaving projects unfinished

**Comment by nikothedude** [comment]
after finals week i'll see about the bugs and requested features, but i really doubt ill be able to replicate the bugs

**Comment by StrangeWeirdKitten** [comment]
There just needs to be something that when it's unequipped, it'll drop the person riding them.

**Comment by nikothedude** [comment]
hey turns out i completely forgot about this but if it isnt clear im done with bubber 

if someone wants to continue this be my guest, its functional aside from a few bugs

**Comment by nikothedude** [comment]
closing just because im not working on it anymore

**Comment by Strazyplus** [comment]
noooooooo.....

**Comment by nikothedude** [comment]
known bugs
1. being revived as a heretic thrall (and other things) cause the bags to wig out and like. stuck in your hand or something. i forgot the exact bug
2. unequpping saddles do not kick off riders
3. ghosts can alt click saddlebag users for silliness
4. needs better inhand sprites

again i give up ownership of this to anyone who wants to continue it

**Pull request merged**
