### PR TITLE
(NON-MODULAR) Salt PR

### PR DESCRIPTION
**Pull request by Kilmented**
## About The Pull Request
Adds a heft penalty to the Deagle's duel wielding ability, it's a 60 damage gun, if you had two you could essentially one click everyone without armor and anyone with armor wouldn't post much of a threat either. That's like having two Mosins, one for each hand.

Also, fixes a gripe I have had with cigarettes for the LONGEST time. 

## Testing
I have personally tested the cigar(ette) changes, they work as intended. Even the healing the lungs bit. 
I have not personally tested the Deagle changes, but I see no reason why it shouldn't work.

### CODE REVIEW

**Comment by yourdoom9898** [comment]
Cigarette changes are pretty cook. TIL that the cigarettes produced by the industrial black extract have Krokidil in them.

**Comment by Serxule** [comment]
i dont see why krokodil cigs would heal lungs ngl

**Comment by Serxule** [comment]
> Who ARE you?? You're not in the discord or anything... image

cause im not in the discord, and im taking a break from the serb

**Comment by yourdoom9898** [comment]
> i dont see why krokodil cigs would heal lungs ngl

They're already healing with the regen jelly in them, and are inherently "slime magic shit" with a crossbred core. It's easily one of xenobiology's many "just don't think about it" moments.

**Comment by Serxule** [comment]
> > i dont see why krokodil cigs would heal lungs ngl
> 
> They're already healing with the regen jelly in them, and are inherently "slime magic shit" with a crossbred core. It's easily one of xenobiology's many "just don't think about it" moments.

oh that makes more sense, thought it was only krokodil

**Comment by Zirok-BYOND** [comment]
>60 damage
Wew, but upon checking the .357 has the same. Feel free to nerf any aspect of this weapon, especially if it's less accessible than the .357 which
a) is very loud
b) Has very limited ammo (Until you get to an autolathe, anyways, but even then the magazine capacity sucks)
c) Can only be obtained by traitors.

Nuke ops weapons are a separate thing and need to be very, very powerful since nukies are expected to be massively outnumbered

**Comment by Nicolai904** [comment]
make the prs split tbh making a salt pr with some other change is not that great also i would not nerf the deagle its a weapon that has no way of getting ammo back and mostly admin only unless you are lucky and get it from the safe in the vault which gives you singular deagle

**Comment by Zirok-BYOND** [comment]
Do these modular please

**Pull request closed without merging**
