### PR TITLE
Shadekin

### PR DESCRIPTION
**Pull request by NullDagaf**
## Changelog

:cl:
add: added shadekin
/:cl:

### CODE REVIEW

**Comment by NullDagaf** [comment]
Still testing.

**Comment by NullDagaf** [comment]
Q6ojz15P6D
Works.

**Comment by NullDagaf** [comment]
Doesn't work.

**Comment by NullDagaf** [comment]
Works. I think.

**Comment by projectkepler-ru** [comment]
what the hell is this shit @ReturnToZender  and why do you want it

**Comment by ReturnToZender** [comment]
> Works. I think.

Doesn't work, testmerged it and it doesn't show up in the customization menu.

**Pull request merged**
