### PR TITLE
Public Logging

### PR DESCRIPTION
**Pull request by nevimer**
## About The Pull Request

Gives the players a redacted version of the logs, ckeys filtered out for public logging purposes. 

## Why It's Good For The Game

You can prove your cases in ahelps and appeals, reports, easier. 

## Proof Of Testing

notepad_SbY9NX8Shd

## Changelog

:cl:
admin: added public log folder, and logging. 
/:cl:

### CODE REVIEW

**Comment by Tk420634** [comment]
Imagine having admins and staff so unreliable and shitty that you have to resort to players needing to do this instead of trusting the people you have in place to pull logs.  😆

**Comment by ReturnToZender** [comment]
> Imagine having admins and staff so unreliable and shitty that you have to resort to players needing to do this instead of trusting the people you have in place to pull logs. 😆

We recognize that there are issues within our team and we are trying our best to resolve them. That being said this is not a place that you should use to talk about staff members in this kind of manner. If you have issues, you can make a staff complaint [here](https://discord.com/channels/1059199070016655462/1063719364970414170)

**Comment by nevimer** [comment]
> Imagine having admins and staff so unreliable and shitty that you have to resort to players needing to do this instead of trusting the people you have in place to pull logs. 😆

We like tgstation's public logging, and have wanted a special filtered version for our code base for a long while.
For example: https://tgstation13.org/parsed-logs/

**Comment by nevimer** [comment]
> > > Imagine having admins and staff so unreliable and shitty that you have to resort to players needing to do this instead of trusting the people you have in place to pull logs. 😆
> > 
> > 
> > We recognize that there are issues within our team and we are trying our best to resolve them. That being said this is not a place that you should use to talk about staff members in this kind of manner. If you have issues, you can make a staff complaint [here](https://discord.com/channels/1059199070016655462/1063719364970414170) on our Discord.
> 
> Tell your admins to not try and bully folks for having points of view. What a joke.

This is the GitHub, a site for code discussion. Please direct your grievances to the proper location. We appreciate your concerns and would like to address them at the proper discussion mediums. 

Thank you!

**Comment by projectkepler-ru** [comment]
> Imagine having admins and staff so unreliable and shitty that you have to resort to players needing to do this instead of trusting the people you have in place to pull logs. 😆

Bold fucking statement coming from you sir

**Comment by AffectedArc07** [comment]
See, if thought was put into this PR over agenda, you'd have known that TG's public logs are generated by a tool on their github, https://github.com/tgstation/tgstation13.org/blob/master/public_log_parser.php

Having the game make extra sets of logs is overhead no one needs, especially when it can be done out of process, and is a lot simpler to maintain in the future.

**Comment by nevimer** [comment]
> Use https://github.com/tgstation/tgstation13.org/blob/master/public_log_parser.php
> 
> You're a modular codebase, you need simplicity, this many edits is a disaster, mainly due to maintainability and performance. Out of repo solutions are always better for this.

I mean, I agree, but the solution you are pointing at literally is giving you reasons not to use it in a comment on the first lines. I'm not exactly keen to try to figure out that, when I can edit some TG files that get updated once every four years on days with a solar eclipse. 

Passing a single argument down on a few procs... I'd argue this is much simpler. Unless you plan to ship me your environment and maintain it, a self-described unmaintained and poorly document PHP script is worse. 

The easy of resolving git conflicts and build errors FAR surpasses the ease of maintaining decrepit undocumented PHP scripts, especially with version deprecation. Most of this activity here on that script is from MSO 7 years ago. I'm not going to install PHP 5.6, or fight to keep it working on a recent PHP version. Work smarter, not harder.  

The time investment of resolving any future issues with this is far less anything else. We already have extensive nonmodular edits and resolving such issues is at worst a 20-40 minute investment per month. 

I appreciate your insight, but for those reasons I'm not really willing to try that script.

**Comment by Cyprex** [comment]
> Imagine having admins and staff so unreliable and shitty that you have to resort to players needing to do this instead of trusting the people you have in place to pull logs. 😆

You are making this comment on a PR intended to increase accountability. I also want to highlight here that Coyote Bayou does not allow players to view their own notes(Viewing your own notes is a feature present across seemingly all tgstation-derived codebases- tgstation values transparency/accountability very highly, I assume it originates there). Coyote Bayou is the only server that I am aware of that does not let players view their own notes(That's me speaking personally- I know tgstation/skyrat/nova/Bubber/Citadel/Splurt do! No idea about other servers!)

**Pull request merged**
