### PR TITLE
(FINALLY) Replaces the leaves sprite on biodome

### PR DESCRIPTION
**Pull request by Maia-J**
## About The Pull Request

Originally when biodome dropped I was very opposed to it due to these ugly things

image

I was unable to block it then, nor did I know how to sprite to fix it. Then once I learned some spriting I got bored and forgot about it.

Well not anymore
image
## Why It's Good For The Game

It looks way better than what we had before
## Proof Of Testing

See above

## Changelog
:cl:
image: Prettified the biodome leaves sprite
/:cl:

### CODE REVIEW

**Comment by IgiariValkyr** [comment]
Leaves? Holy shit I thought they were like. A decorative garland or curtain or something. Not leaves. 🤯

**Review by Arturlang — APPROVED** [review]
Better than before, would be awesome to have variations, but that's annoying to do anyway

**Comment by StrangeWeirdKitten** [comment]
wow everything biodome my brain sort of supressed. Especially this... I'm going to try forgetting I saw those.

**Comment by Majkl-J** [comment]
> Better than before, would be awesome to have variations, but that's annoying to do anyway

If our wall rework actually finishes then I'll work on proper iconcuttered sprites

**Pull request merged**
