### PR TITLE
Adds an ERT name preference

### PR DESCRIPTION
**Pull request by ReturnToZender**
## About The Pull Request
This PR allows you to control your name when spawning as an ERT without randomized names. Ever wanted your own Emergency Response OC? Now you can make one.

## Why It's Good For The Game
More customization = Good. Also check out the examples.

## Proof Of Testing
image
image
image

## Changelog

:cl: ReturnToZender
add: You can now control what your name is, when you spawn as an ERT.
/:cl:

### CODE REVIEW

**Review by Swiftfeather — CHANGES_REQUESTED** [review]
I think this should be a button an admin can choose to enable on the ERT creation screen. Sometimes it's good to have anonymized ERTs.

**Comment by ReturnToZender** [comment]
> I think this should be a button an admin can choose to enable on the ERT creation screen. Sometimes it's good to have anonymized ERTs.

I will test this with the randomized name preference and make sure it works in that context, if not I'll fix it

**Comment by ReturnToZender** [comment]
> > I think this should be a button an admin can choose to enable on the ERT creation screen. Sometimes it's good to have anonymized ERTs.
> 
> I will test this with the randomized name preference and make sure it works in that context, if not I'll fix it

It does still work properly

**Comment by ReturnToZender** [comment]
Ready for merge ^^

**Pull request merged**
